/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.GenusCharacter
public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Relative.Ramification
public import TauCeti.NumberTheory.NumberField.Ideal.ArtinMap
public import TauCeti.NumberTheory.NumberField.ResidueDegree
import TauCeti.Algebra.BigOperators.Finset.Erase
import TauCeti.NumberTheory.NumberField.Frobenius.Tower
import TauCeti.NumberTheory.Multiquadratic.Quadratic.GenusCharacter.NarrowClassGroup
import TauCeti.NumberTheory.Multiquadratic.Legendre.PrimeDiscriminant.Frobenius

/-!
# The genus-field isomorphism on Artin symbols

For a squarefree nonsquare integer \(d\), the candidate genus field is an unramified abelian
extension of its embedded quadratic base \(K = \mathbb{Q}(\sqrt d)\). The isomorphism

\[
  \operatorname{Gal}(K_{\mathrm{gen}}/K) \cong \mathrm{Cl}^+(K)/\mathrm{Cl}^+(K)^2
\]

constructed from sign patterns and genus characters agrees with the inverse Artin map on every
degree-one prime above a rational prime, including primes dividing the discriminant. Namely, the
Frobenius at such a prime is sent to the elementary-2 class of that prime. At the prime `2`,
Frobenius acts on `√P` through the congruence class of `P` modulo `8` when `2 ∤ P`, which is the
value at `2` of the character of the prime discriminant `P`; when `2 ∣ P`, the remaining coordinate
is determined by the parity condition.

This module first exposes the local compatibility between relative Frobenius elements and
singleton genus characters: the corresponding quadratic character value agrees on every
nondivisible prime discriminant. When one prime discriminant is divisible by the rational prime,
its coordinate is instead recovered from the parity relation. Consequently, the sign-pattern
isomorphism identifies Frobenius and Artin elements with the elementary-2 narrow ideal classes of
the primes below them.

That local statement is then extended over every prime and multiplied out along the factorization
of an ideal, which gives the global identity

`Φ (Art I) = [I] ∈ Cl⁺(K)/Cl⁺(K)²`

on the group of invertible fractional ideals of multiplicity zero along any finite excluded set.
The remaining prime to handle in the local argument is the inert one, where both sides are trivial:
an inert prime is generated by the totally positive rational integer below it, while the relative
Frobenius is trivial because the absolute Frobenius is an involution and the base residue field
already has
`q ^ 2` elements. Since the sign-pattern isomorphism is a bijection, the Artin map is exactly as
surjective as the narrow class map, and its kernel is exactly the ideals of square narrow class.

The classical account is in D. A. Cox, *Primes of the Form x² + ny²*, §6.A, and F. Lemmermeyer,
*Reciprocity Laws: From Euler to Eisenstein*, §2.2.

## Main definitions

* `TauCeti.Multiquadratic.genusFieldArtinExcludedPrimes`: the primes of the quadratic base whose
  residue characteristic divides the discriminant, the canonical set the Artin map is taken
  away from.

## Main results

* `TauCeti.Multiquadratic.autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius`:
  the genus-field isomorphism sends a relative Frobenius at a degree-one prime to its class,
  including when the rational prime divides the discriminant.
* `TauCeti.Multiquadratic.autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinElement`:
  the same statement for the canonical Artin automorphism.
* `…_frobenius_at_prime`: the same statement at every prime, of degree one or not.
* `TauCeti.Multiquadratic.autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway`:
  the genus-field isomorphism carries the ideal-theoretic Artin map to the narrow elementary-`2`
  ideal class, and `…_artinHomAway_excludedPrimes` is its canonical instance.
* `TauCeti.Multiquadratic.artinHomAway_candidateGenusField_eq_one_iff`: the Artin automorphism of
  an ideal is trivial exactly when its narrow class is a square.
* `TauCeti.Multiquadratic.artinHomAwayIntegral_candidateGenusField_surjective`: every automorphism
  of `K_gen` over `K` is the Artin automorphism of an integral ideal prime to the discriminant;
  `…artinHomAway_candidateGenusField_surjective` is the corresponding fractional-ideal statement.
-/

public section

open NumberField
open scoped IsMulCommutative NumberField nonZeroDivisors

namespace TauCeti.Multiquadratic

variable {d : ℤ}

/-- At a degree-one prime above a rational prime `q`, the Frobenius sign on a
prime-discriminant generator agrees with the corresponding genus character whenever `q` does
not divide that prime discriminant. Other prime discriminants may be divisible by `q`. -/
theorem candidateGenusFieldRelativeSignPattern_frobenius_eq_genusChar
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    {q : ℕ} [Fact q.Prime]
    (qIdeal : Ideal (𝓞 (candidateGenusFieldBase hd)))
    (hnorm : Ideal.absNorm qIdeal = q)
    (Q : Ideal (𝓞 (candidateGenusField hd))) [Q.LiesOver qIdeal]
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (hσ : IsArithFrobAt (𝓞 (candidateGenusFieldBase hd)) σ Q)
    (P : {P // P ∈ genusPrimeDiscriminants hd}) (hqP : ¬ (q : ℤ) ∣ P.val) :
    candidateGenusFieldRelativeSignPattern hd σ P =
      candidateGenusFieldBaseGenusCharLinearMap hd hnsq
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk0
            ⟨qIdeal, by
              rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors, hnorm]
              exact (Fact.out : q.Prime).ne_zero⟩)) P := by
  have hqIdeal : qIdeal ∈ (Ideal (𝓞 (candidateGenusFieldBase hd)))⁰ := by
    rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors, hnorm]
    exact (Fact.out : q.Prime).ne_zero
  have hprimeNorm : (Ideal.absNorm qIdeal).Prime := hnorm ▸ Fact.out
  let _ : qIdeal.IsPrime := Ideal.isPrime_of_irreducible_absNorm hprimeNorm
  let _ : qIdeal.LiesOver (Ideal.span {(q : ℤ)}) := ⟨by
    simpa [hnorm, Ideal.under_def] using
      Ideal.span_singleton_absNorm (I := qIdeal) hprimeNorm⟩
  let _ : Q.LiesOver (Ideal.span {(q : ℤ)}) :=
    Ideal.LiesOver.trans Q qIdeal (Ideal.span {(q : ℤ)})
  have hσint : IsArithFrobAt ℤ (σ.restrictScalars ℚ) Q :=
    NumberField.isArithFrobAt_int_of_absNorm_eq qIdeal hnorm Q hσ
  let u : ℤˣ :=
    genusCharFunNarrowClassGroupHom
      (genusPrimeDiscriminants_spec hd).1 (genusPrimeDiscriminants_spec hd).2.1
      (genusPrimeDiscriminants_spec hd).2.2
      (minpoly_candidateGenusFieldBaseGen hd hnsq)
      (adjoin_candidateGenusFieldBaseGen_eq_top hd) hd
      (Finset.singleton_subset_iff.mpr P.property)
      (NarrowClassGroup.mk0 ⟨qIdeal, hqIdeal⟩)
  rw [candidateGenusFieldBaseGenusCharLinearMap_apply,
    genusCharFunElementaryTwoQuotientFamilyLinearMap_apply,
    genusCharFunElementaryTwoQuotientLinearMap_mk,
    candidateGenusFieldRelativeSignPattern_apply,
    TauCeti.additiveIntUnitsLinearEquiv_apply]
  -- The two sign encodings are definitionally if-expressions; name the genus-character unit
  -- above so their equality reduces to equivalence of their respective fixed-sign tests.
  change (if σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P then 0 else 1) =
    if u = 1 then 0 else 1
  have hroot : candidateGenusFieldGen hd P ^ 2 =
      algebraMap ℤ (candidateGenusField hd) (primeDiscriminantRadicand P.val) := by
    rw [candidateGenusFieldGen_sq]
    simp
  have hfix :
      σ (candidateGenusFieldGen hd P) = candidateGenusFieldGen hd P ↔
        primeDiscriminantCharFun P.val q = 1 :=
    isArithFrobAt_apply_sqrt_primeDiscriminantRadicand_eq_self_iff
      ((genusPrimeDiscriminants_spec hd).1 P.val P.property) hqP hroot Q hσint
  have hchar : (u : ℤ) = primeDiscriminantCharFun P.val q := by
    dsimp only [u]
    rw [genusCharFunNarrowClassGroupHom_mk0_eq_primeDiscriminantCharFun_absNorm
      (genusPrimeDiscriminants_spec hd).1 (genusPrimeDiscriminants_spec hd).2.1
      (genusPrimeDiscriminants_spec hd).2.2
      (minpoly_candidateGenusFieldBaseGen hd hnsq)
      (adjoin_candidateGenusFieldBaseGen_eq_top hd) hd qIdeal hqIdeal P.val P.property (by
        rw [hnorm]
        exact (Nat.prime_iff_prime_int.mp Fact.out).coprime_iff_not_dvd.mpr hqP),
      hnorm]
  have hunit :
      u = 1 ↔ primeDiscriminantCharFun P.val q = 1 := by
    rw [← Units.val_eq_one, hchar]
  simp only [hfix, hunit]

/-- **The genus-field isomorphism sends Frobenius to the prime class.**
Let q be a rational prime, let qIdeal be a degree-one prime of K = ℚ(√d) above q, and let Q be
a prime of the candidate genus field above qIdeal.
Every relative arithmetic Frobenius σ at Q is sent by the genus-field isomorphism to the class
of qIdeal in the maximal elementary-2 quotient of the narrow class group. -/
theorem autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    {q : ℕ} [Fact q.Prime]
    (qIdeal : Ideal (𝓞 (candidateGenusFieldBase hd)))
    (hnorm : Ideal.absNorm qIdeal = q)
    (Q : Ideal (𝓞 (candidateGenusField hd))) [Q.LiesOver qIdeal]
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (hσ : IsArithFrobAt (𝓞 (candidateGenusFieldBase hd)) σ Q) :
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq σ =
      Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk0
            ⟨qIdeal, by
              rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors, hnorm]
              exact (Fact.out : q.Prime).ne_zero⟩)) := by
  have hqIdeal : qIdeal ∈ (Ideal (𝓞 (candidateGenusFieldBase hd)))⁰ := by
    rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors, hnorm]
    exact (Fact.out : q.Prime).ne_zero
  let x : candidateGenusFieldRelativeSignSubmodule hd :=
    ⟨candidateGenusFieldRelativeSignPattern hd σ,
      candidateGenusFieldRelativeSignPattern_mem hd σ⟩
  let y := narrowElementaryTwoQuotientEquivRelativeSign hd hnsq
    (TauCeti.elementaryTwoQuotientMk (NarrowClassGroup.mk0 ⟨qIdeal, hqIdeal⟩))
  have hgood (P : {P // P ∈ genusPrimeDiscriminants hd})
      (hP : ¬ (q : ℤ) ∣ P.val) : x.val P = y.val P := by
    rw [narrowElementaryTwoQuotientEquivRelativeSign_apply_coe]
    exact candidateGenusFieldRelativeSignPattern_frobenius_eq_genusChar hd hnsq
      qIdeal hnorm Q σ hσ P hP
  obtain ⟨hs, heven, hprod⟩ := genusPrimeDiscriminants_spec hd
  have hxy : x = y := by
    by_cases hex : ∃ P ∈ genusPrimeDiscriminants hd, (q : ℤ) ∣ P
    · obtain ⟨P₀, hP₀, hdiv₀⟩ := hex
      let P : {P // P ∈ genusPrimeDiscriminants hd} := ⟨P₀, hP₀⟩
      have haway (R : {P // P ∈ genusPrimeDiscriminants hd}) (hne : R ≠ P) :
          x.val R = y.val R := by
        apply hgood R
        intro hdiv
        apply hne
        apply Subtype.ext
        exact injOn_primeDiscriminantPrime hs heven R.property P.property
          (((natCast_dvd_primeDiscriminant_iff (hs R.val R.property) (Fact.out : q.Prime)).mp
            hdiv).symm.trans
            ((natCast_dvd_primeDiscriminant_iff (hs P₀ hP₀) (Fact.out : q.Prime)).mp hdiv₀))
      apply Subtype.ext
      apply eq_of_sum_eq_of_forall_ne x.val y.val _ P haway
      exact (mem_candidateGenusFieldRelativeSignSubmodule_iff hd x.val).mp x.property |>.trans
        ((mem_candidateGenusFieldRelativeSignSubmodule_iff hd y.val).mp y.property).symm
    · apply Subtype.ext
      funext P
      exact hgood P (fun hdiv ↦ hex ⟨P.val, P.property, hdiv⟩)
  have heq := congrArg (narrowElementaryTwoQuotientEquivRelativeSign hd hnsq).symm hxy
  rw [LinearEquiv.symm_apply_apply] at heq
  rw [autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_apply]
  exact congrArg (fun x : NarrowClassGroup.ElementaryTwoQuotient
    (candidateGenusFieldBase hd) => Multiplicative.ofAdd x) heq

/-- **The genus-field isomorphism sends the Artin automorphism to the prime class.**
Under the hypotheses of the Frobenius theorem, the canonical Artin element at qIdeal maps to the
elementary-2 class of qIdeal. Thus the sign-pattern/genus-character isomorphism agrees locally
with the inverse ideal-theoretic Artin map. -/
theorem autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinElement
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    {q : ℕ} [Fact q.Prime]
    (qIdeal : Ideal (𝓞 (candidateGenusFieldBase hd)))
    (hnorm : Ideal.absNorm qIdeal = q) :
    let hprimeNorm : (Ideal.absNorm qIdeal).Prime := by
      rw [hnorm]
      exact Fact.out
    let _ : qIdeal.IsPrime := Ideal.isPrime_of_irreducible_absNorm hprimeNorm
    let _ : qIdeal.IsMaximal := Ideal.IsPrime.isMaximal inferInstance (by
      intro hbot
      rw [hbot, Ideal.absNorm_bot] at hnorm
      exact (Fact.out : q.Prime).ne_zero hnorm.symm)
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq
        (NumberFieldArithmetic.artinElement
          IsMulCommutative.is_comm.comm qIdeal
          (fun Q hQ hQl =>
            (isUnramifiedIn_candidateGenusField hd hnsq qIdeal) Q hQ hQl)) =
      Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk0
            ⟨qIdeal, by
              rw [← Ideal.absNorm_ne_zero_iff_mem_nonZeroDivisors, hnorm]
              exact (Fact.out : q.Prime).ne_zero⟩)) := by
  have hprimeNorm : (Ideal.absNorm qIdeal).Prime := by
    rw [hnorm]
    exact Fact.out
  let _ : qIdeal.IsPrime := Ideal.isPrime_of_irreducible_absNorm hprimeNorm
  let _ : qIdeal.LiesOver (Ideal.span {(q : ℤ)}) := ⟨by
    simpa [hnorm, Ideal.under_def] using
      Ideal.span_singleton_absNorm (I := qIdeal) hprimeNorm⟩
  let _ : qIdeal.IsMaximal := Ideal.IsPrime.isMaximal inferInstance (by
    intro hbot
    rw [hbot, Ideal.absNorm_bot] at hnorm
    exact (Fact.out : q.Prime).ne_zero hnorm.symm)
  obtain ⟨Q, hQprime, hQlies⟩ :=
    (inferInstance :
      Nonempty (qIdeal.primesOver (𝓞 (candidateGenusField hd))))
  let _ : Q.IsPrime := hQprime
  let _ : Q.LiesOver qIdeal := hQlies
  apply autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius
    hd hnsq qIdeal hnorm Q
  exact NumberFieldArithmetic.isArithFrobAt_artinElement
    IsMulCommutative.is_comm.comm qIdeal
      (fun Q hQ hQl =>
        (isUnramifiedIn_candidateGenusField hd hnsq qIdeal) Q hQ hQl) Q

/-! ### The Frobenius at an arbitrary unramified prime -/

/-- **The genus-field isomorphism sends every Frobenius to the class of the prime below it.**
Let `v` be a height-one prime of the embedded quadratic base `K = ℚ(√d)` and let `Q` be a prime
of the candidate genus field above `v`. Every relative arithmetic
Frobenius `σ` at `Q` is sent by the genus-field isomorphism to the class of `v` in the maximal
elementary-`2` quotient of the narrow class group.

Unlike `autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius`, no degree-one
hypothesis is imposed: `v` is inert over `q` in the remaining case, and then both sides are
trivial. The Frobenius is trivial because the absolute Frobenius at `Q` is an involution and the
residue field of `v` already has `q ^ 2` elements, and the class is trivial because an inert prime
is generated by the totally positive rational integer `q`. -/
theorem autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius_at_prime
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd)))
    (Q : Ideal (𝓞 (candidateGenusField hd))) [Q.IsPrime] [Q.LiesOver v.asIdeal]
    (σ : candidateGenusField hd ≃ₐ[candidateGenusFieldBase hd] candidateGenusField hd)
    (hσ : IsArithFrobAt (𝓞 (candidateGenusFieldBase hd)) σ Q) :
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq σ =
      Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk0
            ⟨v.asIdeal, mem_nonZeroDivisors_iff_ne_zero.mpr v.ne_bot⟩)) := by
  have hqprime := TauCeti.prime_rationalPrimeBelow v
  have : Fact (TauCeti.rationalPrimeBelow v).Prime := ⟨hqprime⟩
  have : v.asIdeal.LiesOver (Ideal.span {(TauCeti.rationalPrimeBelow v : ℤ)}) :=
    ⟨(TauCeti.under_eq_span_rationalPrimeBelow v).symm⟩
  -- The residue degree of `v` over `ℚ` is one or two.
  have hdvd := v.absNorm_dvd_rationalPrimeBelow_pow_finrank
  rw [finrank_candidateGenusFieldBase hd hnsq] at hdvd
  obtain ⟨i, hi, hnorm⟩ := (Nat.dvd_prime_pow hqprime).mp hdvd
  interval_cases i
  · -- The norm is one, so `v.asIdeal` is the unit ideal, which is not prime.
    rw [pow_zero, Ideal.absNorm_eq_one_iff] at hnorm
    exact absurd hnorm v.isPrime.ne_top
  · -- `v` is a degree-one prime: this is the split case.
    rw [pow_one] at hnorm
    exact autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius hd hnsq
      v.asIdeal hnorm Q σ hσ
  · -- `v` is inert: the Frobenius and the narrow class are both trivial.
    have : Q.LiesOver (Ideal.span {(TauCeti.rationalPrimeBelow v : ℤ)}) :=
      Ideal.LiesOver.trans Q v.asIdeal (Ideal.span {(TauCeti.rationalPrimeBelow v : ℤ)})
    have : Algebra.IsUnramifiedAt (𝓞 (candidateGenusFieldBase hd)) Q :=
      isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q inferInstance inferInstance
    obtain ⟨ρ, hρ⟩ := NumberField.exists_isArithFrobAt_int_of_liesOver
      (K := candidateGenusField hd) (p := TauCeti.rationalPrimeBelow v) Q
    have hcard : Nat.card (𝓞 (candidateGenusFieldBase hd) ⧸
        Q.under (𝓞 (candidateGenusFieldBase hd))) = TauCeti.rationalPrimeBelow v ^ 2 := by
      have hunder : Q.under (𝓞 (candidateGenusFieldBase hd)) = v.asIdeal := Ideal.LiesOver.over.symm
      rw [hunder, ← Submodule.cardQuot_apply, ← Ideal.absNorm_apply, hnorm]
    -- Every automorphism of the candidate genus field over `ℚ` is an involution: transport
    -- `aut_mul_self_eq_one` along the presentation of `candidateGenusField` as an `adjoin`.
    have hρ2 : ρ ^ 2 = 1 := by
      apply (AlgEquiv.autCongr (candidateGenusFieldEquivAdjoin hd)).injective
      rw [map_pow, map_one, pow_two]
      exact aut_mul_self_eq_one (genusFieldRoot_sq_algebraMap hd) _
    have hσone : σ = 1 := NumberField.isArithFrobAt_eq_one_of_pow_eq_one hρ hρ2 hcard hσ
    have hspan : v.asIdeal =
        Ideal.span {((TauCeti.rationalPrimeBelow v : ℕ) : 𝓞 (candidateGenusFieldBase hd))} :=
      TauCeti.asIdeal_eq_span_singleton_of_absNorm_eq_pow_finrank
        (by rw [hnorm, finrank_candidateGenusFieldBase hd hnsq])
    have hane : ((TauCeti.rationalPrimeBelow v : ℕ) : 𝓞 (candidateGenusFieldBase hd)) ≠ 0 :=
      Nat.cast_ne_zero.mpr hqprime.ne_zero
    have hpos : NumberField.IsTotallyPositive
        ((((TauCeti.rationalPrimeBelow v : ℕ) : 𝓞 (candidateGenusFieldBase hd)) :
          candidateGenusFieldBase hd)) := by
      have hcast := NumberField.isTotallyPositive_intCast (K := candidateGenusFieldBase hd)
        (n := (TauCeti.rationalPrimeBelow v : ℤ)) (by exact_mod_cast hqprime.pos)
      simpa using hcast
    have hcls : NarrowClassGroup.mk0
        (⟨v.asIdeal, mem_nonZeroDivisors_iff_ne_zero.mpr v.ne_bot⟩ :
          (Ideal (𝓞 (candidateGenusFieldBase hd)))⁰) = 1 :=
      NarrowClassGroup.mk0_eq_one_of_isTotallyPositive hane hpos hspan
    rw [hσone, map_one, hcls, TauCeti.elementaryTwoQuotientMk_one, ofAdd_zero]

/-! ### The Artin map on ideals -/

/-- **The genus-field isomorphism inverts the ideal-theoretic Artin map.** Let `d` be a squarefree
integer that is not a rational square, let `K = ℚ(√d)` be the embedded quadratic base of the
candidate genus field `K_gen`, and let `S` be any finite set of primes of `𝓞 K`. Then, on the
group of
invertible fractional ideals of multiplicity zero along `S`, the genus-field isomorphism carries
the Artin map to the narrow elementary-`2` ideal class:

`Φ (Art I) = [I] ∈ Cl⁺(K)/Cl⁺(K)²`.

Both sides are homomorphisms out of a group generated by the primes outside `S`, and
`autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius_at_prime` identifies them at
each such prime.

Neither input of the Artin map is assumed: `Gal(K_gen/K)` is commutative because `K_gen` is
abelian over `ℚ`, and `isUnramifiedIn_candidateGenusField` makes every prime of `K` unramified in
`K_gen`, so no prime has to be excluded on that account. -/
theorem autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (S : Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))))
    (I : NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S) :
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq
        (NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm S
          (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
            inferInstance inferInstance) I) =
      Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
            (candidateGenusFieldBase hd))ˣ))) := by
  -- The narrow elementary-`2` class, as a homomorphism on the ideals away from `S`.
  let cls : NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S →*
      Multiplicative (NarrowClassGroup.ElementaryTwoQuotient (candidateGenusFieldBase hd)) :=
    MonoidHom.mk' (fun J ↦ Multiplicative.ofAdd
      (TauCeti.elementaryTwoQuotientMk
        (NarrowClassGroup.mk (J : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
          (candidateGenusFieldBase hd))ˣ)))) fun J J' ↦ by
      rw [Subgroup.coe_mul, map_mul, TauCeti.elementaryTwoQuotientMk_mul, ofAdd_add]
  -- `MonoidHom.mk'` stores the underlying function, so this is the computation rule for `cls`.
  have hcls : ∀ J : NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S,
      cls J = Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk (J : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
            (candidateGenusFieldBase hd))ˣ))) := fun _ ↦ rfl
  have key : ((autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd
      hnsq).symm.toMonoidHom).comp cls =
      NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm S
        (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
          inferInstance inferInstance) := by
    refine NumberFieldArithmetic.artinHomAway_eq_of_apply_prime _ S _ _ ?_
    intro J v hv hJ Q hQp hQl σ hσ
    have _ : Q.IsPrime := hQp
    have _ : Q.LiesOver v.asIdeal := hQl
    rw [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, MulEquiv.symm_apply_eq]
    have hunit : (J : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
        (candidateGenusFieldBase hd))ˣ) =
        FractionalIdeal.mk0 (candidateGenusFieldBase hd)
          ⟨v.asIdeal, mem_nonZeroDivisors_iff_ne_zero.mpr v.ne_bot⟩ :=
      Units.ext (by rw [hJ, FractionalIdeal.coe_mk0])
    rw [hcls, hunit, NarrowClassGroup.mk_mk0]
    exact (autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_frobenius_at_prime hd hnsq v
      Q σ hσ).symm
  have hI := DFunLike.congr_fun key I
  rw [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom] at hI
  rw [← hI, MulEquiv.apply_symm_apply]
  exact hcls I

/-- **The genus-field Artin map is trivial exactly on the narrow classes that are squares.** An
invertible fractional ideal prime to `S` has trivial Artin automorphism in `Gal(K_gen/K)` precisely
when its narrow ideal class lies in `Cl⁺(K)²`; in particular the Artin map factors through
`Cl⁺(K)/Cl⁺(K)²`, and kills every ideal with a totally positive generator. -/
theorem artinHomAway_candidateGenusField_eq_one_iff
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (S : Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))))
    (I : NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd) S) :
    NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm S
        (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
          inferInstance inferInstance) I = 1 ↔
      TauCeti.elementaryTwoQuotientMk
        (NarrowClassGroup.mk (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
          (candidateGenusFieldBase hd))ˣ)) = 0 := by
  rw [← (autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq).map_eq_one_iff,
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway hd hnsq S I]
  exact ofAdd_eq_one

/-! ### The canonical excluded set -/

/-- **The primes excluded from the genus-field Artin map**: the primes of the embedded quadratic
base `K = ℚ(√d)` whose residue characteristic divides the discriminant of `K`. This is the
canonical discriminant-excluded set used by the later Artin-map specialization; the local
Frobenius comparison itself holds at every prime. -/
noncomputable def genusFieldArtinExcludedPrimes (hd : Squarefree d) :
    Finset (IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))) :=
  TauCeti.primesDividing (candidateGenusFieldBase hd) (fundamentalDiscriminant d)
    (fundamentalDiscriminant_ne_zero hd.ne_zero)

/-- Membership in `genusFieldArtinExcludedPrimes` is divisibility of the discriminant by the
rational prime below. -/
@[simp]
theorem mem_genusFieldArtinExcludedPrimes (hd : Squarefree d)
    (v : IsDedekindDomain.HeightOneSpectrum (𝓞 (candidateGenusFieldBase hd))) :
    v ∈ genusFieldArtinExcludedPrimes hd ↔
      (TauCeti.rationalPrimeBelow v : ℤ) ∣ fundamentalDiscriminant d :=
  TauCeti.mem_primesDividing _ v

/-- **The genus-field isomorphism inverts the Artin map away from the discriminant.** The
canonical instance of `autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway`: on
the invertible fractional ideals prime to `disc K`, the Artin map of `K_gen / K` is the
inverse of the genus-field isomorphism composed with the narrow elementary-`2` class. -/
theorem autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway_excludedPrimes
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ))
    (I : NumberFieldArithmetic.idealsAway (K := candidateGenusFieldBase hd)
      (genusFieldArtinExcludedPrimes hd)) :
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq
        (NumberFieldArithmetic.artinHomAway IsMulCommutative.is_comm.comm
          (genusFieldArtinExcludedPrimes hd)
          (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
            inferInstance inferInstance) I) =
      Multiplicative.ofAdd
        (TauCeti.elementaryTwoQuotientMk
          (NarrowClassGroup.mk (I : (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰
            (candidateGenusFieldBase hd))ˣ))) :=
  autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway hd hnsq _ I

/-- **The genus-field Artin map is surjective.** Every automorphism of `K_gen` over `K` is the
Artin automorphism of an integral ideal of `K` prime to `disc K`. The genus-field isomorphism
turns this into the statement that every narrow ideal class modulo squares is represented by such
an ideal, which is the coprime-representative theorem
`NumberField.NarrowClassGroup.exists_mk0_eq_and_isCoprime`. -/
theorem artinHomAwayIntegral_candidateGenusField_surjective
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    Function.Surjective
      (NumberFieldArithmetic.artinHomAwayIntegral (L := candidateGenusField hd)
        (fun σ τ ↦ (commute_iff_eq σ τ).2 (IsMulCommutative.is_comm.comm σ τ))
        (genusFieldArtinExcludedPrimes hd)
        (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
          inferInstance inferInstance)) := by
  intro σ
  obtain ⟨C, hC⟩ := TauCeti.elementaryTwoQuotientMk_surjective
    (Multiplicative.toAdd (autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq σ))
  have hDne : algebraMap ℤ (𝓞 (candidateGenusFieldBase hd))
      (fundamentalDiscriminant d) ≠ 0 := fun h ↦
    fundamentalDiscriminant_ne_zero hd.ne_zero
      (FaithfulSMul.algebraMap_injective ℤ (𝓞 (candidateGenusFieldBase hd))
        (h.trans (map_zero _).symm))
  have hM :
      Ideal.span
        {algebraMap ℤ (𝓞 (candidateGenusFieldBase hd))
          (fundamentalDiscriminant d)} ∈ (Ideal (𝓞 (candidateGenusFieldBase hd)))⁰ :=
    Ideal.span_singleton_nonZeroDivisors.mpr (mem_nonZeroDivisors_iff_ne_zero.mpr hDne)
  obtain ⟨J, hJC, hcop⟩ := NarrowClassGroup.exists_mk0_eq_and_isCoprime C ⟨_, hM⟩
  have hmem : (J : Ideal (𝓞 (candidateGenusFieldBase hd))) ∈
      NumberFieldArithmetic.integralIdealsAway (K := candidateGenusFieldBase hd)
        (genusFieldArtinExcludedPrimes hd) := by
    rw [NumberFieldArithmetic.mem_integralIdealsAway_iff]
    refine ⟨mem_nonZeroDivisors_iff_ne_zero.mp J.2, fun v hv hdvdJ ↦ ?_⟩
    have hdvdM : v.asIdeal ∣
        Ideal.span
          {algebraMap ℤ (𝓞 (candidateGenusFieldBase hd))
            (fundamentalDiscriminant d)} :=
      Ideal.dvd_span_singleton.mpr <|
        (v.intCast_mem_asIdeal_iff _).mpr ((mem_genusFieldArtinExcludedPrimes hd v).mp hv)
    refine v.isPrime.ne_top (top_le_iff.mp ?_)
    rw [← Ideal.isCoprime_iff_sup_eq.mp hcop]
    exact sup_le (Ideal.le_of_dvd hdvdJ) (Ideal.le_of_dvd hdvdM)
  refine ⟨⟨J, hmem⟩, ?_⟩
  apply (autCandidateGenusFieldEquivNarrowElementaryTwoQuotient hd hnsq).injective
  rw [NumberFieldArithmetic.artinHomAwayIntegral_apply,
    autCandidateGenusFieldEquivNarrowElementaryTwoQuotient_artinHomAway_excludedPrimes]
  have hcoe : ((NumberFieldArithmetic.integralIdealsAwayHom
      (K := candidateGenusFieldBase hd) (genusFieldArtinExcludedPrimes hd) ⟨_, hmem⟩ :
        NumberFieldArithmetic.idealsAway (genusFieldArtinExcludedPrimes hd)) :
      (FractionalIdeal (𝓞 (candidateGenusFieldBase hd))⁰ (candidateGenusFieldBase hd))ˣ) =
      FractionalIdeal.mk0 (candidateGenusFieldBase hd) J :=
    Units.ext (by
      rw [NumberFieldArithmetic.coe_integralIdealsAwayHom, FractionalIdeal.coe_mk0])
  rw [hcoe, NarrowClassGroup.mk_mk0, hJC, hC, ofAdd_toAdd]

/-- **The genus-field Artin map on fractional ideals is surjective.** This follows from
`artinHomAwayIntegral_candidateGenusField_surjective` by including the integral ideals prime to
`disc K` into the corresponding group of fractional ideals. -/
theorem artinHomAway_candidateGenusField_surjective
    (hd : Squarefree d) (hnsq : ¬ IsSquare ((d : ℤ) : ℚ)) :
    Function.Surjective
      (NumberFieldArithmetic.artinHomAway (L := candidateGenusField hd)
        IsMulCommutative.is_comm.comm (genusFieldArtinExcludedPrimes hd)
        (fun v _ Q _ _ ↦ isUnramifiedIn_candidateGenusField hd hnsq v.asIdeal Q
          inferInstance inferInstance)) := by
  intro σ
  obtain ⟨I, hI⟩ := artinHomAwayIntegral_candidateGenusField_surjective hd hnsq σ
  refine ⟨NumberFieldArithmetic.integralIdealsAwayHom _ I, ?_⟩
  simpa only [NumberFieldArithmetic.artinHomAwayIntegral_apply] using hI

end TauCeti.Multiquadratic
