/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Operations
public import Mathlib.LinearAlgebra.Dual.Lemmas
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Adjoin
public import TauCeti.Algebra.Coalgebra.Comodule.TensorProduct

/-!
# Matrix coefficients of a tensor product of comodules

For two right comodules `M` and `N` over a bialgebra `C`, the tensor product `M ⊗[R] N`
carries the diagonal coaction `m ⊗ n ↦ (m₀ ⊗ n₀) ⊗ m₁ n₁` of
`TauCeti.Algebra.Coalgebra.Comodule.TensorProduct` (`Comodule.tensor`), which multiplies the
two coefficient factors in `C`. This file records the corresponding fact about matrix
coefficients: the coefficient of the product functional `φ ⊗ ψ` on a decomposable vector
`m ⊗ n` is the **product** of the two coefficients,

`c_{φ ⊗ ψ, m ⊗ n} = c_{φ, m} · c_{ψ, n}`.

Here `φ ⊗ ψ` is the functional on `M ⊗[R] N` given by Mathlib's `TensorProduct.dualDistrib`,
`m ⊗ n ↦ φ m · ψ n`. This multiplicativity is the algebra-side reflection of the monoidal
(tensor-product) structure on comodules: multiplying one coefficient of `M` by one coefficient
of `N` produces a coefficient of `M ⊗[R] N`, so the coefficient submodules multiply into the
coefficient submodule of the tensor product.

This is Layer 1 infrastructure for the reductive-groups roadmap (`ReductiveGroups/README.md`
in TauCetiRoadmap), whose Layer 1 asks for the representation/comodule dictionary with matrix
coefficients and for the tensor product of comodules; the faithful-representation criterion is
stated in terms of the subalgebra generated by matrix coefficients, and multiplicativity on
tensor products is the key structural fact relating that subalgebra to the tensor product of
representations.

## Main declarations

* `TauCeti.Comodule.matrixCoefficient_tensor`: the coefficient of `φ ⊗ ψ` on `m ⊗ n` is the
  product `c_{φ, m} · c_{ψ, n}`.
* `TauCeti.Comodule.matrixCoefficientSet_mul_subset`: a product of a coefficient of `M` and a
  coefficient of `N` is a coefficient of `M ⊗[R] N`.
* `TauCeti.Comodule.matrixCoefficientSubmodule_mul_le`: the coefficient submodules multiply
  into the coefficient submodule of the tensor product.

## References

This is the standard multiplicativity of matrix coefficients under the tensor product of
comodules; see Sweedler, *Hopf Algebras*, Chapter 2. It builds on the tensor-product comodule
`TauCeti.Comodule.tensor` and the matrix-coefficient API of
`TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient`, and uses Mathlib's
`TensorProduct.dualDistrib`.
-/

public section

open scoped TensorProduct Pointwise
open TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

variable {R : Type u} {C : Type v} {M : Type w} {N : Type x}
variable [CommSemiring R]
variable [Semiring C] [Bialgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

-- The tensor product of comodules is not a global instance (an `R`-module can carry many
-- coactions); register the diagonal coaction of `Comodule.tensor` locally so that
-- `matrixCoefficient (M := M ⊗[R] N)` resolves to it throughout this file.
attribute [local instance] tensor

omit [Comodule R C M] [Comodule R C N] in
/-- The combining map underlying the tensor coaction turns the coefficient computation on the
tensor product into the product of the two component computations. This is the linear-algebra
core of `matrixCoefficient_tensor`, stated for arbitrary elements `x : M ⊗ C` and `y : N ⊗ C`
so that it can be applied to the two component coactions. -/
private theorem lid_map_dualDistrib_tensorCombine (φ : M →ₗ[R] R) (ψ : N →ₗ[R] R)
    (x : M ⊗[R] C) (y : N ⊗[R] C) :
    TensorProduct.lid R C
        (TensorProduct.map (TensorProduct.dualDistrib R M N (φ ⊗ₜ[R] ψ)) LinearMap.id
          (tensorCombine (R := R) (C := C) (M := M) (N := N) (x ⊗ₜ[R] y))) =
      TensorProduct.lid R C (TensorProduct.map φ LinearMap.id x) *
        TensorProduct.lid R C (TensorProduct.map ψ LinearMap.id y) := by
  induction x using TensorProduct.inductionOn with
  | add x₁ x₂ hx₁ hx₂ => simp only [add_tmul, map_add, add_mul, hx₁, hx₂]
  | tmul m c =>
    induction y using TensorProduct.inductionOn with
    | add y₁ y₂ hy₁ hy₂ => simp only [tmul_add, map_add, mul_add, hy₁, hy₂]
    | tmul n d =>
      rw [tensorCombine_tmul_tmul]
      simp only [TensorProduct.map_tmul, LinearMap.id_coe, id_eq, TensorProduct.lid_tmul,
        TensorProduct.dualDistrib_apply]
      exact (smul_mul_smul_comm (φ m) c (ψ n) d).symm

/-- **Matrix coefficients multiply on a tensor product of comodules.** For the diagonal
coaction on `M ⊗[R] N`, the matrix coefficient of the product functional
`TensorProduct.dualDistrib R M N (φ ⊗ₜ ψ)` (which sends `m ⊗ n ↦ φ m · ψ n`) evaluated at
`m ⊗ n` is the product of the matrix coefficients of `φ` at `m` and of `ψ` at `n`. -/
@[simp]
theorem matrixCoefficient_tensor (φ : M →ₗ[R] R) (ψ : N →ₗ[R] R) (m : M) (n : N) :
    matrixCoefficient (R := R) (C := C) (M := M ⊗[R] N)
        (TensorProduct.dualDistrib R M N (φ ⊗ₜ[R] ψ)) (m ⊗ₜ[R] n) =
      matrixCoefficient (R := R) (C := C) φ m * matrixCoefficient (R := R) (C := C) ψ n := by
  simp only [matrixCoefficient_def]
  rw [tensor_coact, tensorCoact_tmul]
  exact lid_map_dualDistrib_tensorCombine φ ψ
    (coact (R := R) (C := C) (M := M) m) (coact (R := R) (C := C) (M := N) n)

/-- The product of a matrix coefficient of `M` and a matrix coefficient of `N` is a matrix
coefficient of the tensor product `M ⊗[R] N`, realized on the product functional and the
decomposable vector. -/
theorem mul_matrixCoefficient_mem_set_tensor (φ : M →ₗ[R] R) (ψ : N →ₗ[R] R) (m : M) (n : N) :
    matrixCoefficient (R := R) (C := C) φ m * matrixCoefficient (R := R) (C := C) ψ n ∈
      matrixCoefficientSet (R := R) (C := C) (M := M ⊗[R] N) := by
  rw [← matrixCoefficient_tensor]
  exact matrixCoefficient_mem_set (R := R) (C := C) (M := M ⊗[R] N) _ _

/-- **Products of coefficients are coefficients of the tensor product.** The pointwise product
of the coefficient sets of `M` and of `N` is contained in the coefficient set of `M ⊗[R] N`. -/
theorem matrixCoefficientSet_mul_subset :
    matrixCoefficientSet (R := R) (C := C) (M := M) *
        matrixCoefficientSet (R := R) (C := C) (M := N) ⊆
      matrixCoefficientSet (R := R) (C := C) (M := M ⊗[R] N) := by
  rw [Set.mul_subset_iff]
  intro a ha b hb
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) a).mp ha with ⟨φ, m, rfl⟩
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := N) b).mp hb with ⟨ψ, n, rfl⟩
  exact mul_matrixCoefficient_mem_set_tensor φ ψ m n

/-- **The coefficient submodules multiply into the tensor product's.** The product of the
matrix coefficient submodules of `M` and of `N` is contained in the matrix coefficient
submodule of `M ⊗[R] N`. -/
theorem matrixCoefficientSubmodule_mul_le :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) *
        matrixCoefficientSubmodule (R := R) (C := C) (M := N) ≤
      matrixCoefficientSubmodule (R := R) (C := C) (M := M ⊗[R] N) := by
  rw [matrixCoefficientSubmodule, matrixCoefficientSubmodule, matrixCoefficientSubmodule,
    Submodule.span_mul_span]
  exact Submodule.span_mono matrixCoefficientSet_mul_subset

end Comodule

end TauCeti
