/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Witt.FundamentalIdeal
public import TauCeti.RingTheory.Ideal.Operations

/-!
# Pfister classes and powers of the fundamental ideal

For units `a₁, …, aₙ`, the `n`-fold Pfister form is the tensor product

`<<a₁, …, aₙ>> = <<a₁>> ⋯ <<aₙ>>`,

where `<<a>> = <1, -a>`. This file defines its diagonal presentation, isometry class, and Witt
class, and proves that, for
every positive `n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The explicit two- and three-fold corollaries are the forms used to define and control the
Clifford invariant.

The positivity condition is necessary: `I(K)^0 = W(K)`, while the sole zero-fold Pfister class is
`<1>`, and a Witt ring need not be additively cyclic.

## Main definitions

* `TauCeti.pfisterFormClass`: the isometry class of an iterated Pfister tensor product.
* `TauCeti.pfisterClass`: its Witt class.
* `TauCeti.pfisterForm`: its diagonal tuple of weights.

## Main results

* `TauCeti.discr_pfisterFormClass`: Pfister forms of fold at least two have trivial
  discriminant.
* `TauCeti.fundamentalIdeal_pow_eq_addClosure`: positive powers of the
  fundamental ideal are additively generated by Pfister classes.
* `TauCeti.fundamentalIdeal_sq_eq_addClosure` and
  `TauCeti.fundamentalIdeal_cube_eq_addClosure`: the cases needed for
  the Clifford invariant.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter II, §1 and
  Chapter X, with the convention `<<a>> = <1, -a>`.
-/

public section

open scoped BigOperators Pointwise

namespace TauCeti

universe u

variable {K : Type u} [Field K]

/-- The diagonal weights of the `n`-fold Pfister form, ordered by the binary subsets of its
slots. -/
def pfisterForm : {n : ℕ} → (Fin n → Kˣ) → Fin (2 ^ n) → Kˣ
  | 0, _ => fun _ => 1
  | n + 1, a => fun k =>
      let ij := finProdFinEquiv.symm (Fin.cast (pow_succ 2 n) k)
      pfisterForm (Fin.tail a) ij.1 * ![1, -(a 0)] ij.2

/-- The zero-fold Pfister form has the single diagonal weight `1`. -/
@[simp]
theorem pfisterForm_zero (a : Fin 0 → Kˣ) : pfisterForm a = fun _ => 1 := by
  rfl

/-- `⟨⟨a⟩⟩ = ⟨1, -a⟩`. -/
@[simp]
theorem pfisterForm_one (a : Kˣ) : pfisterForm ![a] = ![1, -a] := by
  funext i
  let ij := finProdFinEquiv.symm (Fin.cast (pow_succ 2 0) i)
  -- The recursive definition of `pfisterForm` has no interface lemma for its successor branch;
  -- this exposes that branch after naming the product index `ij`.
  change 1 * ![1, -a] ij.2 = ![1, -a] i
  have hij : ij.2 = i := by
    apply Fin.ext
    simp [ij]
    omega
  rw [hij]
  simp

/-- `⟨⟨a, b⟩⟩ = ⟨1, -a, -b, ab⟩`. -/
@[simp]
theorem pfisterForm_two (a b : Kˣ) : pfisterForm ![a, b] = ![1, -a, -b, a * b] := by
  funext i
  let ij := finProdFinEquiv.symm (Fin.cast (pow_succ 2 1) i)
  -- The recursive definition of `pfisterForm` has no interface lemma for its successor branch;
  -- this exposes that branch after naming the product index `ij`.
  change pfisterForm (Fin.tail ![a, b]) ij.1 * ![1, -a] ij.2 =
    ![1, -a, -b, a * b] i
  have htail : Fin.tail ![a, b] = ![b] := by
    funext j
    fin_cases j
    rfl
  rw [htail, pfisterForm_one]
  fin_cases i
  · have hij : ij = ((0 : Fin 2), (0 : Fin 2)) := by
      apply Prod.ext <;> apply Fin.ext <;> simp [ij]
    rw [hij]
    simp
  · have hij : ij = ((0 : Fin 2), (1 : Fin 2)) := by
      apply Prod.ext <;> apply Fin.ext <;> simp [ij]
    rw [hij]
    simp
  · have hij : ij = ((1 : Fin 2), (0 : Fin 2)) := by
      apply Prod.ext <;> apply Fin.ext <;> simp [ij]
    rw [hij]
    simp
  · have hij : ij = ((1 : Fin 2), (1 : Fin 2)) := by
      apply Prod.ext <;> apply Fin.ext <;> simp [ij]
    rw [hij]
    simp [mul_comm]

/-- Splitting off the first slot identifies the diagonal Pfister presentation with the tensor
product of the remaining presentation and the corresponding one-fold presentation. -/
theorem pfisterPresentation_cons {n : ℕ} (a : Fin (n + 1) → Kˣ) :
    (⟨2 ^ (n + 1), pfisterForm a⟩ : RegularFormPresentation K) =
      RegularFormPresentation.tmul
        (⟨2 ^ n, pfisterForm (Fin.tail a)⟩ : RegularFormPresentation K) ⟨2, ![1, -(a 0)]⟩ := by
  have hfst :
      (⟨2 ^ (n + 1), pfisterForm a⟩ : RegularFormPresentation K).1 =
        (RegularFormPresentation.tmul
          (⟨2 ^ n, pfisterForm (Fin.tail a)⟩ : RegularFormPresentation K)
          ⟨2, ![1, -(a 0)]⟩).1 := by
    rw [RegularFormPresentation.fst_tmul]
    exact pow_succ 2 n
  apply RegularFormPresentation.ext hfst
  intro i
  let p : RegularFormPresentation K := ⟨2 ^ n, pfisterForm (Fin.tail a)⟩
  let q : RegularFormPresentation K := ⟨2, ![1, -(a 0)]⟩
  let ij := finProdFinEquiv.symm (Fin.cast (pow_succ 2 n) i)
  -- No interface theorem relates the recursive Pfister weights directly to `tmul`; this exposes
  -- the two coordinate functions so that `RegularFormPresentation.tmul_apply` applies below.
  change pfisterForm (Fin.tail a) ij.1 * ![1, -(a 0)] ij.2 =
    (p.tmul q).2 (Fin.cast hfst i)
  have hk : Fin.cast hfst i =
      Fin.cast (RegularFormPresentation.fst_tmul p q).symm (finProdFinEquiv ij) := by
    apply Fin.ext
    simp [ij, q]
    omega
  rw [hk]
  exact (RegularFormPresentation.tmul_apply p q ij.1 ij.2).symm

variable [Invertible (2 : K)]

/-- The isometry class of the `n`-fold Pfister form, using the convention
`<<a>> = <1, -a>`. Orthogonal sum is addition and tensor product is multiplication on
`RegularFormClass`; the empty product is therefore the zero-fold form `<1>`. -/
noncomputable def pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) : RegularFormClass K :=
  ∏ i, (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -(a i)⟩)

/-- The defining product for the isometry class of an `n`-fold Pfister form. -/
theorem pfisterFormClass_def {n : ℕ} (a : Fin n → Kˣ) :
    pfisterFormClass a =
      ∏ i, (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -(a i)⟩) :=
  pfisterFormClass.eq_def a

/-- Splitting off the first slot splits a Pfister form as a tensor product. -/
@[simp]
theorem pfisterFormClass_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterFormClass (Fin.cons a b) =
      (1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩) * pfisterFormClass b := by
  simp [pfisterFormClass_def, Fin.prod_univ_succ]

/-- The zero-fold Pfister form is the rank-one unit form. -/
@[simp]
theorem pfisterFormClass_zero (a : Fin 0 → Kˣ) : pfisterFormClass a = 1 := by
  simp [pfisterFormClass_def]

/-- Reindexing the slots of a Pfister form class by an equivalence does not change it. -/
@[simp]
theorem pfisterFormClass_comp_equiv {m n : ℕ} (a : Fin n → Kˣ) (e : Fin m ≃ Fin n) :
    pfisterFormClass (a ∘ e) = pfisterFormClass a := by
  rw [pfisterFormClass_def, pfisterFormClass_def]
  exact e.prod_comp fun i ↦ 1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ ↦ -(a i)⟩

omit [Invertible (2 : K)] in
private theorem pfisterFactor_eq (a : Kˣ) :
    1 + Quotient.mk (regularFormSetoid K) ⟨1, fun _ => -a⟩ =
      Quotient.mk (regularFormSetoid K) ⟨2, ![1, -a]⟩ := by
  rw [← RegularFormClass.mk_rankOne_one, RegularFormClass.mk_add_mk]
  congr 1
  let p : RegularFormPresentation K := ⟨1, fun _ => 1⟩
  let q : RegularFormPresentation K := ⟨1, fun _ => -a⟩
  -- `mk_add_mk` exposes the appended presentation only definitionally; there is no
  -- interface lemma that restates this equality using the local presentations `p` and `q`.
  change p.append q = ⟨2, ![1, -a]⟩
  have h : (p.append q).1 = 2 := by simp [p, q]
  refine RegularFormPresentation.ext h ?_
  intro i
  generalize hj : Fin.cast h i = j
  fin_cases j
  · have hi : i = Fin.cast h.symm 0 := by
      calc
        i = Fin.cast h.symm (Fin.cast h i) := (Fin.leftInverse_cast h i).symm
        _ = Fin.cast h.symm 0 := congrArg (Fin.cast h.symm) hj
    rw [hi]
    simpa [p, q] using RegularFormPresentation.append_apply_castAdd p q (0 : Fin 1)
  · have hi : i = Fin.cast h.symm 1 := by
      calc
        i = Fin.cast h.symm (Fin.cast h i) := (Fin.leftInverse_cast h i).symm
        _ = Fin.cast h.symm 1 := congrArg (Fin.cast h.symm) hj
    rw [hi]
    simpa [p, q] using RegularFormPresentation.append_apply_natAdd p q (0 : Fin 1)

/-- The isometry class of a Pfister form is represented by its explicit diagonal tuple. -/
theorem pfisterFormClass_eq_mk {n : ℕ} (a : Fin n → Kˣ) :
    pfisterFormClass a =
      Quotient.mk (regularFormSetoid K) ⟨2 ^ n, pfisterForm a⟩ := by
  induction n with
  | zero =>
      rw [pfisterFormClass_zero]
      rw [RegularFormClass.one_def]
      congr 1
      have hfst : (RegularFormPresentation.one (K := K)).1 = 2 ^ 0 := by simp
      apply RegularFormPresentation.ext hfst
      intro i
      rw [RegularFormPresentation.one_apply]
      rfl
  | succ n ih =>
      rw [← Fin.cons_self_tail a, pfisterFormClass_cons]
      rw [ih, pfisterFactor_eq, mul_comm, RegularFormClass.mk_mul_mk]
      exact congrArg (Quotient.mk (regularFormSetoid K)) (pfisterPresentation_cons a).symm

/-- A one-fold Pfister form has diagonal weights `<1, -a>`. -/
@[simp]
theorem pfisterFormClass_one (a : Fin 1 → Kˣ) :
    pfisterFormClass a =
      Quotient.mk (regularFormSetoid K) ⟨2, ![1, -(a 0)]⟩ := by
  have ha : a = ![a 0] := by
    funext i
    fin_cases i
    rfl
  rw [ha, pfisterFormClass_eq_mk, pfisterForm_one]
  rfl

/-- A two-fold Pfister form has diagonal weights `<1, -a, -b, ab>`. -/
@[simp]
theorem pfisterFormClass_two (a b : Kˣ) :
    pfisterFormClass ![a, b] =
      Quotient.mk (regularFormSetoid K) ⟨4, ![1, -a, -b, a * b]⟩ := by
  rw [pfisterFormClass_eq_mk, pfisterForm_two]
  rfl

/-- An `n`-fold Pfister form has rank `2 ^ n`. -/
@[simp]
theorem rank_pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) :
    RegularFormClass.rank (pfisterFormClass a) = 2 ^ n := by
  rw [pfisterFormClass_def, ← RegularFormClass.rankHom_apply, map_prod]
  simp [RegularFormClass.rankHom_apply, RegularFormClass.rank_mk]

/-- **Pfister forms of fold at least two have trivial discriminant**: the signed discriminant of
an `n`-fold Pfister form is the trivial square class once `n ≥ 2`. -/
@[simp]
theorem discr_pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) (hn : 2 ≤ n) :
    RegularFormClass.discr (pfisterFormClass a) = 0 := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le' hn
  have h2 (x : SquareClassGroup K) : 2 • x = 0 := ZModModule.char_nsmul_eq_zero 2 x
  -- Split off one slot: `d(<<a>> ⊗ φ) = rank φ • d(<<a>>) + 2 • d(φ)`, with `rank φ` even.
  rw [← Fin.cons_self_tail a, pfisterFormClass_cons]
  simp [RegularFormClass.discr_mul, pow_succ, mul_nsmul', h2]

/-- The Witt class of an `n`-fold Pfister form. -/
noncomputable def pfisterClass {n : ℕ} (a : Fin n → Kˣ) : WittRing K :=
  wittClass (pfisterFormClass a)

/-- Taking the Witt class of a Pfister form class gives its Pfister class. -/
@[simp]
theorem wittClass_pfisterFormClass {n : ℕ} (a : Fin n → Kˣ) :
    wittClass (pfisterFormClass a) = pfisterClass a := (pfisterClass.eq_def a).symm

/-- The Witt class of a Pfister form is the product of its one-fold factors. -/
theorem pfisterClass_eq_prod {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a = ∏ i, oneFoldPfisterClass (a i) := by
  rw [pfisterClass, pfisterFormClass_def, map_prod]
  apply Finset.prod_congr rfl
  intro i _
  rw [map_add, map_one, oneFoldPfisterClass_eq]

/-- The zero-fold Pfister class is the unit of the Witt ring. -/
@[simp]
theorem pfisterClass_zero (a : Fin 0 → Kˣ) : pfisterClass a = 1 := by
  simp [pfisterClass]

/-- Splitting off the first slot splits a Pfister class as a product. -/
@[simp]
theorem pfisterClass_cons {n : ℕ} (a : Kˣ) (b : Fin n → Kˣ) :
    pfisterClass (Fin.cons a b) = oneFoldPfisterClass a * pfisterClass b := by
  rw [pfisterClass, pfisterFormClass_cons, map_mul]
  rw [map_add, map_one, oneFoldPfisterClass_eq, pfisterClass]

/-- A one-fold Pfister class agrees with the existing class of `<1, -a>`. -/
@[simp]
theorem pfisterClass_one (a : Fin 1 → Kˣ) :
    pfisterClass a = oneFoldPfisterClass (a 0) := by
  rw [pfisterClass_eq_prod]
  rw [Fin.prod_univ_one]

/-- Reindexing the slots of a Pfister class by an equivalence does not change it. -/
@[simp]
theorem pfisterClass_comp_equiv {m n : ℕ} (a : Fin n → Kˣ) (e : Fin m ≃ Fin n) :
    pfisterClass (a ∘ e) = pfisterClass a := by
  rw [← wittClass_pfisterFormClass, pfisterFormClass_comp_equiv, wittClass_pfisterFormClass]

/-- The two-fold Pfister class is the product `<<a>> * <<b>>`. -/
@[simp]
theorem pfisterClass_two (a b : Kˣ) :
    pfisterClass ![a, b] = oneFoldPfisterClass a * oneFoldPfisterClass b := by
  simp [pfisterClass_eq_prod, Fin.prod_univ_two]

/-- Every `n`-fold Pfister class belongs to `I(K)^n`. -/
@[simp]
theorem pfisterClass_mem_fundamentalIdeal_pow {n : ℕ} (a : Fin n → Kˣ) :
    pfisterClass a ∈ fundamentalIdeal K ^ n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [← Fin.cons_self_tail a, pfisterClass_cons, pow_succ']
      exact Ideal.mul_mem_mul (oneFoldPfisterClass_mem_fundamentalIdeal (a 0)) (ih (Fin.tail a))

private theorem range_pfisterClass_succ (n : ℕ) :
    Set.range (pfisterClass (K := K) (n := n + 1)) =
      Set.range (pfisterClass (K := K) (n := n)) *
        Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    refine ⟨pfisterClass (Fin.tail a), Set.mem_range_self _,
      oneFoldPfisterClass (a 0), Set.mem_range_self _, ?_⟩
    calc
      pfisterClass (Fin.tail a) * oneFoldPfisterClass (a 0) =
          oneFoldPfisterClass (a 0) * pfisterClass (Fin.tail a) := mul_comm _ _
      _ = pfisterClass a := by rw [← pfisterClass_cons, Fin.cons_self_tail]
  · rintro ⟨_, ⟨a, rfl⟩, _, ⟨b, rfl⟩, rfl⟩
    exact ⟨Fin.cons b a, by rw [pfisterClass_cons, mul_comm]⟩

private theorem range_pfisterClass_one :
    Set.range (pfisterClass (K := K) (n := 1)) =
      Set.range (oneFoldPfisterClass (K := K)) := by
  ext x
  constructor
  · rintro ⟨a, rfl⟩
    exact ⟨a 0, (pfisterClass_one a).symm⟩
  · rintro ⟨a, rfl⟩
    exact ⟨![a], by simp⟩

/-- For `0 < n`, the additive group underlying `I(K)^n` is generated by the `n`-fold Pfister
classes. The positivity hypothesis excludes the generally false assertion that `W(K) = I(K)^0`
is additively generated by the zero-fold class `<1>`. -/
theorem fundamentalIdeal_pow_eq_addClosure {n : ℕ} (hn : 0 < n) :
    (fundamentalIdeal K ^ n).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := n))) := by
  obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (Nat.ne_of_gt hn)
  clear hn
  induction m with
  | zero =>
      rw [pow_one, range_pfisterClass_one,
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass]
  | succ m ih =>
      rw [pow_succ', Ideal.toAddSubgroup_mul_eq_closure_mul
        fundamentalIdeal_toAddSubgroup_eq_closure_oneFoldPfisterClass ih,
        mul_comm (Set.range (oneFoldPfisterClass (K := K))) _, ← range_pfisterClass_succ]

/-- The square of the fundamental ideal is additively generated by two-fold Pfister classes. -/
theorem fundamentalIdeal_sq_eq_addClosure :
    (fundamentalIdeal K ^ 2).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 2))) :=
  fundamentalIdeal_pow_eq_addClosure (by omega)

/-- The cube of the fundamental ideal is additively generated by three-fold Pfister classes. -/
theorem fundamentalIdeal_cube_eq_addClosure :
    (fundamentalIdeal K ^ 3).toAddSubgroup =
      AddSubgroup.closure (Set.range (pfisterClass (K := K) (n := 3))) :=
  fundamentalIdeal_pow_eq_addClosure (by omega)

end TauCeti
