/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Field.ZMod
public import Mathlib.Algebra.Module.ZMod
public import Mathlib.GroupTheory.Abelianization.Defs
public import TauCeti.GroupTheory.ExponentPrime
public import TauCeti.Topology.Algebra.Group.Profinite.Basic

/-!
# The pro-`p` Frattini subgroup

The **pro-`p` Frattini subgroup** `proPFrattini p G` of a topological group `G` is the
intersection of its open normal subgroups of index `p`. For a prime `p` and a *profinite* `G` it
is the smallest closed normal subgroup with elementary abelian quotient, so that
`G ⧸ proPFrattini p G` is the largest elementary abelian quotient of `G` by a closed normal
subgroup; and for a pro-`p` group it is the Frattini subgroup in the usual sense, the
intersection of the maximal open subgroups. That last identification needs the finite `p`-group
theory of maximal subgroups and is `TauCeti.IsProP.proPFrattini_eq_iInf_isCoatom`, in
`TauCeti.Topology.Algebra.Group.Profinite.ProP.MaximalSubgroup`.

The main theorem is the **verbal description**
`proPFrattini p G = closure (Gᵖ [G, G])`, the topological closure of the subgroup generated by
the `p`-th powers and the commutators. One inclusion is immediate: a quotient of prime order `p`
is cyclic, hence commutative of exponent `p`, so it kills both generators. The other inclusion is
where profiniteness enters. Writing `N` for the right-hand side, an element outside `N` is
outside `N ⊔ U` for some open normal `U`, because a closed subgroup of a profinite group is the
intersection of the subgroups `N ⊔ U`; the quotient by `W = N ⊔ U` is then a *finite* group that
is commutative of exponent dividing `p`, and in such a group the subgroups of index `p` separate
points (`TauCeti.exists_index_eq_notMem_of_exponent_dvd`). Pulling one of them back gives an open
normal subgroup of index `p` missing the element.

Two consequences are recorded because they are what consumers use: for a prime `p` the Frattini
quotient `G ⧸ proPFrattini p G` is commutative of exponent dividing `p` — an `𝔽_p`-vector space —
and, for a *profinite* `G`, `proPFrattini p G` is trivial exactly when `G` itself already is one.
The maximality of that quotient is likewise a profinite statement, recorded as
`TauCeti.proPFrattini_le_iff`.

Everything up to the verbal description is stated for an arbitrary topological group; compactness
and total disconnectedness are assumed exactly where they are used.

## Main definitions

* `TauCeti.proPFrattini`: the intersection of the open normal subgroups of index `p`.

## Main results

* `TauCeti.pow_mem_proPFrattini` and `TauCeti.commutator_le_proPFrattini`: the `p`-th powers and
  the commutators lie in the pro-`p` Frattini subgroup.
* `TauCeti.proPFrattini_eq_topologicalClosure`: the verbal description
  `proPFrattini p G = closure (Gᵖ [G, G])`.
* `TauCeti.isMulCommutative_quotient_proPFrattini` and
  `TauCeti.exponent_quotient_proPFrattini_dvd`: the Frattini quotient is elementary abelian for a
  prime `p`.
* `TauCeti.proPFrattini_le_iff`: for a profinite `G`, a closed normal subgroup contains
  `proPFrattini p G` exactly when its quotient is elementary abelian.
* `TauCeti.proPFrattini_le_ker_of_exponent_dvd`: for a profinite `G`, the pro-`p` Frattini
  subgroup lies in the kernel of every homomorphism with closed kernel to a commutative group of
  exponent dividing `p`.
* `TauCeti.map_proPFrattini_eq_of_surjective` and `TauCeti.comap_proPFrattini_eq_of_surjective`:
  a continuous surjection of profinite groups carries the pro-`p` Frattini subgroup onto the
  pro-`p` Frattini subgroup, and the preimage of the latter is the former joined with the kernel.
* `TauCeti.proPFrattini_eq_bot_iff`: for a profinite `G`, the pro-`p` Frattini subgroup is trivial
  exactly when `G` is commutative of exponent dividing `p`.
* `ContinuousMulEquiv.map_proPFrattini_eq`: the pro-`p` Frattini subgroup is characteristic under
  continuous automorphisms.
* `TauCeti.map_proPFrattini_eq_of_surjective`: a continuous surjection of profinite groups carries
  the pro-`p` Frattini subgroup onto the pro-`p` Frattini subgroup.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 2.8.
-/

public section

namespace TauCeti

open scoped commutatorElement

universe u v

section Defs

variable (p : ℕ) (G : Type u) [Group G] [TopologicalSpace G]

/-- The **pro-`p` Frattini subgroup** of a topological group `G`: the intersection of the open
normal subgroups of `G` of index `p`. For a prime `p` and a profinite `G` it is the smallest
closed normal subgroup whose quotient is elementary abelian, so that `G ⧸ proPFrattini p G` is
then the largest elementary abelian quotient of `G` by a closed normal subgroup; see
`TauCeti.proPFrattini_le_iff`. -/
def proPFrattini : Subgroup G :=
  ⨅ U : {U : OpenNormalSubgroup G // U.toSubgroup.index = p}, U.1.toSubgroup

/-- The defining equation of the pro-`p` Frattini subgroup: the body of `TauCeti.proPFrattini` is
not exposed, so unfolding it goes through this lemma. -/
theorem proPFrattini_def :
    proPFrattini p G =
      ⨅ U : {U : OpenNormalSubgroup G // U.toSubgroup.index = p}, U.1.toSubgroup := by
  rw [proPFrattini]

/-- The pro-`p` Frattini subgroup is a normal subgroup. -/
instance proPFrattini_normal : (proPFrattini p G).Normal :=
  Subgroup.normal_iInf_normal fun U ↦ U.1.isNormal'

end Defs

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G]
variable {H : Type v} [Group H] [TopologicalSpace H]

/-- Membership in the pro-`p` Frattini subgroup, unfolded over the defining family. -/
theorem mem_proPFrattini_iff {x : G} :
    x ∈ proPFrattini p G ↔
      ∀ U : OpenNormalSubgroup G, U.toSubgroup.index = p → x ∈ U.toSubgroup := by
  rw [proPFrattini_def, Subgroup.mem_iInf]
  exact ⟨fun h U hU ↦ h ⟨U, hU⟩, fun h U ↦ h U.1 U.2⟩

/-- The pro-`p` Frattini subgroup is contained in every open normal subgroup of index `p`. -/
theorem proPFrattini_le {U : OpenNormalSubgroup G} (hU : U.toSubgroup.index = p) :
    proPFrattini p G ≤ U.toSubgroup :=
  fun _ hx ↦ mem_proPFrattini_iff.mp hx U hU

/-- The pro-`p` Frattini subgroup is closed, being an intersection of open subgroups. -/
instance isClosed_proPFrattini [IsTopologicalGroup G] :
    IsClosed ((proPFrattini p G : Subgroup G) : Set G) := by
  rw [proPFrattini_def, Subgroup.coe_iInf]
  exact isClosed_iInter fun U ↦ U.1.toOpenSubgroup.isClosed

/-! ### The elementary abelian generators -/

/-- Every `p`-th power lies in the pro-`p` Frattini subgroup: a quotient of order `p` has
exponent dividing `p`. -/
@[simp]
theorem pow_mem_proPFrattini (g : G) : g ^ p ∈ proPFrattini p G := by
  refine mem_proPFrattini_iff.mpr fun U hU ↦ ?_
  have hcard : Nat.card (G ⧸ U.toSubgroup) = p := (Subgroup.index_eq_card _).symm.trans hU
  rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow, ← hcard]
  exact pow_card_eq_one'

/-- Every commutator lies in the pro-`p` Frattini subgroup: a quotient of prime order is
cyclic, hence commutative. -/
theorem commutator_le_proPFrattini (hp : p.Prime) : commutator G ≤ proPFrattini p G := by
  rw [commutator_def, Subgroup.commutator_le]
  intro a _ b _
  refine mem_proPFrattini_iff.mpr fun U hU ↦ ?_
  have : Fact p.Prime := ⟨hp⟩
  have hcard : Nat.card (G ⧸ U.toSubgroup) = p := (Subgroup.index_eq_card _).symm.trans hU
  have : IsCyclic (G ⧸ U.toSubgroup) := isCyclic_of_prime_card hcard
  rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, map_commutatorElement]
  exact commutatorElement_eq_one_iff_mul_comm.mpr (mul_comm' _ _)

/-- The Frattini quotient is commutative. -/
theorem isMulCommutative_quotient_proPFrattini (hp : p.Prime) :
    IsMulCommutative (G ⧸ proPFrattini p G) :=
  Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr (commutator_le_proPFrattini hp)

/-- The Frattini quotient has exponent dividing `p`. For a prime `p`, together with
`TauCeti.isMulCommutative_quotient_proPFrattini` this says that `G ⧸ proPFrattini p G` is
elementary abelian, that is an `𝔽_p`-vector space. -/
theorem exponent_quotient_proPFrattini_dvd :
    Monoid.exponent (G ⧸ proPFrattini p G) ∣ p := by
  refine Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr fun x ↦ ?_
  obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective (proPFrattini p G) x
  rw [QuotientGroup.mk'_apply, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
  exact pow_mem_proPFrattini g

/-- The Frattini quotient is an abelian group, with its existing quotient operations. -/
instance instCommGroupQuotientProPFrattini [Fact p.Prime] :
    CommGroup (G ⧸ proPFrattini p G) where
  mul_comm := by
    have := isMulCommutative_quotient_proPFrattini (G := G) (Fact.out : p.Prime)
    exact mul_comm'

/-- The additive Frattini quotient is a vector space over `𝔽_p`. Scalar multiplication is
the canonical action on an abelian group killed by `p`, from `AddCommGroup.zmodModule`. -/
instance instModuleQuotientProPFrattini [Fact p.Prime] :
    Module (ZMod p) (Additive (G ⧸ proPFrattini p G)) :=
  AddCommGroup.zmodModule fun x ↦
    Monoid.exponent_dvd_iff_forall_pow_eq_one.mp exponent_quotient_proPFrattini_dvd x.toMul

/-! ### Functoriality -/

/-- A continuous surjection carries the pro-`p` Frattini subgroup into the pro-`p` Frattini
subgroup of the target: the preimage of an open normal subgroup of index `p` again has index
`p`. -/
theorem _root_.MonoidHom.proPFrattini_le_comap (f : G →* H) (hf : Continuous f)
    (hsurj : Function.Surjective f) : proPFrattini p G ≤ (proPFrattini p H).comap f := by
  intro x hx
  rw [Subgroup.mem_comap]
  refine mem_proPFrattini_iff.mpr fun V hV ↦ ?_
  refine proPFrattini_le (U := ⟨V.toOpenSubgroup.comap f hf, V.isNormal'.comap f⟩) ?_ hx
  exact (Subgroup.index_comap_of_surjective V.toSubgroup hsurj).trans hV

/-- The image of the pro-`p` Frattini subgroup under a continuous surjection lies in the pro-`p`
Frattini subgroup of the target. -/
theorem _root_.MonoidHom.map_proPFrattini_le (f : G →* H) (hf : Continuous f)
    (hsurj : Function.Surjective f) : (proPFrattini p G).map f ≤ proPFrattini p H :=
  Subgroup.map_le_iff_le_comap.mpr (f.proPFrattini_le_comap hf hsurj)

/-- Continuous multiplicative equivalences identify the pro-`p` Frattini subgroups of their
source and target. In particular, the pro-`p` Frattini subgroup is characteristic under
continuous automorphisms. -/
theorem _root_.ContinuousMulEquiv.map_proPFrattini_eq (e : G ≃ₜ* H) :
    (proPFrattini p G).map e.toMulEquiv.toMonoidHom = proPFrattini p H := by
  refine le_antisymm (MonoidHom.map_proPFrattini_le _ e.continuous e.surjective) fun x hx ↦ ?_
  have hsymm : e.symm x ∈ proPFrattini p G :=
    e.symm.toMulEquiv.toMonoidHom.map_proPFrattini_le e.symm.continuous e.symm.surjective
      (Subgroup.mem_map_of_mem _ hx)
  exact ⟨e.symm x, hsymm, e.apply_symm_apply x⟩

/-! ### The verbal description -/

section Profinite

variable [IsTopologicalGroup G] [CompactSpace G] [TotallyDisconnectedSpace G]

/-- **The verbal description of the pro-`p` Frattini subgroup.** For a profinite group `G` and a
prime `p`, the intersection of the open normal subgroups of index `p` is the closed subgroup
topologically generated by the `p`-th powers and the commutators. -/
theorem proPFrattini_eq_topologicalClosure (hp : p.Prime) :
    proPFrattini p G =
      (Subgroup.closure (Set.range fun g : G ↦ g ^ p) ⊔ commutator G).topologicalClosure := by
  have hgen : Subgroup.closure (Set.range fun g : G ↦ g ^ p) ⊔ commutator G ≤ proPFrattini p G :=
    sup_le (Subgroup.closure_le _ |>.mpr <| by
        rintro _ ⟨g, rfl⟩; exact pow_mem_proPFrattini g)
      (commutator_le_proPFrattini hp)
  refine le_antisymm ?_ (Subgroup.topologicalClosure_minimal _ hgen isClosed_proPFrattini)
  -- A closed subgroup of a profinite group is the intersection of its joins with the open
  -- normal subgroups, so it is enough to enter each such join.
  rw [Subgroup.eq_iInf_sup_openNormalSubgroup _ (Subgroup.isClosed_topologicalClosure _)]
  refine le_iInf fun U ↦ ?_
  set W : Subgroup G :=
    (Subgroup.closure (Set.range fun g : G ↦ g ^ p) ⊔ commutator G).topologicalClosure ⊔
      U.toSubgroup
  -- `W` is an open normal subgroup whose quotient is finite and elementary abelian.
  have hcomm : commutator G ≤ W :=
    le_sup_of_le_left (le_sup_right.trans (Subgroup.le_topologicalClosure _))
  have hWnormal : W.Normal := Subgroup.Normal.of_commutator_le G hcomm
  have hWopen : IsOpen (W : Set G) := Subgroup.isOpen_mono le_sup_right U.isOpen
  have hWfinite : Finite (G ⧸ W) := Subgroup.quotient_finite_of_isOpen W hWopen
  have hWcomm : IsMulCommutative (G ⧸ W) :=
    Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr hcomm
  have hWexp : Monoid.exponent (G ⧸ W) ∣ p := by
    refine Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr fun x ↦ ?_
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective W x
    rw [QuotientGroup.mk'_apply, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact Subgroup.mem_sup_left (Subgroup.le_topologicalClosure _
      (Subgroup.mem_sup_left (Subgroup.subset_closure ⟨g, rfl⟩)))
  -- Separate an element outside `W` from an index-`p` subgroup of `G ⧸ W`, and pull it back.
  intro x hx
  by_contra hxW
  obtain ⟨K, hKindex, hKx⟩ :=
    exists_index_eq_notMem_of_exponent_dvd hp hWexp (σ := (QuotientGroup.mk' W) x)
      (by rwa [QuotientGroup.mk'_apply, Ne, QuotientGroup.eq_one_iff])
  have hVopen : IsOpen ((K.comap (QuotientGroup.mk' W) : Subgroup G) : Set G) := by
    refine Subgroup.isOpen_mono (fun y hy ↦ ?_) hWopen
    rw [Subgroup.mem_comap, QuotientGroup.mk'_apply, (QuotientGroup.eq_one_iff y).mpr hy]
    exact K.one_mem
  let V : OpenNormalSubgroup G :=
    { toOpenSubgroup := ⟨K.comap (QuotientGroup.mk' W), hVopen⟩
      isNormal' := (Subgroup.normal_of_isMulCommutative K).comap _ }
  have hVindex : V.toSubgroup.index = p :=
    (Subgroup.index_comap_of_surjective K (QuotientGroup.mk'_surjective W)).trans hKindex
  exact hKx (proPFrattini_le hVindex hx)

/-- **The universal property of the Frattini quotient.** For a profinite group `G` and a prime
`p`, a closed normal subgroup `K` contains `proPFrattini p G` exactly when the quotient `G ⧸ K`
is elementary abelian; that is, `G ⧸ proPFrattini p G` is the largest elementary abelian quotient
of `G` by a closed normal subgroup. -/
theorem proPFrattini_le_iff (hp : p.Prime) (K : Subgroup G) [K.Normal]
    (hK : IsClosed (K : Set G)) :
    proPFrattini p G ≤ K ↔ IsMulCommutative (G ⧸ K) ∧ Monoid.exponent (G ⧸ K) ∣ p := by
  refine ⟨fun h ↦ ⟨Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
    ((commutator_le_proPFrattini hp).trans h), ?_⟩, fun ⟨hcomm, hexp⟩ ↦ ?_⟩
  · refine Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr fun x ↦ ?_
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective K x
    rw [QuotientGroup.mk'_apply, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact h (pow_mem_proPFrattini g)
  · rw [proPFrattini_eq_topologicalClosure hp]
    refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) hK
    · refine Subgroup.closure_le _ |>.mpr ?_
      rintro _ ⟨g, rfl⟩
      rw [SetLike.mem_coe, ← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow]
      exact Monoid.exponent_dvd_iff_forall_pow_eq_one.mp hexp _
    · exact Subgroup.Normal.quotient_commutative_iff_commutator_le.mp hcomm

/-- For a profinite group `G` and a prime `p`, the pro-`p` Frattini subgroup lies in the kernel of
every homomorphism with closed kernel to a commutative group of exponent dividing `p`; for
instance, of every continuous homomorphism to a discrete elementary abelian `p`-group. -/
theorem proPFrattini_le_ker_of_exponent_dvd (hp : p.Prime) {A : Type*} [CommGroup A]
    (f : G →* A) (hf : IsClosed (f.ker : Set G)) (hA : Monoid.exponent A ∣ p) :
    proPFrattini p G ≤ f.ker := by
  rw [proPFrattini_eq_topologicalClosure hp]
  refine Subgroup.topologicalClosure_minimal _
    (sup_le ((Subgroup.closure_le _).mpr ?_) (Abelianization.commutator_subset_ker f)) hf
  rintro _ ⟨g, rfl⟩
  rw [SetLike.mem_coe, MonoidHom.mem_ker, map_pow]
  exact Monoid.exponent_dvd_iff_forall_pow_eq_one.mp hA _

/-- The pro-`p` Frattini subgroup of a profinite group is trivial exactly when the group is
already commutative of exponent dividing `p`, that is an `𝔽_p`-vector space. -/
theorem proPFrattini_eq_bot_iff (hp : p.Prime) :
    proPFrattini p G = ⊥ ↔ IsMulCommutative G ∧ Monoid.exponent G ∣ p := by
  have hbot : IsClosed ((⊥ : Subgroup G) : Set G) := by
    rw [Subgroup.coe_bot]; exact isClosed_singleton
  refine ⟨fun h ↦ ⟨(commutator_eq_bot_iff G).mp
      (le_bot_iff.mp (h ▸ commutator_le_proPFrattini hp)), ?_⟩, fun h ↦ ?_⟩
  · exact Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr fun g ↦ by
      simpa [h] using pow_mem_proPFrattini (p := p) g
  · obtain ⟨hcomm, hexp⟩ := h
    rw [proPFrattini_eq_topologicalClosure hp, ← le_bot_iff]
    refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) hbot
    · exact Subgroup.closure_le _ |>.mpr <| by
        rintro _ ⟨g, rfl⟩
        simpa using Monoid.exponent_dvd_iff_forall_pow_eq_one.mp hexp g
    · exact ((commutator_eq_bot_iff G).mpr hcomm).le

/-! ### Surjective images -/

variable [IsTopologicalGroup H] [CompactSpace H] [TotallyDisconnectedSpace H]

-- Total disconnectedness of the source is not used: only compactness, to see that the image of
-- the (closed) Frattini subgroup is closed.
omit [TotallyDisconnectedSpace G] in
/-- **A continuous surjection of profinite groups carries the pro-`p` Frattini subgroup onto the
pro-`p` Frattini subgroup.** -/
theorem map_proPFrattini_eq_of_surjective (hp : p.Prime) (f : G →* H) (hf : Continuous f)
    (hsurj : Function.Surjective f) :
    (proPFrattini p G).map f = proPFrattini p H := by
  refine le_antisymm (f.map_proPFrattini_le hf hsurj) ?_
  -- The image is a closed subgroup containing the `p`-th powers and the commutators.
  rw [proPFrattini_eq_topologicalClosure hp]
  refine Subgroup.topologicalClosure_minimal _ (sup_le ?_ ?_) ?_
  · refine Subgroup.closure_le _ |>.mpr ?_
    rintro _ ⟨y, rfl⟩
    obtain ⟨g, rfl⟩ := hsurj y
    exact ⟨g ^ p, pow_mem_proPFrattini g, map_pow f g p⟩
  · rw [commutator_def, Subgroup.commutator_le]
    intro a _ b _
    obtain ⟨a, rfl⟩ := hsurj a
    obtain ⟨b, rfl⟩ := hsurj b
    refine Subgroup.mem_map.mpr ⟨(⁅a, b⁆ : G), commutator_le_proPFrattini hp ?_,
      map_commutatorElement f a b⟩
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b)
  · rw [Subgroup.coe_map]
    exact ((isClosed_proPFrattini (p := p) (G := G)).isCompact.image hf).isClosed

omit [TotallyDisconnectedSpace G] in
/-- Along a continuous surjection of profinite groups, the preimage of the pro-`p` Frattini
subgroup of the target is generated by the pro-`p` Frattini subgroup of the source together with
the kernel. -/
theorem comap_proPFrattini_eq_of_surjective (hp : p.Prime) (f : G →* H) (hf : Continuous f)
    (hsurj : Function.Surjective f) :
    (proPFrattini p H).comap f = proPFrattini p G ⊔ f.ker := by
  rw [← map_proPFrattini_eq_of_surjective hp f hf hsurj, Subgroup.comap_map_eq]

end Profinite

end TauCeti
