/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem

/-!
# Dirichlet's unit theorem in structural form

Mathlib's `NumberField.Units.exist_unique_eq_mul_prod` states that every unit of `𝓞 F` has a
unique decomposition as a root of unity times a product of powers of the fundamental system.
This file packages that unique decomposition as a multiplicative equivalence

`(𝓞 F)ˣ ≃* torsion F × Multiplicative (Fin (rank F) → ℤ)`,

exhibiting the unit group as the product of its (finite cyclic) torsion subgroup and a free
abelian group of Dirichlet rank. This structural form is what downstream counting arguments
consume — for instance the exact number of unit square classes in
`TauCeti.NumberTheory.NumberField.Units.ElementaryTwoQuotient`.

## Main results

* `NumberField.unitsMulEquivTorsionProdMultiplicative`: the unit group as the product of
  its torsion subgroup and the free abelian group on the fundamental system.
* `NumberField.rank_eq_one_of_finrank_eq_two_of_isReal`: a quadratic field with a real place
  has unit rank one.
* `NumberField.rank_add_nrComplexPlaces_add_one`: the unit rank plus the number of complex
  places plus one is the degree.
-/

public section

open scoped NumberField

open Module NumberField NumberField.Units

namespace NumberField

variable (F : Type*) [Field F] [NumberField F]

/-- The homomorphism realizing a pair (root of unity, exponent vector) as a unit, the underlying
map of `NumberField.unitsMulEquivTorsionProdMultiplicative`. Kept private; the public
interface is the equivalence. -/
private noncomputable def torsionProdMultiplicativeToUnits :
    torsion F × Multiplicative (Fin (rank F) → ℤ) →* (𝓞 F)ˣ :=
  ((torsion F).subtype).coprod <|
    MonoidHom.mk' (fun e => ∏ i, fundSystem F i ^ Multiplicative.toAdd e i) fun a b => by
      simp only [toAdd_mul, Pi.add_apply, zpow_add, Finset.prod_mul_distrib]

private theorem torsionProdMultiplicativeToUnits_apply
    (ζ : torsion F) (e : Multiplicative (Fin (rank F) → ℤ)) :
    torsionProdMultiplicativeToUnits F (ζ, e) =
      (ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ Multiplicative.toAdd e i := by
  simp [torsionProdMultiplicativeToUnits, MonoidHom.coprod_apply]

/-- Dirichlet's unit theorem in its unique-decomposition form says exactly that realizing a pair
(root of unity, exponent vector) as a unit is bijective. -/
private theorem torsionProdMultiplicativeToUnits_bijective :
    Function.Bijective (torsionProdMultiplicativeToUnits F) := by
  constructor
  · rintro ⟨ζ, e⟩ ⟨ζ', e'⟩ h
    obtain ⟨p, -, huniq⟩ :=
      exist_unique_eq_mul_prod F (torsionProdMultiplicativeToUnits F (ζ, e))
    have h1 : (ζ, Multiplicative.toAdd e) = p :=
      huniq (ζ, Multiplicative.toAdd e) (torsionProdMultiplicativeToUnits_apply F ζ e)
    have h2 : (ζ', Multiplicative.toAdd e') = p :=
      huniq (ζ', Multiplicative.toAdd e')
        (h.trans (torsionProdMultiplicativeToUnits_apply F ζ' e'))
    obtain ⟨hζ, he⟩ := Prod.mk.inj (h1.trans h2.symm)
    exact Prod.ext hζ (Multiplicative.toAdd.injective he)
  · intro x
    obtain ⟨⟨ζ, v⟩, hx, -⟩ := exist_unique_eq_mul_prod F x
    exact ⟨(ζ, Multiplicative.ofAdd v), hx.symm⟩

/-- **Dirichlet's unit theorem, structural form.** The unit group of the ring of integers of a
number field is the product of its torsion subgroup and the free abelian group generated by the
fundamental system: a unit corresponds to its unique decomposition as a root of unity times a
product of powers of fundamental units (`NumberField.Units.exist_unique_eq_mul_prod`). -/
noncomputable def unitsMulEquivTorsionProdMultiplicative :
    (𝓞 F)ˣ ≃* torsion F × Multiplicative (Fin (rank F) → ℤ) :=
  (MulEquiv.ofBijective _ (torsionProdMultiplicativeToUnits_bijective F)).symm

/-- The inverse of `NumberField.unitsMulEquivTorsionProdMultiplicative` sends a pair to
the root of unity times the product of powers of fundamental units. -/
@[simp] theorem unitsMulEquivTorsionProdMultiplicative_symm_apply
    (ζ : torsion F) (e : Multiplicative (Fin (rank F) → ℤ)) :
    (unitsMulEquivTorsionProdMultiplicative F).symm (ζ, e) =
      (ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ Multiplicative.toAdd e i := by
  rw [unitsMulEquivTorsionProdMultiplicative, MulEquiv.symm_symm]
  exact torsionProdMultiplicativeToUnits_apply F ζ e

/-- The forward map of `NumberField.unitsMulEquivTorsionProdMultiplicative` reads off the
Dirichlet decomposition: a unit presented as a root of unity `ζ` times a product of powers of the
fundamental system is sent to the pair `(ζ, e)`. -/
@[simp] theorem unitsMulEquivTorsionProdMultiplicative_apply
    (ζ : torsion F) (e : Fin (rank F) → ℤ) :
    unitsMulEquivTorsionProdMultiplicative F
        ((ζ : (𝓞 F)ˣ) * ∏ i, fundSystem F i ^ e i) = (ζ, Multiplicative.ofAdd e) := by
  rw [unitsMulEquivTorsionProdMultiplicative, MulEquiv.symm_apply_eq, MulEquiv.ofBijective_apply,
    torsionProdMultiplicativeToUnits_apply]
  simp

open scoped Classical in
/-- **The unit rank, the complex places and one exhaust the degree.** Dirichlet's rank is
`#(InfinitePlace F) - 1` while the degree is `r₁ + 2 * r₂`, so restoring the complex places and
the one place the rank drops recovers `finrank ℚ F`.

Stated as an addition rather than as `rank F + nrComplexPlaces F = finrank ℚ F - 1`: the
subtraction on `ℕ` is truncated, and the additive form needs no positivity side condition. -/
theorem rank_add_nrComplexPlaces_add_one :
    rank F + InfinitePlace.nrComplexPlaces F + 1 = finrank ℚ F := by
  have h₁ := InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces F
  have h₂ := InfinitePlace.card_add_two_mul_card_eq_rank F
  -- `rank` is a truncated subtraction, so the count of places must be known to be positive.
  have h₃ : 0 < Fintype.card (InfinitePlace F) := Fintype.card_pos
  simp only [Units.rank]
  omega

/-- **A real quadratic field has unit rank one.** In degree two, a real infinite place forces
both infinite places to be real, so the unit rank is `2 - 1 = 1`. -/
theorem rank_eq_one_of_finrank_eq_two_of_isReal {F : Type*} [Field F] [NumberField F]
    (hdeg : finrank ℚ F = 2) {w : InfinitePlace F} (hw : w.IsReal) : rank F = 1 := by
  classical
  have hcard := InfinitePlace.card_add_two_mul_card_eq_rank F
  rw [hdeg] at hcard
  have hpos : InfinitePlace.nrRealPlaces F ≠ 0 := by
    have : Nonempty {w : InfinitePlace F // w.IsReal} := ⟨⟨w, hw⟩⟩
    exact Fintype.card_ne_zero
  rw [rank, InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces]
  omega

end NumberField
