/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Units.Regulator

/-!
# Evaluating a rank-one regulator

For a number field of unit rank one, a unit generating the units modulo torsion computes the
regulator at any infinite place `w` as `w.mult * |Real.log (w u)|`. In particular, at a place
where `1 < w u`, the absolute value can be removed. The multiplicity is essential at a complex
place.

The more general index formula also applies to a unit which does not generate modulo torsion.
It compares its weighted logarithm with the regulator times the subgroup index, using Mathlib's
`NumberField.Units.regOfFamily_div_regulator` and `NumberField.Units.regOfFamily_eq_det`.

In rank one, the norm of a unit's logarithmic embedding equals its weighted absolute logarithm
at any infinite place. This identifies norm comparisons with logarithm comparisons at a chosen
place. The product formula over the two infinite places also forces a unit expanding at one of
them to contract at the other, which controls the remaining conjugates of a unit bounded at a
chosen place.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §5.7.
-/

public section

open NumberField NumberField.Units NumberField.InfinitePlace
open scoped NumberField

namespace TauCeti.NumberField.Units

variable {K : Type*} [Field K] [NumberField K]

/-- At unit rank one, the regulator of the constant one-unit family is its weighted absolute
logarithm at any infinite place. This includes torsion units, for which both sides vanish. -/
theorem regOfFamily_const_eq_mult_abs_log (hr : rank K = 1) (u : (𝓞 K)ˣ)
    (w : InfinitePlace K) :
    regOfFamily (fun _ : Fin (rank K) => u) = w.mult * |Real.log (w u)| := by
  classical
  have hcard : Fintype.card (InfinitePlace K) = 2 := by
    unfold rank at hr
    omega
  have : Nontrivial (InfinitePlace K) :=
    Fintype.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨w', hw'⟩ := exists_ne w
  have hc : Fintype.card {v : InfinitePlace K // v ≠ w'} = 1 := by
    simp [Fintype.card_subtype_compl, hcard]
  have : Subsingleton {v : InfinitePlace K // v ≠ w'} :=
    Fintype.card_le_one_iff_subsingleton.mp hc.le
  let : Unique {v : InfinitePlace K // v ≠ w'} :=
    ⟨⟨⟨w, Ne.symm hw'⟩⟩, fun _ => Subsingleton.elim _ _⟩
  let e : {v : InfinitePlace K // v ≠ w'} ≃ Fin (rank K) :=
    Fintype.equivOfCardEq (by simp [hr])
  rw [regOfFamily_eq_det _ w' e, Matrix.det_unique]
  rw [Subsingleton.elim (default : {v : InfinitePlace K // v ≠ w'}) ⟨w, Ne.symm hw'⟩]
  simp [Matrix.of_apply, abs_mul]

/-- In unit rank one, the weighted absolute logarithm of a unit is the regulator multiplied
by the index of the subgroup generated by that unit and torsion. -/
theorem mult_abs_log_eq_index_mul_regulator (hr : rank K = 1) (u : (𝓞 K)ˣ)
    (w : InfinitePlace K) :
    w.mult * |Real.log (w u)| =
      ((Subgroup.closure {u} ⊔ torsion K).index : ℝ) * regulator K := by
  have : Nonempty (Fin (rank K)) := ⟨⟨0, by omega⟩⟩
  have h := regOfFamily_div_regulator (fun _ : Fin (rank K) => u)
  rw [regOfFamily_const_eq_mult_abs_log hr u w, Set.range_const] at h
  exact (div_eq_iff (regulator_ne_zero K)).mp h

open scoped Classical in
/-- In unit rank one, the logarithmic embedding has one coordinate. Its norm is the absolute
value of the weighted logarithm at any place other than Mathlib's distinguished place. -/
private theorem norm_logEmbedding_eq_mult_abs_log_of_rank_eq_one (hr : rank K = 1)
    (u : (𝓞 K)ˣ) (w : InfinitePlace K)
    (hw : w ≠ NumberField.Units.dirichletUnitTheorem.w₀) :
    ‖logEmbedding K (Additive.ofMul u)‖ = w.mult * |Real.log (w u)| := by
  classical
  have hplaces : Fintype.card (InfinitePlace K) = 2 := by
    unfold rank at hr
    omega
  have hcard : Fintype.card {v : InfinitePlace K //
      v ≠ NumberField.Units.dirichletUnitTheorem.w₀} = 1 := by
    simp [Fintype.card_subtype_compl, hplaces]
  have : Subsingleton {v : InfinitePlace K //
      v ≠ NumberField.Units.dirichletUnitTheorem.w₀} :=
    Fintype.card_le_one_iff_subsingleton.mp hcard.le
  let : Unique {v : InfinitePlace K //
      v ≠ NumberField.Units.dirichletUnitTheorem.w₀} :=
    ⟨⟨⟨w, hw⟩⟩, fun _ => Subsingleton.elim _ _⟩
  have hdefault : (default : {v : InfinitePlace K //
      v ≠ NumberField.Units.dirichletUnitTheorem.w₀}) = ⟨w, hw⟩ :=
    Subsingleton.elim _ _
  rw [Pi.norm_def]
  simp [Finset.univ_unique, hdefault,
    NumberField.Units.dirichletUnitTheorem.logEmbedding_component]

open scoped Classical in
/-- In unit rank one, the norm of a unit's logarithmic embedding equals its weighted absolute
logarithm at every infinite place. This evaluates an intrinsic norm at any chosen place. -/
theorem norm_logEmbedding_eq_mult_abs_log (hr : rank K = 1) (u : (𝓞 K)ˣ)
    (w : InfinitePlace K) :
    ‖logEmbedding K (Additive.ofMul u)‖ = w.mult * |Real.log (w u)| := by
  have hplaces : Fintype.card (InfinitePlace K) = 2 := by
    unfold rank at hr
    omega
  have : Nontrivial (InfinitePlace K) :=
    Fintype.one_lt_card_iff_nontrivial.mp (by omega)
  obtain ⟨w', hw'⟩ := exists_ne (NumberField.Units.dirichletUnitTheorem.w₀ (K := K))
  calc
    ‖logEmbedding K (Additive.ofMul u)‖ =
        w'.mult * |Real.log (w' u)| :=
      norm_logEmbedding_eq_mult_abs_log_of_rank_eq_one hr u w' hw'
    _ = ((Subgroup.closure {u} ⊔ torsion K).index : ℝ) * regulator K :=
      mult_abs_log_eq_index_mul_regulator hr u w'
    _ = w.mult * |Real.log (w u)| :=
      (mult_abs_log_eq_index_mul_regulator hr u w).symm

/-- In unit rank one, a unit whose absolute value exceeds one at an infinite place has absolute
value less than one at the other infinite place. -/
theorem lt_one_of_rank_eq_one_of_ne_of_one_lt (hr : rank K = 1) {w w' : InfinitePlace K}
    (hne : w' ≠ w)
    {v : (𝓞 K)ˣ} (hv : 1 < w v) : w' v < 1 := by
  classical
  have hcard : Fintype.card (InfinitePlace K) = 2 := by
    unfold rank at hr
    omega
  have huniv : (Finset.univ : Finset (InfinitePlace K)) = {w', w} :=
    (Finset.eq_univ_of_card _ (by rw [Finset.card_pair hne, hcard])).symm
  have h := sum_mult_mul_log v
  rw [huniv, Finset.sum_pair hne] at h
  have hm : (0 : ℝ) < w.mult := by exact_mod_cast mult_pos
  have hm' : (0 : ℝ) < w'.mult := by exact_mod_cast mult_pos
  have hlog : Real.log (w' v) < 0 := by
    have := Real.log_pos hv
    nlinarith
  exact (Real.log_neg_iff (Units.pos_at_place v w')).mp hlog

open scoped Classical in
/-- In unit rank one, a positive real value of a unit in `(1, B]` bounds the norm of its
logarithmic embedding by `log B`. -/
theorem norm_logEmbedding_le_log_of_interval (hr : rank K = 1)
    {w : InfinitePlace K} (hw : w.IsReal) (v : (𝓞 K)ˣ) {B : ℝ}
    (hlo : 1 < w.embedding_of_isReal hw (v : K))
    (hhi : w.embedding_of_isReal hw (v : K) ≤ B) :
    ‖logEmbedding K (Additive.ofMul v)‖ ≤ Real.log B := by
  have hval : w v = w.embedding_of_isReal hw (v : K) := by
    rw [← InfinitePlace.norm_embedding_of_isReal hw, Real.norm_eq_abs,
      abs_of_pos (lt_trans zero_lt_one hlo)]
  rw [norm_logEmbedding_eq_mult_abs_log hr v w, hw.mult_eq_one, Nat.cast_one, one_mul,
    abs_of_pos (Real.log_pos (hval ▸ hlo))]
  exact Real.log_le_log (hval ▸ lt_trans zero_lt_one hlo) (hval ▸ hhi)

open scoped Classical in
/-- At a place where `u` has absolute value greater than one, comparing log-embedding norms
amounts to comparing the absolute logarithm of `v` with the logarithm of `u` at that place. -/
theorem logEmbedding_norm_lt_iff_at_place (hr : rank K = 1) (u v : (𝓞 K)ˣ)
    (w : InfinitePlace K) (hw : 1 < w u) :
    ‖logEmbedding K (Additive.ofMul v)‖ < ‖logEmbedding K (Additive.ofMul u)‖ ↔
      |Real.log (w v)| < Real.log (w u) := by
  rw [norm_logEmbedding_eq_mult_abs_log hr v w,
    norm_logEmbedding_eq_mult_abs_log hr u w, abs_of_pos (Real.log_pos hw)]
  have hmult : (0 : ℝ) < (w.mult : ℝ) := by
    exact_mod_cast (NumberField.InfinitePlace.mult_pos (w := w))
  exact ⟨fun h => lt_of_mul_lt_mul_left h hmult.le,
    fun h => mul_lt_mul_of_pos_left h hmult⟩

/-- A generator modulo torsion in unit rank one evaluates the regulator at any infinite place.
No choice of a sign or of an inverse for the generator is needed. -/
theorem regulator_eq_mult_abs_log_of_rank_eq_one (hr : rank K = 1) (u : (𝓞 K)ˣ)
    (hu : Subgroup.closure {u} ⊔ torsion K = ⊤) (w : InfinitePlace K) :
    regulator K = w.mult * |Real.log (w u)| := by
  simpa [hu] using (mult_abs_log_eq_index_mul_regulator hr u w).symm

/-- At a place where a generator modulo torsion has absolute value greater than one, its
weighted logarithm is the rank-one regulator. -/
theorem regulator_eq_mult_log_of_rank_eq_one (hr : rank K = 1) (u : (𝓞 K)ˣ)
    (hu : Subgroup.closure {u} ⊔ torsion K = ⊤) (w : InfinitePlace K) (hw : 1 < w u) :
    regulator K = w.mult * Real.log (w u) := by
  rw [regulator_eq_mult_abs_log_of_rank_eq_one hr u hu w,
    abs_of_pos (Real.log_pos hw)]

end TauCeti.NumberField.Units
