/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.ConstantForm.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.Symplectic.Basic

/-!
# The symplectic subgroup scheme of `GL₂ₘ`

For a commutative ring `R` and `m : ℕ`, the symplectic subgroup scheme `Sp₂ₘ` of `GL (m + m)`
is the subgroup scheme preserving the standard alternating form `Jₘ`: the specialization of
`TauCeti.ConstantForm` at `C = Jₘ`, cut out of `GL (m + m)` by the entries of

```text
X Jₘ Xᵀ - Jₘ
```

for `X` the localized generic matrix and `Jₘ` the standard alternating form in `Fin (m + m)`
coordinates. On every commutative `R`-algebra `A`, its points are the existing subgroup
`TauCeti.GLSymplecticFin m A`, equivalently `TauCeti.GLSymplectic (Fin m) A`, and that
identification is what this file adds to the general construction.

Together with `TauCeti.GLSymplectic`, this completes the `Sp₂ₘ` worked example of the
ReductiveGroups roadmap at the same boundary as the Borel example
(`TauCeti.GeneralLinear.Borel`): construction and points identification, with no smoothness or
reductivity claim.

The Hopf-ideal closure conditions, the quotient, the group scheme with its closed immersion
into `GL (m + m)`, and the ambient membership criterion `M C Mᵀ = C` all come from
`TauCeti.ConstantForm`, which proves them for an arbitrary constant matrix `C` (local finite
type is the generic instance for Hopf-ideal quotients of the ambient coordinate algebra); no
invertibility or nondegeneracy of `Jₘ` is used anywhere. The construction includes `m = 0` and
the zero ring.

## Main declarations

* `TauCeti.Symplectic.relationMatrix`: the matrix of defining relations `X Jₘ Xᵀ - Jₘ`.
* `TauCeti.Symplectic.definingHopfIdeal`: the Hopf ideal its entries generate.
* `TauCeti.Symplectic.coordinateHopfAlgebra` and `TauCeti.Symplectic.coordinateMap`: the
  symplectic coordinate Hopf algebra, the quotient by the defining Hopf ideal, and the
  quotient morphism onto it.
* `TauCeti.Symplectic.groupScheme` and `TauCeti.Symplectic.inclusion`: the symplectic subgroup
  scheme and its closed immersion into the general linear group scheme.
* `TauCeti.Symplectic.pointsMulEquiv`: the group of algebra-valued points of the symplectic
  coordinate Hopf algebra is `TauCeti.GLSymplecticFin`, and
  `TauCeti.Symplectic.pointsMulEquivGLSymplectic` reads it in `Fin m ⊕ Fin m` coordinates.

## References

* J. S. Milne, *Algebraic Groups* (2017), §2.3 and §24.6: `Sp₂ₙ` as the subgroup of `GL₂ₙ`
  preserving a nondegenerate alternating form, cut out by the entries of the form relation.
* The Stacks Project, [Tag 022W](https://stacks.math.columbia.edu/tag/022W), for the ambient
  general linear group scheme.

The closure computations this file relies on, and the framing identities behind them, are
proved for an arbitrary constant form in `TauCeti.ConstantForm`.
-/

public section

open AlgebraicGeometry CategoryTheory Matrix WithConv
open scoped CategoryTheory.MonObj

namespace TauCeti.Symplectic

universe u v w

variable (R : Type u) [CommRing R] (m : ℕ)

/-! ### The symplectic specialization of the constant-form construction -/

/-- **The matrix of defining relations** of the symplectic subgroup scheme: `X Jₘ Xᵀ - Jₘ` over
the coordinate Hopf algebra of `GL (m + m)`, the constant-form relation matrix at `C = Jₘ`. -/
noncomputable abbrev relationMatrix :
    Matrix (Fin (m + m)) (Fin (m + m)) (GeneralLinear.coordinateHopfAlgebra R (m + m)) :=
  ConstantForm.relationMatrix R (m + m) (JFin m R)

/-- The relation matrix is the standard alternating form transported by the generic matrix,
minus the form: `X Jₘ Xᵀ - Jₘ`. -/
theorem relationMatrix_def :
    relationMatrix R m =
      GeneralLinear.genericMatrix R (m + m) *
          JFin m (GeneralLinear.coordinateHopfAlgebra R (m + m)) *
          (GeneralLinear.genericMatrix R (m + m))ᵀ -
        JFin m (GeneralLinear.coordinateHopfAlgebra R (m + m)) := by
  rw [relationMatrix, ConstantForm.relationMatrix_def, JFin_map]

/-- The set of defining relations: the entries of the relation matrix. -/
abbrev relationSet : Set (GeneralLinear.coordinateHopfAlgebra R (m + m)) :=
  ConstantForm.relationSet R (m + m) (JFin m R)

/-- **The symplectic Hopf ideal**: the ideal of the coordinate Hopf algebra of `GL (m + m)`
generated by the entries of `X Jₘ Xᵀ - Jₘ`. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R (m + m)) :=
  ConstantForm.definingHopfIdeal R (m + m) (JFin m R)

/-- The coordinate Hopf algebra of the symplectic subgroup scheme of `GL (m + m)`. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  ConstantForm.coordinateHopfAlgebra R (m + m) (JFin m R)

/-- The quotient coordinate morphism from `O(GL (m + m))` to the symplectic coordinate Hopf
algebra. -/
noncomputable abbrev coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R (m + m) ⟶ coordinateHopfAlgebra R m :=
  ConstantForm.coordinateMap R (m + m) (JFin m R)

/-- The symplectic coordinate map is the canonical quotient morphism by the defining Hopf
ideal. -/
theorem coordinateMap_def :
    coordinateMap R m =
      CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R (m + m))
        (definingHopfIdeal R m) :=
  ConstantForm.coordinateMap_def R (m + m) (JFin m R)

/-- The symplectic subgroup scheme of `GL (m + m)`. -/
noncomputable abbrev groupScheme := ConstantForm.groupScheme R (m + m) (JFin m R)

/-- The symplectic group scheme is the quotient spectrum of its coordinate Hopf algebra. -/
theorem groupScheme_def :
    groupScheme R m =
      CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra R (m + m))
        (definingHopfIdeal R m) :=
  ConstantForm.groupScheme_def R (m + m) (JFin m R)

/-- The symplectic coordinate Hopf algebra, bundled with its finite-type property. -/
noncomputable abbrev finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  ConstantForm.finiteTypeCoordinateHopfAlgebra R (m + m) (JFin m R)

/-- The finite-type package has the symplectic coordinate Hopf algebra as its underlying
object. -/
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R m).obj = coordinateHopfAlgebra R m :=
  ConstantForm.finiteTypeCoordinateHopfAlgebra_obj R (m + m) (JFin m R)

/-- The closed-subgroup inclusion from the symplectic subgroup scheme into the named general
linear group scheme. -/
noncomputable abbrev inclusion : groupScheme R m ⟶ GeneralLinear.groupScheme R (m + m) :=
  ConstantForm.inclusion R (m + m) (JFin m R)

/-- The symplectic inclusion is the specialization of the constant-form inclusion at the
standard alternating form. -/
theorem inclusion_eq_constantForm :
    inclusion R m = ConstantForm.inclusion R (m + m) (JFin m R) := by
  rfl

/-- The symplectic inclusion is the generic Hopf-ideal closed immersion at the defining Hopf
ideal. -/
theorem inclusion_def :
    inclusion R m =
      GeneralLinear.hopfIdealInclusion R (m + m) (definingHopfIdeal R m) :=
  ConstantForm.inclusion_def R (m + m) (JFin m R)

/-! ### Algebra-valued points -/

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- An ambient point belongs to the subgroup cut out by the symplectic Hopf ideal exactly when
its matrix is symplectic. -/
private theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R (m + m)) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ↔
      GeneralLinear.pointsMulEquiv (m + m) g ∈ GLSymplecticFin m A := by
  rw [ConstantForm.mem_definingPointsSubgroup_iff, GLSymplecticFin.mem_iff, JFin_map]

/-- Read a cut-out ambient point as a symplectic matrix. -/
private noncomputable def pointsSubgroupToGLSymplecticFin
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
      (CommAlgCat.of R A)) : GLSymplecticFin m A :=
  ⟨GeneralLinear.pointsMulEquiv (m + m) g.1,
    (mem_definingPointsSubgroup_iff R m g.1).mp g.2⟩

/-- Regard a symplectic matrix as a point in the cut-out ambient subgroup. -/
private noncomputable def glSymplecticFinToPointsSubgroup (g : GLSymplecticFin m A) :
    CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
      (CommAlgCat.of R A) :=
  ⟨(GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)).symm g.1,
    (mem_definingPointsSubgroup_iff R m _).mpr (by
      rw [MulEquiv.apply_symm_apply]
      exact g.2)⟩

/-- The subgroup of `GL (m + m) (A)` cut out by the symplectic Hopf ideal is
`TauCeti.GLSymplecticFin m A`. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ≃*
      GLSymplecticFin m A where
  toFun := pointsSubgroupToGLSymplecticFin R m
  invFun := glSymplecticFinToPointsSubgroup R m
  left_inv g := by
    apply Subtype.ext
    exact (GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)).symm_apply_apply g.1
  right_inv g := by
    apply Subtype.ext
    exact (GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)).apply_symm_apply g.1
  map_mul' g h := by
    apply Subtype.ext
    exact map_mul (GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)) g.1 h.1

/-- **The points identification**: the group of algebra-valued points of the symplectic
coordinate Hopf algebra is the symplectic subgroup of the general linear group. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A) ≃*
      GLSymplecticFin m A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
      (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)).app
      (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
    (definingPointsSubgroupMulEquiv R m)

/-- Internally, the symplectic point equivalence first forms the cut-out ambient subgroup point
and then reads it as a symplectic matrix. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    pointsMulEquiv R m (A := A) f =
      pointsSubgroupToGLSymplecticFin R m
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)).app
          (CommAlgCat.of R A)).hom f) :=
  rfl

/-- Under the symplectic and general-linear point equivalences, the quotient-point inclusion is
the ordinary inclusion of symplectic matrices into `GL (m + m)`. -/
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    GeneralLinear.pointsMulEquiv (m + m)
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv R m (A := A) f : GL (Fin (m + m)) A) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
    (CommAlgCat.of R A) f
  rw [pointsMulEquiv_apply_eq]
  exact congrArg
    (fun g => (pointsSubgroupToGLSymplecticFin R m g : GLSymplecticFin m A).1)
    hcomponent.symm

/-- The ambient point attached to a symplectic matrix is the general-linear point attached to
its ordinary inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : GLSymplecticFin m A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m)
        (CommAlgCat.of R A) ((pointsMulEquiv R m (A := A)).symm g) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)).symm g.1 := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) (m + m)).injective
  rw [pointsMulEquiv_coe, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type v} [CommRing B] [Algebra R B]

/-- The symplectic point equivalence is natural in the value algebra: postcomposition of Hopf
points agrees with entrywise mapping of symplectic matrices. -/
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (A := B) m
        (AlgHom.mapValue (H := coordinateHopfAlgebra R m) phi f) =
      GLSymplecticFin.map m A (phi : A →+* B)
        (pointsMulEquiv (R := R) (A := A) m f) := by
  apply Subtype.ext
  have hcoe_lhs := pointsMulEquiv_coe (R := R) (A := B) m
    (AlgHom.mapValue (H := coordinateHopfAlgebra R m) phi f)
  have hcoe_rhs := pointsMulEquiv_coe (R := R) (A := A) m f
  have hnatural := (CommHopfAlgCat.mapValue_quotientPointsHom
    (GeneralLinear.coordinateHopfAlgebra R (m + m)) (definingHopfIdeal R m) phi f).symm
  rw [← hcoe_lhs, hnatural,
    GeneralLinear.pointsMulEquiv_mapValue, hcoe_rhs, GLSymplecticFin.coe_map]

/-- The points identification, read in `Fin m ⊕ Fin m` coordinates: the points of the symplectic
coordinate Hopf algebra are `TauCeti.GLSymplectic (Fin m) A`. -/
noncomputable def pointsMulEquivGLSymplectic :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A) ≃*
      GLSymplectic (Fin m) A :=
  (pointsMulEquiv R m).trans (GLSymplecticFin.mulEquivGLSymplectic m A)

/-- On underlying general-linear elements, the `Fin m ⊕ Fin m` reading of a point is the
reindexing of its `Fin (m + m)` reading. -/
@[simp]
theorem coe_pointsMulEquivGLSymplectic
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R m) (CommAlgCat.of R A)) :
    ((pointsMulEquivGLSymplectic R m (A := A) f : GLSymplectic (Fin m) A) :
        GL (Fin m ⊕ Fin m) A) =
      Equiv.reindexGL finSumFinEquiv.symm A
        (pointsMulEquiv R m (A := A) f : GL (Fin (m + m)) A) :=
  GLSymplecticFin.coe_mulEquivGLSymplectic m A (pointsMulEquiv R m (A := A) f)

end Points

end TauCeti.Symplectic
