/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Subsystem
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic

/-!
# The Borel-type subgroup attached to a set of Kostant root subgroups

Let `U_ℤ = kostantForm e h` act on a rational representation `V` preserving an additive subgroup
`M ≤ V` with a weight basis `b`, so that the split torus `T(A) = 𝔾ₘ^κ(A)` acts diagonally on
`A ⊗[ℤ] M` and each designated root vector `eᵢ` acts nilpotently. For a set `S` of root indices,

```text
B_S(A) = U_S(A) ⬝ T(A) ≤ Aut_A(A ⊗[ℤ] M)
```

is the subgroup generated by the split torus together with the Kostant root subgroups indexed by
`S`. When `S` is a positive system of a Chevalley system this is the **Borel-type solvable subgroup
of points** out of which the Borel datum of a pinning of the Chevalley--Demazure group is built:
the torus, a group of points containing it, and the root vectors.

Three properties are proved. They are what separates `B_S` from an arbitrary join, though none of
them is the maximality that would make `B_S` a Borel subgroup on the nose. First, the torus
normalizes `U_S`, by the pinning equation
`t(s) xᵢ(u) t(s)⁻¹ = xᵢ(α(s) u)` of
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic`; so `U_S` is normal in
`B_S` for *every* index set `S`, with no closure hypothesis on `S`. Second, the commutator subgroup
of
`B_S` lies in `U_S`: modulo `U_S` the group is generated by the image of the abelian group
`κ → Aˣ`. Third, `B_S` is solvable as soon as `U_S` is, which by
`isNilpotent_kostantSubsystemSubgroup` holds whenever the indices of `S` carry a bounded height
that every nonzero bracket strictly raises — the situation of a positive system in the simply-laced
case. Finally the construction is functorial by inclusion: scalar extension along a morphism of
value rings `A ⟶ B` carries `B_S(A)` into `B_S(B)`, an inclusion that is in general strict, since
`B_S(B)` also contains the points built from parameters outside the image of `A`.

Nothing here divides by a factorial, so every statement holds over a value ring of any
characteristic; and nothing here asserts that `B_S` is *maximal* among solvable subgroups, which
is a geometric statement about the group scheme rather than about its points.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemSubgroup`: the subgroup `B_S(A)`
  generated by the split torus and the Kostant root subgroups indexed by `S`.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.map_kostantSubsystemSubgroup_conj_kostantTorusPoints`: a
  torus point normalizes `U_S(A)`.
* `kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup`:
  `U_S(A)` is normal in `B_S(A)`.
* `TauCeti.UniversalEnvelopingAlgebra.commutator_kostantTorusSubsystemSubgroup_le`: the derived
  subgroup of `B_S(A)` lies in `U_S(A)`.
* `TauCeti.UniversalEnvelopingAlgebra.isSolvable_kostantTorusSubsystemSubgroup`: `B_S(A)` is
  solvable under the height grading that makes `U_S(A)` nilpotent.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le`: scalar extension
  along a morphism of value rings carries `B_S(A)` into `B_S(B)`.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §§8.2 and 8.5.
* J. E. Humphreys, *Linear Algebraic Groups*, §§26--28.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open CategoryTheory TensorProduct WithConv
open scoped commutatorElement

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type*} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

variable (e : ι → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {η : Type*} (b : Module.Basis η ℤ M) (wt : η → κ → ℤ)

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

variable [Fintype κ]

/-! ## The torus normalizes a subsystem subgroup -/

/-- **The torus normalizes every subsystem subgroup.** Conjugation by a torus point carries the
root-subgroup element `xᵢ(t)` to `xᵢ(α(s) t)`, an element of the same root subgroup, so it
preserves the subgroup generated by any set of them.

No hypothesis on `S` is needed: unlike conjugation by a root subgroup, conjugation by the torus
does not move the index. The case `S = Set.univ` is
`map_kostantElementarySubgroup_conj_kostantTorusPoints`. -/
theorem map_kostantSubsystemSubgroup_conj_kostantTorusPoints
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (S : Set ι)
    (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) (s : κ → Aˣ) :
    (kostantSubsystemSubgroup e h ρ M hM hnil S A).map
        (MulAut.conj (kostantTorusPoints M b wt A s)) =
      kostantSubsystemSubgroup e h ρ M hM hnil S A := by
  have hconj : ∀ (i : ι), i ∈ S → ∀ (t : Multiplicative A),
      (MulAut.conj (kostantTorusPoints M b wt A s))
          (kostantRootSubgroupParam e h ρ M hM i (hnil i) A t) =
        kostantRootSubgroupParam e h ρ M hM i (hnil i) A
          (Multiplicative.ofAdd ((torusCharacter s (α i) : A) * Multiplicative.toAdd t)) :=
    fun i hiS t => kostantTorusPoints_conj_kostantRootSubgroupParam e h ρ M hM b wt hwt (hα i hiS)
      (hnil i) A s t
  refine le_antisymm ?_ ?_
  · rw [Subgroup.map_le_iff_le_comap]
    refine (kostantSubsystemSubgroup_le_iff e h ρ M hM hnil).2 fun i hiS t => ?_
    rw [Subgroup.mem_comap, MonoidHom.coe_ofClass, hconj i hiS]
    exact kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hiS A _
  · refine (kostantSubsystemSubgroup_le_iff e h ρ M hM hnil).2 fun i hiS t => ?_
    refine ⟨kostantRootSubgroupParam e h ρ M hM i (hnil i) A
      (Multiplicative.ofAdd ((↑(torusCharacter s (α i))⁻¹ : A) * Multiplicative.toAdd t)),
      kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hiS A _, ?_⟩
    rw [MonoidHom.coe_ofClass, hconj i hiS]
    congr 1
    simp only [toAdd_ofAdd, ← mul_assoc, Units.mul_inv, one_mul, ofAdd_toAdd]

/-- A torus point lies in the normalizer of every subsystem subgroup. -/
theorem kostantTorusPoints_mem_normalizer_kostantSubsystemSubgroup
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    (α : ι → κ → ℤ) (S : Set ι)
    (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
    (A : CommAlgCat.{w} ℤ) (s : κ → Aˣ) :
    kostantTorusPoints M b wt A s ∈
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil S A : Set _) :=
  Subgroup.mem_normalizer_iff_map_conj_eq.2
    (map_kostantSubsystemSubgroup_conj_kostantTorusPoints e h ρ M hM hnil b wt hwt α S hα A s)

/-! ## The subgroup generated by the torus and a set of root subgroups -/

/-- The subgroup of `Aut_A(A ⊗[ℤ] M)` generated by the split torus and the Kostant root subgroups
indexed by a set `S` of root indices. For suitable positive systems it supplies the group of
points underlying the Borel datum of a pinning; maximality among solvable subgroups is not asserted
here. -/
noncomputable def kostantTorusSubsystemSubgroup (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) :=
  kostantSubsystemSubgroup e h ρ M hM hnil S A ⊔ (kostantTorusPoints M b wt A).range

-- The public `rfl` lemma below cannot unfold `kostantTorusSubsystemSubgroup` itself: the module
-- system only lets an exported theorem unfold exposed definitions.
private theorem kostantTorusSubsystemSubgroup_eq_sup_def (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A =
      kostantSubsystemSubgroup e h ρ M hM hnil S A ⊔ (kostantTorusPoints M b wt A).range :=
  rfl

/-- The Borel-type subgroup is the join of the subsystem subgroup and the torus. -/
theorem kostantTorusSubsystemSubgroup_eq_sup (S : Set ι) (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A =
      kostantSubsystemSubgroup e h ρ M hM hnil S A ⊔ (kostantTorusPoints M b wt A).range :=
  kostantTorusSubsystemSubgroup_eq_sup_def e h ρ M hM hnil b wt S A

/-- The subsystem subgroup is contained in the Borel-type subgroup attached to the same index
set. -/
theorem kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup (S : Set ι)
    (A : CommAlgCat.{w} ℤ) :
    kostantSubsystemSubgroup e h ρ M hM hnil S A ≤
      kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A :=
  (kostantTorusSubsystemSubgroup_eq_sup e h ρ M hM hnil b wt S A) ▸ le_sup_left

/-- A root-subgroup element with index in `S` lies in the Borel-type subgroup. -/
theorem kostantRootSubgroupParam_mem_kostantTorusSubsystemSubgroup {S : Set ι} {i : ι}
    (hiS : i ∈ S) (A : CommAlgCat.{w} ℤ) (t : Multiplicative A) :
    kostantRootSubgroupParam e h ρ M hM i (hnil i) A t ∈
      kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A :=
  kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A
    (kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hiS A t)

/-- Every torus point lies in the Borel-type subgroup. -/
theorem kostantTorusPoints_mem_kostantTorusSubsystemSubgroup (S : Set ι) (A : CommAlgCat.{w} ℤ)
    (s : κ → Aˣ) :
    kostantTorusPoints M b wt A s ∈ kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A :=
  (kostantTorusSubsystemSubgroup_eq_sup e h ρ M hM hnil b wt S A) ▸
    Subgroup.mem_sup_right (MonoidHom.mem_range.2 ⟨s, rfl⟩)

/-- **Elimination principle.** A subgroup contains `B_S(A)` exactly when it contains every torus
point and every root-subgroup element indexed by `S`. -/
theorem kostantTorusSubsystemSubgroup_le_iff {S : Set ι} {A : CommAlgCat.{w} ℤ}
    {P : Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M))} :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A ≤ P ↔
      (∀ i ∈ S, ∀ t : Multiplicative A,
          kostantRootSubgroupParam e h ρ M hM i (hnil i) A t ∈ P) ∧
        ∀ s : κ → Aˣ, kostantTorusPoints M b wt A s ∈ P := by
  rw [kostantTorusSubsystemSubgroup_eq_sup, sup_le_iff, kostantSubsystemSubgroup_le_iff]
  exact and_congr_right' ⟨fun hle s => hle (MonoidHom.mem_range.2 ⟨s, rfl⟩),
    fun hs => by rintro - ⟨s, rfl⟩; exact hs s⟩

/-- The Borel-type subgroup grows with the index set. -/
@[gcongr]
theorem kostantTorusSubsystemSubgroup_mono {S T : Set ι} (hST : S ⊆ T) (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A ≤
      kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt T A :=
  (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
    ⟨fun _ hiS t => kostantRootSubgroupParam_mem_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt
      (hST hiS) A t,
     kostantTorusPoints_mem_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt T A⟩

/-- With no root subgroups adjoined, the Borel-type subgroup is the torus. -/
@[simp] theorem kostantTorusSubsystemSubgroup_empty (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt ∅ A =
      (kostantTorusPoints M b wt A).range := by
  rw [kostantTorusSubsystemSubgroup_eq_sup, kostantSubsystemSubgroup_empty, bot_sup_eq]

/-- With every root subgroup adjoined, the Borel-type subgroup is generated by the elementary
group and the torus. -/
@[simp] theorem kostantTorusSubsystemSubgroup_univ (A : CommAlgCat.{w} ℤ) :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt Set.univ A =
      kostantElementarySubgroup e h ρ M hM hnil A ⊔ (kostantTorusPoints M b wt A).range := by
  rw [kostantTorusSubsystemSubgroup_eq_sup, kostantSubsystemSubgroup_univ]

/-! ## The subsystem subgroup is normal, with abelian quotient -/

section Normal

variable (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
variable (α : ι → κ → ℤ) (S : Set ι)
variable (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
variable (A : CommAlgCat.{w} ℤ)

include hwt hα in
/-- The Borel-type subgroup normalizes its subsystem subgroup: the torus does by the pinning
equation, and the subsystem subgroup normalizes itself. -/
theorem kostantTorusSubsystemSubgroup_le_normalizer :
    kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A ≤
      Subgroup.normalizer (kostantSubsystemSubgroup e h ρ M hM hnil S A : Set _) :=
  (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
    ⟨fun _ hiS t => Subgroup.le_normalizer
      (kostantRootSubgroupParam_mem_kostantSubsystemSubgroup e h ρ M hM hnil hiS A t),
     kostantTorusPoints_mem_normalizer_kostantSubsystemSubgroup e h ρ M hM hnil b wt hwt α S hα A⟩

include hwt hα in
/-- **The root-generated subsystem subgroup is normal in the Borel-type subgroup.** -/
theorem kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup :
    ((kostantSubsystemSubgroup e h ρ M hM hnil S A).subgroupOf
      (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A)).Normal :=
  (Subgroup.normal_subgroupOf_iff_le_normalizer
      (kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A)).2
    (kostantTorusSubsystemSubgroup_le_normalizer e h ρ M hM hnil b wt hwt α S hα A)

include hwt hα in
/-- **The derived subgroup of the Borel-type subgroup lies in the subsystem subgroup.** Modulo
`U_S(A)` the group `B_S(A)` is generated by the image of the abelian group `κ → Aˣ` of torus
points, so its commutator subgroup already lies in `U_S(A)`.

Only the normalizing property of the torus is used, so this holds for an arbitrary index set `S`;
the commutator relations among the root subgroups are not needed. -/
theorem commutator_kostantTorusSubsystemSubgroup_le :
    ⁅kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A,
        kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A⁆ ≤
      kostantSubsystemSubgroup e h ρ M hM hnil S A := by
  let U := kostantSubsystemSubgroup e h ρ M hM hnil S A
  let T := (kostantTorusPoints M b wt A).range
  let B' := kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A
  have hUB : U ≤ B' :=
    kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A
  have hTB : T ≤ B' := by
    dsimp only [B']
    rw [kostantTorusSubsystemSubgroup_eq_sup]
    exact le_sup_right
  let N := U.subgroupOf B'
  let H := T.subgroupOf B'
  have hnormal : N.Normal :=
    kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup
      e h ρ M hM hnil b wt hwt α S hα A
  have htop : N ⊔ H = ⊤ := by
    dsimp only [N, H]
    rw [← Subgroup.subgroupOf_sup hUB hTB]
    have hsup : U ⊔ T = B' := by
      dsimp only [U, T, B']
      rw [kostantTorusSubsystemSubgroup_eq_sup]
    rw [hsup, Subgroup.subgroupOf_self]
  have hcomm : _root_.commutator B' ≤ N :=
    @Subgroup.Normal.commutator_le_of_self_sup_commutative_eq_top B' _ N hnormal H htop
      inferInstance
  rw [← B'.map_subtype_commutator, Subgroup.map_le_iff_le_comap]
  exact hcomm

end Normal

/-! ## Solvability -/

section Solvable

variable (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
variable (α : ι → κ → ℤ) {S : Set ι}
variable (hα : ∀ i ∈ S, ∀ j, ⁅h j, e i⁆ = (α i j : ℚ) • e i)
variable (A : CommAlgCat.{w} ℤ)

include hwt hα in
/-- **The Borel-type subgroup is solvable whenever its subsystem subgroup is.** The quotient by
the subsystem subgroup is abelian by `commutator_kostantTorusSubsystemSubgroup_le`. -/
theorem isSolvable_kostantTorusSubsystemSubgroup_of_isSolvable
    (hsolv : Group.IsSolvable (kostantSubsystemSubgroup e h ρ M hM hnil S A)) :
    Group.IsSolvable (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A) := by
  have hle := kostantSubsystemSubgroup_le_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A
  have hcomm := commutator_kostantTorusSubsystemSubgroup_le
    e h ρ M hM hnil b wt hwt α S hα A
  have hnormal := kostantSubsystemSubgroup_normal_subgroupOf_kostantTorusSubsystemSubgroup
    e h ρ M hM hnil b wt hwt α S hα A
  rw [Group.isSolvable_iff_subgroup_quotient
    ((kostantSubsystemSubgroup e h ρ M hM hnil S A).subgroupOf
      (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A))]
  refine ⟨?_, ?_⟩
  · -- The subsystem subgroup, viewed inside the Borel-type subgroup, is the same group.
    have := hsolv
    exact Group.isSolvable_of_isSolvable_injective
      (f := (Subgroup.subgroupOfEquivOfLe hle).toMonoidHom)
      (Subgroup.subgroupOfEquivOfLe hle).injective
  · -- The quotient is abelian because every commutator lies in the subsystem subgroup.
    refine Group.isSolvable_of_comm fun x y => ?_
    induction x using QuotientGroup.induction_on with
    | H x =>
      induction y using QuotientGroup.induction_on with
      | H y =>
        rw [← QuotientGroup.mk_mul, ← QuotientGroup.mk_mul, QuotientGroup.eq,
          Subgroup.mem_subgroupOf]
        have key := Subgroup.commutator_le.1 hcomm _ (inv_mem y.2) _ (inv_mem x.2)
        rw [commutatorElement_def, inv_inv, inv_inv] at key
        have hxy : (((x * y)⁻¹ * (y * x) :
              kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A) :
            LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M)) =
              (y : LinearMap.GeneralLinearGroup A (A ⊗[ℤ] M))⁻¹ * (x : _)⁻¹ * (y : _) *
                (x : _) := by
          push_cast
          group
        rw [hxy]
        exact key

include hwt hα in
/-- **The Borel-type subgroup of a graded closed set of roots is solvable.** Under the hypotheses
that make `U_S(A)` nilpotent — every index of `S` has bounded height, and a nonzero bracket of two
root vectors indexed in `S` is an integer multiple of a third root vector, indexed in `S`, of
strictly larger height and central for both — the subgroup generated by the split torus and the
root subgroups indexed by `S` is solvable over every value ring.

For a simply-laced Chevalley system and `S` the positive roots this is the solvability of the
Borel-type subgroup of points underlying the Borel datum of the pinning. -/
theorem isSolvable_kostantTorusSubsystemSubgroup {ht : ι → ℕ} {N : ℕ} (hbdd : ∀ i ∈ S, ht i ≤ N)
    (hgrade : ∀ i ∈ S, ∀ j ∈ S, ⁅e i, e j⁆ = 0 ∨
      ∃ k ∈ S, ht i < ht k ∧ ∃ c : ℤ,
        ⁅e i, e j⁆ = c • e k ∧ ⁅e i, e k⁆ = 0 ∧ ⁅e j, e k⁆ = 0) :
    Group.IsSolvable (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A) := by
  have := isNilpotent_kostantSubsystemSubgroup e h ρ M hM hnil hbdd hgrade A
  exact isSolvable_kostantTorusSubsystemSubgroup_of_isSolvable
    e h ρ M hM hnil b wt hwt α hα A
    inferInstance

end Solvable

/-! ## Change of value ring -/

section Naturality

variable {A B : CommAlgCat.{w} ℤ}

/-- **Change of value ring.** Scalar extension along a morphism of value rings carries the
Borel-type subgroup attached to an index set into the Borel-type subgroup attached to the same
index set. This is functoriality by inclusion, not by equality: already for the torus part the
image lands in the points whose parameters come from `A`, so the inclusion is in general strict. -/
theorem map_kostantTorusSubsystemSubgroup_le (S : Set ι) (φ : A ⟶ B) :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S A).map
        (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom ≤
      kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S B := by
  rw [Subgroup.map_le_iff_le_comap]
  refine (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
    ⟨fun i hiS t => ?_, fun s => ?_⟩
  · have hx : (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom
        (kostantRootSubgroupParam e h ρ M hM i (hnil i) A t) =
      kostantRootSubgroupParam e h ρ M hM i (hnil i) B
        (Multiplicative.ofAdd (φ.hom (Multiplicative.toAdd t))) :=
      mapScalarExtensionAutomorphisms_kostantRootSubgroupParam e h ρ M hM i (hnil i) φ t
    rw [Subgroup.mem_comap, hx]
    exact kostantRootSubgroupParam_mem_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt hiS B _
  · have hx : (GeneralLinear.mapScalarExtensionAutomorphisms (V := M) φ).hom
        (kostantTorusPoints M b wt A s) =
      kostantTorusPoints M b wt B fun j => Units.map φ.hom.toRingHom.toMonoidHom (s j) :=
      mapScalarExtensionAutomorphisms_kostantTorusPoints M b wt φ s
    rw [Subgroup.mem_comap, hx]
    exact kostantTorusPoints_mem_kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S B _

end Naturality

end TauCeti.UniversalEnvelopingAlgebra
