/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Matrix.BaseChange
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.LieAlgebra.Basic
public import Mathlib.RingTheory.Flat.Basic

/-!
# Base change of the pinned Dynkin-type Lie algebra

The pinned Lie algebra `TauCeti.DynkinType.lieAlgebra` is Geck's explicit matrix construction over
`ℚ`. This file extends the underlying pinned root system to an arbitrary characteristic-zero
domain `K` equipped with a rational algebra structure and identifies the resulting Geck Lie
algebra with `K ⊗[ℚ] TauCeti.DynkinType.lieAlgebra t ht`.

The comparison is explicit. Mathlib's matrix scalar-extension equivalence sends every numbered
matrix `hᵢ`, `eᵢ`, and `fᵢ` over `ℚ` to the matrix constructed from the scalar-extended root
system over `K`; because both Lie algebras are generated by those matrices, it restricts to the
required Lie equivalence. This makes Mathlib's algebraically-closed-field results about Geck's
construction available to descent arguments for the pinned rational carrier.

That descent is the gap the pinned carrier still has. Mathlib proves Geck's Lie algebra
semisimple only over an algebraically closed field, while the
`SimplyConnectedRootDatum/LieAlgebra/Basic.lean` module records that `ℚ` is not one. It therefore
leaves semisimplicity of `TauCeti.DynkinType.lieAlgebra` unclaimed;
`TauCeti/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/KostantForm.lean` inherits the same
gap. Taking `K` to be an algebraic closure of `ℚ` turns those results into statements about
`K ⊗[ℚ] TauCeti.DynkinType.lieAlgebra t ht`, from which `LieModule.traceForm_baseChange` carries
the nondegenerate Killing form back to `ℚ`. The Chevalley `ℤ`-form is a lattice in that Lie
algebra, while the Kostant `ℤ`-form is an integral form in its universal enveloping algebra.
Thus this comparison is a prerequisite of the construction rather than a parallel to it: positive
characteristic enters only afterwards, when the resulting integral data is base changed along
`ℤ → k`.

## Main definitions

* `TauCeti.DynkinType.rootSystemBaseChange`: the pinned rational root system extended to `K`.
* `TauCeti.DynkinType.baseChangeBase`: its Bourbaki-numbered base.
* `TauCeti.DynkinType.lieAlgebraBaseChange`: Geck's Lie algebra over `K` for that base.
* `TauCeti.DynkinType.lieAlgebraBaseChangeEquiv`: the Lie equivalence from the scalar extension of
  the pinned rational Lie algebra.

## References

The matrix construction is M. Geck, *On the construction of semisimple Lie algebras and Chevalley
groups*, Proc. Amer. Math. Soc. **145** (2017), 3233--3247. This is a prerequisite for the explicit
Chevalley--Demazure construction in Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, consumed
by milestone L0 of `TauCetiRoadmap/CFSGStatement/README.md`.
-/

public section

namespace TauCeti.DynkinType

open RootPairing.GeckConstruction
open scoped TensorProduct

noncomputable section

attribute [local instance 100] LieRing.ofAssociativeRing

variable (t : DynkinType) (ht : t.Valid) (K : Type*)
  [CommRing K] [IsDomain K] [Algebra ℚ K]

local instance : CharZero K := Algebra.charZero_of_charZero ℚ K

omit [IsDomain K] in
private theorem algebraMap_rat_intCast (z : ℤ) :
    algebraMap ℚ K (z : ℚ) = (z : K) :=
  map_intCast (algebraMap ℚ K) z

omit [IsDomain K] in
private theorem algebraMap_rat_abs_intCast (z : ℤ) :
    algebraMap ℚ K |(z : ℚ)| = (↑(|z| : ℤ) : K) := by
  rw [← Int.cast_abs]
  exact algebraMap_rat_intCast K |z|

/-- The pinned rational root system of a Dynkin type, extended to a characteristic-zero domain. -/
abbrev rootSystemBaseChange :
    RootPairing (Fin t.numRoots) K (Fin t.rank → K) (Fin t.rank → K) :=
  rootPairingBaseChange K (t.rationalRootSystem ht) (t.toLinearMap_rationalRootSystem ht)

/-- The pinned Bourbaki-numbered base after extending the rational root system to `K`. -/
abbrev baseChangeBase : (t.rootSystemBaseChange ht K).Base :=
  rootPairingBaseChangeBase K (t.rationalRootSystem ht)
    (t.toLinearMap_rationalRootSystem ht) (t.rationalBase ht)

/-- The support of the scalar-extended base is canonically the support of the rational base. -/
def supportBaseChangeEquiv :
    (t.baseChangeBase ht K).support ≃ (t.rationalBase ht).support :=
  supportEquivRootPairingBaseChangeBase K (t.rationalRootSystem ht)
    (t.toLinearMap_rationalRootSystem ht) (t.rationalBase ht)

@[simp] theorem coe_supportBaseChangeEquiv (i : (t.baseChangeBase ht K).support) :
    ((t.supportBaseChangeEquiv ht K i : (t.rationalBase ht).support) : Fin t.numRoots) = i :=
  coe_supportEquivRootPairingBaseChangeBase ..

@[simp] theorem coe_supportBaseChangeEquiv_symm (i : (t.rationalBase ht).support) :
    (((t.supportBaseChangeEquiv ht K).symm i : (t.baseChangeBase ht K).support) :
      Fin t.numRoots) = i := by
  exact (coe_supportBaseChangeEquiv t ht K
    ((t.supportBaseChangeEquiv ht K).symm i)).symm.trans
      (congrArg Subtype.val ((t.supportBaseChangeEquiv ht K).apply_symm_apply i))

@[simp] private theorem supportEquivRootPairingBaseChangeBase_supportBaseChangeEquiv_symm
    (i : (t.rationalBase ht).support) :
    supportEquivRootPairingBaseChangeBase K (t.rationalRootSystem ht)
        (t.toLinearMap_rationalRootSystem ht) (t.rationalBase ht)
        ((t.supportBaseChangeEquiv ht K).symm i) = i := by
  simpa only [supportBaseChangeEquiv] using
    (supportEquivRootPairingBaseChangeBase K (t.rationalRootSystem ht)
      (t.toLinearMap_rationalRootSystem ht) (t.rationalBase ht)).apply_symm_apply i

instance instIsCrystallographicRootSystemBaseChange :
    (t.rootSystemBaseChange ht K).IsCrystallographic :=
  isCrystallographic_rootPairingBaseChange ..

instance instIsRootSystemRootSystemBaseChange : (t.rootSystemBaseChange ht K).IsRootSystem where
  span_root_eq_top := span_range_root_rootPairingBaseChange_eq_top K _ _
    (span_range_root_rationalRootSystem_eq_top t ht)
  span_coroot_eq_top := span_range_coroot_rootPairingBaseChange_eq_top K _ _
    (span_range_coroot_rationalRootSystem_eq_top t ht)

instance instIsReducedRootSystemBaseChange : (t.rootSystemBaseChange ht K).IsReduced :=
  isReduced_rootPairingBaseChange K _ _

/-- The scalar-extended pinned base realizes the same Dynkin type and Bourbaki numbering. -/
theorem hasCartanType_baseChange :
    HasCartanType (t.rootSystemBaseChange ht K) (t.baseChangeBase ht K) t := by
  obtain ⟨e, he⟩ := (hasCartanType_iff _ _).1 (t.hasCartanType_rationalRootSystem ht)
  refine (hasCartanType_iff _ _).2
    ⟨(supportEquivRootPairingBaseChangeBase K _ _ _).trans e, fun i j ↦ ?_⟩
  exact (cartanMatrix_rootPairingBaseChangeBase K _ _ _ i j).trans (he _ _)

/-- The index equivalence identifying the matrix coordinates before and after scalar extension.
The root indices are unchanged, and the two base supports have the same underlying indices. -/
def geckIndexBaseChangeEquiv :
    ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) ≃ t.GeckIndex ht :=
  Equiv.sumCongr (t.supportBaseChangeEquiv ht K) (Equiv.refl _)

/-- Geck's explicit matrix Lie algebra for the scalar-extended pinned root system. -/
def lieAlgebraBaseChange :
    LieSubalgebra K (Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
      ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) :=
  RootPairing.GeckConstruction.lieAlgebra (t.baseChangeBase ht K)

@[simp] theorem lieAlgebraBaseChange_def :
    t.lieAlgebraBaseChange ht K =
      RootPairing.GeckConstruction.lieAlgebra (t.baseChangeBase ht K) := (rfl)

/-! ## The Geck generators under base change -/

/-- The Cartan generators of Geck's construction commute with scalar extension. -/
@[simp]
theorem h_baseChangeBase (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K))
        (h (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i)) =
      (h (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
        (algebraMap ℚ K) := by
  classical
  ext (j | j) (k | k) <;>
    simp [h, geckIndexBaseChangeEquiv, Matrix.coe_reindexAlgEquiv,
      Matrix.reindex_apply, Matrix.diagonal_apply, rootSystemBaseChange,
      apply_ite (algebraMap ℚ K)]

/-- The raising generators of Geck's construction commute with scalar extension. -/
@[simp]
theorem e_baseChangeBase (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K))
        (e (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i)) =
      (e (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
        (algebraMap ℚ K) := by
  classical
  have hpi : Function.Injective (Pi.algebraMap (Fin t.rank) ℚ K) := fun x y hxy ↦
    funext fun k ↦ FaithfulSMul.algebraMap_injective ℚ K (congrFun hxy k)
  have hs (j : (t.rationalBase ht).support) :
      (t.supportBaseChangeEquiv ht K).symm j =
        (t.supportBaseChangeEquiv ht K).symm i ↔ j = i :=
    (t.supportBaseChangeEquiv ht K).symm.injective.eq_iff
  ext (j | j) (k | k) <;>
    simp [e, geckIndexBaseChangeEquiv, Matrix.coe_reindexAlgEquiv,
      Matrix.reindex_apply, Matrix.of_apply, coe_supportBaseChangeEquiv_symm,
      hs, baseChangeBase, rootSystemBaseChange,
      chainBotCoeff_rootPairingBaseChange,
      ← map_add, hpi.eq_iff, apply_ite (algebraMap ℚ K),
      algebraMap_rat_abs_intCast]
  all_goals split_ifs <;> simp

/-- The lowering generators of Geck's construction commute with scalar extension. -/
@[simp]
theorem f_baseChangeBase (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K))
        (f (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i)) =
      (f (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
        (algebraMap ℚ K) := by
  classical
  have hpi : Function.Injective (Pi.algebraMap (Fin t.rank) ℚ K) := fun x y hxy ↦
    funext fun k ↦ FaithfulSMul.algebraMap_injective ℚ K (congrFun hxy k)
  have hs (j : (t.rationalBase ht).support) :
      (t.supportBaseChangeEquiv ht K).symm j =
        (t.supportBaseChangeEquiv ht K).symm i ↔ j = i :=
    (t.supportBaseChangeEquiv ht K).symm.injective.eq_iff
  ext (j | j) (k | k) <;>
    simp [f, geckIndexBaseChangeEquiv, Matrix.coe_reindexAlgEquiv,
      Matrix.reindex_apply, Matrix.of_apply, coe_supportBaseChangeEquiv_symm,
      hs, baseChangeBase, rootSystemBaseChange,
      chainTopCoeff_rootPairingBaseChange,
      ← map_sub, hpi.eq_iff, apply_ite (algebraMap ℚ K),
      algebraMap_rat_abs_intCast]

/-! ## Restriction to the generated Lie algebras -/

/-- Scalar extension of the ambient rational matrix Lie algebra, followed by the canonical
reindexing to the scalar-extended base support. -/
noncomputable def ambientLieAlgebraBaseChangeEquiv :
    LieEquiv K (K ⊗[ℚ] Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ)
      (Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
        ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) :=
  (TauCeti.matrixBaseChangeLieEquiv (t.GeckIndex ht) ℚ K).trans
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm).toLieEquiv

@[simp] theorem ambientLieAlgebraBaseChangeEquiv_tmul (a : K)
    (M : Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ) :
    t.ambientLieAlgebraBaseChangeEquiv ht K (a ⊗ₜ[ℚ] M) =
      a • (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
        (M.map (algebraMap ℚ K)) := by
  simp [ambientLieAlgebraBaseChangeEquiv]

private theorem reindex_symm_map_h (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
        ((h (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
          (algebraMap ℚ K)) =
      h (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
        ((t.supportBaseChangeEquiv ht K).symm i) := by
  apply (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K)).injective
  simp

private theorem reindex_symm_map_e (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
        ((e (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
          (algebraMap ℚ K)) =
      e (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
        ((t.supportBaseChangeEquiv ht K).symm i) := by
  apply (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K)).injective
  simp

private theorem reindex_symm_map_f (i : (t.rationalBase ht).support) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
        ((f (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i).map
          (algebraMap ℚ K)) =
      f (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
        ((t.supportBaseChangeEquiv ht K).symm i) := by
  apply (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K)).injective
  simp

private theorem reindex_symm_map_mem_lieAlgebraBaseChange
    (M : Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ) (hM : M ∈ t.lieAlgebra ht) :
    (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
        (M.map (algebraMap ℚ K)) ∈ t.lieAlgebraBaseChange ht K := by
  rw [lieAlgebra_def] at hM
  simp only [RootPairing.GeckConstruction.lieAlgebra] at hM
  induction hM using LieSubalgebra.lieSpan_induction with
  | mem M hM =>
      rcases hM with (hM | hM) | hM
      · obtain ⟨i, rfl⟩ := hM
        rw [reindex_symm_map_h]
        exact LieSubalgebra.subset_lieSpan (Or.inl (Or.inl ⟨_, rfl⟩))
      · obtain ⟨i, rfl⟩ := hM
        rw [reindex_symm_map_e]
        exact LieSubalgebra.subset_lieSpan (Or.inl (Or.inr ⟨_, rfl⟩))
      · obtain ⟨i, rfl⟩ := hM
        rw [reindex_symm_map_f]
        exact LieSubalgebra.subset_lieSpan (Or.inr ⟨_, rfl⟩)
  | zero => simp
  | add M N _ _ hM hN =>
      rw [Matrix.map_add _ (map_add (algebraMap ℚ K)), map_add]
      exact (t.lieAlgebraBaseChange ht K).add_mem hM hN
  | smul a M _ hM =>
      rw [Matrix.map_smulₛₗ (algebraMap ℚ K) (algebraMap ℚ K) a
        (map_mul (algebraMap ℚ K) a), map_smul]
      exact (t.lieAlgebraBaseChange ht K).smul_mem (algebraMap ℚ K a) hM
  | lie M N _ _ hM hN =>
      have hmap_lie : (⁅M, N⁆).map (algebraMap ℚ K) =
          ⁅M.map (algebraMap ℚ K), N.map (algebraMap ℚ K)⁆ := by
        simp only [LieRing.of_associative_ring_bracket, Matrix.map_sub _
          (map_sub (algebraMap ℚ K)), Matrix.map_mul]
      rw [hmap_lie]
      have heq :
          (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
              ⁅M.map (algebraMap ℚ K), N.map (algebraMap ℚ K)⁆ =
            ⁅(Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
                (M.map (algebraMap ℚ K)),
              (Matrix.reindexAlgEquiv K K (t.geckIndexBaseChangeEquiv ht K).symm)
                (N.map (algebraMap ℚ K))⁆ :=
        (Matrix.reindexAlgEquiv K K
          (t.geckIndexBaseChangeEquiv ht K).symm).toLieEquiv.map_lie _ _
      rw [heq]
      exact (t.lieAlgebraBaseChange ht K).lie_mem hM hN

/-- Scalar extension of the inclusion of the pinned rational Lie algebra into its ambient
matrix Lie algebra. -/
private noncomputable def lieAlgebraBaseChangeIncl :
    LieHom K (K ⊗[ℚ] t.lieAlgebra ht)
      (K ⊗[ℚ] Matrix (t.GeckIndex ht) (t.GeckIndex ht) ℚ) where
  __ := LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap
  map_lie' {x y} := by
    induction x with
    | tmul a x =>
      induction y with
      | tmul b y => simp [LieAlgebra.ExtendScalars.bracket_tmul]
      | add y z hy hz =>
        simp only [lie_add]
        calc
          _ = (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) ⁅a ⊗ₜ[ℚ] x, y⁆ +
              (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) ⁅a ⊗ₜ[ℚ] x, z⁆ :=
            (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap).map_add _ _
          _ = ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) (a ⊗ₜ[ℚ] x),
                (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) y⁆ +
              ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) (a ⊗ₜ[ℚ] x),
                (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) z⁆ :=
            congrArg₂ (fun p q ↦ p + q) hy hz
          _ = ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) (a ⊗ₜ[ℚ] x),
                (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) (y + z)⁆ := by
            rw [(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap).map_add, lie_add]
    | add x z hx hz =>
      simp only [add_lie]
      calc
        _ = (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) ⁅x, y⁆ +
            (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) ⁅z, y⁆ :=
          (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap).map_add _ _
        _ = ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) x,
              (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) y⁆ +
            ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) z,
              (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) y⁆ :=
          congrArg₂ (fun p q ↦ p + q) hx hz
        _ = ⁅(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) (x + z),
              (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap) y⁆ := by
          rw [(LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap).map_add, add_lie]

/-- The ambient scalar-extension map restricted to tensors of the pinned rational Lie algebra. -/
private noncomputable def lieAlgebraBaseChangeHom :
    LieHom K (K ⊗[ℚ] t.lieAlgebra ht)
      (Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
        ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) :=
  t.ambientLieAlgebraBaseChangeEquiv ht K |>.toLieHom.comp
    (t.lieAlgebraBaseChangeIncl ht K)

private theorem lieAlgebraBaseChangeIncl_injective :
    Function.Injective (t.lieAlgebraBaseChangeIncl ht K) := by
  exact Module.Flat.lTensor_preserves_injective_linearMap
    (M := K) (t.lieAlgebra ht).incl.toLinearMap Subtype.val_injective

private theorem lieAlgebraBaseChangeHom_injective :
    Function.Injective (t.lieAlgebraBaseChangeHom ht K) :=
  (t.ambientLieAlgebraBaseChangeEquiv ht K).injective.comp
    (t.lieAlgebraBaseChangeIncl_injective ht K)

/-- The restricted ambient map has image exactly the Geck Lie algebra constructed after scalar
extension. -/
private theorem lieAlgebraBaseChangeHom_range :
    (t.lieAlgebraBaseChangeHom ht K).range = t.lieAlgebraBaseChange ht K := by
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x with
    | tmul a x =>
      simpa [lieAlgebraBaseChangeHom, lieAlgebraBaseChangeIncl] using
        (t.lieAlgebraBaseChange ht K).smul_mem a
          (reindex_symm_map_mem_lieAlgebraBaseChange t ht K x x.property)
    | add x y hx hy => simpa using (t.lieAlgebraBaseChange ht K).add_mem hx hy
  · rw [lieAlgebraBaseChange_def, RootPairing.GeckConstruction.lieAlgebra,
      LieSubalgebra.lieSpan_le]
    rintro _ ((⟨j, rfl⟩ | ⟨j, rfl⟩) | ⟨j, rfl⟩)
    · let i := t.supportBaseChangeEquiv ht K j
      refine ⟨1 ⊗ₜ[ℚ] ⟨h (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, ?_⟩, ?_⟩
      · rw [lieAlgebra_def, RootPairing.GeckConstruction.lieAlgebra]
        exact LieSubalgebra.subset_lieSpan (Or.inl (Or.inl ⟨i, rfl⟩))
      · simp [lieAlgebraBaseChangeHom, lieAlgebraBaseChangeIncl,
          reindex_symm_map_h, i]
    · let i := t.supportBaseChangeEquiv ht K j
      refine ⟨1 ⊗ₜ[ℚ] ⟨e (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, ?_⟩, ?_⟩
      · rw [lieAlgebra_def, RootPairing.GeckConstruction.lieAlgebra]
        exact LieSubalgebra.subset_lieSpan (Or.inl (Or.inr ⟨i, rfl⟩))
      · simp [lieAlgebraBaseChangeHom, lieAlgebraBaseChangeIncl,
          reindex_symm_map_e, i]
    · let i := t.supportBaseChangeEquiv ht K j
      refine ⟨1 ⊗ₜ[ℚ] ⟨f (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, ?_⟩, ?_⟩
      · rw [lieAlgebra_def, RootPairing.GeckConstruction.lieAlgebra]
        exact LieSubalgebra.subset_lieSpan (Or.inr ⟨i, rfl⟩)
      · simp [lieAlgebraBaseChangeHom, lieAlgebraBaseChangeIncl,
          reindex_symm_map_f, i]

/-- The scalar-extension map with codomain restricted to the Geck Lie algebra over `K`. -/
private noncomputable def lieAlgebraBaseChangeLieHom :
    LieHom K (K ⊗[ℚ] t.lieAlgebra ht) (t.lieAlgebraBaseChange ht K) where
  toFun x := ⟨t.lieAlgebraBaseChangeHom ht K x, by
    have hx := (t.lieAlgebraBaseChangeHom ht K).mem_range_self x
    rwa [lieAlgebraBaseChangeHom_range] at hx⟩
  map_add' x y := Subtype.ext (map_add (t.lieAlgebraBaseChangeHom ht K) x y)
  map_smul' a x := Subtype.ext (map_smul (t.lieAlgebraBaseChangeHom ht K) a x)
  map_lie' {x y} := Subtype.ext ((t.lieAlgebraBaseChangeHom ht K).map_lie x y)

@[simp] private theorem coe_lieAlgebraBaseChangeLieHom_apply
    (x : K ⊗[ℚ] t.lieAlgebra ht) :
    (t.lieAlgebraBaseChangeLieHom ht K x :
      Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
        ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) =
      t.ambientLieAlgebraBaseChangeEquiv ht K
        (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap x) :=
  rfl

private theorem lieAlgebraBaseChangeLieHom_bijective :
    Function.Bijective (t.lieAlgebraBaseChangeLieHom ht K) := by
  constructor
  · intro x y hxy
    apply t.lieAlgebraBaseChangeHom_injective ht K
    exact congrArg Subtype.val hxy
  · intro y
    have hy : (y : Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
        ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) ∈
        (t.lieAlgebraBaseChangeHom ht K).range := by
      rw [lieAlgebraBaseChangeHom_range]
      exact y.property
    obtain ⟨x, hx⟩ := hy
    exact ⟨x, Subtype.ext hx⟩

/-- **The pinned Dynkin-type Lie algebra commutes with extension of scalars.** For every
characteristic-zero rational algebra domain `K`, scalar extension of the rational pinned carrier
is canonically Lie equivalent to Geck's matrix construction on the scalar-extended pinned root
system. -/
noncomputable def lieAlgebraBaseChangeEquiv :
    LieEquiv K (K ⊗[ℚ] t.lieAlgebra ht) (t.lieAlgebraBaseChange ht K) :=
  LieEquiv.ofBijective (t.lieAlgebraBaseChangeLieHom ht K)
    (t.lieAlgebraBaseChangeLieHom_bijective ht K)

@[simp] theorem coe_lieAlgebraBaseChangeEquiv_apply
    (x : K ⊗[ℚ] t.lieAlgebra ht) :
    (t.lieAlgebraBaseChangeEquiv ht K x :
      Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
        ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) =
      t.ambientLieAlgebraBaseChangeEquiv ht K
        (LinearMap.baseChange K (t.lieAlgebra ht).incl.toLinearMap x) := by
  calc
    _ = (t.lieAlgebraBaseChangeLieHom ht K x :
        Matrix ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots)
          ((t.baseChangeBase ht K).support ⊕ Fin t.numRoots) K) :=
      congrArg Subtype.val <| LinearEquiv.ofBijective_apply
        (t.lieAlgebraBaseChangeLieHom ht K).toLinearMap
        (hf := t.lieAlgebraBaseChangeLieHom_bijective ht K) x
    _ = _ := coe_lieAlgebraBaseChangeLieHom_apply t ht K x

/-- The base-change equivalence sends a pure tensor of a Cartan generator to the corresponding
generator for the scalar-extended root system. -/
@[simp]
theorem lieAlgebraBaseChangeEquiv_tmul_h (a : K) (i : (t.rationalBase ht).support) :
    t.lieAlgebraBaseChangeEquiv ht K
        (a ⊗ₜ[ℚ] (⟨h (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, by
          rw [lieAlgebra_def]
          exact h_mem_lieAlgebra i⟩ : t.lieAlgebra ht)) =
      a • (⟨h (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i), by
        rw [lieAlgebraBaseChange_def]
        exact h_mem_lieAlgebra _⟩ : t.lieAlgebraBaseChange ht K) := by
  apply Subtype.ext
  simp [reindex_symm_map_h]

/-- The base-change equivalence sends a pure tensor of a raising generator to the corresponding
generator for the scalar-extended root system. -/
@[simp]
theorem lieAlgebraBaseChangeEquiv_tmul_e (a : K) (i : (t.rationalBase ht).support) :
    t.lieAlgebraBaseChangeEquiv ht K
        (a ⊗ₜ[ℚ] (⟨e (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, by
          rw [lieAlgebra_def]
          exact e_mem_lieAlgebra i⟩ : t.lieAlgebra ht)) =
      a • (⟨e (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i), by
        rw [lieAlgebraBaseChange_def]
        exact e_mem_lieAlgebra _⟩ : t.lieAlgebraBaseChange ht K) := by
  apply Subtype.ext
  simp [reindex_symm_map_e]

/-- The base-change equivalence sends a pure tensor of a lowering generator to the corresponding
generator for the scalar-extended root system. -/
@[simp]
theorem lieAlgebraBaseChangeEquiv_tmul_f (a : K) (i : (t.rationalBase ht).support) :
    t.lieAlgebraBaseChangeEquiv ht K
        (a ⊗ₜ[ℚ] (⟨f (P := t.rationalRootSystem ht) (b := t.rationalBase ht) i, by
          rw [lieAlgebra_def]
          exact f_mem_lieAlgebra i⟩ : t.lieAlgebra ht)) =
      a • (⟨f (P := t.rootSystemBaseChange ht K) (b := t.baseChangeBase ht K)
          ((t.supportBaseChangeEquiv ht K).symm i), by
        rw [lieAlgebraBaseChange_def]
        exact f_mem_lieAlgebra _⟩ : t.lieAlgebraBaseChange ht K) := by
  apply Subtype.ext
  simp [reindex_symm_map_f]

end

end TauCeti.DynkinType

namespace TauCeti.DynkinType

noncomputable section

variable (t : DynkinType) (ht : t.Valid) (K : Type*) [Field K] [Algebra ℚ K]

local instance : CharZero K := Algebra.charZero_of_charZero ℚ K

instance instIsIrreducibleRootSystemBaseChange :
    (t.rootSystemBaseChange ht K).IsIrreducible :=
  (t.hasCartanType_baseChange ht K).isIrreducible ht

end

end TauCeti.DynkinType
