/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Basis

/-!
# Laurent covers of the adic spectrum

**The covering geometry of Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), Lemma 8.34(ii) and
(iii).**

For a family `f₁, …, f_r` of elements of `A`, the *Laurent cover* of `Spa (A, A⁺)` generated by
the family consists of the pieces

```text
X(f₁^{ε₁}, …, f_r^{ε_r}) = {v | v(fᵢ) ≤ 1 if εᵢ = 1,  v(fᵢ) ≥ 1 if εᵢ = -1},
```

one for each choice of signs. Here the signs are recorded by the set `J` of indices with
`εᵢ = -1`, and the piece is `laurentPiece Aplus f J`. The pieces are rational subsets
(`val_preimage_laurentPiece_mem_spaRationalFamily`), and they cover `Spa (A, A⁺)`, each point lying
in the piece of its own signs (`mem_laurentPiece_setOf_vle`).

Wedhorn's Lemma 8.34 reduces Čech acyclicity of an arbitrary finite rational cover to Laurent
covers, and the reduction rests on two refinement statements about the standard rational cover
`(R(T/t))_{t ∈ T}` of a finite set `T` generating the unit ideal. This file proves both, at the
level of subsets of `Spa (A, A⁺)`.

* **Part (ii).** Over a Tate ring there is a unit `ϖ` of `A` which is strictly dominated at every
  point by some element of `T` (`exists_unit_forall_mem_spa_exists_vlt`; for a single element
  this is Corollary 7.32). On a piece `V` of the Laurent cover generated by the `ϖ⁻¹ t`, the
  cover `(R(T/t) ∩ V)_{t ∈ T}` is generated by the elements `t` whose sign on `V` is `≥`: these
  vanish nowhere on `V` (`not_vle_zero_of_mem_laurentPiece_inv_mul`), the piece `R(T/t) ∩ V` is
  cut out of `V` by comparison with them alone when `t` is one of them
  (`mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul`), and it is empty otherwise
  (`rationalSubset_inter_laurentPiece_inv_mul_eq_empty`).
* **Part (iii).** If every element of `T` is a unit, the Laurent cover generated by the ratios
  `t t'⁻¹` refines `(R(T/t))_{t ∈ T}`: every piece lies in some `R(T/t)`
  (`exists_rationalSubset_superset_laurentPiece_mul_inverse`). A piece fixes the sign of every
  ratio, so it totally preorders `T` by `t' ≤ t` throughout the piece, and a greatest element of
  this preorder is the `t` sought.

What part (ii) calls units are units of the coordinate ring `𝒪_X(V)`. Here they appear only in
pointwise form, as elements vanishing at no point of `V`; their invertibility in `𝒪_X(V)` is not
proved here. Nor is the algebraic half of Lemma 8.34, Čech acyclicity of Laurent covers and its
transfer along refinements. The two-piece Laurent cover `{|f| ≤ 1}, {|f| ≥ 1}`, with its
coordinate rings, is treated in `TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.LaurentCover`.

## Main definitions

* `TauCeti.ValuationSpectrum.laurentPiece` : the piece `X(f^ε)` of the Laurent cover generated
  by a family `f`, with sign set `J`.

## Main results

* `TauCeti.ValuationSpectrum.spa_eq_iUnion_laurentPiece` : the pieces cover `Spa (A, A⁺)`.
* `TauCeti.ValuationSpectrum.val_preimage_laurentPiece_eq_iInter` and
  `TauCeti.ValuationSpectrum.val_preimage_laurentPiece_mem_spaRationalFamily` : a piece is an
  intersection of rational subsets, and so, for a finite family, is itself rational.
* `TauCeti.ValuationSpectrum.exists_unit_forall_mem_spa_exists_vlt` : the dominating unit of
  part (ii), for a finite set generating the unit ideal of a Tate ring.
* `TauCeti.ValuationSpectrum.rationalSubset_inter_laurentPiece_inv_mul_eq_empty`,
  `TauCeti.ValuationSpectrum.not_vle_zero_of_mem_laurentPiece_inv_mul` and
  `TauCeti.ValuationSpectrum.mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul` : part (ii).
* `TauCeti.ValuationSpectrum.exists_rationalSubset_superset_laurentPiece_mul_inverse` : part (iii).

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Corollary 7.32 and
  Lemma 8.34.
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemmas 2 and 3, the
  rigid-analytic originals of parts (ii) and (iii).

## Related formalization

AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0), branch `dev/adic-spaces` at commit
`37bbdaeb9ad9e3bc9f0d660feadc2779e455a91c`, file
`projects/AdicSpaces/Adic spaces/WedhornCechAcyclicity.lean`, states parts (ii) and (iii) for its
bundled rational covering data, with the Laurent cover built as an iterated list of two-piece
splits (`laurentProdLeaves`) and Corollary 7.32 for a finite family (`cor_7_32_dominating_unit`)
carrying strong-noetherian and completeness hypotheses. Here the pieces are indexed by sign sets,
and the dominating unit uses only the Tate property.
-/

public section

namespace TauCeti.ValuationSpectrum

open Topology TauCeti.Huber

variable {A : Type*} [CommRing A] [TopologicalSpace A] {ι : Type*}

/-! ### Laurent covers -/

/-- **A piece of the Laurent cover** generated by the family `f`: the points of `Spa (A, A⁺)` with
`v(fᵢ) ≥ 1` for `i ∈ J` and `v(fᵢ) ≤ 1` for `i ∉ J`. This is Wedhorn's `X(f₁^{ε₁}, …, f_r^{ε_r})`
with `J` the set of indices of sign `εᵢ = -1`.

As with `rationalSubset`, nothing is assumed of `A`, `A⁺` or the family; the pieces are rational
subsets when the family is finite and `A` is a Huber ring
(`val_preimage_laurentPiece_mem_spaRationalFamily`). -/
def laurentPiece (Aplus : Subring A) (f : ι → A) (J : Set ι) : Set (Spv A) :=
  {v | v ∈ spa Aplus ∧ ∀ i, (i ∈ J → v.toValuativeRel.vle 1 (f i)) ∧
    (i ∉ J → v.toValuativeRel.vle (f i) 1)}

/-- The set-level characterization of a Laurent piece. -/
theorem laurentPiece_def (Aplus : Subring A) (f : ι → A) (J : Set ι) :
    laurentPiece Aplus f J = spa Aplus ∩
      {v | ∀ i, (i ∈ J → v.toValuativeRel.vle 1 (f i)) ∧
        (i ∉ J → v.toValuativeRel.vle (f i) 1)} :=
  by ext v; rfl

/-- Membership in a piece of a Laurent cover. -/
@[simp]
theorem mem_laurentPiece_iff (Aplus : Subring A) (f : ι → A) (J : Set ι) (v : Spv A) :
    v ∈ laurentPiece Aplus f J ↔ v ∈ spa Aplus ∧ ∀ i, (i ∈ J → v.toValuativeRel.vle 1 (f i)) ∧
      (i ∉ J → v.toValuativeRel.vle (f i) 1) :=
  Iff.rfl

/-- Every piece of a Laurent cover is contained in the adic spectrum. -/
theorem laurentPiece_subset_spa (Aplus : Subring A) (f : ι → A) (J : Set ι) :
    laurentPiece Aplus f J ⊆ spa Aplus :=
  fun _ hv ↦ hv.1

/-- **A point lies in the piece of its own signs**: the one whose sign set consists of the
indices `i` with `v(fᵢ) ≥ 1`. -/
theorem mem_laurentPiece_setOf_vle {Aplus : Subring A} {v : Spv A} (hv : v ∈ spa Aplus)
    (f : ι → A) : v ∈ laurentPiece Aplus f {i | v.toValuativeRel.vle 1 (f i)} :=
  ⟨hv, fun i ↦ ⟨id, fun hi ↦ (v.toValuativeRel.vle_total (f i) 1).resolve_right hi⟩⟩

/-- **The pieces of a Laurent cover cover the adic spectrum.** -/
theorem spa_eq_iUnion_laurentPiece (Aplus : Subring A) (f : ι → A) :
    spa Aplus = ⋃ J : Set ι, laurentPiece Aplus f J :=
  subset_antisymm (fun _ hv ↦ Set.mem_iUnion_of_mem _ (mem_laurentPiece_setOf_vle hv f))
    (Set.iUnion_subset fun J ↦ laurentPiece_subset_spa Aplus f J)

open scoped Classical in
/-- **A piece of a Laurent cover is an intersection of rational subsets**: of `R({1}/fᵢ)` for
`i ∈ J` and of `R({fᵢ, 1}/1)` for `i ∉ J`. The numerator `1` makes both numerator ideals the unit
ideal, and costs nothing: `v(1) ≤ v(1)` always, and `v(1) ≤ v(fᵢ)` already forces `v(fᵢ) ≠ 0`. -/
theorem val_preimage_laurentPiece_eq_iInter (Aplus : Subring A) (f : ι → A) (J : Set ι) :
    (Subtype.val ⁻¹' laurentPiece Aplus f J : Set (spa Aplus)) =
      ⋂ i, Subtype.val ⁻¹'
        (if i ∈ J then rationalSubset Aplus {1} (f i) else rationalSubset Aplus {f i, 1} 1) := by
  ext v
  simp only [Set.mem_preimage, Set.mem_iInter, mem_laurentPiece_iff]
  refine ⟨fun ⟨_, hvJ⟩ i ↦ ?_, fun h ↦ ⟨v.2, fun i ↦ ?_⟩⟩
  · split_ifs with hi
    · refine (mem_rationalSubset_iff _ _ _ _).mpr ⟨v.2, by simpa using (hvJ i).1 hi, fun h0 ↦ ?_⟩
      exact (v.1.toValuativeRel.not_vle_one_zero) (v.1.toValuativeRel.vle_trans ((hvJ i).1 hi) h0)
    · refine (mem_rationalSubset_iff _ _ _ _).mpr ⟨v.2, ?_, v.1.toValuativeRel.not_vle_one_zero⟩
      simp only [Finset.mem_insert, Finset.mem_singleton, forall_eq_or_imp, forall_eq]
      exact ⟨(hvJ i).2 hi, (v.1.toValuativeRel.vle_total 1 1).elim id id⟩
  · have hi := h i
    split_ifs at hi with hiJ
    · exact ⟨fun _ ↦ by simpa using ((mem_rationalSubset_iff _ _ _ _).mp hi).2.1,
        fun h' ↦ absurd hiJ h'⟩
    · exact ⟨fun h' ↦ absurd h' hiJ, fun _ ↦ by
        simpa using (((mem_rationalSubset_iff _ _ _ _).mp hi).2.1 (f i) (by simp))⟩

/-- **The pieces of a Laurent cover generated by a finite family are rational subsets** of the adic
spectrum of a Huber ring. -/
theorem val_preimage_laurentPiece_mem_spaRationalFamily [IsTopologicalRing A] [IsHuberRing A]
    [Finite ι] (Aplus : Subring A) (f : ι → A) (J : Set ι) :
    (Subtype.val ⁻¹' laurentPiece Aplus f J : Set (spa Aplus)) ∈ spaRationalFamily Aplus := by
  classical
  have hopen {T : Finset A} (h1 : (1 : A) ∈ T) : IsOpen (Ideal.span (T : Set A) : Set A) := by
    rw [(Ideal.eq_top_iff_one _).mpr (Ideal.subset_span h1)]
    exact isOpen_univ
  rw [val_preimage_laurentPiece_eq_iInter]
  refine iInter_mem_spaRationalFamily fun i ↦ ?_
  split_ifs
  · exact mem_spaRationalFamily_iff.mpr ⟨{1}, f i, hopen (by simp), rfl⟩
  · exact mem_spaRationalFamily_iff.mpr ⟨{f i, 1}, 1, hopen (by simp), rfl⟩

/-! ### Part (ii): restricting a standard cover to a Laurent cover -/

/-- **The generators of the `≥` side vanish nowhere on the piece** (Wedhorn Lemma 8.34(ii)). On a
piece `V` of the Laurent cover generated by the elements `ϖ⁻¹ t`, `t ∈ T`, every `t` of sign `≥`
satisfies `v(t) ≥ v(ϖ) ≠ 0`. These are the elements that generate the restricted cover
`(R(T/t) ∩ V)_{t ∈ T}` (`mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul`), and this is the
pointwise form of Wedhorn's assertion that they are units of `𝒪_X(V)`. -/
theorem not_vle_zero_of_mem_laurentPiece_inv_mul {Aplus : Subring A} {T : Finset A} (ϖ : Aˣ)
    {J : Set T} {t : T} (ht : t ∈ J) {v : Spv A}
    (hv : v ∈ laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J) :
    ¬ v.toValuativeRel.vle (t : A) 0 := fun h0 ↦
  -- `v(ϖ) ≤ v(t) = 0` would put the unit `ϖ` in the support
  @TauCeti.ValuativeRel.not_vle_zero_of_isUnit A _ v.toValuativeRel _ ϖ.isUnit
    (v.toValuativeRel.vle_trans
      (@TauCeti.ValuativeRel.vle_of_vle_inv_mul A _ v.toValuativeRel ϖ t ((hv.2 t).1 ht)) h0)

/-- **Off the `≥` side, the restricted piece is empty** (Wedhorn Lemma 8.34(ii)). Let `ϖ` be a unit
strictly dominated at every point of `Spa (A, A⁺)` by an element of `T`, as
`exists_unit_forall_mem_spa_exists_vlt` provides. On a piece `V` of the Laurent cover generated by
the `ϖ⁻¹ t`, if `t` has sign `≤` then `R(T/t)` does not meet `V`: at a point of `R(T/t)` the value
of `t` is the largest on `T`, hence above `v(ϖ)`, whereas on `V` it is at most `v(ϖ)`. -/
theorem rationalSubset_inter_laurentPiece_inv_mul_eq_empty {Aplus : Subring A} {T : Finset A}
    {ϖ : Aˣ} (hϖ : ∀ v ∈ spa Aplus, ∃ t ∈ T, v.toValuativeRel.vlt (ϖ : A) t) {J : Set T} {t : T}
    (ht : t ∉ J) :
    rationalSubset Aplus T t ∩ laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J = ∅ := by
  refine Set.eq_empty_iff_forall_notMem.mpr fun v ⟨hvT, hvJ⟩ ↦ ?_
  obtain ⟨t', ht', hlt⟩ := hϖ v hvJ.1
  -- `v(t') ≤ v(t) ≤ v(ϖ) < v(t')`
  exact hlt (v.toValuativeRel.vle_trans (((mem_rationalSubset_iff _ _ _ _).mp hvT).2.1 t' ht')
    (@TauCeti.ValuativeRel.vle_of_inv_mul_vle A _ v.toValuativeRel ϖ t ((hvJ.2 t).2 ht)))

/-- **On the `≥` side, the restricted piece is cut out by the `≥` generators** (Wedhorn Lemma
8.34(ii)). On a piece `V` of the Laurent cover generated by the `ϖ⁻¹ t`, for `t` of sign `≥`, a
point of `V` lies in `R(T/t)` exactly when `t` dominates every element of `T` of sign `≥`: the
elements of sign `≤` are at most `v(ϖ) ≤ v(t)` on `V` anyway, and `t` vanishes nowhere on `V` by
`not_vle_zero_of_mem_laurentPiece_inv_mul`. So the restriction of the standard cover
`(R(T/t))_{t ∈ T}` to `V` is the standard cover of `V` generated by the elements of sign `≥`. -/
theorem mem_rationalSubset_iff_of_mem_laurentPiece_inv_mul {Aplus : Subring A} {T : Finset A}
    (ϖ : Aˣ) {J : Set T} {t : T} (ht : t ∈ J) {v : Spv A}
    (hv : v ∈ laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J) :
    v ∈ rationalSubset Aplus T t ↔ ∀ t' ∈ J, v.toValuativeRel.vle (t' : A) t := by
  refine ⟨fun hvT t' _ ↦ ((mem_rationalSubset_iff _ _ _ _).mp hvT).2.1 t' t'.2, fun h ↦ ?_⟩
  refine (mem_rationalSubset_iff _ _ _ _).mpr
    ⟨hv.1, fun t' ht' ↦ ?_, not_vle_zero_of_mem_laurentPiece_inv_mul ϖ ht hv⟩
  by_cases ht'J : (⟨t', ht'⟩ : T) ∈ J
  · exact h _ ht'J
  · exact v.toValuativeRel.vle_trans
      (@TauCeti.ValuativeRel.vle_of_inv_mul_vle A _ v.toValuativeRel ϖ t' ((hv.2 _).2 ht'J))
      (@TauCeti.ValuativeRel.vle_of_vle_inv_mul A _ v.toValuativeRel ϖ t ((hv.2 t).1 ht))

/-! ### Part (iii): refining a standard cover generated by units -/

/-- **The Laurent cover of ratios refines a standard cover generated by units** (Wedhorn Lemma
8.34(iii)). Let `T` be a nonempty finite set of units of `A`. Every piece of the Laurent cover
generated by the ratios `t t'⁻¹`, `(t, t') ∈ T × T`, lies in `R(T/t)` for some `t ∈ T`; since the
pieces cover `Spa (A, A⁺)` (`spa_eq_iUnion_laurentPiece`), this Laurent cover refines the standard
rational cover `(R(T/t))_{t ∈ T}`.

The resulting refinement of the standard rational cover is the unit-generated case of
part (iii). -/
theorem exists_rationalSubset_superset_laurentPiece_mul_inverse (Aplus : Subring A) {T : Finset A}
    (hT : T.Nonempty) (hu : ∀ t ∈ T, IsUnit t) (J : Set (T × T)) :
    ∃ t ∈ T, laurentPiece Aplus (fun p : T × T ↦ (p.1 : A) * Ring.inverse (p.2 : A)) J ⊆
      rationalSubset Aplus T t := by
  set V := laurentPiece Aplus (fun p : T × T ↦ (p.1 : A) * Ring.inverse (p.2 : A)) J
  -- `r a b`: the element `b` dominates `a` throughout the piece
  let r (a b : A) : Prop := ∀ v ∈ V, v.toValuativeRel.vle a b
  have : IsTrans A r :=
    ⟨fun _ _ _ hab hbc v hv ↦ v.toValuativeRel.vle_trans (hab v hv) (hbc v hv)⟩
  have hrefl (a : A) : r a a := fun v _ ↦ (v.toValuativeRel.vle_total a a).elim id id
  -- the piece fixes the sign of `a b⁻¹`, and so compares `a` with `b`
  have hdir : Directed r (Subtype.val : T → A) := fun a b ↦ by
    by_cases hab : (a, b) ∈ J
    · refine ⟨a, hrefl a, fun v hv ↦ ?_⟩
      have h := v.toValuativeRel.mul_vle_mul_left ((hv.2 (a, b)).1 hab) b
      rwa [one_mul, Ring.inverse_mul_cancel_right (b : A) a (hu b b.2)] at h
    · refine ⟨b, fun v hv ↦ ?_, hrefl b⟩
      have h := v.toValuativeRel.mul_vle_mul_left ((hv.2 (a, b)).2 hab) b
      rwa [one_mul, Ring.inverse_mul_cancel_right (b : A) a (hu b b.2)] at h
  -- a greatest element for this total preorder, which vanishes nowhere, being a unit
  have : Nonempty T := hT.coe_sort
  obtain ⟨m, hm⟩ := hdir.finset_le Finset.univ
  exact ⟨m, m.2, fun v hv ↦ (mem_rationalSubset_iff _ _ _ _).mpr
    ⟨hv.1, fun t ht ↦ hm ⟨t, ht⟩ (Finset.mem_univ _) v hv,
      @TauCeti.ValuativeRel.not_vle_zero_of_isUnit A _ v.toValuativeRel _ (hu m m.2)⟩⟩

end TauCeti.ValuationSpectrum
