/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Basic
public import TauCeti.Algebra.AlgebraicGroup.Smooth.CommHopfAlgCat
public import Mathlib.FieldTheory.IsAlgClosed.Basic
import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Reduction
import TauCeti.Algebra.AlgebraicGroup.Smooth.AlgebraicallyClosed
import TauCeti.RingTheory.FiniteType.Tensor.Product

/-!
# Reducedness of closed subgroups generated by reduced group schemes

The closed subgroup scheme generated by affine group schemes is the common-kernel Hopf quotient:
the largest Hopf ideal killed by all generator maps. If its coordinate ring had a nilpotent, its
reduction would give a further Hopf ideal killed by the same maps, contradicting that maximality.

The reduction is a Hopf ideal whenever the tensor square of the reduced quotient is reduced. Over
an algebraically closed field, finite type supplies this tensor condition automatically. The
result applies to root-subgroup and torus generators in constructions of split reductive groups.
In that setting reducedness also makes the generated subgroup scheme smooth.

## References

* W. C. Waterhouse, *Introduction to Affine Group Schemes*, §11.4.
* J. S. Milne, *Algebraic Groups* (2017), Theorem 1.45 and §2.h.
-/

public section

open scoped TensorProduct

namespace TauCeti.CommHopfAlgCat

universe u v w

variable {R : Type u} [CommRing R] [IsReduced R]
variable {H : _root_.CommHopfAlgCat.{v} R}
variable {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} R}

/-- **The common-kernel Hopf quotient is reduced** when each generator map has radical kernel
and the tensor square of the quotient's reduction is reduced. The tensor condition makes the
nilradical a Hopf ideal, to which the common-kernel universal property applies. -/
theorem isReduced_quotient_commonKernelHopfIdeal_of_isRadical_ker (f : ∀ i, H ⟶ K i)
    [IsReduced (((quotient H (commonKernelHopfIdeal f) ⧸
      nilradical (quotient H (commonKernelHopfIdeal f))) ⊗[R]
      (quotient H (commonKernelHopfIdeal f) ⧸
        nilradical (quotient H (commonKernelHopfIdeal f)))))]
    (hker : ∀ i, (RingHom.ker (f i).hom.toAlgHom.toRingHom).IsRadical) :
    IsReduced (quotient H (commonKernelHopfIdeal f)) := by
  let Q := quotient H (commonKernelHopfIdeal f)
  let I := HopfIdeal.reduction R Q
  have hI : I ≤ commonKernelHopfIdeal (commonKernelLift f) := by
    apply (le_commonKernelHopfIdeal_iff _ _).mpr
    intro i x hx
    apply RingHom.mem_ker.mpr
    have hnil := (HopfIdeal.mem_reduction R Q).mp hx
    obtain ⟨y, hy⟩ := mkQuotient_surjective H (commonKernelHopfIdeal f) x
    have hcomp := congrArg (fun m : H ⟶ K i => m.hom y)
      (mkQuotient_comp_commonKernelLift f i)
    simp only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] at hcomp
    rw [hy] at hcomp
    have hnilY : IsNilpotent ((f i).hom y) := hcomp.symm ▸ hnil.map (commonKernelLift f i).hom
    have hmem : y ∈ RingHom.ker (f i).hom.toAlgHom.toRingHom := by
      apply hker i
      exact ⟨hnilY.choose, by
        rw [RingHom.mem_ker, map_pow]
        exact hnilY.choose_spec⟩
    exact hcomp.trans (RingHom.mem_ker.mp hmem)
  have hbot : I = ⊥ :=
    eq_bot_iff.mpr (hI.trans (le_of_eq (commonKernelHopfIdeal_commonKernelLift_eq_bot f)))
  apply (nilradical_eq_bot_iff (R := Q)).mp
  calc
    nilradical Q = I.toIdeal := (HopfIdeal.reduction_toIdeal R Q).symm
    _ = ⊥ := by rw [hbot, HopfIdeal.bot_toIdeal]

/-- The common-kernel Hopf quotient of reduced generator algebras is reduced when the tensor
square of its reduction is reduced. -/
theorem isReduced_quotient_commonKernelHopfIdeal_of_isReduced_tensorProduct
    (f : ∀ i, H ⟶ K i)
    [IsReduced (((quotient H (commonKernelHopfIdeal f) ⧸
      nilradical (quotient H (commonKernelHopfIdeal f))) ⊗[R]
      (quotient H (commonKernelHopfIdeal f) ⧸
        nilradical (quotient H (commonKernelHopfIdeal f)))))]
    [∀ i, IsReduced (K i)] :
    IsReduced (quotient H (commonKernelHopfIdeal f)) := by
  apply isReduced_quotient_commonKernelHopfIdeal_of_isRadical_ker f
  intro i
  exact (Ideal.isRadical_bot (R := K i)).comap _

/-- Over an algebraically closed field, a finite-type common-kernel quotient is reduced if
every generator map has radical kernel. -/
theorem isReduced_quotient_commonKernelHopfIdeal_of_isAlgClosed_of_isRadical_ker
    {k : Type u} [Field k] [IsAlgClosed k]
    {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i)
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))]
    (hker : ∀ i, (RingHom.ker (f i).hom.toAlgHom.toRingHom).IsRadical) :
    IsReduced (quotient H (commonKernelHopfIdeal f)) := by
  let Q := quotient H (commonKernelHopfIdeal f)
  let _ : Algebra.FiniteType k (Q ⧸ nilradical Q) := inferInstance
  let _ : IsReduced (Q ⧸ nilradical Q) :=
    (Ideal.isRadical_iff_quotient_reduced _).mp (Ideal.radical_isRadical ⊥)
  exact isReduced_quotient_commonKernelHopfIdeal_of_isRadical_ker f hker

/-- **A subgroup scheme generated by reduced affine group schemes is reduced** over an
algebraically closed field. The quotient coordinate algebra is of finite type; the generators
need not be of finite type. -/
theorem isReduced_quotient_commonKernelHopfIdeal
    {k : Type u} [Field k] [IsAlgClosed k]
    {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i) [∀ i, IsReduced (K i)]
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))] :
    IsReduced (quotient H (commonKernelHopfIdeal f)) := by
  apply isReduced_quotient_commonKernelHopfIdeal_of_isAlgClosed_of_isRadical_ker f
  intro i
  exact (Ideal.isRadical_bot (R := K i)).comap _

/-- A finite-type common-kernel quotient with radical generator kernels is smooth over an
algebraically closed field. -/
theorem smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal_of_isRadical_ker
    {k : Type u} [Field k] [IsAlgClosed k]
    {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i)
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))]
    (hker : ∀ i, (RingHom.ker (f i).hom.toAlgHom.toRingHom).IsRadical) :
    smoothCommHopfAlgProperty k (quotient H (commonKernelHopfIdeal f)) := by
  let _ : IsReduced (quotient H (commonKernelHopfIdeal f)) :=
    isReduced_quotient_commonKernelHopfIdeal_of_isAlgClosed_of_isRadical_ker f hker
  exact smoothCommHopfAlgProperty_of_isAlgClosed_of_isReduced k _

/-- **A subgroup scheme generated by reduced affine group schemes is smooth** when its
coordinate algebra is of finite type over an algebraically closed field. -/
theorem smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal
    {k : Type u} [Field k] [IsAlgClosed k]
    {H : _root_.CommHopfAlgCat.{v} k}
    {ι : Type w} {K : ι → _root_.CommHopfAlgCat.{v} k}
    (f : ∀ i, H ⟶ K i) [∀ i, IsReduced (K i)]
    [Algebra.FiniteType k (quotient H (commonKernelHopfIdeal f))] :
    smoothCommHopfAlgProperty k (quotient H (commonKernelHopfIdeal f)) := by
  apply smoothCommHopfAlgProperty_quotient_commonKernelHopfIdeal_of_isRadical_ker f
  intro i
  exact (Ideal.isRadical_bot (R := K i)).comap _

end TauCeti.CommHopfAlgCat
