/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
import TauCeti.FieldTheory.IntermediateField.Quadratic
import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.Independence
import TauCeti.NumberTheory.Multiquadratic.RelativeDegree

/-!
# The candidate genus field over its quadratic base

For a squarefree integer `d`, `candidateGenusField hd` contains a chosen square root of `d`.
This file names that root and the resulting copy of `ℚ(√d)` inside the candidate genus field.
When `d` is not a rational square, this base has degree two over `ℚ`, and the full candidate
genus field has relative degree

`[candidateGenusField hd : ℚ(√d)] = 2 ^ ((genusPrimeDiscriminants hd).card - 1)`.

The absolute degree `2 ^ (genusPrimeDiscriminants hd).card` is proved in
`CandidateGenusField/Degree`. The relative formula here combines that theorem with the quadratic
degree of the base through the tower law
`[M : ℚ] = [ℚ(√d) : ℚ] · [M : ℚ(√d)]`.

This is the relative-degree part of the genus-field construction. For negative `d`,
`isGenusField_candidateGenusField` identifies the candidate with the maximal extension satisfying
the required ramification conditions. The real case and the identification of its relative Galois
group with `Cl/Cl²` remain future work.

The prime-discriminant description of the genus field is classical; see D. A. Cox,
*Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*.

## Main definitions

* `TauCeti.Multiquadratic.candidateGenusFieldBaseRoot`: a chosen square root of `d` in the
  candidate genus field.
* `TauCeti.Multiquadratic.candidateGenusFieldBase`: the copy of `ℚ(√d)` generated by that root.

## Main results

* `TauCeti.Multiquadratic.finrank_candidateGenusFieldBase`: the base has degree two when `d`
  is not a rational square.
* `TauCeti.Multiquadratic.finrank_candidateGenusField_over_candidateGenusFieldBase`: the
  candidate genus field has degree `2 ^ (t - 1)` over its quadratic base.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- A chosen square root of `d` inside its candidate genus field. Existence follows from the
prime-discriminant factorization of `fundamentalDiscriminant d`; no particular sign is selected. -/
noncomputable def candidateGenusFieldBaseRoot {d : ℤ} (hd : Squarefree d) :
    candidateGenusField hd :=
  ⟨(exists_mem_candidateGenusField_sq_eq hd).choose,
    (exists_mem_candidateGenusField_sq_eq hd).choose_spec.1⟩

/-- The chosen base root squares to `d`. -/
@[simp] theorem candidateGenusFieldBaseRoot_sq {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBaseRoot hd ^ 2 =
      algebraMap ℚ (candidateGenusField hd) ((d : ℤ) : ℚ) := by
  apply Subtype.ext
  exact (exists_mem_candidateGenusField_sq_eq hd).choose_spec.2

/-- The copy of `ℚ(√d)` inside `candidateGenusField hd`, generated by the chosen square root
of `d`. It is quadratic exactly in the nonsquare case used for quadratic fields. -/
noncomputable def candidateGenusFieldBase {d : ℤ} (hd : Squarefree d) :
    IntermediateField ℚ (candidateGenusField hd) :=
  adjoin ℚ {candidateGenusFieldBaseRoot hd}

/-- `candidateGenusFieldBase` presented as the simple extension generated by its chosen root. -/
theorem candidateGenusFieldBase_def {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBase hd = adjoin ℚ {candidateGenusFieldBaseRoot hd} := by
  simp only [candidateGenusFieldBase]

/-- The chosen square root of `d` lies in the quadratic base. -/
@[simp] theorem candidateGenusFieldBaseRoot_mem {d : ℤ} (hd : Squarefree d) :
    candidateGenusFieldBaseRoot hd ∈ candidateGenusFieldBase hd := by
  rw [candidateGenusFieldBase_def]
  exact subset_adjoin ℚ _ (Set.mem_singleton _)

/-- **Universal property of the quadratic base.** It lies below an intermediate field `F`
exactly when `F` contains the chosen square root of `d`. -/
@[simp] theorem candidateGenusFieldBase_le_iff {d : ℤ} (hd : Squarefree d)
    {F : IntermediateField ℚ (candidateGenusField hd)} :
    candidateGenusFieldBase hd ≤ F ↔ candidateGenusFieldBaseRoot hd ∈ F := by
  simp only [candidateGenusFieldBase_def, adjoin_le_iff, Set.singleton_subset_iff,
    SetLike.mem_coe]

/-- **The embedded base `ℚ(√d)` is quadratic.** If `d` is not a square in `ℚ`, the simple
subfield generated by the chosen square root of `d` has degree two over `ℚ`. -/
theorem finrank_candidateGenusFieldBase {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Module.finrank ℚ (candidateGenusFieldBase hd) = 2 := by
  rw [candidateGenusFieldBase_def]
  have hx2 : candidateGenusFieldBaseRoot hd ^ 2 ∈
      (⊥ : IntermediateField ℚ (candidateGenusField hd)) := by
    rw [candidateGenusFieldBaseRoot_sq]
    exact IntermediateField.algebraMap_mem _ _
  have hxnot : candidateGenusFieldBaseRoot hd ∉
      (⊥ : IntermediateField ℚ (candidateGenusField hd)) := by
    intro hmem
    rw [IntermediateField.mem_bot] at hmem
    obtain ⟨q, hq⟩ := hmem
    apply hnsq
    refine ⟨q, ?_⟩
    apply (algebraMap ℚ (candidateGenusField hd)).injective
    have hsq := candidateGenusFieldBaseRoot_sq hd
    rw [← hq, ← map_pow] at hsq
    simpa only [pow_two] using hsq.symm
  have h := (⊥ : IntermediateField ℚ (candidateGenusField hd)).finrank_sup_adjoin_simple_eq_mul_two
    hx2 hxnot
  rwa [bot_sup_eq, IntermediateField.finrank_bot, one_mul] at h

/-- **Relative degree of the candidate genus field over `ℚ(√d)`.** If the squarefree integer
`d` is not a rational square, the prime-discriminant compositum has degree
`2 ^ (t - 1)` over its embedded quadratic base, where
`t = (genusPrimeDiscriminants hd).card`. -/
theorem finrank_candidateGenusField_over_candidateGenusFieldBase {d : ℤ} (hd : Squarefree d)
    (hnsq : ¬ IsSquare (((d : ℤ) : ℚ))) :
    Module.finrank (candidateGenusFieldBase hd) (candidateGenusField hd) =
      2 ^ ((genusPrimeDiscriminants hd).card - 1) := by
  classical
  let e : candidateGenusField hd ≃ₐ[ℚ] adjoin ℚ (Set.range (genusFieldRoot hd)) :=
    IntermediateField.equivOfEq (candidateGenusField_def hd)
  let F : IntermediateField ℚ (adjoin ℚ (Set.range (genusFieldRoot hd))) :=
    (candidateGenusFieldBase hd).map e.toAlgHom
  let eF : candidateGenusFieldBase hd ≃ₐ[ℚ] F :=
    IntermediateField.equivMap (candidateGenusFieldBase hd) e.toAlgHom
  obtain ⟨hprime, heven_unique, _⟩ := genusPrimeDiscriminants_spec hd
  have hroot : ∀ P : {P // P ∈ genusPrimeDiscriminants hd},
      genusFieldRoot hd P ^ 2 =
        algebraMap ℚ ℂ (((primeDiscriminantRadicand P.val : ℤ) : ℚ)) := fun P => by simp
  have hindep :
      ∀ S : Finset {P // P ∈ genusPrimeDiscriminants hd}, S.Nonempty →
        ¬ IsSquare (∏ P ∈ S, ((primeDiscriminantRadicand P.val : ℤ) : ℚ)) :=
    not_isSquare_prod_primeDiscriminantRadicands_of_forall_isEvenPrimeDiscriminant_eq
      (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
      (fun P => hprime P.val P.property) Subtype.val_injective
      (fun P Q hP hQ => heven_unique P.val P.property Q.val Q.property hP hQ)
  have hF : Module.finrank ℚ F = 2 := by
    rw [← eF.toLinearEquiv.finrank_eq]
    exact finrank_candidateGenusFieldBase hd hnsq
  have h := finrank_top_over_intermediateField_of_finrank_eq_two hroot hindep
    F hF
  have heF (x : candidateGenusFieldBase hd) :
      (↑(eF x) : adjoin ℚ (Set.range (genusFieldRoot hd))) =
        e (x : candidateGenusField hd) := by
    (convert IntermediateField.coe_equivMap_apply
      (candidateGenusFieldBase hd) e.toAlgHom x using 1; rfl)
  have hrel :
      Module.finrank (candidateGenusFieldBase hd) (candidateGenusField hd) =
        Module.finrank F (adjoin ℚ (Set.range (genusFieldRoot hd))) :=
    Algebra.finrank_eq_of_equiv_equiv eF.toRingEquiv e.toRingEquiv (by
      apply RingHom.ext
      intro x
      simpa only [RingHom.comp_apply, IntermediateField.algebraMap_apply,
        RingEquiv.toRingHom_eq_coe, RingHom.coe_coe, AlgEquiv.coe_toRingEquiv] using heF x)
  rw [hrel]
  simpa only [Nat.card_eq_fintype_card, Fintype.card_coe] using h

end TauCeti.Multiquadratic
