/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.Minpoly
public import TauCeti.NumberTheory.LocalField.Different.Basic
public import TauCeti.NumberTheory.LocalField.RamificationGroup
public import TauCeti.RingTheory.DedekindDomain.Different.Monogenic
public import TauCeti.RingTheory.DiscreteValuationRing.Monogenic
public import TauCeti.RingTheory.Valuation.AddValuation

/-!
# Hilbert's formula for the different exponent

Let `L/K` be a finite Galois extension of nonarchimedean local fields with group `G`, and let
`G_i` be its lower ramification groups. **Hilbert's formula** computes the different exponent
`d(L/K)` from the ramification filtration:

`d(L/K) = ∑_{i ≥ 0} (#G_i - 1)`.

The proof is Serre's. The ring of integers `𝒪[L]` is generated over `𝒪[K]` by a single element
`x`, so the different is generated by `f'(x)` for the minimal polynomial `f` of `x`, and
`f'(x) = ∏_{σ ≠ 1} (x - σ x)` because the conjugates of `x` are its images under the Galois
group. Hence `d(L/K) = ∑_{σ ≠ 1} v_L(σ x - x)`, and `σ` lies in `G_i` exactly when
`v_L(σ x - x) ≥ i + 1`, so each `σ ≠ 1` contributes `1` to exactly `v_L(σ x - x)` of the terms
`#G_i - 1`.

## Main results

* `TauCeti.natCast_differentExponent_eq_sum_addVal_smul_sub`: `d(L/K) = ∑_{σ ≠ 1} v_L(σ x - x)`
  for a generator `x` of `𝒪[L]` over `𝒪[K]`.
* `TauCeti.differentExponent_eq_finsum_lowerRamificationGroup`: Hilbert's formula.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §1, Proposition 4.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, §10.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing Polynomial

attribute [local instance] FractionRing.liftAlgebra FractionRing.isScalarTower_liftAlgebra

namespace TauCeti

variable (K L : Type*) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L] [Algebra K L] [ValuativeExtension K L]
  [Module.Finite K L] [IsGalois K L]

/-- **The different exponent at a generator.** If `x` generates `𝒪[L]` over `𝒪[K]`, then
`d(L/K) = ∑_{σ ≠ 1} v_L(σ x - x)`, the sum running over the nontrivial automorphisms of `L/K`. -/
theorem natCast_differentExponent_eq_sum_addVal_smul_sub [DecidableEq (L ≃ₐ[K] L)] {x : 𝒪[L]}
    (hx : Algebra.adjoin 𝒪[K] {x} = ⊤) :
    (differentExponent K L : ℕ∞) =
      ∑ σ ∈ (Finset.univ : Finset (L ≃ₐ[K] L)).erase 1,
        IsDiscreteValuationRing.addVal 𝒪[L] (σ • x - x) := by
  have hint : IsIntegral 𝒪[K] x := .of_finite 𝒪[K] x
  have hxL : IntermediateField.adjoin K {algebraMap 𝒪[L] L x} = ⊤ :=
    TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top hx
  -- The different is generated by `f'(x)`.
  have hy : differentIdeal 𝒪[K] 𝒪[L] = Ideal.span {aeval x (derivative (minpoly 𝒪[K] x))} :=
    differentIdeal_eq_span_aeval_derivative_minpoly 𝒪[K] K L 𝒪[L] x hx
  have hy0 : aeval x (derivative (minpoly 𝒪[K] x)) ≠ 0 := fun h ↦
    differentIdeal_ne_bot (A := 𝒪[K]) (B := 𝒪[L]) (by rw [hy, h, Ideal.span_singleton_eq_bot])
  -- `f'(x) = ∏_{σ ≠ 1} (x - σ x)`, computed in `L` and pulled back to `𝒪[L]`.
  have hprod : aeval x (derivative (minpoly 𝒪[K] x)) =
      ∏ σ ∈ (Finset.univ : Finset (L ≃ₐ[K] L)).erase 1, (x - σ • x) := by
    apply Subtype.ext
    have h : algebraMap 𝒪[L] L (aeval x (derivative (minpoly 𝒪[K] x))) =
        aeval (algebraMap 𝒪[L] L x) (derivative (minpoly K (algebraMap 𝒪[L] L x))) := by
      rw [minpoly.isIntegrallyClosed_eq_field_fractions K L hint, derivative_map,
        aeval_map_algebraMap, aeval_algebraMap_apply]
    rw [aeval_derivative_minpoly_eq_prod_of_adjoin_eq_top hxL] at h
    -- The algebra map `𝒪[L] → L` is the subring inclusion.
    have hcoe : ∀ y : 𝒪[L], algebraMap 𝒪[L] L y = (y : L) := fun _ ↦ rfl
    simpa only [hcoe, SubmonoidClass.coe_finsetProd, AddSubgroupClass.coe_sub,
      AlgEquiv.coe_smul_integerRing] using h
  rw [differentExponent_def, hy,
    ← TauCeti.IsDiscreteValuationRing.addVal_eq_multiplicity_span_singleton hy0, hprod,
    AddValuation.map_prod]
  exact Finset.sum_congr rfl fun σ _ ↦ AddValuation.map_sub_swap _ _ _

/-- **Hilbert's formula for the different exponent**: for a finite Galois extension `L/K` of
nonarchimedean local fields, `d(L/K) = ∑_{i ≥ 0} (#G_i - 1)`, where `G_i` is the `i`-th lower
ramification group. The sum is finite because the filtration is eventually trivial. -/
theorem differentExponent_eq_finsum_lowerRamificationGroup :
    differentExponent K L =
      ∑ᶠ i : ℕ, (Nat.card (LocalFieldsRamification.lowerRamificationGroup K L i) - 1) := by
  classical
  obtain ⟨x, hx⟩ := IsDiscreteValuationRing.exists_adjoin_eq_top (R := 𝒪[K]) (S := 𝒪[L])
  have h := natCast_differentExponent_eq_sum_addVal_smul_sub K L hx
  rw [TauCeti.IsLocalRing.sum_addVal_smul_sub_eq_finsum_card_ramificationGroup_sub_one hx,
    Nat.cast_inj] at h
  simpa only [LocalFieldsRamification.lowerRamificationGroup_def] using h

end TauCeti
