/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.FieldTheory.IsAlgClosed.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
import TauCeti.Algebra.AlgebraicGroup.Hopf.Commutator
import TauCeti.RingTheory.TensorProduct.PointSeparation
import TauCeti.RingTheory.FiniteType.PointSeparation
import Mathlib.RingTheory.Ideal.Quotient.Nilpotent

/-!
# The Hopf ideal vanishing on a subgroup of rational points

The functions vanishing on any subgroup of the rational points of an affine group form a
radical Hopf ideal. Its quotient is the reduced closed subgroup generated by those points.
The construction and its order-theoretic API need no finite-type or algebraic-closedness
assumption. The density statement `vanishingIdeal_top` additionally assumes a reduced
finite-type algebra over an algebraically closed field. This construction connects abstract
point subgroups, such as commutator subgroups, with closed subgroup schemes.

Passing to the generated closed subgroup is compatible with commutators: the commutator of the
closed subgroups generated by two point subgroups lies in the closed subgroup generated by their
commutator. The trivial point subgroup generates the trivial closed subgroup.

## Main declarations

* `TauCeti.HopfIdeal.vanishingIdeal`: the Hopf ideal of functions vanishing on a point subgroup.
* `TauCeti.HopfIdeal.le_vanishingIdeal_iff`: its quotient is the smallest closed subgroup
  containing the point subgroup.
* `TauCeti.HopfIdeal.commutator_quotientPointsSubgroup_vanishingIdeal_le`: commutators of
  closures lie in the closure of the commutator.
* `TauCeti.HopfIdeal.quotientPointsSubgroup_vanishingIdeal_bot`: the closure of the trivial
  subgroup is trivial.

## References

* W. C. Waterhouse, *Introduction to Affine Group Schemes*, §4.
-/

public section

open scoped TensorProduct commutatorElement
open WithConv

namespace TauCeti.HopfIdeal

noncomputable section

variable {k H : Type*} [Field k] [CommRing H] [HopfAlgebra k H]

/-- Functions vanishing at every point of the subgroup. -/
private def pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) : Ideal H :=
  ⨅ g : S, RingHom.ker g.val.ofConv

private theorem mem_pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) (x : H) :
    x ∈ pointKernelIdeal S ↔ ∀ g : S, g.val.ofConv x = 0 := by
  simp [pointKernelIdeal, RingHom.mem_ker]

/-- Evaluation at a subgroup point descends to the quotient by its vanishing ideal. -/
private def quotientEval (S : Subgroup (WithConv (H →ₐ[k] k))) (g : S) :
    H ⧸ pointKernelIdeal S →ₐ[k] k :=
  Ideal.Quotient.liftₐ _ g.val.ofConv fun x hx ↦ (mem_pointKernelIdeal S x).mp hx g

private theorem quotientEval_mk (S : Subgroup (WithConv (H →ₐ[k] k))) (g : S) (x : H) :
    quotientEval S g (Ideal.Quotient.mk (pointKernelIdeal S) x) = g.val.ofConv x :=
  Ideal.Quotient.liftₐ_apply _ _ _ _

private theorem quotientEval_separates (S : Subgroup (WithConv (H →ₐ[k] k)))
    (x : H ⧸ pointKernelIdeal S) (hx : ∀ g, quotientEval S g x = 0) : x = 0 := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mkₐ_surjective k (pointKernelIdeal S) x
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact (mem_pointKernelIdeal S x).mpr hx

private theorem comul_mem_pointKernelIdeal (S : Subgroup (WithConv (H →ₐ[k] k)))
    {x : H} (hx : x ∈ pointKernelIdeal S) :
    Coalgebra.comul (R := k) x ∈
      leftTensorIdeal (R := k) (H := H) (pointKernelIdeal S) ⊔
        rightTensorIdeal (R := k) (H := H) (pointKernelIdeal S) := by
  let q := Ideal.Quotient.mkₐ k (pointKernelIdeal S)
  have hker : RingHom.ker q = pointKernelIdeal S := Ideal.Quotient.mkₐ_ker k (pointKernelIdeal S)
  rw [← hker, ← ker_tensorProduct_map_eq_leftTensorIdeal_sup_rightTensorIdeal q q
    (Ideal.Quotient.mkₐ_surjective k _) (Ideal.Quotient.mkₐ_surjective k _), RingHom.mem_ker]
  apply tensor_eq_zero_of_forall_productMap_eq_zero
    (quotientEval S) (quotientEval S) (quotientEval_separates S) (quotientEval_separates S)
  intro g h
  have heq : (Algebra.TensorProduct.productMap (quotientEval S g) (quotientEval S h)).comp
      (Algebra.TensorProduct.map q q) =
        Algebra.TensorProduct.productMap g.val.ofConv h.val.ofConv := by
    ext : 1 <;> ext b <;> simp [AlgHom.comp_apply, q, quotientEval_mk]
  rw [← AlgHom.comp_apply, heq]
  exact (AlgHom.convMul_apply g.val h.val x).symm.trans
    ((mem_pointKernelIdeal S x).mp hx (g * h))

/-- The radical Hopf ideal of functions vanishing on a subgroup of rational points. -/
def vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) : HopfIdeal k H :=
  ofIdeal (pointKernelIdeal S) (fun _ hx ↦ comul_mem_pointKernelIdeal S hx)
    (fun x hx ↦ by simpa using (mem_pointKernelIdeal S x).mp hx 1)
    (fun x hx ↦ (mem_pointKernelIdeal S _).mpr fun g ↦ by
      simpa using (mem_pointKernelIdeal S x).mp hx g⁻¹)

/-- Membership means vanishing at every point of the subgroup. -/
@[simp]
theorem mem_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) (x : H) :
    x ∈ vanishingIdeal S ↔ ∀ g : S, g.val.ofConv x = 0 :=
  mem_ofIdeal.trans (mem_pointKernelIdeal S x)

/-- Evaluations at the original subgroup points separate the coordinate algebra of its closure. -/
theorem eq_zero_of_forall_liftQuotientPoint_apply_eq_zero
    (S : Subgroup (WithConv (H →ₐ[k] k)))
    (x : CommHopfAlgCat.quotient (_root_.CommHopfAlgCat.of k H) (vanishingIdeal S))
    (hx : ∀ g : S, (CommHopfAlgCat.liftQuotientPoint (_root_.CommHopfAlgCat.of k H)
      (vanishingIdeal S) (CommAlgCat.of k k) g.val
      (fun y hy ↦ (mem_vanishingIdeal S y).mp hy g)).ofConv x = 0) : x = 0 := by
  apply quotientEval_separates S x
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mkₐ_surjective k (pointKernelIdeal S) x
  intro g
  rw [Ideal.Quotient.mkₐ_eq_mk, quotientEval_mk]
  exact (CommHopfAlgCat.liftQuotientPoint_mk (_root_.CommHopfAlgCat.of k H)
    (vanishingIdeal S) (CommAlgCat.of k k) g.val
    (fun y hy ↦ (mem_vanishingIdeal S y).mp hy g) x).symm.trans (hx g)

/-- The underlying ideal is the intersection of the kernels of the evaluations. -/
theorem vanishingIdeal_toIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    (vanishingIdeal S).toIdeal = ⨅ g : S, RingHom.ker g.val.ofConv := by
  ext x
  rw [mem_toIdeal, mem_vanishingIdeal]
  simp [RingHom.mem_ker]

/-- The vanishing ideal of a point subgroup is radical. -/
theorem isRadical_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    (vanishingIdeal S).toIdeal.IsRadical := by
  rw [vanishingIdeal_toIdeal]
  exact Ideal.isRadical_iInf _ fun g ↦ (Ideal.isRadical_bot (R := k)).comap g.val.ofConv

/-- The closed subgroup cut out by the vanishing ideal of a point subgroup is reduced. -/
instance isReduced_quotient_vanishingIdeal (S : Subgroup (WithConv (H →ₐ[k] k))) :
    IsReduced (CommHopfAlgCat.quotient (_root_.CommHopfAlgCat.of k H)
      (vanishingIdeal S)) := by
  rw [← Ideal.isRadical_iff_quotient_reduced]
  exact isRadical_vanishingIdeal S

/-- A Hopf ideal vanishes on a point subgroup exactly when the associated closed subgroup
contains that point subgroup. This is the minimality property of its closed subgroup closure. -/
theorem le_vanishingIdeal_iff (S : Subgroup (WithConv (H →ₐ[k] k))) (I : HopfIdeal k H) :
    I ≤ vanishingIdeal S ↔
      S ≤ CommHopfAlgCat.quotientPointsSubgroup (CommHopfAlgCat.of k H) I (CommAlgCat.of k k) := by
  constructor
  · intro h g hg
    apply (CommHopfAlgCat.mem_quotientPointsSubgroup_iff
      (_root_.CommHopfAlgCat.of k H) I (CommAlgCat.of k k) g).mpr
    intro x hx
    exact (mem_vanishingIdeal S x).mp (h hx) ⟨g, hg⟩
  · intro h x hx
    apply (mem_vanishingIdeal S x).mpr
    intro g
    exact (CommHopfAlgCat.mem_quotientPointsSubgroup_iff
      (_root_.CommHopfAlgCat.of k H) I (CommAlgCat.of k k) g.val).mp (h g.2) x hx

/-- Evaluating the coordinate commutator at the points `g` and `h` is the same as first
contracting its left leg against `g` and then evaluating at `h`. -/
private theorem productMap_commutatorAlgHom_eq_apply_left (g h : H →ₐ[k] k) (x : H) :
    Algebra.TensorProduct.productMap g h (HopfAlgebra.commutatorAlgHom (R := k) (H := H) x) =
      h (Algebra.TensorProduct.productMap ((Algebra.ofId k H).comp g) (AlgHom.id k H)
        (HopfAlgebra.commutatorAlgHom (R := k) (H := H) x)) := by
  rw [← AlgHom.comp_apply h]
  congr 1
  ext a <;> simp

/-- Evaluating the coordinate commutator at the points `g` and `h` is the same as first
contracting its right leg against `h` and then evaluating at `g`. -/
private theorem productMap_commutatorAlgHom_eq_apply_right (g h : H →ₐ[k] k) (x : H) :
    Algebra.TensorProduct.productMap g h (HopfAlgebra.commutatorAlgHom (R := k) (H := H) x) =
      g (Algebra.TensorProduct.productMap (AlgHom.id k H) ((Algebra.ofId k H).comp h)
        (HopfAlgebra.commutatorAlgHom (R := k) (H := H) x)) := by
  rw [← AlgHom.comp_apply g]
  congr 1
  ext a <;> simp

/-- **Commutators of closures lie in the closure of the commutators.** For subgroups `S` and
`T` of rational points, the commutator of the closed subgroups they generate is contained in the
closed subgroup generated by `⁅S, T⁆`. Here the closed subgroup generated by `S` is the one cut
out by the functions vanishing on `S`. -/
theorem commutator_quotientPointsSubgroup_vanishingIdeal_le
    (S T : Subgroup (WithConv (H →ₐ[k] k))) :
    ⁅CommHopfAlgCat.quotientPointsSubgroup (_root_.CommHopfAlgCat.of k H) (vanishingIdeal S)
        (CommAlgCat.of k k),
      CommHopfAlgCat.quotientPointsSubgroup (_root_.CommHopfAlgCat.of k H) (vanishingIdeal T)
        (CommAlgCat.of k k)⁆ ≤
      CommHopfAlgCat.quotientPointsSubgroup (_root_.CommHopfAlgCat.of k H) (vanishingIdeal ⁅S, T⁆)
        (CommAlgCat.of k k) := by
  -- Freeze one argument of the commutator at a time: with the other argument fixed, the
  -- commutator is a regular function, so its vanishing on a subgroup extends to the closure.
  let c := HopfAlgebra.commutatorAlgHom (R := k) (H := H)
  have hval (g h : WithConv (H →ₐ[k] k)) (x : H) :
      (⁅g, h⁆ : WithConv (H →ₐ[k] k)).ofConv x =
        Algebra.TensorProduct.productMap g.ofConv h.ofConv (c x) := by
    rw [← HopfAlgebra.productMap_comp_commutatorAlgHom g h, AlgHom.comp_apply]
  rw [Subgroup.commutator_le]
  intro g hg h hh
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff] at hg hh ⊢
  intro x hx
  have hST (s : S) (t : T) :
      Algebra.TensorProduct.productMap s.val.ofConv t.val.ofConv (c x) = 0 := by
    rw [← hval]
    exact (mem_vanishingIdeal _ x).mp hx
      ⟨_, Subgroup.commutator_mem_commutator s.2 t.2⟩
  -- Fixing the first argument in `S`, vanishing on `T` extends to its closure.
  have hSh (s : S) :
      Algebra.TensorProduct.productMap s.val.ofConv h.ofConv (c x) = 0 := by
    rw [productMap_commutatorAlgHom_eq_apply_left]
    refine hh _ ((mem_vanishingIdeal _ _).mpr fun t ↦ ?_)
    rw [← productMap_commutatorAlgHom_eq_apply_left]
    exact hST s t
  -- Fixing the second argument at `h`, vanishing on `S` extends to its closure.
  rw [hval, productMap_commutatorAlgHom_eq_apply_right]
  refine hg _ ((mem_vanishingIdeal _ _).mpr fun s ↦ ?_)
  rw [← productMap_commutatorAlgHom_eq_apply_right]
  exact hSh s

/-- The closed subgroup generated by the trivial subgroup of rational points is trivial. -/
@[simp↓]
theorem quotientPointsSubgroup_vanishingIdeal_bot :
    CommHopfAlgCat.quotientPointsSubgroup (_root_.CommHopfAlgCat.of k H)
      (vanishingIdeal (⊥ : Subgroup (WithConv (H →ₐ[k] k)))) (CommAlgCat.of k k) = ⊥ := by
  refine eq_bot_iff.mpr fun g hg ↦ Subgroup.mem_bot.mpr ?_
  refine WithConv.ofConv_injective (AlgHom.ext fun x ↦ ?_)
  have hx : x - algebraMap k H (Coalgebra.counit (R := k) x) ∈
      vanishingIdeal (⊥ : Subgroup (WithConv (H →ₐ[k] k))) := by
    refine (mem_vanishingIdeal _ _).mpr fun s ↦ ?_
    rw [Subgroup.mem_bot.mp s.2, AlgHom.convOne_apply]
    simp
  have hzero := (CommHopfAlgCat.mem_quotientPointsSubgroup_iff _ _ _ g).mp hg _ hx
  rw [map_sub, sub_eq_zero] at hzero
  rw [hzero, AlgHom.commutes]
  exact (AlgHom.convOne_apply x).symm

/-- The closure of the trivial point subgroup is the identity subgroup scheme. -/
@[simp] theorem vanishingIdeal_bot :
    vanishingIdeal (⊥ : Subgroup (WithConv (H →ₐ[k] k))) = augmentation k H := by
  ext x
  simp [mem_vanishingIdeal, mem_augmentation, AlgHom.convOne_apply]

/-- A point subgroup has trivial reduced closure exactly when it is trivial. -/
@[simp] theorem vanishingIdeal_eq_augmentation_iff
    (S : Subgroup (WithConv (H →ₐ[k] k))) :
    vanishingIdeal S = augmentation k H ↔ S = ⊥ := by
  constructor
  · intro h
    apply le_bot_iff.mp
    intro g hg
    apply Subgroup.mem_bot.mpr
    apply CommHopfAlgCat.eq_one_of_mem_quotientPointsSubgroup_augmentation
      (_root_.CommHopfAlgCat.of k H) (CommAlgCat.of k k)
    exact ((le_vanishingIdeal_iff S (augmentation k H)).mp h.ge) hg
  · rintro rfl
    exact vanishingIdeal_bot

/-- Rational points are schematically dense in a reduced finite-type affine group over an
algebraically closed field. -/
@[simp] theorem vanishingIdeal_top [IsAlgClosed k] [Algebra.FiniteType k H] [IsReduced H] :
    vanishingIdeal (⊤ : Subgroup (WithConv (H →ₐ[k] k))) = ⊥ := by
  apply le_bot_iff.mp
  intro x hx
  apply HopfIdeal.mem_bot.mpr
  apply eq_of_forall_algHom_apply_eq (k := k) (K := k)
  intro f
  exact ((mem_vanishingIdeal _ x).mp hx ⟨toConv f, Subgroup.mem_top _⟩).trans
    (map_zero f).symm

end

end TauCeti.HopfIdeal
