/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Group.Coprime
public import TauCeti.Algebra.Group.Subgroup.Map
public import TauCeti.Algebra.Group.Subgroup.Normalizer
public import TauCeti.GroupTheory.OrderOfElement.PPart
public import TauCeti.GroupTheory.PGroup
public import Mathlib.Data.Nat.Factorization.Basic
public import Mathlib.GroupTheory.Complement
public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.GroupTheory.Sylow

/-!
# Elementary and hyperelementary groups

Fix a natural number `p`. A group is **`p`-elementary** when it is the internal direct product of a
cyclic subgroup of order prime to `p` and a `p`-subgroup, and **`p`-hyperelementary** when it has a
cyclic normal subgroup of order prime to `p` whose quotient is a `p`-group; a group is
**elementary** (respectively **hyperelementary**) when it is `p`-elementary (respectively
`p`-hyperelementary) for some prime `p`. Mathlib has `IsCyclic` and `IsPGroup` but no predicate
built from them in this shape, so this file supplies the two definitions together with the closure
properties they are used through.

The definitions are the ones Brauer's induction theorem is stated against: Artin's theorem writes a
character as a rational combination of characters induced from *cyclic* subgroups, and Brauer's
sharpens this to an integral combination of characters induced from *elementary* subgroups. That
the elementary groups include the cyclic ones is the content of
`TauCeti.isPElementary_of_isCyclic` below: a finite cyclic group is `p`-elementary for **every**
prime `p`, by splitting it as the product of its `p`-part and its `p'`-part.

The second half of the file builds the `p`-elementary subgroups that carry arithmetic information.
For a finite-order element `x` and a prime `p`, a suitable Sylow `p`-subgroup of the centraliser
of the `p`-free part `s` of `x` yields a join with `⟨s⟩` that contains `x`. Every such join is
`p`-elementary, and when the Sylow subgroup has finite index in the centraliser the join has index
prime to `p` there. The cyclic subgroups are already elementary, so it is this larger subgroup, not
`⟨x⟩`, that carries content.

## Main definitions

* `TauCeti.IsPElementary p G`: `G` is the internal direct product of a cyclic subgroup of order
  prime to `p` and a `p`-subgroup.
* `TauCeti.IsPHyperelementary p G`: `G` has a cyclic normal subgroup of order prime to `p` with
  `p`-group quotient.
* `TauCeti.IsElementary G`, `TauCeti.IsHyperelementary G`: the same, for some prime `p`.
* `TauCeti.pElementaryOfSylow s P`: for an element `s` of order prime to `p` and a Sylow
  `p`-subgroup `P` of the centraliser of `s`, the subgroup of `G` generated by `s` together
  with `P`.
* `TauCeti.pFreePartHom s P`: the `p`-free part as a homomorphism from that subgroup onto its
  cyclic factor `⟨s⟩`, the projection along which class functions of `⟨s⟩` are pulled back.

Each of the four predicates is restated as an `Iff` by `TauCeti.isPElementary_def`,
`TauCeti.isPHyperelementary_def`, `TauCeti.isElementary_def` and `TauCeti.isHyperelementary_def`.

## Main results

* `TauCeti.isPElementary_of_isCyclic`: every finite cyclic group is `p`-elementary, for every
  prime `p`; hence `TauCeti.isElementary_of_isCyclic`, cyclic groups are elementary.
* `TauCeti.IsPElementary.isPHyperelementary`: `p`-elementary groups are `p`-hyperelementary.
* `TauCeti.IsPElementary.of_injective`, `TauCeti.IsPHyperelementary.of_injective`: both classes are
  closed under passing to a subgroup, in the form of an injective homomorphism into the group. The
  subgroup forms are `TauCeti.IsPElementary.subgroup` and `TauCeti.IsPHyperelementary.subgroup`.
* `TauCeti.IsHyperelementary.isSolvable`: a finite hyperelementary group is solvable, whence
  `TauCeti.not_isElementary_perm_fin_5`, the symmetric group on five letters is not elementary.
* `TauCeti.isPElementary_sup_of_commute`: a cyclic subgroup of order prime to `p` and a
  `p`-subgroup that centralises it generate a `p`-elementary subgroup, and
  `TauCeti.disjoint_of_not_dvd_natCard_of_isPGroup` supplies the disjointness it asks for.
* `TauCeti.isPElementary_pElementaryOfSylow` and
  `TauCeti.not_dvd_relIndex_pElementaryOfSylow`: `TauCeti.pElementaryOfSylow s P` is
  `p`-elementary, and, provided `P` has finite index in the centraliser of `s`, its index there is
  prime to `p`.
* `TauCeti.exists_mem_pElementaryOfSylow`: every finite-order element `x` lies in
  `TauCeti.pElementaryOfSylow` of its `p`-free part, for a suitable Sylow `p`-subgroup.
* `TauCeti.pFreePart_mem_zpowers_of_mem_pElementaryOfSylow` and
  `TauCeti.pPart_mem_map_sylow_of_mem_pElementaryOfSylow`: the `p`-free part and the `p`-part of
  an element of `TauCeti.pElementaryOfSylow s P` lie in its cyclic and its Sylow factor, and
  `TauCeti.pFreePart_mul_of_mem_pElementaryOfSylow`: the `p`-free part is multiplicative there.

## Implementation notes

The `p`-group condition on the quotient in `TauCeti.IsPHyperelementary` is spelled out elementwise,
as `∀ g, ∃ k, g ^ p ^ k ∈ C`, rather than as `IsPGroup p (G ⧸ C)`. The two are equivalent
(`TauCeti.isPHyperelementary_iff_isPGroup_quotient`, and the two implications it is assembled from,
`TauCeti.isPGroup_quotient_of_forall_exists_pow_mem` and
`TauCeti.isPHyperelementary_of_isPGroup_quotient`), but the quotient `G ⧸ C` is a group only once
the normality of `C` is available as an instance, which an existential quantifier inside the
definition cannot supply. The elementwise form keeps the definition free of that bookkeeping and is
also the form the closure proofs use directly.

`TauCeti.IsPElementary` records the internal direct product decomposition as
`Subgroup.IsComplement'` together with elementwise commutation, rather than as normality of both
factors: this is the form the proofs consume, and normality of the cyclic factor is derived from it
in `TauCeti.normal_of_commute_of_sup_eq_top`.

`TauCeti.pElementaryOfSylow` takes the Sylow subgroup as an argument instead of choosing one: a
centraliser has in general several Sylow `p`-subgroups, and everything proved about the resulting
subgroup holds for each of them. `TauCeti.exists_mem_pElementaryOfSylow` makes the choice that puts
a prescribed element inside.

## References

This supplies a prerequisite for
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`,
Layer 6 ("Elementary and hyperelementary subgroups"), which asks for exactly these two predicates
"from these orientations, with their basic closure properties", as the indexing sets of Artin's and
Brauer's induction theorems.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Part II, §10.
-/

public section

namespace TauCeti

open _root_.Subgroup

section Defs

variable (p : ℕ) (G : Type*) [Group G]

/-- A group `G` is **`p`-elementary** when it is the internal direct product of a cyclic subgroup
of order prime to `p` and a `p`-subgroup: there are subgroups `C` and `P` of `G` with `C` cyclic of
order prime to `p`, `P` a `p`-group, every element of `C` commuting with every element of `P`, and
`C` a complement of `P`. -/
def IsPElementary : Prop :=
  ∃ C P : Subgroup G, IsCyclic C ∧ ¬ p ∣ Nat.card C ∧ IsPGroup p P ∧
    (∀ c ∈ C, ∀ x ∈ P, Commute c x) ∧ C.IsComplement' P

/-- A group `G` is **`p`-hyperelementary** when it has a cyclic normal subgroup `C` of order prime
to `p` whose quotient `G ⧸ C` is a `p`-group. The condition on the quotient is spelled elementwise,
as `∀ g, ∃ k, g ^ p ^ k ∈ C`; see `TauCeti.isPGroup_quotient_of_forall_exists_pow_mem` for the
identification with `IsPGroup p (G ⧸ C)`. -/
def IsPHyperelementary : Prop :=
  ∃ C : Subgroup G, C.Normal ∧ IsCyclic C ∧ ¬ p ∣ Nat.card C ∧
    ∀ g : G, ∃ k : ℕ, g ^ p ^ k ∈ C

/-- A group is **elementary** when it is `p`-elementary for some prime `p`. -/
def IsElementary : Prop := ∃ q : ℕ, q.Prime ∧ IsPElementary q G

/-- A group is **hyperelementary** when it is `p`-hyperelementary for some prime `p`. -/
def IsHyperelementary : Prop := ∃ q : ℕ, q.Prime ∧ IsPHyperelementary q G

end Defs

variable {p : ℕ} {G H : Type*} [Group G] [Group H]

/-! ### Restating the definitions

The four definitions above are `public` but not `@[expose]`, so downstream modules see their
statements and not their bodies: neither `unfold IsPElementary` nor `simp only [IsPElementary]`
is available there. The `Iff.rfl` lemmas in this section are therefore the only way to eliminate
the predicates outside this file, as `Subgroup.isComplement'_def` is for `Subgroup.IsComplement'`
and `isPrimePow_def` is for `IsPrimePow`.
-/

/-- `TauCeti.IsPElementary p G` unfolded: a decomposition of `G` into a cyclic subgroup of order
prime to `p` and a complementary `p`-subgroup commuting with it elementwise. -/
theorem isPElementary_def : IsPElementary p G ↔
    ∃ C P : Subgroup G, IsCyclic C ∧ ¬ p ∣ Nat.card C ∧ IsPGroup p P ∧
      (∀ c ∈ C, ∀ x ∈ P, Commute c x) ∧ C.IsComplement' P :=
  Iff.rfl

/-- `TauCeti.IsPHyperelementary p G` unfolded: a cyclic normal subgroup of order prime to `p` such
that every element of `G` has a `p`-power inside it. See
`TauCeti.isPHyperelementary_iff_isPGroup_quotient` for the quotient reading of the last clause. -/
theorem isPHyperelementary_def : IsPHyperelementary p G ↔
    ∃ C : Subgroup G, C.Normal ∧ IsCyclic C ∧ ¬ p ∣ Nat.card C ∧
      ∀ g : G, ∃ k : ℕ, g ^ p ^ k ∈ C :=
  Iff.rfl

/-- `TauCeti.IsElementary G` unfolded: `p`-elementarity for some prime `p`. -/
theorem isElementary_def : IsElementary G ↔ ∃ q : ℕ, q.Prime ∧ IsPElementary q G :=
  Iff.rfl

/-- `TauCeti.IsHyperelementary G` unfolded: `p`-hyperelementarity for some prime `p`. -/
theorem isHyperelementary_def : IsHyperelementary G ↔ ∃ q : ℕ, q.Prime ∧ IsPHyperelementary q G :=
  Iff.rfl

/-! ### The quotient form of hyperelementarity -/

/-- If every element of `G` has a `p`-power lying in a normal subgroup `C`, the quotient `G ⧸ C` is
a `p`-group. This is the quotient reading of the last clause of `TauCeti.IsPHyperelementary`. -/
theorem isPGroup_quotient_of_forall_exists_pow_mem {C : Subgroup G} [C.Normal]
    (h : ∀ g : G, ∃ k : ℕ, g ^ p ^ k ∈ C) : IsPGroup p (G ⧸ C) := by
  intro x
  obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective x
  obtain ⟨k, hk⟩ := h g
  exact ⟨k, by rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]; exact hk⟩

/-- A cyclic normal subgroup of order prime to `p` with `p`-group quotient exhibits `G` as
`p`-hyperelementary. -/
theorem isPHyperelementary_of_isPGroup_quotient (C : Subgroup G) [hC : C.Normal]
    (h₁ : IsCyclic C) (h₂ : ¬ p ∣ Nat.card C) (h₃ : IsPGroup p (G ⧸ C)) :
    IsPHyperelementary p G := by
  refine ⟨C, hC, h₁, h₂, fun g => ?_⟩
  obtain ⟨k, hk⟩ := h₃ (g : G ⧸ C)
  rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff] at hk
  exact ⟨k, hk⟩

/-- `G` is `p`-hyperelementary exactly when it has a cyclic normal subgroup `C` of order prime to
`p` with `IsPGroup p (G ⧸ C)`. This is the quotient form of the definition, with the normality
witness packaged so that it supplies the group structure on `G ⧸ C`. -/
theorem isPHyperelementary_iff_isPGroup_quotient : IsPHyperelementary p G ↔
    ∃ (C : Subgroup G) (hC : C.Normal),
      IsCyclic C ∧ ¬ p ∣ Nat.card C ∧ (letI := hC; IsPGroup p (G ⧸ C)) := by
  refine ⟨fun ⟨C, hC, h₁, h₂, h₃⟩ => ?_, fun ⟨C, hC, h₁, h₂, h₃⟩ => ?_⟩ <;> let := hC
  · exact ⟨C, hC, h₁, h₂, isPGroup_quotient_of_forall_exists_pow_mem h₃⟩
  · exact isPHyperelementary_of_isPGroup_quotient C h₁ h₂ h₃

/-! ### Elementary groups are hyperelementary -/

/-- A subgroup centralised elementwise by a complement is normal: the complement form of
`TauCeti.normal_of_commute_of_sup_eq_top`, matching the shape in which `TauCeti.IsPElementary`
records its decomposition. -/
theorem normal_of_commute_of_isComplement' {C P : Subgroup G}
    (hcomm : ∀ c ∈ C, ∀ x ∈ P, Commute c x) (hcompl : C.IsComplement' P) : C.Normal :=
  normal_of_commute_of_sup_eq_top hcomm hcompl.sup_eq_top

/-- A `p`-elementary group is `p`-hyperelementary: the cyclic factor is normal, and the quotient by
it is the `p`-group factor. -/
theorem IsPElementary.isPHyperelementary (h : IsPElementary p G) : IsPHyperelementary p G := by
  obtain ⟨C, P, hC, hCp, hP, hcomm, hcompl⟩ := h
  refine ⟨C, normal_of_commute_of_isComplement' hcomm hcompl, hC, hCp, fun g => ?_⟩
  obtain ⟨⟨a, b⟩, rfl⟩ := hcompl.2 g
  obtain ⟨k, hk⟩ := hP b
  refine ⟨k, ?_⟩
  have hk' : (b : G) ^ p ^ k = 1 := by exact_mod_cast hk
  rw [(hcomm a a.2 b b.2).mul_pow, hk', mul_one]
  exact pow_mem a.2 _

/-- An elementary group is hyperelementary. -/
theorem IsElementary.isHyperelementary (h : IsElementary G) : IsHyperelementary G :=
  h.imp fun _ hq => ⟨hq.1, hq.2.isPHyperelementary⟩

/-! ### Basic examples -/

/-- A `p`-group is `p`-elementary, with trivial cyclic factor. -/
theorem isPElementary_of_isPGroup (hp : p ≠ 1) (h : IsPGroup p G) : IsPElementary p G := by
  refine ⟨⊥, ⊤, inferInstance, ?_, h.of_equiv topEquiv.symm, ?_, ?_⟩
  · simpa using hp
  · rintro c hc x -
    rw [mem_bot] at hc
    simp [hc]
  · exact isComplement'_bot_left.mpr rfl

/-- A finite cyclic group is `p`-elementary for **every** prime `p`: writing `Nat.card G` as
`p ^ a * m` with `p ∤ m` and taking a generator `g`, the subgroup generated by `g ^ (p ^ a)` is
cyclic of order `m` and the subgroup generated by `g ^ m` is a `p`-group of order `p ^ a`, and the
two are complementary because their orders are coprime.

So the elementary subgroups of a finite group include all its cyclic subgroups: Brauer's induction
theorem, indexed by elementary subgroups, refines Artin's, indexed by cyclic ones. -/
theorem isPElementary_of_isCyclic [Finite G] [IsCyclic G] (p : ℕ) [Fact p.Prime] :
    IsPElementary p G := by
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := G)
  have hord : orderOf g = Nat.card G := orderOf_eq_card_of_forall_mem_zpowers hg
  have hN0 : Nat.card G ≠ 0 := Nat.card_pos.ne'
  have hm0 : ordCompl[p] (Nat.card G) ≠ 0 := (Nat.ordCompl_pos p hN0).ne'
  have hqm : ordProj[p] (Nat.card G) * ordCompl[p] (Nat.card G) = Nat.card G :=
    Nat.ordProj_mul_ordCompl_eq_self _ p
  have hmp : ¬ p ∣ ordCompl[p] (Nat.card G) :=
    Nat.not_dvd_ordCompl (Fact.out : p.Prime) hN0
  -- the `p'`-part and the `p`-part of `G`, as subgroups generated by powers of the generator
  have hcard : Nat.card (zpowers (g ^ ordProj[p] (Nat.card G))) = ordCompl[p] (Nat.card G) := by
    rw [Nat.card_zpowers, orderOf_pow_of_dvd (Nat.ordProj_pos _ p).ne' (hord ▸ Nat.ordProj_dvd _ p),
      hord]
  have hcard' : Nat.card (zpowers (g ^ ordCompl[p] (Nat.card G))) = ordProj[p] (Nat.card G) := by
    rw [Nat.card_zpowers, orderOf_pow_of_dvd hm0 (hord ▸ Nat.ordCompl_dvd _ p), hord]
    exact Nat.div_eq_of_eq_mul_left (Nat.pos_of_ne_zero hm0) hqm.symm
  have hcop : Nat.Coprime (ordCompl[p] (Nat.card G)) (ordProj[p] (Nat.card G)) :=
    Nat.Coprime.pow_right _ ((Nat.Prime.coprime_iff_not_dvd Fact.out).mpr hmp).symm
  have hpow : IsPGroup p (zpowers (g ^ ordCompl[p] (Nat.card G))) :=
    IsPGroup.of_card_dvd_pow (n := (Nat.card G).factorization p) (by rw [hcard'])
  refine ⟨zpowers (g ^ ordProj[p] (Nat.card G)), zpowers (g ^ ordCompl[p] (Nat.card G)),
    inferInstance, by rw [hcard]; exact hmp, hpow, fun c _ x _ => mul_comm' c x, ?_⟩
  exact isComplement'_of_coprime (by rw [hcard, hcard', mul_comm]; exact hqm)
    (by rw [hcard, hcard']; exact hcop)

/-- A finite cyclic group is elementary. -/
theorem isElementary_of_isCyclic [Finite G] [IsCyclic G] : IsElementary G :=
  ⟨2, Nat.prime_two, isPElementary_of_isCyclic 2⟩

/-- A finite cyclic group is hyperelementary. -/
theorem isHyperelementary_of_isCyclic [Finite G] [IsCyclic G] : IsHyperelementary G :=
  isElementary_of_isCyclic.isHyperelementary

/-! ### Closure under subgroups -/

/-- `p`-hyperelementarity passes to subgroups, in the form of an injective homomorphism into the
group. -/
theorem IsPHyperelementary.of_injective (h : IsPHyperelementary p G) (f : H →* G)
    (hf : Function.Injective f) : IsPHyperelementary p H := by
  obtain ⟨C, hCnormal, hCcyclic, hCp, hquot⟩ := h
  have := hCcyclic
  refine ⟨C.comap f, hCnormal.comap f,
    isCyclic_of_injective _ (MonoidHom.subgroupComap_injective_of_injective hf C),
    fun hdvd => hCp (hdvd.trans (Subgroup.card_comap_dvd_of_injective C f hf)), fun y => ?_⟩
  obtain ⟨k, hk⟩ := hquot (f y)
  exact ⟨k, mem_comap.mpr (by rwa [map_pow])⟩

/-- Along any `f : H →* G`, an element `y` of `H` factors as a preimage of `C` times a preimage of
the `p`-subgroup `P`, given a commuting factorization of the single element `f y`.

Only coprimality of `p` with `Nat.card C` is used — not primality of `p`, not that `C` and `P` form
a complement, not finiteness of `P`, and, since only `f y` is decomposed, not surjectivity of
`f`. -/
private theorem exists_mem_comap_mul_mem_comap_eq {C P : Subgroup G}
    (hcop : Nat.Coprime p (Nat.card C)) (hP : IsPGroup p P)
    (hcomm : ∀ c ∈ C, ∀ x ∈ P, Commute c x) (f : H →* G) {y : H}
    (hfac : ∃ a : C, ∃ b : P, (a : G) * b = f y) :
    ∃ c ∈ C.comap f, ∃ x ∈ P.comap f, c * x = y := by
  obtain ⟨a, b, hab⟩ := hfac
  obtain ⟨k, hk⟩ := hP b
  have ha : (a : G) ^ Nat.card C = 1 := by
    exact_mod_cast congrArg Subtype.val (pow_card_eq_one' (x := a))
  -- the two factors of a preimage, and the Bézout identity between their orders; the exponent
  -- killing the `p`-part is the one `hP` supplies for that element, so `P` need not be finite
  set m := Nat.card C
  set n := p ^ k
  have hcop : Nat.Coprime n m := Nat.Coprime.pow_left _ hcop
  have hb : (b : G) ^ n = 1 := by exact_mod_cast hk
  have hyn : f (y ^ n) ∈ C := by
    rw [map_pow, ← hab, (hcomm a a.2 b b.2).mul_pow, hb, mul_one]
    exact pow_mem a.2 _
  have hym : f (y ^ m) ∈ P := by
    rw [map_pow, ← hab, (hcomm a a.2 b b.2).mul_pow, ha, one_mul]
    exact pow_mem b.2 _
  obtain ⟨i, j, hij⟩ := exists_zpow_mul_zpow_eq_of_coprime hcop y
  exact ⟨(y ^ n) ^ i, zpow_mem (mem_comap.mpr hyn) _,
    (y ^ m) ^ j, zpow_mem (mem_comap.mpr hym) _, hij⟩

/-- `p`-elementarity passes to subgroups, in the form of an injective homomorphism into the group.

The decomposition of a subgroup is inherited factor by factor: the crux is that the subgroup is
still the product of the two intersections, which follows via
`TauCeti.exists_zpow_mul_zpow_eq_of_coprime` from a Bézout identity between the orders of the two
factors, coprime because one is prime to `p` and the other is a power of `p`. -/
theorem IsPElementary.of_injective [Fact p.Prime] (h : IsPElementary p G) (f : H →* G)
    (hf : Function.Injective f) : IsPElementary p H := by
  obtain ⟨C, P, hC, hCp, hP, hcomm, hcompl⟩ := h
  have := hC
  refine ⟨C.comap f, P.comap f,
    isCyclic_of_injective _ (MonoidHom.subgroupComap_injective_of_injective hf C),
    fun hdvd => hCp (hdvd.trans (Subgroup.card_comap_dvd_of_injective C f hf)),
    hP.of_injective _ (MonoidHom.subgroupComap_injective_of_injective hf P), ?_, ?_⟩
  · intro c hc x hx
    refine hf ?_
    rw [map_mul, map_mul]
    exact hcomm _ (mem_comap.mp hc) _ (mem_comap.mp hx)
  · refine isComplement'_of_disjoint_and_mul_eq_univ ?_ ?_
    · rw [disjoint_def]
      intro y hy₁ hy₂
      have : f y = 1 :=
        disjoint_def.mp hcompl.disjoint (mem_comap.mp hy₁) (mem_comap.mp hy₂)
      exact hf (this.trans (map_one f).symm)
    · refine Set.eq_univ_iff_forall.mpr fun y => ?_
      obtain ⟨c, hc, x, hx, hcx⟩ :=
        exists_mem_comap_mul_mem_comap_eq ((Nat.Prime.coprime_iff_not_dvd Fact.out).mpr hCp) hP
          hcomm f (let ⟨⟨a, b⟩, hab⟩ := hcompl.2 (f y); ⟨a, b, hab⟩)
      exact Set.mem_mul.mpr ⟨c, hc, x, hx, hcx⟩

/-- `p`-hyperelementarity passes to subgroups. -/
theorem IsPHyperelementary.subgroup (h : IsPHyperelementary p G) (K : Subgroup G) :
    IsPHyperelementary p K :=
  h.of_injective K.subtype K.subtype_injective

/-- `p`-elementarity passes to subgroups. -/
theorem IsPElementary.subgroup [Fact p.Prime] (h : IsPElementary p G)
    (K : Subgroup G) : IsPElementary p K :=
  h.of_injective K.subtype K.subtype_injective

/-- Hyperelementarity passes to subgroups. -/
theorem IsHyperelementary.subgroup (h : IsHyperelementary G) (K : Subgroup G) :
    IsHyperelementary K :=
  h.imp fun _ hq => ⟨hq.1, hq.2.subgroup K⟩

/-- Elementarity passes to subgroups. -/
theorem IsElementary.subgroup (h : IsElementary G) (K : Subgroup G) :
    IsElementary K := by
  obtain ⟨q, hq, hqG⟩ := h
  have : Fact q.Prime := ⟨hq⟩
  exact ⟨q, hq, hqG.subgroup K⟩

/-! ### Solvability -/

/-- A finite `p`-hyperelementary group is solvable: the cyclic normal subgroup `C` supplied by the
definition is abelian, hence solvable, and the quotient `G ⧸ C` is a `p`-group, hence nilpotent and
so solvable too. -/
theorem IsPHyperelementary.isSolvable [Finite G] [Fact p.Prime] (h : IsPHyperelementary p G) :
    Group.IsSolvable G := by
  obtain ⟨C, hCnormal, hCcyclic, -, hquot⟩ := h
  have := hCnormal
  have := hCcyclic
  have : Group.IsSolvable C := Group.isSolvable_of_comm mul_comm'
  have : Group.IsNilpotent (G ⧸ C) :=
    IsPGroup.isNilpotent (isPGroup_quotient_of_forall_exists_pow_mem hquot)
  exact (Group.isSolvable_iff_subgroup_quotient C).mpr ⟨inferInstance, inferInstance⟩

/-- A finite hyperelementary group is solvable. -/
theorem IsHyperelementary.isSolvable [Finite G] (h : IsHyperelementary G) :
    Group.IsSolvable G := by
  obtain ⟨q, hq, hqG⟩ := h
  have : Fact q.Prime := ⟨hq⟩
  exact hqG.isSolvable

/-- A finite elementary group is solvable. -/
theorem IsElementary.isSolvable [Finite G] (h : IsElementary G) : Group.IsSolvable G :=
  h.isHyperelementary.isSolvable

/-- The symmetric group on five letters is not hyperelementary, since it is not solvable. Together
with `TauCeti.isElementary_of_isCyclic` this pins the two predicates between the cyclic groups and
the solvable ones. -/
theorem not_isHyperelementary_perm_fin_5 : ¬ IsHyperelementary (Equiv.Perm (Fin 5)) :=
  fun h => Equiv.Perm.not_isSolvable_fin_5 h.isSolvable

/-- The symmetric group on five letters is not elementary. -/
theorem not_isElementary_perm_fin_5 : ¬ IsElementary (Equiv.Perm (Fin 5)) :=
  fun h => not_isHyperelementary_perm_fin_5 h.isHyperelementary

/-! ### `p`-elementary subgroups built from a Sylow subgroup of a centraliser

The cyclic subgroups of a finite group are already elementary, so they witness nothing beyond
`TauCeti.isPElementary_of_isCyclic`. What Brauer's induction theorem needs is a *large* elementary
subgroup attached to an element: for `x : G` with `p`-free part `s`, some suitable Sylow
`p`-subgroup of the centraliser of `s` yields a join with `⟨s⟩` that contains `x`. Every such join
is `p`-elementary, and as soon as the Sylow subgroup has finite index in that centraliser the join
has relative index prime to `p` there, which is the arithmetic the induction theorem runs on.
-/

section OfSylow

/-- Two subgroups centralising one another, one cyclic of order prime to `p` and one a `p`-group,
generate a `p`-elementary subgroup. -/
theorem isPElementary_sup_of_commute {C Q : Subgroup G} (hC : IsCyclic C)
    (hCp : ¬ p ∣ Nat.card C) (hQ : IsPGroup p Q) (hdisj : Disjoint C Q)
    (hcomm : ∀ c ∈ C, ∀ y ∈ Q, Commute c y) : IsPElementary p ↥(C ⊔ Q) := by
  have hCle : C ≤ C ⊔ Q := le_sup_left
  have hQle : Q ≤ C ⊔ Q := le_sup_right
  have hnorm : C ≤ normalizer (Q : Set G) :=
    le_trans (fun c hc => mem_centralizer_iff.2 fun y hy => (hcomm c hc y hy).symm.eq)
      (centralizer_le_normalizer _)
  refine ⟨C.subgroupOf (C ⊔ Q), Q.subgroupOf (C ⊔ Q), ?_, ?_, ?_, ?_, ?_⟩
  · exact isCyclic_of_surjective (hH := hC) (subgroupOfEquivOfLe hCle).symm
      (subgroupOfEquivOfLe hCle).symm.surjective
  · rwa [Nat.card_congr (subgroupOfEquivOfLe hCle).toEquiv]
  · exact hQ.of_equiv (subgroupOfEquivOfLe hQle).symm
  · intro c hc y hy
    rw [mem_subgroupOf] at hc hy
    exact Subtype.ext (hcomm _ hc _ hy)
  · refine isComplement'_of_disjoint_and_mul_eq_univ ?_ (Set.eq_univ_of_forall fun z => ?_)
    · rw [disjoint_def]
      intro z hz hz'
      rw [mem_subgroupOf] at hz hz'
      exact Subtype.ext (disjoint_def.1 hdisj hz hz')
    · have hz : (z : G) ∈ (↑(C ⊔ Q) : Set G) := z.2
      rw [coe_mul_of_left_le_normalizer_right C Q hnorm] at hz
      obtain ⟨c, hc, y, hy, hcy⟩ := hz
      exact ⟨⟨c, hCle hc⟩, mem_subgroupOf.2 hc, ⟨y, hQle hy⟩, mem_subgroupOf.2 hy,
        Subtype.ext hcy⟩

variable (s : G) (P : Sylow p (centralizer ({s} : Set G)))

/-- The `p`-elementary subgroup attached to an element `s` of order prime to `p` together with a
Sylow `p`-subgroup `P` of the centraliser of `s`: the join of the cyclic group generated by `s`
with `P`. It is `p`-elementary by `TauCeti.isPElementary_pElementaryOfSylow`, and, when `P` has
finite index in the centraliser, its relative index there is prime to `p` by
`TauCeti.not_dvd_relIndex_pElementaryOfSylow`. -/
noncomputable def pElementaryOfSylow : Subgroup G :=
  zpowers s ⊔ (P : Subgroup (centralizer ({s} : Set G))).map (centralizer ({s} : Set G)).subtype

theorem zpowers_le_pElementaryOfSylow : zpowers s ≤ pElementaryOfSylow s P := le_sup_left

theorem self_mem_pElementaryOfSylow : s ∈ pElementaryOfSylow s P :=
  zpowers_le_pElementaryOfSylow s P (mem_zpowers s)

theorem map_sylow_le_pElementaryOfSylow :
    (P : Subgroup (centralizer ({s} : Set G))).map (centralizer ({s} : Set G)).subtype ≤
      pElementaryOfSylow s P := le_sup_right

@[simp]
theorem pElementaryOfSylow_le_iff {K : Subgroup G} :
    pElementaryOfSylow s P ≤ K ↔ s ∈ K ∧
      (P : Subgroup (centralizer ({s} : Set G))).map (centralizer ({s} : Set G)).subtype ≤ K := by
  rw [pElementaryOfSylow, sup_le_iff, zpowers_le]

theorem pElementaryOfSylow_le_centralizer :
    pElementaryOfSylow s P ≤ centralizer ({s} : Set G) :=
  (pElementaryOfSylow_le_iff s P).2
    ⟨mem_centralizer_singleton_iff.2 rfl, map_subtype_le _⟩

/-- Every element of `⟨s⟩` commutes with every element centralising `s`. -/
theorem commute_of_mem_zpowers_of_mem_centralizer {c y : G} (hc : c ∈ zpowers s)
    (hy : y ∈ centralizer ({s} : Set G)) : Commute c y := by
  obtain ⟨n, rfl⟩ := mem_zpowers_iff.1 hc
  have hcom : Commute y s := mem_centralizer_singleton_iff.1 hy
  exact hcom.symm.zpow_left n

/-- The subgroup attached to a `p`-regular element and a Sylow `p`-subgroup of its centraliser is
indeed `p`-elementary. -/
theorem isPElementary_pElementaryOfSylow [Fact p.Prime] (hs : ¬ p ∣ orderOf s) :
    IsPElementary p ↥(pElementaryOfSylow s P) := by
  have hQ : IsPGroup p
      ((P : Subgroup (centralizer ({s} : Set G))).map (centralizer ({s} : Set G)).subtype) :=
    P.2.map _
  have hCp : ¬ p ∣ Nat.card (zpowers s) := by rwa [Nat.card_zpowers]
  exact isPElementary_sup_of_commute inferInstance hCp hQ
    (disjoint_of_not_dvd_natCard_of_isPGroup hCp hQ)
    fun c hc y hy => commute_of_mem_zpowers_of_mem_centralizer s hc (map_subtype_le _ hy)

/-- The subgroup attached to a `p`-regular element `s` and a Sylow `p`-subgroup `P` of finite index
in its centraliser has index prime to `p` inside that centraliser: it contains a full Sylow
`p`-subgroup. -/
theorem not_dvd_relIndex_pElementaryOfSylow [Fact p.Prime]
    [(P : Subgroup (centralizer ({s} : Set G))).FiniteIndex] :
    ¬ p ∣ (pElementaryOfSylow s P).relIndex (centralizer ({s} : Set G)) := by
  have hle : (P : Subgroup (centralizer ({s} : Set G))) ≤
      (pElementaryOfSylow s P).subgroupOf (centralizer ({s} : Set G)) := fun y hy =>
    mem_subgroupOf.2 (map_sylow_le_pElementaryOfSylow s P ⟨y, hy, rfl⟩)
  exact fun h => P.not_dvd_index (h.trans (index_dvd_of_le hle))

/-- **An element of the subgroup attached to `s` and `P` factors through the Sylow subgroup.**
Every element of `TauCeti.pElementaryOfSylow s P` is a power of `s` times an element of the image
of `P`, and the two factors commute. -/
theorem exists_mul_eq_of_mem_pElementaryOfSylow {x : G} (hx : x ∈ pElementaryOfSylow s P) :
    ∃ c ∈ zpowers s, ∃ y ∈ (P : Subgroup (centralizer ({s} : Set G))).map
      (centralizer ({s} : Set G)).subtype, Commute c y ∧ c * y = x := by
  set Q := (P : Subgroup (centralizer ({s} : Set G))).map (centralizer ({s} : Set G)).subtype
    with hQ
  have hcomm : ∀ c ∈ zpowers s, ∀ y ∈ Q, Commute c y :=
    fun c hc y hy => commute_of_mem_zpowers_of_mem_centralizer s hc (map_subtype_le _ (hQ ▸ hy))
  have hnorm : zpowers s ≤ normalizer (Q : Set G) :=
    le_trans (fun c hc => mem_centralizer_iff.2 fun y hy => (hcomm c hc y hy).symm.eq)
      (centralizer_le_normalizer _)
  rw [pElementaryOfSylow, ← hQ, ← SetLike.mem_coe,
    coe_mul_of_left_le_normalizer_right _ _ hnorm] at hx
  obtain ⟨c, hc, y, hy, hcy⟩ := hx
  exact ⟨c, hc, y, hy, hcomm c hc y hy, hcy⟩

/-- **The `p`-part of an element of `TauCeti.pElementaryOfSylow s P` lies in its Sylow factor.**
The factorisation of `TauCeti.exists_mul_eq_of_mem_pElementaryOfSylow` splits the element into a
factor of order prime to `p` and a `p`-element, so it is *the* factorisation of
`TauCeti.eq_pPart`. -/
theorem pPart_mem_map_sylow_of_mem_pElementaryOfSylow [Fact p.Prime] (hs : ¬ p ∣ orderOf s) {x : G}
    (hx : x ∈ pElementaryOfSylow s P) :
    pPart p x ∈ (P : Subgroup (centralizer ({s} : Set G))).map
      (centralizer ({s} : Set G)).subtype := by
  obtain ⟨c, hc, y, hy, hcomm, rfl⟩ := exists_mul_eq_of_mem_pElementaryOfSylow s P hx
  obtain ⟨n, hn⟩ := (IsPGroup.iff_orderOf (p := p)).1 (P.2.map _) ⟨y, hy⟩
  rw [← eq_pPart Fact.out hcomm rfl
    (fun hd => hs (hd.trans (orderOf_dvd_of_mem_zpowers hc))) (k := n) (by simpa using hn)]
  exact hy

/-- **The `p`-free part of an element of `TauCeti.pElementaryOfSylow s P` lies in its cyclic
factor `⟨s⟩`.** This is the other half of the factorisation
`TauCeti.exists_mul_eq_of_mem_pElementaryOfSylow`, read through `TauCeti.eq_pFreePart`. -/
theorem pFreePart_mem_zpowers_of_mem_pElementaryOfSylow [Fact p.Prime] (hs : ¬ p ∣ orderOf s)
    {x : G} (hx : x ∈ pElementaryOfSylow s P) : pFreePart p x ∈ zpowers s := by
  obtain ⟨c, hc, y, hy, hcomm, rfl⟩ := exists_mul_eq_of_mem_pElementaryOfSylow s P hx
  obtain ⟨n, hn⟩ := (IsPGroup.iff_orderOf (p := p)).1 (P.2.map _) ⟨y, hy⟩
  rw [← eq_pFreePart Fact.out hcomm rfl
    (fun hd => hs (hd.trans (orderOf_dvd_of_mem_zpowers hc))) (k := n) (by simpa using hn)]
  exact hc

/-- **The `p`-free part is multiplicative on `TauCeti.pElementaryOfSylow s P`.** The cyclic
factor is central in the subgroup, so the product of two elements factors as the product of their
`p`-free parts times the product of their `p`-parts, and that is again a commuting factorisation
of the kind `TauCeti.eq_pFreePart` recognises. -/
theorem pFreePart_mul_of_mem_pElementaryOfSylow [Fact p.Prime] (hs : ¬ p ∣ orderOf s) {x y : G}
    (hx : x ∈ pElementaryOfSylow s P) (hy : y ∈ pElementaryOfSylow s P) :
    pFreePart p (x * y) = pFreePart p x * pFreePart p y := by
  have hfx := pFreePart_mem_zpowers_of_mem_pElementaryOfSylow s P hs hx
  have hfy := pFreePart_mem_zpowers_of_mem_pElementaryOfSylow s P hs hy
  have hpx := pPart_mem_map_sylow_of_mem_pElementaryOfSylow s P hs hx
  have hpy := pPart_mem_map_sylow_of_mem_pElementaryOfSylow s P hs hy
  obtain ⟨n, hn⟩ := (IsPGroup.iff_orderOf (p := p)).1 (P.2.map _) ⟨_, mul_mem hpx hpy⟩
  refine (eq_pFreePart Fact.out
    (commute_of_mem_zpowers_of_mem_centralizer s (mul_mem hfx hfy)
      (map_subtype_le _ (mul_mem hpx hpy))) ?_
    (fun hd => hs (hd.trans (orderOf_dvd_of_mem_zpowers (mul_mem hfx hfy)))) (k := n)
    (by simpa using hn)).symm
  calc pFreePart p x * pFreePart p y * (pPart p x * pPart p y)
      = pFreePart p x * (pFreePart p y * pPart p x) * pPart p y := by group
    _ = pFreePart p x * (pPart p x * pFreePart p y) * pPart p y := by
        rw [(commute_of_mem_zpowers_of_mem_centralizer s hfy (map_subtype_le _ hpx)).eq]
    _ = pFreePart p x * pPart p x * (pFreePart p y * pPart p y) := by group
    _ = x * y := by rw [pFreePart_mul_pPart, pFreePart_mul_pPart]

/-- **The `p`-free part as a homomorphism** from `TauCeti.pElementaryOfSylow s P` onto its cyclic
factor `⟨s⟩`. It is the projection of the direct product `⟨s⟩ × P` onto its first factor, the one
along which class functions of `⟨s⟩` are pulled back to the `p`-elementary subgroup. -/
noncomputable def pFreePartHom [Fact p.Prime] (hs : ¬ p ∣ orderOf s) :
    ↥(pElementaryOfSylow s P) →* ↥(zpowers s) where
  toFun x := ⟨pFreePart p (x : G), pFreePart_mem_zpowers_of_mem_pElementaryOfSylow s P hs x.2⟩
  map_one' := Subtype.ext (by simp [pFreePart_one])
  map_mul' x y := Subtype.ext (pFreePart_mul_of_mem_pElementaryOfSylow s P hs x.2 y.2)

@[simp]
theorem coe_pFreePartHom_apply [Fact p.Prime] (hs : ¬ p ∣ orderOf s)
    (x : ↥(pElementaryOfSylow s P)) : (pFreePartHom s P hs x : G) = pFreePart p (x : G) :=
  (rfl)

/-- The `p`-free-part projection is the identity on the cyclic factor. -/
@[simp]
theorem pFreePartHom_inclusion_apply [Fact p.Prime] (hs : ¬ p ∣ orderOf s)
    (c : ↥(zpowers s)) :
    pFreePartHom s P hs (Subgroup.inclusion (zpowers_le_pElementaryOfSylow s P) c) = c := by
  apply Subtype.ext
  exact (eq_pFreePart Fact.out (Commute.one_right (c : G)) (mul_one (c : G))
    (fun h => hs (h.trans (orderOf_dvd_of_mem_zpowers c.2))) (k := 0) (by simp)).symm

/-- The `p`-free-part projection maps onto the cyclic factor. -/
theorem pFreePartHom_surjective [Fact p.Prime] (hs : ¬ p ∣ orderOf s) :
    Function.Surjective (pFreePartHom s P hs) := fun c =>
  ⟨Subgroup.inclusion (zpowers_le_pElementaryOfSylow s P) c,
    pFreePartHom_inclusion_apply s P hs c⟩

end OfSylow

/-! ### Finite-order elements

Every finite-order element lies in the `p`-elementary subgroup built from its `p`-free part.
-/

/-- For every prime `p` and every finite-order element `x`, some Sylow `p`-subgroup of the
centraliser of the `p`-free part of `x` produces, by
`TauCeti.pElementaryOfSylow`, a subgroup containing `x`. That subgroup is `p`-elementary by
`TauCeti.isPElementary_pElementaryOfSylow`; when the Sylow subgroup has finite index in the
centraliser, which is not asserted here, `TauCeti.not_dvd_relIndex_pElementaryOfSylow` further
gives the subgroup index prime to `p` there. -/
theorem exists_mem_pElementaryOfSylow [Fact p.Prime] (x : G) (hx : orderOf x ≠ 0) :
    ∃ P : Sylow p (centralizer ({pFreePart p x} : Set G)),
      x ∈ pElementaryOfSylow (pFreePart p x) P := by
  have hu : pPart p x ∈ centralizer ({pFreePart p x} : Set G) :=
    mem_centralizer_singleton_iff.2 (commute_pFreePart_pPart p x).symm.eq
  have hQ : IsPGroup p (zpowers (⟨pPart p x, hu⟩ :
      centralizer ({pFreePart p x} : Set G))) := by
    refine IsPGroup.of_card_dvd_pow (n := (orderOf x).factorization p) ?_
    rw [Nat.card_zpowers, orderOf_mk, orderOf_pPart Fact.out hx]
  obtain ⟨P, hP⟩ := hQ.exists_le_sylow
  refine ⟨P, ?_⟩
  have hmem : pFreePart p x * pPart p x ∈ pElementaryOfSylow (pFreePart p x) P :=
    mul_mem (self_mem_pElementaryOfSylow _ _)
      (map_sylow_le_pElementaryOfSylow _ _ ⟨_, hP (mem_zpowers _), rfl⟩)
  rwa [pFreePart_mul_pPart] at hmem


end TauCeti
