/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib.GroupTheory.Nilpotent
public import Mathlib.GroupTheory.PGroup

/-!
# The lower `p`-central series of a subgroup

For a subgroup `S` of a group `G` and a natural number `p`, the *lower `p`-central series* of `S`,
computed in `G`, is the descending chain

* `λ₀ = S`,
* `λₙ₊₁ = ⟨x ^ p | x ∈ λₙ⟩ ⊔ ⁅λₙ, S⁆`.

Each factor `λₙ ⧸ λₙ₊₁` is central in `S ⧸ λₙ₊₁` and killed by `p`, so for a prime `p` the factors
are elementary abelian `p`-groups. The series refines Mathlib's `Subgroup.lowerCentralSeries` by
the `p`-th powers and is defined in the same relative way, with the series of `G` itself being the
case `S = ⊤`. Its purpose is to filter a finite `p`-group in finitely many steps by subgroups
that are normal in every group in which the `p`-group is normal, with elementary abelian factors:
this is the reduction that passes from embedding problems with elementary abelian kernel to
embedding problems with `p`-group kernel, and it is the abstract shadow of the lower `p`-series of
a pro-`p` group.

## Main results

* `Subgroup.pLowerCentralSeries_succ_le_iff`: the successor term is the least subgroup containing
  the `p`-th powers of the current term and its commutators with `S`.
* `Subgroup.pLowerCentralSeries_map`: the series is natural for group homomorphisms.
* `Subgroup.pLowerCentralSeries_mono`: the series is monotone in the subgroup.
* `Subgroup.normalizer_le_normalizer_pLowerCentralSeries`: whatever normalises `S` normalises every
  term; in particular the terms are normal when `S` is, and characteristic when `S` is.
* `IsPGroup.exists_pLowerCentralSeries_eq_bot`: the series of a finite `p`-subgroup reaches `⊥`.
* `Subgroup.exists_pLowerCentral_filtration_of_isPGroup`: the packaged filtration of a finite
  normal `p`-subgroup by normal subgroups with elementary abelian factors.

## References

* J. D. Dixon, M. P. F. du Sautoy, A. Mann, D. Segal, *Analytic pro-p groups*, §1.2, where the
  series is written `Pᵢ(G)`.
* L. Ribes, P. Zalesskii, *Profinite Groups*, §2.8.
-/

public section

open scoped commutatorElement

namespace Subgroup

variable {G : Type*} [Group G]

/-- The lower `p`-central series of a subgroup `S` of `G`, computed in the ambient group `G`:
`λ₀ = S`, and `λₙ₊₁` is generated by the `p`-th powers of the elements of `λₙ` together with the
commutators `⁅λₙ, S⁆`. The lower `p`-central series of `G` itself is the case `S = ⊤`. -/
def pLowerCentralSeries (p : ℕ) (S : Subgroup G) : ℕ → Subgroup G
  | 0 => S
  | n + 1 =>
    closure ((fun x : G ↦ x ^ p) '' (pLowerCentralSeries p S n : Set G)) ⊔
      ⁅pLowerCentralSeries p S n, S⁆

variable (p : ℕ) (S : Subgroup G)

@[simp]
theorem pLowerCentralSeries_zero : S.pLowerCentralSeries p 0 = S := (rfl)

/-- The recursion defining the successor term of the lower `p`-central series. -/
theorem pLowerCentralSeries_succ (n : ℕ) :
    S.pLowerCentralSeries p (n + 1) =
      closure ((fun x : G ↦ x ^ p) '' (S.pLowerCentralSeries p n : Set G)) ⊔
        ⁅S.pLowerCentralSeries p n, S⁆ := (rfl)

/-- The `p`-th power of an element of `λₙ` lies in `λₙ₊₁`. -/
theorem pow_mem_pLowerCentralSeries_succ {n : ℕ} {x : G} (hx : x ∈ S.pLowerCentralSeries p n) :
    x ^ p ∈ S.pLowerCentralSeries p (n + 1) :=
  mem_sup_left (subset_closure ⟨x, hx, rfl⟩)

/-- The commutator of an element of `λₙ` with an element of `S` lies in `λₙ₊₁`. -/
theorem commutator_mem_pLowerCentralSeries_succ {n : ℕ} {x y : G}
    (hx : x ∈ S.pLowerCentralSeries p n) (hy : y ∈ S) :
    ⁅x, y⁆ ∈ S.pLowerCentralSeries p (n + 1) :=
  mem_sup_right (commutator_mem_commutator hx hy)

variable {p S} in
/-- The successor term `λₙ₊₁` is the least subgroup containing the `p`-th powers of the elements
of `λₙ` and the commutators of `λₙ` with `S`. -/
theorem pLowerCentralSeries_succ_le_iff {n : ℕ} {H : Subgroup G} :
    S.pLowerCentralSeries p (n + 1) ≤ H ↔
      (∀ x ∈ S.pLowerCentralSeries p n, x ^ p ∈ H) ∧
        ∀ x ∈ S.pLowerCentralSeries p n, ∀ y ∈ S, ⁅x, y⁆ ∈ H := by
  simp only [pLowerCentralSeries_succ, sup_le_iff, closure_le, commutator_le, Set.subset_def,
    Set.forall_mem_image, SetLike.mem_coe]

/-- The lower `p`-central series is monotone in the subgroup: `S ≤ T` gives `λₙ(S) ≤ λₙ(T)`. -/
theorem pLowerCentralSeries_mono (n : ℕ) :
    Monotone fun S : Subgroup G ↦ S.pLowerCentralSeries p n := by
  induction n with
  | zero => exact fun _ _ h ↦ h
  | succ n ih =>
    intro S T h
    exact sup_le_sup (closure_mono (Set.image_mono (ih h))) (commutator_mono (ih h) h)

/-- The lower `p`-central series is natural: a homomorphism carries the series of `S` onto the
series of the image of `S`. -/
@[simp]
theorem pLowerCentralSeries_map {G' : Type*} [Group G'] (f : G →* G') (n : ℕ) :
    (S.pLowerCentralSeries p n).map f = (S.map f).pLowerCentralSeries p n := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pLowerCentralSeries_succ, pLowerCentralSeries_succ, map_sup, MonoidHom.map_closure,
      map_commutator, ← ih, coe_map, Set.image_image, Set.image_image]
    simp only [map_pow]

/-- An element normalising `S` normalises every term of the lower `p`-central series of `S`. -/
theorem normalizer_le_normalizer_pLowerCentralSeries (n : ℕ) :
    normalizer (S : Set G) ≤ normalizer (S.pLowerCentralSeries p n : Set G) := by
  intro g hg
  rw [mem_normalizer_iff_map_conj_eq] at hg ⊢
  rw [pLowerCentralSeries_map, hg]

/-- `S` normalises every term of its own lower `p`-central series. -/
theorem self_le_normalizer_pLowerCentralSeries (n : ℕ) :
    S ≤ normalizer (S.pLowerCentralSeries p n : Set G) :=
  le_normalizer.trans (S.normalizer_le_normalizer_pLowerCentralSeries p n)

/-- The lower `p`-central series is descending: `λₙ₊₁ ≤ λₙ`. -/
theorem pLowerCentralSeries_succ_le (n : ℕ) :
    S.pLowerCentralSeries p (n + 1) ≤ S.pLowerCentralSeries p n :=
  sup_le ((closure_le _).2 <| by rintro _ ⟨x, hx, rfl⟩; exact pow_mem hx p)
    (le_normalizer_iff_commutator_le_left.1 (S.self_le_normalizer_pLowerCentralSeries p n))

/-- The lower `p`-central series is antitone in the index. -/
theorem pLowerCentralSeries_antitone : Antitone (S.pLowerCentralSeries p) :=
  antitone_nat_of_succ_le (S.pLowerCentralSeries_succ_le p)

/-- Every term of the lower `p`-central series of `S` is contained in `S`. -/
theorem pLowerCentralSeries_le (n : ℕ) : S.pLowerCentralSeries p n ≤ S := by
  simpa using S.pLowerCentralSeries_antitone p (Nat.zero_le n)

/-- Consecutive factors of the lower `p`-central series are abelian: `⁅λₙ, λₙ⁆ ≤ λₙ₊₁`. -/
theorem commutator_pLowerCentralSeries_le_succ (n : ℕ) :
    ⁅S.pLowerCentralSeries p n, S.pLowerCentralSeries p n⁆ ≤ S.pLowerCentralSeries p (n + 1) :=
  (commutator_mono le_rfl (S.pLowerCentralSeries_le p n)).trans le_sup_right

/-- The terms of the lower `p`-central series of a normal subgroup are normal. -/
instance pLowerCentralSeries_normal [S.Normal] (n : ℕ) : (S.pLowerCentralSeries p n).Normal := by
  have h := S.normalizer_le_normalizer_pLowerCentralSeries p n
  rw [normalizer_eq_top] at h
  exact normalizer_eq_top_iff.1 (top_le_iff.1 h)

/-- In the quotient by `λₙ₊₁`, the class of an element of `λₙ` is killed by `p`. -/
theorem mk_pow_eq_one_of_mem_pLowerCentralSeries [S.Normal] {n : ℕ} {x : G}
    (hx : x ∈ S.pLowerCentralSeries p n) : (x : G ⧸ S.pLowerCentralSeries p (n + 1)) ^ p = 1 := by
  rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
  exact S.pow_mem_pLowerCentralSeries_succ p hx

/-- In the quotient by `λₙ₊₁`, the classes of two elements of `λₙ` commute. -/
theorem commute_mk_of_mem_pLowerCentralSeries [S.Normal] {n : ℕ} {x y : G}
    (hx : x ∈ S.pLowerCentralSeries p n) (hy : y ∈ S.pLowerCentralSeries p n) :
    Commute (x : G ⧸ S.pLowerCentralSeries p (n + 1)) y := by
  have hxy := map_commutatorElement (QuotientGroup.mk' (S.pLowerCentralSeries p (n + 1))) x y
  simp only [QuotientGroup.mk'_apply] at hxy
  rw [← commutatorElement_eq_one_iff_commute, ← hxy, QuotientGroup.eq_one_iff]
  exact S.commutator_mem_pLowerCentralSeries_succ p hx (S.pLowerCentralSeries_le p n hy)

/-- The terms of the lower `p`-central series of a characteristic subgroup are characteristic. -/
instance pLowerCentralSeries_characteristic [S.Characteristic] (n : ℕ) :
    (S.pLowerCentralSeries p n).Characteristic :=
  characteristic_iff_map_eq.2 fun φ ↦ by
    rw [pLowerCentralSeries_map, characteristic_iff_map_eq.1 ‹S.Characteristic› φ]

/-- The lower `p`-central series refines the lower central series. -/
theorem lowerCentralSeries_le_pLowerCentralSeries (n : ℕ) :
    S.lowerCentralSeries n ≤ S.pLowerCentralSeries p n := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [lowerCentralSeries_succ, pLowerCentralSeries_succ]
    exact (commutator_mono ih le_rfl).trans le_sup_right

/-- The first term of the lower `p`-central series of `G` is generated by the `p`-th powers and
the commutators. -/
theorem top_pLowerCentralSeries_one :
    (⊤ : Subgroup G).pLowerCentralSeries p 1 =
      closure (Set.range fun g : G ↦ g ^ p) ⊔ _root_.commutator G := by
  rw [pLowerCentralSeries_succ, pLowerCentralSeries_zero, _root_.commutator_def, coe_top,
    Set.image_univ]

/-- **The lower `p`-central series of a commutative group** is the chain of subgroups of
`p ^ n`-th powers: the commutators vanish, so `λₙ₊₁` is generated by the `p`-th powers of `λₙ`. -/
theorem top_pLowerCentralSeries_eq_range_powMonoidHom {G : Type*} [CommGroup G] (p n : ℕ) :
    (⊤ : Subgroup G).pLowerCentralSeries p n = (powMonoidHom (p ^ n) : G →* G).range := by
  induction n with
  | zero =>
    rw [pLowerCentralSeries_zero, eq_comm, MonoidHom.range_eq_top]
    exact fun x ↦ ⟨x, pow_one x⟩
  | succ n ih =>
    have hcomm : ⁅(powMonoidHom (p ^ n) : G →* G).range, (⊤ : Subgroup G)⁆ = ⊥ :=
      commutator_eq_bot_iff_le_centralizer.mpr fun x _ ↦
        mem_centralizer_iff.mpr fun y _ ↦ mul_comm y x
    have himage : (fun x : G ↦ x ^ p) '' ((powMonoidHom (p ^ n) : G →* G).range : Set G) =
        ((powMonoidHom (p ^ (n + 1)) : G →* G).range : Set G) := by
      ext x
      simp only [Set.mem_image, SetLike.mem_coe, MonoidHom.mem_range, powMonoidHom_apply,
        exists_exists_eq_and, pow_succ, pow_mul]
    rw [pLowerCentralSeries_succ, ih, hcomm, sup_bot_eq, himage, closure_eq]

end Subgroup

namespace IsPGroup

universe u

variable {p : ℕ} [hp : Fact p.Prime]

/-- The lower `p`-central series of every finite `p`-group `G` of order `m` reaches `⊥`. -/
private theorem exists_pLowerCentralSeries_top_eq_bot_aux (m : ℕ) :
    ∀ (G : Type u) [Group G] [Finite G], Nat.card G = m → IsPGroup p G →
      ∃ n, (⊤ : Subgroup G).pLowerCentralSeries p n = ⊥ := by
  induction m using Nat.strong_induction_on with
  | _ m ih =>
  intro G _ _ hm hG
  rcases subsingleton_or_nontrivial G with _ | _
  · exact ⟨0, (Subgroup.eq_bot_iff_forall _).2 fun x _ ↦ Subsingleton.elim x 1⟩
  -- A nontrivial finite `p`-group has a central element `z` of order `p`.
  have := hG.center_nontrivial
  obtain ⟨z, hz⟩ : ∃ z : Subgroup.center G, orderOf z = p := by
    refine exists_prime_orderOf_dvd_card' p ?_
    rcases (hG.to_subgroup (Subgroup.center G)).card_eq_or_dvd with h | h
    · exact absurd h Finite.one_lt_card.ne'
    · exact h
  set Z : Subgroup G := Subgroup.zpowers (z : G) with hZ
  have hZc : Z ≤ Subgroup.center G := Subgroup.zpowers_le.2 z.2
  have : Z.Normal := Subgroup.normal_of_le_center hZc
  have hz1 : (z : G) ≠ 1 := by
    intro h
    have := Subgroup.orderOf_coe z
    rw [h, orderOf_one, hz] at this
    exact hp.out.one_lt.ne this
  -- The quotient `G ⧸ Z` is a smaller `p`-group, so its series vanishes at some stage `n`.
  have hlt : Nat.card (G ⧸ Z) < m := by
    rw [← hm, ← Z.index_eq_card, ← Z.card_mul_index]
    exact (Nat.lt_mul_iff_one_lt_left (Nat.pos_of_ne_zero Z.index_ne_zero_of_finite)).2
      (Z.one_lt_card_iff_ne_bot.2 (Subgroup.zpowers_eq_bot.not.2 hz1))
  obtain ⟨n, hn⟩ := ih _ hlt (G ⧸ Z) rfl (hG.to_quotient Z)
  -- Hence `λₙ ≤ Z`, and `Z` is central of exponent `p`, so `λₙ₊₁ = ⊥`.
  have hle : (⊤ : Subgroup G).pLowerCentralSeries p n ≤ Z := by
    rw [← QuotientGroup.ker_mk' Z, ← Subgroup.map_eq_bot_iff, Subgroup.pLowerCentralSeries_map,
      Subgroup.map_top_of_surjective _ (QuotientGroup.mk'_surjective Z), hn]
  refine ⟨n + 1, le_bot_iff.1 (Subgroup.pLowerCentralSeries_succ_le_iff.2 ⟨?_, ?_⟩)⟩
  · intro x hx
    rw [Subgroup.mem_bot, ← orderOf_dvd_iff_pow_eq_one]
    exact (orderOf_dvd_of_mem_zpowers (hle hx)).trans (by rw [Subgroup.orderOf_coe, hz])
  · intro x hx y _
    rw [Subgroup.mem_bot, commutatorElement_eq_one_iff_commute]
    exact (Subgroup.mem_center_iff.1 (hZc (hle hx)) y).symm

variable {G : Type*} [Group G]

/-- **The lower `p`-central series of a finite `p`-group reaches the trivial subgroup.** For a
finite `p`-subgroup `S` of any group `G`, some term of `S.pLowerCentralSeries p` is `⊥`. -/
theorem exists_pLowerCentralSeries_eq_bot {S : Subgroup G} [Finite S] (hS : IsPGroup p S) :
    ∃ n, S.pLowerCentralSeries p n = ⊥ := by
  obtain ⟨n, hn⟩ := exists_pLowerCentralSeries_top_eq_bot_aux _ S rfl hS
  refine ⟨n, ?_⟩
  have h := congrArg (Subgroup.map S.subtype) hn
  rwa [Subgroup.pLowerCentralSeries_map, ← MonoidHom.range_eq_map, S.range_subtype,
    Subgroup.map_bot] at h

end IsPGroup

namespace Subgroup

/-- **The lower `p`-central filtration of a finite normal `p`-subgroup.** A finite normal
`p`-subgroup `N` of a group `E` carries a finite descending chain of subgroups of `E`, starting
at `N` and ending at `⊥`, each normal in `E`, along which `p`-th powers and commutators with `N`
drop one step. So every factor is an elementary abelian `p`-group on which `E` acts by
conjugation. The chain is the lower `p`-central series `Subgroup.pLowerCentralSeries p N`. -/
theorem exists_pLowerCentral_filtration_of_isPGroup {p : ℕ} [Fact p.Prime] {E : Type*} [Group E]
    (N : Subgroup E) [N.Normal] [Finite N] (hN : IsPGroup p N) :
    ∃ (m : ℕ) (lam : ℕ → Subgroup E), lam 0 = N ∧ lam m = ⊥ ∧
      (∀ k, lam (k + 1) ≤ lam k) ∧ (∀ k, (lam k).Normal) ∧
      (∀ k, ∀ x ∈ lam k, x ^ p ∈ lam (k + 1)) ∧
      ∀ k, ∀ x ∈ lam k, ∀ y ∈ N, ⁅x, y⁆ ∈ lam (k + 1) :=
  let ⟨m, hm⟩ := hN.exists_pLowerCentralSeries_eq_bot
  ⟨m, N.pLowerCentralSeries p, N.pLowerCentralSeries_zero p, hm, N.pLowerCentralSeries_succ_le p,
    fun _ ↦ inferInstance, fun _ _ hx ↦ N.pow_mem_pLowerCentralSeries_succ p hx,
    fun _ _ hx _ hy ↦ N.commutator_mem_pLowerCentralSeries_succ p hx hy⟩

end Subgroup
