/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Rank
public import Mathlib.GroupTheory.Schreier

/-!
# Predecessor transversals and the sharp Schreier index formula

Schreier's lemma, `Subgroup.closure_mul_image_eq` in Mathlib, says that a subgroup `H` of a
group `G = ⟨S⟩` is generated by the *Schreier generators* `r * s * (r * s)‾⁻¹`, where `r` runs
over a right transversal `R` of `H` containing `1`, `s` runs over `S`, and `g ↦ g‾` is the map
`Subgroup.IsComplement.toRightFun` sending an element to its representative in `R`. Counting
these generators gives `[G : H] * |S|` of them (`Subgroup.exists_finset_card_le_mul`). This file
sharpens the count to `1 + [G : H] * (|S| - 1)`, the classical Schreier index formula.

The saving comes from the choice of transversal. A **predecessor transversal** is a right
transversal `R` of `H` that contains `1` and satisfies the *predecessor condition*: every
`r ≠ 1` in `R` is `r' * s` for some `r' ∈ R` and `s ∈ S`. Along such a transversal the Schreier
generators at the pairs `(r', s)` with `r' * s ∈ R` are trivial, and there are at least `|R| - 1`
such pairs, one for each `r ≠ 1`. Every subgroup of finite index has a finite predecessor
transversal with respect to every generating set.

The predecessor condition is a one-step condition: it does not ask that every element of `R` be
reached from `1` by a chain of such steps, so it allows cycles: if `S` contains both `s` and
`s⁻¹`, then `r = r' * s` and `r' = r * s⁻¹` satisfy it with neither `r` nor `r'` reached from
`1`. It is therefore weaker than a *Schreier transversal* in the sense of the references below, a
prefix-closed set of reduced words in `S ∪ S⁻¹`, and it only uses letters from `S`, not from
`S⁻¹`; the name records the condition that is actually imposed. The one-step condition is all
that the index formula needs. The transversal built in
`Subgroup.exists_finset_isPredecessorTransversal` starts from `{1}` and adds elements of the form
`r * s` with `r` already present, so it is reached from `1` by chains of steps, but the
predicate does not record this.

## Main results

* `Subgroup.IsPredecessorTransversal`: a right transversal containing `1` in which every other
  element is an element of the transversal times an element of `S`.
* `Subgroup.exists_finset_isPredecessorTransversal`: a finite-index subgroup has a finite
  predecessor transversal with respect to every generating set.
* `Subgroup.exists_finset_card_le_one_add_index_mul`: **Schreier's index formula**: a subgroup of
  index `n` in a group generated by `d` elements is generated by `1 + n * (d - 1)` elements.
* `Subgroup.rank_le_one_add_index_mul_rank_sub_one`: the same for `Group.rank`, sharpening
  Mathlib's `Subgroup.rank_le_index_mul_rank`.

## References

* D. L. Johnson, *Presentations of Groups*, 2nd ed., Cambridge University Press, 1997,
  Chapter 9.
* W. Magnus, A. Karrass and D. Solitar, *Combinatorial Group Theory*, Section 2.3.
-/

public section

namespace TauCeti

open Subgroup

variable {G : Type*} [Group G]

/-- The representative of an element of a right transversal is that element. -/
@[simp]
theorem _root_.Subgroup.IsComplement.coe_toRightFun_of_mem {H : Subgroup G} {R : Set G}
    (hR : IsComplement (H : Set G) R) {r : G} (hr : r ∈ R) : (hR.toRightFun r : G) = r := by
  have h := (isComplement_iff_existsUnique_mul_inv_mem.mp hR r).unique
    (hR.mul_inv_toRightFun_mem r) (y₂ := ⟨r, hr⟩) (by simp)
  exact congrArg Subtype.val h

/-- A **predecessor transversal** of a subgroup `H` with respect to a set `S`: a right
transversal `R` of `H`, so that `H * R = G` with unique factorization, which contains `1` and
satisfies the predecessor condition that every `r ≠ 1` in `R` is `r' * s` for some `r' ∈ R` and
`s ∈ S`. This is a one-step condition: it does not require `r` to be reached from `1` by a chain
of such steps, so it is weaker than a Schreier transversal in the usual prefix-closed sense, and
it is all that the index formula uses. When `S` generates `G`, the Schreier generators of `H` at
the pairs `(r', s)` with `r' * s ∈ R` are trivial, which is what sharpens Schreier's lemma to the
index formula `Subgroup.exists_finset_card_le_one_add_index_mul`. -/
structure _root_.Subgroup.IsPredecessorTransversal (H : Subgroup G) (S R : Set G) : Prop where
  /-- `R` is a right transversal of `H`. -/
  isComplement : IsComplement (H : Set G) R
  /-- `R` contains the identity. -/
  one_mem : (1 : G) ∈ R
  /-- Every element of `R` other than `1` is an element of `R` times an element of `S`. -/
  exists_mul_eq : ∀ r ∈ R, r ≠ 1 → ∃ r' ∈ R, ∃ s ∈ S, r' * s = r

section Existence

/-- A finite set of representatives of pairwise distinct right cosets of `H` containing `1` and
satisfying the predecessor condition: a predecessor transversal that may miss some cosets. The
existence proof enlarges such a set until no coset is missing. -/
private structure IsPartialPredecessorTransversal (H : Subgroup G) (S : Set G) (R : Finset G) :
    Prop where
  one_mem : (1 : G) ∈ R
  exists_mul_eq : ∀ r ∈ R, r ≠ 1 → ∃ r' ∈ R, ∃ s ∈ S, r' * s = r
  eq_of_mul_inv_mem : ∀ r ∈ R, ∀ r' ∈ R, r * r'⁻¹ ∈ H → r = r'

variable {H : Subgroup G} {S : Set G}

/-- Representatives of pairwise distinct cosets are at most as many as the cosets. -/
private theorem IsPartialPredecessorTransversal.card_le_index [H.FiniteIndex] {R : Finset G}
    (hR : IsPartialPredecessorTransversal H S R) : R.card ≤ H.index := by
  rw [← Nat.card_eq_finsetCard, index_eq_card]
  refine Nat.card_le_card_of_injective (fun r : R ↦ (((r : G)⁻¹ : G) : G ⧸ H)) fun r r' h ↦ ?_
  rw [QuotientGroup.eq, inv_inv] at h
  exact Subtype.ext (hR.eq_of_mul_inv_mem r r.2 r' r'.2 h)

/-- If `S` generates `G` and some right coset of `H` is not represented by `R`, then some product
`r * s` with `r ∈ R` and `s ∈ S` represents a coset that `R` misses. -/
private theorem IsPartialPredecessorTransversal.exists_mul_mem_forall_mul_inv_notMem
    (hS : closure S = ⊤) {R : Finset G} (hR : IsPartialPredecessorTransversal H S R) {g : G}
    (hg : ∀ r ∈ R, g * r⁻¹ ∉ H) : ∃ r ∈ R, ∃ s ∈ S, ∀ r' ∈ R, r * s * r'⁻¹ ∉ H := by
  -- This is where finiteness is used: if every `r * s` stayed in a coset represented by `R`,
  -- right multiplication by each `s ∈ S` would permute the finitely many cosets represented by
  -- `R`, so those cosets would be stable under `S` and `S⁻¹`, hence under `G = ⟨S⟩`.
  by_contra hcon
  push Not at hcon
  -- Right multiplication by `s` induces an injective, hence bijective, self-map of the finite
  -- set of cosets represented by `R`; surjectivity is stability under `s⁻¹`.
  have hinv : ∀ s ∈ S, ∀ r' ∈ R, ∃ r ∈ R, r * s * r'⁻¹ ∈ H := by
    intro s hs
    choose σ hσR hσ using fun r : R ↦ hcon r r.2 s hs
    have hτ : Function.Injective fun r : R ↦ (⟨σ r, hσR r⟩ : R) := by
      intro r₁ r₂ h
      have h' : σ r₁ = σ r₂ := congrArg Subtype.val h
      refine Subtype.ext (hR.eq_of_mul_inv_mem r₁ r₁.2 r₂ r₂.2 ?_)
      simpa [h', mul_assoc] using H.mul_mem (hσ r₁) (H.inv_mem (hσ r₂))
    intro r' hr'
    obtain ⟨r, hr⟩ := Finite.injective_iff_surjective.mp hτ ⟨r', hr'⟩
    have hr' : σ r = r' := congrArg Subtype.val hr
    exact ⟨r, r.2, hr' ▸ hσ r⟩
  -- Every element of `G = ⟨S⟩` lies in a coset represented by `R`.
  have key : ∀ x ∈ closure S, ∃ r ∈ R, x * r⁻¹ ∈ H := by
    intro x hx
    induction hx using closure_induction_right with
    | one => exact ⟨1, hR.one_mem, by simp⟩
    | mul_right x _ s hs ih =>
      obtain ⟨r, hr, hxr⟩ := ih
      obtain ⟨r', hr', hrs⟩ := hcon r hr s hs
      exact ⟨r', hr', by simpa [mul_assoc] using H.mul_mem hxr hrs⟩
    | mul_inv_cancel x _ s hs ih =>
      obtain ⟨r', hr', hxr'⟩ := ih
      obtain ⟨r, hr, hrs⟩ := hinv s hs r' hr'
      exact ⟨r, hr, by simpa [mul_assoc] using H.mul_mem hxr' (H.inv_mem hrs)⟩
  obtain ⟨r, hr, hgr⟩ := key g (hS ▸ mem_top g)
  exact hg r hr hgr

/-- A partial predecessor transversal that misses a coset extends by one element. -/
private theorem IsPartialPredecessorTransversal.exists_insert [DecidableEq G] (hS : closure S = ⊤)
    {R : Finset G} (hR : IsPartialPredecessorTransversal H S R) {g : G}
    (hg : ∀ r ∈ R, g * r⁻¹ ∉ H) : ∃ x ∉ R, IsPartialPredecessorTransversal H S (insert x R) := by
  obtain ⟨r, hr, s, hs, hnew⟩ := hR.exists_mul_mem_forall_mul_inv_notMem hS hg
  have hnotMem : r * s ∉ R := fun h ↦ hnew _ h (by simp)
  refine ⟨r * s, hnotMem, Finset.mem_insert_of_mem hR.one_mem, fun x hx hx1 ↦ ?_, ?_⟩
  · rcases Finset.mem_insert.mp hx with rfl | hx
    · exact ⟨r, Finset.mem_insert_of_mem hr, s, hs, rfl⟩
    · obtain ⟨r', hr', s', hs', h⟩ := hR.exists_mul_eq x hx hx1
      exact ⟨r', Finset.mem_insert_of_mem hr', s', hs', h⟩
  · intro x hx y hy hxy
    rcases Finset.mem_insert.mp hx with rfl | hx <;> rcases Finset.mem_insert.mp hy with rfl | hy
    · rfl
    · exact (hnew y hy hxy).elim
    · refine (hnew x hx ?_).elim
      simpa using H.inv_mem hxy
    · exact hR.eq_of_mul_inv_mem x hx y hy hxy

/-- A partial predecessor transversal representing every coset is a predecessor transversal. -/
private theorem IsPartialPredecessorTransversal.isPredecessorTransversal {R : Finset G}
    (hR : IsPartialPredecessorTransversal H S R) (hcomp : ∀ g : G, ∃ r ∈ R, g * r⁻¹ ∈ H) :
    H.IsPredecessorTransversal S R where
  isComplement := by
    refine isComplement_iff_existsUnique_mul_inv_mem.mpr fun g ↦ ?_
    obtain ⟨r, hr, hgr⟩ := hcomp g
    refine ⟨⟨r, Finset.mem_coe.mpr hr⟩, hgr, fun t ht ↦ Subtype.ext ?_⟩
    exact hR.eq_of_mul_inv_mem t (Finset.mem_coe.mp t.2) r hr
      (by simpa [mul_assoc] using H.mul_mem (H.inv_mem ht) hgr)
  one_mem := Finset.mem_coe.mpr hR.one_mem
  exists_mul_eq r hr := hR.exists_mul_eq r (Finset.mem_coe.mp hr)

/-- **Existence of predecessor transversals.** A subgroup of finite index has a finite
predecessor transversal with respect to every generating set of the ambient group. -/
theorem _root_.Subgroup.exists_finset_isPredecessorTransversal (H : Subgroup G) [H.FiniteIndex]
    (hS : closure S = ⊤) : ∃ R : Finset G, H.IsPredecessorTransversal S R := by
  classical
  -- Enlarge a partial transversal one coset at a time; `m` bounds the number of missing cosets.
  suffices h : ∀ (m : ℕ) (R : Finset G), IsPartialPredecessorTransversal H S R →
      H.index ≤ R.card + m → ∃ R : Finset G, H.IsPredecessorTransversal S R from
    h H.index {1} ⟨Finset.mem_singleton_self 1,
      fun r hr hr1 ↦ (hr1 (Finset.mem_singleton.mp hr)).elim,
      fun r hr r' hr' _ ↦ (Finset.mem_singleton.mp hr).trans (Finset.mem_singleton.mp hr').symm⟩
      (by simp)
  intro m
  induction m with
  | zero =>
    intro R hR hle
    by_cases hcomp : ∀ g : G, ∃ r ∈ R, g * r⁻¹ ∈ H
    · exact ⟨R, hR.isPredecessorTransversal hcomp⟩
    · push Not at hcomp
      obtain ⟨g, hg⟩ := hcomp
      obtain ⟨x, hx, hR'⟩ := hR.exists_insert hS hg
      have := hR'.card_le_index
      rw [Finset.card_insert_of_notMem hx] at this
      omega
  | succ m ih =>
    intro R hR hle
    by_cases hcomp : ∀ g : G, ∃ r ∈ R, g * r⁻¹ ∈ H
    · exact ⟨R, hR.isPredecessorTransversal hcomp⟩
    · push Not at hcomp
      obtain ⟨g, hg⟩ := hcomp
      obtain ⟨x, hx, hR'⟩ := hR.exists_insert hS hg
      refine ih _ hR' ?_
      rw [Finset.card_insert_of_notMem hx]
      omega

end Existence

section IndexFormula

open scoped Pointwise

variable {H : Subgroup G}

/-- **Schreier's index formula.** If `H` has finite index `n` in a group generated by a finite set
`S` of `d` elements, then `H` is generated by at most `1 + n * (d - 1)` elements. This sharpens
Mathlib's `Subgroup.exists_finset_card_le_mul`, which gives `n * d`. -/
theorem _root_.Subgroup.exists_finset_card_le_one_add_index_mul (H : Subgroup G) [H.FiniteIndex]
    {S : Finset G} (hS : closure (S : Set G) = ⊤) :
    ∃ T : Finset H, T.card ≤ 1 + H.index * (S.card - 1) ∧ closure (T : Set H) = ⊤ := by
  classical
  -- Take the Schreier generators of `Subgroup.closure_mul_image_eq_top'` along a predecessor
  -- transversal `R`: at least `n - 1` of them at pairs `(r', s)` with `r' * s ∈ R` are trivial.
  obtain ⟨R, hR⟩ := H.exists_finset_isPredecessorTransversal hS
  have hRcard : R.card = H.index := by
    rw [← hR.isComplement.card_right, ← Nat.card_eq_finsetCard, Finset.coe_sort_coe]
  -- The Schreier generator attached to `g ∈ R * S`.
  let f : G → H := fun g ↦ ⟨g * (hR.isComplement.toRightFun g : G)⁻¹,
    hR.isComplement.mul_inv_toRightFun_mem g⟩
  refine ⟨((R * S) \ R).image f, ?_, ?_⟩
  · -- Count: `R * S` has at most `n * d` elements, and by the predecessor condition at least
    -- `n - 1` of them lie in `R`, namely every `r ≠ 1`.
    have hsub : R.erase 1 ⊆ R ∩ (R * S) := fun r hr ↦ by
      obtain ⟨hr1, hr⟩ := Finset.mem_erase.mp hr
      obtain ⟨r', hr', s, hs, h⟩ := hR.exists_mul_eq r (Finset.mem_coe.mpr hr) hr1
      exact Finset.mem_inter.mpr ⟨hr, Finset.mem_mul.mpr ⟨r', Finset.mem_coe.mp hr', s, hs, h⟩⟩
    have h₁ : (R * S).card ≤ R.card * S.card := Finset.card_mul_le
    have h₂ : R.card - 1 ≤ (R ∩ (R * S)).card := by
      rw [← Finset.card_erase_of_mem (Finset.mem_coe.mp hR.one_mem)]
      exact Finset.card_le_card hsub
    calc (((R * S) \ R).image f).card ≤ ((R * S) \ R).card := Finset.card_image_le
      _ = (R * S).card - (R ∩ (R * S)).card := Finset.card_sdiff
      _ ≤ 1 + H.index * (S.card - 1) := by
        rw [Nat.mul_sub_one, ← hRcard]
        omega
  · -- Generation: Schreier's lemma gives the generators at all of `R * S`, and the ones at
    -- `R * S ∩ R` are trivial.
    have hgen := closure_mul_image_eq_top' hR.isComplement hR.one_mem hS
    rw [eq_top_iff, ← hgen, closure_le]
    intro x hx
    obtain ⟨g, hg, hfg⟩ := Finset.mem_coe.mp hx |> Finset.mem_image.mp
    rw [← hfg]
    by_cases hgR : g ∈ R
    · have h1 : (⟨g * (hR.isComplement.toRightFun g : G)⁻¹,
          hR.isComplement.mul_inv_toRightFun_mem g⟩ : H) = 1 := Subtype.ext <| by
        simp [hR.isComplement.coe_toRightFun_of_mem (Finset.mem_coe.mpr hgR)]
      rw [h1]
      exact one_mem _
    · exact subset_closure (Finset.mem_coe.mpr
        (Finset.mem_image.mpr ⟨g, Finset.mem_sdiff.mpr ⟨hg, hgR⟩, rfl⟩))

/-- **Schreier's index formula for `Group.rank`:** `rank H ≤ 1 + [G : H] * (rank G - 1)` for a
finite-index subgroup `H` of a finitely generated group `G`. This sharpens Mathlib's
`Subgroup.rank_le_index_mul_rank`. -/
theorem _root_.Subgroup.rank_le_one_add_index_mul_rank_sub_one [Group.FG G] [H.FiniteIndex] :
    Group.rank H ≤ 1 + H.index * (Group.rank G - 1) := by
  obtain ⟨S, hS₀, hS⟩ := Group.rank_spec G
  obtain ⟨T, hT₀, hT⟩ := H.exists_finset_card_le_one_add_index_mul hS
  exact (Group.rank_le hT).trans (hS₀ ▸ hT₀)

end IndexFormula

end TauCeti
