/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Sylow

/-!
# Sylow subgroups of prime order

When a prime `p` divides the order of a finite group exactly once, its Sylow `p`-subgroups have
order `p`. This is the form in which Sylow's theorems are applied to groups such as `S₅`, whose
order `120` is divisible by `5` but not by `25`, and to their subgroups.

The file also records that `p` times the number of Sylow `p`-subgroups divides the order of the
group whenever `p` does. When `p ^ 2` does not divide the order, any two elements of order `p`
generate conjugate subgroups.

## Main results

* `Sylow.card_eq_of_dvd_of_not_sq_dvd`: a Sylow `p`-subgroup has order `p` when `p` divides the
  order of the group but `p ^ 2` does not.
* `Sylow.mul_card_sylow_dvd_card`: if `p` divides the order of the group, then so does `p` times
  the number of Sylow `p`-subgroups.
* `TauCeti.exists_mul_mul_inv_mem_zpowers_of_not_sq_dvd`: if `p ^ 2` does not divide the order of
  the group, some conjugate of an element of order `p` is a power of any other element of
  order `p`.
-/

public section

namespace Sylow

variable {G : Type*} [Group G] [Finite G] {p : ℕ} [hp : Fact p.Prime]

/-- A Sylow `p`-subgroup has order `p` when `p` divides the order of the group exactly once. -/
theorem card_eq_of_dvd_of_not_sq_dvd (P : Sylow p G) (hdvd : p ∣ Nat.card G)
    (hsq : ¬ p ^ 2 ∣ Nat.card G) : Nat.card P = p := by
  have hG : Nat.card G ≠ 0 := Nat.card_pos.ne'
  have h1 := (hp.out.dvd_iff_one_le_factorization hG).1 hdvd
  have h2 := mt (hp.out.pow_dvd_iff_le_factorization (k := 2) hG).2 hsq
  -- `p` divides `|G|` but `p ^ 2` does not, so `p` occurs exactly once in `|G|`.
  have hfac : (Nat.card G).factorization p = 1 := by omega
  rw [P.card_eq_multiplicity, hfac, pow_one]

/-- If a prime `p` divides the order of a finite group, then so does `p` times the number of
Sylow `p`-subgroups. -/
theorem mul_card_sylow_dvd_card (hdvd : p ∣ Nat.card G) :
    p * Nat.card (Sylow p G) ∣ Nat.card G := by
  obtain ⟨P⟩ : Nonempty (Sylow p G) := inferInstance
  have hG : Nat.card G ≠ 0 := Nat.card_pos.ne'
  have hfac := (hp.out.dvd_iff_one_le_factorization hG).1 hdvd
  have hP : p ∣ Nat.card P := by
    rw [P.card_eq_multiplicity]
    exact dvd_pow_self p (Nat.one_le_iff_ne_zero.1 hfac)
  have hN : p ∣ Nat.card (Subgroup.normalizer (P : Set G)) :=
    hP.trans (Subgroup.card_dvd_of_le Subgroup.le_normalizer)
  rw [P.card_eq_index_normalizer, ← (Subgroup.normalizer (P : Set G)).index_mul_card, mul_comm]
  exact Nat.mul_dvd_mul_left _ hN

end Sylow

namespace TauCeti

variable {G : Type*} [Group G] [Finite G] {p : ℕ} [hp : Fact p.Prime]

/-- If `p ^ 2` does not divide the order of a finite group, then the subgroups generated by two
elements of order `p` are Sylow `p`-subgroups, hence conjugate: some conjugate of `h` is a power
of `g`. -/
theorem exists_mul_mul_inv_mem_zpowers_of_not_sq_dvd (hsq : ¬ p ^ 2 ∣ Nat.card G) {g h : G}
    (hg : orderOf g = p) (hh : orderOf h = p) : ∃ y : G, y * h * y⁻¹ ∈ Subgroup.zpowers g := by
  obtain ⟨P⟩ : Nonempty (Sylow p G) := inferInstance
  have hcard : p ^ (Nat.card G).factorization p = p := by
    rw [← P.card_eq_multiplicity, P.card_eq_of_dvd_of_not_sq_dvd (hg ▸ orderOf_dvd_natCard g) hsq]
  let Pg := Sylow.ofCard (Subgroup.zpowers g) (by rw [Nat.card_zpowers, hcard, hg])
  let Ph := Sylow.ofCard (Subgroup.zpowers h) (by rw [Nat.card_zpowers, hcard, hh])
  obtain ⟨y, hy⟩ := MulAction.exists_smul_eq G Ph Pg
  refine ⟨y, ?_⟩
  have hmem : y * h * y⁻¹ ∈ ((y • Ph : Sylow p G) : Subgroup G) := by
    rw [Sylow.coe_subgroup_smul, ← MulAut.conj_apply]
    exact Subgroup.smul_mem_pointwise_smul _ _ _ (by
      simp only [Ph, Sylow.coe_ofCard]
      exact Subgroup.mem_zpowers h)
  rw [hy] at hmem
  simp only [Pg, Sylow.coe_ofCard] at hmem
  exact hmem

end TauCeti
