/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Ring.Action.Invariant
public import Mathlib.RingTheory.IntegralDomain
public import TauCeti.NumberTheory.LocalField.UnitFiltration.Basic
public import TauCeti.RingTheory.DiscreteValuationRing.Uniformizer
public import TauCeti.RingTheory.LocalRing.RamificationGroup

/-!
# The quotient embeddings of the ramification filtration

Let `L` be a nonarchimedean local field and let a group `G` act on `L` by ring automorphisms
preserving the ring of integers, so that both the ramification filtration
`G_i = TauCeti.IsLocalRing.ramificationGroup G 𝒪[L] i` and the unit filtration
`U(L,i) = TauCeti.unitFiltration L i` are defined. The motivating case is the Galois group
`L ≃ₐ[K] L` of a finite extension of local fields, for which
`TauCeti.integerRingIsInvariantSubring` supplies the invariance hypothesis.

Fixing a uniformizer `ϖ`, that is an irreducible element of `𝒪[L]`, this file compares the two
filtrations through the ratio `σ ϖ / ϖ`. An element of `G_i` moves `ϖ` by a factor lying in
`U(L,i)`, and the class of that factor modulo `U(L,i+1)`

* does not depend on the choice of `ϖ`,
* is multiplicative in `σ`, and
* is trivial on `G_{i+1}`,

so it defines `θ_i : G_i / G_{i+1} → U(L,i) / U(L,i+1)`. The map `θ_i` is injective as soon as
`𝒪[L]` is generated by the single element `ϖ` over a base ring whose scalars commute with the
action, for instance the integers of a subfield fixed by `G`: membership in `G_{i+1}` is then
decided at `ϖ` alone. That is the monogenic situation of a totally ramified extension. Without
that hypothesis the maps below are still defined, but are only homomorphisms.

At depth zero, composing with the reduction isomorphism `U(L,0) / U(L,1) ≃ 𝓀[L]ˣ`
gives the **tame character** `G_0 → 𝓀[L]ˣ`, which kills `G_1`; under the same monogenic
hypothesis the induced map on `G_0 / G_1` is injective, so the tame quotient is cyclic of order
dividing `q - 1`, where `q` is the cardinality of the residue field.

## Main definitions

* `TauCeti.uniformizerRatio`: the ratio `σ ϖ / ϖ`, as an element of `U(L,i)`.
* `TauCeti.ramificationGroupToUnitFiltrationGraded`: the homomorphism
  `G_i → U(L,i) / U(L,i+1)`, and
  `TauCeti.ramificationGroupGradedToUnitFiltrationGraded`: the induced `θ_i` on `G_i / G_{i+1}`.
* `TauCeti.tameCharacter`: the depth-zero homomorphism `G_0 → 𝓀[L]ˣ`, and
  `TauCeti.tameCharacterGraded`: the map it induces on `G_0 / G_1`.

## Main results

* `TauCeti.mem_ramificationGroup_natCast_iff_valuation_le`: the valuation form of the
  ramification filtration, `v(σ x - x) ≤ v(ϖ)^(i+1)` for every integer `x`.
* `TauCeti.ramificationGroupToUnitFiltrationGraded_eq_of_irreducible`,
  `TauCeti.ramificationGroupGradedToUnitFiltrationGraded_eq_of_irreducible`,
  `TauCeti.tameCharacter_eq_of_irreducible` and
  `TauCeti.tameCharacterGraded_eq_of_irreducible`: independence of the choice of uniformizer.
* `TauCeti.ker_ramificationGroupToUnitFiltrationGraded` and
  `TauCeti.ramificationGroupGradedToUnitFiltrationGraded_injective`: the kernel is exactly
  `G_{i+1}`, and `θ_i` is injective, in the monogenic case.
* `TauCeti.isCyclic_ramificationGroupGraded_zero` and
  `TauCeti.card_ramificationGroupGraded_zero_dvd_card_residueField_sub_one`: in the monogenic
  case the tame quotient is cyclic, of order dividing `q - 1`.

## Implementation notes

The ramification groups are indexed by `ℤ` and the unit filtration by `ℕ`. Every general statement
below therefore fixes a natural index `i` and reads the ramification group at `(i : ℤ)`, whereas
the depth-zero declarations fix the index `(0 : ℤ)`, the spelling in which a statement about
`G_0 / G_1` is met.

## References

* [J.-P. Serre, *Corps Locaux*][serre1968], Chapter IV, §2, Proposition 5.
-/

public section
noncomputable section

open ValuativeRel IsLocalRing IsNonarchimedeanLocalField TauCeti.IsLocalRing

namespace TauCeti

variable {L : Type*} [Field L] [ValuativeRel L] [TopologicalSpace L]
  [IsNonarchimedeanLocalField L]
variable {G : Type*} [Group G] [MulSemiringAction G L] [IsInvariantSubring G 𝒪[L]]
variable {ϖ : 𝒪[L]} {i : ℕ} {σ : G}

/-! ### The valuation form of the ramification filtration -/

omit [TopologicalSpace L] [IsNonarchimedeanLocalField L] in
/-- The image of an integer of `L` under the action, read in `L`. This is `map_smul` for the
equivariant inclusion `IsInvariantSubring.subtypeHom`. -/
private theorem coe_smul_integer (σ : G) (y : 𝒪[L]) : ((σ • y : 𝒪[L]) : L) = σ • (y : L) :=
  map_smul (IsInvariantSubring.subtypeHom G 𝒪[L]) σ y

omit [TopologicalSpace L] [IsNonarchimedeanLocalField L] in
/-- The displacement `σ y - y` of an integer of `L`, read in `L`. -/
private theorem coe_smul_sub_integer (σ : G) (y : 𝒪[L]) :
    ((σ • y - y : 𝒪[L]) : L) = σ • (y : L) - (y : L) := by
  rw [AddSubgroupClass.coe_sub, coe_smul_integer]

/-- Lying in a power of the maximal ideal, for a difference `σ y - y`, is a valuation inequality
measured against a uniformizer. -/
private theorem sub_mem_maximalIdeal_pow_iff (hϖ : Irreducible ϖ) (σ : G) (y : 𝒪[L]) (n : ℕ) :
    σ • y - y ∈ 𝓂[L] ^ n ↔ valuation L (σ • (y : L) - (y : L)) ≤ valuation L (ϖ : L) ^ n := by
  rw [← coe_smul_sub_integer]
  exact Set.ext_iff.mp
    (hϖ.maximalIdeal_pow_eq_setOfPred_le_v_coe_pow (valuation L) n) (σ • y - y)

/-- **Serre's valuation form** of the ramification filtration: `σ` lies in `G_i` exactly when it
moves every integer of `L` by an element of valuation at most `v(ϖ) ^ (i + 1)`, for `ϖ` a
uniformizer. The left-hand side does not mention `ϖ`, so neither side depends on the choice.
The same condition read through the additive valuation of the discrete valuation ring `𝒪[L]` is
`TauCeti.IsLocalRing.mem_ramificationGroup_iff_le_addVal`; the multiplicative form below is the
one in which the unit filtration is stated. -/
theorem mem_ramificationGroup_natCast_iff_valuation_le (hϖ : Irreducible ϖ) :
    σ ∈ ramificationGroup G 𝒪[L] (i : ℤ) ↔
      ∀ y : 𝒪[L], valuation L (σ • (y : L) - (y : L)) ≤ valuation L (ϖ : L) ^ (i + 1) := by
  rw [mem_ramificationGroup_natCast_iff]
  exact forall_congr' fun y ↦ sub_mem_maximalIdeal_pow_iff hϖ σ y (i + 1)

/-- The action preserves the valuation of a uniformizer: the image of an irreducible element of
`𝒪[L]` is irreducible, hence associated to it. -/
theorem valuation_smul_of_irreducible (hϖ : Irreducible ϖ) (σ : G) :
    valuation L (σ • (ϖ : L)) = valuation L (ϖ : L) := by
  have hσϖ : Irreducible (σ • ϖ) := hϖ.map (MulSemiringAction.toRingAut G 𝒪[L] σ)
  obtain ⟨u, hu⟩ : ∃ u : 𝒪[L]ˣ, σ • ϖ * (u : 𝒪[L]) = ϖ :=
    ⟨uniformizerChangeUnit (σ • ϖ) ϖ hσϖ hϖ, mul_uniformizerChangeUnit (σ • ϖ) ϖ hσϖ hϖ⟩
  have h := congrArg (fun y : 𝒪[L] ↦ valuation L (y : L)) hu
  have hu1 : valuation L ((u : 𝒪[L]) : L) = 1 :=
    (Valuation.integer.integers (valuation L)).valuation_unit u
  simpa [hu1, coe_smul_integer] using h

/-! ### The ratio of a uniformizer -/

/-- For `σ` in the `i`-th ramification group and `x` a unit of `𝒪[L]`, the ratio `σ x / x` lies
one step deeper in the unit filtration, in `U(L, i+1)`. -/
theorem mem_unitFiltration_succ_of_val_eq_smul_div
    (hσ : σ ∈ ramificationGroup G 𝒪[L] (i : ℤ)) {x y : Lˣ} (hx : x ∈ unitFiltration L 0)
    (hy : (y : L) = σ • (x : L) / (x : L)) : y ∈ unitFiltration L (i + 1) := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible (R := 𝒪[L])
  obtain ⟨u, -, hux⟩ := mem_unitFiltration_iff_exists.mp hx
  have hx1 : valuation L (x : L) = 1 := (mem_unitFiltration_zero x).mp hx
  have hval : valuation L (σ • (x : L) - (x : L)) ≤ valuation L (ϖ : L) ^ (i + 1) := by
    rw [← hux]
    exact (mem_ramificationGroup_natCast_iff_valuation_le hϖ).mp hσ u
  rw [mem_unitFiltration_succ_valuation i y ϖ hϖ, hy, div_sub_one x.ne_zero, map_div₀, hx1,
    div_one, map_pow]
  exact hval

/-- For `σ` in the `i`-th ramification group and `ϖ` a uniformizer, the ratio `σ ϖ / ϖ` lies in
the `i`-th step `U(L,i)` of the unit filtration. -/
theorem mem_unitFiltration_of_val_eq_smul_div (hϖ : Irreducible ϖ)
    (hσ : σ ∈ ramificationGroup G 𝒪[L] (i : ℤ)) {y : Lˣ}
    (hy : (y : L) = σ • (ϖ : L) / (ϖ : L)) : y ∈ unitFiltration L i := by
  have hϖpos : 0 < valuation L (ϖ : L) := by
    simpa using Valuation.integer.v_irreducible_pos (v := valuation L) hϖ
  have hϖne : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  refine (mem_unitFiltration_iff_valuation_le hϖ).mpr ⟨?_, ?_⟩
  · rw [hy, map_div₀, valuation_smul_of_irreducible hϖ σ, div_self hϖpos.ne']
  · rw [hy, div_sub_one hϖne, map_div₀, div_le_iff₀ hϖpos, ← pow_succ]
    exact (mem_ramificationGroup_natCast_iff_valuation_le hϖ).mp hσ ϖ

variable (i) in
/-- The ratio `σ ϖ / ϖ` of a uniformizer `ϖ` and its image under an element `σ` of the `i`-th
ramification group, as an element of the `i`-th step `U(L,i)` of the unit filtration. -/
def uniformizerRatio (hϖ : Irreducible ϖ) (σ : ramificationGroup G 𝒪[L] (i : ℤ)) :
    unitFiltration L i :=
  ⟨Units.mk0 ((σ : G) • (ϖ : L) / (ϖ : L)) (by
      have hϖne : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
      exact div_ne_zero ((smul_ne_zero_iff_ne _).mpr hϖne) hϖne),
    mem_unitFiltration_of_val_eq_smul_div hϖ σ.2 rfl⟩

@[simp]
theorem coe_uniformizerRatio (hϖ : Irreducible ϖ) (σ : ramificationGroup G 𝒪[L] (i : ℤ)) :
    ((uniformizerRatio i hϖ σ : Lˣ) : L) = (σ : G) • (ϖ : L) / (ϖ : L) := (rfl)

/-! ### The quotient homomorphism -/

variable (i) in
/-- The **quotient homomorphism** attached to a uniformizer `ϖ`: the homomorphism
`G_i → U(L,i) / U(L,i+1)` carrying `σ` to the class of `σ ϖ / ϖ`. It kills `G_{i+1}`, so it may
fail to be injective; the map it induces on `G_i / G_{i+1}` is the embedding `θ_i` of
`TauCeti.ramificationGroupGradedToUnitFiltrationGraded`, injective whenever `𝒪[L]` is generated
by `ϖ` over a base ring whose scalars commute with the action of `G`. -/
def ramificationGroupToUnitFiltrationGraded (hϖ : Irreducible ϖ) :
    ramificationGroup G 𝒪[L] (i : ℤ) →* UnitFiltrationGraded L i :=
  MonoidHom.mk' (fun σ ↦ QuotientGroup.mk (uniformizerRatio i hϖ σ)) <| by
    intro σ τ
    have hϖne : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
    have hσϖ : (σ : G) • (ϖ : L) ≠ 0 := (smul_ne_zero_iff_ne _).mpr hϖne
    have hτϖ : (τ : G) • (ϖ : L) ≠ 0 := (smul_ne_zero_iff_ne _).mpr hϖne
    rw [← QuotientGroup.mk_mul]
    refine QuotientGroup.eq.mpr ?_
    rw [Subgroup.mem_subgroupOf, ← Subgroup.inv_mem_iff]
    refine mem_unitFiltration_succ_of_val_eq_smul_div (σ := (σ : G)) σ.2
      (unitFiltration_antitone (Nat.zero_le i) (uniformizerRatio i hϖ τ).2) ?_
    have hsmul : (σ : G) • ((τ : G) • (ϖ : L) / (ϖ : L))
        = ((σ : G) * (τ : G)) • (ϖ : L) / (σ : G) • (ϖ : L) := by
      rw [div_eq_mul_inv, smul_mul', smul_inv'', ← div_eq_mul_inv, ← mul_smul]
    push_cast [coe_uniformizerRatio, hsmul]
    field_simp

@[simp]
theorem ramificationGroupToUnitFiltrationGraded_apply (hϖ : Irreducible ϖ)
    (σ : ramificationGroup G 𝒪[L] (i : ℤ)) :
    ramificationGroupToUnitFiltrationGraded i hϖ σ =
      QuotientGroup.mk (uniformizerRatio i hϖ σ) := (rfl)

/-- The quotient homomorphism does not depend on the choice of uniformizer: two uniformizers
differ by a unit of `𝒪[L]`, and `σ` moves that unit inside `U(L,i+1)`. -/
theorem ramificationGroupToUnitFiltrationGraded_eq_of_irreducible {ϖ' : 𝒪[L]}
    (hϖ : Irreducible ϖ) (hϖ' : Irreducible ϖ') :
    ramificationGroupToUnitFiltrationGraded (G := G) i hϖ =
      ramificationGroupToUnitFiltrationGraded (G := G) i hϖ' := by
  obtain ⟨u, hu⟩ : ∃ u : 𝒪[L]ˣ, ϖ * (u : 𝒪[L]) = ϖ' :=
    ⟨uniformizerChangeUnit ϖ ϖ' hϖ hϖ', mul_uniformizerChangeUnit ϖ ϖ' hϖ hϖ'⟩
  have hϖne : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  refine MonoidHom.ext fun σ ↦ ?_
  have hσϖ : (σ : G) • (ϖ : L) ≠ 0 := (smul_ne_zero_iff_ne _).mpr hϖne
  have hune : ((u : 𝒪[L]) : L) ≠ 0 := (u.isUnit.map (Subring.subtype 𝒪[L])).ne_zero
  rw [ramificationGroupToUnitFiltrationGraded_apply, ramificationGroupToUnitFiltrationGraded_apply]
  refine QuotientGroup.eq.mpr ?_
  rw [Subgroup.mem_subgroupOf]
  refine mem_unitFiltration_succ_of_val_eq_smul_div (σ := (σ : G)) σ.2
    (x := Units.map (Subring.subtype 𝒪[L]).toMonoidHom u) (mem_unitFiltration_iff_exists.mpr
      ⟨u, by simp, rfl⟩) ?_
  have hϖ'L : (ϖ' : L) = (ϖ : L) * ((u : 𝒪[L]) : L) := by
    rw [← hu]
    simp
  have hsmul : (σ : G) • (ϖ' : L) = (σ : G) • (ϖ : L) * (σ : G) • ((u : 𝒪[L]) : L) := by
    rw [hϖ'L, smul_mul']
  have hxval : ((Units.map (Subring.subtype 𝒪[L]).toMonoidHom u : Lˣ) : L) = ((u : 𝒪[L]) : L) :=
    rfl
  push_cast [coe_uniformizerRatio, hϖ'L, hsmul, hxval, smul_mul']
  field_simp

/-! ### The kernel -/

/-- The kernel of the quotient homomorphism, as a valuation condition at the chosen uniformizer:
`σ` is killed exactly when it moves `ϖ` one step deeper than membership in `G_i` requires. -/
theorem mem_ker_ramificationGroupToUnitFiltrationGraded_iff (hϖ : Irreducible ϖ)
    {σ : ramificationGroup G 𝒪[L] (i : ℤ)} :
    σ ∈ (ramificationGroupToUnitFiltrationGraded i hϖ).ker ↔
      valuation L ((σ : G) • (ϖ : L) - (ϖ : L)) ≤ valuation L (ϖ : L) ^ (i + 2) := by
  have hϖpos : 0 < valuation L (ϖ : L) := by
    simpa using Valuation.integer.v_irreducible_pos (v := valuation L) hϖ
  have hϖne : (ϖ : L) ≠ 0 := fun h ↦ hϖ.ne_zero (Subtype.ext h)
  rw [MonoidHom.mem_ker, ramificationGroupToUnitFiltrationGraded_apply,
    QuotientGroup.eq_one_iff, Subgroup.mem_subgroupOf,
    mem_unitFiltration_succ_valuation i _ ϖ hϖ, coe_uniformizerRatio, div_sub_one hϖne,
    map_div₀, map_pow, div_le_iff₀ hϖpos, ← pow_succ]

/-- The next step `G_{i+1}` of the ramification filtration is killed by the quotient
homomorphism. -/
theorem ramificationGroup_succ_subgroupOf_le_ker (hϖ : Irreducible ϖ) :
    (ramificationGroup G 𝒪[L] ((i : ℤ) + 1)).subgroupOf (ramificationGroup G 𝒪[L] (i : ℤ)) ≤
      (ramificationGroupToUnitFiltrationGraded i hϖ).ker := by
  intro σ hσ
  have hσ' : (σ : G) ∈ ramificationGroup G 𝒪[L] ((i + 1 : ℕ) : ℤ) := by
    exact_mod_cast Subgroup.mem_subgroupOf.mp hσ
  rw [mem_ker_ramificationGroupToUnitFiltrationGraded_iff hϖ]
  exact (mem_ramificationGroup_natCast_iff_valuation_le hϖ).mp hσ' ϖ

/-- **The kernel of the quotient homomorphism is exactly `G_{i+1}`**, which is what makes the
induced `θ_i` on `G_i / G_{i+1}` an embedding. When `𝒪[L]` is generated over a base ring `R` whose
scalars commute with the action by the single uniformizer `ϖ` — the monogenic situation, for
instance a totally ramified extension with `ϖ` a root of an Eisenstein polynomial — membership in
`G_{i+1}` is decided at `ϖ`. -/
theorem ker_ramificationGroupToUnitFiltrationGraded (hϖ : Irreducible ϖ) {R : Type*}
    [CommSemiring R] [Algebra R 𝒪[L]] [SMulCommClass G R 𝒪[L]]
    (hadj : Algebra.adjoin R {ϖ} = ⊤) :
    (ramificationGroupToUnitFiltrationGraded i hϖ).ker =
      (ramificationGroup G 𝒪[L] ((i : ℤ) + 1)).subgroupOf (ramificationGroup G 𝒪[L] (i : ℤ)) := by
  refine le_antisymm (fun σ hσ ↦ ?_) (ramificationGroup_succ_subgroupOf_le_ker hϖ)
  rw [mem_ker_ramificationGroupToUnitFiltrationGraded_iff hϖ] at hσ
  -- Serre's criterion cuts out `G_{i+1}` by the `(((i : ℤ) + 1) + 1).toNat`-th power of the
  -- maximal ideal; name that index in its `ℕ` form before rewriting, as in
  -- `TauCeti.IsLocalRing.mem_ramificationGroup_natCast_iff`.
  have hidx : (((i : ℤ) + 1) + 1).toNat = i + 2 := by omega
  rw [Subgroup.mem_subgroupOf, mem_ramificationGroup_iff_of_adjoin_singleton_eq_top hadj, hidx,
    sub_mem_maximalIdeal_pow_iff hϖ]
  exact hσ

/-! ### The embedding of the graded pieces -/

variable (i) in
/-- The **quotient map** `θ_i : G_i / G_{i+1} →* U(L,i) / U(L,i+1)`, induced by
`σ ↦ σ ϖ / ϖ` for a uniformizer `ϖ`. It is an embedding under the monogenic hypothesis of
`TauCeti.ramificationGroupGradedToUnitFiltrationGraded_injective`. -/
def ramificationGroupGradedToUnitFiltrationGraded (hϖ : Irreducible ϖ) :
    RamificationGroupGraded G 𝒪[L] (i : ℤ) →* UnitFiltrationGraded L i :=
  QuotientGroup.lift _ (ramificationGroupToUnitFiltrationGraded i hϖ)
    fun _ hσ ↦ ramificationGroup_succ_subgroupOf_le_ker hϖ hσ

@[simp]
theorem ramificationGroupGradedToUnitFiltrationGraded_mk (hϖ : Irreducible ϖ)
    (σ : ramificationGroup G 𝒪[L] (i : ℤ)) :
    ramificationGroupGradedToUnitFiltrationGraded i hϖ (QuotientGroup.mk σ) =
      QuotientGroup.mk (uniformizerRatio i hϖ σ) := (rfl)

/-- **The quotient embeddings are injective** when `𝒪[L]` is generated over a base ring `R`
whose scalars commute with the action by the single uniformizer `ϖ`. -/
theorem ramificationGroupGradedToUnitFiltrationGraded_injective (hϖ : Irreducible ϖ) {R : Type*}
    [CommSemiring R] [Algebra R 𝒪[L]] [SMulCommClass G R 𝒪[L]]
    (hadj : Algebra.adjoin R {ϖ} = ⊤) :
    Function.Injective (ramificationGroupGradedToUnitFiltrationGraded (G := G) i hϖ) :=
  (QuotientGroup.injective_lift_iff _ _ _).2
    (ker_ramificationGroupToUnitFiltrationGraded (R := R) hϖ hadj).symm

/-- The descended quotient map does not depend on the choice of uniformizer. -/
theorem ramificationGroupGradedToUnitFiltrationGraded_eq_of_irreducible {ϖ' : 𝒪[L]}
    (hϖ : Irreducible ϖ) (hϖ' : Irreducible ϖ') :
    ramificationGroupGradedToUnitFiltrationGraded (G := G) i hϖ =
      ramificationGroupGradedToUnitFiltrationGraded (G := G) i hϖ' := by
  refine MonoidHom.ext fun x ↦ ?_
  induction x using QuotientGroup.induction_on with
  | _ σ =>
    exact DFunLike.congr_fun
      (ramificationGroupToUnitFiltrationGraded_eq_of_irreducible (G := G) (i := i) hϖ hϖ') σ

/-! ### The tame character -/

/-- The **tame character** `θ_0 : G_0 →* 𝓀[L]ˣ`: the depth-zero quotient homomorphism composed
with the identification of `U(L,0) / U(L,1)` with the multiplicative group of the residue
field. It carries `σ` to the residue of `σ ϖ / ϖ`. It kills `G_1`, hence factors through
`TauCeti.tameCharacterGraded`. -/
def tameCharacter (hϖ : Irreducible ϖ) : ramificationGroup G 𝒪[L] (0 : ℤ) →* 𝓀[L]ˣ :=
  (unitFiltrationGradedZeroEquivResidueFieldUnits (K := L)).toMonoidHom.comp
    (ramificationGroupToUnitFiltrationGraded 0 hϖ)

theorem coe_tameCharacter_of_val_eq_smul_div (hϖ : Irreducible ϖ)
    (σ : ramificationGroup G 𝒪[L] (0 : ℤ)) {y : 𝒪[L]}
    (hy : (y : L) = (σ : G) • (ϖ : L) / (ϖ : L)) :
    (tameCharacter hϖ σ : 𝓀[L]) = IsLocalRing.residue 𝒪[L] y := by
  -- `ramificationGroupToUnitFiltrationGraded_apply` is keyed on the cast index `(i : ℤ)`, which
  -- does not match the `simp`-normal `(0 : ℤ)` of the statement, so instantiate it at `i = 0`.
  rw [tameCharacter, MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom,
    ramificationGroupToUnitFiltrationGraded_apply (i := 0)]
  simp only [unitFiltrationGradedZeroEquivResidueFieldUnits_mk,
    ValuationSubring.coe_unitGroupToResidueFieldUnits_apply]
  refine congrArg _ (Subtype.ext ?_)
  rw [ValuationSubring.coe_unitGroupMulEquiv_apply, coe_uniformizerRatio, hy]

/-- The tame character does not depend on the choice of uniformizer. -/
theorem tameCharacter_eq_of_irreducible {ϖ' : 𝒪[L]} (hϖ : Irreducible ϖ)
    (hϖ' : Irreducible ϖ') :
    tameCharacter (G := G) hϖ = tameCharacter (G := G) hϖ' := by
  rw [tameCharacter, tameCharacter,
    ramificationGroupToUnitFiltrationGraded_eq_of_irreducible (G := G) (i := 0) hϖ hϖ']

/-- The tame character read on the quotient `G_0 / G_1` it factors through. It is injective
under the monogenic hypothesis of `TauCeti.tameCharacterGraded_injective`. -/
def tameCharacterGraded (hϖ : Irreducible ϖ) :
    RamificationGroupGraded G 𝒪[L] (0 : ℤ) →* 𝓀[L]ˣ :=
  (unitFiltrationGradedZeroEquivResidueFieldUnits (K := L)).toMonoidHom.comp
    (ramificationGroupGradedToUnitFiltrationGraded 0 hϖ)

-- The `(0 : ℤ)` index of the depth-zero declarations is `simp`-normal, unlike the cast `(i : ℤ)`
-- of the general ones, so this application lemma can carry `@[simp]`.
@[simp]
theorem tameCharacterGraded_mk (hϖ : Irreducible ϖ)
    (σ : ramificationGroup G 𝒪[L] (0 : ℤ)) :
    tameCharacterGraded hϖ (QuotientGroup.mk σ) = tameCharacter hϖ σ := (rfl)

/-- The graded tame character does not depend on the choice of uniformizer. -/
theorem tameCharacterGraded_eq_of_irreducible {ϖ' : 𝒪[L]} (hϖ : Irreducible ϖ)
    (hϖ' : Irreducible ϖ') :
    tameCharacterGraded (G := G) hϖ = tameCharacterGraded (G := G) hϖ' := by
  rw [tameCharacterGraded, tameCharacterGraded,
    ramificationGroupGradedToUnitFiltrationGraded_eq_of_irreducible (G := G) (i := 0) hϖ hϖ']

/-- **The tame character is injective on `G_0 / G_1`**, in the monogenic situation. -/
theorem tameCharacterGraded_injective (hϖ : Irreducible ϖ) {R : Type*} [CommSemiring R]
    [Algebra R 𝒪[L]] [SMulCommClass G R 𝒪[L]] (hadj : Algebra.adjoin R {ϖ} = ⊤) :
    Function.Injective (tameCharacterGraded (G := G) hϖ) :=
  (unitFiltrationGradedZeroEquivResidueFieldUnits (K := L)).injective.comp
    (ramificationGroupGradedToUnitFiltrationGraded_injective (i := 0) hϖ hadj)

/-- **The tame quotient is cyclic**, in the monogenic situation: `G_0 / G_1` then embeds into
the multiplicative group of the residue field, which is cyclic because the residue field is
finite. -/
theorem isCyclic_ramificationGroupGraded_zero (hϖ : Irreducible ϖ) {R : Type*} [CommSemiring R]
    [Algebra R 𝒪[L]] [SMulCommClass G R 𝒪[L]] (hadj : Algebra.adjoin R {ϖ} = ⊤) :
    IsCyclic (RamificationGroupGraded G 𝒪[L] (0 : ℤ)) :=
  isCyclic_of_injective _ (tameCharacterGraded_injective hϖ hadj)

/-- The order of the tame quotient `G_0 / G_1` divides `q - 1`, for `q` the cardinality of the
residue field, in the monogenic situation. -/
theorem card_ramificationGroupGraded_zero_dvd_card_residueField_sub_one (hϖ : Irreducible ϖ)
    {R : Type*} [CommSemiring R] [Algebra R 𝒪[L]] [SMulCommClass G R 𝒪[L]]
    (hadj : Algebra.adjoin R {ϖ} = ⊤) :
    Nat.card (RamificationGroupGraded G 𝒪[L] (0 : ℤ)) ∣ Nat.card 𝓀[L] - 1 := by
  rw [← Nat.card_units]
  exact Subgroup.card_dvd_of_injective _ (tameCharacterGraded_injective hϖ hadj)

end TauCeti
