/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Prod
public import Mathlib.Algebra.Group.TypeTags.Finite
public import Mathlib.Algebra.GroupWithZero.Idempotent
public import Mathlib.Algebra.MonoidAlgebra.Basic
public import Mathlib.Data.ZMod.Basic
public import Mathlib.Tactic.Abel
public import Mathlib.Tactic.LinearCombination
public import Mathlib.Tactic.Ring
public import TauCeti.Algebra.Ring.Prod

/-!
# The group algebra of the cyclic group of order two

Let `C₂ = Multiplicative (ZMod 2)`, generated by `σ = Multiplicative.ofAdd 1`. Over a commutative
ring `R`, every element of the group algebra `R[C₂]` is `a + bσ` for unique coefficients `a, b`,
and `σ² = 1`. The two characters of `C₂`, trivial and sign, assemble into the `R`-algebra
homomorphism `R[C₂] → R × R`, `a + bσ ↦ (a + b, a - b)`.

* When `2` is invertible in `R`, this map is an isomorphism `R[C₂] ≃ₐ[R] R × R`, with inverse
  `(x, y) ↦ ⅟2 (x + y) + ⅟2 (x - y) σ`; the two idempotents `⅟2 (1 ± σ)` are the preimages of
  `(1, 0)` and `(0, 1)`, and they split `R[C₂]` into the two eigenspaces of the involution `σ`.
* When `R` has no zero divisors and `2` is not a unit of `R`, there is no such splitting: the
  only idempotents of `R[C₂]` are `0` and `1`.

## Main declarations

* `TauCeti.cyclicTwoSign`: the sign character `Multiplicative (ZMod 2) →* R`.
* `MonoidAlgebra.cyclicTwoToProd`: the algebra homomorphism `R[C₂] →ₐ[R] R × R`.
* `MonoidAlgebra.cyclicTwoEquivProd`: the isomorphism `R[C₂] ≃ₐ[R] R × R` when `2` is
  invertible in `R`.
* `MonoidAlgebra.isIdempotentElem_cyclicTwo_iff`: over a ring without zero divisors in
  which `2` is not a unit, an element of `R[C₂]` is idempotent if and only if it is `0` or `1`.

## References

The ring `ℤ₂[C₂]` is the coefficient ring of the completed group algebra
`ℤ₂[[C₂ × ℤ₂]] ≅ ℤ₂[C₂][[T]]` in which J. Labute, *Classification of Demushkin groups*,
Canad. J. Math. 19 (1967), §4, p. 122, treats the even-rank Demushkin groups with `q = 2`.
Labute works integrally over `ℤ₂`; the splitting after inverting `2` and the absence of an
integral splitting recorded here are related facts about that coefficient ring, specialised to
`ℚ₂` and `ℤ₂` in `TauCeti.NumberTheory.Padics.GroupAlgebraCyclicTwo`.
-/

public section

namespace TauCeti

open MonoidAlgebra

section Sign

variable (R : Type*) [Monoid R] [HasDistribNeg R]

/-- The sign character of the cyclic group of order two, `Multiplicative (ZMod 2) →* R`, sending
the generator `Multiplicative.ofAdd 1` to `-1`. -/
def cyclicTwoSign : Multiplicative (ZMod 2) →* R where
  toFun g := (-1) ^ g.toAdd.val
  map_one' := by simp
  map_mul' x y := by
    rw [toAdd_mul, ZMod.val_add, ← pow_eq_pow_mod _ (neg_one_sq (R := R)), pow_add]

theorem cyclicTwoSign_apply (g : Multiplicative (ZMod 2)) :
    cyclicTwoSign R g = (-1) ^ g.toAdd.val := (rfl)

@[simp]
theorem cyclicTwoSign_ofAdd_one : cyclicTwoSign R (Multiplicative.ofAdd 1) = -1 := by
  rw [cyclicTwoSign_apply, toAdd_ofAdd, ZMod.val_one, pow_one]

end Sign

theorem one_ne_ofAdd_one : (1 : Multiplicative (ZMod 2)) ≠ Multiplicative.ofAdd 1 := by decide

/-- The generator `σ = Multiplicative.ofAdd 1` of `C₂` squares to `1`. -/
theorem ofAdd_one_mul_ofAdd_one :
    (Multiplicative.ofAdd (1 : ZMod 2)) * Multiplicative.ofAdd 1 = 1 := by decide

end TauCeti

namespace MonoidAlgebra

open TauCeti

section Semiring

variable {R : Type*} [Semiring R]

/-- Every element of `R[C₂]` is `a + bσ`, where `a` and `b` are its coefficients at `1` and at
the generator `σ = Multiplicative.ofAdd 1`. -/
theorem eq_single_one_add_single_ofAdd_one (x : MonoidAlgebra R (Multiplicative (ZMod 2))) :
    x = single 1 (x.coeff 1) +
      single (Multiplicative.ofAdd 1) (x.coeff (Multiplicative.ofAdd 1)) := by
  ext g
  have hg : g = 1 ∨ g = Multiplicative.ofAdd 1 := by revert g; decide
  rcases hg with rfl | rfl <;>
    simp [coeff_add, coeff_single, one_ne_ofAdd_one, one_ne_ofAdd_one.symm]

/-- The product of two elements of `R[C₂]` written as `a + bσ`: since `σ² = 1`,
`(a + bσ)(a' + b'σ) = (aa' + bb') + (ab' + ba')σ`. -/
theorem single_one_add_single_ofAdd_one_mul (a b a' b' : R) :
    (single (1 : Multiplicative (ZMod 2)) a + single (Multiplicative.ofAdd 1) b) *
        (single 1 a' + single (Multiplicative.ofAdd 1) b') =
      single 1 (a * a' + b * b') + single (Multiplicative.ofAdd 1) (a * b' + b * a') := by
  simp only [add_mul, mul_add, single_mul_single, one_mul, mul_one, ofAdd_one_mul_ofAdd_one,
    single_add]
  abel

end Semiring

section CommRing

variable (R : Type*) [CommRing R]

/-- The `R`-algebra homomorphism `R[C₂] → R × R` whose two components are the trivial and the
sign character of `C₂`: it sends `a + bσ` to `(a + b, a - b)`. -/
noncomputable def cyclicTwoToProd : MonoidAlgebra R (Multiplicative (ZMod 2)) →ₐ[R] R × R :=
  MonoidAlgebra.lift R (R × R) (Multiplicative (ZMod 2))
    ((1 : Multiplicative (ZMod 2) →* R).prod (cyclicTwoSign R))

/-- The trivial and sign characters send the monomial `r·g` to `(r, r · sign g)`. -/
@[simp]
theorem cyclicTwoToProd_single (g : Multiplicative (ZMod 2)) (r : R) :
    cyclicTwoToProd R (single g r) = (r, r * cyclicTwoSign R g) := by
  simp [cyclicTwoToProd]

/-- The trivial and sign characters send `a + bσ` to `(a + b, a - b)`, computing
`cyclicTwoToProd` from the coefficients in the basis `(1, σ)`. -/
theorem cyclicTwoToProd_single_one_add_single_ofAdd_one (a b : R) :
    cyclicTwoToProd R (single (1 : Multiplicative (ZMod 2)) a + single (Multiplicative.ofAdd 1) b) =
      (a + b, a - b) := by
  simp [map_add, cyclicTwoToProd_single, sub_eq_add_neg]

/-- The trivial and sign characters send an element of `R[C₂]` to the sum and difference
of its coefficients at `1` and at the generator `σ = Multiplicative.ofAdd 1`. -/
-- Not a simp lemma: it would rewrite the left-hand side of the simp rule `cyclicTwoToProd_single`
-- into conditional coefficients of `single`, so the monomial rule owns the simp normal form.
theorem cyclicTwoToProd_apply (x : MonoidAlgebra R (Multiplicative (ZMod 2))) :
    cyclicTwoToProd R x =
      (x.coeff 1 + x.coeff (Multiplicative.ofAdd 1),
        x.coeff 1 - x.coeff (Multiplicative.ofAdd 1)) := by
  simpa only [cyclicTwoToProd_single_one_add_single_ofAdd_one] using
    congrArg (cyclicTwoToProd R) (eq_single_one_add_single_ofAdd_one x)

section Invertible

variable [Invertible (2 : R)]

private theorem cyclicTwoToProd_bijective : Function.Bijective (cyclicTwoToProd R) := by
  refine ⟨(injective_iff_map_eq_zero _).mpr fun x hx => ?_, fun z => ?_⟩
  · rw [eq_single_one_add_single_ofAdd_one x,
      cyclicTwoToProd_single_one_add_single_ofAdd_one, Prod.mk_eq_zero] at hx
    obtain ⟨h₁, h₂⟩ := hx
    have ha : x.coeff 1 = 0 := by
      calc
        x.coeff 1 = ⅟(2 : R) * (2 * x.coeff 1) := (invOf_mul_cancel_left _ _).symm
        _ = ⅟(2 : R) * ((x.coeff 1 + x.coeff (Multiplicative.ofAdd 1)) +
            (x.coeff 1 - x.coeff (Multiplicative.ofAdd 1))) := by ring
        _ = 0 := by rw [h₁, h₂, add_zero, mul_zero]
    have hb : x.coeff (Multiplicative.ofAdd 1) = 0 := by linear_combination h₁ - ha
    rw [eq_single_one_add_single_ofAdd_one x, ha, hb, single_zero, single_zero, add_zero]
  · refine ⟨single 1 (⅟2 * (z.1 + z.2)) + single (Multiplicative.ofAdd 1) (⅟2 * (z.1 - z.2)), ?_⟩
    rw [cyclicTwoToProd_single_one_add_single_ofAdd_one]
    exact Prod.invOf_two_mul_add_sub z

/-- When `2` is invertible in `R`, the trivial and the sign character identify `R[C₂]` with
`R × R`. The inverse sends `(x, y)` to `⅟2 (x + y) + ⅟2 (x - y) σ`; in particular the two
idempotents `⅟2 (1 ± σ)` are the preimages of `(1, 0)` and `(0, 1)`. -/
noncomputable def cyclicTwoEquivProd : MonoidAlgebra R (Multiplicative (ZMod 2)) ≃ₐ[R] R × R :=
  AlgEquiv.ofBijective (cyclicTwoToProd R) (cyclicTwoToProd_bijective R)

@[simp]
theorem cyclicTwoEquivProd_apply (x : MonoidAlgebra R (Multiplicative (ZMod 2))) :
    cyclicTwoEquivProd R x = cyclicTwoToProd R x := (rfl)

/-- The inverse sends `(x, y)` to `⅟2 (x + y) + ⅟2 (x - y) σ`, recovering the two
coefficients from the trivial and sign character values. -/
@[simp]
theorem cyclicTwoEquivProd_symm_apply (z : R × R) :
    (cyclicTwoEquivProd R).symm z =
      single 1 (⅟2 * (z.1 + z.2)) + single (Multiplicative.ofAdd 1) (⅟2 * (z.1 - z.2)) := by
  rw [AlgEquiv.symm_apply_eq, cyclicTwoEquivProd_apply,
    cyclicTwoToProd_single_one_add_single_ofAdd_one]
  exact (Prod.invOf_two_mul_add_sub z).symm

end Invertible

/-- Over a ring `R` without zero divisors in which `2` is not a unit, the group algebra `R[C₂]`
has no nontrivial idempotents: an element is idempotent if and only if it is `0` or `1`. In
particular `R[C₂]` admits no direct-product decomposition, in contrast with
`cyclicTwoEquivProd` when `2` is invertible. -/
theorem isIdempotentElem_cyclicTwo_iff [NoZeroDivisors R] (h₂ : ¬ IsUnit (2 : R))
    {e : MonoidAlgebra R (Multiplicative (ZMod 2))} : IsIdempotentElem e ↔ e = 0 ∨ e = 1 := by
  refine ⟨fun he => ?_, ?_⟩
  · set a := e.coeff 1
    set b := e.coeff (Multiplicative.ofAdd 1)
    have he' : e = single 1 a + single (Multiplicative.ofAdd 1) b :=
      eq_single_one_add_single_ofAdd_one e
    rw [IsIdempotentElem, he', single_one_add_single_ofAdd_one_mul] at he
    have h₁ : a * a + b * b = a := by
      have := congrArg (fun x => x.coeff 1) he
      simpa [coeff_add, coeff_single, Finsupp.single_apply, one_ne_ofAdd_one.symm] using this
    have hb : b = 0 := by
      have hmul : b * (2 * a - 1) = 0 := by
        have := congrArg (fun x => x.coeff (Multiplicative.ofAdd 1)) he
        simp only [coeff_add, coeff_single, Finsupp.add_apply, Finsupp.single_apply,
          one_ne_ofAdd_one, ite_false, ite_true, zero_add] at this
        linear_combination this
      rcases mul_eq_zero.mp hmul with hb | hb
      · exact hb
      · exact absurd (IsUnit.of_mul_eq_one a (by linear_combination hb)) h₂
    rw [hb, mul_zero, add_zero] at h₁
    rcases IsIdempotentElem.iff_eq_zero_or_one.mp h₁ with ha | ha
    · left
      rw [he', ha, hb, single_zero, single_zero, add_zero]
    · right
      rw [he', ha, hb, single_zero, add_zero, one_def]
  · rintro (rfl | rfl)
    exacts [IsIdempotentElem.zero, IsIdempotentElem.one]

end CommRing

end MonoidAlgebra
