/-
Copyright (c) 2026 Tau Ceti. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.End.FiniteOrder
public import TauCeti.RepresentationTheory.CharacterTable.ClassFunction
public import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
public import Mathlib.RepresentationTheory.Character
public import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots

/-!
# The arithmetic of character values

If `g` is an element of finite order `n` in a group and `ρ` is a finite-dimensional
representation, then `ρ g` satisfies `X ^ n - 1`, so every root of its characteristic polynomial
is an `n`-th root of unity. As soon as that characteristic polynomial splits, over an
algebraically closed field for instance, the character value `ρ.character g` is the sum of
`finrank` of these roots of unity.

This file proves that dichotomy and reads off its arithmetic consequences: the character value is
integral over `ℤ`, and over `ℂ` it lies in the ring `ℤ[ζ]` generated by a primitive `n`-th root of
unity, is bounded in absolute value by the degree `χ(1)`, and is conjugated by inverting the group
element, since conjugation inverts roots of unity. The endomorphism `ρ g` is moreover semisimple as
soon as `n` is invertible in the coefficient field, since `X ^ n - 1` is then squarefree.

Integrality needs no splitting hypothesis, because base change to an algebraic closure transports
the character value along the field embedding; that reduction is
`TauCeti.End.isIntegral_trace_of_pow_eq_one`. Over `ℚ` it gives more than integrality over `ℤ`: a
rational algebraic integer is an integer, so a rational character is **integer-valued**. That is
what makes the character table of a group with rational representations, the symmetric group for
instance, a matrix of integers.

The facts about `ρ g` as a bare endomorphism live in `TauCeti.LinearAlgebra.End.FiniteOrder`.

The conjugation identity `conj (χ g) = χ g⁻¹` also holds for a unitary representation of a
topological group, where it is `TauCeti.ContRepresentation.character_apply_inv` and comes from the
action of `g⁻¹` being the adjoint of the action of `g`. Here it is proved for an arbitrary complex
representation of a group, from the eigenvalues alone, with no invariant inner product in sight.

## Main results

* `TauCeti.Representation.exists_multiset_rootsOfUnity_char_eq_sum_of_splits`: whenever
  `(ρ g).charpoly` splits, a character value is a sum of `finrank` many `n`-th roots of unity. The
  variant `TauCeti.Representation.exists_multiset_rootsOfUnity_char_eq_sum` specializes it to an
  algebraically closed field.
* `TauCeti.Representation.isIntegral_char`: **character values are algebraic integers**, over an
  arbitrary field. The bundled `FDRep` form is Mathlib's `FDRep.isIntegral_character`.
* `Representation.char_mem_of_forall_pow_eq_one_mem`: over an algebraically closed field,
  a character value at `g` with `g ^ n = 1` lies in every subring containing the `n`-th roots of
  unity.
* `TauCeti.Representation.exists_char_eq_intCast` and `FDRep.exists_char_eq_intCast`:
  **a rational character is integer-valued**.
* `FDRep.intCharacter`: the resulting `ℤ`-valued character of a rational representation of
  a finite group, taking the degree at the identity, and `FDRep.intClassFunction`: the same
  character read as an element of `TauCeti.ClassFunction ℤ G`.
* `FDRep.char_mem_adjoin_of_isPrimitiveRoot`: over `ℂ` they lie in `ℤ[ζ_e]`, for `ζ_e`
  a primitive root of unity of order the exponent of the group.
* `FDRep.norm_char_le_finrank`: over `ℂ`, `‖χ(g)‖ ≤ χ(1)`.
* `Representation.exists_apply_eq_smul_of_norm_char_eq_finrank` and its bundled form
  `FDRep.exists_apply_eq_smul_of_norm_char_eq_finrank`: the equality case of that bound,
  `‖χ(g)‖ = χ(1)`, which forces `ρ g` to be a root of unity times the identity.
* `FDRep.conj_char`: over `ℂ`, **inversion conjugates character values**,
  `conj (χ g) = χ g⁻¹`. This is what makes the character pairing agree with the Hermitian inner
  product on complex class functions.
* `TauCeti.Representation.isSemisimple_apply` and `FDRep.isSemisimple_ρ`: if the
  characteristic of `k` does not divide `|G|`, then `ρ g` is a semisimple endomorphism; over `ℂ`
  the hypothesis is found by instance search.

The eigenvalues are taken with algebraic multiplicity, as the root multiset of the characteristic
polynomial. The *set* of roots of the minimal polynomial is the same, namely the distinct
eigenvalues, but its root multiplicities record maximal Jordan block sizes rather than algebraic
multiplicities, so they do not sum to the trace.

Cyclotomic integrality is stated over `ℂ` only, as the roadmap prescribes.

## References

* [Character Theory roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/CharacterTheory/README.md),
  Layer 4, "The arithmetic of character values".
* I. M. Isaacs, *Character Theory of Finite Groups* (1976), Chapter 3.
* J.-P. Serre, *Linear Representations of Finite Groups* (1977), Section 12.1.
-/

public section

namespace TauCeti

open Module Polynomial

universe u v w

namespace Representation

section Field

variable {k : Type u} {G : Type v} {V : Type w} [Field k] [Monoid G] [AddCommGroup V] [Module k V]
  [FiniteDimensional k V]

/-- If `g ^ n = 1` then every eigenvalue of `ρ g` is an `n`-th root of unity. -/
theorem pow_eq_one_of_mem_roots_charpoly (ρ : Representation k G V) {g : G} {n : ℕ}
    (hg : g ^ n = 1) {μ : k} (hμ : μ ∈ (ρ g).charpoly.roots) : μ ^ n = 1 :=
  End.pow_eq_one_of_isRoot_charpoly (by rw [← map_pow, hg, map_one]) (isRoot_of_mem_roots hμ)

/-- **A character value is a sum of roots of unity.** If `g ^ n = 1` and the characteristic
polynomial of `ρ g` splits, then `ρ.character g` is the sum of a multiset of `finrank k V` many
`n`-th roots of unity, namely the eigenvalues of `ρ g` with algebraic multiplicity. -/
theorem exists_multiset_rootsOfUnity_char_eq_sum_of_splits (ρ : Representation k G V) {g : G}
    {n : ℕ} (hsplits : (ρ g).charpoly.Splits) (hg : g ^ n = 1) :
    ∃ s : Multiset k, Multiset.card s = finrank k V ∧ (∀ μ ∈ s, μ ^ n = 1) ∧
      ρ.character g = s.sum := by
  refine ⟨(ρ g).charpoly.roots, ?_, fun _ hμ => pow_eq_one_of_mem_roots_charpoly ρ hg hμ, ?_⟩
  · rw [← hsplits.natDegree_eq_card_roots, LinearMap.charpoly_natDegree]
  · simp only [Representation.character]
    exact End.trace_eq_sum_roots_charpoly_of_splits hsplits

/-- **A character value is a sum of roots of unity.** Over an algebraically closed field, if
`g ^ n = 1` then `ρ.character g` is the sum of a multiset of `finrank k V` many `n`-th roots of
unity, namely the eigenvalues of `ρ g` with algebraic multiplicity. -/
theorem exists_multiset_rootsOfUnity_char_eq_sum [IsAlgClosed k] (ρ : Representation k G V) {g : G}
    {n : ℕ} (hg : g ^ n = 1) :
    ∃ s : Multiset k, Multiset.card s = finrank k V ∧ (∀ μ ∈ s, μ ^ n = 1) ∧
      ρ.character g = s.sum :=
  exists_multiset_rootsOfUnity_char_eq_sum_of_splits ρ (IsAlgClosed.splits _) hg

omit [FiniteDimensional k V] in
/-- If `g ^ n = 1` with `n` invertible in `k`, then `ρ g` is a semisimple endomorphism. This needs
no hypothesis on the field beyond invertibility of `n`. Over a field splitting `X ^ n - 1`, an
algebraically closed one for instance, semisimplicity of `ρ g` is its diagonalizability, the form
in which it underlies the eigenvalue description of character values. -/
theorem isSemisimple_of_pow_eq_one (ρ : Representation k G V) {g : G} {n : ℕ} (hn : (n : k) ≠ 0)
    (hg : g ^ n = 1) : End.IsSemisimple (ρ g) :=
  End.isSemisimple_of_pow_eq_one hn (by rw [← map_pow, hg, map_one])

/-- **Character values are algebraic integers**: over any field, the value of a character at an
element of finite order is integral over `ℤ`. Once the characteristic polynomial of `ρ g` splits
this is the statement that a sum of roots of unity is an algebraic integer, and the general case
follows from that one by base change to an algebraic closure
(`TauCeti.End.isIntegral_trace_of_pow_eq_one`). -/
theorem isIntegral_char (ρ : Representation k G V) {g : G} {n : ℕ}
    (hn : n ≠ 0) (hg : g ^ n = 1) : IsIntegral ℤ (ρ.character g) := by
  have hf : ρ g ^ n = 1 := by rw [← map_pow, hg, map_one]
  exact End.isIntegral_trace_of_pow_eq_one hn hf

/-- **Character values lie in every subring containing the relevant roots of unity.** Over an
algebraically closed field, if `g ^ n = 1` and the subring `A` of `k` contains every `n`-th root of
unity, then `ρ.character g ∈ A`, being a sum of `n`-th roots of unity. -/
theorem _root_.Representation.char_mem_of_forall_pow_eq_one_mem [IsAlgClosed k]
    (ρ : Representation k G V) {g : G}
    {n : ℕ} (hg : g ^ n = 1) {A : Subring k} (hA : ∀ x : k, x ^ n = 1 → x ∈ A) :
    ρ.character g ∈ A := by
  obtain ⟨s, -, hroot, hsum⟩ := exists_multiset_rootsOfUnity_char_eq_sum ρ hg
  rw [hsum]
  exact A.multiset_sum_mem s fun μ hμ => hA μ (hroot μ hμ)

end Field

section Rat

variable {G : Type v} {V : Type w} [Monoid G] [AddCommGroup V] [Module ℚ V] [FiniteDimensional ℚ V]

/-- **A rational character value is an integer.** The character of a representation over `ℚ` takes
at an element of finite order a value that is integral over `ℤ`, and `ℤ` is integrally closed in
its fraction field `ℚ`, so that value is the cast of an integer. -/
theorem exists_char_eq_intCast (ρ : Representation ℚ G V) {g : G} {n : ℕ} (hn : n ≠ 0)
    (hg : g ^ n = 1) : ∃ m : ℤ, ρ.character g = (m : ℚ) := by
  obtain ⟨m, hm⟩ := IsIntegrallyClosed.isIntegral_iff.1 (isIntegral_char ρ hn hg)
  exact ⟨m, by simpa using hm.symm⟩

end Rat

section Group

variable {k : Type u} {G : Type v} {V : Type w} [Field k] [Group G] [AddCommGroup V] [Module k V]

/-- **If the order of `G` is invertible in `k`, then every group element acts semisimply.** The
order of `g` divides `|G|`, so it too is invertible, and `ρ g` is annihilated by the squarefree
polynomial `X ^ orderOf g - 1`. Over a field splitting that polynomial, an algebraically closed one
for instance, this is diagonalizability of `ρ g`. -/
theorem isSemisimple_apply (ρ : Representation k G V) (hG : (Nat.card G : k) ≠ 0) (g : G) :
    End.IsSemisimple (ρ g) :=
  isSemisimple_of_pow_eq_one ρ
    (ne_zero_of_dvd_ne_zero hG (Nat.cast_dvd_cast (orderOf_dvd_natCard g))) (pow_orderOf_eq_one g)

end Group

section Complex

variable {G : Type v} {V : Type w} [Monoid G] [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- **Character values are cyclotomic integers**: over `ℂ`, if `ζ` is a primitive `n`-th root of
unity and `g ^ n = 1`, then `ρ.character g` lies in the subring `ℤ[ζ]` of `ℂ`. -/
theorem char_mem_adjoin_of_isPrimitiveRoot (ρ : Representation ℂ G V) {g : G} {ζ : ℂ} {n : ℕ}
    [NeZero n] (hζ : IsPrimitiveRoot ζ n) (hg : g ^ n = 1) :
    ρ.character g ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) := by
  have hmem : ζ ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) := Algebra.subset_adjoin rfl
  have hA : ∀ μ : ℂ, μ ^ n = 1 → μ ∈ (Algebra.adjoin ℤ ({ζ} : Set ℂ)).toSubring := by
    intro μ hμ
    obtain ⟨i, -, rfl⟩ := hζ.eq_pow_of_pow_eq_one hμ
    exact Subalgebra.mem_toSubring.2 (Subalgebra.pow_mem _ hmem i)
  exact Subalgebra.mem_toSubring.1 (Representation.char_mem_of_forall_pow_eq_one_mem ρ hg hA)

/-- Over `ℂ` a character value at an element of finite order is bounded in absolute value by the
degree of the representation, since it is a sum of `finrank ℂ V` many roots of unity. -/
theorem norm_char_le_finrank (ρ : Representation ℂ G V) {g : G} {n : ℕ} (hn : n ≠ 0)
    (hg : g ^ n = 1) : ‖ρ.character g‖ ≤ finrank ℂ V := by
  obtain ⟨s, hcard, hroot, hsum⟩ := exists_multiset_rootsOfUnity_char_eq_sum ρ hg
  have hmap : s.map (fun μ => ‖μ‖) = s.map (fun _ => (1 : ℝ)) :=
    Multiset.map_congr rfl fun μ hμ => Complex.norm_eq_one_of_pow_eq_one (hroot μ hμ) hn
  calc ‖ρ.character g‖ = ‖s.sum‖ := by rw [hsum]
    _ ≤ (s.map (fun μ => ‖μ‖)).sum := norm_multiset_sum_le s
    _ = finrank ℂ V := by rw [hmap]; simp [hcard]

/-- **The equality case of the bound on a character value.** If the absolute value of
`ρ.character g` attains the degree `finrank ℂ V`, then `ρ g` is a scalar, the scalar being an
`n`-th root of unity: the character value is a sum of `finrank ℂ V` many roots of unity, so it can
have that absolute value only if they all coincide, and then `ρ g` is diagonalizable with a single
eigenvalue. The bound itself is `TauCeti.Representation.norm_char_le_finrank`. -/
theorem _root_.Representation.exists_apply_eq_smul_of_norm_char_eq_finrank
    (ρ : Representation ℂ G V) {g : G} {n : ℕ}
    (hn : n ≠ 0) (hg : g ^ n = 1) (h : ‖ρ.character g‖ = (finrank ℂ V : ℝ)) :
    ∃ μ : ℂ, μ ^ n = 1 ∧ ρ g = μ • 1 :=
  Module.End.exists_eq_smul_of_norm_trace_eq_finrank hn (by rw [← map_pow, hg, map_one]) h

end Complex

section ComplexGroup

variable {G : Type v} {V : Type w} [Group G] [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- **Over `ℂ`, inversion conjugates character values**: if `g ^ n = 1` with `n ≠ 0`, then
`conj (χ g) = χ g⁻¹`. The eigenvalues of `ρ g` are `n`-th roots of unity, so conjugating them
inverts them, and `ρ g⁻¹` is the inverse of `ρ g`. -/
theorem conj_char_eq_char_inv (ρ : Representation ℂ G V) {g : G} {n : ℕ} (hn : n ≠ 0)
    (hg : g ^ n = 1) : (starRingEnd ℂ) (ρ.character g) = ρ.character g⁻¹ := by
  have hf : ρ g ^ n = 1 := by rw [← map_pow, hg, map_one]
  have hinv : g⁻¹ = g ^ (n - 1) :=
    inv_eq_of_mul_eq_one_right (by
      rw [← pow_succ', Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.2 hn), hg])
  simp only [Representation.character, hinv, map_pow]
  exact End.conj_trace_eq_trace_pow_sub_one hn hf

/-- **Over `ℂ`, inversion conjugates the character values of a finite group.** -/
@[simp]
theorem conj_char [Finite G] (ρ : Representation ℂ G V) (g : G) :
    (starRingEnd ℂ) (ρ.character g) = ρ.character g⁻¹ :=
  conj_char_eq_char_inv ρ (isOfFinOrder_of_finite g).orderOf_pos.ne' (pow_orderOf_eq_one g)

end ComplexGroup

end Representation

namespace FDRep

variable {G : Type v} [Group G] [Finite G]

/-- **A rational character is integer-valued.** For a finite group, every value of the character of
a finite-dimensional representation over `ℚ` is the cast of an integer. -/
theorem _root_.FDRep.exists_char_eq_intCast (V : FDRep ℚ G) (g : G) :
    ∃ m : ℤ, V.character g = (m : ℚ) :=
  Representation.exists_char_eq_intCast V.ρ (isOfFinOrder_of_finite g).orderOf_pos.ne'
    (pow_orderOf_eq_one g)

/-- **The integer character** of a rational representation of a finite group: the character value
`V.character g` is the cast of an integer (`FDRep.exists_char_eq_intCast`), and this is
that integer, extracted as the numerator of the rational value. Read it only through
`FDRep.intCharacter_cast`, which is what pins it down; the numerator is a way of naming the
integer, not extra information.

It lives in the root `FDRep` namespace, so dot notation on an `FDRep ℚ G` reaches it: write
`V.intCharacter g`. -/
noncomputable def _root_.FDRep.intCharacter (V : FDRep ℚ G) (g : G) : ℤ := (V.character g).num

omit [Finite G] in
private theorem intCharacter_def (V : FDRep ℚ G) (g : G) :
    FDRep.intCharacter V g = (V.character g).num := (rfl)

/-- **The integer character casts back to the character.** -/
@[simp]
theorem _root_.FDRep.intCharacter_cast (V : FDRep ℚ G) (g : G) :
    (FDRep.intCharacter V g : ℚ) = V.character g := by
  obtain ⟨m, hm⟩ := FDRep.exists_char_eq_intCast V g
  rw [intCharacter_def, hm, Rat.num_intCast]

/-- **The integer character carries exactly the information of the rational one**: this is the
elimination principle for `FDRep.intCharacter`, an integer equation between its values
being the corresponding equation between character values. -/
theorem _root_.FDRep.intCharacter_eq_iff {V W : FDRep ℚ G} {g h : G} :
    FDRep.intCharacter V g = FDRep.intCharacter W h ↔ V.character g = W.character h := by
  rw [← Int.cast_inj (α := ℚ), FDRep.intCharacter_cast, FDRep.intCharacter_cast]

/-- **The integer character is a class function.** -/
@[simp]
theorem _root_.FDRep.intCharacter_conj (V : FDRep ℚ G) (g h : G) :
    FDRep.intCharacter V (h * g * h⁻¹) = FDRep.intCharacter V g :=
  _root_.FDRep.intCharacter_eq_iff.2 (_root_.FDRep.char_conj V g h)

/-- **The integer character of a rational representation, as a class function.** -/
noncomputable def _root_.FDRep.intClassFunction (V : FDRep ℚ G) : ClassFunction ℤ G :=
  ⟨FDRep.intCharacter V, ClassFunction.mem_iff.2 (FDRep.intCharacter_conj V)⟩

@[simp]
theorem _root_.FDRep.intClassFunction_apply (V : FDRep ℚ G) (g : G) :
    (FDRep.intClassFunction V).1 g = FDRep.intCharacter V g := (rfl)

/-- Conjugate elements have the same integer character. -/
theorem _root_.FDRep.intCharacter_eq_of_isConj (V : FDRep ℚ G) {g h : G} (hgh : IsConj g h) :
    FDRep.intCharacter V g = FDRep.intCharacter V h :=
  ClassFunction.eq_of_isConj (FDRep.intClassFunction V) hgh

/-- **The integer character at the identity is the degree.** -/
@[simp]
theorem _root_.FDRep.intCharacter_one (V : FDRep ℚ G) :
    FDRep.intCharacter V 1 = Module.finrank ℚ V :=
  Int.cast_injective (α := ℚ) (by simp)

/-- **Character values are cyclotomic integers.** For a finite group of exponent `e` and a
primitive `e`-th root of unity `ζ`, every value of a complex character lies in `ℤ[ζ]`. -/
theorem _root_.FDRep.char_mem_adjoin_of_isPrimitiveRoot (V : FDRep ℂ G) {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ (Monoid.exponent G)) (g : G) :
    V.character g ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) :=
  haveI : NeZero (Monoid.exponent G) := ⟨Monoid.exponent_ne_zero_of_finite⟩
  Representation.char_mem_adjoin_of_isPrimitiveRoot V.ρ hζ (Monoid.pow_exponent_eq_one g)

/-- Over `ℂ`, a character of a finite group is bounded in absolute value by its degree,
`‖χ(g)‖ ≤ χ(1)`. -/
theorem _root_.FDRep.norm_char_le_finrank (V : FDRep ℂ G) (g : G) : ‖V.character g‖ ≤ finrank ℂ V :=
  Representation.norm_char_le_finrank V.ρ (isOfFinOrder_of_finite g).orderOf_pos.ne'
    (pow_orderOf_eq_one g)

/-- **The equality case of the bound on a character value**, for a finite group: if `‖χ(g)‖`
attains the degree, then `V.ρ g` is a scalar, the scalar being a root of unity of order dividing
that of `g`. The bound itself is `FDRep.norm_char_le_finrank`. -/
theorem _root_.FDRep.exists_apply_eq_smul_of_norm_char_eq_finrank (V : FDRep ℂ G) {g : G}
    (h : ‖V.character g‖ = (finrank ℂ V : ℝ)) :
    ∃ μ : ℂ, μ ^ orderOf g = 1 ∧ V.ρ g = μ • 1 :=
  Representation.exists_apply_eq_smul_of_norm_char_eq_finrank V.ρ
    (isOfFinOrder_of_finite g).orderOf_pos.ne' (pow_orderOf_eq_one g) h

/-- **Over `ℂ`, inversion conjugates the character values of a finite group**, so that a complex
character is a "unitary" class function: `conj (χ g) = χ g⁻¹`. -/
@[simp]
theorem _root_.FDRep.conj_char (V : FDRep ℂ G) (g : G) :
    (starRingEnd ℂ) (V.character g) = V.character g⁻¹ :=
  Representation.conj_char V.ρ g

omit [Finite G] in
/-- **Diagonalizability.** If the order of `G` is invertible in `k`, which forces `G` to be finite
and which every finite group satisfies in characteristic zero, then `V.ρ g` is a semisimple
endomorphism. Over an algebraically closed field, `ℂ` for instance, this is its
diagonalizability. -/
theorem _root_.FDRep.isSemisimple_ρ {k : Type u} [Field k] [NeZero (Nat.card G : k)] (V : FDRep k G)
    (g : G) : End.IsSemisimple (V.ρ g) :=
  Representation.isSemisimple_apply V.ρ (NeZero.ne _) g

end FDRep

end TauCeti
