/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.RingTheory.Kaehler.Basic

/-!
# Ranges of base-change maps for Kähler differentials

This file records two reusable consequences of the Jacobi–Zariski sequence. The base-change map
onto `Ω[B⁄R]` is surjective exactly when `Ω[B⁄A]` vanishes, and if `Ω[A⁄R]` is cyclic then
its range is generated by the image of a generator. The final linear-algebra lemma identifies
generation by one vector with nonvanishing in a one-dimensional vector space.

## Main results

* `TauCeti.subsingleton_kaehlerDifferential_iff_range_mapBaseChange_eq_top`
* `TauCeti.range_mapBaseChange_eq_span_singleton`
* `TauCeti.span_singleton_eq_top_iff_ne_zero_of_finrank_eq_one`
-/

public section

noncomputable section

namespace TauCeti

open Module

variable (R A B : Type*) [CommRing R] [CommRing A] [CommRing B] [Algebra R A] [Algebra R B]
  [Algebra A B] [IsScalarTower R A B]

/-- In a tower `R → A → B`, the first map in the Jacobi–Zariski sequence is surjective
exactly when the relative differential module `Ω[B⁄A]` vanishes. -/
theorem subsingleton_kaehlerDifferential_iff_range_mapBaseChange_eq_top :
    Subsingleton Ω[B⁄A] ↔ (KaehlerDifferential.mapBaseChange R A B).range = ⊤ := by
  rw [KaehlerDifferential.range_mapBaseChange, LinearMap.ker_eq_top]
  refine ⟨fun h ↦ LinearMap.ext fun x ↦ Subsingleton.elim _ _, fun h ↦ ⟨fun x y ↦ ?_⟩⟩
  obtain ⟨x, rfl⟩ := KaehlerDifferential.map_surjective R A B x
  obtain ⟨y, rfl⟩ := KaehlerDifferential.map_surjective R A B y
  rw [h, LinearMap.zero_apply, LinearMap.zero_apply]

/-- If `Ω[A⁄R]` is generated by `ω`, then the range of the base-change map to `Ω[B⁄R]` is
generated by the image of `ω`. -/
theorem range_mapBaseChange_eq_span_singleton (ω : Ω[A⁄R])
    (hω : Submodule.span A {ω} = ⊤) :
    (KaehlerDifferential.mapBaseChange R A B).range =
      Submodule.span B {KaehlerDifferential.map R R A B ω} := by
  refine le_antisymm ?_ ?_
  · rintro v ⟨t, rfl⟩
    induction t using TensorProduct.inductionOn with
    | tmul b η =>
      obtain ⟨a, rfl⟩ := (Submodule.span_singleton_eq_top_iff A ω).mp hω η
      rw [KaehlerDifferential.mapBaseChange_tmul, map_smul]
      exact Submodule.smul_mem _ _ (Submodule.smul_of_tower_mem _ _
        (Submodule.mem_span_singleton_self _))
    | add x y hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact ⟨1 ⊗ₜ ω, by rw [KaehlerDifferential.mapBaseChange_tmul, one_smul]⟩

/-- In a one-dimensional vector space, a singleton spans exactly when its vector is nonzero. -/
theorem span_singleton_eq_top_iff_ne_zero_of_finrank_eq_one {K V : Type*} [DivisionRing K]
    [AddCommGroup V] [Module K V] (hfin : finrank K V = 1) (v : V) :
    Submodule.span K {v} = ⊤ ↔ v ≠ 0 := by
  constructor
  · intro hspan hv
    subst v
    rw [Submodule.span_zero_singleton] at hspan
    have hzero (w : V) : w = 0 :=
      (Submodule.mem_bot _).mp (hspan ▸ Submodule.mem_top)
    let _ : Subsingleton V := ⟨fun x y ↦ (hzero x).trans (hzero y).symm⟩
    exact Nat.one_ne_zero (hfin.symm.trans Module.finrank_zero_of_subsingleton)
  · exact fun hv ↦ (finrank_eq_one_iff_of_nonzero v hv).mp hfin

end TauCeti
