/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Index.DedekindCubic.Basic
public import Mathlib.RingTheory.Discriminant
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.LinearCombination

/-!
# The order in Dedekind's cubic field

For an integral element `θ` with minimal polynomial `X³ - X² - 2X - 8`, the
extra integer `β = (θ² - θ)/2` enlarges the power order. The algebra generated by
`θ` and `β` has integral basis `(1, θ, β)` and discriminant `−503`.
This explicit order is the input to the index–discriminant argument identifying
the full ring of integers and to the computation of its primes above `2`.

The construction follows Neukirch, *Algebraic Number Theory*, III §2, Exercise 1.
The discriminant is computed from the multiplication matrices of the integral
basis using Mathlib's `Algebra.trace_eq_matrix_trace`. The construction does not
require `θ` to generate the ambient field.
-/

public section
noncomputable section

open Polynomial NumberField Module Matrix
open scoped NumberField

namespace TauCeti.NumberField

section Order

variable {K : Type*} [Field K] [CharZero K] {θ : 𝓞 K}

/-- The order generated by `θ` and the extra integer `(θ² - θ)/2`. -/
def dedekindOrder (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) : Subalgebra ℤ (𝓞 K) :=
  Algebra.adjoin ℤ {θ, dedekindBeta hθ}

/-- Elements of Dedekind's order are exactly the integer linear combinations of
`1`, `θ`, and `β`. -/
@[simp] theorem mem_dedekindOrder_iff (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) (x : 𝓞 K) :
    x ∈ dedekindOrder hθ ↔ ∃ a b c : ℤ,
      x = a + b * θ + c * dedekindBeta hθ := by
  constructor
  · intro hx
    induction hx using Algebra.adjoin_induction with
    | mem y hy =>
      rcases Set.mem_insert_iff.mp hy with rfl | hy
      · exact ⟨0, 1, 0, by simp⟩
      · obtain rfl := Set.mem_singleton_iff.mp hy
        exact ⟨0, 0, 1, by simp⟩
    | algebraMap a => exact ⟨a, 0, 0, by simp⟩
    | add x y _ _ hx hy =>
      obtain ⟨a, b, c, rfl⟩ := hx
      obtain ⟨d, e, f, rfl⟩ := hy
      exact ⟨a + d, b + e, c + f, by push_cast; ring⟩
    | mul x y _ _ hx hy =>
      obtain ⟨a, b, c, rfl⟩ := hx
      obtain ⟨d, e, f, rfl⟩ := hy
      refine ⟨a * d + 4 * b * f + 4 * c * e - 2 * c * f,
        a * e + b * d + b * e + b * f + c * e + 2 * c * f,
        a * f + c * d + 2 * b * e + c * f, ?_⟩
      push_cast
      linear_combination (b * e : 𝓞 K) * dedekindCubic_theta_sq hθ +
        (b * f + c * e : 𝓞 K) * dedekindCubic_theta_mul_beta hθ +
        (c * f : 𝓞 K) * dedekindCubic_beta_sq hθ
  · rintro ⟨a, b, c, rfl⟩
    exact add_mem (add_mem (Subalgebra.algebraMap_mem _ a)
      (mul_mem (Subalgebra.algebraMap_mem _ b) (Algebra.subset_adjoin (by simp))))
      (mul_mem (Subalgebra.algebraMap_mem _ c) (Algebra.subset_adjoin (by simp)))

/-- The underlying module of Dedekind's order is the span of `(1, θ, β)`. -/
theorem dedekindOrder_eq_span (hθ : θ ^ 3 - θ ^ 2 - 2 * θ - 8 = 0) :
    (dedekindOrder hθ).toSubmodule =
      Submodule.span ℤ (Set.range ![1, θ, dedekindBeta hθ]) := by
  ext x
  rw [Subalgebra.mem_toSubmodule, mem_dedekindOrder_iff,
    Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨a, b, c, rfl⟩
    exact ⟨![a, b, c], by simp [Fin.sum_univ_succ, zsmul_eq_mul, add_assoc]⟩
  · rintro ⟨a, ha⟩
    exact ⟨a 0, a 1, a 2, by simpa [Fin.sum_univ_succ, zsmul_eq_mul, add_assoc] using ha.symm⟩

end Order

variable {K : Type*} [Field K] [CharZero K] {θ : 𝓞 K}

/-- The three displayed integers in Dedekind's order are linearly independent over `ℤ`. -/
theorem linearIndependent_dedekindOrder
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8) :
    LinearIndependent ℤ ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] := by
  have hdegree : (minpoly ℚ (θ : K)).natDegree = 3 := by
    rw [minpoly.isIntegrallyClosed_eq_field_fractions' ℚ θ.isIntegral_coe,
      RingOfIntegers.minpoly_coe, Polynomial.Monic.natDegree_map
        (minpoly.monic θ.isIntegral), hmin]
    compute_degree <;> norm_num
  have hp := linearIndependent_pow (K := ℚ) (θ : K)
  rw [hdegree] at hp
  have hli : LinearIndependent ℚ
      ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] := by
    refine Fintype.linearIndependent_iff.mpr fun c hc i => ?_
    have hz : ∑ j : Fin 3, (![c 0, c 1 - c 2 / 2, c 2 / 2] j) •
        (θ : K) ^ (j : ℕ) = 0 := by
      simp [Fin.sum_univ_succ, Algebra.smul_def, coe_dedekindBeta] at hc ⊢
      linear_combination hc
    have h := Fintype.linearIndependent_iff.mp hp _ hz
    have h2 : c 2 = 0 := by simpa using h 2
    have h1 : c 1 = 0 := by simpa [h2] using h 1
    fin_cases i
    · exact h 0
    · exact h1
    · exact h2
  have hcomp : (IsScalarTower.toAlgHom ℤ (𝓞 K) K).toLinearMap ∘
      ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] =
      ![1, (θ : K), (dedekindBeta (dedekindCubic_relation hmin) : K)] := by
    ext i
    fin_cases i <;> simp
  rw [← hcomp] at hli
  exact (hli.restrict_scalars' ℤ).of_comp _

/-- The integral basis `(1, θ, β)` of Dedekind's order. -/
def dedekindOrderBasis
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8) :
    Basis (Fin 3) ℤ (dedekindOrder (dedekindCubic_relation hmin)) :=
  (Basis.span (linearIndependent_dedekindOrder hmin)).map
    ((LinearEquiv.ofEq _ _ (dedekindOrder_eq_span _).symm).trans
      (Subalgebra.toSubmoduleEquiv _))

/-- The basis vectors of Dedekind's order, viewed as algebraic integers. -/
@[simp] theorem coe_dedekindOrderBasis
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8) (i : Fin 3) :
    (dedekindOrderBasis hmin i : 𝓞 K) =
      ![1, θ, dedekindBeta (dedekindCubic_relation hmin)] i := by
  simp only [dedekindOrderBasis, Basis.map_apply, LinearEquiv.trans_apply,
    Subalgebra.toSubmoduleEquiv, Basis.span_apply]
  exact LinearEquiv.coe_ofEq_apply _ _

/-- The integral basis of Dedekind's order has discriminant `−503`.
This does not assume that the order is the full ring of integers. -/
theorem discr_dedekindOrder
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 - C 2 * X - C 8) :
    Algebra.discr ℤ (dedekindOrderBasis hmin) = -503 := by
  let b := dedekindOrderBasis hmin
  -- The columns record multiplication by `1`, `θ`, and `β` in the integral basis.
  let M : Fin 3 → Matrix (Fin 3) (Fin 3) ℤ :=
    ![1, !![0, 0, 4; 1, 1, 1; 0, 2, 0], !![0, 4, -2; 0, 1, 2; 1, 0, 1]]
  have hmul (i j : Fin 3) : b i * b j = b.equivFun.symm (fun k => M i k j) := by
    apply Subtype.ext
    simp only [Basis.equivFun_symm_apply, Fin.sum_univ_succ, Subalgebra.coe_add,
      Subalgebra.coe_smul, Subalgebra.coe_mul, b, coe_dedekindOrderBasis]
    fin_cases i <;> fin_cases j <;>
      simp [M, Matrix.one_apply,
        zsmul_eq_mul, ← pow_two, dedekindCubic_theta_sq (dedekindCubic_relation hmin),
        dedekindCubic_beta_sq, mul_comm] <;> ring
  have hM (i : Fin 3) : Algebra.leftMulMatrix b (b i) = M i := by
    ext j k
    rw [Algebra.leftMulMatrix_eq_repr_mul, hmul]
    exact congrFun (b.equivFun.apply_symm_apply _) j
  have htrace : Algebra.traceMatrix ℤ b = !![3, 1, 2; 1, 5, 13; 2, 13, -2] := by
    ext i j
    rw [Algebra.traceMatrix_apply, Algebra.traceForm_apply,
      Algebra.trace_eq_matrix_trace b, map_mul, hM, hM]
    fin_cases i <;> fin_cases j <;>
      norm_num [M, Matrix.trace, Matrix.mul_apply, Fin.sum_univ_succ]
  rw [Algebra.discr_def, htrace]
  norm_num [Matrix.det_fin_three]

end TauCeti.NumberField
