/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.Spin.SpinorNorm.Basic
public import TauCeti.LinearAlgebra.QuadraticForm.Transvection

/-!
# Spin lifts of Eichler transvections

Let `u` be an isotropic vector of a quadratic form `Q` and `w` a vector orthogonal to it. The
Eichler transvection `E_{u,w}` (`QuadraticMap.transvection`) is a proper isometry of `Q`. It has a
canonical lift to the Spin group, written down inside the even Clifford algebra:

`L_{u,w} = 1 + ι w * ι u`.

Since `u` is isotropic and orthogonal to `w`, the element `ι w * ι u` squares to zero, so
`L_{u,w}` is a unit with inverse `1 - ι w * ι u`. Conjugation by it is exactly `E_{u,w}` on the
vectors, with no sign. Moreover `w ↦ L_{u,w}` turns addition into multiplication and kills
`K ∙ u`. So the lifts form a homomorphism from the additive group of `u^⊥ / K ∙ u` into the Spin
group, lifting `QuadraticMap.transvectionHom` along `CliffordAlgebra.spinToSpecialOrthogonal`.
These form a unipotent subgroup of the Spin group. In particular every Eichler
transvection lies in the image of Spin, so its spinor norm is trivial.

The lift is stated over a field with `2` invertible and for a nondegenerate form, with no finite
dimensionality assumed except for the spinor-norm corollaries. Nondegeneracy is what puts
`1 + ι w * ι u` in Mathlib's `lipschitzGroup`, which is generated by the vectors of invertible
norm. It cannot be dropped: for `Q = 0` the Lipschitz group is trivial, while `1 + ι w * ι u` is a
nontrivial unit as soon as `u` and `w` are linearly independent.

## Main definitions

* `CliffordAlgebra.spinTransvection hQ hu huw`: the Spin element `1 + ι w * ι u` lifting
  `E_{u,w}`.
* `CliffordAlgebra.spinTransvectionHom hQ hu`: the homomorphism `w ↦ L_{u,w}` from the additive
  group of `u^⊥ / K ∙ u` into the Spin group.

## Main results

* `CliffordAlgebra.coe_spinToSpecialOrthogonal_spinTransvection`: the lift acts on the quadratic
  space as the Eichler transvection `E_{u,w}`.
* `CliffordAlgebra.spinTransvection_add`: `L_{u,w + w'} = L_{u,w} * L_{u,w'}`.
* `CliffordAlgebra.spinTransvection_eq_one_iff`: for `u ≠ 0`, `L_{u,w} = 1` exactly when
  `w ∈ K ∙ u`.
* `CliffordAlgebra.spinToSpecialOrthogonal_comp_spinTransvectionHom`: the lifts lift
  `QuadraticMap.transvectionHom`.
* `CliffordAlgebra.spinTransvectionHom_injective`: for `u ≠ 0` the lifts form a copy of
  `u^⊥ / K ∙ u` inside the Spin group.
* `CliffordAlgebra.spinorNorm_transvection` and `CliffordAlgebra.orthogonalSpinorNorm_transvection`:
  Eichler transvections have trivial spinor norm.

## References

* M. Eichler, *Quadratische Formen und orthogonale Gruppen*, Springer (1952).
-/
public section

open QuadraticMap TauCeti.QuadraticMap

namespace CliffordAlgebra

universe u v

section CommRing

variable {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
  {Q : QuadraticForm R M} {u w w' : M}

/-- If `u` is isotropic and orthogonal to `w'`, then `(ι w * ι u) * (ι w' * ι u) = 0`. -/
private theorem ι_mul_ι_mul_ι_mul_ι_eq_zero (w : M) (hu : Q u = 0) (huw' : polar Q u w' = 0) :
    ι Q w * ι Q u * (ι Q w' * ι Q u) = 0 := by
  rw [mul_ι_mul_ι_mul_comm, huw', ι_sq_scalar, hu]
  simp

/-- The element `1 + ι w * ι u` is a unit with inverse `1 - ι w * ι u`. -/
private def transvectionUnit (hu : Q u = 0) (huw : polar Q u w = 0) : (CliffordAlgebra Q)ˣ where
  val := 1 + ι Q w * ι Q u
  inv := 1 - ι Q w * ι Q u
  val_inv := by
    rw [add_mul, one_mul, mul_sub, mul_one, ι_mul_ι_mul_ι_mul_ι_eq_zero w hu huw]
    abel
  inv_val := by
    rw [sub_mul, one_mul, mul_add, mul_one, ι_mul_ι_mul_ι_mul_ι_eq_zero w hu huw]
    abel

private theorem coe_transvectionUnit (hu : Q u = 0) (huw : polar Q u w = 0) :
    (transvectionUnit hu huw : CliffordAlgebra Q) = 1 + ι Q w * ι Q u := (rfl)

/-- Conjugation by `1 + ι w * ι u` acts on vectors as the Eichler transvection `E_{u,w}`. -/
private theorem transvection_conj_ι (hu : Q u = 0) (huw : polar Q u w = 0) (x : M) :
    (1 + ι Q w * ι Q u) * ι Q x * (1 - ι Q w * ι Q u) = ι Q (transvection Q hu huw x) := by
  have hUX : ι Q u * ι Q x = polar Q x u • 1 - ι Q x * ι Q u := by
    rw [ι_mul_ι_comm, polar_comm, Algebra.algebraMap_eq_smul_one]
  have hWX : ι Q w * ι Q x = polar Q x w • 1 - ι Q x * ι Q w := by
    rw [ι_mul_ι_comm, polar_comm, Algebra.algebraMap_eq_smul_one]
  have hUW : ι Q u * ι Q w = -(ι Q w * ι Q u) := by
    rw [ι_mul_ι_comm, huw, map_zero, zero_sub]
  have hUU : ι Q u * ι Q u = 0 := by rw [ι_sq_scalar, hu, map_zero]
  -- Moving `ι x` to the left of `N = ι w * ι u` produces the first-order terms of `E_{u,w}`.
  have hNX : ι Q w * ι Q u * ι Q x =
      ι Q x * (ι Q w * ι Q u) + polar Q x u • ι Q w - polar Q x w • ι Q u := by
    rw [mul_assoc, hUX, mul_sub, mul_smul_comm, mul_one, ← mul_assoc, hWX, sub_mul,
      smul_mul_assoc, one_mul, mul_assoc]
    abel
  have hNN := ι_mul_ι_mul_ι_mul_ι_eq_zero (Q := Q) w hu huw
  have hWN : ι Q w * (ι Q w * ι Q u) = Q w • ι Q u := by
    rw [← mul_assoc, ι_sq_scalar, Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
  have hUN : ι Q u * (ι Q w * ι Q u) = 0 := by
    rw [← mul_assoc, hUW, neg_mul, mul_assoc, hUU, mul_zero, neg_zero]
  calc (1 + ι Q w * ι Q u) * ι Q x * (1 - ι Q w * ι Q u)
      = ι Q x + ι Q w * ι Q u * ι Q x - ι Q x * (ι Q w * ι Q u) -
          ι Q w * ι Q u * ι Q x * (ι Q w * ι Q u) := by noncomm_ring
    _ = ι Q (transvection Q hu huw x) := by
      rw [hNX, sub_mul, add_mul, mul_assoc, hNN, smul_mul_assoc, smul_mul_assoc, hWN, hUN,
        transvection_apply]
      simp only [map_add, map_sub, map_smul, mul_zero, smul_zero]
      module

/-- The lifts compose additively in `w`:
`(1 + ι w * ι u) * (1 + ι w' * ι u) = 1 + ι (w + w') * ι u`. -/
private theorem one_add_ι_mul_ι_mul_one_add_ι_mul_ι (w : M) (hu : Q u = 0)
    (huw' : polar Q u w' = 0) :
    (1 + ι Q w * ι Q u) * (1 + ι Q w' * ι Q u) = 1 + ι Q (w + w') * ι Q u := by
  rw [mul_add, mul_one, add_mul, one_mul, ι_mul_ι_mul_ι_mul_ι_eq_zero w hu huw', map_add, add_mul]
  abel

/-- The Clifford conjugate of `1 + ι w * ι u` is `1 - ι w * ι u`. -/
private theorem star_one_add_ι_mul_ι (huw : polar Q u w = 0) :
    star (1 + ι Q w * ι Q u) = 1 - ι Q w * ι Q u := by
  rw [star_add, star_one, star_mul, star_ι, star_ι, neg_mul_neg, ι_mul_ι_comm, huw, map_zero,
    zero_sub, sub_eq_add_neg]

/-- If `Q w` is a unit, then `1 + ι w * ι u = ι ((Q w)⁻¹ • w) * ι (w + Q w • u)` is a product of
two vectors of invertible norm, so it lies in the Lipschitz group. -/
private theorem transvectionUnit_mem_lipschitzGroup_of_isUnit (hu : Q u = 0)
    (huw : polar Q u w = 0) (hw : IsUnit (Q w)) :
    transvectionUnit hu huw ∈ lipschitzGroup Q := by
  set c : R := ↑hw.unit⁻¹
  have hc : c * Q w = 1 := hw.val_inv_mul
  refine mem_lipschitzGroup_of_coe_eq_prod_map_ι [c • w, w + Q w • u] ?_ ?_
  · simp only [List.mem_cons, List.not_mem_nil, or_false, forall_eq_or_imp, forall_eq]
    refine ⟨isUnit_apply_smul (hw.unit⁻¹).isUnit hw, ?_⟩
    rwa [QuadraticMap.map_add Q, QuadraticMap.map_smul, hu, polar_smul_right, polar_comm, huw,
      smul_zero, add_zero, smul_zero, add_zero]
  · simp only [coe_transvectionUnit, List.map_cons, List.map_nil, List.prod_cons, List.prod_nil,
      mul_one, map_add, map_smul, mul_add, mul_smul_comm, smul_mul_assoc, ι_sq_scalar,
      Algebra.algebraMap_eq_smul_one, smul_smul, hc, one_smul]
    rw [mul_comm, hc, one_smul]

end CommRing

section Field

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V] [Invertible (2 : K)]
  {Q : QuadraticForm K V} {u w w' : V}

/-- Over a field with `2 ≠ 0`, for a nondegenerate form, `1 + ι w * ι u` lies in the Lipschitz
group. -/
private theorem transvectionUnit_mem_lipschitzGroup (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) : transvectionUnit hu huw ∈ lipschitzGroup Q := by
  -- If `Q w ≠ 0`, the lift is a product of two vectors. If `Q w = 0` and some `x ⊥ u` has
  -- `polar Q w x = b ≠ 0`, then `a = x + ((b - Q x) / b) • w` is orthogonal to `u` with `Q a = b`
  -- and `Q (w + a) = 2 * b`, and the lift of `w` is the product of the lifts of `w + a` and `-a`.
  -- Otherwise nondegeneracy forces `w ∈ K ∙ u`, and the lift is `1`.
  by_cases hw : Q w = 0
  swap
  · exact transvectionUnit_mem_lipschitzGroup_of_isUnit hu huw (Ne.isUnit hw)
  by_cases hx : ∃ x, polar Q u x = 0 ∧ polar Q w x ≠ 0
  · obtain ⟨x, hux, hb⟩ := hx
    set b := polar Q w x
    set a := x + ((b - Q x) / b) • w
    have hua : polar Q u a = 0 := by simp [a, polar_add_right, polar_smul_right, hux, huw]
    have hQa : Q a = b := by
      simp only [a, QuadraticMap.map_add, QuadraticMap.map_smul, hw, polar_smul_right,
        polar_comm Q x w, smul_eq_mul, mul_zero, add_zero]
      field_simp
      ring
    have hQwa : Q (w + a) = 2 * b := by
      simp only [a, QuadraticMap.map_add Q w, hQa, hw, polar_add_right, polar_smul_right,
        polar_self, smul_zero, add_zero, zero_add, b]
      ring
    have hsplit : transvectionUnit hu huw =
        transvectionUnit (w := w + a) hu (by rw [polar_add_right, huw, hua, add_zero]) *
          transvectionUnit (w := -a) hu (by rw [polar_neg_right, hua, neg_zero]) := by
      ext
      rw [Units.val_mul, coe_transvectionUnit, coe_transvectionUnit, coe_transvectionUnit,
        one_add_ι_mul_ι_mul_one_add_ι_mul_ι _ hu (by rw [polar_neg_right, hua, neg_zero]),
        add_neg_cancel_right]
    rw [hsplit]
    refine mul_mem (transvectionUnit_mem_lipschitzGroup_of_isUnit _ _ ?_)
      (transvectionUnit_mem_lipschitzGroup_of_isUnit _ _ ?_)
    · rw [hQwa]
      exact (isUnit_of_invertible 2).mul (Ne.isUnit hb)
    · rw [QuadraticMap.map_neg, hQa]
      exact Ne.isUnit hb
  -- Every vector orthogonal to `u` is orthogonal to `w`, so `polar Q w` is a multiple of
  -- `polar Q u`, and nondegeneracy gives `w ∈ K ∙ u`.
  push Not at hx
  have hker : ⨅ _ : Unit, LinearMap.ker (Q.polarBilin u) ≤ LinearMap.ker (Q.polarBilin w) := by
    intro x hx'
    simp only [Submodule.mem_iInf, LinearMap.mem_ker, polarBilin_apply_apply] at hx' ⊢
    exact hx x (hx' ())
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (by
    simpa using mem_span_of_iInf_ker_le_ker hker)
  have hrad : w - c • u ∈ Q.radical := by
    rw [radical_eq_ker_polarBilin, LinearMap.mem_ker, map_sub, map_smul, ← hc, sub_self]
  rw [hQ.radical_eq_bot, Submodule.mem_bot, sub_eq_zero] at hrad
  have hone : transvectionUnit hu huw = 1 := by
    ext
    simp [coe_transvectionUnit, hrad, ι_sq_scalar, hu]
  rw [hone]
  exact one_mem _

/-- **The canonical Spin lift of an Eichler transvection**: for an isotropic vector `u` and a
vector `w` orthogonal to it, the element `L_{u,w} = 1 + ι w * ι u` of the Spin group of a
nondegenerate form. It acts on the quadratic space as the Eichler transvection `E_{u,w}`
(`coe_spinToSpecialOrthogonal_spinTransvection`). -/
def spinTransvection (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0) :
    spinGroup Q :=
  ⟨1 + ι Q w * ι Q u, spinGroup.mem_iff.mpr
    ⟨pinGroup.mem_iff.mpr
      ⟨⟨transvectionUnit hu huw, transvectionUnit_mem_lipschitzGroup hQ hu huw, rfl⟩,
        Unitary.mem_iff.mpr
          ⟨by rw [star_one_add_ι_mul_ι huw]; exact (transvectionUnit hu huw).inv_val,
            by rw [star_one_add_ι_mul_ι huw]; exact (transvectionUnit hu huw).val_inv⟩⟩,
      add_mem (one_mem _) (by
        rw [← Subalgebra.mem_toSubmodule, even_toSubmodule]
        exact ι_mul_ι_mem_evenOdd_zero Q w u)⟩⟩

/-- The Spin lift of `E_{u,w}` is the Clifford element `1 + ι w * ι u`. -/
@[simp]
theorem coe_spinTransvection (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0) :
    (spinTransvection hQ hu huw : CliffordAlgebra Q) = 1 + ι Q w * ι Q u := (rfl)

/-- The Spin lifts of the Eichler transvections with a fixed isotropic vector `u` compose
additively in `w`. -/
@[simp]
theorem spinTransvection_add (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0)
    (huw' : polar Q u w' = 0) :
    spinTransvection hQ (w := w + w') hu (by simp [huw, huw']) =
      spinTransvection hQ hu huw * spinTransvection hQ hu huw' := by
  apply Subtype.ext
  rw [Submonoid.coe_mul, coe_spinTransvection, coe_spinTransvection, coe_spinTransvection,
    one_add_ι_mul_ι_mul_one_add_ι_mul_ι w hu huw']

/-- The Spin lift of `E_{u,w}` is trivial when `w` is a multiple of `u`. -/
@[simp]
theorem spinTransvection_eq_one_of_mem_span (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) (hw : w ∈ K ∙ u) : spinTransvection hQ hu huw = 1 := by
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.mp hw
  apply Subtype.ext
  simp [ι_sq_scalar, hu]

/-- The inverse of the Spin lift of `E_{u,w}` is the Spin lift of `E_{u,-w}`. -/
@[simp]
theorem spinTransvection_neg (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0) :
    spinTransvection hQ (w := -w) hu (by simpa using huw) = (spinTransvection hQ hu huw)⁻¹ := by
  refine eq_inv_of_mul_eq_one_left ?_
  rw [← spinTransvection_add hQ hu (by simpa using huw) huw]
  exact spinTransvection_eq_one_of_mem_span hQ hu _ (by simp)

/-- The Spin lift of `E_{u,w}` depends on `w` only through its class modulo `K ∙ u`. -/
-- `spinTransvection_add` simplifies the left-hand side first, so `simpNF` rejects `@[simp]` here.
theorem spinTransvection_add_smul (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0)
    (c : K) :
    spinTransvection hQ (w := w + c • u) hu (by simp [polar_self, hu, huw]) =
      spinTransvection hQ hu huw := by
  have hcu : polar Q u (c • u) = 0 := by simp [polar_self, hu]
  rw [spinTransvection_add hQ hu huw hcu, spinTransvection_eq_one_of_mem_span hQ hu hcu
    (Submodule.smul_mem _ c (Submodule.mem_span_singleton_self u)), mul_one]

/-- **The Spin lift of `E_{u,w}` acts on the quadratic space as `E_{u,w}`.** -/
@[simp]
theorem coe_spinToSpecialOrthogonal_spinTransvection (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) :
    ((spinToSpecialOrthogonal Q (spinTransvection hQ hu huw) : specialOrthogonalGroup Q) :
      V ≃ₗ[K] V) = transvection Q hu huw := by
  ext x
  apply ι_injective Q
  rw [coe_spinToSpecialOrthogonal_apply, ι_spinVectorAction_apply, coe_spinTransvection,
    star_one_add_ι_mul_ι huw, transvection_conj_ι]

/-- The Spin lift of `E_{u,w}` maps to `E_{u,w}` in `SO(Q)`. -/
-- The coercion theorem above is already a simp normal form, so `simpNF` rejects `@[simp]` here.
theorem spinToSpecialOrthogonal_spinTransvection (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) :
    spinToSpecialOrthogonal Q (spinTransvection hQ hu huw) =
      ⟨transvection Q hu huw, transvection_mem_specialOrthogonalGroup hu huw⟩ :=
  Subtype.ext (coe_spinToSpecialOrthogonal_spinTransvection hQ hu huw)

/-- For `u ≠ 0`, the Spin lift of `E_{u,w}` is trivial exactly when `w` is a multiple of `u`. -/
@[simp]
theorem spinTransvection_eq_one_iff (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) (hu₀ : u ≠ 0) : spinTransvection hQ hu huw = 1 ↔ w ∈ K ∙ u := by
  refine ⟨fun h => ?_, spinTransvection_eq_one_of_mem_span hQ hu huw⟩
  rw [← transvection_eq_one_iff hu huw (hQ.polarBilin_ne_zero hu₀),
    ← coe_spinToSpecialOrthogonal_spinTransvection hQ hu huw, h, map_one, OneMemClass.coe_one]

/-- The Spin lifts with isotropic vector `u`, as a homomorphism out of the vectors orthogonal to
`u`. It descends to `u^⊥ / K ∙ u` as `spinTransvectionHom`. -/
private def spinTransvectionAddHom (hQ : Q.Nondegenerate) (hu : Q u = 0) :
    LinearMap.ker (Q.polarBilin u) →+ Additive (spinGroup Q) :=
  AddMonoidHom.mk' (fun w => Additive.ofMul (spinTransvection hQ hu (LinearMap.mem_ker.mp w.2)))
    fun w w' => by
      rw [← ofMul_mul, ← spinTransvection_add hQ hu (LinearMap.mem_ker.mp w.2)
        (LinearMap.mem_ker.mp w'.2)]

private theorem spinTransvectionAddHom_apply (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (w : LinearMap.ker (Q.polarBilin u)) :
    Additive.toMul (spinTransvectionAddHom hQ hu w) =
      spinTransvection hQ hu (LinearMap.mem_ker.mp w.2) := by
  rw [spinTransvectionAddHom, AddMonoidHom.mk'_apply, toMul_ofMul]

/-- **The Spin lifts of the Eichler transvections with a fixed isotropic vector `u`**, as a
homomorphism `w ↦ L_{u,w}` from the additive group of `u^⊥ / K ∙ u` into the Spin group. It lifts
`QuadraticMap.transvectionHom` (`spinToSpecialOrthogonal_comp_spinTransvectionHom`) and is
injective for `u ≠ 0` (`spinTransvectionHom_injective`). -/
noncomputable def spinTransvectionHom (hQ : Q.Nondegenerate) (hu : Q u = 0) :
    (LinearMap.ker (Q.polarBilin u) ⧸
        (K ∙ u).comap (LinearMap.ker (Q.polarBilin u)).subtype) →+
      Additive (spinGroup Q) :=
  QuotientAddGroup.lift _ (spinTransvectionAddHom hQ hu) fun w hw => by
    have hw' : (w : V) ∈ K ∙ u := hw
    apply Additive.toMul.injective
    rw [toMul_zero, spinTransvectionAddHom_apply]
    exact spinTransvection_eq_one_of_mem_span hQ hu _ hw'

/-- The quotient homomorphism sends the class of `w` to the Spin lift `L_{u,w}`. -/
@[simp]
theorem toMul_spinTransvectionHom_mk (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) :
    Additive.toMul (spinTransvectionHom hQ hu (Submodule.Quotient.mk ⟨w, by simpa using huw⟩)) =
      spinTransvection hQ hu huw :=
  -- `Submodule.Quotient.mk` is the additive quotient map, on which `QuotientAddGroup.lift`
  -- computes by definition.
  spinTransvectionAddHom_apply hQ hu _

/-- **The Spin lifts lift the Eichler transvections**: followed by the projection
`Spin(Q) → SO(Q)`, the homomorphism `w ↦ L_{u,w}` is `w ↦ E_{u,w}`. -/
theorem spinToSpecialOrthogonal_comp_spinTransvectionHom (hQ : Q.Nondegenerate) (hu : Q u = 0) :
    (spinToSpecialOrthogonal Q).toAdditive.comp (spinTransvectionHom hQ hu) =
      transvectionHom Q hu := by
  refine AddMonoidHom.ext fun q => ?_
  induction q using Submodule.Quotient.induction_on with | H w => ?_
  obtain ⟨w, hw⟩ := w
  have huw : polar Q u w = 0 := by simpa using hw
  apply Additive.toMul.injective
  apply Subtype.ext
  rw [AddMonoidHom.comp_apply, MonoidHom.toAdditive_apply_apply, toMul_ofMul,
    toMul_spinTransvectionHom_mk hQ hu huw, coe_spinToSpecialOrthogonal_spinTransvection,
    coe_transvectionHom_mk hu huw]

/-- For `u ≠ 0`, the Spin lifts of the Eichler transvections with isotropic vector `u` form a copy
of the additive group `u^⊥ / K ∙ u` inside the Spin group. -/
theorem spinTransvectionHom_injective (hQ : Q.Nondegenerate) (hu : Q u = 0) (hu₀ : u ≠ 0) :
    Function.Injective (spinTransvectionHom hQ hu) := by
  refine Function.Injective.of_comp (f := (spinToSpecialOrthogonal Q).toAdditive) ?_
  rw [← AddMonoidHom.coe_comp, spinToSpecialOrthogonal_comp_spinTransvectionHom]
  exact transvectionHom_injective hu (hQ.polarBilin_ne_zero hu₀)

variable [FiniteDimensional K V]

/-- **An Eichler transvection has trivial spinor norm**: it is the image of its Spin lift. -/
-- `spinorNorm_apply` simplifies the left-hand side first, so `simpNF` rejects `@[simp]` here.
theorem spinorNorm_transvection (hQ : Q.Nondegenerate) (hu : Q u = 0) (huw : polar Q u w = 0) :
    spinorNorm Q hQ ⟨transvection Q hu huw, transvection_mem_specialOrthogonalGroup hu huw⟩ =
      1 := by
  rw [← spinToSpecialOrthogonal_spinTransvection hQ hu huw, spinorNorm_spinToSpecialOrthogonal]

/-- An Eichler transvection has trivial spinor norm as an element of `O(Q)`. -/
@[simp]
theorem orthogonalSpinorNorm_transvection (hQ : Q.Nondegenerate) (hu : Q u = 0)
    (huw : polar Q u w = 0) :
    orthogonalSpinorNorm Q hQ ⟨transvection Q hu huw, transvection_mem_orthogonalGroup hu huw⟩ =
      1 := by
  have h : _root_.QuadraticMap.specialOrthogonalToOrthogonal Q
      ⟨transvection Q hu huw, transvection_mem_specialOrthogonalGroup hu huw⟩ =
        ⟨transvection Q hu huw, transvection_mem_orthogonalGroup hu huw⟩ :=
    Subtype.ext (_root_.QuadraticMap.coe_specialOrthogonalToOrthogonal _)
  rw [← h, ← spinorNorm_apply, spinorNorm_transvection]

end Field

end CliffordAlgebra
