/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Abelian
public import Mathlib.Algebra.Lie.IdealOperations
public import Mathlib.LinearAlgebra.FiniteDimensional.Defs
public import Mathlib.LinearAlgebra.Basis.Basic

/-!
# Basic infrastructure for Lie modules

This file supplies general constructions for Lie modules that are missing from Mathlib.

## Main definitions

* `TauCeti.LieModuleEquiv.ofBijective`: a bijective morphism of Lie modules is an equivalence.
* `TauCeti.LieModuleEquiv.restrictLie`: an equivalence of Lie modules over a Lie algebra, read as
  one over a Lie subalgebra.
* `TauCeti.LieModuleEquiv.congrRight` and `TauCeti.LieModuleEquiv.congrLeft`: postcomposition and
  precomposition with an equivalence of Lie modules, as linear equivalences of morphism spaces.
* `TauCeti.lieAnnihilator`: the Lie subalgebra of elements annihilating a vector in a Lie
  module.

## Main results

* `Module.Basis.repr_lie_eq_sum`: a Lie bracket coordinate is a weighted sum of bracket columns.

* `TauCeti.LieModuleHom.instFiniteDimensional`: the morphism space of two finite-dimensional Lie
  modules is finite-dimensional.
* `TauCeti.mem_lieAnnihilator`: membership in `lieAnnihilator R L v` is equivalent to vanishing
  of the Lie action on `v`.
* `LieHom.map_ad_pow`: a Lie homomorphism carries `(ad x) ^ n y` to `(ad (f x)) ^ n (f y)`.
* `LieSubmodule.lie_iSup`: bracketing with a Lie ideal distributes over suprema of Lie submodules.
* `TauCeti.ad_pow_apply_eq_ad_pow_apply`: iterating the adjoint action gives the same element
  whichever base ring the Lie algebra is read over.
* `TauCeti.isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top`: a Lie module generated by
  a vector annihilated by the Lie algebra is trivial.
-/

public section

namespace TauCeti

universe u v w w₁ w₂

variable {R : Type u} {L : Type v} {M : Type w} {N : Type w₁}
variable [CommRing R] [LieRing L] [AddCommGroup M] [Module R M] [LieRingModule L M]
  [AddCommGroup N] [Module R N] [LieRingModule L N]

namespace LieModuleEquiv

/-- A bijective morphism of Lie modules is an equivalence of Lie modules. This is the Lie module
analogue of `LieEquiv.ofBijective`. -/
noncomputable def ofBijective (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) : M ≃ₗ⁅R,L⁆ N :=
  { LinearEquiv.ofBijective (f : M →ₗ[R] N) hf with
    toFun := f
    map_lie' := f.map_lie _ _ }

@[simp]
theorem ofBijective_apply (f : M →ₗ⁅R,L⁆ N) (hf : Function.Bijective f) (m : M) :
    ofBijective f hf m = f m := by
  -- `LieModuleEquiv` has no projection lemma exposing the underlying `LinearEquiv`, so reveal that
  -- representation boundary before applying the corresponding linear-equivalence interface lemma.
  change (LinearEquiv.ofBijective (f : M →ₗ[R] N) hf) m = f m
  exact LinearEquiv.ofBijective_apply _ _

/-- **An equivalence of `L`-modules is an equivalence of `L'`-modules** for a Lie subalgebra
`L' ≤ L`, with the same underlying map. This is Mathlib's `LieModuleHom.restrictLie` for
equivalences. -/
noncomputable def restrictLie [LieAlgebra R L] (e : M ≃ₗ⁅R,L⁆ N) (L' : LieSubalgebra R L) :
    M ≃ₗ⁅R,L'⁆ N :=
  ofBijective ((e : M →ₗ⁅R,L⁆ N).restrictLie L') ⟨e.injective, e.surjective⟩

@[simp]
theorem coe_restrictLie [LieAlgebra R L] (e : M ≃ₗ⁅R,L⁆ N) (L' : LieSubalgebra R L) :
    ⇑(restrictLie e L') = e := by
  funext m
  refine (ofBijective_apply ((e : M →ₗ⁅R,L⁆ N).restrictLie L') _ m).trans ?_
  rw [LieModuleHom.coe_restrictLie]
  rfl

section CongrRight

variable {P : Type w₂} [AddCommGroup P] [Module R P] [LieRingModule L P]
variable [LieAlgebra R L] [LieModule R L M] [LieModule R L N] [LieModule R L P]

/-- **Postcomposition with an equivalence of Lie modules**, as an `R`-linear equivalence
`(M →ₗ⁅R,L⁆ N) ≃ₗ[R] (M →ₗ⁅R,L⁆ P)` of morphism spaces. This is the Lie-module analogue of
`LinearEquiv.congrRight`, which is unavailable here because a `LieModuleHom` is not a
`LinearMap`. -/
def congrRight (e : N ≃ₗ⁅R,L⁆ P) : (M →ₗ⁅R,L⁆ N) ≃ₗ[R] (M →ₗ⁅R,L⁆ P) where
  toFun f := (e : N →ₗ⁅R,L⁆ P).comp f
  invFun g := (e.symm : P →ₗ⁅R,L⁆ N).comp g
  map_add' _ _ := by ext m; simp
  map_smul' _ _ := by ext m; simp
  left_inv f := by ext m; simp
  right_inv g := by ext m; simp

omit [LieModule R L M] in
@[simp]
theorem congrRight_apply (e : N ≃ₗ⁅R,L⁆ P) (f : M →ₗ⁅R,L⁆ N) (m : M) :
    congrRight (M := M) e f m = e (f m) :=
  (rfl)

omit [LieModule R L M] in
@[simp]
theorem congrRight_symm_apply (e : N ≃ₗ⁅R,L⁆ P) (g : M →ₗ⁅R,L⁆ P) (m : M) :
    (congrRight (M := M) e).symm g m = e.symm (g m) :=
  (rfl)

end CongrRight

section CongrLeft

variable {P : Type w₂} [AddCommGroup P] [Module R P] [LieRingModule L P]
variable [LieAlgebra R L] [LieModule R L M] [LieModule R L N] [LieModule R L P]

omit [LieModule R L M] [LieModule R L N] in
/-- **Precomposition with an equivalence of Lie modules**, as an `R`-linear equivalence
`(M →ₗ⁅R,L⁆ P) ≃ₗ[R] (N →ₗ⁅R,L⁆ P)` of morphism spaces. This is the source-variable companion of
`TauCeti.LieModuleEquiv.congrRight`. -/
def congrLeft (e : M ≃ₗ⁅R,L⁆ N) : (M →ₗ⁅R,L⁆ P) ≃ₗ[R] (N →ₗ⁅R,L⁆ P) where
  toFun f := f.comp (e.symm : N →ₗ⁅R,L⁆ M)
  invFun g := g.comp (e : M →ₗ⁅R,L⁆ N)
  map_add' _ _ := by ext n; simp
  map_smul' _ _ := by ext n; simp
  left_inv f := by ext m; simp
  right_inv g := by ext n; simp

omit [LieModule R L M] [LieModule R L N] in
@[simp]
theorem congrLeft_apply (e : M ≃ₗ⁅R,L⁆ N) (f : M →ₗ⁅R,L⁆ P) (n : N) :
    congrLeft (P := P) e f n = f (e.symm n) :=
  (rfl)

omit [LieModule R L M] [LieModule R L N] in
@[simp]
theorem congrLeft_symm_apply (e : M ≃ₗ⁅R,L⁆ N) (g : N →ₗ⁅R,L⁆ P) (m : M) :
    (congrLeft (P := P) e).symm g m = g (e m) :=
  (rfl)

end CongrLeft

end LieModuleEquiv

namespace LieModuleHom

/-! ### Morphism spaces of Lie modules -/

/-- The morphism space of two finite-dimensional Lie modules is finite-dimensional: by
`LieModule.maxTrivLinearMapEquivLieModuleHom` it is the maximal trivial submodule of the
finite-dimensional space of all linear maps between them. -/
instance instFiniteDimensional {K : Type u} {L : Type v} {M : Type w} {N : Type w₁}
    [Field K] [LieRing L] [LieAlgebra K L]
    [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M] [FiniteDimensional K M]
    [AddCommGroup N] [Module K N] [LieRingModule L N] [LieModule K L N]
    [FiniteDimensional K N] :
    FiniteDimensional K (M →ₗ⁅K,L⁆ N) :=
  Module.Finite.equiv (LieModule.maxTrivLinearMapEquivLieModuleHom (R := K) (L := L)
    (M := M) (N := N))

end LieModuleHom

variable [LieAlgebra R L] [LieModule R L M]

omit [LieModule R L M] in
/-- Bracketing with a Lie ideal distributes over suprema of Lie submodules. -/
theorem _root_.LieSubmodule.lie_iSup {ι : Type*} (I : LieIdeal R L)
    (N : ι → LieSubmodule R L M) : ⁅I, ⨆ i, N i⁆ = ⨆ i, ⁅I, N i⁆ := by
  refine le_antisymm ?_ (iSup_le fun i ↦ LieSubmodule.mono_lie_right _ (le_iSup N i))
  rw [LieSubmodule.lie_le_iff]
  intro x hx m hm
  refine LieSubmodule.iSup_induction N (motive := fun y ↦ ⁅x, y⁆ ∈ ⨆ i, ⁅I, N i⁆) hm
    (fun i y hy ↦ ?_) (by simp) (fun y z hy hz ↦ ?_)
  · exact LieSubmodule.mem_iSup_of_mem i (LieSubmodule.lie_mem_lie hx hy)
  · rw [lie_add]
    exact add_mem hy hz

section Annihilator

variable (R L)

/-- The elements of `L` annihilating a fixed vector `v` form a Lie subalgebra: the bracket is
linear in its left argument, and the Leibniz rule `lie_lie` closes the set under brackets. -/
def lieAnnihilator (v : M) : LieSubalgebra R L where
  carrier := {x : L | ⁅x, v⁆ = 0}
  add_mem' {x y} hx hy := by
    simp only [Set.mem_ofPred_eq] at hx hy ⊢
    rw [add_lie, hx, hy, add_zero]
  zero_mem' := by
    simp only [Set.mem_ofPred_eq]
    rw [zero_lie]
  smul_mem' c x hx := by
    simp only [Set.mem_ofPred_eq] at hx ⊢
    rw [smul_lie, hx, smul_zero]
  lie_mem' {x y} hx hy := by
    simp only [Set.mem_ofPred_eq] at hx hy ⊢
    rw [lie_lie, hx, hy, lie_zero, lie_zero, sub_zero]

/-- Membership in the annihilator of a vector is exactly vanishing of the Lie action. -/
@[simp]
theorem mem_lieAnnihilator {v : M} {x : L} :
    x ∈ lieAnnihilator R L v ↔ ⁅x, v⁆ = 0 :=
  Iff.rfl

end Annihilator

/-- A Lie module generated by a vector annihilated by every element of the Lie algebra is
trivial. -/
theorem isTrivial_of_forall_lie_eq_zero_of_lieSpan_eq_top {v : M}
    (h : ∀ x : L, ⁅x, v⁆ = 0) (hgen : LieSubmodule.lieSpan R L {v} = ⊤) :
    _root_.LieModule.IsTrivial L M := by
  refine (_root_.LieModule.isTrivial_iff_max_triv_eq_top
    (R := R) (L := L) (M := M)).mpr ?_
  apply eq_top_iff.mpr
  rw [← hgen, LieSubmodule.lieSpan_le]
  exact Set.singleton_subset_iff.mpr
    ((_root_.LieModule.mem_maxTrivSubmodule R L M v).mpr h)

/-- **The adjoint action does not depend on the base ring.** A Lie algebra over two commutative
rings has one bracket, so iterating `ad` over either ring gives the same element. This reads a
higher Serre relation proved over `ℤ` as the relation asked of a Lie algebra over `ℚ`. -/
theorem ad_pow_apply_eq_ad_pow_apply {L : Type*} [LieRing L] (R S : Type*) [CommRing R]
    [CommRing S] [LieAlgebra R L] [LieAlgebra S L] (x y : L) (k : ℕ) :
    (LieAlgebra.ad R L x ^ k) y = (LieAlgebra.ad S L x ^ k) y := by
  induction k generalizing y with
  | zero => simp
  | succ k ih =>
      simp only [pow_succ, Module.End.mul_apply, LieAlgebra.ad_apply]
      exact ih ⁅x, y⁆

/-- **A Lie homomorphism carries the iterated adjoint action.** `f ((ad x) ^ n y)` is
`(ad (f x)) ^ n (f y)`; relations of the form `(ad x) ^ n y = 0`, such as
Serre's, are transported along a homomorphism by this. -/
@[simp]
theorem _root_.LieHom.map_ad_pow {R L L' : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
    [LieRing L'] [LieAlgebra R L'] (f : L →ₗ⁅R⁆ L') (x : L) (n : ℕ) (y : L) :
    f ((LieAlgebra.ad R L x ^ n) y) = (LieAlgebra.ad R L' (f x) ^ n) (f y) := by
  induction n generalizing y with
  | zero => simp
  | succ n ih =>
    simp only [pow_succ, Module.End.mul_apply, LieAlgebra.ad_apply] at ih ⊢
    rw [ih, f.map_lie]

end TauCeti

namespace Module.Basis

/-- A bracket coordinate is the sum of the bracket columns weighted by the first argument's
basis coordinates. -/
theorem repr_lie_eq_sum {R L ι : Type*} [CommRing R] [LieRing L] [LieAlgebra R L]
    [Fintype ι] (b : Basis ι R L) (X Y : L) (k : ι) :
    b.repr ⁅X, Y⁆ k = ∑ i : ι, b.repr X i * b.repr ⁅b i, Y⁆ k := by
  classical
  conv_lhs => rw [← b.sum_repr X]
  rw [sum_lie]
  simp [smul_lie, map_sum, map_smul, Finsupp.coe_finsetSum, Finset.sum_apply,
    smul_eq_mul]

end Module.Basis
