/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.PowerSeries.WeierstrassPreparation
public import TauCeti.Topology.Algebra.Group.Profinite.CompletedGroupAlgebra.PowerSeries

/-!
# The finite levels of the power-series coordinate on `ℤ_p[[Γ]]`

Let `Γ` be a commutative pro-`p` group, let `U ≤ Γ` be an open normal subgroup, and let `γ ∈ Γ`
be an element whose class `σ` generates the finite cyclic `p`-group `Γ ⧸ U` of order `p ^ m`; a
topological generator of `Γ` does so at every level `U`. Evaluation of power series at `γ - 1` is
the map `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`, `1 + X ↦ γ`, of `TauCeti.completedGroupAlgebra.aeval_one_add_X`, and
the level `U` of the completed group algebra is the projection `ℤ_p[[Γ]] → ℤ_p[Γ ⧸ U]`. This file
identifies the kernel of the composite `ℤ_p⟦X⟧ → ℤ_p[Γ ⧸ U]`, `1 + X ↦ σ`, with the principal
ideal generated by the polynomial

  `ω_U = (1 + X) ^ |Γ ⧸ U| - 1`,

which vanishes at `σ - 1` because `σ ^ |Γ ⧸ U| = 1`. The Mathlib input is the Weierstrass
division in `ℤ_p⟦X⟧` of `Mathlib.RingTheory.PowerSeries.WeierstrassPreparation`.

Consequently the finite level `ℤ_p[Γ ⧸ U]` is the quotient `ℤ_p⟦X⟧ ⧸ (ω_U)`
(`TauCeti.completedGroupAlgebra.powerSeriesLevelEquiv`), and, for a topological generator `γ` of
`Γ`, the kernel of the level `U` of the completed group algebra itself is the principal ideal
`(γ ^ |Γ ⧸ U| - 1)` (`TauCeti.completedGroupAlgebra.ker_proj`). For `Γ ≅ ℤ_p` with the
power-series coordinate `ℤ_p⟦X⟧ ≃ₐ[ℤ_p] ℤ_p[[Γ]]` of
`TauCeti.completedGroupAlgebra.powerSeriesCoordinate`, this is the classical description of the
Iwasawa algebra: the kernels of its finite levels are the ideals `(ω_m)`,
`ω_m = (1 + X) ^ (p ^ m) - 1`, and `ℤ_p⟦X⟧ ⧸ (ω_m) ≅ ℤ_p[ℤ ⧸ p ^ m]` (Washington, *Introduction
to Cyclotomic Fields*, Section 7.1). These ideals are not the `X`-adic filtration: `ω_m` has
`X`-order one, and `ω_m / X` has constant coefficient `p ^ m`, which is not a unit for `m ≥ 1`, so
`(ω_m)` is not a power of `(X)`.

## Main results

* `TauCeti.completedGroupAlgebra.proj_aeval_eq_zero_iff`: a power series evaluated at `γ - 1`
  projects to zero at the level `U` exactly when `(1 + X) ^ |Γ ⧸ U| - 1` divides it, when the
  class of `γ` generates `Γ ⧸ U`.
* `TauCeti.completedGroupAlgebra.ker_proj_comp_aeval`: the kernel of `ℤ_p⟦X⟧ → ℤ_p[Γ ⧸ U]` is
  the principal ideal `((1 + X) ^ |Γ ⧸ U| - 1)`.
* `TauCeti.completedGroupAlgebra.powerSeriesLevelEquiv`: the induced isomorphism
  `ℤ_p⟦X⟧ ⧸ ((1 + X) ^ |Γ ⧸ U| - 1) ≃ₐ[ℤ_p] ℤ_p[Γ ⧸ U]`.
* `TauCeti.completedGroupAlgebra.ker_proj`: for a topological generator `γ` of `Γ`, the kernel of
  the level `U` of `ℤ_p[[Γ]]` is the principal ideal `(γ ^ |Γ ⧸ U| - 1)`.
* `TauCeti.completedGroupAlgebra.proj_powerSeriesCoordinate_eq_zero_iff`,
  `TauCeti.completedGroupAlgebra.ker_proj_comp_powerSeriesCoordinate`: the same, through the
  power-series coordinate of an infinite procyclic pro-`p` group.

## References

* L. C. Washington, *Introduction to Cyclotomic Fields*, 2nd ed., Section 7.1.
* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), Section 1.5.
-/

public section

namespace TauCeti.completedGroupAlgebra

variable {p : ℕ} [Fact p.Prime] {Γ : Type*} [Group Γ] [TopologicalSpace Γ] [IsTopologicalGroup Γ]
  [CompactSpace Γ] [IsMulCommutative Γ] (hΓ : IsProP p Γ)
include hΓ

section Generator

variable (γ : Γ) (U : OpenNormalSubgroup Γ)

/-- Evaluation at `γ - 1` sends the polynomial `(1 + X) ^ |Γ ⧸ U| - 1` to `γ ^ |Γ ⧸ U| - 1`. -/
theorem aeval_one_add_X_pow_card_sub_one :
    PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      ((1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : PowerSeries ℤ_[p]) =
        of ℤ_[p] Γ γ ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 := by
  rw [map_sub, map_pow, aeval_one_add_X hΓ γ, map_one]

/-- The polynomial `(1 + X) ^ |Γ ⧸ U| - 1`, evaluated at `γ - 1`, projects to zero at the level
`U`: its image is `σ ^ |Γ ⧸ U| - 1` for the class `σ` of `γ` in the finite group `Γ ⧸ U`. -/
theorem proj_aeval_one_add_X_pow_card_sub_one_eq_zero :
    proj ℤ_[p] Γ U (PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      ((1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : PowerSeries ℤ_[p])) = 0 := by
  rw [aeval_one_add_X_pow_card_sub_one hΓ γ U, map_sub, map_pow, proj_of,
    ← MonoidAlgebra.of_apply, ← map_pow, pow_card_eq_one', map_one, map_one, sub_self]

end Generator

section Level

variable {γ : Γ} {U : OpenNormalSubgroup Γ}
  (hσ : ∀ x : Γ ⧸ U.toSubgroup, x ∈ Subgroup.zpowers (γ : Γ ⧸ U.toSubgroup))
include hσ

/-- **The kernel of a finite level of `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`.** Let `U` be an open normal subgroup of
the commutative pro-`p` group `Γ` and let `γ ∈ Γ` have a class generating `Γ ⧸ U`. A power series
evaluated at `γ - 1` projects to zero in `ℤ_p[Γ ⧸ U]` exactly when it is divisible by
`(1 + X) ^ |Γ ⧸ U| - 1`. -/
theorem proj_aeval_eq_zero_iff (ψ : PowerSeries ℤ_[p]) :
    proj ℤ_[p] Γ U (PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ) ψ) = 0 ↔
      (1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 ∣ ψ := by
  refine ⟨fun h ↦ ?_, fun ⟨q, hq⟩ ↦ by
    rw [hq, map_mul, map_mul, proj_aeval_one_add_X_pow_card_sub_one_eq_zero hΓ γ U, zero_mul]⟩
  -- The level polynomial `ω = (1 + X) ^ |Γ ⧸ U| - 1` is distinguished at the maximal ideal `(p)`
  -- of `ℤ_p`, because `|Γ ⧸ U|` is a power of `p`.
  obtain ⟨n, hn⟩ := IsPGroup.iff_card.mp ((isProP_iff.mp hΓ) U)
  have hdist : ((1 + Polynomial.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 :
      Polynomial ℤ_[p]).IsDistinguishedAt (IsLocalRing.maximalIdeal ℤ_[p]) := by
    rw [hn, PadicInt.maximalIdeal_eq_span_p]
    exact TauCeti.Polynomial.isDistinguishedAt_one_add_X_pow_sub_one Fact.out n
  have hcoe : (((1 + Polynomial.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : Polynomial ℤ_[p]) :
      PowerSeries ℤ_[p]) = (1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 := by
    simp [Polynomial.coe_sub, Polynomial.coe_pow, Polynomial.coe_add]
  have hω : proj ℤ_[p] Γ U (PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      (((1 + Polynomial.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : Polynomial ℤ_[p]) :
        PowerSeries ℤ_[p])) = 0 := by
    rw [hcoe]
    exact proj_aeval_one_add_X_pow_card_sub_one_eq_zero hΓ γ U
  -- Weierstrass division: `ψ = ω * q + r` with `r` a polynomial of degree `< |Γ ⧸ U|`.
  obtain ⟨hdeg, heq⟩ := hdist.isWeierstrassDivisorAt'.isWeierstrassDivisionAt_div_mod ψ
  have hord : ((((1 + Polynomial.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : Polynomial ℤ_[p]) :
      PowerSeries ℤ_[p]).map (Ideal.Quotient.mk (IsLocalRing.maximalIdeal ℤ_[p]))).order.toNat =
        Nat.card (Γ ⧸ U.toSubgroup) := by
    rw [← hdist.coe_natDegree_eq_order_map _ 1 (by
        rw [PowerSeries.constantCoeff_one]
        exact fun h ↦ (IsLocalRing.maximalIdeal.isMaximal ℤ_[p]).ne_top
          ((Ideal.eq_top_iff_one _).mpr h)) (mul_one _).symm,
      ENat.toNat_natCast, TauCeti.Polynomial.natDegree_one_add_X_pow_sub_one]
  rw [hord] at hdeg
  -- Projecting the division to the level `U` kills `ω * q` and `ψ`, so `r(σ - 1) = 0`.
  have hr : Polynomial.aeval (MonoidAlgebra.of ℤ_[p] (Γ ⧸ U.toSubgroup) (γ : Γ ⧸ U.toSubgroup) - 1)
      (hdist.isWeierstrassDivisorAt'.mod ψ) = 0 := by
    rw [heq, map_add, map_mul, map_add, map_mul, hω, zero_mul, zero_add, PowerSeries.aeval_coe,
      ← Polynomial.aeval_algHom_apply, map_sub, map_one, proj_of] at h
    exact h
  -- A polynomial of degree `< |Γ ⧸ U|` vanishing at `σ - 1` is zero, as `σ` generates `Γ ⧸ U`.
  rw [TauCeti.MonoidAlgebra.eq_zero_of_aeval_of_sub_one_eq_zero hσ hdeg hr, Polynomial.coe_zero,
    add_zero] at heq
  refine ⟨hdist.isWeierstrassDivisorAt'.div ψ, ?_⟩
  rw [← hcoe]
  exact heq

/-- **The kernel of `ℤ_p⟦X⟧ → ℤ_p[Γ ⧸ U]`, `1 + X ↦ σ`, is `((1 + X) ^ |Γ ⧸ U| - 1)`**, for an
open normal subgroup `U` of the commutative pro-`p` group `Γ` and an element `γ ∈ Γ` whose class
`σ` generates `Γ ⧸ U`. -/
theorem ker_proj_comp_aeval :
    RingHom.ker ((proj ℤ_[p] Γ U).comp
      (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ))) =
        Ideal.span {((1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : PowerSeries ℤ_[p])} :=
  Ideal.ext fun ψ ↦ by
    rw [RingHom.mem_ker, AlgHom.comp_apply, proj_aeval_eq_zero_iff hΓ hσ, Ideal.mem_span_singleton]

/-- Evaluation at `γ - 1` followed by projection to the level `U` is a surjection
`ℤ_p⟦X⟧ → ℤ_p[Γ ⧸ U]`, for an element `γ ∈ Γ` whose class generates `Γ ⧸ U`. -/
theorem proj_comp_aeval_surjective :
    Function.Surjective ((proj ℤ_[p] Γ U).comp
      (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ))) := by
  intro x
  obtain ⟨f, rfl⟩ := TauCeti.MonoidAlgebra.aeval_of_sub_one_surjective hσ x
  refine ⟨(f : PowerSeries ℤ_[p]), ?_⟩
  rw [AlgHom.comp_apply, PowerSeries.aeval_coe, ← Polynomial.aeval_algHom_apply, map_sub, map_one,
    proj_of, MonoidAlgebra.of_apply]

/-- **A finite level of `ℤ_p[[Γ]]` as a quotient of the power-series ring.** For an open normal
subgroup `U` of the commutative pro-`p` group `Γ` and an element `γ ∈ Γ` whose class generates
`Γ ⧸ U`, evaluation at `γ - 1` followed by projection to the level `U` induces an isomorphism of
`ℤ_p`-algebras `ℤ_p⟦X⟧ ⧸ ((1 + X) ^ |Γ ⧸ U| - 1) ≃ₐ[ℤ_p] ℤ_p[Γ ⧸ U]`, sending the class of
`1 + X` to the class of `γ`. -/
noncomputable def powerSeriesLevelEquiv :
    (PowerSeries ℤ_[p] ⧸
      Ideal.span {((1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : PowerSeries ℤ_[p])})
        ≃ₐ[ℤ_[p]] MonoidAlgebra ℤ_[p] (Γ ⧸ U.toSubgroup) :=
  (Ideal.quotientEquivAlgOfEq ℤ_[p] (ker_proj_comp_aeval hΓ hσ).symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective (proj_comp_aeval_surjective hΓ hσ))

/-- The level isomorphism sends the class of a power series to the projection of its value at
`γ - 1`. -/
@[simp]
theorem powerSeriesLevelEquiv_mk (ψ : PowerSeries ℤ_[p]) :
    powerSeriesLevelEquiv hΓ hσ (Ideal.Quotient.mk _ ψ) =
      proj ℤ_[p] Γ U (PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ) ψ) := by
  rw [powerSeriesLevelEquiv, AlgEquiv.trans_apply, Ideal.quotientEquivAlgOfEq_mk,
    Ideal.quotientKerAlgEquivOfSurjective_mk, AlgHom.comp_apply]

/-- The level isomorphism sends the class of `1 + X` to the class of `γ` in `ℤ_p[Γ ⧸ U]`. -/
theorem powerSeriesLevelEquiv_mk_one_add_X :
    powerSeriesLevelEquiv hΓ hσ (Ideal.Quotient.mk _ (1 + PowerSeries.X)) =
      MonoidAlgebra.of ℤ_[p] (Γ ⧸ U.toSubgroup) (γ : Γ ⧸ U.toSubgroup) := by
  rw [powerSeriesLevelEquiv_mk, aeval_one_add_X hΓ γ, proj_of, MonoidAlgebra.of_apply]

end Level

variable {γ : Γ} (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤)
  (U : OpenNormalSubgroup Γ)
include hγ

/-- **The kernel of a finite level of the completed group algebra is principal.** For a
topological generator `γ` of the commutative pro-`p` group `Γ` and an open normal subgroup `U`,
the kernel of the projection `ℤ_p[[Γ]] → ℤ_p[Γ ⧸ U]` is the principal ideal generated by
`γ ^ |Γ ⧸ U| - 1`. -/
theorem ker_proj :
    RingHom.ker (proj ℤ_[p] Γ U) =
      Ideal.span {of ℤ_[p] Γ γ ^ Nat.card (Γ ⧸ U.toSubgroup) - 1} := by
  ext x
  obtain ⟨ψ, rfl⟩ := aeval_surjective hΓ hγ x
  have hσ := forall_mem_zpowers_mk_of_topologicalClosure_closure_eq_top hγ U
  rw [RingHom.mem_ker, proj_aeval_eq_zero_iff hΓ hσ, Ideal.mem_span_singleton,
    ← aeval_one_add_X_pow_card_sub_one hΓ γ U]
  refine ⟨fun h ↦ map_dvd _ h, fun ⟨y, hy⟩ ↦ (proj_aeval_eq_zero_iff hΓ hσ ψ).mp ?_⟩
  rw [hy, map_mul, proj_aeval_one_add_X_pow_card_sub_one_eq_zero hΓ γ U, zero_mul]

section Coordinate

variable [TotallyDisconnectedSpace Γ] [Infinite Γ]

/-- Through the power-series coordinate of an infinite procyclic pro-`p` group, a power series
projects to zero at the level `U` exactly when `(1 + X) ^ |Γ ⧸ U| - 1` divides it. -/
theorem proj_powerSeriesCoordinate_eq_zero_iff (ψ : PowerSeries ℤ_[p]) :
    proj ℤ_[p] Γ U (powerSeriesCoordinate hΓ hγ ψ) = 0 ↔
      (1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 ∣ ψ := by
  rw [coe_powerSeriesCoordinate]
  exact proj_aeval_eq_zero_iff hΓ
    (forall_mem_zpowers_mk_of_topologicalClosure_closure_eq_top hγ U) ψ

/-- **The finite levels of the Iwasawa algebra through the power-series coordinate.** For an
infinite procyclic pro-`p` group `Γ` with topological generator `γ`, the kernel of the level `U`
of `ℤ_p[[Γ]] ≃ ℤ_p⟦X⟧` is the principal ideal `((1 + X) ^ |Γ ⧸ U| - 1)`. -/
theorem ker_proj_comp_powerSeriesCoordinate :
    RingHom.ker ((proj ℤ_[p] Γ U).comp (powerSeriesCoordinate hΓ hγ).toAlgHom) =
      Ideal.span {((1 + PowerSeries.X) ^ Nat.card (Γ ⧸ U.toSubgroup) - 1 : PowerSeries ℤ_[p])} :=
  Ideal.ext fun ψ ↦ by
    rw [RingHom.mem_ker, AlgHom.comp_apply, AlgEquiv.coe_toAlgHom,
      proj_powerSeriesCoordinate_eq_zero_iff hΓ hγ U, Ideal.mem_span_singleton]

end Coordinate

end TauCeti.completedGroupAlgebra
