/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.CharZero.Infinite
public import Mathlib.Algebra.Group.TypeTags.Finite
public import Mathlib.NumberTheory.Padics.MahlerBasis
public import Mathlib.NumberTheory.Padics.ProperSpace
public import Mathlib.RingTheory.Filtration
public import Mathlib.RingTheory.PowerSeries.Inverse
public import Mathlib.RingTheory.PowerSeries.Trunc
public import TauCeti.Algebra.MonoidAlgebra.Cyclic
public import TauCeti.NumberTheory.Padics.MonoidAlgebra
public import TauCeti.RingTheory.MvPowerSeries.Substitution
public import TauCeti.RingTheory.PowerSeries.Evaluation
public import TauCeti.RingTheory.PowerSeries.Substitution
public import TauCeti.Topology.Algebra.Group.Profinite.CompletedGroupAlgebra.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicInt
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Procyclic
public import TauCeti.Topology.Algebra.Module.Compact
public import TauCeti.Topology.Algebra.Nonarchimedean.Profinite

/-!
# Power series in the completed group algebra of a pro-`p` group

Let `Γ` be a pro-`p` group and `Λ = ℤ_p[[Γ]]` its completed group algebra over the `p`-adic
integers, a compact totally disconnected topological ring. For every `γ ∈ Γ` the element
`γ - 1` of `Λ` is topologically nilpotent: at each finite level `ℤ_p[Γ ⧸ U]` the class of `γ` has
`p`-power order, so the coefficients of `(γ - 1) ^ n` tend to zero
(`TauCeti.PadicInt.tendsto_coeff_single_sub_one_pow`). When `Γ` is moreover compact and
commutative, `Λ` is a complete linearly topologized commutative ring, and Mathlib's
`PowerSeries.aeval` evaluates every power series `ψ ∈ ℤ_p⟦X⟧` at `γ - 1`, giving the continuous
`ℤ_p`-algebra homomorphism

  `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`, `X ↦ γ - 1`, `1 + X ↦ γ`.

When `γ` topologically generates `Γ` this homomorphism is surjective: its range is compact, hence
closed, it contains `γ` and `γ⁻¹`, hence every element of the closed subgroup generated by `γ`,
which is all of `Γ`, and the span of the group elements is dense
(`TauCeti.completedGroupAlgebra.dense_span_range_of`). So the completed group algebra of a
procyclic pro-`p` group is a quotient of the power-series ring.

When `Γ` is moreover infinite and totally disconnected, the homomorphism is also injective
(`TauCeti.completedGroupAlgebra.aeval_injective`, Washington, *Introduction to Cyclotomic Fields*,
Theorem 7.1), and `X ↦ γ - 1` is the **power-series coordinate** `ℤ_p⟦X⟧ ≃ₐ[ℤ_p] ℤ_p[[Γ]]`
(`TauCeti.completedGroupAlgebra.powerSeriesCoordinate`), the classical description of the Iwasawa
algebra. Both the infinitude and the total disconnectedness of `Γ` are needed: for finite `Γ` the
evaluation has kernel `((1 + X) ^ |Γ| - 1)`, and for the circle group `ℤ_p[[Γ]] = ℤ_p`. The
coordinate is a homeomorphism for the product topology on `ℤ_p⟦X⟧`, so `Λ`-module structures,
such as that on the relation module of a Demushkin group, can be read as `ℤ_p⟦X⟧`-module
structures through it. The concrete instance `Γ = Multiplicative ℤ_[p]` with
`γ = Multiplicative.ofAdd (1 : ℤ_[p])` is recorded.

The coordinate depends on the generator, and the dependence is a substitution. The binomial series
`(1 + X) ^ u ∈ ℤ_p⟦X⟧`, for `u ∈ ℤ_p`, evaluates at `γ - 1` to the `p`-adic power `γ ^ u`
(`TauCeti.completedGroupAlgebra.aeval_binomialSeries`). Every other topological generator of `Γ` is
`γ ^ u` for a unit `u` of `ℤ_p`, and the coordinate attached to `γ ^ u` is the coordinate attached
to `γ` composed with the substitution `X ↦ (1 + X) ^ u - 1`
(`TauCeti.completedGroupAlgebra.powerSeriesCoordinate_padicPow_apply`,
`TauCeti.completedGroupAlgebra.exists_isUnit_powerSeriesCoordinate_eq_subst`). A statement about
`ℤ_p[[Γ]]` read through a coordinate is therefore independent of the chosen generator exactly when
it is invariant under these substitutions.

## Main results

* `TauCeti.completedGroupAlgebra.isTopologicallyNilpotent_of_sub_one`: `γ - 1` is topologically
  nilpotent in `ℤ_p[[Γ]]` for a pro-`p` group `Γ`; as this is `PowerSeries.HasEval`, the
  evaluation `PowerSeries.aeval` of power series at `γ - 1` is available.
* `TauCeti.completedGroupAlgebra.aeval_one_add_X`: the evaluation sends `1 + X` to `γ`.
* `TauCeti.completedGroupAlgebra.aeval_surjective`: the evaluation is surjective when `γ`
  topologically generates `Γ`.
* `TauCeti.completedGroupAlgebra.aeval_injective`: the evaluation is injective when `γ`
  topologically generates the infinite profinite group `Γ`.
* `TauCeti.completedGroupAlgebra.powerSeriesCoordinate`: the resulting isomorphism of
  `ℤ_p`-algebras `ℤ_p⟦X⟧ ≃ₐ[ℤ_p] ℤ_p[[Γ]]`, with `powerSeriesCoordinate_X`,
  `powerSeriesCoordinate_one_add_X`, and its continuity in both directions.
* `TauCeti.completedGroupAlgebra.aeval_binomialSeries`,
  `TauCeti.completedGroupAlgebra.powerSeriesCoordinate_binomialSeries`: the binomial series
  `(1 + X) ^ u` goes to the `p`-adic power `γ ^ u`.
* `TauCeti.completedGroupAlgebra.powerSeriesCoordinate_padicPow_apply`,
  `TauCeti.completedGroupAlgebra.exists_isUnit_powerSeriesCoordinate_eq_subst`: changing the
  topological generator changes the coordinate by the substitution `X ↦ (1 + X) ^ u - 1`.
* `TauCeti.completedGroupAlgebra.aeval_bijective_multiplicative_padicInt`: the case of the
  Iwasawa algebra `ℤ_p[[ℤ_p]]`.

## References

* L. C. Washington, *Introduction to Cyclotomic Fields*, 2nd ed., Theorem 7.1.
* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), Section 1.5.
-/

public section

open Filter Topology PowerSeries.WithPiTopology

namespace TauCeti.completedGroupAlgebra

variable {p : ℕ} [Fact p.Prime] {Γ : Type*} [Group Γ] [TopologicalSpace Γ]

/-- **`γ - 1` is topologically nilpotent** in the completed group algebra `ℤ_p[[Γ]]` of a pro-`p`
group `Γ`. As `PowerSeries.HasEval` is this predicate, power series over `ℤ_[p]` can be evaluated
at `γ - 1` by `PowerSeries.aeval` once `ℤ_p[[Γ]]` is a complete linearly topologized commutative
ring, which it is for `Γ` compact and commutative. -/
theorem isTopologicallyNilpotent_of_sub_one (hΓ : IsProP p Γ) (γ : Γ) :
    IsTopologicallyNilpotent (of ℤ_[p] Γ γ - 1) := by
  refine (isInducing_coeffFamily ℤ_[p] Γ).tendsto_nhds_iff.mpr
    (tendsto_pi_nhds.mpr fun U ↦ tendsto_pi_nhds.mpr fun g ↦ ?_)
  obtain ⟨k, hk⟩ := (isProP_iff.mp hΓ) U (γ : Γ ⧸ U.toSubgroup)
  simp only [Function.comp_def, coeffFamily_apply, map_pow, map_sub, map_one, proj_of, map_zero,
    MonoidAlgebra.coeff_zero, Finsupp.coe_zero, Pi.zero_apply]
  exact PadicInt.tendsto_coeff_single_sub_one_pow hk g

section

variable [SeparatelyContinuousMul Γ] [CompactSpace Γ] [IsMulCommutative Γ]

/-- Evaluation of power series at `γ - 1` sends `1 + X` to the group element `γ`. -/
@[simp]
theorem aeval_one_add_X (hΓ : IsProP p Γ) (γ : Γ) :
    PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      (1 + PowerSeries.X : PowerSeries ℤ_[p]) = of ℤ_[p] Γ γ := by
  rw [map_add, map_one, PowerSeries.aeval_X, add_sub_cancel]

end

variable [IsTopologicalGroup Γ] [CompactSpace Γ] [IsMulCommutative Γ]

/-- **The completed group algebra of a procyclic pro-`p` group is a quotient of `ℤ_p⟦X⟧`.** If `γ`
topologically generates the commutative pro-`p` group `Γ`, evaluation of power series at `γ - 1`
is a surjection `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`. -/
theorem aeval_surjective (hΓ : IsProP p Γ) {γ : Γ}
    (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤) :
    Function.Surjective
      (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ)) := by
  set ε := PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ) with hε
  -- The range of `ε` is the continuous image of the compact space `ℤ_p⟦X⟧`, hence closed.
  have hclosed : IsClosed (ε.range : Set (completedGroupAlgebra ℤ_[p] Γ)) := by
    have : CompactSpace (PowerSeries ℤ_[p]) := inferInstanceAs (CompactSpace ((Unit →₀ ℕ) → ℤ_[p]))
    rw [AlgHom.coe_range]
    exact (isCompact_range (PowerSeries.continuous_aeval _)).isClosed
  -- The range contains `γ`, as the image of `1 + X`, and `γ⁻¹`, as the image of `(1 + X)⁻¹`.
  have hγ_mem : of ℤ_[p] Γ γ ∈ ε.range := (AlgHom.mem_range ε).mpr ⟨_, aeval_one_add_X hΓ γ⟩
  have hγ_inv_mem : of ℤ_[p] Γ γ⁻¹ ∈ ε.range := by
    obtain ⟨u, hu⟩ := PowerSeries.isUnit_iff_constantCoeff.mpr
      (by simp : IsUnit (PowerSeries.constantCoeff (1 + PowerSeries.X : PowerSeries ℤ_[p])))
    refine (AlgHom.mem_range ε).mpr ⟨↑u⁻¹, left_inv_eq_right_inv (a := of ℤ_[p] Γ γ) ?_ ?_⟩
    · rw [← aeval_one_add_X hΓ γ, ← hu, ← hε, ← map_mul, Units.inv_mul, map_one]
    · rw [← map_mul, mul_inv_cancel, map_one]
  -- Hence it contains every element of the closed subgroup generated by `γ`, which is `Γ`.
  have hall : ∀ g : Γ, of ℤ_[p] Γ g ∈ ε.range := by
    have hsub : (Subgroup.closure ({γ} : Set Γ) : Set Γ) ⊆ of ℤ_[p] Γ ⁻¹' ε.range := by
      intro g hg
      refine (Subgroup.closure_induction
        (p := fun g _ ↦ of ℤ_[p] Γ g ∈ ε.range ∧ of ℤ_[p] Γ g⁻¹ ∈ ε.range) ?_ ?_ ?_ ?_ hg).1
      · rintro g (rfl : g = γ)
        exact ⟨hγ_mem, hγ_inv_mem⟩
      · rw [inv_one, map_one]
        exact ⟨one_mem _, one_mem _⟩
      · rintro g h _ _ ⟨hg, hg'⟩ ⟨hh, hh'⟩
        rw [map_mul, mul_inv_rev, map_mul]
        exact ⟨mul_mem hg hh, mul_mem hh' hg'⟩
      · rintro g _ ⟨hg, hg'⟩
        rw [inv_inv]
        exact ⟨hg', hg⟩
    intro g
    have hg : g ∈ closure (Subgroup.closure ({γ} : Set Γ) : Set Γ) := by
      rw [← Subgroup.topologicalClosure_coe, hγ]
      exact Set.mem_univ g
    exact closure_minimal hsub (hclosed.preimage (continuous_of ℤ_[p] Γ)) hg
  -- The dense span of the group elements lies in the closed range, which is therefore everything.
  have hspan : (Submodule.span ℤ_[p] (Set.range (of ℤ_[p] Γ)) : Set (completedGroupAlgebra ℤ_[p] Γ))
      ⊆ ε.range :=
    Submodule.span_le (p := Subalgebra.toSubmodule ε.range).mpr (Set.range_subset_iff.mpr hall)
  intro x
  have hx : x ∈ (ε.range : Set (completedGroupAlgebra ℤ_[p] Γ)) := by
    rw [← hclosed.closure_eq]
    exact closure_mono hspan ((dense_span_range_of ℤ_[p] Γ).closure_eq ▸ Set.mem_univ x)
  exact hx

/-! ### The binomial series and the `p`-adic powers -/

section Binomial

variable [TotallyDisconnectedSpace Γ]

/-- **The binomial series `(1 + X) ^ u` evaluates at `γ - 1` to the `p`-adic power `γ ^ u`**, for
every exponent `u ∈ ℤ_[p]`. -/
@[simp]
theorem aeval_binomialSeries (hΓ : IsProP p Γ) (γ : Γ) (u : ℤ_[p]) :
    PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ)
      (PowerSeries.binomialSeries ℤ_[p] u) = of ℤ_[p] Γ (hΓ.padicPow γ u) := by
  -- Both sides are continuous in `u` and agree on the dense subset `ℕ`, where the binomial
  -- series is `(1 + X) ^ k` and the `p`-adic power is `γ ^ k`.
  have hbin : Continuous fun u : ℤ_[p] ↦ PowerSeries.binomialSeries ℤ_[p] u := by
    refine continuous_iff_continuousAt.mpr fun u ↦
      (PowerSeries.WithPiTopology.tendsto_iff_coeff_tendsto _ _ _ _).mpr fun n ↦ ?_
    simp only [PowerSeries.binomialSeries_coeff, smul_eq_mul, mul_one]
    exact (PadicInt.continuous_choose n).continuousAt
  have hpow : Continuous fun u : ℤ_[p] ↦ of ℤ_[p] Γ (hΓ.padicPow γ u) :=
    (continuous_of ℤ_[p] Γ).comp
      (hΓ.continuous_padicPow.comp (continuous_id.prodMk continuous_const))
  exact congrFun (PadicInt.denseRange_natCast.equalizer
    ((PowerSeries.continuous_aeval _).comp hbin) hpow
    (funext fun k ↦ by simp [hΓ.padicPow_natCast])) u

end Binomial

/-! ### Injectivity, and the power-series coordinate of an infinite procyclic group -/

section Injective

variable [TotallyDisconnectedSpace Γ] [Infinite Γ]

/-- Every coefficient of a power series killed by evaluation at `γ - 1` is divisible by `p`, when
`γ` topologically generates the infinite pro-`p` group `Γ`. This is the finite-level step in
the injectivity proof below. -/
private theorem dvd_coeff_of_aeval_eq_zero (hΓ : IsProP p Γ) {γ : Γ}
    (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤) {ψ : PowerSeries ℤ_[p]}
    (hψ : PowerSeries.aeval (isTopologicallyNilpotent_of_sub_one hΓ γ) ψ = 0) (i : ℕ) :
    (p : ℤ_[p]) ∣ PowerSeries.coeff i ψ := by
  -- A finite level `Γ ⧸ U` of order `N = p ^ n > i`, generated by the class `σ` of `γ`.
  obtain ⟨U, hU⟩ := exists_openNormalSubgroup_lt_card_quotient (G := Γ) i
  obtain ⟨n, hn⟩ := IsPGroup.iff_card.mp ((isProP_iff.mp hΓ) U)
  set σ : Γ ⧸ U.toSubgroup := (γ : Γ ⧸ U.toSubgroup)
  have hσ : ∀ x, x ∈ Subgroup.zpowers σ :=
    forall_mem_zpowers_mk_of_topologicalClosure_closure_eq_top hγ U
  -- `(σ - 1) ^ N` is divisible by `p` in `ℤ_p[Γ ⧸ U]`, as `σ ^ N = 1`.
  obtain ⟨z, hz⟩ : (p : MonoidAlgebra ℤ_[p] (Γ ⧸ U.toSubgroup)) ∣
      (MonoidAlgebra.of ℤ_[p] _ σ - 1) ^ Nat.card (Γ ⧸ U.toSubgroup) := by
    rw [hn]
    exact (Fact.out : p.Prime).dvd_sub_one_pow_of_pow_eq_one
      (by rw [← map_pow, ← hn, pow_card_eq_one', map_one])
  -- Split `ψ` at `N` and project the evaluation to the level `U`.
  set ε := PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ)
  have hproj : proj ℤ_[p] Γ U (ε ψ) =
      (MonoidAlgebra.of ℤ_[p] _ σ - 1) ^ Nat.card (Γ ⧸ U.toSubgroup) *
        proj ℤ_[p] Γ U (ε (PowerSeries.mk fun j ↦
          PowerSeries.coeff (j + Nat.card (Γ ⧸ U.toSubgroup)) ψ)) +
      Polynomial.aeval (MonoidAlgebra.of ℤ_[p] _ σ - 1)
        (ψ.trunc (Nat.card (Γ ⧸ U.toSubgroup))) := by
    conv_lhs => rw [PowerSeries.eq_X_pow_mul_shift_add_trunc (Nat.card (Γ ⧸ U.toSubgroup)) ψ]
    rw [map_add, map_mul, map_pow, map_add, map_mul, map_pow, PowerSeries.aeval_X,
      PowerSeries.aeval_coe, ← Polynomial.aeval_algHom_apply, map_sub, map_one, proj_of,
      MonoidAlgebra.of_apply]
  have h0 : Polynomial.aeval (MonoidAlgebra.of ℤ_[p] _ σ - 1)
      (ψ.trunc (Nat.card (Γ ⧸ U.toSubgroup))) = (p : ℤ_[p]) • -(z * proj ℤ_[p] Γ U
        (ε (PowerSeries.mk fun j ↦ PowerSeries.coeff (j + Nat.card (Γ ⧸ U.toSubgroup)) ψ))) := by
    rw [hψ, map_zero, hz] at hproj
    rw [eq_neg_of_add_eq_zero_right hproj.symm, Algebra.smul_def, map_natCast, mul_neg, mul_assoc]
  have := MonoidAlgebra.dvd_coeff_of_aeval_of_sub_one_eq_smul hσ
    (PowerSeries.degree_trunc_lt ψ (Nat.card (Γ ⧸ U.toSubgroup))) h0 i
  simpa [PowerSeries.coeff_trunc, hU] using this

/-- **Evaluation at `γ - 1` is injective on power series.** If `γ` topologically generates the
infinite commutative pro-`p` group `Γ`, then `ℤ_p⟦X⟧ → ℤ_p[[Γ]]`, `X ↦ γ - 1`, is injective
(Washington, *Introduction to Cyclotomic Fields*, Theorem 7.1). -/
theorem aeval_injective (hΓ : IsProP p Γ) {γ : Γ}
    (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤) :
    Function.Injective
      (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ)) := by
  -- The finite-level lemma `dvd_coeff_of_aeval_eq_zero` shows that every coefficient of an
  -- element of the kernel is divisible by `p`. Since `ℤ_p[[Γ]]` is torsion-free, the kernel
  -- is then `p` times itself.
  set ε := PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ)
  refine (injective_iff_map_eq_zero ε).mpr fun ψ hψ ↦ ?_
  -- Every coefficient of an element of the kernel is divisible by every power of `p`.
  have key : ∀ k : ℕ, ∀ ψ : PowerSeries ℤ_[p], ε ψ = 0 →
      ∀ i, (p : ℤ_[p]) ^ k ∣ PowerSeries.coeff i ψ := by
    intro k
    induction k with
    | zero => exact fun ψ _ i ↦ one_dvd _
    | succ k ih =>
      intro ψ hψ i
      choose χ hχ using fun j ↦ dvd_coeff_of_aeval_eq_zero hΓ hγ hψ j
      have hψχ : ψ = (p : ℤ_[p]) • PowerSeries.mk χ := by
        ext j
        rw [PowerSeries.coeff_smul, PowerSeries.coeff_mk, smul_eq_mul, hχ]
      have hχ0 : ε (PowerSeries.mk χ) = 0 := by
        rw [hψχ, map_smul] at hψ
        exact (smul_eq_zero.mp hψ).resolve_left
          (Nat.cast_ne_zero.mpr (Fact.out : p.Prime).ne_zero)
      rw [hψχ, PowerSeries.coeff_smul, smul_eq_mul, pow_succ']
      exact mul_dvd_mul_left _ (ih _ hχ0 i)
  -- Hence every coefficient lies in every power of the maximal ideal of `ℤ_p`, so it vanishes.
  refine PowerSeries.ext fun i ↦ ?_
  have hmem : PowerSeries.coeff i ψ ∈ ⨅ k : ℕ, Ideal.span {(p : ℤ_[p])} ^ k := by
    rw [Ideal.mem_iInf]
    intro k
    rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact key k ψ hψ i
  have hbot := Ideal.iInf_pow_eq_bot_of_isDomain (I := Ideal.span {(p : ℤ_[p])})
    (Ideal.span_singleton_ne_top (mem_nonunits_iff.mp PadicInt.p_nonunit))
  rwa [hbot, Ideal.mem_bot, ← map_zero (PowerSeries.coeff i)] at hmem

/-- **The power-series coordinate on the completed group algebra of an infinite procyclic pro-`p`
group.** For a topological generator `γ` of the infinite commutative pro-`p` group `Γ` (so that
`Γ ≅ ℤ_p`), evaluation at `γ - 1` is an isomorphism of `ℤ_p`-algebras
`ℤ_p⟦X⟧ ≃ₐ[ℤ_p] ℤ_p[[Γ]]` with `X ↦ γ - 1` and `1 + X ↦ γ`. The coordinate depends on `γ`: for
`Γ = Multiplicative ℤ_[p]` and `γ = Multiplicative.ofAdd 1` this is the classical description of
the Iwasawa algebra as a power-series ring. -/
noncomputable def powerSeriesCoordinate (hΓ : IsProP p Γ) {γ : Γ}
    (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤) :
    PowerSeries ℤ_[p] ≃ₐ[ℤ_[p]] completedGroupAlgebra ℤ_[p] Γ :=
  AlgEquiv.ofBijective _ ⟨aeval_injective hΓ hγ, aeval_surjective hΓ hγ⟩

variable (hΓ : IsProP p Γ) {γ : Γ} (hγ : (Subgroup.closure ({γ} : Set Γ)).topologicalClosure = ⊤)

/-- The power-series coordinate is evaluation at `γ - 1`. -/
@[simp]
theorem coe_powerSeriesCoordinate :
    ⇑(powerSeriesCoordinate hΓ hγ) =
      PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ) :=
  AlgEquiv.coe_ofBijective
    (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one hΓ γ))
    ⟨aeval_injective hΓ hγ, aeval_surjective hΓ hγ⟩

/-- The power-series coordinate sends `X` to `γ - 1`. -/
@[simp]
theorem powerSeriesCoordinate_X :
    powerSeriesCoordinate hΓ hγ PowerSeries.X = of ℤ_[p] Γ γ - 1 := by
  rw [coe_powerSeriesCoordinate, PowerSeries.aeval_X]

/-- The power-series coordinate sends `1 + X` to the group element `γ`. -/
@[simp]
theorem powerSeriesCoordinate_one_add_X :
    powerSeriesCoordinate hΓ hγ (1 + PowerSeries.X) = of ℤ_[p] Γ γ := by
  rw [coe_powerSeriesCoordinate, aeval_one_add_X hΓ γ]

/-- The inverse of the power-series coordinate sends the group element `γ` to `1 + X`. -/
@[simp]
theorem powerSeriesCoordinate_symm_of :
    (powerSeriesCoordinate hΓ hγ).symm (of ℤ_[p] Γ γ) = 1 + PowerSeries.X :=
  (powerSeriesCoordinate hΓ hγ).symm_apply_eq.mpr (powerSeriesCoordinate_one_add_X hΓ hγ).symm

/-- The power-series coordinate is continuous for the product topology on `ℤ_p⟦X⟧` and the
inverse-limit topology on `ℤ_p[[Γ]]`. -/
theorem continuous_powerSeriesCoordinate : Continuous (powerSeriesCoordinate hΓ hγ) := by
  rw [coe_powerSeriesCoordinate]
  exact PowerSeries.continuous_aeval _

/-- The inverse of the power-series coordinate is continuous, so the coordinate is a
homeomorphism between the compact space `ℤ_p⟦X⟧` and `ℤ_p[[Γ]]`. -/
theorem continuous_powerSeriesCoordinate_symm :
    Continuous (powerSeriesCoordinate hΓ hγ).symm := by
  have : CompactSpace (PowerSeries ℤ_[p]) := inferInstanceAs (CompactSpace ((Unit →₀ ℕ) → ℤ_[p]))
  exact (Continuous.homeoOfEquivCompactToT2 (f := (powerSeriesCoordinate hΓ hγ).toEquiv)
    (continuous_powerSeriesCoordinate hΓ hγ)).symm.continuous

/-- The power-series coordinate sends the binomial series `(1 + X) ^ u` to the group element
`γ ^ u`, the `p`-adic power of the generator. -/
@[simp]
theorem powerSeriesCoordinate_binomialSeries (u : ℤ_[p]) :
    powerSeriesCoordinate hΓ hγ (PowerSeries.binomialSeries ℤ_[p] u) =
      of ℤ_[p] Γ (hΓ.padicPow γ u) := by
  rw [coe_powerSeriesCoordinate, aeval_binomialSeries]

/-- **Change of topological generator.** If the `p`-adic power `γ ^ u` again topologically
generates `Γ`, the power-series coordinate attached to `γ ^ u` is the coordinate attached to `γ`
composed with the substitution `X ↦ (1 + X) ^ u - 1`. -/
theorem powerSeriesCoordinate_padicPow_apply (u : ℤ_[p])
    (hγu : (Subgroup.closure ({hΓ.padicPow γ u} : Set Γ)).topologicalClosure = ⊤)
    (ψ : PowerSeries ℤ_[p]) :
    powerSeriesCoordinate hΓ hγu ψ =
      powerSeriesCoordinate hΓ hγ (ψ.subst (PowerSeries.binomialSeries ℤ_[p] u - 1)) := by
  have hX : (powerSeriesCoordinate hΓ hγ).toAlgHom (PowerSeries.binomialSeries ℤ_[p] u - 1) =
      of ℤ_[p] Γ (hΓ.padicPow γ u) - 1 := by
    rw [AlgEquiv.coe_toAlgHom, map_sub, map_one, powerSeriesCoordinate_binomialSeries]
  have hb : PowerSeries.HasEval
      ((powerSeriesCoordinate hΓ hγ).toAlgHom (PowerSeries.binomialSeries ℤ_[p] u - 1)) :=
    hX ▸ isTopologicallyNilpotent_of_sub_one hΓ (hΓ.padicPow γ u)
  have h := PowerSeries.aeval_subst (ε := (powerSeriesCoordinate hΓ hγ).toAlgHom)
    (hasSubst_binomialSeries_sub_one u) (continuous_powerSeriesCoordinate hΓ hγ) hb ψ
  -- Both sides are evaluations of `ψ`, at points identified by `hX`.
  rw [coe_powerSeriesCoordinate]
  refine Eq.trans ?_ h.symm
  rw [congrFun (PowerSeries.coe_aeval (isTopologicallyNilpotent_of_sub_one hΓ _)) ψ,
    congrFun (PowerSeries.coe_aeval hb) ψ, hX]

/-- **Any two power-series coordinates differ by a substitution `X ↦ (1 + X) ^ u - 1` with `u` a
unit of `ℤ_p`.** For a second topological generator `γ'` of `Γ`, there is a unit `u` with
`γ' = γ ^ u`, and the coordinate attached to `γ'` is the coordinate attached to `γ` composed with
the substitution `X ↦ (1 + X) ^ u - 1`. -/
theorem exists_isUnit_powerSeriesCoordinate_eq_subst {γ' : Γ}
    (hγ' : (Subgroup.closure ({γ'} : Set Γ)).topologicalClosure = ⊤) :
    ∃ u : ℤ_[p], IsUnit u ∧ ∀ ψ : PowerSeries ℤ_[p], powerSeriesCoordinate hΓ hγ' ψ =
      powerSeriesCoordinate hΓ hγ (ψ.subst (PowerSeries.binomialSeries ℤ_[p] u - 1)) := by
  obtain ⟨u, hu, rfl⟩ := hΓ.exists_isUnit_padicPow_eq_of_topologicalClosure_closure_eq_top hγ hγ'
  exact ⟨u, hu, powerSeriesCoordinate_padicPow_apply hΓ hγ u hγ'⟩

end Injective

/-- **The Iwasawa algebra `ℤ_p[[ℤ_p]]` is the power-series ring `ℤ_p⟦X⟧`**: evaluation at
`γ - 1`, for `γ = Multiplicative.ofAdd (1 : ℤ_[p])` the topological generator of
`Multiplicative ℤ_[p]`, is bijective; the isomorphism is `powerSeriesCoordinate`. -/
theorem aeval_bijective_multiplicative_padicInt (p : ℕ) [Fact p.Prime] :
    Function.Bijective (PowerSeries.aeval (R := ℤ_[p]) (isTopologicallyNilpotent_of_sub_one
      (isProP_multiplicative_padicInt p) (Multiplicative.ofAdd (1 : ℤ_[p])))) :=
  (powerSeriesCoordinate (isProP_multiplicative_padicInt p)
    (topologicallyGenerates_ofAdd_one_padicInt p)).bijective

end TauCeti.completedGroupAlgebra
