/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors, Chris Birkbeck
-/
module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.RingTheory.Localization.FractionRing

/-!
# Field extensions generated by a set

Complements on `IntermediateField.adjoin F s = ⊤`, the statement that a set `s` generates a field
extension `E / F`: two independent consequences of it, and one criterion for it.

*Extensionality.* An `F`-algebra automorphism of `E` fixing every element of `s` is the
identity. This is the whole-field counterpart of Mathlib's
`IntermediateField.algHom_ext_of_eq_adjoin` (which compares homomorphisms out of the *subfield*
`adjoin F s`), obtained from it by transporting along `adjoin F s ≃ₐ[F] E` rather than repeating
the adjoin induction. It is the extensionality step shared by the multiquadratic arguments:
the splitting law shows a decomposition-group element fixes every generator `√dᵢ` and concludes
it is trivial, and the Frobenius computation concludes the same when every Legendre symbol
is `1`.

*Changing the base of a generated extension.* For a tower `K ⊆ L ⊆ M` in which a set `t`
generates `M` over `L`, the compositum of `K(t)` — generated over the *bottom* of the
tower — with the image of `L` is already all of `M`. That is the shape every compositum argument
over the base `K` needs, because Mathlib's engines (`IntermediateField.fixingSubgroup_sup`,
`IntermediateField.normal_sup`, and the linear-disjointness API) all take two intermediate
fields of a *single* extension `M / K` together with a hypothesis that their join is `⊤`.

*Generation from an algebra generator.* If a ring `S` is generated as an `R`-algebra by a single
element `β`, then the fraction field `L` of `S` is generated by the image of `β` over any field
`K` between `R` and `L`, because every element of `L` is a ratio of two elements of `R[β]`. This
is how a generator of an extension of integer rings becomes a primitive element of the extension
of fraction fields.

## Main results

* `TauCeti.IntermediateField.algHom_ext_of_adjoin_eq_top`: algebra homomorphisms into any
  semiring are determined by their values on a generating set.
* `TauCeti.IntermediateField.algEquiv_ext_of_adjoin_eq_top`: two automorphisms agreeing on a
  generating set are equal.
* `TauCeti.IntermediateField.algEquiv_eq_one_of_adjoin_eq_top`: an automorphism fixing each
  element of a generating set is `1`.
* `TauCeti.IntermediateField.adjoin_adjoinSimpleGen_eq_top`: the distinguished generator of a
  simple adjoin generates that field.
* `TauCeti.IntermediateField.adjoin_sup_fieldRange_eq_top`: for a tower `K ⊆ L ⊆ M` in which
  `t` generates `M` over `L`, the compositum `K(t) ⊔ L` is `⊤` inside `M`.
* `TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top`: an algebra generator of a
  domain also generates its fraction field over any intermediate base field.

## Generating sets

The compositum criterion allows an arbitrary set of field generators, so it applies to extensions
that need several generators or contain transcendental elements. It expresses generation over a
larger base as generation by the same set together with that base inside a single extension.
For a cyclotomic extension, the singleton consisting of a primitive root suffices; its algebra
generation hypothesis implies field generation by `IntermediateField.adjoin_eq_top_of_algebra`.

`adjoin_sup_fieldRange_eq_top` is adapted from the Birkbeck–Brasca Chebotarev density project,
where the step is inlined into a larger `adjoin_induction`.
-/

public section

namespace TauCeti.IntermediateField

variable {F E : Type*} [Field F] [Field E] [Algebra F E] {s : Set E}

/-- **Two algebra homomorphisms agreeing on a generating set are equal.** If `s` generates `E`
over `F` (`IntermediateField.adjoin F s = ⊤`) and `F`-algebra maps `σ, τ : E →ₐ[F] E₂` (into any
semiring `E₂`) agree on every element of `s`, then `σ = τ`. This is the whole-field, two-map
counterpart of Mathlib's `IntermediateField.algHom_ext_of_eq_adjoin`. -/
theorem algHom_ext_of_adjoin_eq_top {E₂ : Type*} [Semiring E₂] [Algebra F E₂]
    (htop : IntermediateField.adjoin F s = ⊤)
    {σ τ : E →ₐ[F] E₂} (h : ∀ x ∈ s, σ x = τ x) : σ = τ := by
  -- Transport `σ`, `τ` along `adjoin F s ≃ E` and compare on the subfield with Mathlib's
  -- `algHom_ext_of_eq_adjoin`, which is the adjoin induction we would otherwise repeat.
  let e : IntermediateField.adjoin F s ≃ₐ[F] E :=
    (IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv
  have key : σ.comp e.toAlgHom = τ.comp e.toAlgHom :=
    IntermediateField.adjoin_algHom_ext F fun x hx => h x hx
  refine AlgHom.ext fun y => ?_
  obtain ⟨z, rfl⟩ := e.surjective y
  exact AlgHom.congr_fun key z

/-- Two `F`-algebra automorphisms of `E` agreeing on a generating set are equal. -/
theorem algEquiv_ext_of_adjoin_eq_top (htop : IntermediateField.adjoin F s = ⊤)
    {σ τ : E ≃ₐ[F] E} (h : ∀ x ∈ s, σ x = τ x) : σ = τ :=
  AlgEquiv.ext (AlgHom.ext_iff.mp
    (algHom_ext_of_adjoin_eq_top (E₂ := E) htop (σ := σ.toAlgHom) (τ := τ.toAlgHom) h))

/-- An `F`-algebra automorphism of `E` that fixes every element of a set generating `E` over
`F` is the identity. This is `TauCeti.IntermediateField.algEquiv_ext_of_adjoin_eq_top` against
the identity. -/
theorem algEquiv_eq_one_of_adjoin_eq_top (htop : IntermediateField.adjoin F s = ⊤)
    {σ : E ≃ₐ[F] E} (hfix : ∀ x ∈ s, σ x = x) : σ = 1 :=
  algEquiv_ext_of_adjoin_eq_top htop (σ := σ) (τ := 1) (by simpa using hfix)

/-- The distinguished generator of `F⟮x⟯`, viewed as an element of that field, generates
`F⟮x⟯` over `F`. -/
theorem adjoin_adjoinSimpleGen_eq_top (x : E) :
    IntermediateField.adjoin F {IntermediateField.AdjoinSimple.gen F x} = ⊤ := by
  refine IntermediateField.map_injective (IntermediateField.adjoin F {x}).val ?_
  rw [IntermediateField.adjoin_map, ← AlgHom.fieldRange_eq_map,
    IntermediateField.fieldRange_val]
  congr 1
  ext y
  simp

/-- **The compositum step.** If a set `t` generates `M` over `L`, then inside `M` the
compositum of `K(t)` with the image of `L` is all of `M`, for any base field `K` of the
tower. This is the input to Mathlib's compositum engines
(`IntermediateField.fixingSubgroup_sup`, `IntermediateField.normal_sup`). The single-generator
case `t = {ζ}` is the one the cyclotomic compositum uses; it is obtained by specialisation. -/
theorem adjoin_sup_fieldRange_eq_top (K L M : Type*) [Field K] [Field L] [Field M]
    [Algebra K L] [Algebra K M] [Algebra L M] [IsScalarTower K L M] {t : Set M}
    (hadj : IntermediateField.adjoin L t = ⊤) :
    IntermediateField.adjoin K t ⊔ (IsScalarTower.toAlgHom K L M).fieldRange = ⊤ := by
  refine top_le_iff.mp fun x _ ↦ ?_
  have hx : x ∈ IntermediateField.adjoin L t := hadj ▸ IntermediateField.mem_top
  refine IntermediateField.adjoin_induction L (fun y hy ↦ ?_) (fun r ↦ ?_)
    (fun a b _ _ ha hb ↦ add_mem ha hb) (fun a _ ha ↦ inv_mem ha)
    (fun a b _ _ ha hb ↦ mul_mem ha hb) hx
  · exact le_sup_left (α := IntermediateField K M) (IntermediateField.subset_adjoin K t hy)
  · exact le_sup_right (α := IntermediateField K M) ⟨r, rfl⟩

variable {R S K L : Type*} [CommSemiring R] [CommRing S] [Field K] [Field L] [Algebra R S]
  [Algebra R K] [Algebra R L] [Algebra S L] [Algebra K L] [IsScalarTower R S L]
  [IsScalarTower R K L] [IsFractionRing S L]

/-- If `S` is generated as an `R`-algebra by a single element `β`, then the fraction field `L` of
`S` is generated by the image of `β` over any field `K` sitting between `R` and `L`: every element
of `L` is a ratio of two elements of `R[β]`. -/
theorem adjoin_eq_top_of_algebra_adjoin_eq_top {β : S} (h : Algebra.adjoin R {β} = ⊤) :
    IntermediateField.adjoin K {algebraMap S L β} = ⊤ := by
  -- `R[β]` lands in `K(β)` by the universal property of `Algebra.adjoin`, applied to the
  -- preimage of `K(β)` in `S`.
  have key : ∀ s : S, algebraMap S L s ∈ IntermediateField.adjoin K {algebraMap S L β} := by
    have hle : Algebra.adjoin R ({β} : Set S) ≤
        ((IntermediateField.adjoin K {algebraMap S L β}).toSubalgebra.restrictScalars R).comap
          (IsScalarTower.toAlgHom R S L) :=
      Algebra.adjoin_le fun _ hx => hx ▸ IntermediateField.subset_adjoin K _ rfl
    exact fun s => hle (h.ge Algebra.mem_top)
  refine eq_top_iff.mpr fun x _ => ?_
  obtain ⟨s, t, -, rfl⟩ := IsFractionRing.div_surjective (A := S) x
  exact div_mem (key s) (key t)

end TauCeti.IntermediateField
