/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Orthogonal.TypeD.Root.AllGenerators

/-!
# Generation of the positive type-D root vectors

The positive roots of type `Dₙ` are `εᵢ - εⱼ` and `εᵢ + εⱼ` for `i < j`. This file
shows directly on the split orthogonal matrix carrier that their standard root vectors belong to
the Lie subalgebra generated by the numbered positive simple-root vectors.

For the difference roots, successive brackets concatenate intervals along the chain. For the sum
roots, the fork generator first produces every sum root involving the last coordinate; a generated
difference root then moves the second coordinate from the last index to any `j` with
`i < j < n - 1`. The imported matrix bracket identities record the signs used in these recurrences.

## Main declarations

* `TauCeti.TypeDStd.positiveSimpleRootMatrixLieSpan` is the Lie subalgebra generated by the
  numbered positive simple-root matrices.
* `TauCeti.TypeDStd.differenceRootGenerator_mem_positiveSimpleRootMatrixLieSpan` generates every
  positive difference-root vector.
* `TauCeti.TypeDStd.sumRootGenerator_mem_positiveSimpleRootMatrixLieSpan` generates every positive
  sum-root vector.

## References

* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate IV.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §10.
-/

public section

namespace TauCeti.TypeDStd

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [CommRing K]

/-! ## The positive simple-root span -/

/-- The Lie subalgebra of the split type-`D` matrix Lie algebra generated by its numbered
positive simple-root vectors. -/
noncomputable def positiveSimpleRootMatrixLieSpan (n : ℕ) (hn : 4 ≤ n) :
    LieSubalgebra K (LieAlgebra.Orthogonal.typeD (Fin n) K) :=
  LieSubalgebra.lieSpan K _
    (Set.range (fun i : Fin n => rootGenerator (K := K) n hn (.inl i)))

/-- Every numbered positive simple-root vector belongs to their generated Lie subalgebra. -/
@[simp]
theorem rootGenerator_inl_mem_positiveSimpleRootMatrixLieSpan
    (n : ℕ) (hn : 4 ≤ n) (i : Fin n) :
    rootGenerator (K := K) n hn (.inl i) ∈ positiveSimpleRootMatrixLieSpan n hn := by
  exact LieSubalgebra.subset_lieSpan (Set.mem_range_self i)

/-- The positive simple-root matrix span lies in a Lie subalgebra exactly when every numbered
positive simple-root vector lies in it. -/
@[simp]
theorem positiveSimpleRootMatrixLieSpan_le_iff (n : ℕ) (hn : 4 ≤ n)
    (S : LieSubalgebra K (LieAlgebra.Orthogonal.typeD (Fin n) K)) :
    positiveSimpleRootMatrixLieSpan n hn ≤ S ↔
      ∀ i : Fin n, rootGenerator (K := K) n hn (.inl i) ∈ S := by
  rw [positiveSimpleRootMatrixLieSpan, LieSubalgebra.lieSpan_le, Set.range_subset_iff]
  rfl

/-! ## Generation of all positive roots -/

/-- Every positive difference-root vector `εᵢ - εⱼ`, with `i < j`, belongs to the Lie
subalgebra generated by the positive simple-root vectors. -/
theorem differenceRootGenerator_mem_positiveSimpleRootMatrixLieSpan
    (n : ℕ) (hn : 4 ≤ n) (i j : Fin n) (hij : i < j) :
    differenceRootGenerator (K := K) i j ∈ positiveSimpleRootMatrixLieSpan n hn := by
  by_cases hadj : (i : ℕ) + 1 = (j : ℕ)
  · have hi : (i : ℕ) + 1 < n := hadj.trans_lt j.isLt
    have hnext : chainNext n i hi = j := Fin.ext (by simp [hadj])
    rw [← hnext, differenceRootGenerator_chain_eq_rootGenerator n hn i hi]
    exact rootGenerator_inl_mem_positiveSimpleRootMatrixLieSpan n hn i
  · have hi : (i : ℕ) + 1 < n := by omega
    let k := chainNext n i hi
    have hsucc : (i : ℕ) + 1 < (j : ℕ) := by omega
    have hkj : k < j := by
      simpa [k, Fin.lt_def] using hsucc
    have hi_mem : differenceRootGenerator (K := K) i k ∈
        positiveSimpleRootMatrixLieSpan n hn := by
      rw [differenceRootGenerator_chain_eq_rootGenerator n hn i hi]
      exact rootGenerator_inl_mem_positiveSimpleRootMatrixLieSpan n hn i
    have hj_mem : differenceRootGenerator (K := K) k j ∈
        positiveSimpleRootMatrixLieSpan n hn :=
      differenceRootGenerator_mem_positiveSimpleRootMatrixLieSpan n hn k j hkj
    rw [← lie_differenceRootGenerator_differenceRootGenerator i k j (ne_of_lt hij)]
    exact LieSubalgebra.lie_mem _ hi_mem hj_mem
termination_by (j : ℕ) - (i : ℕ)
decreasing_by simp only [chainNext_val]; omega

private theorem sumRootGenerator_last_mem_positiveSimpleRootMatrixLieSpan
    (n : ℕ) (hn : 4 ≤ n) (i : Fin n) (hi : i < forkRight n hn) :
    sumRootGenerator (K := K) i (forkRight n hn) ∈
      positiveSimpleRootMatrixLieSpan n hn := by
  by_cases hil : i = forkLeft n hn
  · subst i
    rw [sumRootGenerator_fork_eq_rootGenerator n hn]
    exact rootGenerator_inl_mem_positiveSimpleRootMatrixLieSpan n hn (forkRight n hn)
  · have hilt : i < forkLeft n hn := by
      rw [Fin.lt_def] at hi ⊢
      rw [forkRight_val] at hi
      rw [forkLeft_val]
      have hneval : (i : ℕ) ≠ n - 2 := by
        intro h
        apply hil
        apply Fin.ext
        simpa using h
      omega
    have hdiff := differenceRootGenerator_mem_positiveSimpleRootMatrixLieSpan
      (K := K) n hn i (forkLeft n hn) hilt
    have hfork : sumRootGenerator (K := K) (forkLeft n hn) (forkRight n hn) ∈
        positiveSimpleRootMatrixLieSpan n hn := by
      rw [sumRootGenerator_fork_eq_rootGenerator n hn]
      exact rootGenerator_inl_mem_positiveSimpleRootMatrixLieSpan n hn (forkRight n hn)
    rw [← lie_differenceRootGenerator_sumRootGenerator i (forkLeft n hn) (forkRight n hn)
      (forkLeft_ne_forkRight n hn)]
    exact LieSubalgebra.lie_mem _ hdiff hfork

/-- Every positive sum-root vector `εᵢ + εⱼ`, with `i < j`, belongs to the Lie subalgebra
generated by the positive simple-root vectors. -/
theorem sumRootGenerator_mem_positiveSimpleRootMatrixLieSpan
    (n : ℕ) (hn : 4 ≤ n) (i j : Fin n) (hij : i < j) :
    sumRootGenerator (K := K) i j ∈ positiveSimpleRootMatrixLieSpan n hn := by
  have hjle : j ≤ forkRight n hn := by
    rw [Fin.le_iff_val_le_val]
    simp only [forkRight_val]
    omega
  rcases hjle.eq_or_lt with hj | hj
  · subst j
    exact sumRootGenerator_last_mem_positiveSimpleRootMatrixLieSpan n hn i hij
  · have hdiff := differenceRootGenerator_mem_positiveSimpleRootMatrixLieSpan
      (K := K) n hn j (forkRight n hn) hj
    have hsum := sumRootGenerator_last_mem_positiveSimpleRootMatrixLieSpan
      (K := K) n hn i (hij.trans hj)
    have hbracket := LieSubalgebra.lie_mem (positiveSimpleRootMatrixLieSpan n hn) hdiff hsum
    have heq :
        ⁅differenceRootGenerator (K := K) j (forkRight n hn),
          sumRootGenerator (K := K) i (forkRight n hn)⁆ =
            sumRootGenerator (K := K) i j := by
      rw [sumRootGenerator_swap (forkRight n hn) i, lie_neg,
        lie_differenceRootGenerator_sumRootGenerator j (forkRight n hn) i
          (ne_of_gt (hij.trans hj)),
        sumRootGenerator_swap i j, neg_neg]
    rwa [heq] at hbracket

end TauCeti.TypeDStd
