/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Nonarchimedean.Completion.Basic
public import TauCeti.RingTheory.Huber.Basic
public import TauCeti.RingTheory.Huber.Pair

/-!
# The completion of a Huber ring

The Hausdorff completion `Â` of a Huber ring `A` is again a Huber ring. If `(A₀, I)` is a pair of
definition for `A`, then the closure `Â₀` of the image of `A₀` is an open subring of `Â`, and the
ideal `Î` of `Â₀` generated by the image of `I` is an ideal of definition for it.

That Huber structure rests on one identity: the `n`-th power `Îⁿ` is *exactly* the closure of the
image of `Iⁿ` (`TauCeti.Huber.PairOfDefinition.completionIdeal_pow`). Those closures are a
neighbourhood basis of zero in `Â`, so the identity gives both halves of `IsAdic Î` at once. Read
from right to left it also makes the extension of an open ideal of `A` to `Â` open: the closure of
the image of `Iⁿ` is the ideal of `Â₀` *generated by* that image, so an ideal of `Â` containing the
image already contains that closure, which is an open neighbourhood of zero.

The inclusion `Îⁿ ⊆ closure (Iⁿ)` is formal. The reverse inclusion is the substantial point, and
it is the only place where finite generation of `I` enters the proof of `completionIdeal_pow`:
fixing a finite family `G` generating `Iⁿ`, an element of the closure is approximated to order
`n + k`, for every `k`, by a combination of the *same* family `G` with coefficients in `Iᵏ`.
Finite generation is used once more, and directly, to see that `Î` is itself finitely generated
(`TauCeti.Huber.PairOfDefinition.fg_completionIdeal`). The coefficients accumulate to series which
converge because `Â` is complete, and their sums exhibit the element as a combination of `G`.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.completionRingOfDefinition` and
  `TauCeti.Huber.PairOfDefinition.completionIdeal`: the ring and the ideal of definition of `Â`.
* `TauCeti.Huber.PairOfDefinition.completionIdealImage`: the closure in `Â` of the image of `Iⁿ`,
  and `TauCeti.Huber.PairOfDefinition.completionIdealImageIdeal`, the ideal of `Â₀` it cuts out.
* `TauCeti.Huber.PairOfDefinition.toCompletionRingOfDefinition`: the completion map restricted to
  `A₀` and corestricted to `Â₀`.
* `TauCeti.Huber.PairOfDefinition.completion`: the pair of definition of `Â` they assemble into.

## Main results

* `TauCeti.Huber.isBounded_image_completion_coe_of_isBounded` and
  `TauCeti.Huber.isPowerBounded_completion_coe_of_isPowerBounded`: boundedness and
  power-boundedness transfer from `A` to its completion along the canonical map. Both are stated
  for a Huber ring, with no pair of definition in the signature.
* `TauCeti.Huber.isBounded_of_isBounded_image_completion_coe` and
  `TauCeti.Huber.isPowerBounded_of_isPowerBounded_completion_coe`: the converses, which come back
  down to `A` through the open-subgroup correspondence
  `UniformSpace.Completion.preimage_closure_image_coe`.
* `TauCeti.Huber.isPowerBounded_completion_coe_iff`: the two power-bounded directions together —
  Wedhorn's Lemma 7.47(1) at the level of elements, that `A⁰` is the preimage of `Â⁰`.
* `TauCeti.Huber.PairOfDefinition.hasBasis_nhds_zero_completion`: the closures of the images of
  the powers `Iⁿ` are a neighbourhood basis of zero in `Â`.
* `TauCeti.Huber.PairOfDefinition.completionIdeal_pow`: `Îⁿ` is the closure of the image of `Iⁿ`.
* `TauCeti.Huber.PairOfDefinition.completionIdealImage_le_of_image_subset` and
  `TauCeti.Huber.isOpen_map_coeRingHom`: an ideal of `Â` containing the image of `Iⁿ` contains the
  whole closure of that image, so the ideal of `Â` generated by the image of an open ideal of `A`
  is open.
* `TauCeti.Huber.IsHuberRing.completion`: the completion of a Huber ring is a Huber ring, and
  `TauCeti.Huber.IsTateRing.completion`: the completion of a Tate ring is a Tate ring.
* `TauCeti.Huber.topologicalClosure_map_coeRingHom_le_powerBoundedSubring` and
  `TauCeti.Huber.IsRingOfIntegralElements.completion`: the closure in `Â` of the image of a subring
  of `A⁰` lies in `Â⁰`, and the closure of the image of a ring of integral elements of `A` is a ring
  of integral elements of `Â`.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Remark 6.8.
* [The Stacks Project][stacks], Lemma 10.96.3 (tag
  [05GG](https://stacks.math.columbia.edu/tag/05GG)), the successive-approximation argument
  behind the private `completionIdealImageIdeal_le` below.
* Mathlib's `Mathlib/Topology/Algebra/Nonarchimedean/Completion.lean`, whose
  `Completion.isDenseInducing_coe` neighbourhood pattern is what
  `UniformSpace.Completion.isOpen_closure_image_coe` adapts, and which
  `TauCeti.Huber.PairOfDefinition.hasBasis_nhds_zero_completion` then builds on.
-/

public section

open Filter Topology UniformSpace

namespace TauCeti.Huber

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]

namespace PairOfDefinition

/-- The ring of definition of the completion: the closure in `Â` of the image of `A₀`. -/
noncomputable def completionRingOfDefinition (P : PairOfDefinition A) :
    Subring (Completion A) :=
  (P.ringOfDefinition.map Completion.coeRingHom).topologicalClosure

/-- `Â₀` is the closure of the image of `A₀`, by definition. -/
@[simp]
theorem coe_completionRingOfDefinition (P : PairOfDefinition A) :
    (P.completionRingOfDefinition : Set (Completion A))
      = closure (((↑) : A → Completion A) '' (P.ringOfDefinition : Set A)) := (rfl)

/-- Membership in `Â₀`. -/
@[simp]
theorem mem_completionRingOfDefinition_iff (P : PairOfDefinition A) {x : Completion A} :
    x ∈ P.completionRingOfDefinition
      ↔ x ∈ closure (((↑) : A → Completion A) '' (P.ringOfDefinition : Set A)) := (Iff.rfl)

/-- The ring of definition of the completion is open. -/
theorem isOpen_completionRingOfDefinition (P : PairOfDefinition A) :
    IsOpen (P.completionRingOfDefinition : Set (Completion A)) :=
  UniformSpace.Completion.isOpen_topologicalClosure_map_coeRingHom P.isOpen_ringOfDefinition

/-- The closure in `Â` of the image of `Iⁿ`, as an additive subgroup. These closures are the
neighbourhood basis of zero of the completion, and they turn out to be the powers of the ideal of
definition of the completion (`completionIdeal_pow`). -/
noncomputable def completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    AddSubgroup (Completion A) :=
  ((P.idealImage n).map Completion.toCompl).topologicalClosure

/-- `completionIdealImage` is the closure of the image of `Iⁿ`, by definition. -/
@[simp]
theorem coe_completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    (P.completionIdealImage n : Set (Completion A))
      = closure (((↑) : A → Completion A) '' (P.idealImage n : Set A)) := (rfl)

/-- The closure of the image of `Iⁿ` is open in `Â`. -/
theorem isOpen_completionIdealImage (P : PairOfDefinition A) (n : ℕ) :
    IsOpen (P.completionIdealImage n : Set (Completion A)) :=
  UniformSpace.Completion.isOpen_closure_image_coe (P.isOpen_idealImage n)

/-- The image of `Iⁿ` lies in its closure. -/
theorem coe_mem_completionIdealImage (P : PairOfDefinition A) {n : ℕ} {a : A}
    (ha : a ∈ P.idealImage n) : (a : Completion A) ∈ P.completionIdealImage n :=
  subset_closure ⟨a, ha, rfl⟩

/-- The closures of the images of the `Iⁿ` decrease with `n`. -/
theorem completionIdealImage_anti (P : PairOfDefinition A) {m n : ℕ} (h : m ≤ n) :
    P.completionIdealImage n ≤ P.completionIdealImage m := by
  refine fun x hx ↦ closure_mono (Set.image_mono ?_) hx
  rw [P.coe_idealImage, P.coe_idealImage]
  exact Set.image_mono fun z hz ↦ Ideal.pow_le_pow_right h hz

/-- The closure of the image of `Iⁿ` lies in the ring of definition of the completion. -/
theorem completionIdealImage_le (P : PairOfDefinition A) (n : ℕ) :
    (P.completionIdealImage n : Set (Completion A))
      ⊆ (P.completionRingOfDefinition : Set (Completion A)) := by
  refine closure_mono (Set.image_mono ?_)
  rw [P.coe_idealImage]
  rintro _ ⟨z, -, rfl⟩
  exact z.2

/-- Wedhorn Remark 6.8: the closures of the images of the powers of the ideal of definition are a
neighbourhood basis of zero in the completion. -/
theorem hasBasis_nhds_zero_completion (P : PairOfDefinition A) :
    (𝓝 (0 : Completion A)).HasBasis (fun _ : ℕ ↦ True)
      fun n ↦ (P.completionIdealImage n : Set (Completion A)) := by
  refine Filter.hasBasis_iff.mpr fun U ↦ ⟨fun hU ↦ ?_, ?_⟩
  · obtain ⟨C, ⟨hC, hCclosed⟩, hCU⟩ := (closed_nhds_basis (0 : Completion A)).mem_iff.mp hU
    have hpre : ((↑) : A → Completion A) ⁻¹' C ∈ 𝓝 (0 : A) :=
      (Completion.continuous_coe A).continuousAt.preimage_mem_nhds (by rwa [Completion.coe_zero])
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hpre
    refine ⟨n, trivial, fun x hx ↦ hCU ?_⟩
    have hx' : x ∈ closure C := closure_mono (Set.image_subset_iff.mpr hn) hx
    rwa [hCclosed.closure_eq] at hx'
  · rintro ⟨n, -, hn⟩
    exact Filter.mem_of_superset
      ((P.isOpen_completionIdealImage n).mem_nhds (P.completionIdealImage n).zero_mem) hn

/-- The closure of the image of `Iⁿ` absorbs multiplication by the ring of definition of the
completion, because `Iⁿ` is an ideal of `A₀` and multiplication is continuous. -/
theorem mul_mem_completionIdealImage (P : PairOfDefinition A) {n : ℕ} {t y : Completion A}
    (ht : t ∈ P.completionRingOfDefinition) (hy : y ∈ P.completionIdealImage n) :
    t * y ∈ P.completionIdealImage n := by
  have key : ∀ a ∈ P.idealImage n, t * (a : Completion A) ∈ P.completionIdealImage n := by
    intro a ha
    rw [← SetLike.mem_coe, P.coe_idealImage] at ha
    obtain ⟨b, hb, rfl⟩ := ha
    have h1 : t * ((b : A) : Completion A) ∈
        closure ((fun u : Completion A ↦ u * ((b : A) : Completion A)) ''
          (((↑) : A → Completion A) '' (P.ringOfDefinition : Set A))) :=
      image_closure_subset_closure_image (by fun_prop) ⟨t, ht, rfl⟩
    refine closure_mono ?_ h1
    rintro _ ⟨_, ⟨s, hs, rfl⟩, rfl⟩
    exact ⟨s * (b : A), (P.mem_idealImage n).mpr ⟨⟨s, hs⟩ * b, Ideal.mul_mem_left _ _ hb, rfl⟩,
      Completion.coe_mul s (b : A)⟩
  have h2 : t * y ∈ closure ((fun u : Completion A ↦ t * u) ''
      (((↑) : A → Completion A) '' (P.idealImage n : Set A))) :=
    image_closure_subset_closure_image (by fun_prop) ⟨y, hy, rfl⟩
  refine closure_minimal ?_ isClosed_closure h2
  rintro _ ⟨_, ⟨a, ha, rfl⟩, rfl⟩
  exact key a ha

/-- The closure of the image of `Iⁿ`, viewed as an ideal of the ring of definition of the
completion. -/
noncomputable def completionIdealImageIdeal (P : PairOfDefinition A) (n : ℕ) :
    Ideal P.completionRingOfDefinition where
  carrier := {y | (y : Completion A) ∈ P.completionIdealImage n}
  add_mem' hx hy := by simpa using AddSubgroup.add_mem _ hx hy
  zero_mem' := (P.completionIdealImage n).zero_mem
  smul_mem' c x hx := by simpa [smul_eq_mul] using P.mul_mem_completionIdealImage c.2 hx

/-- Membership in the ideal cut out by the closure of the image of `Iⁿ`. -/
@[simp]
theorem mem_completionIdealImageIdeal_iff (P : PairOfDefinition A) (n : ℕ)
    {y : P.completionRingOfDefinition} :
    y ∈ P.completionIdealImageIdeal n ↔ (y : Completion A) ∈ P.completionIdealImage n := (Iff.rfl)

/-- The completion map, restricted to a ring of definition and corestricted to the ring of
definition of the completion. -/
noncomputable def toCompletionRingOfDefinition (P : PairOfDefinition A) :
    P.ringOfDefinition →+* P.completionRingOfDefinition :=
  (Completion.coeRingHom.comp P.ringOfDefinition.subtype).codRestrict _ fun x ↦
    Subring.le_topologicalClosure _ ⟨x, x.2, rfl⟩

/-- The corestricted completion map agrees with the completion map on `A₀`. -/
@[simp] theorem toCompletionRingOfDefinition_apply (P : PairOfDefinition A)
    (x : P.ringOfDefinition) : (P.toCompletionRingOfDefinition x : Completion A) = (x : A) :=
  (rfl)

/-- The ideal of definition of the completion: the ideal of `Â₀` generated by the image of `I`. -/
noncomputable def completionIdeal (P : PairOfDefinition A) :
    Ideal P.completionRingOfDefinition :=
  P.idealOfDefinition.map P.toCompletionRingOfDefinition

/-- Unfolding lemma for `TauCeti.Huber.PairOfDefinition.completionIdeal`. -/
theorem completionIdeal_def (P : PairOfDefinition A) :
    P.completionIdeal = P.idealOfDefinition.map P.toCompletionRingOfDefinition := (rfl)

/-- Membership in `Î` is membership in the ideal spanned by the image of `I`. -/
@[simp]
theorem mem_completionIdeal_iff (P : PairOfDefinition A)
    {x : P.completionRingOfDefinition} : x ∈ P.completionIdeal ↔ x ∈ Ideal.span
      (P.toCompletionRingOfDefinition '' (P.idealOfDefinition : Set P.ringOfDefinition)) :=
  (Iff.rfl)

/-- The image of an element of `I` lies in `Î`. -/
theorem toCompletionRingOfDefinition_mem_completionIdeal (P : PairOfDefinition A)
    {x : P.ringOfDefinition} (hx : x ∈ P.idealOfDefinition) :
    P.toCompletionRingOfDefinition x ∈ P.completionIdeal :=
  Ideal.mem_map_of_mem _ hx

/-- The ideal of definition of the completion is finitely generated. -/
theorem fg_completionIdeal (P : PairOfDefinition A) : P.completionIdeal.FG :=
  P.fg_idealOfDefinition.map _

/-- The formal half of `completionIdeal_pow`: `Îⁿ` is generated by the image of `Iⁿ`, which lies
in its closure. -/
private theorem completionIdeal_pow_le (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdeal ^ n ≤ P.completionIdealImageIdeal n := by
  rw [completionIdeal, ← Ideal.map_pow, Ideal.map_le_iff_le_comap]
  intro x hx
  exact P.coe_mem_completionIdealImage (a := (x : A)) ((P.mem_idealImage n).mpr ⟨x, hx, rfl⟩)

/-- A finite `A₀`-combination of elements of `A₀` maps to the corresponding combination in `Â`. -/
private theorem coe_sum_mul (P : PairOfDefinition A) (G : Finset P.ringOfDefinition)
    (c : P.ringOfDefinition → P.ringOfDefinition) :
    ∑ z ∈ G, ((z : A) : Completion A) * ((c z : A) : Completion A)
      = (((∑ z ∈ G, z * c z : P.ringOfDefinition) : A) : Completion A) := by
  calc ∑ z ∈ G, ((z : A) : Completion A) * ((c z : A) : Completion A)
      = ∑ z ∈ G, (((z * c z : P.ringOfDefinition) : A) : Completion A) :=
        Finset.sum_congr rfl fun z _ ↦ by rw [Subring.coe_mul, Completion.coe_mul]
    _ = ((∑ z ∈ G, ((z * c z : P.ringOfDefinition) : A) : A) : Completion A) :=
        (map_sum (Completion.coeRingHom : A →+* Completion A) _ G).symm
    _ = (((∑ z ∈ G, z * c z : P.ringOfDefinition) : A) : Completion A) := by
        rw [AddSubmonoidClass.coe_finsetSum]

/-- One step of the successive approximation behind Wedhorn Remark 6.8: an element of the closure
of the image of `Iⁿ⁺ᵏ` agrees, modulo the closure of the image of `Iⁿ⁺ᵏ⁺¹`, with a combination of
the fixed generators `G` of `Iⁿ` whose coefficients lie in `Iᵏ`.

The statement is unconditional in `x` — the conclusion is guarded by the hypothesis instead — so
that the coefficients can be chosen simultaneously for all `x` and iterated. -/
private theorem exists_sub_sum_mem (P : PairOfDefinition A) {n : ℕ}
    (G : Finset P.ringOfDefinition)
    (hG : Ideal.span (G : Set P.ringOfDefinition) = P.idealOfDefinition ^ n)
    (k : ℕ) (x : Completion A) :
    ∃ c : P.ringOfDefinition → P.ringOfDefinition, (∀ z, c z ∈ P.idealOfDefinition ^ k) ∧
      (x ∈ P.completionIdealImage (n + k) →
        x - ∑ z ∈ G, ((z : A) : Completion A) * ((c z : A) : Completion A)
          ∈ P.completionIdealImage (n + k + 1)) := by
  by_cases hx : x ∈ P.completionIdealImage (n + k)
  · have hVopen : IsOpen ((fun w : Completion A ↦ w - x) ⁻¹'
        (P.completionIdealImage (n + k + 1) : Set (Completion A))) :=
      (P.isOpen_completionIdealImage _).preimage (by fun_prop)
    have hxV : x ∈ (fun w : Completion A ↦ w - x) ⁻¹'
        (P.completionIdealImage (n + k + 1) : Set (Completion A)) := by
      simp only [Set.mem_preimage, sub_self, SetLike.mem_coe]
      exact (P.completionIdealImage _).zero_mem
    rw [← SetLike.mem_coe, P.coe_completionIdealImage] at hx
    obtain ⟨w, hwV, a, ha, rfl⟩ := mem_closure_iff_nhds.mp hx _ (hVopen.mem_nhds hxV)
    rw [P.coe_idealImage] at ha
    obtain ⟨b, hb, rfl⟩ := ha
    have hb' : b ∈ Ideal.span (G : Set P.ringOfDefinition) * P.idealOfDefinition ^ k := by
      rw [hG, ← pow_add]; exact hb
    obtain ⟨c, hc, hcsum⟩ := exists_sum_eq_of_mem_span_mul G (P.idealOfDefinition ^ k) hb'
    refine ⟨c, hc, fun _ ↦ ?_⟩
    rw [P.coe_sum_mul, hcsum, ← neg_sub]
    exact (P.completionIdealImage (n + k + 1)).neg_mem hwV
  · exact ⟨0, fun _ ↦ Ideal.zero_mem _, fun h ↦ absurd h hx⟩

/-- Partial sums whose `k`-th term lies in the image of `Iᵏ` are a Cauchy sequence in `Â`. -/
private theorem cauchySeq_sum_coe (P : PairOfDefinition A) (d : ℕ → A)
    (hd : ∀ k, d k ∈ P.idealImage k) :
    CauchySeq fun m ↦ ∑ k ∈ Finset.range m, ((d k : A) : Completion A) := by
  have hsub : ∀ j m, j ≤ m → (∑ k ∈ Finset.range m, ((d k : A) : Completion A))
      - ∑ k ∈ Finset.range j, ((d k : A) : Completion A) ∈ P.completionIdealImage j := by
    intro j m hjm
    induction m, hjm using Nat.le_induction with
    | base => simp
    | succ m hjm ih =>
        rw [Finset.sum_range_succ, add_sub_right_comm]
        exact (P.completionIdealImage j).add_mem ih
          (P.completionIdealImage_anti hjm (P.coe_mem_completionIdealImage (hd m)))
  refine P.hasBasis_nhds_zero_completion.uniformity_of_nhds_zero.cauchySeq_iff.mpr fun j _ ↦ ?_
  refine ⟨j, fun m hm p hp ↦ ?_⟩
  have h := (P.completionIdealImage j).sub_mem (hsub j p hp) (hsub j m hm)
  rw [sub_sub_sub_cancel_right] at h
  exact h

/-- For an element `x` of the closure of the image of `Iⁿ`, coefficients `d k z ∈ Iᵏ` and errors
`u k` in the closure of the image of `Iⁿ⁺ᵏ` satisfying `x - u m = ∑_{z ∈ G} z * ∑_{k < m} d k z`. -/
private theorem exists_approx_seq (P : PairOfDefinition A) {n : ℕ}
    (G : Finset P.ringOfDefinition)
    (hG : Ideal.span (G : Set P.ringOfDefinition) = P.idealOfDefinition ^ n)
    {x : Completion A} (hx : x ∈ P.completionIdealImage n) :
    ∃ (d : ℕ → P.ringOfDefinition → P.ringOfDefinition) (u : ℕ → Completion A),
      (∀ k z, d k z ∈ P.idealOfDefinition ^ k) ∧ (∀ k, u k ∈ P.completionIdealImage (n + k)) ∧
        ∀ m, x - u m = ∑ z ∈ G, ((z : A) : Completion A)
          * ∑ k ∈ Finset.range m, ((d k z : A) : Completion A) := by
  choose c hc1 hc2 using P.exists_sub_sum_mem G hG
  obtain ⟨u, hu0, hurec⟩ : ∃ u : ℕ → Completion A, u 0 = x ∧ ∀ k,
      u (k + 1) = u k - ∑ z ∈ G, ((z : A) : Completion A) * ((c k (u k) z : A) : Completion A) :=
    ⟨fun m ↦ Nat.rec (motive := fun _ ↦ Completion A) x
      (fun k v ↦ v - ∑ z ∈ G, ((z : A) : Completion A) * ((c k v z : A) : Completion A)) m,
      rfl, fun _ ↦ rfl⟩
  have huK : ∀ k, u k ∈ P.completionIdealImage (n + k) := by
    intro k
    induction k with
    | zero => rw [hu0]; exact hx
    | succ k ih => rw [hurec k]; exact hc2 k (u k) ih
  refine ⟨fun k ↦ c k (u k), u, fun k z ↦ hc1 k (u k) z, huK, fun m ↦ ?_⟩
  induction m with
  | zero => simp [hu0]
  | succ m ih =>
      have hstep : x - u (m + 1) = (x - u m)
          + ∑ z ∈ G, ((z : A) : Completion A) * ((c m (u m) z : A) : Completion A) := by
        rw [hurec m]; ring
      rw [hstep, ih, ← Finset.sum_add_distrib]
      exact Finset.sum_congr rfl fun z _ ↦ by rw [Finset.sum_range_succ, mul_add]

/-- The substantial half of Wedhorn Remark 6.8: the closure of the image of `Iⁿ` is contained in
`Îⁿ`.

Fix a finite family `G` generating `Iⁿ`. By `exists_approx_seq`, an element `x` of the closure is
`∑_{z ∈ G} z * ∑_{k < m} d k z` up to an error tending to zero, with `d k z ∈ Iᵏ`. For each `z`
the series `∑ₖ d k z` is Cauchy, hence converges in `Â` to an element of `Â₀`, and `x` is the
corresponding combination of `G`. -/
private theorem completionIdealImageIdeal_le (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdealImageIdeal n ≤ P.completionIdeal ^ n := by
  classical
  obtain ⟨G, hG⟩ := P.fg_idealOfDefinition.pow (n := n)
  intro y hy
  obtain ⟨d, u, hd, huK, hpartial⟩ := P.exists_approx_seq G hG hy
  have hcauchy : ∀ z : P.ringOfDefinition, CauchySeq fun m ↦ ∑ k ∈ Finset.range m,
      ((d k z : A) : Completion A) :=
    fun z ↦ P.cauchySeq_sum_coe _ fun k ↦ (P.mem_idealImage k).mpr ⟨d k z, hd k z, rfl⟩
  choose L hL using fun z ↦ cauchySeq_tendsto_of_complete (hcauchy z)
  have hLmem : ∀ z, L z ∈ P.completionRingOfDefinition := fun z ↦
    (Subring.isClosed_topologicalClosure _).mem_of_tendsto (hL z) (.of_forall fun m ↦
      Subring.sum_mem _ fun k _ ↦ Subring.le_topologicalClosure _
        ⟨((d k z : P.ringOfDefinition) : A), (d k z).2, rfl⟩)
  have hulim : Tendsto u atTop (𝓝 0) := by
    refine P.hasBasis_nhds_zero_completion.tendsto_right_iff.mpr fun j _ ↦ ?_
    filter_upwards [eventually_ge_atTop j] with k hk
    exact P.completionIdealImage_anti (hk.trans (Nat.le_add_left k n)) (huK k)
  have hyeq : (y : Completion A) = ∑ z ∈ G, ((z : A) : Completion A) * L z := by
    have h := tendsto_nhds_unique
      (((tendsto_const_nhds (x := (y : Completion A))).sub hulim).congr hpartial)
      (tendsto_finsetSum G fun z _ ↦ (hL z).const_mul _)
    rwa [sub_zero] at h
  have hsum : y = ∑ z ∈ G, P.toCompletionRingOfDefinition z
      * (⟨L z, hLmem z⟩ : P.completionRingOfDefinition) := by
    apply Subtype.ext
    push_cast
    exact hyeq
  rw [hsum]
  refine Submodule.sum_mem _ fun z hz ↦ Ideal.mul_mem_right _ _ ?_
  rw [completionIdeal, ← Ideal.map_pow]
  exact Ideal.mem_map_of_mem _ (hG ▸ Ideal.subset_span (Finset.mem_coe.mpr hz))

/-- Wedhorn Remark 6.8: the `n`-th power of the ideal of definition of the completion is exactly
the closure of the image of `Iⁿ`. -/
theorem completionIdeal_pow (P : PairOfDefinition A) (n : ℕ) :
    P.completionIdeal ^ n = P.completionIdealImageIdeal n :=
  le_antisymm (P.completionIdeal_pow_le n) (P.completionIdealImageIdeal_le n)

/-- Wedhorn Remark 6.8: the subspace topology on the ring of definition of the completion is the
adic topology of the ideal of definition of the completion. -/
theorem isAdic_completionIdeal (P : PairOfDefinition A) : IsAdic P.completionIdeal := by
  refine isAdic_iff.mpr ⟨fun n ↦ ?_, fun s hs ↦ ?_⟩
  · rw [P.completionIdeal_pow]
    exact (P.isOpen_completionIdealImage n).preimage continuous_subtype_val
  · rw [mem_nhds_subtype] at hs
    obtain ⟨V, hV, hVs⟩ := hs
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero_completion.mem_iff.mp hV
    exact ⟨n, by rw [P.completionIdeal_pow]; exact (Set.preimage_mono hn).trans hVs⟩

/-- Wedhorn Remark 6.8: a pair of definition of `A` induces one of the completion of `A`, with the
closure of the image of `A₀` as ring of definition and the ideal generated by the image of `I` as
ideal of definition. -/
noncomputable def completion (P : PairOfDefinition A) :
    PairOfDefinition (Completion A) where
  ringOfDefinition := P.completionRingOfDefinition
  isOpen_ringOfDefinition := P.isOpen_completionRingOfDefinition
  idealOfDefinition := P.completionIdeal
  fg_idealOfDefinition := P.fg_completionIdeal
  isAdic_idealOfDefinition := P.isAdic_completionIdeal

/-- The ring of definition of the induced pair is `Â₀`. -/
@[simp]
theorem completion_ringOfDefinition (P : PairOfDefinition A) :
    P.completion.ringOfDefinition = P.completionRingOfDefinition := (rfl)

/-- Membership in the ideal of definition of the completed pair is membership in `I · Â₀`.

Stated as a membership characterisation rather than an equation because the type of
`idealOfDefinition` depends on `ringOfDefinition`, which the opaque body of `completion` does not
expose. -/
@[simp]
theorem mem_completion_idealOfDefinition (P : PairOfDefinition A)
    {x : P.completion.ringOfDefinition} :
    x ∈ P.completion.idealOfDefinition ↔
      (⟨x, by rw [← completion_ringOfDefinition P]; exact x.2⟩ :
        P.completionRingOfDefinition) ∈ P.completionIdeal := (Iff.rfl)

/-- An ideal of `Â` that contains the image of `Iⁿ` contains the whole closure of that image. The
hypothesis constrains `J` only at the points of `Â` that come from `A`. -/
theorem completionIdealImage_le_of_image_subset (P : PairOfDefinition A) (n : ℕ)
    {J : Ideal (Completion A)} (hJ : ∀ a ∈ P.idealImage n, (a : Completion A) ∈ J) :
    (P.completionIdealImage n : Set (Completion A)) ⊆ (J : Set (Completion A)) := by
  intro y hy
  -- `Îⁿ` is generated by the image of `Iⁿ`, so it lands in the ideal `J` cuts out on `Â₀`
  have hkey : P.completionIdeal ^ n ≤ J.comap P.completionRingOfDefinition.subtype := by
    rw [P.completionIdeal_def, ← Ideal.map_pow, Ideal.map_le_iff_le_comap]
    exact fun x hx ↦ hJ (x : A) ((P.mem_idealImage n).mpr ⟨x, hx, rfl⟩)
  -- and `y`, being in the closure, is one of its elements
  have hmem : (⟨y, P.completionIdealImage_le n hy⟩ : P.completionRingOfDefinition)
      ∈ P.completionIdeal ^ n := by
    rw [P.completionIdeal_pow]
    exact (P.mem_completionIdealImageIdeal_iff n).mpr hy
  exact hkey hmem

end PairOfDefinition

/-- **The extension of an open ideal along the completion map is open**: for an open ideal `J` of
a Huber ring `A`, the ideal of `Â` generated by the image of `J` is open. -/
theorem isOpen_map_coeRingHom [IsHuberRing A] {J : Ideal A} (hJ : IsOpen (J : Set A)) :
    IsOpen (J.map (Completion.coeRingHom : A →+* Completion A) : Set (Completion A)) := by
  refine (IsHuberRing.nonempty_pairOfDefinition (A := A)).elim fun P ↦ ?_
  obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp (hJ.mem_nhds J.zero_mem)
  refine AddSubgroup.isOpen_mono
    (H₂ := (J.map (Completion.coeRingHom : A →+* Completion A)).toAddSubgroup)
    (P.completionIdealImage_le_of_image_subset n fun a ha ↦ Ideal.mem_map_of_mem _ (hn ha))
    (P.isOpen_completionIdealImage n)

/-- **The image of a bounded subset of `A` is bounded in `Â`.**

Stated for a Huber ring rather than for a chosen pair of definition: the conclusion does not
mention one, so the choice is internal to the proof.

The closure argument follows AINTLIB (`github.com/CBirkbeck/AINTLIB`, Apache-2.0, branch
`dev/adic-spaces` at `37bbdaeb9`), `projects/AdicSpaces/Adic spaces/LocalizationTopology.lean:545`,
where it is stated for the rational-localisation completion. No proof was copied. -/
theorem isBounded_image_completion_coe_of_isBounded [IsHuberRing A] {X : Set A}
    (hX : IsBounded X) : IsBounded (((↑) : A → Completion A) '' X) := by
  refine (IsHuberRing.nonempty_pairOfDefinition (A := A)).elim fun P ↦ ?_
  rw [isBounded_iff]
  intro U hU
  obtain ⟨n, -, hnU⟩ := (P.hasBasis_nhds_zero_completion).mem_iff.mp hU
  obtain ⟨W, hW, hXW⟩ := isBounded_iff.mp hX (P.idealImage n)
    ((P.isOpen_idealImage n).mem_nhds (P.idealImage n).zero_mem)
  obtain ⟨m, -, hmW⟩ := P.hasBasis_nhds_zero.mem_iff.mp hW
  refine ⟨_, (P.hasBasis_nhds_zero_completion).mem_of_mem (i := m) trivial,
    Set.Subset.trans ?_ hnU⟩
  rintro _ ⟨y, hy, _, ⟨x, hxX, rfl⟩, rfl⟩
  -- `· * ↑x` is continuous and carries the image of `Iᵐ` into the image of `Iⁿ`, so it carries
  -- the closure of the first into the closure of the second.
  have hcont : Continuous (fun u : Completion A ↦ u * (x : Completion A)) :=
    continuous_id.mul continuous_const
  have hmaps : ((↑) : A → Completion A) '' (P.idealImage m : Set A)
      ⊆ (fun u : Completion A ↦ u * (x : Completion A)) ⁻¹'
        closure (((↑) : A → Completion A) '' (P.idealImage n : Set A)) := by
    rintro _ ⟨a, ha, rfl⟩
    rw [Set.mem_preimage, ← Completion.coe_mul]
    exact subset_closure ⟨a * x, hXW (Set.mul_mem_mul (hmW ha) hxX), rfl⟩
  exact closure_minimal (Set.image_subset_iff.mpr hmaps) isClosed_closure
    (image_closure_subset_closure_image hcont ⟨y, hy, rfl⟩)

/-- **The converse of `isBounded_image_completion_coe_of_isBounded`.** A set whose image in `Â` is
bounded was already bounded in `A`.

The step that comes back down to `A` is the open-subgroup correspondence: `Iⁿ` is open, so
`UniformSpace.Completion.preimage_closure_image_coe` says an element of `A` whose image lies in
`closure (ι '' Iⁿ)` — that is, in `completionIdealImage n` — lies in `Iⁿ` itself. -/
theorem isBounded_of_isBounded_image_completion_coe [IsHuberRing A] {X : Set A}
    (hX : IsBounded (((↑) : A → Completion A) '' X)) : IsBounded X := by
  refine (IsHuberRing.nonempty_pairOfDefinition (A := A)).elim fun P ↦ ?_
  rw [isBounded_iff]
  intro U hU
  obtain ⟨n, -, hnU⟩ := P.hasBasis_nhds_zero.mem_iff.mp hU
  obtain ⟨W, hW, hWX⟩ := isBounded_iff.mp hX _ ((P.isOpen_completionIdealImage n).mem_nhds
    (P.completionIdealImage n).zero_mem)
  obtain ⟨m, -, hmW⟩ := (P.hasBasis_nhds_zero_completion).mem_iff.mp hW
  refine ⟨P.idealImage m, (P.isOpen_idealImage m).mem_nhds (P.idealImage m).zero_mem,
    Set.Subset.trans ?_ hnU⟩
  rintro _ ⟨v, hv, x, hx, rfl⟩
  have hup : ((v * x : A) : Completion A) ∈ P.completionIdealImage n := by
    rw [Completion.coe_mul]
    exact hWX (Set.mul_mem_mul (hmW (P.coe_mem_completionIdealImage hv)) ⟨x, hx, rfl⟩)
  have hback := UniformSpace.Completion.preimage_closure_image_coe (P.isOpen_idealImage n)
  have : (v * x : A) ∈ ((P.idealImage n : AddSubgroup A) : Set A) := by
    rw [← hback, Set.mem_preimage, ← P.coe_completionIdealImage]
    exact hup
  simpa using this

/-- **A power-bounded element of `A` stays power-bounded in `Â`.** -/
theorem isPowerBounded_completion_coe_of_isPowerBounded [IsHuberRing A] {a : A}
    (ha : IsPowerBounded a) : IsPowerBounded ((a : Completion A)) := by
  -- the coercion is `⇑Completion.coeRingHom`, so it commutes with powers; stated once here
  have hcoe : ∀ k : ℕ, ((a : Completion A)) ^ k = ((a ^ k : A) : Completion A) :=
    fun k ↦ (map_pow Completion.coeRingHom a k).symm
  have h : Set.range (((a : Completion A)) ^ · : ℕ → Completion A)
      = ((↑) : A → Completion A) '' Set.range (a ^ · : ℕ → A) := by
    simpa only [hcoe] using Set.range_comp' (((↑) : A → Completion A)) (a ^ · : ℕ → A)
  rw [isPowerBounded_iff, h]
  exact isBounded_image_completion_coe_of_isBounded (isPowerBounded_iff.mp ha)

/-- **The converse of `isPowerBounded_completion_coe_of_isPowerBounded`.** An element of `A` whose
image in `Â` is power-bounded was already power-bounded. -/
theorem isPowerBounded_of_isPowerBounded_completion_coe [IsHuberRing A] {a : A}
    (ha : IsPowerBounded ((a : Completion A))) : IsPowerBounded a := by
  have hcoe : ∀ k : ℕ, ((a : Completion A)) ^ k = ((a ^ k : A) : Completion A) :=
    fun k ↦ (map_pow Completion.coeRingHom a k).symm
  have h : Set.range (((a : Completion A)) ^ · : ℕ → Completion A)
      = ((↑) : A → Completion A) '' Set.range (a ^ · : ℕ → A) := by
    simpa only [hcoe] using Set.range_comp' (((↑) : A → Completion A)) (a ^ · : ℕ → A)
  rw [isPowerBounded_iff] at ha ⊢
  rw [h] at ha
  exact isBounded_of_isBounded_image_completion_coe ha

/-- **Wedhorn Lemma 7.47(1), at the level of elements: `A⁰` is the preimage of `Â⁰`.** An element of
`A` is power-bounded exactly when its image in the completion is. -/
@[simp]
theorem isPowerBounded_completion_coe_iff [IsHuberRing A] {a : A} :
    IsPowerBounded ((a : Completion A)) ↔ IsPowerBounded a :=
  ⟨isPowerBounded_of_isPowerBounded_completion_coe,
    isPowerBounded_completion_coe_of_isPowerBounded⟩

/-- Wedhorn Remark 6.8: the completion of a Huber ring is a Huber ring. -/
instance IsHuberRing.completion [IsHuberRing A] : IsHuberRing (Completion A) :=
  ⟨IsHuberRing.nonempty_pairOfDefinition.elim fun P ↦ ⟨P.completion⟩⟩

/-- Wedhorn Remark 6.8: the completion of a Tate ring is a Tate ring. -/
instance IsTateRing.completion [IsTateRing A] : IsTateRing (Completion A) :=
  -- the structure map is continuous, so `IsTateRing.of_continuous` carries the pseudouniformiser
  IsTateRing.of_continuous (A := A) Completion.continuous_coeRingHom

/-- **The closure in `Â` of the image of a subring of `A⁰` lies in `Â⁰`**: the image lies in `Â⁰`
by `isPowerBounded_completion_coe_of_isPowerBounded`, and `Â⁰` is open, hence closed. -/
theorem topologicalClosure_map_coeRingHom_le_powerBoundedSubring [IsHuberRing A] {R : Subring A}
    (hR : R ≤ powerBoundedSubring A) :
    (R.map (Completion.coeRingHom : A →+* Completion A)).topologicalClosure ≤
      powerBoundedSubring (Completion A) :=
  Subring.topologicalClosure_minimal _
    (Subring.map_le_iff_le_comap.mpr fun _ ha ↦ mem_powerBoundedSubring.mpr <|
      isPowerBounded_completion_coe_of_isPowerBounded (mem_powerBoundedSubring.mp (hR ha)))
    (AddSubgroup.isClosed_of_isOpen (powerBoundedSubring _).toAddSubgroup
      (isOpen_powerBoundedSubring _))

/-- **Completion preserves rings of integral elements** (Wedhorn, Lemma 7.47): the closure in `Â`
of the image of a ring of integral elements of a Huber ring `A` is a ring of integral elements of
`Â`. -/
theorem IsRingOfIntegralElements.completion [IsHuberRing A] {Aplus : Subring A}
    (h : IsRingOfIntegralElements Aplus) :
    IsRingOfIntegralElements
      (Aplus.map (Completion.coeRingHom : A →+* Completion A)).topologicalClosure :=
  have := h.isIntegrallyClosedIn
  ⟨Completion.isOpen_topologicalClosure_map_coeRingHom h.isOpen,
    Completion.isIntegrallyClosedIn_topologicalClosure_map_coeRingHom h.isOpen,
    topologicalClosure_map_coeRingHom_le_powerBoundedSubring h.le_powerBoundedSubring⟩

end TauCeti.Huber
