/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.ClassGroup.Basic
public import TauCeti.RingTheory.DedekindDomain.Factorization
public import TauCeti.RingTheory.DedekindDomain.FiniteAdeleRing.Basic

/-!
# The ideal class group as a quotient of the finite ideles

Let `R` be a Dedekind domain with fraction field `K`.  A *finite idele* is a unit of the finite
adele ring `𝔸ᶠ[R, K]`: a family `(x_v)` of nonzero elements of the completions `K_v`, integral
with integral inverse at all but finitely many height one primes `v`.  Reading off the `v`-adic
orders of the components attaches an invertible fractional ideal to a finite idele, and this
file identifies the ideal class group of `R` with the quotient of the group of finite ideles by
the everywhere-integral units together with the principal finite ideles.

## Main definitions

* `IsDedekindDomain.FiniteAdeleRing.adicOrd`: the `v`-adic order of a finite idele, normalized so
  that a uniformizer at `v` has order `1`.
* `IsDedekindDomain.FiniteAdeleRing.toFractionalIdeal`: the homomorphism from the finite ideles to
  the invertible fractional ideals whose multiplicity at `v` is the `v`-adic order.
* `IsDedekindDomain.FiniteAdeleRing.integralUnits`: the finite ideles whose components are units of
  the local integers at every place, that is, the unit group of the integral finite adeles.
* `IsDedekindDomain.FiniteAdeleRing.toClassGroup`: the induced homomorphism to `ClassGroup R`.

## Main results

* `IsDedekindDomain.FiniteAdeleRing.count_coe_toFractionalIdeal`: the multiplicity of `v` in the
  fractional ideal of a finite idele is its `v`-adic order.  This is the characterizing property
  of `toFractionalIdeal`.
* `IsDedekindDomain.FiniteAdeleRing.toFractionalIdeal_surjective` and
  `IsDedekindDomain.FiniteAdeleRing.ker_toFractionalIdeal`: the fractional-ideal map is surjective
  with kernel the everywhere-integral units, so the invertible fractional ideals are the quotient
  of the finite ideles by `𝒪̂ˣ`.
* `IsDedekindDomain.FiniteAdeleRing.exists_forall_adicOrd_eq_count`: every invertible fractional
  ideal has a finite-idele representative with the corresponding local orders.
* `IsDedekindDomain.FiniteAdeleRing.ker_toClassGroup`: the kernel of the class-group map is the
  subgroup generated by the everywhere-integral units and the principal finite ideles.
* `IsDedekindDomain.FiniteAdeleRing.quotientEquivClassGroup`: the resulting isomorphism between
  the quotient of the finite ideles by that subgroup and `ClassGroup R`.

On a principal finite idele the order at `v` is the `v`-adic order of the global element it comes
from, so `toFractionalIdeal` extends Mathlib's `toPrincipalIdeal` along the diagonal embedding of
`Kˣ`: this is `IsDedekindDomain.FiniteAdeleRing.toFractionalIdeal_unitEmbedding`, and it is what
puts the principal finite ideles in the kernel of the class-group map.

The passage between the adic valuation and the multiplicity of a fractional ideal is
`IsDedekindDomain.HeightOneSpectrum.FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation`,
and the factorization of an invertible fractional ideal into prime powers is
`IsDedekindDomain.HeightOneSpectrum.FractionalIdeal.finprod_unitOfPrime_zpow_count`.

## References

* J. W. S. Cassels and A. Fröhlich, eds., *Algebraic Number Theory*, Chapter II, §16.
* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum

open scoped nonZeroDivisors

namespace IsDedekindDomain.FiniteAdeleRing

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-! ### The local orders of a finite idele -/

/-- Every component of a finite idele is nonzero. -/
theorem coe_units_apply_ne_zero (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    (x : 𝔸ᶠ[R, K]) v ≠ 0 :=
  (isUnit_iff.mp x.isUnit).1 v

/-- The valuation of a component of a finite idele is nonzero. -/
theorem valued_coe_units_apply_ne_zero (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    Valued.v ((x : 𝔸ᶠ[R, K]) v) ≠ 0 := by
  rw [ne_eq, Valuation.zero_iff]
  exact coe_units_apply_ne_zero x v

/-- A finite idele is a unit of the local integers at all but finitely many places. -/
theorem eventually_valued_coe_units_apply_eq_one (x : 𝔸ᶠ[R, K]ˣ) :
    ∀ᶠ v : HeightOneSpectrum R in Filter.cofinite, Valued.v ((x : 𝔸ᶠ[R, K]) v) = 1 :=
  (isUnit_iff.mp x.isUnit).2

/-- The valuations of a finite idele and of its inverse at a place are inverse to each other. -/
@[simp] theorem valued_coe_units_inv_apply (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    Valued.v (((x⁻¹ : 𝔸ᶠ[R, K]ˣ) : 𝔸ᶠ[R, K]) v) = (Valued.v ((x : 𝔸ᶠ[R, K]) v))⁻¹ :=
  (inv_eq_of_mul_eq_one_right (by
    rw [← map_mul, ← mul_apply, ← Units.val_mul, mul_inv_cancel, Units.val_one, one_apply,
      map_one])).symm

/-- The `v`-adic order of a finite idele `x`, that is, the exponent of `v` in the fractional
ideal that `x` defines.  The sign is chosen so that a uniformizer at `v` has order `1`. -/
noncomputable def adicOrd (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) : ℤ :=
  -WithZero.log (Valued.v ((x : 𝔸ᶠ[R, K]) v))

/-- The defining formula for the `v`-adic order of a finite idele. -/
theorem adicOrd_def (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    adicOrd x v = -WithZero.log (Valued.v ((x : 𝔸ᶠ[R, K]) v)) := by
  simp only [adicOrd]

/-- The `v`-adic order vanishes exactly at the places where the idele is a local unit. -/
@[simp] theorem adicOrd_eq_zero_iff {x : 𝔸ᶠ[R, K]ˣ} {v : HeightOneSpectrum R} :
    adicOrd x v = 0 ↔ Valued.v ((x : 𝔸ᶠ[R, K]) v) = 1 := by
  rw [adicOrd_def, neg_eq_zero]
  refine ⟨fun h ↦ ?_, fun h ↦ by rw [h, WithZero.log_one]⟩
  have hexp := WithZero.exp_log (valued_coe_units_apply_ne_zero x v)
  rwa [h, WithZero.exp_zero, eq_comm] at hexp

/-- The unit idele has order `0` everywhere. -/
@[simp] theorem adicOrd_one (v : HeightOneSpectrum R) : adicOrd (1 : 𝔸ᶠ[R, K]ˣ) v = 0 := by
  rw [adicOrd_eq_zero_iff, Units.val_one, one_apply, map_one]

/-- The `v`-adic order is additive in the finite idele. -/
@[simp] theorem adicOrd_mul (x y : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    adicOrd (x * y) v = adicOrd x v + adicOrd y v := by
  simp only [adicOrd_def]
  rw [Units.val_mul, mul_apply, map_mul,
    WithZero.log_mul (valued_coe_units_apply_ne_zero x v) (valued_coe_units_apply_ne_zero y v),
    neg_add]

/-- The order of the inverse of a finite idele is the negative of its order. -/
@[simp] theorem adicOrd_inv (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    adicOrd x⁻¹ v = -adicOrd x v := by
  simp only [adicOrd_def, valued_coe_units_inv_apply, WithZero.log_inv]

/-- A finite idele has order `0` at all but finitely many places. -/
theorem eventually_adicOrd_eq_zero (x : 𝔸ᶠ[R, K]ˣ) :
    ∀ᶠ v : HeightOneSpectrum R in Filter.cofinite, adicOrd x v = 0 :=
  (eventually_valued_coe_units_apply_eq_one x).mono fun _ h ↦ adicOrd_eq_zero_iff.mpr h

/-- The prime powers cut out by the orders of a finite idele have finite multiplicative support,
so their product over all height one primes is defined. -/
theorem hasFiniteMulSupport_unitOfPrime_zpow_adicOrd (x : 𝔸ᶠ[R, K]ˣ) :
    (Function.mulSupport fun v : HeightOneSpectrum R ↦ v.unitOfPrime K ^ adicOrd x v).Finite :=
  (Filter.eventually_cofinite.mp (eventually_adicOrd_eq_zero x)).subset fun _ hv hc ↦
    hv (by simp only [hc, zpow_zero])

/-! ### The fractional ideal of a finite idele -/

/-- The invertible fractional ideal `∏_v v ^ ord_v(x)` attached to a finite idele `x`. -/
noncomputable def toFractionalIdeal : 𝔸ᶠ[R, K]ˣ →* (FractionalIdeal R⁰ K)ˣ where
  toFun x := ∏ᶠ v : HeightOneSpectrum R, v.unitOfPrime K ^ adicOrd x v
  map_one' := by simp only [adicOrd_one, zpow_zero, finprod_one]
  map_mul' x y := by
    simp only [adicOrd_mul, zpow_add]
    exact finprod_mul_distrib (hasFiniteMulSupport_unitOfPrime_zpow_adicOrd x)
      (hasFiniteMulSupport_unitOfPrime_zpow_adicOrd y)

/-- The defining prime factorization of the fractional ideal of a finite idele. -/
theorem toFractionalIdeal_apply (x : 𝔸ᶠ[R, K]ˣ) :
    toFractionalIdeal x = ∏ᶠ v : HeightOneSpectrum R, v.unitOfPrime K ^ adicOrd x v := by
  simp only [toFractionalIdeal, MonoidHom.coe_mk, OneHom.coe_mk]

/-- **The characterizing property of `toFractionalIdeal`**: the multiplicity of `v` in the
fractional ideal of a finite idele is its `v`-adic order. -/
@[simp] theorem count_coe_toFractionalIdeal (x : 𝔸ᶠ[R, K]ˣ) (v : HeightOneSpectrum R) :
    FractionalIdeal.count K v (toFractionalIdeal x : FractionalIdeal R⁰ K) = adicOrd x v := by
  have hmap : ((∏ᶠ w : HeightOneSpectrum R, w.unitOfPrime K ^ adicOrd x w :
        (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) =
      ∏ᶠ w : HeightOneSpectrum R,
        ((w.unitOfPrime K ^ adicOrd x w : (FractionalIdeal R⁰ K)ˣ) : FractionalIdeal R⁰ K) :=
    MonoidHom.map_finprod (Units.coeHom (FractionalIdeal R⁰ K))
      (hasFiniteMulSupport_unitOfPrime_zpow_adicOrd x)
  rw [toFractionalIdeal_apply, hmap]
  simp only [Units.val_zpow_eq_zpow_val, HeightOneSpectrum.coe_unitOfPrime]
  exact FractionalIdeal.count_finprod K v _ (eventually_adicOrd_eq_zero x)

/-- A finite idele defines the trivial fractional ideal exactly when all its orders vanish. -/
@[simp] theorem toFractionalIdeal_eq_one_iff {x : 𝔸ᶠ[R, K]ˣ} :
    toFractionalIdeal x = 1 ↔ ∀ v : HeightOneSpectrum R, adicOrd x v = 0 := by
  refine ⟨fun h v ↦ ?_, fun h ↦ ?_⟩
  · rw [← count_coe_toFractionalIdeal x v, h, Units.val_one, FractionalIdeal.count_one]
  · rw [toFractionalIdeal_apply]
    simp only [h, zpow_zero, finprod_one]

/-- **Every invertible fractional ideal comes from a finite idele.** -/
theorem toFractionalIdeal_surjective :
    Function.Surjective (toFractionalIdeal (R := R) (K := K)) := by
  intro I
  -- choose a global element of the prescribed `v`-adic valuation at each place
  choose a ha using fun v : HeightOneSpectrum R ↦ (v.valuation_surjective K)
    (WithZero.exp (-FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)))
  have hval (v : HeightOneSpectrum R) :
      Valued.v ((a v : v.adicCompletion K)) =
        WithZero.exp (-FractionalIdeal.count K v (I : FractionalIdeal R⁰ K)) := by
    rw [valuedAdicCompletion_eq_valuation', ha v]
  have hcount := FractionalIdeal.finite_factors (I : FractionalIdeal R⁰ K)
  have hunit : ∀ᶠ v : HeightOneSpectrum R in Filter.cofinite,
      Valued.v ((a v : v.adicCompletion K)) = 1 := by
    filter_upwards [hcount] with v hv
    rw [hval v, hv, neg_zero, WithZero.exp_zero]
  -- assemble them into a finite adele, which is a unit because its valuations are nonzero
  have hint : ∀ᶠ v : HeightOneSpectrum R in Filter.cofinite,
      (a v : v.adicCompletion K) ∈ v.adicCompletionIntegers K := by
    filter_upwards [hunit] with v hv
    rw [mem_adicCompletionIntegers, hv]
  obtain ⟨b, hbapp⟩ : ∃ b : 𝔸ᶠ[R, K], ∀ v, b v = (a v : v.adicCompletion K) :=
    ⟨⟨fun v ↦ (a v : v.adicCompletion K), hint⟩, fun _ ↦ rfl⟩
  have hb : IsUnit b := isUnit_iff.mpr
    ⟨fun v h ↦ WithZero.exp_ne_zero (by rw [← hval v, ← hbapp v, h, map_zero]),
      by filter_upwards [hunit] with v hv; rw [hbapp v, hv]⟩
  refine ⟨hb.unit, ?_⟩
  have hord (v : HeightOneSpectrum R) :
      adicOrd hb.unit v = FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) := by
    rw [adicOrd_def, IsUnit.unit_spec, hbapp v, hval v, WithZero.log_exp, neg_neg]
  rw [toFractionalIdeal_apply]
  simp only [hord]
  exact (FractionalIdeal.finprod_unitOfPrime_zpow_count I).symm

/-- Every invertible fractional ideal has a finite-idele representative whose order at each place
is the multiplicity of that place in the ideal. -/
theorem exists_forall_adicOrd_eq_count (I : (FractionalIdeal R⁰ K)ˣ) :
    ∃ x : 𝔸ᶠ[R, K]ˣ,
      ∀ v : HeightOneSpectrum R,
        adicOrd x v = FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) := by
  obtain ⟨x, hx⟩ := toFractionalIdeal_surjective I
  refine ⟨x, fun v ↦ ?_⟩
  rw [← count_coe_toFractionalIdeal x v, hx]

/-! ### The everywhere-integral units -/

variable (R K) in
/-- The finite ideles that are units of the local integers at every place: the unit group of the
integral finite adeles `∏_v 𝒪_v`. -/
def integralUnits : Subgroup 𝔸ᶠ[R, K]ˣ where
  carrier := {x | ∀ v : HeightOneSpectrum R, Valued.v ((x : 𝔸ᶠ[R, K]) v) = 1}
  one_mem' v := by rw [Units.val_one, one_apply, map_one]
  mul_mem' hx hy v := by rw [Units.val_mul, mul_apply, map_mul, hx v, hy v, one_mul]
  inv_mem' {x} hx v := by rw [valued_coe_units_inv_apply, hx v, inv_one]

/-- Membership in `integralUnits`, unfolded. -/
@[simp] theorem mem_integralUnits_iff {x : 𝔸ᶠ[R, K]ˣ} :
    x ∈ integralUnits R K ↔ ∀ v : HeightOneSpectrum R, Valued.v ((x : 𝔸ᶠ[R, K]) v) = 1 :=
  Iff.rfl

/-- A finite idele is an everywhere-integral unit exactly when both it and its inverse are
integral at every place. -/
theorem mem_integralUnits_iff_forall_mem_adicCompletionIntegers {x : 𝔸ᶠ[R, K]ˣ} :
    x ∈ integralUnits R K ↔ ∀ v : HeightOneSpectrum R,
      (x : 𝔸ᶠ[R, K]) v ∈ v.adicCompletionIntegers K ∧
        ((x⁻¹ : 𝔸ᶠ[R, K]ˣ) : 𝔸ᶠ[R, K]) v ∈ v.adicCompletionIntegers K := by
  simp only [mem_integralUnits_iff, mem_adicCompletionIntegers, valued_coe_units_inv_apply]
  refine forall_congr' fun v ↦ ?_
  have hpos : 0 < Valued.v ((x : 𝔸ᶠ[R, K]) v) :=
    zero_lt_iff.mpr (valued_coe_units_apply_ne_zero x v)
  exact ⟨fun h ↦ ⟨h.le, by rw [h, inv_one]⟩,
    fun ⟨h₁, h₂⟩ ↦ le_antisymm h₁ ((inv_le_one₀ hpos).mp h₂)⟩

/-- The principal finite idele of a unit of `R` is an everywhere-integral unit. -/
@[simp 1100] theorem unitEmbedding_map_algebraMap_mem_integralUnits (u : Rˣ) :
    unitEmbedding R K (Units.map (algebraMap R K) u) ∈ integralUnits R K := by
  refine mem_integralUnits_iff.mpr fun v ↦ ?_
  rw [unitEmbedding_apply, algebraMap_apply, valuedAdicCompletion_eq_valuation', Units.coe_map,
    MonoidHom.coe_ofClass, valuation_eq_one_iff_notMem]
  exact fun h ↦ v.isPrime.ne_top (Ideal.eq_top_of_isUnit_mem _ h u.isUnit)

/-- The finite ideles defining the trivial fractional ideal are exactly the everywhere-integral
units. -/
theorem ker_toFractionalIdeal :
    (toFractionalIdeal (R := R) (K := K)).ker = integralUnits R K := by
  ext x
  simp only [MonoidHom.mem_ker, toFractionalIdeal_eq_one_iff, mem_integralUnits_iff,
    adicOrd_eq_zero_iff]

/-! ### Principal finite ideles and the class group -/

/-- The fractional ideal of a principal finite idele is the corresponding principal fractional
ideal. -/
@[simp] theorem toFractionalIdeal_unitEmbedding (u : Kˣ) :
    toFractionalIdeal (unitEmbedding R K u) = toPrincipalIdeal R K u := by
  have hcount (v : HeightOneSpectrum R) :
      FractionalIdeal.count K v (toFractionalIdeal (unitEmbedding R K u) : FractionalIdeal R⁰ K) =
        FractionalIdeal.count K v (toPrincipalIdeal R K u : FractionalIdeal R⁰ K) := by
    rw [count_coe_toFractionalIdeal, adicOrd_def,
      FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation K v u, unitEmbedding_apply,
      algebraMap_apply, valuedAdicCompletion_eq_valuation']
  rw [FractionalIdeal.finprod_unitOfPrime_zpow_count (toFractionalIdeal (unitEmbedding R K u)),
    FractionalIdeal.finprod_unitOfPrime_zpow_count (toPrincipalIdeal R K u)]
  simp only [hcount]

variable (R K) in
/-- The ideal class attached to a finite idele. -/
noncomputable def toClassGroup : 𝔸ᶠ[R, K]ˣ →* ClassGroup R :=
  (ClassGroup.mk K).comp toFractionalIdeal

/-- The ideal class of a finite idele is the class of its fractional ideal. -/
@[simp] theorem toClassGroup_apply (x : 𝔸ᶠ[R, K]ˣ) :
    toClassGroup R K x = ClassGroup.mk K (toFractionalIdeal x) := by
  simp only [toClassGroup, MonoidHom.coe_comp, Function.comp_apply]

/-- **Every ideal class is the class of a finite idele.** -/
theorem toClassGroup_surjective : Function.Surjective (toClassGroup R K) := by
  intro c
  obtain ⟨J, hJ⟩ := ClassGroup.mk0_surjective (R := R) c
  obtain ⟨x, hx⟩ := toFractionalIdeal_surjective (K := K) (FractionalIdeal.mk0 K J)
  exact ⟨x, by rw [toClassGroup_apply, hx, ClassGroup.mk_mk0, hJ]⟩

/-- **The finite-idele description of the ideal class group**: the kernel of the class-group map
is generated by the everywhere-integral units and the principal finite ideles. -/
theorem ker_toClassGroup :
    (toClassGroup R K).ker = integralUnits R K ⊔ (unitEmbedding R K).range := by
  refine le_antisymm (fun x hx ↦ ?_) (sup_le (fun x hx ↦ ?_) ?_)
  · rw [MonoidHom.mem_ker, toClassGroup_apply, ClassGroup.mk_eq_one_iff_exists] at hx
    obtain ⟨u, hu⟩ := hx
    have hmem : x * (unitEmbedding R K u)⁻¹ ∈ integralUnits R K := by
      rw [← ker_toFractionalIdeal, MonoidHom.mem_ker, map_mul, map_inv,
        toFractionalIdeal_unitEmbedding, hu, mul_inv_cancel]
    have hx' : x * (unitEmbedding R K u)⁻¹ * unitEmbedding R K u ∈
        integralUnits R K ⊔ (unitEmbedding R K).range :=
      Subgroup.mul_mem_sup hmem (MonoidHom.mem_range.mpr ⟨u, rfl⟩)
    simpa using hx'
  · have hx' : toFractionalIdeal x = 1 := by
      rw [← MonoidHom.mem_ker, ker_toFractionalIdeal]
      exact hx
    rw [MonoidHom.mem_ker, toClassGroup_apply, hx', map_one]
  · rintro _ ⟨u, rfl⟩
    rw [MonoidHom.mem_ker, toClassGroup_apply, toFractionalIdeal_unitEmbedding,
      ClassGroup.mk_toPrincipalIdeal]

variable (R K) in
/-- **The ideal class group is the quotient of the finite ideles** by the everywhere-integral
units and the principal finite ideles. -/
noncomputable def quotientEquivClassGroup :
    𝔸ᶠ[R, K]ˣ ⧸ (integralUnits R K ⊔ (unitEmbedding R K).range) ≃* ClassGroup R :=
  (QuotientGroup.quotientMulEquivOfEq ker_toClassGroup.symm).trans
    (QuotientGroup.quotientKerEquivOfSurjective _ toClassGroup_surjective)

/-- `quotientEquivClassGroup` sends the class of a finite idele to its ideal class. -/
@[simp] theorem quotientEquivClassGroup_mk (x : 𝔸ᶠ[R, K]ˣ) :
    quotientEquivClassGroup R K (QuotientGroup.mk x) = toClassGroup R K x := by
  simp only [quotientEquivClassGroup, MulEquiv.trans_apply,
    QuotientGroup.quotientMulEquivOfEq_mk, QuotientGroup.quotientKerEquivOfSurjective,
    QuotientGroup.quotientKerEquivOfRightInverse_apply, QuotientGroup.kerLift_mk]

end IsDedekindDomain.FiniteAdeleRing
