/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Certificate.Evidence
public import TauCeti.FieldTheory.GaloisGroups.Label

import TauCeti.FieldTheory.GaloisGroups.Certificate.Routes

/-!
# Quintic Galois-group certificates and their soundness

A `TauCeti.QuinticCertificate` is a finite package of evidence about a monic integral quintic
`f`, with one constructor for each sound route to a transitive-group label of degree five. Every
constructor starts with a prime `p` modulo which `f` is irreducible; the further evidence is:

| constructor | further evidence | label |
|---|---|---|
| `cyclic p b` | a second root `b` of `f` in `ℚ[X]/(f)` | `5T1` |
| `dihedral p q s a` | `disc f = s²`, sextic root `a`, factor degrees `(1,2,2)` modulo `q` | `5T2` |
| `frobeniusF20 p a` | `disc f` not a square, sextic root `a` | `5T3` |
| `alternating p q s` | `disc f = s²`, factor degrees `(1,1,3)` modulo `q` | `5T4` |
| `symmetric p q` | factor degrees `(2,3)` modulo `q` | `5T5` |

Every factorization is taken modulo a prime not dividing `disc f`, as packaged by
`TauCeti.HasFactorDegrees`. A sextic root is an integral root of the resolvent sextic
`TauCeti.resolventSextic f` with nonzero discriminant, as packaged by `TauCeti.HasSexticRoot`.
The irreducible reduction modulo `p` makes the Galois action transitive, and it also forces `f`
to have degree five.

`TauCeti.QuinticCertificate.Verifies` lists the conditions the evidence must satisfy, and
`TauCeti.QuinticCertificate.check` is the Boolean verdict on them. Every condition is finite: an
equation or a non-square condition on integers, a congruence in `ℚ[X]`, or a factorization over
`ZMod p`.

The certificates are sound, and only sound: a certificate that verifies proves its label. Nothing
here says that a certificate exists for a given quintic, or looks for one. Producing the primes a
certificate needs is a question about the density of Frobenius elements. The discriminant and the
sextic alone cannot separate `5T1` from `5T2`, which is why the cyclic and dihedral routes carry
further evidence.

## Main definitions

* `TauCeti.QuinticCertificate`: the evidence for one route to a label.
* `TauCeti.QuinticCertificate.label`: the label a certificate claims.
* `TauCeti.QuinticCertificate.Verifies`: the conditions the evidence must satisfy.
* `TauCeti.QuinticCertificate.check`: the Boolean verdict on those conditions.

## Main results

* `TauCeti.QuinticCertificate.Verifies.hasGaloisLabel`: a verified certificate proves its label.
* `TauCeti.QuinticCertificate.check_sound`: the same statement for the Boolean verdict.

## References

* D. S. Dummit, *Solving solvable quintics*, Mathematics of Computation **57** (1991), §2.
* H. Cohen, *A Course in Computational Algebraic Number Theory*, §6.3.
-/

public section
noncomputable section

open Polynomial

namespace TauCeti

/-- A certificate for the Galois group of a monic integral quintic. Each constructor is one sound
route to a transitive-group label of degree five, and its arguments are the evidence that route
reads: primes at which to factor, a square root of the discriminant, a root of the resolvent
sextic, or a second root in the field generated by one root. The conditions this evidence must
satisfy are `TauCeti.QuinticCertificate.Verifies`. -/
inductive QuinticCertificate : Type
  /-- `5T1`: irreducible modulo `p`, and `b` represents a second root of `f` in `ℚ[X]/(f)`. -/
  | cyclic (p : ℕ) (b : ℚ[X])
  /-- `5T2`: irreducible modulo `p`, discriminant `s²`, a root `a` of the separable resolvent
  sextic, and factor degrees `(1,2,2)` modulo `q`, exhibiting an element of order two. -/
  | dihedral (p q : ℕ) (s a : ℤ)
  /-- `5T3`: irreducible modulo `p`, non-square discriminant, and a root `a` of the separable
  resolvent sextic. -/
  | frobeniusF20 (p : ℕ) (a : ℤ)
  /-- `5T4`: irreducible modulo `p`, discriminant `s²`, and factor degrees `(1,1,3)` modulo `q`,
  exhibiting an element of order three. -/
  | alternating (p q : ℕ) (s : ℤ)
  /-- `5T5`: irreducible modulo `p`, and factor degrees `(2,3)` modulo `q`, exhibiting an element
  of order six. -/
  | symmetric (p q : ℕ)

namespace QuinticCertificate

/-- The transitive-group label a certificate claims; index `j` is the label `5T(j+1)`. -/
def label : QuinticCertificate → TransitiveGroupIndex 5
  | cyclic .. => ⟨0, by simp⟩
  | dihedral .. => ⟨1, by simp⟩
  | frobeniusF20 .. => ⟨2, by simp⟩
  | alternating .. => ⟨3, by simp⟩
  | symmetric .. => ⟨4, by simp⟩

/-- The conditions that the evidence of a certificate must satisfy for the monic integral
quintic `f`. Each route asks for an irreducible reduction of `f` modulo a prime not dividing its
discriminant, together with the further evidence that separates its label from the others. -/
def Verifies : QuinticCertificate → ℤ[X] → Prop
  | cyclic p b, f => HasFactorDegrees f p {5} ∧ HasSecondRootInRootField f b
  | dihedral p q s a, f =>
      HasFactorDegrees f p {5} ∧ f.discr = s ^ 2 ∧ HasSexticRoot f a ∧
        HasFactorDegrees f q {1, 2, 2}
  | frobeniusF20 p a, f => HasFactorDegrees f p {5} ∧ ¬ IsSquare f.discr ∧ HasSexticRoot f a
  | alternating p q s, f =>
      HasFactorDegrees f p {5} ∧ f.discr = s ^ 2 ∧ HasFactorDegrees f q {1, 1, 3}
  | symmetric p q, f => HasFactorDegrees f p {5} ∧ HasFactorDegrees f q {2, 3}

open scoped Classical in
/-- The Boolean verdict on the verification conditions of a certificate. -/
def check (cert : QuinticCertificate) (f : ℤ[X]) : Bool :=
  decide (cert.Verifies f)

variable {cert : QuinticCertificate} {f : ℤ[X]}

section label

variable (p q : ℕ) (s a : ℤ) (b : ℚ[X])

/-- A cyclic-route certificate claims the label `5T1`. -/
@[simp] theorem label_cyclic : (cyclic p b).label = ⟨0, by simp⟩ := (rfl)

/-- A dihedral-route certificate claims the label `5T2`. -/
@[simp] theorem label_dihedral : (dihedral p q s a).label = ⟨1, by simp⟩ := (rfl)

/-- A Frobenius-route certificate claims the label `5T3`. -/
@[simp] theorem label_frobeniusF20 : (frobeniusF20 p a).label = ⟨2, by simp⟩ := (rfl)

/-- An alternating-route certificate claims the label `5T4`. -/
@[simp] theorem label_alternating : (alternating p q s).label = ⟨3, by simp⟩ := (rfl)

/-- A symmetric-route certificate claims the label `5T5`. -/
@[simp] theorem label_symmetric : (symmetric p q).label = ⟨4, by simp⟩ := (rfl)

end label

section Verifies

variable {p q : ℕ} {s a : ℤ} {b : ℚ[X]}

/-- The verification conditions of the cyclic route. -/
@[simp] theorem verifies_cyclic_iff :
    (cyclic p b).Verifies f ↔ HasFactorDegrees f p {5} ∧ HasSecondRootInRootField f b :=
  (Iff.rfl)

/-- The verification conditions of the dihedral route. -/
@[simp] theorem verifies_dihedral_iff :
    (dihedral p q s a).Verifies f ↔ HasFactorDegrees f p {5} ∧ f.discr = s ^ 2 ∧
      HasSexticRoot f a ∧ HasFactorDegrees f q {1, 2, 2} :=
  (Iff.rfl)

/-- The verification conditions of the Frobenius route. -/
@[simp] theorem verifies_frobeniusF20_iff :
    (frobeniusF20 p a).Verifies f ↔
      HasFactorDegrees f p {5} ∧ ¬ IsSquare f.discr ∧ HasSexticRoot f a :=
  (Iff.rfl)

/-- The verification conditions of the alternating route. -/
@[simp] theorem verifies_alternating_iff :
    (alternating p q s).Verifies f ↔
      HasFactorDegrees f p {5} ∧ f.discr = s ^ 2 ∧ HasFactorDegrees f q {1, 1, 3} :=
  (Iff.rfl)

/-- The verification conditions of the symmetric route. -/
@[simp] theorem verifies_symmetric_iff :
    (symmetric p q).Verifies f ↔ HasFactorDegrees f p {5} ∧ HasFactorDegrees f q {2, 3} :=
  (Iff.rfl)

end Verifies

/-- A certificate checks exactly when its evidence verifies. -/
@[simp]
theorem check_eq_true_iff : cert.check f = true ↔ cert.Verifies f := by
  simp only [check, decide_eq_true_eq]

/-- **Soundness of quintic certificates.** A certificate whose evidence verifies for a monic
integral polynomial proves the label it claims for the Galois group of that polynomial over
`ℚ`. -/
theorem Verifies.hasGaloisLabel (hf : f.Monic) (h : cert.Verifies f) :
    HasGaloisLabel (f.map (Int.castRingHom ℚ)) cert.label := by
  cases cert with
  | cyclic p b =>
    obtain ⟨hp, hb⟩ := verifies_cyclic_iff.mp h
    exact hasGaloisLabel_five_zero_of_hasSecondRootInRootField hf (hp.irreducible_map_rat hf)
      (by simpa using (hp.sum_eq_natDegree hf).symm) hb
  | dihedral p q s a =>
    obtain ⟨hp, hs, ha, hq⟩ := verifies_dihedral_iff.mp h
    exact hasGaloisLabel_five_one_of_isSquare_discr_of_hasSexticRoot_of_hasFactorDegrees hf
      (hp.irreducible_map_rat hf) ⟨s, hs.trans (sq s)⟩ ha hq
  | frobeniusF20 p a =>
    obtain ⟨hp, hs, ha⟩ := verifies_frobeniusF20_iff.mp h
    exact hasGaloisLabel_five_two_of_not_isSquare_discr_of_hasSexticRoot hf
      (hp.irreducible_map_rat hf) (by simpa using (hp.sum_eq_natDegree hf).symm) hs ha
  | alternating p q s =>
    obtain ⟨hp, hs, hq⟩ := verifies_alternating_iff.mp h
    exact hasGaloisLabel_five_three_of_isSquare_discr_of_hasFactorDegrees hf
      (hp.irreducible_map_rat hf) ⟨s, hs.trans (sq s)⟩ hq
  | symmetric p q =>
    obtain ⟨hp, hq⟩ := verifies_symmetric_iff.mp h
    exact hasGaloisLabel_five_four_of_hasFactorDegrees hf (hp.irreducible_map_rat hf) hq

/-- **Soundness of the quintic checker.** A certificate that checks for a monic integral
polynomial proves the label it claims for the Galois group of that polynomial over `ℚ`. -/
theorem check_sound (hf : f.Monic) (h : cert.check f = true) :
    HasGaloisLabel (f.map (Int.castRingHom ℚ)) cert.label :=
  (check_eq_true_iff.mp h).hasGaloisLabel hf

end QuinticCertificate

end TauCeti
