/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisGroups.Certificate.Check

import TauCeti.FieldTheory.GaloisGroups.FactorDegrees
import Mathlib.RingTheory.Polynomial.Cyclotomic.Factorization
import Mathlib.Tactic.ComputeDegree
import Mathlib.Tactic.LinearCombination

/-!
# A cyclic quintic certificate

The polynomial `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` is irreducible modulo `2`.
Together with its second root `X² - 2` in the root field, this supplies a
cyclic-route certificate and proves that its Galois group has label `5T1`.
This polynomial defines the LMFDB number field `5.5.14641.1`.

## Main results

* `TauCeti.hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the second-root evidence.
* `Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two`:
  the irreducible reduction at `2`.
* `Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two`:
  the factor degrees at `2`.
* `TauCeti.QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the certificate checks.
* `TauCeti.hasGaloisLabel_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1`:
  the Galois label is `5T1`.
-/

public section
noncomputable section

open Polynomial

namespace TauCeti

/-- The polynomial `X² - 2` supplies formal second-root evidence for the cyclic quintic
`X⁵ + X⁴ - 4X³ - 3X² + 3X + 1`. For this monic irreducible quintic, it represents a second
root in the field generated by one root. -/
theorem hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    HasSecondRootInRootField (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1)
      (X ^ 2 - 2) := by
  rw [hasSecondRootInRootField_iff]
  norm_num only [Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul,
    Polynomial.map_pow, Polynomial.map_X, Polynomial.map_one, Polynomial.map_ofNat]
  let f : ℚ[X] := X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1
  have hf : f.Monic := by
    dsimp [f]
    monicity!
  have hsecond : (f.comp (X ^ 2 - 2)) %ₘ f = 0 ∧ (X ^ 2 - 2) %ₘ f ≠ X %ₘ f := by
    constructor
    · rw [modByMonic_eq_zero_iff_dvd hf]
      refine ⟨X ^ 5 - X ^ 4 - 4 * X ^ 3 + 3 * X ^ 2 + 3 * X - 1, ?_⟩
      dsimp [f]
      simp
      ring_nf
    · have hb : (X ^ 2 - 2 : ℚ[X]) %ₘ f = X ^ 2 - 2 :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hbdeg : (X ^ 2 - 2 : ℚ[X]).degree = 2 := by compute_degree!
          rw [hfdeg, hbdeg]
          decide)
      have hX : (X : ℚ[X]) %ₘ f = X :=
        (modByMonic_eq_self_iff hf).mpr (by
          have hfdeg : f.degree = 5 := by dsimp [f]; compute_degree!
          have hXdeg : (X : ℚ[X]).degree = 1 := by compute_degree!
          rw [hfdeg, hXdeg]
          decide)
      rw [hb, hX]
      intro h
      have := congrArg (fun q : ℚ[X] ↦ q.coeff 0) h
      norm_num at this
  simpa only [f] using hsecond

/-- The reduction of the cyclic quintic modulo `2` is irreducible. -/
theorem _root_.Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two :
    Irreducible (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]) := by
  have hpn : ¬ 2 ∣ 31 := by decide
  apply ZMod.irreducible_of_dvd_cyclotomic_of_natDegree (n := 31) hpn
  · have : Fact (Nat.Prime 31) := ⟨by decide⟩
    rw [cyclotomic_prime]
    refine ⟨∑ i ∈ ({0, 3, 4, 8, 9, 10, 11, 14, 16, 18, 19, 21, 22, 23, 25} : Finset ℕ),
      X ^ i, ?_⟩
    norm_num [Finset.sum_range_succ, Finset.sum_range_zero] at *
    ring_nf
    have h3 : (3 : (ZMod 2)[X]) = 1 := by
      linear_combination (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
    have h5 : (5 : (ZMod 2)[X]) = 1 := by
      linear_combination 2 * (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
    rw [h3, h5]
    ring
  · have hdegree : (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]).natDegree = 5 := by
      compute_degree!
    have horder : orderOf (ZMod.unitOfCoprime 2 (by decide : Nat.Coprime 2 31)) = 5 := by
      apply orderOf_eq_of_pow_and_pow_div_prime (by decide)
      · apply Units.ext
        decide
      · intro p hp hpdvd
        have hple : p ≤ 5 := Nat.le_of_dvd (by decide) hpdvd
        have hp2 := hp.two_le
        have heq : p = 5 := by
          interval_cases p <;> simp_all
        subst p
        apply Ne.intro
        intro h
        have h' := congrArg Units.val h
        have hne : (2 : ZMod 31) ≠ 1 := by decide
        exact hne h'
    simpa only [hdegree] using horder.symm

/-- The cyclic quintic has a single irreducible factor of degree five modulo `2`. -/
@[simp] theorem _root_.Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two :
    (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).factorDegrees 2 = {5} := by
  rw [Polynomial.factorDegrees_eq_singleton_iff]
  have hmap : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
      (Int.castRingHom (ZMod 2)) = (X ^ 5 + X ^ 4 + X ^ 2 + X + 1 : (ZMod 2)[X]) := by
    norm_num
    linear_combination (-2 * X ^ 3 - 2 * X ^ 2 + X : (ZMod 2)[X]) *
      (CharTwo.two_eq_zero : (2 : (ZMod 2)[X]) = 0)
  rw [hmap]
  constructor
  · exact Polynomial.irreducible_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_zmod_two
  · compute_degree!

/-- The cyclic-route certificate for the cyclic quintic checks. -/
@[simp] theorem QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    (QuinticCertificate.cyclic 2 (X ^ 2 - 2)).check
      (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1) = true := by
  have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  have hf : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).Monic := by
    monicity!
  have hirr : Irreducible ((X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
      (Int.castRingHom (ZMod 2))) :=
    (Polynomial.factorDegrees_eq_singleton_iff.mp
      Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two).1
  have hgood : IsGoodPrime (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1) 2 :=
    (isGoodPrime_iff _ 2).mpr <|
      (hf.separable_map_zmod_iff_not_dvd_discr 2).mp
        (PerfectField.separable_of_irreducible hirr)
  rw [QuinticCertificate.check_eq_true_iff, QuinticCertificate.verifies_cyclic_iff]
  exact ⟨HasFactorDegrees.mk hgood
      Polynomial.factorDegrees_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1_two,
    hasSecondRootInRootField_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1⟩

/-- The cyclic quintic `X⁵ + X⁴ - 4X³ - 3X² + 3X + 1` has Galois label `5T1`. -/
theorem hasGaloisLabel_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1 :
    HasGaloisLabel
      ((X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).map
        (Int.castRingHom ℚ)) (⟨0, by simp⟩ : TransitiveGroupIndex 5) := by
  have hf : (X ^ 5 + X ^ 4 - 4 * X ^ 3 - 3 * X ^ 2 + 3 * X + 1 : ℤ[X]).Monic := by
    monicity!
  have h := QuinticCertificate.check_sound hf
    QuinticCertificate.check_X5_add_X4_sub_4X3_sub_3X2_add_3X_add_1
  rwa [QuinticCertificate.label_cyclic] at h

end TauCeti
