/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.Curves.StableReduction.Picard.Basic
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# The Picard group of a weighted two-component numerical type

For the numerical type with two components of multiplicity one and weight two, meeting
twice, the weighted intersection relations are generated by `(-1, 1)`. Thus its Picard
group is infinite cyclic. The unweighted intersection relations are generated by
`(-2, 2)`, and their cokernel has nonzero two-torsion. This calculation distinguishes
the weighted Picard group from the raw intersection cokernel in the numerical argument
for stable reduction.
-/

public section

namespace TauCeti

namespace NumericalType

open Matrix

/-- Two components of multiplicity one, weight two and genus one, meeting doubly: a numerical
type of signed genus three. -/
noncomputable abbrev twoComponentWeightTwoExample : NumericalType.{0} where
  Component := Fin 2
  multiplicity _ := 1
  weight _ := 2
  intersection := !![-2, 2; 2, -2]
  intersection_isSymm := Matrix.IsSymm.ext fun i j ↦ by fin_cases i <;> fin_cases j <;> rfl
  offDiagonal_nonneg i j h := by
    fin_cases i <;> fin_cases j <;> first | exact absurd rfl h | decide
  connected := by
    have key : ∀ i j : Fin 2, i ≠ j → (0 : ℤ) < !![(-2 : ℤ), 2; 2, -2] i j := by
      intro i j h
      fin_cases i <;> fin_cases j <;> first | exact absurd rfl h | decide
    intro i j
    rcases eq_or_ne i j with rfl | h
    · exact Relation.ReflTransGen.refl
    · exact Relation.ReflTransGen.single ⟨h, key i j h⟩
  fiber_relation i := by fin_cases i <;> decide
  weight_dvd i j := by fin_cases i <;> fin_cases j <;> decide
  genus _ := 1

/-- Each component of the two-component weight-two example has multiplicity one. -/
@[simp]
lemma twoComponentWeightTwoExample_multiplicity (i : Fin 2) :
    twoComponentWeightTwoExample.multiplicity i = 1 := rfl

/-- Each component of the two-component weight-two example has weight two. -/
@[simp]
lemma twoComponentWeightTwoExample_weight (i : Fin 2) :
    twoComponentWeightTwoExample.weight i = 2 := rfl

/-- Each component of the two-component weight-two example has genus one. -/
@[simp]
lemma twoComponentWeightTwoExample_genus (i : Fin 2) :
    twoComponentWeightTwoExample.genus i = 1 := rfl

/-- The two-component weight-two example has signed genus three. -/
@[simp]
lemma twoComponentWeightTwoExample_arithmeticGenus :
    twoComponentWeightTwoExample.arithmeticGenus = 3 := by
  rw [arithmeticGenus_def]
  decide

example :
    ({ twoComponentWeightTwoExample with genus := fun _ ↦ 0 } : NumericalType).arithmeticGenus =
      -1 := by
  rw [arithmeticGenus_def]
  decide

/-- The weighted intersection matrix of the two-component weight-two example. -/
@[simp]
lemma twoComponentWeightTwoExample_weightedIntersection :
    twoComponentWeightTwoExample.weightedIntersection = !![-1, 1; 1, -1] := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [weightedIntersection_apply, twoComponentWeightTwoExample]

/-- The intersection matrix of the two-component weight-two example. -/
@[simp]
lemma twoComponentWeightTwoExample_intersection :
    twoComponentWeightTwoExample.intersection = !![-2, 2; 2, -2] := rfl

/-- The principal multidegrees in the weight-two example are exactly the pairs with sum zero. -/
@[simp]
theorem twoComponentWeightTwoExample_mem_principalDivisors_iff (d : Fin 2 → ℤ) :
    d ∈ twoComponentWeightTwoExample.principalDivisors ↔ d 0 + d 1 = 0 := by
  rw [twoComponentWeightTwoExample.mem_principalDivisors_iff]
  constructor
  · rintro ⟨v, rfl⟩
    rw [twoComponentWeightTwoExample_weightedIntersection]
    simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two]
    omega
  · intro hd
    refine ⟨![0, d 0], ?_⟩
    funext i
    fin_cases i
    · simp [twoComponentWeightTwoExample_weightedIntersection, Matrix.vecMul_apply_eq_sum,
        Fin.sum_univ_two]
    · simp [twoComponentWeightTwoExample_weightedIntersection, Matrix.vecMul_apply_eq_sum,
        Fin.sum_univ_two]
      omega

private def twoComponentWeightTwoExampleSum : (Fin 2 → ℤ) →ₗ[ℤ] ℤ :=
  (LinearMap.proj 0 : (Fin 2 → ℤ) →ₗ[ℤ] ℤ) + LinearMap.proj 1

private lemma twoComponentWeightTwoExampleSum_surjective :
    Function.Surjective twoComponentWeightTwoExampleSum :=
  fun n ↦ ⟨![n, 0], by simp [twoComponentWeightTwoExampleSum]⟩

private lemma twoComponentWeightTwoExample_ker_sum :
    LinearMap.ker twoComponentWeightTwoExampleSum =
      twoComponentWeightTwoExample.principalDivisors := by
  ext d
  simpa [twoComponentWeightTwoExampleSum, LinearMap.mem_ker] using
    (twoComponentWeightTwoExample_mem_principalDivisors_iff d).symm

/-- The weighted Picard group of the two-component example is infinite cyclic, with a
multidegree sent to the sum of its two coordinates. -/
noncomputable def twoComponentWeightTwoExamplePicLinearEquivInt :
    twoComponentWeightTwoExample.Pic ≃ₗ[ℤ] ℤ :=
  (Submodule.quotEquivOfEq _ _ twoComponentWeightTwoExample_ker_sum.symm) |>.trans
    (twoComponentWeightTwoExampleSum.quotKerEquivOfSurjective
      twoComponentWeightTwoExampleSum_surjective)

/-- The Picard-class isomorphism is the sum of multidegrees. -/
@[simp]
theorem twoComponentWeightTwoExamplePicLinearEquivInt_mk (d : Fin 2 → ℤ) :
    twoComponentWeightTwoExamplePicLinearEquivInt (Submodule.Quotient.mk d) = d 0 + d 1 := by
  simp only [twoComponentWeightTwoExamplePicLinearEquivInt, LinearEquiv.trans_apply,
    Submodule.quotEquivOfEq_mk]
  rw [LinearMap.quotKerEquivOfSurjective_apply_mk]
  simp [twoComponentWeightTwoExampleSum]

/-- The weighted Picard group of the two-component example is torsion-free. -/
instance twoComponentWeightTwoExample_isTorsionFree_pic :
    Module.IsTorsionFree ℤ twoComponentWeightTwoExample.Pic :=
  twoComponentWeightTwoExamplePicLinearEquivInt.injective.moduleIsTorsionFree _ (map_smul _)

/-- The weighted Picard group has no nonzero two-torsion. -/
theorem twoComponentWeightTwoExample_pic_eq_zero_of_two_smul_eq_zero
    (x : twoComponentWeightTwoExample.Pic) (hx : (2 : ℤ) • x = 0) :
    x = 0 :=
  (smul_eq_zero_iff_right two_ne_zero).mp hx

/-- The raw intersection cokernel of the weight-two example contains nonzero two-torsion:
the class of `(1, -1)` has order two. -/
theorem twoComponentWeightTwoExample_coker_has_two_torsion :
    ∃ x : twoComponentWeightTwoExample.Coker, x ≠ 0 ∧ (2 : ℤ) • x = 0 := by
  let x : twoComponentWeightTwoExample.Coker := Submodule.Quotient.mk (![1, -1] : Fin 2 → ℤ)
  refine ⟨x, ?_, ?_⟩
  · intro hx
    have hmem : (![1, -1] : Fin 2 → ℤ) ∈ twoComponentWeightTwoExample.intersectionRelations :=
      (Submodule.Quotient.mk_eq_zero _).mp hx
    obtain ⟨v, hv⟩ := twoComponentWeightTwoExample.mem_intersectionRelations_iff.mp hmem
    rw [twoComponentWeightTwoExample_intersection] at hv
    have h0 := congrFun hv 0
    simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two] at h0
    omega
  · dsimp only [x]
    rw [← Submodule.Quotient.mk_smul]
    apply (Submodule.Quotient.mk_eq_zero _).mpr
    refine twoComponentWeightTwoExample.mem_intersectionRelations_iff.mpr ⟨![0, 1], ?_⟩
    rw [twoComponentWeightTwoExample_intersection]
    funext i
    fin_cases i <;>
      simp [Matrix.vecMul_apply_eq_sum, Fin.sum_univ_two, Pi.smul_apply]

private noncomputable abbrev unequalWeights : NumericalType.{0} :=
  { twoComponentWeightTwoExample with
    weight := ![1, 2]
    weight_dvd := by
      intro i j
      fin_cases i <;> fin_cases j <;> decide }

/-- In the unevenly weighted example, division is by the destination weight: the first
relation is `(-2, 1)`. -/
example : unequalWeights.weightedIntersection 0 0 = -2 ∧
    unequalWeights.weightedIntersection 0 1 = 1 := by
  constructor <;>
    norm_num [weightedIntersection_apply, unequalWeights, twoComponentWeightTwoExample]

end NumericalType

end TauCeti
