/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import Mathlib.MeasureTheory.Measure.FiniteMeasureExt

/-!
# Finite measures are determined by a separating submonoid of test functions

Two finite Borel measures on a Polish space are equal once their integrals agree on a family of
real bounded continuous functions that separates points, contains the constant `1` and is closed
under multiplication.

This criterion applies when the known integrals are moments of a multiplicative family, such as
coordinate monomials or graph homomorphism densities. The constant `1` ensures that the measures
have the same total mass.

## Main results

* `TauCeti.MeasureTheory.ext_of_forall_mem_submonoid_integral_eq_of_polish` — two finite Borel
  measures on a Polish space with the same integrals on a point-separating submonoid of
  `E →ᵇ ℝ` are equal.
-/

public section

noncomputable section

open MeasureTheory BoundedContinuousFunction

namespace TauCeti

namespace MeasureTheory

variable {E : Type*} [TopologicalSpace E] [MeasurableSpace E]

/-- **A separating submonoid of test functions determines a finite measure.** Two finite Borel
measures on a Polish space that give the same integral to every member of a submonoid `S` of the
real bounded continuous functions are equal, provided the members of `S` separate points. -/
theorem ext_of_forall_mem_submonoid_integral_eq_of_polish [PolishSpace E] [BorelSpace E]
    {P P' : Measure E} [IsFiniteMeasure P] [IsFiniteMeasure P'] {S : Submonoid (E →ᵇ ℝ)}
    (hS : ∀ ⦃x y : E⦄, x ≠ y → ∃ g ∈ S, g x ≠ g y)
    (heq : ∀ g ∈ S, ∫ x, g x ∂P = ∫ x, g x ∂P') : P = P' := by
  -- The algebra generated by `S`, as a star subalgebra: `star` is the identity on real functions.
  let A : StarSubalgebra ℝ (E →ᵇ ℝ) :=
    { Algebra.adjoin ℝ (S : Set (E →ᵇ ℝ)) with
      star_mem' := fun {a} ha => by
        have hstar : star a = a := by ext x; exact star_trivial _
        rwa [hstar] }
  refine ext_of_forall_mem_subalgebra_integral_eq_of_polish (A := A) (fun x y hxy => ?_)
    fun g hg => ?_
  · obtain ⟨g, hgS, hg⟩ := hS hxy
    exact ⟨g, ⟨toContinuousMapStarₐ ℝ g, StarSubalgebra.mem_map.2
      ⟨g, Algebra.subset_adjoin hgS, rfl⟩, rfl⟩, hg⟩
  -- The algebra generated by a submonoid is its linear span, and agreement of integrals is
  -- linear (but not multiplicative, so `Algebra.adjoin_induction` would not do).
  have hmem : g ∈ Submodule.span ℝ (S : Set (E →ᵇ ℝ)) := by
    have hspan := Algebra.adjoin_eq_span (R := ℝ) (s := (S : Set (E →ᵇ ℝ)))
    rw [Submonoid.closure_eq] at hspan
    exact hspan ▸ hg
  clear hg
  induction hmem using Submodule.span_induction with
  | mem f hf => exact heq f hf
  | zero => simp
  | add a b _ _ ha hb =>
    simp only [BoundedContinuousFunction.add_apply]
    rw [integral_add (a.integrable P) (b.integrable P),
      integral_add (a.integrable P') (b.integrable P'), ha, hb]
  | smul c a _ ha =>
    simp only [BoundedContinuousFunction.smul_apply, smul_eq_mul]
    rw [integral_const_mul, integral_const_mul, ha]

end MeasureTheory

end TauCeti
