/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.IntermediateField.Quadratic
public import Mathlib.Analysis.Real.Sqrt
public import Mathlib.Data.Finset.Fin

/-!
# Square-class descent in multiquadratic towers

For a sequence of chosen square roots `root : ℕ → L` over a base field `K`, the tower
`sqrtTower root n = K(root₀, …, rootₙ₋₁)` is the intermediate field generated by the first
`n` roots. This file proves **square-class descent** in characteristic not two: if an
element `y` whose square is `r : K` lies in `sqrtTower root n`, then `r` is a square times
a subset product of the corresponding radicands. The rational-real specialization only
requires the nonnegativity hypotheses needed for `Real.sqrt` to supply the chosen roots.

This is the engine behind the degree computation
`[K(√d₀, …, √dₙ₋₁) : K] = 2ⁿ` for square-class-independent radicands, and hence behind
the structure theory of multiquadratic fields.

## Main definitions and results

* `TauCeti.Multiquadratic.sqrtTower`: the tower `K(root₀, …, rootₙ₋₁)`.
* `TauCeti.Multiquadratic.sqrtTower_def`: the defining adjoin restatement.
* `TauCeti.Multiquadratic.mem_sqrtTower_iff`: membership in the defining adjoin.
* `TauCeti.Multiquadratic.sqrtTower_succ`: the one-step recursion.
* `TauCeti.Multiquadratic.sqrtTower_le_iff`: the universal property of the tower.
* `TauCeti.Multiquadratic.sqrtTower_eq_adjoin_fin_range`: the bridge to a `Fin n` index.
* `TauCeti.Multiquadratic.sqrtTower_root_mem`: the listed roots lie in the tower.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem`: field-generic square-class descent.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem_fin`: finite-index square-class descent.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem_fintype`: arbitrary finite-index descent.
* `TauCeti.Multiquadratic.squareClass_of_sqrt_mem`: rational-real square-class descent.

## Provenance

This material is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where it was developed for one specific CM field. Here it is the field-generic
square-class engine of the multiquadratic-fields roadmap.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Iterated multiquadratic tower `K(root₀, …, rootₙ₋₁) ⊆ L`. -/
@[expose] noncomputable def sqrtTower (root : ℕ → L) (n : ℕ) : IntermediateField K L :=
  IntermediateField.adjoin K (root '' Set.Iio n)

/-- The defining adjoin presentation of `sqrtTower`. -/
theorem sqrtTower_def (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root n = IntermediateField.adjoin K (root '' Set.Iio n) :=
  rfl

/-- Membership in `sqrtTower` in terms of the defining adjoin. -/
theorem mem_sqrtTower_iff (root : ℕ → L) (n : ℕ) (x : L) :
    x ∈ sqrtTower (K := K) root n ↔
      x ∈ IntermediateField.adjoin K (root '' Set.Iio n) :=
  Iff.rfl

/-- The zeroth multiquadratic tower is the base field. -/
@[simp]
theorem sqrtTower_zero (root : ℕ → L) : sqrtTower (K := K) root 0 = ⊥ := by
  simp [sqrtTower]

/-- Adjoining the next square root gives the successor stage of `sqrtTower`. -/
@[simp]
theorem sqrtTower_succ (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root (n + 1)
      = (sqrtTower (K := K) root n) ⊔ IntermediateField.adjoin K {root n} := by
  rw [sqrtTower, sqrtTower, ← IntermediateField.adjoin_union]
  congr 1
  have hIio : Set.Iio (n + 1) = Set.Iio n ∪ {n} := by
    ext k
    simp only [Set.mem_Iio, Set.mem_union, Set.mem_singleton_iff]
    omega
  rw [hIio, Set.image_union, Set.image_singleton]

/-- The universal property of `sqrtTower`: it is the smallest intermediate field containing
the first `n` chosen roots. -/
@[simp]
theorem sqrtTower_le_iff (root : ℕ → L) (n : ℕ) (F : IntermediateField K L) :
    sqrtTower (K := K) root n ≤ F ↔ ∀ j, j < n → root j ∈ F := by
  rw [sqrtTower, IntermediateField.adjoin_le_iff]
  constructor
  · intro h j hj
    exact h ⟨j, hj, rfl⟩
  · rintro h _ ⟨j, hj, rfl⟩
    exact h j hj

/-- The first `n` roots may equivalently be indexed by `Fin n`. -/
theorem sqrtTower_eq_adjoin_fin_range (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root n =
      IntermediateField.adjoin K (Set.range fun j : Fin n => root j) := by
  rw [sqrtTower]
  congr 1
  · ext x
    constructor
    · rintro ⟨j, hj, rfl⟩
      exact ⟨⟨j, hj⟩, rfl⟩
    · rintro ⟨j, rfl⟩
      exact ⟨j, j.isLt, rfl⟩

/-- The universal property of `sqrtTower` using the finite index type `Fin n`. -/
theorem sqrtTower_le_iff_fin (root : ℕ → L) (n : ℕ) (F : IntermediateField K L) :
    sqrtTower (K := K) root n ≤ F ↔ ∀ j : Fin n, root j ∈ F := by
  rw [sqrtTower_le_iff]
  constructor
  · intro h j
    exact h j j.isLt
  · intro h j hj
    exact h ⟨j, hj⟩

/-- A chosen root indexed before `n` lies in `sqrtTower root n`. -/
theorem sqrtTower_root_mem (root : ℕ → L) {j n : ℕ} (hj : j < n) :
    root j ∈ sqrtTower (K := K) root n :=
  IntermediateField.mem_adjoin_of_mem K ⟨j, hj, rfl⟩

/-- The square of a listed root lies in `sqrtTower root n` as soon as its radicand is in the
base field. -/
theorem sqrtTower_sq_mem (root : ℕ → L) (d : ℕ → K)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) {j n : ℕ} :
    root j ^ 2 ∈ sqrtTower (K := K) root n := by
  rw [hroot j]
  exact (sqrtTower (K := K) root n).algebraMap_mem (d j)

private theorem sqrtTower_sup_adjoin_eq_of_mem (root : ℕ → L) {n : ℕ}
    (hroot : root n ∈ sqrtTower (K := K) root n) :
    sqrtTower (K := K) root n ⊔ IntermediateField.adjoin K {root n}
      = sqrtTower (K := K) root n := by
  rw [sup_eq_left]
  exact IntermediateField.adjoin_le_iff.mpr (by simpa using hroot)

/-- Square-class reconstruction across one tower level: from `r * dₙ = s² * ∏_T dⱼ` with
`dₙ ≠ 0` and `n ∉ T`, the radicand `r` equals `(s / dₙ)²` times the product over `insert n T`. -/
private theorem eq_sq_mul_prod_insert_of_mul_radicand {d : ℕ → K} {n : ℕ} {r s : K}
    {T : Finset ℕ} (hnT : n ∉ T) (hdn : d n ≠ 0) (hmul : r * d n = s ^ 2 * ∏ j ∈ T, d j) :
    r = (s / d n) ^ 2 * ∏ j ∈ insert n T, d j := by
  rw [Finset.prod_insert hnT]
  -- `r = (r * dₙ) / dₙ = (s² * ∏_T) / dₙ = (s / dₙ)² * (dₙ * ∏_T)`.
  calc
    r = r * d n / d n := by field_simp
    _ = s ^ 2 * (∏ j ∈ T, d j) / d n := by rw [hmul]
    _ = (s / d n) ^ 2 * (d n * ∏ j ∈ T, d j) := by field_simp

/-- If the chosen square root of `d n` lies outside the `n`-th tower, then `d n ≠ 0`: a zero
radicand has `root n = 0`, which lies in every tower. -/
private theorem radicand_ne_zero_of_root_notMem (d : ℕ → K) (root : ℕ → L) {n : ℕ}
    (hroot : root n ^ 2 = algebraMap K L (d n))
    (hnext : root n ∉ sqrtTower (K := K) root n) : d n ≠ 0 := by
  intro hdn
  apply hnext
  have hroot_zero : root n = 0 := by
    apply eq_zero_of_pow_eq_zero
    rw [hroot, hdn, map_zero]
  rw [hroot_zero]
  exact zero_mem _

/-- Descent step of `squareClass_of_sq_mem` in the branch where `y = b · rootₙ` with `b` in the
`n`-th tower — the `a = 0` case left by the vanishing cross term. Then `y · rootₙ` lies in the
`n`-th tower and squares to `r · dₙ`, so the level-`n` descent hypothesis produces a
representation of `r` over `Set.Iio (n + 1)` with `n` adjoined to the subset. -/
private theorem exists_sq_mul_prod_of_eq_mul_root (d : ℕ → K) (root : ℕ → L)
    {n : ℕ} {r : K} {y b : L} (hroot : root n ^ 2 = algebraMap K L (d n)) (hdn0 : d n ≠ 0)
    (hb : b ∈ sqrtTower (K := K) root n) (heq : y = b * root n)
    (hy : y ^ 2 = algebraMap K L r)
    (ih : ∀ r : K, ∀ y : L, y ^ 2 = algebraMap K L r → y ∈ sqrtTower (K := K) root n →
      ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio n ∧ r = s ^ 2 * ∏ j ∈ T, d j) :
    ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio (n + 1) ∧ r = s ^ 2 * ∏ j ∈ T, d j := by
  have hy_mul_mem : y * root n ∈ sqrtTower (K := K) root n := by
    have hy_mul_eq : y * root n = b * algebraMap K L (d n) := by
      calc y * root n = b * root n ^ 2 := by rw [heq]; ring
        _ = b * algebraMap K L (d n) := by rw [hroot]
    rw [hy_mul_eq]
    exact mul_mem hb ((sqrtTower (K := K) root n).algebraMap_mem (d n))
  have hy_mul_sq : (y * root n) ^ 2 = algebraMap K L (r * d n) := by
    rw [map_mul, ← hy, ← hroot]
    ring
  obtain ⟨T, s, hT, hmul⟩ := ih (r * d n) (y * root n) hy_mul_sq hy_mul_mem
  have hnT : n ∉ T := fun hn => Nat.lt_irrefl n (hT hn)
  refine ⟨insert n T, s / d n, ?_, ?_⟩
  · intro j hj
    rw [Finset.mem_coe, Finset.mem_insert] at hj
    rw [Set.mem_Iio]
    rcases hj with rfl | hj
    · omega
    · exact Nat.lt_trans (hT hj) n.lt_succ_self
  · exact eq_sq_mul_prod_insert_of_mul_radicand hnT hdn0 hmul

/-- **Square-class descent.** In characteristic not two, if `y² = r` over `K` and
`y ∈ K(root₀, …, rootₙ₋₁)`, where `root j` is a chosen square root of `d j`, then `r` is a
square times a subset product of the `d j` with `j < n`. -/
theorem squareClass_of_sq_mem (d : ℕ → K) (root : ℕ → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)] :
    ∀ n, ∀ r : K, ∀ y : L, y ^ 2 = algebraMap K L r → y ∈ sqrtTower (K := K) root n →
      ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio n ∧
        r = s ^ 2 * ∏ j ∈ T, d j := by
  classical
  have : NeZero (2 : L) :=
    NeZero.nat_of_injective (n := 2) (f := algebraMap K L) (algebraMap K L).injective
  intro n
  induction n with
  | zero =>
      intro r y hy hmem
      rw [sqrtTower_zero, IntermediateField.mem_bot] at hmem
      obtain ⟨s, rfl⟩ := hmem
      have h2 : s ^ 2 = r := (algebraMap K L).injective (by simpa using hy)
      exact ⟨∅, s, by simp, by rw [Finset.prod_empty, mul_one, h2]⟩
  | succ n ih =>
      intro r y hy hmem
      rw [sqrtTower_succ] at hmem
      by_cases hnext : root n ∈ sqrtTower (K := K) root n
      · rw [sqrtTower_sup_adjoin_eq_of_mem root hnext] at hmem
        obtain ⟨T, s, hT, heq⟩ := ih r y hy hmem
        exact ⟨T, s, hT.trans (Set.Iio_subset_Iio n.le_succ), heq⟩
      · have hx2 : root n ^ 2 ∈ sqrtTower (K := K) root n := by
          rw [hroot n]
          exact (sqrtTower (K := K) root n).algebraMap_mem (d n)
        obtain ⟨a, b, ha, hb, heq⟩ :=
          TauCeti.IntermediateField.exists_add_mul_of_mem_sup_adjoin_sq hx2 hmem
        -- `(a + b·root n)² = y² = algebraMap K L r ∈ sqrtTower`, while `root n ∉ sqrtTower`; hence
        -- the cross-term coefficient vanishes (`TauCeti.mul_eq_zero_of_add_mul_sq_mem`).
        have hab_mem : (a + b * root n) ^ 2 ∈ sqrtTower (K := K) root n := by
          rw [← heq, hy]
          exact (sqrtTower (K := K) root n).algebraMap_mem r
        have hab : a * b = 0 :=
          TauCeti.mul_eq_zero_of_add_mul_sq_mem hx2 hnext ha hb hab_mem
        rcases mul_eq_zero.mp hab with ha0 | hb0
        · exact exists_sq_mul_prod_of_eq_mul_root d root (hroot n)
            (radicand_ne_zero_of_root_notMem d root (hroot n) hnext) hb
            (by rw [heq, ha0, zero_add]) hy ih
        · have hy_mem : y ∈ sqrtTower (K := K) root n := by
            rw [heq, hb0, zero_mul, add_zero]
            exact ha
          obtain ⟨T, s, hT, hres⟩ := ih r y hy hy_mem
          exact ⟨T, s, hT.trans (Set.Iio_subset_Iio n.le_succ), hres⟩

/-- **Finite-index square-class descent.** If `y² = r` over `K` and
`y ∈ K(root i | i : Fin n)`, where `root i` is a chosen square root of `d i`, then `r`
is a square times a subset product of the `d i`. -/
theorem squareClass_of_sq_mem_fin {n : ℕ} (d : Fin n → K) (root : Fin n → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)]
    {r : K} {y : L} (hy : y ^ 2 = algebraMap K L r)
    (hmem : y ∈ IntermediateField.adjoin K (Set.range root)) :
    ∃ (T : Finset (Fin n)) (s : K), r = s ^ 2 * ∏ j ∈ T, d j := by
  classical
  let dNat : ℕ → K := fun j => if h : j < n then d ⟨j, h⟩ else 0
  let rootNat : ℕ → L := fun j => if h : j < n then root ⟨j, h⟩ else 0
  have hrootNat : ∀ j, rootNat j ^ 2 = algebraMap K L (dNat j) := by
    intro j
    by_cases h : j < n
    · simp [rootNat, dNat, h, hroot ⟨j, h⟩]
    · simp [rootNat, dNat, h]
  have htower :
      sqrtTower (K := K) rootNat n = IntermediateField.adjoin K (Set.range root) := by
    rw [sqrtTower_eq_adjoin_fin_range]
    congr 1
    ext z
    constructor
    · rintro ⟨j, rfl⟩
      exact ⟨j, by simp [rootNat]⟩
    · rintro ⟨j, rfl⟩
      exact ⟨j, by simp [rootNat]⟩
  have hmemNat : y ∈ sqrtTower (K := K) rootNat n := by
    rwa [htower]
  obtain ⟨T, s, hT, hr⟩ := squareClass_of_sq_mem dNat rootNat hrootNat n r y hy hmemNat
  have hTlt : ∀ m ∈ T, m < n := fun m hm => hT hm
  refine ⟨T.attachFin hTlt, s, ?_⟩
  have hprod : (∏ j ∈ T.attachFin hTlt, d j) = ∏ j ∈ T, dNat j := by
    calc
      (∏ j ∈ T.attachFin hTlt, d j) = ∏ j ∈ T.attachFin hTlt, dNat j := by
        refine Finset.prod_congr rfl ?_
        intro j hj
        simp [dNat]
      _ = ∏ j ∈ (T.attachFin hTlt).map Fin.valEmbedding, dNat j := by
        rw [Finset.prod_map]
        rfl
      _ = ∏ j ∈ T, dNat j := by
        rw [Finset.map_valEmbedding_attachFin]
  rwa [hprod]

/-- **Arbitrary finite-index square-class descent.** If `y² = r` over `K` and
`y ∈ K(root i | i : ι)` for a finite index type `ι`, where `root i` is a chosen square
root of `d i`, then `r` is a square times a subset product of the `d i`. -/
theorem squareClass_of_sq_mem_fintype {ι : Type*} [Finite ι] (d : ι → K) (root : ι → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)]
    {r : K} {y : L} (hy : y ^ 2 = algebraMap K L r)
    (hmem : y ∈ IntermediateField.adjoin K (Set.range root)) :
    ∃ (T : Finset ι) (s : K), r = s ^ 2 * ∏ j ∈ T, d j := by
  classical
  let := Fintype.ofFinite ι
  let e : ι ≃ Fin (Fintype.card ι) := Fintype.equivFin ι
  let dFin : Fin (Fintype.card ι) → K := fun j => d (e.symm j)
  let rootFin : Fin (Fintype.card ι) → L := fun j => root (e.symm j)
  have hrootFin : ∀ j, rootFin j ^ 2 = algebraMap K L (dFin j) := by
    intro j
    exact hroot (e.symm j)
  have hfield :
      IntermediateField.adjoin K (Set.range rootFin) =
        IntermediateField.adjoin K (Set.range root) := by
    congr 1
    ext z
    constructor
    · rintro ⟨j, rfl⟩
      exact ⟨e.symm j, rfl⟩
    · rintro ⟨j, rfl⟩
      exact ⟨e j, by simp [rootFin, e]⟩
  have hmemFin : y ∈ IntermediateField.adjoin K (Set.range rootFin) := by
    rwa [hfield]
  obtain ⟨T, s, hr⟩ := squareClass_of_sq_mem_fin dFin rootFin hrootFin hy hmemFin
  refine ⟨T.map e.symm.toEmbedding, s, ?_⟩
  have hprod : (∏ j ∈ T.map e.symm.toEmbedding, d j) = ∏ j ∈ T, dFin j := by
    rw [Finset.prod_map]
    rfl
  rwa [hprod]

/-- **Square-class descent for real rational square roots.** If `r` is a nonnegative
rational with `√r ∈ ℚ(√c₀, …, √cₙ₋₁)` and every `c j` is nonnegative, then `r` is a
rational square times a subset product of the `c j`. -/
theorem squareClass_of_sqrt_mem (c : ℕ → ℚ) (hc : ∀ j, 0 ≤ c j) :
    ∀ n, ∀ r : ℚ, 0 ≤ r → (Real.sqrt r : ℝ) ∈ sqrtTower (K := ℚ) (fun j => Real.sqrt (c j)) n →
      ∃ (T : Finset ℕ) (s : ℚ), ↑T ⊆ Set.Iio n ∧
        r = s ^ 2 * ∏ j ∈ T, c j := by
  intro n r hr hmem
  apply squareClass_of_sq_mem c (fun j => Real.sqrt (c j)) ?_ n r (Real.sqrt r) ?_ hmem
  · intro j
    have hcj_nonneg : 0 ≤ (c j : ℝ) := by exact_mod_cast hc j
    simpa using Real.sq_sqrt hcj_nonneg
  · have hr_nonneg : 0 ≤ (r : ℝ) := by exact_mod_cast hr
    simpa using Real.sq_sqrt hr_nonneg

/-- The real square root of a nonnegative integer squares back to its rational value, in the form
`(√n)² = algebraMap ℚ ℝ n`. This supplies the `hroot` hypothesis of the degree theorem for the real
square roots of integer radicands. The natural-number form `sq_sqrt_natCast` is the special case
`0 ≤ n`. -/
theorem sq_sqrt_intCast {n : ℤ} (hn : 0 ≤ n) : (Real.sqrt n) ^ 2 = algebraMap ℚ ℝ (n : ℚ) := by
  rw [Real.sq_sqrt (by exact_mod_cast hn), map_intCast]

end TauCeti.Multiquadratic
