/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.Ideal.Lemmas
public import Mathlib.RingTheory.DiscreteValuationRing.Basic

/-!
# Powers of the maximal ideal of a discrete valuation ring

The maximal ideal of a discrete valuation ring is generated by a uniformizer, so membership in its
`n`-th power is the inequality `n ≤ v x` for the additive valuation
`IsDiscreteValuationRing.addVal`, and the principal ideal generated by a nonzero `x` is
`𝔪 ^ (v x)`. Mathlib inlines these rewrites where it needs them; this file states them once.

## Main results

* `TauCeti.IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_le_addVal`: `x ∈ 𝔪 ^ n` is
  `n ≤ addVal x`.
* `TauCeti.IsDiscreteValuationRing.addVal_eq_multiplicity_span_singleton`: for `x ≠ 0`,
  `addVal x` is the multiplicity of `𝔪` in the ideal `(x)`.
-/

public section

open IsLocalRing

namespace TauCeti.IsDiscreteValuationRing

variable {S : Type*} [CommRing S] [IsDomain S] [_root_.IsDiscreteValuationRing S]

/-- Membership in a power of the maximal ideal of a discrete valuation ring, read on the additive
valuation. -/
theorem mem_maximalIdeal_pow_iff_le_addVal {n : ℕ} {x : S} :
    x ∈ maximalIdeal S ^ n ↔ (n : ℕ∞) ≤ _root_.IsDiscreteValuationRing.addVal S x := by
  obtain ⟨ϖ, hϖ⟩ := _root_.IsDiscreteValuationRing.exists_irreducible S
  rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton,
    ← _root_.IsDiscreteValuationRing.addVal_le_iff_dvd, hϖ.addVal_pow]

/-- The additive valuation of a nonzero element of a discrete valuation ring is the multiplicity
of the maximal ideal in the principal ideal it generates. -/
theorem addVal_eq_multiplicity_span_singleton {x : S} (hx : x ≠ 0) :
    _root_.IsDiscreteValuationRing.addVal S x =
      multiplicity (maximalIdeal S) (Ideal.span {x}) := by
  obtain ⟨ϖ, hϖ⟩ := _root_.IsDiscreteValuationRing.exists_irreducible S
  obtain ⟨n, u, rfl⟩ := _root_.IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hx hϖ
  rw [_root_.IsDiscreteValuationRing.addVal_def _ u hϖ n rfl,
    Ideal.span_singleton_mul_left_unit u.isUnit, ← Ideal.span_singleton_pow,
    ← hϖ.maximalIdeal_eq, multiplicity_pow_self_of_prime
      (Ideal.prime_of_isPrime (_root_.IsDiscreteValuationRing.not_a_field S) inferInstance)]

end TauCeti.IsDiscreteValuationRing
