/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Noetherian.Defs
public import TauCeti.Algebra.WordFiltration.AssociatedGraded

/-!
# A word-filtered algebra whose associated graded is Noetherian is Noetherian

Let `f : M →ₗ[R] A` be a linear family of generators of an algebra `A` and let
`TauCeti.Algebra.wordFiltration f` be the filtration it generates. This file proves the
**filtered-to-graded transfer of the Noetherian property**: if the associated graded ring
`TauCeti.Algebra.wordFiltration.AssociatedGraded f` is left Noetherian and the filtration is
exhaustive, then `A` is left Noetherian. The specialization to the PBW filtration of a universal
enveloping algebra is `TauCeti/Algebra/Lie/UniversalEnveloping/PBW/Noetherian.lean`; it is the
companion of the domain transfer in `TauCeti/Algebra/WordFiltration/Domain.lean`, which has the
same shape and the same two inputs.

The mechanism is the **symbol ideal**. A left ideal `I ⊆ A` meets the filtration in
`I ⊓ F n`, and the classes of those elements in the graded piece `F n / F_{n-1}` form an
`R`-submodule `symbolSubmodule f I n` of that piece, the degree-`n` *symbols* of `I`. Multiplying a
symbol of `I` on the left by any homogeneous class again gives a symbol of `I`, because `I` is a
left ideal, so the ideal `symbolIdeal f I` of the associated graded generated by all the symbols
has *no* homogeneous component beyond them: an element of the associated graded lies in
`symbolIdeal f I` exactly when each of its homogeneous components is a symbol of `I`
(`mem_symbolIdeal_iff`).

Symbols therefore **pin a left ideal inside a larger one**: if `I ≤ J` are left ideals and the
symbol ideal of `J` is contained in that of `I`, the two coincide (`eq_of_le_of_symbolIdeal_le`).
Nothing is claimed here about left ideals that are not nested. The proof is an induction on the
filtration degree: if `a` lies in the larger ideal and in `F n`, its degree-`n` symbol is a symbol
of the smaller ideal `I`, so `a` differs from an element of `I` by an element of `F_{n-1}`, and
that difference is handled by the inductive hypothesis; exhaustivity starts the induction for every
`a`. An ascending chain of left ideals of `A` then has an ascending chain of symbol ideals, which
stabilizes because the associated graded is Noetherian, and every step past that point is a nested
pair with the same symbol ideal, hence an equality.

Only the **left** ideals of `A` are considered, matching Mathlib's `IsNoetherianRing`; the
right-handed statement is the same theorem read in the opposite algebra, whose word filtration is
generated by the same family.

## Main definitions

* `TauCeti.Algebra.wordFiltration.symbolSubmodule`: the degree-`n` symbols of a left ideal, a
  submodule of the degree-`n` graded piece.
* `TauCeti.Algebra.wordFiltration.symbolIdeal`: the ideal of the associated graded generated by
  the homogeneous symbols of a left ideal.

## Main results

* `TauCeti.Algebra.wordFiltration.gradedMul_mem_symbolSubmodule`: the symbols of a left ideal
  absorb homogeneous multiplication on the left.
* `TauCeti.Algebra.wordFiltration.mem_symbolIdeal_iff`: membership in the symbol ideal is
  degreewise -- an element lies in it exactly when all its homogeneous components are symbols.
* `TauCeti.Algebra.wordFiltration.symbolSubmodule_le_of_symbolIdeal_le`: comparing symbol ideals
  compares symbols degreewise.
* `TauCeti.Algebra.wordFiltration.eq_of_le_of_symbolIdeal_le`: **nested left ideals with the same
  symbols are equal**, for an exhaustive filtration.
* `TauCeti.Algebra.wordFiltration.isNoetherianRing_of_isNoetherianRing_associatedGraded`: **the
  transfer**, an exhaustively word-filtered algebra with Noetherian associated graded is
  Noetherian.

## References

* J. C. McConnell and J. C. Robson, *Noncommutative Noetherian Rings*, Wiley (1987), §1.6.
* J. Dixmier, *Enveloping Algebras*, AMS GSM 11 (1996), §2.3.
-/

public section

open scoped DirectSum

universe u v w

namespace TauCeti.Algebra.wordFiltration

variable {R : Type u} {M : Type v} {A : Type w}
variable [CommRing R] [AddCommMonoid M] [Module R M] [Ring A] [Algebra R A]
variable (f : M →ₗ[R] A)

/-- The **degree-`n` symbols** of a left ideal `I` of a word-filtered algebra: the classes in the
degree-`n` graded piece of the elements of `I` of filtration degree at most `n`. -/
def symbolSubmodule (I : Ideal A) (n : ℕ) : Submodule R (GradedPiece f n) :=
  ((I.restrictScalars R).comap (wordFiltration f n).subtype).map
    (previousRestricted f n).mkQ

/-- The class of an element of a left ideal is a symbol of that ideal. -/
@[simp]
theorem mk_mem_symbolSubmodule {I : Ideal A} {n : ℕ} (a : wordFiltration f n)
    (ha : (a : A) ∈ I) :
    (Submodule.Quotient.mk a : GradedPiece f n) ∈ symbolSubmodule f I n :=
  Submodule.mem_map_of_mem (f := (previousRestricted f n).mkQ) ha

/-- Every symbol of a left ideal is the class of an element of that ideal. -/
theorem exists_mem_of_mem_symbolSubmodule {I : Ideal A} {n : ℕ} {z : GradedPiece f n}
    (hz : z ∈ symbolSubmodule f I n) :
    ∃ a : wordFiltration f n, (a : A) ∈ I ∧
      (Submodule.Quotient.mk a : GradedPiece f n) = z := by
  obtain ⟨a, ha, rfl⟩ := hz
  exact ⟨a, ha, rfl⟩

/-- **The symbols of a left ideal absorb homogeneous multiplication on the left**: a homogeneous
class of degree `i` times a degree-`j` symbol of `I` is a degree-`i + j` symbol of `I`. -/
theorem gradedMul_mem_symbolSubmodule (I : Ideal A) (i j : ℕ) (x : GradedPiece f i)
    {y : GradedPiece f j} (hy : y ∈ symbolSubmodule f I j) :
    gradedMul f i j x y ∈ symbolSubmodule f I (i + j) := by
  induction x using Submodule.Quotient.induction_on with
  | _ a =>
      obtain ⟨b, hb, rfl⟩ := exists_mem_of_mem_symbolSubmodule f hy
      rw [gradedMul_apply_mk]
      exact mk_mem_symbolSubmodule f _ (I.mul_mem_left _ hb)

/-- The **symbol ideal** of a left ideal `I`: the ideal of the associated graded generated by the
homogeneous symbols of `I`, the degree-`n` classes of the elements of `I` of filtration degree at
most `n`. -/
noncomputable def symbolIdeal (I : Ideal A) : Ideal (AssociatedGraded f) :=
  Ideal.span {z | ∃ (n : ℕ) (a : wordFiltration f n), (a : A) ∈ I ∧
    z = DirectSum.of (GradedPiece f) n (Submodule.Quotient.mk a)}

/-- The homogeneous symbol of an element of a left ideal lies in the symbol ideal. Not a `simp`
lemma: `TauCeti.Algebra.wordFiltration.mem_symbolIdeal_iff` already rewrites its left-hand side. -/
theorem of_mk_mem_symbolIdeal {I : Ideal A} {n : ℕ} (a : wordFiltration f n) (ha : (a : A) ∈ I) :
    DirectSum.of (GradedPiece f) n (Submodule.Quotient.mk a) ∈ symbolIdeal f I :=
  Ideal.subset_span ⟨n, a, ha, rfl⟩

/-- Passing to the symbol ideal is monotone. -/
theorem symbolIdeal_mono {I J : Ideal A} (h : I ≤ J) :
    symbolIdeal f I ≤ symbolIdeal f J :=
  Ideal.span_mono fun _ hz => by
    obtain ⟨n, a, ha, hz⟩ := hz
    exact ⟨n, a, h ha, hz⟩

/-- The elements of the associated graded all of whose homogeneous components are symbols of `I`.
It is a left ideal precisely because the symbols absorb homogeneous multiplication
(`TauCeti.Algebra.wordFiltration.gradedMul_mem_symbolSubmodule`), and it is what confines the
symbol ideal to the symbols. -/
private noncomputable def componentIdeal (I : Ideal A) : Ideal (AssociatedGraded f) where
  carrier := {z | ∀ n, z n ∈ symbolSubmodule f I n}
  add_mem' {x y} hx hy n := by
    rw [DirectSum.add_apply]
    exact Submodule.add_mem _ (hx n) (hy n)
  zero_mem' n := by
    rw [DirectSum.zero_apply]
    exact Submodule.zero_mem _
  smul_mem' c z hz n := by
    classical
    rw [smul_eq_mul, DirectSum.mul_eq_sum_support_ghas_mul, DFinsupp.finsetSum_apply]
    refine Submodule.sum_mem _ fun ij _ => ?_
    by_cases h : n = ij.1 + ij.2
    · subst h
      rw [DirectSum.of_eq_same]
      exact gradedMul_mem_symbolSubmodule f I _ _ _ (hz ij.2)
    · rw [DirectSum.of_eq_of_ne _ _ _ h]
      exact Submodule.zero_mem _

/-- **Membership in the symbol ideal is degreewise**: an element of the associated graded lies in
the symbol ideal of `I` exactly when every one of its homogeneous components is a symbol of `I`. In
particular the symbol ideal adds nothing to the symbols in any single degree. -/
@[simp]
theorem mem_symbolIdeal_iff {I : Ideal A} {z : AssociatedGraded f} :
    z ∈ symbolIdeal f I ↔ ∀ n, z n ∈ symbolSubmodule f I n := by
  classical
  constructor
  · intro hz
    have hle : symbolIdeal f I ≤ componentIdeal f I := by
      rw [symbolIdeal, Ideal.span_le]
      rintro w ⟨m, a, ha, rfl⟩
      intro k
      by_cases h : k = m
      · subst h
        rw [DirectSum.of_eq_same]
        exact mk_mem_symbolSubmodule f a ha
      · rw [DirectSum.of_eq_of_ne _ _ _ h]
        exact Submodule.zero_mem _
    exact hle hz
  · intro hz
    rw [← DirectSum.sum_support_of z]
    refine Submodule.sum_mem _ fun n _ => ?_
    obtain ⟨a, ha, hmk⟩ := exists_mem_of_mem_symbolSubmodule f (hz n)
    rw [← hmk]
    exact of_mk_mem_symbolIdeal f a ha

/-- **Comparing symbol ideals compares symbols degreewise.** -/
theorem symbolSubmodule_le_of_symbolIdeal_le {I J : Ideal A}
    (h : symbolIdeal f J ≤ symbolIdeal f I) (n : ℕ) :
    symbolSubmodule f J n ≤ symbolSubmodule f I n := by
  intro z hz
  obtain ⟨a, ha, rfl⟩ := exists_mem_of_mem_symbolSubmodule f hz
  have hcomp := (mem_symbolIdeal_iff f).mp (h (of_mk_mem_symbolIdeal f a ha)) n
  rwa [DirectSum.of_eq_same] at hcomp

/-- Two filtered elements with the same symbol differ by an element of strictly lower degree. -/
private theorem sub_mem_wordFiltrationPrevious_of_mk_eq {n : ℕ} {x y : wordFiltration f n}
    (h : (Submodule.Quotient.mk x : GradedPiece f n) = Submodule.Quotient.mk y) :
    (x : A) - (y : A) ∈ wordFiltrationPrevious f n := by
  have hmem := (Submodule.Quotient.eq (previousRestricted f n)).mp h
  rw [mem_previousRestricted_iff] at hmem
  simpa using hmem

/-- The step the induction below runs on: if the degree-`n` symbols of `J` are symbols of `I`, an
element of `J` of filtration degree at most `n` differs from an element of `I` by an element of
strictly lower degree. -/
private theorem exists_mem_sub_mem_wordFiltrationPrevious {I J : Ideal A}
    (h : ∀ n, symbolSubmodule f J n ≤ symbolSubmodule f I n) {n : ℕ} {a : A} (haJ : a ∈ J)
    (ha : a ∈ wordFiltration f n) :
    ∃ b ∈ I, b - a ∈ wordFiltrationPrevious f n := by
  obtain ⟨b, hb, hmk⟩ := exists_mem_of_mem_symbolSubmodule f
    (h n (mk_mem_symbolSubmodule f (⟨a, ha⟩ : wordFiltration f n) haJ))
  exact ⟨b, hb, sub_mem_wordFiltrationPrevious_of_mk_eq f hmk⟩

/-- The inductive core of `TauCeti.Algebra.wordFiltration.eq_of_le_of_symbolIdeal_le`: if the
symbols of `J` are symbols of `I ≤ J` in every degree, then the two ideals agree on each
filtration step. -/
private theorem mem_of_mem_wordFiltration {I J : Ideal A} (hIJ : I ≤ J)
    (h : ∀ n, symbolSubmodule f J n ≤ symbolSubmodule f I n) :
    ∀ (n : ℕ) (a : A), a ∈ J → a ∈ wordFiltration f n → a ∈ I := by
  intro n
  induction n with
  | zero =>
      intro a haJ ha
      obtain ⟨b, hb, hsub⟩ := exists_mem_sub_mem_wordFiltrationPrevious f h haJ ha
      rw [wordFiltrationPrevious_zero, Submodule.mem_bot, sub_eq_zero] at hsub
      exact hsub ▸ hb
  | succ m ih =>
      intro a haJ ha
      obtain ⟨b, hb, hsub⟩ := exists_mem_sub_mem_wordFiltrationPrevious f h haJ ha
      rw [wordFiltrationPrevious_succ] at hsub
      have hdiff : b - a ∈ I := ih _ (Submodule.sub_mem _ (hIJ hb) haJ) hsub
      have hmem := Submodule.sub_mem I hb hdiff
      rwa [sub_sub_cancel] at hmem

/-- **Nested left ideals with the same symbols are equal**: if `I ≤ J` are left ideals of an
exhaustively word-filtered algebra and the symbol ideal of `J` is contained in that of `I`, then
`I = J`. Only that one inclusion of symbol ideals is hypothesized, the other being the monotonicity
`TauCeti.Algebra.wordFiltration.symbolIdeal_mono`; the statement says nothing about left ideals
that are not nested. -/
theorem eq_of_le_of_symbolIdeal_le (hex : ∀ a : A, ∃ k, a ∈ wordFiltration f k)
    {I J : Ideal A} (hIJ : I ≤ J) (h : symbolIdeal f J ≤ symbolIdeal f I) : I = J := by
  refine le_antisymm hIJ fun a ha => ?_
  obtain ⟨n, hn⟩ := hex a
  exact mem_of_mem_wordFiltration f hIJ (symbolSubmodule_le_of_symbolIdeal_le f h) n a ha hn

/-- **The filtered-to-graded transfer of the Noetherian property**: an exhaustively word-filtered
algebra whose associated graded ring is left Noetherian is itself left Noetherian. -/
theorem isNoetherianRing_of_isNoetherianRing_associatedGraded
    [IsNoetherianRing (AssociatedGraded f)] (hex : ∀ a : A, ∃ k, a ∈ wordFiltration f k) :
    IsNoetherianRing A := by
  rw [isNoetherianRing_iff, ← monotone_stabilizes_iff_noetherian]
  intro c
  obtain ⟨n, hn⟩ :=
    monotone_stabilizes_iff_noetherian.mpr (isNoetherianRing_iff.mp ‹_›)
      (⟨fun m => symbolIdeal f (c m), fun _ _ hij => symbolIdeal_mono f (c.monotone hij)⟩ :
        ℕ →o Ideal (AssociatedGraded f))
  exact ⟨n, fun m hm =>
    eq_of_le_of_symbolIdeal_le f hex (c.monotone hm) (le_of_eq (hn m hm).symm)⟩

end TauCeti.Algebra.wordFiltration
