/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.Analysis.Complex.Order

/-!
# Totally real and totally complex fields at infinite places

An extension of a totally real field is unramified at every infinite place exactly when it is
itself totally real. Indeed, a complex place above a real place is precisely a ramified infinite
place.

A field containing an element whose square is a negative rational is totally complex: a real
embedding would send that element to a real square root of a negative number. A totally complex
field, having only complex infinite places, is then unramified at every infinite place in any
extension, and in degree `2` it has exactly one such place.

Restricting a real place along a field embedding gives a real place, and the real embedding of the
restriction is the composite of the embeddings. For an extension `L / k`, every place of `L` lies
over its restriction to `k`.

## Main results

* `NumberField.IsTotallyReal.of_isUnramifiedAtInfinitePlaces`: an everywhere-unramified
  extension of a totally real field is totally real.
* `NumberField.isUnramifiedAtInfinitePlaces_iff_isTotallyReal`: the resulting characterization.
* `NumberField.isTotallyReal_of_sq_ratCast_of_nonneg`: a nonnegative square generating the field
  forces total reality.
* `NumberField.isTotallyComplex_of_sq_ratCast_of_neg`: a negative square forces total
  complexity.
* `NumberField.IsUnramifiedAtInfinitePlaces_of_isTotallyComplex`: a totally complex base is
  unramified at all infinite places of any extension.
* `NumberField.InfinitePlace.nrComplexPlaces_eq_one_of_finrank_eq_two`: a totally complex
  field of degree `2` — an imaginary quadratic field — has exactly one complex place.
* `NumberField.InfinitePlace.finrank_sub_nrRealPlaces_div_two_eq_nrComplexPlaces`: halving the
  degree less the real places counts the complex places, for any number field.
* `NumberField.InfinitePlace.embedding_of_isReal_comap`: the real embedding of a restricted real
  place.
* `NumberField.InfinitePlace.liesOver_comap`: a place lies over its restriction.
-/

public section

open NumberField NumberField.InfinitePlace
open scoped ComplexOrder

namespace NumberField

variable {K : Type*} [Field K] [NumberField K]

omit [NumberField K] in
/-- **An extension of a totally real field unramified at infinity is totally real.** If every
infinite place of `K` is unramified over a totally real field `k`, then every infinite place of
`K` is real: the only other alternative in `InfinitePlace.isUnramified_iff` would make its
restriction a complex place of `k`. -/
theorem IsTotallyReal.of_isUnramifiedAtInfinitePlaces {k : Type*} [Field k] [Algebra k K]
    [IsTotallyReal k] [IsUnramifiedAtInfinitePlaces k K] : IsTotallyReal K where
  isReal w := by
    rcases InfinitePlace.isUnramified_iff.mp (InfinitePlace.isUnramified (k := k) w) with hw | hw
    · exact hw
    · exact ((not_isReal_iff_isComplex.mpr hw) (IsTotallyReal.isReal _)).elim

omit [NumberField K] in
/-- **A totally real extension is unramified at every infinite place.** Every infinite place of
the extension is real, which is the first alternative in `InfinitePlace.isUnramified_iff`. -/
theorem IsTotallyReal.isUnramifiedAtInfinitePlaces {k : Type*} [Field k] [Algebra k K]
    [IsTotallyReal K] : IsUnramifiedAtInfinitePlaces k K where
  isUnramified w := InfinitePlace.isUnramified_iff.mpr (Or.inl (IsTotallyReal.isReal w))

omit [NumberField K] in
/-- Over a totally real base, an extension is unramified at every infinite place exactly
when it is totally real. -/
@[simp] theorem isUnramifiedAtInfinitePlaces_iff_isTotallyReal {k : Type*} [Field k] [Algebra k K]
    [IsTotallyReal k] : IsUnramifiedAtInfinitePlaces k K ↔ IsTotallyReal K := by
  constructor
  · intro h
    let _ : IsUnramifiedAtInfinitePlaces k K := h
    exact IsTotallyReal.of_isUnramifiedAtInfinitePlaces (k := k) (K := K)
  · intro h
    let _ : IsTotallyReal K := h
    exact IsTotallyReal.isUnramifiedAtInfinitePlaces (k := k) (K := K)

omit [NumberField K] in
/-- **A field generated by a nonnegative rational square root is totally real.** If `K = ℚ(x)`,
`x² = r`, and `r ≥ 0`, then every complex embedding of `K` is real. Each embedding sends `x` to a
complex number whose square is the nonnegative real number `r`, so its imaginary part vanishes;
the generator hypothesis determines the embedding on all of `K`. -/
theorem isTotallyReal_of_sq_ratCast_of_nonneg [Algebra ℚ K] {x : K} {r : ℚ}
    (hx2 : x ^ 2 = algebraMap ℚ K r) (hgen : Algebra.adjoin ℚ {x} = ⊤) (hr : 0 ≤ r) :
    IsTotallyReal K := by
  rw [isTotallyReal_iff]
  intro w
  rw [InfinitePlace.isReal_iff, ComplexEmbedding.isReal_iff]
  apply RingHom.ext
  have halg : (ComplexEmbedding.conjugate w.embedding).toRatAlgHom =
      w.embedding.toRatAlgHom := by
    apply AlgHom.ext_of_adjoin_eq_top hgen
    rintro y rfl
    simp only [RingHom.toRatAlgHom_apply]
    rw [ComplexEmbedding.conjugate_coe_eq, Complex.conj_eq_iff_im]
    apply Complex.sq_nonneg_iff.mp
    rw [← map_pow, hx2]
    have hmap : w.embedding (algebraMap ℚ K r) = (r : ℂ) :=
      w.embedding.toRatAlgHom.commutes r
    rw [hmap]
    apply Complex.zero_le_real.mpr
    exact_mod_cast hr
  intro y
  exact AlgHom.congr_fun halg y

/-- **A field with a negative square is totally complex.** If some `x : K` has `x² = r` for a
negative rational `r`, then every infinite place of `K` is complex. -/
theorem isTotallyComplex_of_sq_ratCast_of_neg {x : K} {r : ℚ} (hx2 : x ^ 2 = algebraMap ℚ K r)
    (hr : r < 0) : IsTotallyComplex K := by
  -- A real embedding would carry `x` to a real square root of `r < 0`, which is impossible.
  rw [isTotallyComplex_iff]
  intro w
  rw [isComplex_iff]
  intro hφ
  have hφsq : (embedding w) x ^ 2 = (r : ℂ) := by
    rw [← map_pow, hx2]; simp [map_ratCast]
  have hψsq : (hφ.embedding x) ^ 2 = (r : ℝ) := by
    have h : (((hφ.embedding x) ^ 2 : ℝ) : ℂ) = (r : ℂ) := by
      push_cast [hφ.coe_embedding_apply]; rw [hφsq]
    exact_mod_cast h
  have hrR : (r : ℝ) < 0 := by exact_mod_cast hr
  nlinarith [sq_nonneg (hφ.embedding x), hψsq, hrR]

/-- **A totally complex base is unramified at all infinite places.** Since a totally complex field
has only complex infinite places and a complex place never ramifies, every infinite place is
unramified in any extension `K` of a totally complex field `k`. -/
lemma IsUnramifiedAtInfinitePlaces_of_isTotallyComplex {k K : Type*} [Field k] [Field K]
    [Algebra k K] [IsTotallyComplex k] : IsUnramifiedAtInfinitePlaces k K where
  isUnramified w := by
    rw [InfinitePlace.isUnramified_iff]
    exact Or.inr (IsTotallyComplex.isComplex _)

/-- **A totally complex field of degree `2` has exactly one complex place.** Such a field
satisfies `Module.finrank ℚ K = 2 * nrComplexPlaces K`, so degree `2` leaves exactly one
complex place; with `NumberField.IsTotallyComplex.nrRealPlaces_eq_zero` it is the field's only
infinite place. This is the imaginary quadratic case. -/
theorem InfinitePlace.nrComplexPlaces_eq_one_of_finrank_eq_two [IsTotallyComplex K]
    (hK : Module.finrank ℚ K = 2) : InfinitePlace.nrComplexPlaces K = 1 := by
  have := NumberField.IsTotallyComplex.finrank (K := K)
  omega

variable (K) in
/-- **Halving the degree less the real places counts the complex places.** The degree is
`r₁ + 2 r₂`, so subtracting the real places and halving leaves the complex ones. -/
theorem InfinitePlace.finrank_sub_nrRealPlaces_div_two_eq_nrComplexPlaces :
    (Module.finrank ℚ K - nrRealPlaces K) / 2 = nrComplexPlaces K := by
  have key := card_add_two_mul_card_eq_rank K
  omega

omit [NumberField K] in
/-- The real embedding of the restriction of a real place `w` along `f` is the real embedding of
`w` composed with `f`. -/
@[simp]
theorem InfinitePlace.embedding_of_isReal_comap {k : Type*} [Field k] (f : k →+* K)
    {w : InfinitePlace K} (hw : w.IsReal) :
    embedding_of_isReal (hw.comap f) = (embedding_of_isReal hw).comp f := by
  refine RingHom.ext fun x ↦ Complex.ofReal_injective ?_
  rw [embedding_of_isReal_apply, RingHom.comp_apply, embedding_of_isReal_apply,
    comap_embedding_of_isReal _ (hw.comap f), RingHom.comp_apply]

/-- An infinite place of `L` lies over its restriction to `k`.

Mathlib's `AbsoluteValue.LiesOver` instance is this statement for `AbsoluteValue.under`, which is
not the spelling `InfinitePlace.comap` produces, so it is registered here. Constructions indexed by
`w.comap (algebraMap k L)` that consume a `LiesOver` hypothesis, such as
`NumberField.LiesOver.completionMap`, need it. -/
instance InfinitePlace.liesOver_comap {k L : Type*} [Field k] [Field L] [Algebra k L]
    (w : InfinitePlace L) : w.LiesOver (w.comap (algebraMap k L)) :=
  ⟨rfl⟩

end NumberField
