/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Coalgebra.Comodule.Evaluation
public import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient.Regular
public import TauCeti.Algebra.Coalgebra.Subcoalgebra.Finite

/-!
# Finite comodule actions separate points

An algebra-valued point of an algebra-coalgebra acts on every scalar-extended comodule.
Equality of two such actions on one comodule forces the points to agree on that comodule's
matrix coefficients. Consequently, a comodule whose matrix coefficients generate the
algebra separates points.

Finite projective comodules over a commutative semiring admit the converse characterization. Over a
commutative principal ideal domain, the finite restricted regular comodules of a free coalgebra
collectively separate all algebra-valued points. Indeed, the fundamental theorem of coalgebras
places any coefficient in a finite subcoalgebra. Its restricted regular comodule has that
coefficient in its matrix-coefficient algebra, so equality of the two actions there detects
equality at the chosen coefficient.

This is the injectivity input for the Tannakian reconstruction target in Layer 1 of the
reductive-groups roadmap: once a point is packaged as a tensor automorphism of the
scalar-extension fibre functor, its components on finite-dimensional comodules determine the
point uniquely.

## Main declarations

* `TauCeti.Comodule.eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq`: equal point actions
  imply equality on the algebra generated by the comodule's matrix coefficients.
* `TauCeti.Comodule.eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top`: a
  coefficient-generating comodule separates points.
* `TauCeti.Comodule.endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra`: equality of actions
  is characterized by the coefficient algebra for finite projective comodules.
* `TauCeti.Comodule.eq_of_forall_finiteSubcoalgebra_endOfPoint_eq_of_exists_mem`: under an
  elementwise finite-subcoalgebra covering hypothesis, the restricted regular comodules
  collectively separate algebra-valued points.
* `TauCeti.Comodule.eq_of_forall_finiteSubcoalgebra_endOfPoint_eq`: the restricted regular
  comodules of finite subcoalgebras of a free coalgebra collectively separate algebra-valued
  points over a commutative principal ideal domain.

## References

* J. S. Milne, *Algebraic Groups* (2017), Sections 4.5 and 9.4.
* M. Sweedler, *Hopf Algebras*, Chapter 2.
-/

public section

open scoped TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

section OneComodule

variable {R : Type u} {C : Type v} {M : Type w} {A : Type x}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [CommSemiring A] [Algebra R A]

/-- If two points induce the same endomorphism on a comodule, then they agree on the algebra
generated by that comodule's matrix coefficients. -/
theorem eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h) :
    Set.EqOn g h (matrixCoefficientSubalgebra (R := R) (C := C) (M := M)) := by
  rw [matrixCoefficientSubalgebra_def, AlgHom.eqOn_adjoin_iff]
  intro c hc
  obtain ⟨φ, m, rfl⟩ := (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc
  have heval := congrArg
    (fun f : A ⊗[R] M →ₗ[A] A ⊗[R] M =>
      TauCeti.Module.Dual.baseChangeEvaluation (R := R) (M := M) (A := A)
        (1 ⊗ₜ[R] φ) (f (1 ⊗ₜ[R] m))) haction
  simpa only [baseChangeEvaluation_endOfPoint_tmul, one_mul] using heval

/-- A comodule whose matrix coefficients generate the ambient algebra separates
algebra-valued points: equal induced endomorphisms come only from equal points. -/
theorem eq_of_endOfPoint_eq_of_matrixCoefficientSubalgebra_eq_top (g h : C →ₐ[R] A)
    (haction : endOfPoint M g = endOfPoint M h)
    (hgenerate : matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊤) :
    g = h := by
  apply AlgHom.ext
  intro c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h haction
    (by simp [hgenerate])

end OneComodule

section FiniteProjective

variable {R : Type u} {C : Type v} {A : Type w}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C]
variable [CommSemiring A] [Algebra R A]

noncomputable section

/-- For a finite projective comodule over a commutative semiring, two points induce the same
endomorphism exactly when they agree on the algebra generated by the comodule's matrix
coefficients. -/
@[simp]
theorem endOfPoint_eq_iff_eqOn_matrixCoefficientSubalgebra
    {M : Type x} [AddCommMonoid M] [Module R M] [Comodule R C M]
    [Module.Projective R M] [Module.Finite R M] (g h : C →ₐ[R] A) :
    endOfPoint M g = endOfPoint M h ↔
      Set.EqOn g h (matrixCoefficientSubalgebra (R := R) (C := C) (M := M)) := by
  constructor
  · exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
  · intro hcoeff
    have hcontract (k : C →ₐ[R] A) (m : M) (φ : Module.Dual R M) :
        dualTensorHom R (Module.Dual R M) A
            (((Module.evalEquiv R M).rTensor A)
              (LinearMap.lTensor M k.toLinearMap (coact (R := R) (C := C) m))) φ =
          k (matrixCoefficient (R := R) (C := C) φ m) := by
      rw [matrixCoefficient_def]
      induction coact (R := R) (C := C) m using TensorProduct.inductionOn with
      | add x y hx hy => simp [hx, hy]
      | tmul m c => simp
    apply LinearMap.ext
    intro z
    induction z using TensorProduct.inductionOn with
    | add z t hz ht => simp [hz, ht]
    | tmul a m =>
        rw [endOfPoint_tmul, endOfPoint_tmul]
        congr 1
        have hout :
            LinearMap.lTensor M g.toLinearMap (coact (R := R) (C := C) m) =
              LinearMap.lTensor M h.toLinearMap (coact (R := R) (C := C) m) := by
          apply ((Module.evalEquiv R M).rTensor A).injective
          apply (dualTensorHom_bijective (R := R) (M := Module.Dual R M) (N := A)).1
          ext φ
          rw [hcontract, hcontract]
          exact hcoeff (matrixCoefficient_mem_subalgebra (R := R) (C := C) φ m)
        exact congrArg (TensorProduct.comm R M A) hout

end

end FiniteProjective

section FiniteSubcoalgebraCover

variable {R : Type u} {C : Type v} {A : Type w}
variable [CommSemiring R] [Semiring C] [Algebra R C] [Coalgebra R C] [Module.Flat R C]
variable [CommSemiring A] [Algebra R A]

/-- If every element belongs to a module-finite subcoalgebra, then the actions on the restricted
regular comodules of all module-finite subcoalgebras jointly determine an algebra-valued point. -/
theorem eq_of_forall_finiteSubcoalgebra_endOfPoint_eq_of_exists_mem
    (g h : C →ₐ[R] A)
    (haction : ∀ (D : Subcoalgebra R C), Module.Finite R D.toSubmodule →
      endOfPoint D.toRegularSubcomodule g = endOfPoint D.toRegularSubcomodule h)
    (hcover : ∀ c : C, ∃ D : Subcoalgebra R C, Module.Finite R D.toSubmodule ∧ c ∈ D) :
    g = h := by
  apply AlgHom.ext
  intro c
  obtain ⟨D, hDfinite, hcD⟩ := hcover c
  exact eqOn_matrixCoefficientSubalgebra_of_endOfPoint_eq g h
    (haction D hDfinite)
    (D.le_matrixCoefficientSubalgebra_toRegularSubcomodule hcD)

end FiniteSubcoalgebraCover

section PID

variable {R : Type u} {C : Type v} {A : Type w}
variable [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
variable [Semiring C] [Algebra R C] [Coalgebra R C] [Module.Free R C]
variable [CommSemiring A] [Algebra R A]

noncomputable section

/-- Over a commutative principal ideal domain, the actions on the restricted regular comodules of
all finite subcoalgebras of a free coalgebra jointly determine an algebra-valued point. In
particular, the family of finite free comodules separates points. -/
theorem eq_of_forall_finiteSubcoalgebra_endOfPoint_eq (g h : C →ₐ[R] A) :
    let _ : Ring C := Algebra.semiringToRing R
    (∀ (D : Subcoalgebra R C), Module.Finite R D.toSubmodule →
      endOfPoint D.toRegularSubcomodule g = endOfPoint D.toRegularSubcomodule h) →
    g = h := by
  let _ : Ring C := Algebra.semiringToRing R
  let _ : Module.Flat R C := Module.Flat.of_free
  dsimp only
  intro haction
  exact eq_of_forall_finiteSubcoalgebra_endOfPoint_eq_of_exists_mem
    g h haction
    (fun c ↦ Subcoalgebra.exists_finite_subcoalgebra_mem (R := R) (C := C) c)

end

end PID

end Comodule

end TauCeti
