/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

import Mathlib.LinearAlgebra.TensorProduct.Basis
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Central
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Scheme.Basic

/-!
# The center of an affine group scheme

Let `H` be a commutative Hopf algebra over a field `k`. This file constructs the center of
`Spec H` as a closed subgroup scheme. The defining equations are the coefficients, in the second
tensor factor, of the cocommutativity defect

```text
  Δ(x) - τ(Δ(x)).
```

A point kills these coefficients exactly when it commutes universally with every point of the
group. Since universally central points contain the identity and are closed under products and
inverses, the coefficient ideal is a Hopf ideal. Its quotient therefore represents the center.

The coefficient presentation uses a chosen vector-space basis only inside the construction. The
public universal property characterizes the resulting Hopf ideal as the smallest central Hopf
ideal, so the represented closed subgroup is canonical.

## Main declarations

* `TauCeti.CommHopfAlgCat.centerDefiningIdeal`: the Hopf ideal cutting out the center.
* `TauCeti.CommHopfAlgCat.centerCoordinateHopfAlgebra`: the coordinate Hopf algebra of the center.
* `TauCeti.CommHopfAlgCat.centerGroupScheme`: the center as a closed affine group scheme.
* `TauCeti.CommHopfAlgCat.mem_centerPointsSubgroup_iff`: its points are exactly the universally
  central points.
* `TauCeti.CommHopfAlgCat.centerDefiningIdeal_eq_augmentation_iff_forall_isCentralPoint_eq_one`:
  the center is trivial exactly when every universally central algebra-valued point is the
  identity.
* `TauCeti.CommHopfAlgCat.centerDefiningIdeal_le_iff`: the center contains every central closed
  subgroup scheme.

## References

* J. S. Milne, *Algebraic Groups* (2017), §1.k and §2.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Chapter 2.

This constructs the center `Z(G)` required in Layer 6, "Reductive and semisimple groups", of
`TauCetiRoadmap/ReductiveGroups/README.md`.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.CommHopfAlgCat

universe u v w

section Coefficients

variable {k : Type u} [Field k]
variable {H : Type v} [CommRing H] [_root_.HopfAlgebra k H]

/-- The index type of the vector-space basis used to extract center equations. -/
private abbrev centerBasisIndex := Module.Basis.ofVectorSpaceIndex k H

private noncomputable instance :
    DecidableEq (centerBasisIndex (k := k) (H := H)) :=
  Classical.decEq _

/-- The vector-space basis used internally to extract coefficients in the second tensor factor. -/
private noncomputable abbrev centerBasis :
    Module.Basis (centerBasisIndex (k := k) (H := H)) k H :=
  Module.Basis.ofVectorSpace k H

/-- The failure of the comultiplication to be invariant under interchange of its factors. -/
private noncomputable def centerDefect (x : H) : H ⊗[k] H :=
  Coalgebra.comul (R := k) x - TensorProduct.comm k H H (Coalgebra.comul (R := k) x)

/-- A coefficient of the cocommutativity defect in its second tensor factor. -/
private noncomputable def centerCoefficient (x : H)
    (i : centerBasisIndex (k := k) (H := H)) : H :=
  TensorProduct.equivFinsuppOfBasisRight (centerBasis (k := k) (H := H))
    (centerDefect (k := k) x) i

/-- The ideal generated by the coefficients of all cocommutativity defects. -/
private noncomputable def centerCoefficientIdeal : Ideal H :=
  Ideal.span (Set.range fun p : H × centerBasisIndex (k := k) (H := H) ↦
    centerCoefficient (k := k) p.1 p.2)

private theorem equivFinsuppOfBasisRight_map_apply
    {A : Type w} [CommRing A] [Algebra k A] (g : H →ₐ[k] A) (z : H ⊗[k] H)
    (i : centerBasisIndex (k := k) (H := H)) :
    TensorProduct.equivFinsuppOfBasisRight (centerBasis (k := k) (H := H))
        (Algebra.TensorProduct.map g (AlgHom.id k H) z) i =
      g (TensorProduct.equivFinsuppOfBasisRight (centerBasis (k := k) (H := H)) z i) := by
  classical
  induction z with
  | tmul x y =>
      simp only [Algebra.TensorProduct.map_tmul,
        TensorProduct.equivFinsuppOfBasisRight_apply_tmul_apply, AlgHom.id_apply, map_smul]
  | add x y hx hy =>
      simpa only [map_add, LinearEquiv.map_add, Finsupp.add_apply] using
        congrArg₂ (· + ·) hx hy

private theorem tensorMap_eq_zero_iff_coefficients
    {A : Type w} [CommRing A] [Algebra k A] (g : H →ₐ[k] A) (z : H ⊗[k] H) :
    Algebra.TensorProduct.map g (AlgHom.id k H) z = 0 ↔
      ∀ i, g (TensorProduct.equivFinsuppOfBasisRight
        (centerBasis (k := k) (H := H)) z i) = 0 := by
  classical
  constructor
  · intro hz i
    have := congrArg (fun q ↦ TensorProduct.equivFinsuppOfBasisRight
      (centerBasis (k := k) (H := H)) q i) hz
    simpa [equivFinsuppOfBasisRight_map_apply] using this
  · intro h
    apply (TensorProduct.equivFinsuppOfBasisRight
      (centerBasis (k := k) (H := H))).injective
    ext i
    rw [equivFinsuppOfBasisRight_map_apply, h]
    simp

private theorem centerCoefficientIdeal_le_ker_iff
    {A : Type w} [CommRing A] [Algebra k A] (g : H →ₐ[k] A) :
    centerCoefficientIdeal (k := k) (H := H) ≤ RingHom.ker g.toRingHom ↔
      ∀ x i, g (centerCoefficient (k := k) x i) = 0 := by
  rw [centerCoefficientIdeal, Ideal.span_le]
  constructor
  · intro h x i
    exact RingHom.mem_ker.mp (h ⟨(x, i), rfl⟩)
  · rintro h _ ⟨⟨x, i⟩, rfl⟩
    exact RingHom.mem_ker.mpr (h x i)

private theorem tensorMap_comul_eq_convMul
    {A : Type v} [CommRing A] [Algebra k A] (g : WithConv (H →ₐ[k] A)) :
    toConv ((Algebra.TensorProduct.map g.ofConv (AlgHom.id k H)).comp
      (_root_.Bialgebra.comulAlgHom k H)) =
      AlgHom.mapValue
          (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := H)) g *
        toConv (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := H)) := by
  rw [Bialgebra.toConv_comp_comulAlgHom]
  simp only [Bialgebra.TensorProduct.includeLeft_toAlgHom,
    Bialgebra.TensorProduct.includeRight_toAlgHom, AlgHom.mapValue_apply]
  rw [Algebra.TensorProduct.map_comp_includeLeft,
    Algebra.TensorProduct.map_comp_includeRight, AlgHom.comp_id]

private theorem tensorMap_comm_comul_eq_convMul
    {A : Type v} [CommRing A] [Algebra k A] (g : WithConv (H →ₐ[k] A)) :
    toConv ((Algebra.TensorProduct.map g.ofConv (AlgHom.id k H)).comp
      ((Algebra.TensorProduct.comm k H H).toAlgHom.comp
        (_root_.Bialgebra.comulAlgHom k H))) =
      toConv (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := H)) *
        AlgHom.mapValue
          (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := H)) g := by
  have h := congrArg
    (AlgHom.mapValue (H := H) (Algebra.TensorProduct.map g.ofConv (AlgHom.id k H)))
    (HopfAlgebra.convMul_includeRight_includeLeft (R := k) (H := H))
  symm
  simpa only [map_mul, AlgHom.mapValue_apply, ofConv_toConv, AlgHom.comp_assoc,
    Algebra.TensorProduct.map_comp_includeLeft,
    Algebra.TensorProduct.map_comp_includeRight, AlgHom.comp_id] using h

private theorem map_centerDefect_eq_zero_iff_isCentralPoint
    {A : Type v} [CommRing A] [Algebra k A] (g : WithConv (H →ₐ[k] A)) :
    (∀ x, Algebra.TensorProduct.map g.ofConv (AlgHom.id k H)
      (centerDefect (k := k) x) = 0) ↔ HopfAlgebra.IsCentralPoint g := by
  rw [HopfAlgebra.isCentralPoint_iff_commute_includeRight, commute_iff_eq]
  constructor
  · intro h
    apply WithConv.ofConv_injective
    apply AlgHom.ext
    intro x
    have hx := h x
    rw [centerDefect, map_sub, sub_eq_zero] at hx
    have h₁ := DFunLike.congr_fun (WithConv.toConv_injective (tensorMap_comul_eq_convMul g)) x
    have h₂ := DFunLike.congr_fun
      (WithConv.toConv_injective (tensorMap_comm_comul_eq_convMul g)) x
    exact h₁.symm.trans (hx.trans h₂)
  · intro h x
    have hx := DFunLike.congr_fun (WithConv.toConv_injective h) x
    rw [centerDefect, map_sub, sub_eq_zero]
    have h₁ := DFunLike.congr_fun (WithConv.toConv_injective (tensorMap_comul_eq_convMul g)) x
    have h₂ := DFunLike.congr_fun
      (WithConv.toConv_injective (tensorMap_comm_comul_eq_convMul g)) x
    exact h₁.trans (hx.trans h₂.symm)

private theorem centerCoefficientIdeal_le_ker_iff_isCentralPoint
    {A : Type v} [CommRing A] [Algebra k A] (g : WithConv (H →ₐ[k] A)) :
    centerCoefficientIdeal (k := k) (H := H) ≤ RingHom.ker g.ofConv.toRingHom ↔
      HopfAlgebra.IsCentralPoint g := by
  rw [centerCoefficientIdeal_le_ker_iff]
  rw [← map_centerDefect_eq_zero_iff_isCentralPoint]
  exact forall_congr' fun x ↦
    (tensorMap_eq_zero_iff_coefficients g.ofConv (centerDefect (k := k) x)).symm

end Coefficients

section DefiningIdeal

variable {k : Type u} [Field k]
variable {H : Type v} [CommRing H] [_root_.HopfAlgebra k H]

private theorem centerCoefficientIdeal_counit_eq_zero {x : H}
    (hx : x ∈ centerCoefficientIdeal (k := k) (H := H)) :
    Coalgebra.counit (R := k) x = 0 := by
  have he : HopfAlgebra.IsCentralPoint (1 : WithConv (H →ₐ[k] H)) :=
    HopfAlgebra.isCentralPoint_one (R := k) (H := H) (A := H)
  have hle : centerCoefficientIdeal (k := k) (H := H) ≤
      RingHom.ker (1 : WithConv (H →ₐ[k] H)).ofConv.toRingHom :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint
      (1 : WithConv (H →ₐ[k] H))).2 he
  have hxzero := RingHom.mem_ker.mp (hle hx)
  have hxzero' : (1 : WithConv (H →ₐ[k] H)) x = 0 := hxzero
  rw [AlgHom.convOne_apply] at hxzero'
  have := congrArg (Bialgebra.counitAlgHom k H) hxzero'
  simpa only [map_zero, AlgHom.commutes, Algebra.algebraMap_self_apply] using this

private theorem centerCoefficientIdeal_antipode_mem {x : H}
    (hx : x ∈ centerCoefficientIdeal (k := k) (H := H)) :
    HopfAlgebra.antipode k x ∈ centerCoefficientIdeal (k := k) (H := H) := by
  let I := centerCoefficientIdeal (k := k) (H := H)
  let q : H →ₐ[k] H ⧸ I := Ideal.Quotient.mkₐ k I
  let g : WithConv (H →ₐ[k] H ⧸ I) := toConv q
  have hgker : I ≤ RingHom.ker g.ofConv.toRingHom := by
    simp [g, q, Ideal.Quotient.mkₐ_ker]
  have hg : HopfAlgebra.IsCentralPoint g :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint g).1 hgker
  have hginv : HopfAlgebra.IsCentralPoint g⁻¹ := hg.inv
  have hle : I ≤ RingHom.ker g⁻¹.ofConv.toRingHom :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint g⁻¹).2 hginv
  have hxzero := RingHom.mem_ker.mp (hle hx)
  have hxzero' : g⁻¹ x = 0 := hxzero
  rw [AlgHom.convInv_apply] at hxzero'
  exact Ideal.Quotient.eq_zero_iff_mem.mp hxzero'

private theorem centerCoefficientIdeal_comul_mem {x : H}
    (hx : x ∈ centerCoefficientIdeal (k := k) (H := H)) :
    Coalgebra.comul (R := k) x ∈
      HopfIdeal.leftTensorIdeal (R := k) (H := H)
          (centerCoefficientIdeal (k := k) (H := H)) ⊔
        HopfIdeal.rightTensorIdeal (R := k) (H := H)
          (centerCoefficientIdeal (k := k) (H := H)) := by
  let I := centerCoefficientIdeal (k := k) (H := H)
  let Q := H ⧸ I
  let q : H →ₐ[k] Q := Ideal.Quotient.mkₐ k I
  let ql : H →ₐ[k] Q ⊗[k] Q :=
    (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := Q) (B := Q)).comp q
  let qr : H →ₐ[k] Q ⊗[k] Q :=
    (Algebra.TensorProduct.includeRight (R := k) (A := Q) (B := Q)).comp q
  have hcompker (f : Q →ₐ[k] Q ⊗[k] Q) :
      I ≤ RingHom.ker (f.comp q).toRingHom := by
    intro y hy
    rw [RingHom.mem_ker]
    have hqy : q y = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hy
    simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, AlgHom.comp_apply, hqy, map_zero]
  have hqlker : I ≤ RingHom.ker ql.toRingHom :=
    hcompker (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := Q) (B := Q))
  have hqrker : I ≤ RingHom.ker qr.toRingHom :=
    hcompker (Algebra.TensorProduct.includeRight (R := k) (A := Q) (B := Q))
  have hql : HopfAlgebra.IsCentralPoint (toConv ql) :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint (toConv ql)).1 hqlker
  have hqr : HopfAlgebra.IsCentralPoint (toConv qr) :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint (toConv qr)).1 hqrker
  have hmulker : I ≤ RingHom.ker (toConv ql * toConv qr).ofConv.toRingHom :=
    (centerCoefficientIdeal_le_ker_iff_isCentralPoint (toConv ql * toConv qr)).2
      (hql.mul hqr)
  have hconvzero : (toConv ql * toConv qr).ofConv x = 0 :=
    RingHom.mem_ker.mp (hmulker hx)
  have hproduct : Algebra.TensorProduct.lift ql qr (fun _ _ ↦ Commute.all _ _) =
      Algebra.TensorProduct.map q q := by
    ext <;> simp [ql, qr]
  have hmapzero : Algebra.TensorProduct.map q q (Coalgebra.comul (R := k) x) = 0 := by
    rw [AlgHom.convMul_apply, hproduct] at hconvzero
    exact hconvzero
  have hker : RingHom.ker (Algebra.TensorProduct.map q q).toRingHom =
      HopfIdeal.leftTensorIdeal (R := k) (H := H) I ⊔
        HopfIdeal.rightTensorIdeal (R := k) (H := H) I := by
    have hqker : RingHom.ker q = I := Ideal.Quotient.mkₐ_ker k I
    simpa only [AlgHom.ker_coe, AlgHom.toRingHom_eq_coe, hqker] using
      HopfIdeal.ker_tensorProduct_map_eq_leftTensorIdeal_sup_rightTensorIdeal q q
        (Ideal.Quotient.mkₐ_surjective k I) (Ideal.Quotient.mkₐ_surjective k I)
  rw [← hker, RingHom.mem_ker]
  exact hmapzero

/-- The Hopf ideal generated by the coefficients of the cocommutativity defect. -/
private noncomputable def centerCoefficientHopfIdeal : HopfIdeal k H :=
  HopfIdeal.ofIdeal (centerCoefficientIdeal (k := k) (H := H))
    (fun {x} hx ↦ centerCoefficientIdeal_comul_mem (k := k) (H := H) (x := x) hx)
    (fun {x} hx ↦ centerCoefficientIdeal_counit_eq_zero (k := k) (H := H) (x := x) hx)
    (fun {x} hx ↦ centerCoefficientIdeal_antipode_mem (k := k) (H := H) (x := x) hx)

end DefiningIdeal

variable {k : Type u} [Field k]

/-- The Hopf ideal cutting out the center of an affine group scheme.

Its quotient represents the universally central points of the group functor. The construction
uses coefficients in a chosen vector-space basis internally; `centerDefiningIdeal_le_iff`
characterizes it without that choice. -/
noncomputable def centerDefiningIdeal (H : _root_.CommHopfAlgCat.{v} k) : HopfIdeal k H :=
  centerCoefficientHopfIdeal (k := k) (H := H)

/-- The coordinate Hopf algebra of the center of an affine group. -/
noncomputable abbrev centerCoordinateHopfAlgebra (H : _root_.CommHopfAlgCat.{v} k) :
    _root_.CommHopfAlgCat.{v} k :=
  quotient H (centerDefiningIdeal H)

/-- The underlying ideal of the center is the coefficient ideal of the cocommutativity defect. -/
private theorem mem_centerDefiningIdeal_iff (H : _root_.CommHopfAlgCat.{v} k) {x : H} :
    x ∈ centerDefiningIdeal H ↔ x ∈ centerCoefficientIdeal (k := k) (H := H) :=
  Iff.rfl

/-- The Hopf ideal defining the center is central. -/
theorem isCentral_centerDefiningIdeal (H : _root_.CommHopfAlgCat.{v} k) :
    (centerDefiningIdeal H).IsCentral := by
  rw [isCentral_iff_forall_isCentralPoint]
  intro A g hg
  apply (centerCoefficientIdeal_le_ker_iff_isCentralPoint g).1
  intro x hx
  rw [RingHom.mem_ker]
  exact (mem_quotientPointsSubgroup_iff H (centerDefiningIdeal H) A g).1 hg x
    ((mem_centerDefiningIdeal_iff H).2 hx)

/-- **The center ideal is the smallest central Hopf ideal.** Equivalently, every central closed
subgroup scheme of `Spec H` factors through the center. -/
@[simp]
theorem centerDefiningIdeal_le_iff (H : _root_.CommHopfAlgCat.{v} k)
    (I : HopfIdeal k H) : centerDefiningIdeal H ≤ I ↔ I.IsCentral := by
  constructor
  · intro h
    exact (isCentral_centerDefiningIdeal H).mono h
  · intro hI
    let A : CommAlgCat.{v} k := CommAlgCat.of k (H ⧸ I.toIdeal)
    let q : WithConv (H →ₐ[k] A) := toConv (Ideal.Quotient.mkₐ k I.toIdeal)
    have hqmem : q ∈ quotientPointsSubgroup H I A := by
      rw [mem_quotientPointsSubgroup_iff]
      intro x hx
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (HopfIdeal.mem_toIdeal.mpr hx)
    have hqcentral : HopfAlgebra.IsCentralPoint q :=
      isCentralPoint_of_mem_quotientPointsSubgroup H I hI A hqmem
    have hle : centerCoefficientIdeal (k := k) (H := H) ≤
        RingHom.ker q.ofConv.toRingHom :=
      (centerCoefficientIdeal_le_ker_iff_isCentralPoint q).2 hqcentral
    intro x hx
    have hx' : x ∈ centerCoefficientIdeal (k := k) (H := H) :=
      (mem_centerDefiningIdeal_iff H).1 hx
    exact HopfIdeal.mem_toIdeal.mp <| Ideal.Quotient.eq_zero_iff_mem.mp <|
      RingHom.mem_ker.mp (hle hx')

/-- The center is the whole group exactly when the coordinate Hopf algebra is cocommutative. -/
@[simp]
theorem centerDefiningIdeal_eq_bot_iff_isCocomm (H : _root_.CommHopfAlgCat.{v} k) :
    centerDefiningIdeal H = ⊥ ↔ _root_.Coalgebra.IsCocomm k H := by
  constructor
  · intro h
    rw [← HopfIdeal.isCentral_bot_iff_isCocomm]
    rw [← h]
    exact isCentral_centerDefiningIdeal H
  · intro h
    apply le_antisymm
    · rw [centerDefiningIdeal_le_iff, HopfIdeal.isCentral_bot_iff_isCocomm]
      exact h
    · exact bot_le

/-- The subgroup of algebra-valued points cut out by the center ideal. -/
noncomputable abbrev centerPointsSubgroup (H : _root_.CommHopfAlgCat.{v} k)
    (A : CommAlgCat.{v} k) : Subgroup (HopfAlgebra.points (R := k) (H := H) A) :=
  quotientPointsSubgroup H (centerDefiningIdeal H) A

/-- Membership in the represented center is universal centrality in the functor of points. -/
@[simp]
theorem mem_centerPointsSubgroup_iff (H : _root_.CommHopfAlgCat.{v} k)
    (A : CommAlgCat.{v} k) (g : HopfAlgebra.points (R := k) (H := H) A) :
    g ∈ centerPointsSubgroup H A ↔ HopfAlgebra.IsCentralPoint g := by
  rw [mem_quotientPointsSubgroup_iff]
  have hcoeff := centerCoefficientIdeal_le_ker_iff_isCentralPoint g
  rw [← hcoeff]
  constructor
  · intro h x hx
    rw [RingHom.mem_ker]
    exact h x ((mem_centerDefiningIdeal_iff H).2 hx)
  · intro h x hx
    exact RingHom.mem_ker.mp (h ((mem_centerDefiningIdeal_iff H).1 hx))

/-- Triviality of the represented center can be tested on all algebra-valued points. -/
theorem centerDefiningIdeal_eq_augmentation_iff_forall_isCentralPoint_eq_one
    (H : _root_.CommHopfAlgCat.{v} k) :
    centerDefiningIdeal H = HopfIdeal.augmentation k H ↔
      ∀ (A : CommAlgCat.{v} k)
        (g : HopfAlgebra.points (R := k) (H := H) A),
        HopfAlgebra.IsCentralPoint g → g = 1 := by
  constructor
  · intro h A g hg
    apply eq_one_of_mem_quotientPointsSubgroup_augmentation H A
    rw [← h, mem_centerPointsSubgroup_iff]
    exact hg
  · intro h
    apply le_antisymm
    · exact HopfIdeal.le_augmentation k H (centerDefiningIdeal H)
    intro x hx
    let A : CommAlgCat.{v} k := CommAlgCat.of k (H ⧸ (centerDefiningIdeal H).toIdeal)
    let q : HopfAlgebra.points (R := k) (H := H) A :=
      toConv (Ideal.Quotient.mkₐ k (centerDefiningIdeal H).toIdeal)
    have hqcentral : HopfAlgebra.IsCentralPoint q := by
      rw [← mem_centerPointsSubgroup_iff]
      rw [mem_quotientPointsSubgroup_iff]
      intro y hy
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (HopfIdeal.mem_toIdeal.mpr hy)
    have hq : q = 1 := h A q hqcentral
    apply HopfIdeal.mem_toIdeal.mp
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    have hxzero : Coalgebra.counit (R := k) x = 0 :=
      (HopfIdeal.mem_augmentation k H).mp hx
    calc
      Ideal.Quotient.mkₐ k (centerDefiningIdeal H).toIdeal x = q.ofConv x := rfl
      _ = (1 : HopfAlgebra.points (R := k) (H := H) A).ofConv x :=
        congrArg (fun f : HopfAlgebra.points (R := k) (H := H) A => f.ofConv x) hq
      _ = 0 := by simp [AlgHom.convOne_apply, hxzero]

/-- The represented center agrees with the center previously defined directly on the functor of
points. -/
theorem centerPointsSubgroup_eq_center (H : _root_.CommHopfAlgCat.{v} k)
    (A : CommAlgCat.{v} k) :
    centerPointsSubgroup H A = HopfAlgebra.center k H A := by
  ext g
  rw [mem_centerPointsSubgroup_iff, HopfAlgebra.mem_center]

section Scheme

open AlgebraicGeometry

/-- The center of an affine group scheme, represented by the quotient by its center ideal. -/
noncomputable abbrev centerGroupScheme (H : _root_.CommHopfAlgCat.{u} k) :
    Grp (Over (Spec (CommRingCat.of k))) :=
  quotientSpec H (centerDefiningIdeal H)

/-- The canonical inclusion of the center into the ambient affine group scheme. -/
noncomputable abbrev centerGroupSchemeι (H : _root_.CommHopfAlgCat.{u} k) :
    centerGroupScheme H ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of k)).obj (Opposite.op H) :=
  quotientSpecι H (centerDefiningIdeal H)

/-- The center is a closed subgroup scheme of the ambient affine group scheme. -/
instance isClosedImmersion_centerGroupSchemeι (H : _root_.CommHopfAlgCat.{u} k) :
    IsClosedImmersion (centerGroupSchemeι H).hom.hom.left :=
  inferInstance

/-- A central closed subgroup scheme cut out by `I` includes canonically into the center. -/
noncomputable def centralSubgroupToCenter (H : _root_.CommHopfAlgCat.{u} k)
    (I : HopfIdeal k H) (hI : I.IsCentral) :
    quotientSpec H I ⟶ centerGroupScheme H :=
  quotientSpecMapOfLe H ((centerDefiningIdeal_le_iff H I).2 hI)

/-- Including a central subgroup through the center and then into the ambient group recovers its
original closed-subgroup inclusion. -/
@[simp]
theorem centralSubgroupToCenter_comp_centerGroupSchemeι
    (H : _root_.CommHopfAlgCat.{u} k) (I : HopfIdeal k H) (hI : I.IsCentral) :
    centralSubgroupToCenter H I hI ≫ centerGroupSchemeι H = quotientSpecι H I :=
  quotientSpecMapOfLe_comp_quotientSpecι H ((centerDefiningIdeal_le_iff H I).2 hI)

/-- The inclusion of a central closed subgroup into the center is a closed immersion. -/
instance isClosedImmersion_centralSubgroupToCenter (H : _root_.CommHopfAlgCat.{u} k)
    (I : HopfIdeal k H) (hI : I.IsCentral) :
    IsClosedImmersion (centralSubgroupToCenter H I hI).hom.hom.left :=
  by
    rw [centralSubgroupToCenter]
    infer_instance

end Scheme

end TauCeti.CommHopfAlgCat
