/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.Add

/-!
# Frobenius and composition of isogenies

Over a finite field, the Frobenius commutes with every isogeny because every function-field
homomorphism commutes with raising to the cardinality of the ground field. Its action by
composition on the additive group of morphisms is additive. This is the Frobenius-specific
distributivity needed to calculate in the subgroup generated by the identity and Frobenius.

## Main results

* `TauCeti.Isogeny.frobeniusIsogeny_comp`: Frobenius commutes with an isogeny.
* `TauCeti.Isogeny.Hom.frobenius_comp`: Frobenius is central in the endomorphism carrier.
* `TauCeti.Isogeny.Hom.frobenius_comp_add`: composition by Frobenius preserves addition.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], V.1–2.
-/

public section

namespace TauCeti.Isogeny

open WeierstrassCurve.Affine

variable {F : Type*} [Field F] [Finite F]
  {W₁ W₂ : WeierstrassCurve.Affine F}

/-- Frobenius commutes with an isogeny defined over the finite ground field. -/
theorem frobeniusIsogeny_comp (φ : Isogeny W₁ W₂) :
    (frobeniusIsogeny W₂).comp φ = φ.comp (frobeniusIsogeny W₁) := by
  apply Isogeny.ext
  apply AlgHom.ext
  intro x
  have h := congrArg
    (fun σ : W₂.FunctionField →ₐ[F] W₁.FunctionField ↦
      σ (algebraMap W₂.CoordinateRing W₂.FunctionField x))
    (AlgHom.comp_fieldPullback_frobeniusIsogeny φ.fieldPullback)
  simpa only [comp_pullback, AlgHom.comp_apply, fieldPullback_algebraMap] using h

namespace Hom

variable [W₂.IsElliptic]

omit [W₂.IsElliptic] in
/-- Frobenius commutes with every morphism, including the zero morphism. -/
theorem frobenius_comp (f : Hom W₁ W₂) :
    (ofIsogeny (frobeniusIsogeny W₂)).comp f =
      f.comp (ofIsogeny (frobeniusIsogeny W₁)) := by
  rcases f.eq_zero_or_exists_ofIsogeny with rfl | ⟨φ, rfl⟩
  · simp
  · rw [ofIsogeny_comp_ofIsogeny, ofIsogeny_comp_ofIsogeny, frobeniusIsogeny_comp]

/-- Frobenius preserves sums of morphisms under composition. -/
@[simp]
theorem frobenius_comp_add (f g : Hom W₁ W₂) :
    (ofIsogeny (frobeniusIsogeny W₂)).comp (f + g) =
      (ofIsogeny (frobeniusIsogeny W₂)).comp f +
        (ofIsogeny (frobeniusIsogeny W₂)).comp g := by
  rw [frobenius_comp, add_comp, ← frobenius_comp, ← frobenius_comp]

end Hom

end TauCeti.Isogeny

end
