/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex, Claude
-/
module

public import Mathlib.RepresentationTheory.Homological.TateCohomology.Basic
public import Mathlib.Data.ZMod.QuotientRing

/-!
# Low-degree Tate cohomology

This file gives the low-degree descriptions used by the Nakayama map. For a representation `M`
of a finite group, degree zero is the quotient of the invariant submodule by the image of the
norm, and degree `-1` is the kernel of the norm modulo the augmentation submodule `I_G M`. For a
trivial representation `A`, the comparison with first group homology identifies degree `-2` with
`Gᵃᵇ ⊗[ℤ] A`, and hence, for the trivial integral representation, with the additive form of the
abelianization. For the trivial integral representation the same descriptions evaluate degree
zero as `ZMod |G|` and make degree `-1` trivial.

The degree-zero and degree-`-1` constructions are adapted from
`ClassFieldTheory/Cohomology/TateCohomology.lean` and
`ClassFieldTheory/Cohomology/FiniteCyclic/ExplicitTate.lean` in `kbuzzard/ClassFieldTheory`,
commit `ccc3323c6750abca25b49b35106f54eb3a398509`; the trivial integral calculations are adapted
from `ClassFieldTheory/Cohomology/FiniteCyclic/HerbrandQuotient/Trivial.lean` in the same
repository and commit. The degree-`-2` identification combines Mathlib's comparison with group
homology, `groupHomology.H1AddEquivOfIsTrivial`, and the tensor-product right unitor.

## Main definitions

* `TauCeti.TateCohomology.H0IsoNormQuotient`: `Ĥ⁰(G, M) ≅ Mᴳ / N_G M`.
* `TauCeti.TateCohomology.HNegOneIsoNormKernelQuotient`: `Ĥ⁻¹(G, M) ≅ ker N_G / I_G M`.
* `TauCeti.TateCohomology.HNegTwoAddEquivTensorOfIsTrivial`:
  `Ĥ⁻²(G, A) ≃+ Gᵃᵇ ⊗[ℤ] A` for a trivial representation `A`.
* `TauCeti.TateCohomology.HNegTwoAddEquivAbelianization`:
  `Ĥ⁻²(G, ℤ) ≃+ Additive (Gᵃᵇ)`.
* `TauCeti.TateCohomology.H0LinearEquivTrivialIntZModCard`: for the trivial integral
  representation, degree zero is `ZMod |G|`.

## Main results

* `TauCeti.TateCohomology.range_norm_trivial_int`: for trivial integral coefficients the image of
  the norm is the ideal generated by the order of the group.
* `TauCeti.TateCohomology.natCard_tateCohomology_zero_trivial_int_eq_card`: for trivial integral
  coefficients, degree zero has order the order of the group.
* `TauCeti.TateCohomology.subsingleton_tateCohomology_negOne_trivial_int`: for trivial integral
  coefficients, degree `-1` is trivial.

## References

* E. Artin and J. Tate, *Class Field Theory*, Chapter XIV, §4.
* K. S. Brown, *Cohomology of Groups*, Chapter VI, §5.
-/

public noncomputable section

universe u v

open CategoryTheory Limits groupCohomology groupHomology LinearMap Rep
open scoped TensorProduct

namespace TauCeti.TateCohomology

variable {R G : Type u} [CommRing R] [Group G] [Fintype G]

namespace Zero

variable (M : Rep R G)

/-- The concrete short complex whose homology is degree-zero Tate cohomology. -/
private def shortComplex : ShortComplex (ModuleCat R) :=
  .mk M.norm.toModuleCatHom (d₀₁ M) (norm_comp_d_eq_zero M)

/-- The degree-zero part of the Tate complex is the norm-to-coboundary short complex. -/
private def isoShortComplex' : (tateComplex M).sc' (-1) 0 1 ≅ shortComplex M := by
  have hnorm :
      (chainsIso₀ M).hom ≫ M.norm.toModuleCatHom = M.tateNorm ≫ (cochainsIso₀ M).hom := by
    simp only [Rep.tateNorm, Category.assoc, Iso.inv_hom_id, Category.comp_id]
  exact ShortComplex.isoMk (by exact chainsIso₀ M) (cochainsIso₀ M) (cochainsIso₁ M)
    hnorm (comp_d₀₁_eq M)

private def cyclesIso : (tateComplex M).cycles 0 ≅ (shortComplex M).cycles :=
  (tateComplex M).cyclesIsoSc' (-1) 0 1 (by simp) (by simp) ≪≫
    ShortComplex.cyclesMapIso (isoShortComplex' M)

@[reassoc]
private theorem cyclesIso_hom_comp_iCycles :
    (cyclesIso M).hom ≫ (shortComplex M).iCycles =
      (tateComplex M).iCycles 0 ≫ (cochainsIso₀ M).hom := by
  simp only [cyclesIso, Iso.trans_hom, Category.assoc, ShortComplex.cyclesMapIso_hom,
    ShortComplex.cyclesMap_i, HomologicalComplex.cyclesIsoSc'_hom_iCycles_assoc]
  rfl

private def cyclesIsoInvariants :
    (shortComplex M).cycles ≅ ModuleCat.of R M.ρ.invariants :=
  (shortComplex M).moduleCatCyclesIso ≪≫ eqToIso (by rfl) ≪≫
      (LinearEquiv.ofEq _ _ (d₀₁_ker_eq_invariants M)).toModuleIso

@[reassoc]
private theorem cyclesIsoInvariants_hom_comp_subtype :
    (cyclesIsoInvariants M).hom ≫ ModuleCat.ofHom M.ρ.invariants.subtype =
      (shortComplex M).iCycles := by
  ext
  rfl

private def homologyIso :
    (tateComplex M).homology 0 ≅ (shortComplex M).homology :=
  (tateComplex M).homologyIsoSc' (-1) 0 1 (by simp) (by simp) ≪≫
    ShortComplex.homologyMapIso (isoShortComplex' M)

private def homologyIsoNormQuotient :
    (shortComplex M).homology ≅
      ModuleCat.of R (M.ρ.invariants ⧸ (range M.ρ.norm).submoduleOf M.ρ.invariants) :=
  (shortComplex M).moduleCatHomologyIso ≪≫ eqToIso (by rfl) ≪≫ by
    refine (Submodule.Quotient.equiv _ _
      (LinearEquiv.ofEq _ _ (d₀₁_ker_eq_invariants M)) ?_).toModuleIso
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨_, ⟨y, rfl⟩, hy⟩
      exact ⟨y, congr(Subtype.val $hy)⟩
    · rintro ⟨y, rfl⟩
      exact ⟨⟨M.norm.hom y, norm_comp_d_eq_zero_apply _ y⟩, ⟨_, rfl⟩, rfl⟩

@[reassoc]
private theorem cyclesIso_inv_comp_homologyπ_comp_homologyIso_hom :
    (cyclesIso M).inv ≫ (tateComplex M).homologyπ 0 ≫ (homologyIso M).hom =
      (shortComplex M).homologyπ := by
  simp only [cyclesIso, homologyIso, Iso.trans_inv, Iso.trans_hom, Category.assoc,
    HomologicalComplex.π_homologyIsoSc'_hom_assoc, Iso.inv_hom_id_assoc,
    ShortComplex.homologyMapIso_hom]
  rw [ShortComplex.homologyπ_naturality]
  exact Iso.inv_hom_id_assoc (ShortComplex.cyclesMapIso (isoShortComplex' M)) _

private theorem cyclesIsoInvariants_inv_comp_homologyπ_comp_homologyIsoNormQuotient_hom :
    (cyclesIsoInvariants M).inv ≫ (shortComplex M).homologyπ ≫
        (homologyIsoNormQuotient M).hom =
      ModuleCat.ofHom (Submodule.mkQ
        ((range M.ρ.norm).submoduleOf M.ρ.invariants)) := by
  simp only [cyclesIsoInvariants, homologyIsoNormQuotient, Iso.trans_inv, Iso.trans_hom,
    Category.assoc, Iso.inv_hom_id_assoc, ShortComplex.moduleCatCyclesIso_inv_π_assoc]
  ext x
  simp only [ModuleCat.hom_comp, ConcreteCategory.hom_ofHom, LinearMap.coe_comp,
    Function.comp_apply, Submodule.mkQ_apply]
  simp only [shortComplex, Submodule.Quotient.equiv]
  rfl

end Zero

/-- Degree-zero Tate cohomology is the quotient of the invariant submodule by the image of the
norm. -/
def H0IsoNormQuotient (M : Rep R G) :
    tateCohomology M 0 ≅
      ModuleCat.of R (M.ρ.invariants ⧸ (range M.ρ.norm).submoduleOf M.ρ.invariants) :=
  Zero.homologyIso M ≪≫ Zero.homologyIsoNormQuotient M

/-- Degree-zero Tate cohomology of a finite representation is finite: it is a subquotient of the
coefficient module. -/
instance finite_tateCohomology_zero (M : Rep R G) [Finite M] : Finite (tateCohomology M 0) :=
  have : Finite (M.ρ.invariants ⧸ (range M.ρ.norm).submoduleOf M.ρ.invariants) :=
    Finite.of_surjective _ (Submodule.mkQ_surjective _)
  (H0IsoNormQuotient M).toLinearEquiv.toEquiv.finite_iff.mpr this

/-- The cycles in degree zero of the Tate complex are the invariant submodule. -/
def H0CyclesIso (M : Rep R G) :
    (tateComplex M).cycles 0 ≅ ModuleCat.of R M.ρ.invariants :=
  Zero.cyclesIso M ≪≫
    Zero.cyclesIsoInvariants M

/-- Under the degree-zero identification, including a cycle into the Tate complex is the same as
including the corresponding invariant into the coefficient module. -/
@[reassoc]
theorem H0CyclesIso_hom_comp_subtype (M : Rep R G) :
    (H0CyclesIso M).hom ≫ ModuleCat.ofHom M.ρ.invariants.subtype =
      (tateComplex M).iCycles 0 ≫ (cochainsIso₀ M).hom := by
  simp only [H0CyclesIso, Iso.trans_hom, Category.assoc,
    Zero.cyclesIsoInvariants_hom_comp_subtype]
  exact Zero.cyclesIso_hom_comp_iCycles M

/-- The map from invariant representatives to degree-zero Tate cohomology. -/
def H0π (M : Rep R G) : ModuleCat.of R M.ρ.invariants ⟶ tateCohomology M 0 :=
  ModuleCat.ofHom (Submodule.mkQ ((range M.ρ.norm).submoduleOf M.ρ.invariants)) ≫
    (H0IsoNormQuotient M).inv

/-- The representative map to degree-zero Tate cohomology is the canonical projection from
degree-zero cycles to homology, after identifying those cycles with the invariants. -/
theorem H0π_eq_cyclesIso_inv_comp_homologyπ (M : Rep R G) :
    H0π M = (H0CyclesIso M).inv ≫ (tateComplex M).homologyπ 0 := by
  refine (cancel_mono (H0IsoNormQuotient M).hom).1 ?_
  rw [H0π, Category.assoc, Iso.inv_hom_id, Category.comp_id]
  refine
    (Zero.cyclesIsoInvariants_inv_comp_homologyπ_comp_homologyIsoNormQuotient_hom M).symm.trans ?_
  rw [← Zero.cyclesIso_inv_comp_homologyπ_comp_homologyIso_hom_assoc]
  exact ((Category.assoc _ _ _).trans (congrArg ((Zero.cyclesIsoInvariants M).inv ≫ ·)
    (Category.assoc _ _ _))).symm

/-- The quotient map from invariant representatives onto degree-zero Tate cohomology is an
epimorphism. -/
instance (M : Rep R G) : Epi (H0π M) :=
  have : Epi (ModuleCat.ofHom (Submodule.mkQ ((range M.ρ.norm).submoduleOf M.ρ.invariants))) :=
    (ModuleCat.epi_iff_surjective _).2 (Submodule.mkQ_surjective _)
  inferInstanceAs <| Epi (_ ≫ _)

/-- Passing an invariant representative to degree-zero Tate cohomology and then applying the
low-degree identification is the quotient map by the norm image. -/
@[reassoc (attr := simp), elementwise (attr := simp)]
theorem H0π_comp_H0IsoNormQuotient_hom (M : Rep R G) :
    H0π M ≫ (H0IsoNormQuotient M).hom =
      ModuleCat.ofHom (Submodule.mkQ ((range M.ρ.norm).submoduleOf M.ρ.invariants)) := by
  simp [H0π]

/-- Composing the quotient map by the norm image with the inverse of the low-degree
identification is the map from invariant representatives to degree-zero Tate cohomology. -/
@[reassoc (attr := simp), elementwise (attr := simp)]
theorem mkQ_comp_H0IsoNormQuotient_inv (M : Rep R G) :
    ModuleCat.ofHom (Submodule.mkQ ((range M.ρ.norm).submoduleOf M.ρ.invariants)) ≫
      (H0IsoNormQuotient M).inv = H0π M :=
  (Iso.comp_inv_eq _).2 (H0π_comp_H0IsoNormQuotient_hom M).symm

-- `simp` reduces the carrier of `ModuleCat.of R X` to `X` (and `(Rep.trivial ℤ H ℤ).ρ` to
-- `Representation.trivial ℤ H ℤ`) in implicit type arguments before it looks a term up, so the
-- `simp` lemmas evaluating `H0π`, `HNegOneπ` and `H1π` in this file state their left-hand sides
-- through `dsimp% only`, as in #8315.
/-- An invariant represents the zero degree-zero Tate cohomology class exactly when it lies in
the image of the norm. -/
@[simp]
theorem H0π_eq_zero_iff {M : Rep R G} (y : M.ρ.invariants) :
    (dsimp% only (H0π M y)) = 0 ↔ y ∈ (range M.ρ.norm).submoduleOf M.ρ.invariants := by
  rw [← Submodule.Quotient.mk_eq_zero, ← H0π_comp_H0IsoNormQuotient_hom_apply]
  exact ((H0IsoNormQuotient M).toLinearEquiv.map_eq_zero_iff).symm

/-- Two invariants represent the same degree-zero Tate cohomology class exactly when their
difference lies in the image of the norm. -/
@[simp]
theorem H0π_eq_iff {M : Rep R G} (y z : M.ρ.invariants) :
    (dsimp% only (H0π M y = H0π M z)) ↔ y - z ∈ (range M.ρ.norm).submoduleOf M.ρ.invariants := by
  rw [← sub_eq_zero, ← map_sub, H0π_eq_zero_iff]

/-- Every degree-zero Tate cohomology class is represented by an invariant, so a property of all
classes follows from the property of the classes of invariants. -/
@[elab_as_elim]
theorem H0_induction_on {M : Rep R G} {C : tateCohomology M 0 → Prop} (x : tateCohomology M 0)
    (h : ∀ y : M.ρ.invariants, C (H0π M y)) : C x := by
  obtain ⟨y, hy⟩ := Submodule.mkQ_surjective ((range M.ρ.norm).submoduleOf M.ρ.invariants)
    ((H0IsoNormQuotient M).hom x)
  have hx : H0π M y = x := by
    rw [← mkQ_comp_H0IsoNormQuotient_inv_apply, ← Submodule.mkQ_apply, hy,
      Iso.hom_inv_id_apply]
  exact hx ▸ h y

namespace NegOne

variable (M : Rep R G)

/-- The concrete short complex computing degree `-1` Tate cohomology. -/
private def shortComplex : ShortComplex (ModuleCat R) :=
  .mk (d₁₀ M) M.norm.toModuleCatHom (Rep.comp_eq_zero M)

/-- The degree `-1` part of the Tate complex is the augmentation-to-norm short complex. -/
private def isoShortComplex : (tateComplex M).sc (-1) ≅ shortComplex M := by
  have hnorm :
      (chainsIso₀ M).hom ≫ M.norm.toModuleCatHom =
        M.tateNorm ≫ (cochainsIso₀ M).hom := by
    simp only [Rep.tateNorm, Category.assoc, Iso.inv_hom_id, Category.comp_id]
  exact (tateComplex M).isoSc' (-2) (-1) 0 (by simp) (by simp) ≪≫
    ShortComplex.isoMk (chainsIso₁ M) (chainsIso₀ M) (cochainsIso₀ M)
      (comp_d₁₀_eq M) hnorm

private def cyclesIso : (tateComplex M).cycles (-1) ≅ (shortComplex M).cycles :=
  ShortComplex.cyclesMapIso (isoShortComplex M)

@[reassoc]
private theorem cyclesIso_hom_comp_iCycles :
    (cyclesIso M).hom ≫ (shortComplex M).iCycles =
      (tateComplex M).iCycles (-1) ≫ (chainsIso₀ M).hom :=
  ShortComplex.cyclesMap_i (isoShortComplex M).hom

@[reassoc]
private theorem cyclesIso_inv_comp_homologyπ_comp_homologyMapIso_hom :
    (cyclesIso M).inv ≫ (tateComplex M).homologyπ (-1) ≫
        (ShortComplex.homologyMapIso (isoShortComplex M)).hom =
      (shortComplex M).homologyπ :=
  (congrArg ((cyclesIso M).inv ≫ ·)
    (ShortComplex.homologyπ_naturality (isoShortComplex M).hom)).trans
    (Iso.inv_hom_id_assoc (ShortComplex.cyclesMapIso (isoShortComplex M)) _)

end NegOne

/-- Degree `-1` Tate cohomology is the kernel of the norm modulo the augmentation submodule,
namely the kernel of the quotient to coinvariants. -/
def HNegOneIsoNormKernelQuotient (M : Rep R G) :
    tateCohomology M (-1) ≅ ModuleCat.of R
      (ker M.ρ.norm ⧸
        (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)) := calc
  tateCohomology M (-1) ≅ (NegOne.shortComplex M).homology :=
    ShortComplex.homologyMapIso (NegOne.isoShortComplex M)
  _ ≅ ModuleCat.of R (ker M.ρ.norm ⧸ _) :=
    ShortComplex.moduleCatHomologyIso _
  _ ≅ ModuleCat.of R
      (ker M.ρ.norm ⧸
        (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)) := by
    refine (Submodule.Quotient.equiv _ _ (LinearEquiv.refl R _) ?_).toModuleIso
    rw [← range_d₁₀_eq_coinvariantsKer]
    refine Submodule.ext fun ⟨x, hx⟩ ↦ ⟨?_, ?_⟩
    · rintro ⟨_, ⟨y, rfl⟩, hy⟩
      exact ⟨y, congr(Subtype.val $hy)⟩
    · rintro ⟨y, rfl⟩
      exact ⟨⟨d₁₀ M y,
        LinearMap.congr_fun (ModuleCat.hom_ext_iff.mp (Rep.comp_eq_zero M)) y⟩,
        ⟨_, rfl⟩, rfl⟩

/-- Degree `-1` Tate cohomology of a finite representation is finite: it is a subquotient of the
coefficient module. -/
instance finite_tateCohomology_negOne (M : Rep R G) [Finite M] :
    Finite (tateCohomology M (-1)) :=
  have : Finite (ker M.ρ.norm ⧸
      (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)) :=
    Finite.of_surjective _ (Submodule.mkQ_surjective _)
  (HNegOneIsoNormKernelQuotient M).toLinearEquiv.toEquiv.finite_iff.mpr this

/-- The quotient map from norm-zero representatives to degree `-1` Tate cohomology. -/
def HNegOneπ (M : Rep R G) : ModuleCat.of R (ker M.ρ.norm) ⟶ tateCohomology M (-1) :=
  ModuleCat.ofHom
      (Submodule.mkQ ((Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm))) ≫
    (HNegOneIsoNormKernelQuotient M).inv

/-- The quotient map from norm-zero representatives onto degree `-1` Tate cohomology is an
epimorphism. -/
instance (M : Rep R G) : Epi (HNegOneπ M) :=
  have : Epi (ModuleCat.ofHom
      (Submodule.mkQ ((Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm)))) :=
    (ModuleCat.epi_iff_surjective _).2 (Submodule.mkQ_surjective _)
  inferInstanceAs <| Epi (_ ≫ _)

/-- Under the degree `-1` identification, `HNegOneπ` is the quotient map by the augmentation
submodule. -/
@[reassoc (attr := simp), elementwise (attr := simp)]
theorem HNegOneπ_comp_HNegOneIsoNormKernelQuotient_hom (M : Rep R G) :
    HNegOneπ M ≫ (HNegOneIsoNormKernelQuotient M).hom =
      ModuleCat.ofHom
        (Submodule.mkQ
          ((Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm))) := by
  simp [HNegOneπ]

-- `dsimp% only` on the left-hand side: see the comment on `H0π_eq_zero_iff`.
/-- A norm-zero element represents zero in degree `-1` Tate cohomology exactly when it belongs to
the augmentation submodule. -/
@[simp]
theorem HNegOneπ_eq_zero_iff {M : Rep R G} (x : ker M.ρ.norm) :
    (dsimp% only (HNegOneπ M x)) = 0 ↔
      x ∈ (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm) := by
  rw [← Submodule.Quotient.mk_eq_zero,
    ← HNegOneπ_comp_HNegOneIsoNormKernelQuotient_hom_apply]
  exact ((HNegOneIsoNormKernelQuotient M).toLinearEquiv.map_eq_zero_iff).symm

/-- Two norm-zero elements represent the same degree `-1` Tate class exactly when their
difference belongs to the augmentation submodule. -/
@[simp]
theorem HNegOneπ_eq_iff {M : Rep R G} (x y : ker M.ρ.norm) :
    (dsimp% only (HNegOneπ M x = HNegOneπ M y)) ↔
      x - y ∈ (Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm) := by
  rw [← sub_eq_zero, ← map_sub, HNegOneπ_eq_zero_iff]

/-- Every degree `-1` Tate cohomology class is represented by a norm-zero element, so a property
of all classes follows from the property of the classes of norm-zero elements. -/
@[elab_as_elim]
theorem HNegOne_induction_on {M : Rep R G} {C : tateCohomology M (-1) → Prop}
    (x : tateCohomology M (-1)) (h : ∀ y : ker M.ρ.norm, C (HNegOneπ M y)) : C x := by
  obtain ⟨y, hy⟩ := Submodule.mkQ_surjective
    ((Representation.Coinvariants.ker M.ρ).submoduleOf (ker M.ρ.norm))
    ((HNegOneIsoNormKernelQuotient M).hom x)
  have hx : HNegOneπ M y = x := by
    apply (ModuleCat.mono_iff_injective (HNegOneIsoNormKernelQuotient M).hom).1 inferInstance
    rw [HNegOneπ_comp_HNegOneIsoNormKernelQuotient_hom_apply]
    simpa only [Submodule.mkQ_apply] using hy
  exact hx ▸ h y

/-- The cycles in degree `-1` of the Tate complex are the kernel of the norm. -/
def HNegOneCyclesIso (M : Rep R G) :
    (tateComplex M).cycles (-1) ≅ ModuleCat.of R (ker M.ρ.norm) :=
  NegOne.cyclesIso M ≪≫ (NegOne.shortComplex M).moduleCatCyclesIso ≪≫ eqToIso (by rfl)

/-- Under the degree `-1` identification, including a cycle into the Tate complex is the same as
including the corresponding norm-zero element into the coefficient module. -/
@[reassoc]
theorem HNegOneCyclesIso_hom_comp_subtype (M : Rep R G) :
    (HNegOneCyclesIso M).hom ≫ ModuleCat.ofHom (ker M.ρ.norm).subtype =
      (tateComplex M).iCycles (-1) ≫ (chainsIso₀ M).hom := by
  simp only [HNegOneCyclesIso, Iso.trans_hom, Category.assoc]
  exact (congrArg _ (NegOne.shortComplex M).moduleCatCyclesIso_hom_i).trans
    (NegOne.cyclesIso_hom_comp_iCycles M)

/-- The representative map to degree `-1` Tate cohomology is the canonical projection from
degree `-1` cycles to homology, after identifying those cycles with the kernel of the norm. -/
theorem HNegOneπ_eq_cyclesIso_inv_comp_homologyπ (M : Rep R G) :
    HNegOneπ M = (HNegOneCyclesIso M).inv ≫ (tateComplex M).homologyπ (-1) := by
  let S := NegOne.shortComplex M
  let e := ShortComplex.homologyMapIso (NegOne.isoShortComplex M)
  -- The degree `-1` homology of the Tate complex is by definition the homology of its short
  -- complex in degree `-1`; the comparisons are therefore composed as terms, since `rw` cannot
  -- match across that unfolding.
  have h1 : (NegOne.cyclesIso M).inv ≫ (tateComplex M).homologyπ (-1) = S.homologyπ ≫ e.inv :=
    (Iso.eq_comp_inv e).2 ((Category.assoc _ _ _).trans
      (NegOne.cyclesIso_inv_comp_homologyπ_comp_homologyMapIso_hom M))
  have h2 : HNegOneπ M = S.moduleCatLeftHomologyData.π ≫ S.moduleCatHomologyIso.inv ≫ e.inv := by
    ext x
    rfl
  refine h2.trans ((Category.assoc _ _ _).symm.trans ?_)
  refine (congrArg (· ≫ e.inv) S.moduleCatCyclesIso_inv_π.symm).trans ?_
  exact (Category.assoc _ _ _).trans (congrArg (S.moduleCatCyclesIso.inv ≫ ·) h1.symm)

variable (A : Rep R G) [A.IsTrivial]

/-- For a trivial representation `A`, degree-`-2` Tate cohomology is the tensor product of the
additive abelianization of the group with `A`. -/
def HNegTwoAddEquivTensorOfIsTrivial :
    tateCohomology A (-2) ≃+ (Additive <| Abelianization G) ⊗[ℤ] A :=
  let e : tateCohomology A (-2) ≅ groupHomology.H1 A :=
    (TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).app A
  e.toLinearEquiv.toAddEquiv.trans (H1AddEquivOfIsTrivial A)

/-- The degree `-2` Tate identification factors through the comparison with first homology. -/
theorem HNegTwoAddEquivTensorOfIsTrivial_apply (x : tateCohomology A (-2)) :
    HNegTwoAddEquivTensorOfIsTrivial A x =
      H1AddEquivOfIsTrivial A
        ((_root_.TateCohomology.isoGroupHomology (-2) 1 rfl).hom.app A x) := by
  rw [HNegTwoAddEquivTensorOfIsTrivial]
  rfl

-- `dsimp% only` on the left-hand side: see the comment on `H0π_eq_zero_iff`.
/-- The degree-`-2` identification sends the homology class represented by `(g, a)` to the
elementary tensor `⟦g⟧ ⊗ₜ a`. -/
@[simp]
theorem HNegTwoAddEquivTensorOfIsTrivial_single (g : G) (a : A) :
    (dsimp% only (HNegTwoAddEquivTensorOfIsTrivial A
      ((TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).inv.app A
        (H1π A ((cycles₁IsoOfIsTrivial A).inv (Finsupp.single g a)))))) =
      Additive.ofMul (Abelianization.of g) ⊗ₜ[ℤ] a :=
  -- The natural isomorphism lands in `groupHomology.functor R G 1`, whereas the low-degree API
  -- uses the definitionally equal alias `groupHomology.H1`; the two facts are therefore composed
  -- as terms, since `rw` cannot match across that unfolding.
  (congrArg (H1AddEquivOfIsTrivial A)
    (((TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).app A).inv_hom_id_apply _)).trans
    (H1AddEquivOfIsTrivial_single A g a)

/-- The inverse degree-`-2` identification sends an elementary tensor to the corresponding Tate
homology class. -/
@[simp]
theorem HNegTwoAddEquivTensorOfIsTrivial_symm_tmul (g : G) (a : A) :
    (HNegTwoAddEquivTensorOfIsTrivial A).symm
        (Additive.ofMul (Abelianization.of g) ⊗ₜ[ℤ] a) =
      (TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).inv.app A
        (H1π A ((cycles₁IsoOfIsTrivial A).inv (Finsupp.single g a))) := by
  simp [AddEquiv.symm_apply_eq]

variable {G : Type} [Group G] [Fintype G]

/-- The degree-`-2` Tate cohomology of the trivial integral representation is the additive
abelianization of the group. -/
def HNegTwoAddEquivAbelianization :
    tateCohomology (Rep.trivial ℤ G ℤ) (-2) ≃+ Additive (Abelianization G) :=
  (HNegTwoAddEquivTensorOfIsTrivial (Rep.trivial ℤ G ℤ)).trans
    (TensorProduct.rid ℤ (Additive (Abelianization G))).toAddEquiv

-- `dsimp% only` on the left-hand side: see the comment on `H0π_eq_zero_iff`.
/-- The degree-`-2` identification sends the homology class represented by `(g, 1)` to the class
of `g` in the additive abelianization. -/
@[simp]
theorem HNegTwoAddEquivAbelianization_single_one (g : G) :
    (dsimp% only (HNegTwoAddEquivAbelianization
      ((TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).inv.app (Rep.trivial ℤ G ℤ)
        (H1π (Rep.trivial ℤ G ℤ)
          ((cycles₁IsoOfIsTrivial (Rep.trivial ℤ G ℤ)).inv (Finsupp.single g 1)))))) =
      Additive.ofMul (Abelianization.of g) := by
  rw [HNegTwoAddEquivAbelianization, AddEquiv.trans_apply, HNegTwoAddEquivTensorOfIsTrivial_single]
  simp

/-- The inverse integral degree-`-2` identification sends the class of `g` to the Tate homology
class represented by `(g, 1)`. -/
@[simp]
theorem HNegTwoAddEquivAbelianization_symm_of (g : G) :
    HNegTwoAddEquivAbelianization.symm (Additive.ofMul (Abelianization.of g)) =
      (TateCohomology.isoGroupHomology (-2) 1 (Eq.refl (-2))).inv.app
        (Rep.trivial ℤ G ℤ)
        (H1π (Rep.trivial ℤ G ℤ)
          ((cycles₁IsoOfIsTrivial (Rep.trivial ℤ G ℤ)).inv (Finsupp.single g 1))) := by
  simp [AddEquiv.symm_apply_eq]

section TrivialInt

variable (H : Type v) [Group H] [Fintype H]

-- Stated over `Representation.trivial ℤ H ℤ`, the form to which `simp` reduces
-- `(Rep.trivial ℤ H ℤ).ρ`, so that it fires.
/-- For trivial integral coefficients, the norm image is the ideal generated by the order of the
group. -/
@[simp]
theorem range_norm_trivial_int :
    range (Representation.trivial ℤ H ℤ).norm = Ideal.span {(Nat.card H : ℤ)} := by
  ext x
  simp [Representation.norm, Ideal.mem_span_singleton', mul_comm]

-- Mathlib's Tate cohomology takes its coefficient ring and its group in a single universe, so
-- with integral coefficients the group is confined to `Type`.
variable (H : Type) [Group H] [Fintype H]

/-- Degree-zero Tate cohomology with trivial integral coefficients is `ZMod |G|`. -/
def H0LinearEquivTrivialIntZModCard :
    tateCohomology (Rep.trivial ℤ H ℤ) 0 ≃ₗ[ℤ] ZMod (Nat.card H) := by
  -- A trivial representation is its own invariant submodule, so the inclusion of the invariants
  -- is an equivalence onto `ℤ`.
  let e : (Rep.trivial ℤ H ℤ).ρ.invariants ≃ₗ[ℤ] ℤ :=
    LinearEquiv.ofEq _ _ (Representation.invariants_eq_top _) ≪≫ₗ Submodule.topEquiv
  have he : (e : (Rep.trivial ℤ H ℤ).ρ.invariants →ₗ[ℤ] ℤ) =
      (Rep.trivial ℤ H ℤ).ρ.invariants.subtype := by
    ext x
    simp [e]
  have hsurjective : Function.Surjective
      ⇑(Rep.trivial ℤ H ℤ).ρ.invariants.subtype :=
    LinearMap.range_eq_top.mp <| by
      rw [Submodule.range_subtype, Representation.invariants_eq_top]
  refine (H0IsoNormQuotient (Rep.trivial ℤ H ℤ)).toLinearEquiv ≪≫ₗ
    Submodule.Quotient.equiv _ _ e ?_ ≪≫ₗ
      (Int.quotientSpanNatEquivZMod _).toIntLinearEquiv
  rw [he, Submodule.submoduleOf, Submodule.map_comap_eq_of_surjective hsurjective,
    range_norm_trivial_int]

-- `dsimp% only` on the left-hand side: see the comment on `H0π_eq_zero_iff`.
/-- The degree-zero equivalence sends an invariant representative to its residue class modulo the
order of the group. -/
@[simp]
theorem H0LinearEquivTrivialIntZModCard_H0π (x : (Rep.trivial ℤ H ℤ).ρ.invariants) :
    (dsimp% only (H0LinearEquivTrivialIntZModCard H (H0π (Rep.trivial ℤ H ℤ) x))) = (x : ℤ) := by
  simp only [H0LinearEquivTrivialIntZModCard, LinearEquiv.trans_apply]
  rw [Iso.toLinearEquiv_apply, H0π_comp_H0IsoNormQuotient_hom_apply,
    Submodule.Quotient.equiv_apply, Submodule.mapQ_apply]
  rfl

/-- The order of degree-zero Tate cohomology with trivial integral coefficients is the order of
the group. -/
@[simp]
theorem natCard_tateCohomology_zero_trivial_int_eq_card :
    Nat.card (tateCohomology (Rep.trivial ℤ H ℤ) 0) = Nat.card H := by
  rw [Nat.card_congr (H0LinearEquivTrivialIntZModCard H).toEquiv, Nat.card_zmod]

/-- Degree `-1` Tate cohomology with trivial integral coefficients is trivial. -/
instance subsingleton_tateCohomology_negOne_trivial_int :
    Subsingleton (tateCohomology (Rep.trivial ℤ H ℤ) (-1)) := by
  let Q := ker (Rep.trivial ℤ H ℤ).ρ.norm ⧸
    (Representation.Coinvariants.ker (Rep.trivial ℤ H ℤ).ρ).submoduleOf
      (ker (Rep.trivial ℤ H ℤ).ρ.norm)
  have hker : ker (Rep.trivial ℤ H ℤ).ρ.norm = ⊥ := by
    ext x
    simp [Representation.norm]
  have hQ : Subsingleton Q := by
    have hkerSubsingleton : Subsingleton (ker (Rep.trivial ℤ H ℤ).ρ.norm) := by
      rw [hker]
      infer_instance
    let _ : Subsingleton (ker (Rep.trivial ℤ H ℤ).ρ.norm) := hkerSubsingleton
    infer_instance
  let _ : Subsingleton Q := hQ
  exact Function.Injective.subsingleton (HNegOneIsoNormKernelQuotient
    (Rep.trivial ℤ H ℤ)).toLinearEquiv.injective

end TrivialInt

end TauCeti.TateCohomology
