/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Homology.AInfinity.Coderivation

/-!
# Nonunital A-infinity algebras

An uncurved nonunital `A∞` algebra on an internally `ℤ`-graded module consists of operations
`m n` of degree `2 - n`, with `m 0 = 0`, whose suspended Taylor map extends to a square-zero
degree-one coderivation of the reduced tensor coalgebra.  This file packages that definition and
exposes both of its standard presentations: the bar differential and the unsuspended Stasheff
identities.

The comparison between the presentations uses the degree-`-1` suspension convention.  In
particular, the arity-two identity has the sign `(-1)^|a|` on `m₂(a,m₁(b))`, while the arity-three
identity becomes ordinary associativity when `m₃` vanishes.  Arity zero is explicitly forced to
vanish, rather than being unconstrained data hidden from the bar construction.

## Main definitions

* `TauCeti.AInfinityAlgebra`: an uncurved nonunital `A∞` algebra.
* `TauCeti.AInfinityAlgebra.barDifferential`: its square-zero bar coderivation.
* `TauCeti.AInfinityAlgebra.ofStasheff`: construct an algebra from the unsuspended identities.
* `TauCeti.AInfinityAlgebra.differential`: the unary operation as a linear endomorphism.
* `TauCeti.AInfinityAlgebra.mul`: the binary operation as a bilinear map.

## Main results

* `TauCeti.AInfinityAlgebra.stasheff`: the unsuspended Stasheff identities, with
  `stasheff_arity_one` through `stasheff_arity_four` evaluated verbatim.
* `TauCeti.AInfinityAlgebra.taylor_of_two` and
  `TauCeti.AInfinityAlgebra.barDifferential_of_two`: the Taylor map and the bar differential on a
  two-letter word.

## References

* E. Getzler and J. D. S. Jones, *A-infinity algebras and the cyclic bar complex*, Sections 1--2.
* B. Keller, *Introduction to A-infinity algebras and modules*, Sections 3.1 and 3.6.
-/

public section

open scoped DirectSum TensorProduct

universe uR uA

namespace TauCeti

-- Interface provenance: the first `A∞` algebra prototype in
-- `TauCetiRoadmap/DGAInfinity/Suggested.lean` supplied the public shape packaged below.
/-- An uncurved nonunital `A∞` algebra over a commutative ring.

The Taylor map is stored alongside the operations because suspension depends on the degrees of
homogeneous inputs.  `taylor_isSuspension` determines it uniquely from `grading` and `m`, as
recorded by `AInfinity.IsSuspension.taylor_eq`.  Its graded Taylor expansion is the primary bar
coderivation, and `bar_square_zero` is the stored Stasheff law. -/
structure AInfinityAlgebra (R : Type uR) (A : Type uA) [CommRing R] [AddCommGroup A]
    [Module R A] where
  /-- The internal cohomological grading of the carrier. -/
  grading : InternalGrading R A
  /-- The unsuspended arity-`n` operation. -/
  m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A
  /-- The arity-zero operation vanishes: the algebra is uncurved. -/
  m_zero : m 0 = 0
  /-- The operation `m n` has cohomological degree `2 - n`. -/
  m_degree : ∀ n, 0 < n →
    MultilinearMap.IsHomogeneous (m n) (fun _ ↦ grading.piece) grading.piece (2 - n)
  /-- The Taylor map from nonempty suspended tensor words to suspended letters. -/
  taylor : ReducedTensorWords R A →ₗ[R] A
  /-- The Taylor map is the suspension of the displayed operations. -/
  taylor_isSuspension : AInfinity.IsSuspension grading taylor m
  /-- The degree-one coderivation extended from `taylor` squares to zero. -/
  bar_square_zero :
    ReducedTensorWords.gradedCoderiv (grading.shift 1) taylor 1 ∘ₗ
        ReducedTensorWords.gradedCoderiv (grading.shift 1) taylor 1 = 0

namespace AInfinityAlgebra

variable {R : Type uR} {A : Type uA} [CommRing R] [AddCommGroup A] [Module R A]

attribute [simp] AInfinityAlgebra.m_zero

/-- The degree-one coderivation of the reduced bar construction. -/
noncomputable def barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords R A →ₗ[R] ReducedTensorWords R A :=
  ReducedTensorWords.gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1

/-- The bar differential is the coderivation generated by the stored Taylor map. -/
theorem barDifferential_def (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential =
      ReducedTensorWords.gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1 := by
  rw [barDifferential]

/-- The bar differential is a graded coderivation for the suspended grading. -/
theorem isGradedCoderivation_barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords.IsGradedCoderivation (𝒜.grading.shift 1) 1 𝒜.barDifferential := by
  simpa only [barDifferential_def] using
    ReducedTensorWords.isGradedCoderivation_gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1

/-- The bar differential has cohomological degree one. -/
theorem isHomogeneous_barDifferential (𝒜 : AInfinityAlgebra R A) :
    LinearMap.IsHomogeneous 𝒜.barDifferential
      (ReducedTensorWords.gradedPiece (𝒜.grading.shift 1))
      (ReducedTensorWords.gradedPiece (𝒜.grading.shift 1)) 1 := by
  simpa only [barDifferential_def] using
    ReducedTensorWords.isHomogeneous_gradedCoderiv (𝒜.grading.shift 1) 𝒜.taylor 1 _
      (𝒜.taylor_isSuspension.isHomogeneous 𝒜.m_degree)

/-- The letter component of the bar differential is its stored Taylor map. -/
@[simp]
theorem letter_comp_barDifferential (𝒜 : AInfinityAlgebra R A) :
    ReducedTensorWords.letter R A ∘ₗ 𝒜.barDifferential = 𝒜.taylor := by
  rw [barDifferential, ReducedTensorWords.letter_comp_gradedCoderiv]

/-- The bar differential squares to zero. -/
@[simp]
theorem barDifferential_sq (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential ∘ₗ 𝒜.barDifferential = 0 := by
  simpa only [barDifferential_def] using 𝒜.bar_square_zero

/-- The square-zero bar law is equivalent to all unsuspended Stasheff identities on homogeneous
inputs. -/
theorem barDifferential_sq_iff_stasheff (𝒜 : AInfinityAlgebra R A) :
    𝒜.barDifferential ∘ₗ 𝒜.barDifferential = 0 ↔
      ∀ (n : ℕ) (_hn : 0 < n) (d : ℕ → ℤ) (x : ℕ → A),
        (∀ i < n, x i ∈ 𝒜.grading.piece (d i)) →
          AInfinity.stasheffSum 𝒜.m d x n = 0 := by
  simpa only [barDifferential_def] using
    𝒜.taylor_isSuspension.comp_self_eq_zero_iff_forall_stasheffSum_eq_zero 𝒜.m_degree

/-- The unsuspended operations of an `A∞` algebra satisfy every Stasheff identity on homogeneous
inputs. -/
theorem stasheff (𝒜 : AInfinityAlgebra R A) (n : ℕ) (hn : 0 < n)
    (d : ℕ → ℤ) (x : ℕ → A) (hx : ∀ i < n, x i ∈ 𝒜.grading.piece (d i)) :
    AInfinity.stasheffSum 𝒜.m d x n = 0 :=
  𝒜.barDifferential_sq_iff_stasheff.mp 𝒜.barDifferential_sq n hn d x hx

/-- Construct an `A∞` algebra from homogeneous operations satisfying the unsuspended Stasheff
identities and a Taylor map realizing their suspension. -/
def ofStasheff (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 : m 0 = 0)
    (hm : ∀ n, 0 < n →
      MultilinearMap.IsHomogeneous (m n) (fun _ ↦ G.piece) G.piece (2 - n))
    (F : ReducedTensorWords R A →ₗ[R] A) (hFm : AInfinity.IsSuspension G F m)
    (hSI : ∀ (n : ℕ) (_hn : 0 < n) (d : ℕ → ℤ) (x : ℕ → A),
      (∀ i < n, x i ∈ G.piece (d i)) → AInfinity.stasheffSum m d x n = 0) :
    AInfinityAlgebra R A where
  grading := G
  m := m
  m_zero := hm0
  m_degree := hm
  taylor := F
  taylor_isSuspension := hFm
  bar_square_zero :=
    (hFm.comp_self_eq_zero_iff_forall_stasheffSum_eq_zero hm).2 hSI

@[simp]
theorem ofStasheff_grading (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).grading = G := (rfl)

@[simp]
theorem ofStasheff_m (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).m = m := (rfl)

@[simp]
theorem ofStasheff_taylor (G : InternalGrading R A)
    (m : ∀ n : ℕ, MultilinearMap R (fun _ : Fin n ↦ A) A) (hm0 hm F hFm hSI) :
    (ofStasheff G m hm0 hm F hFm hSI).taylor = F := (rfl)

/-- `A∞` algebras are determined by their grading and unsuspended operations; the Taylor map is
forced by the suspension relation and all remaining fields are propositions. -/
@[ext]
theorem ext {𝒜 𝒜' : AInfinityAlgebra R A} (hG : 𝒜.grading = 𝒜'.grading)
    (hm : 𝒜.m = 𝒜'.m) : 𝒜 = 𝒜' := by
  cases 𝒜 with
  | mk G m hm0 hmdeg F hFm hsq =>
    cases 𝒜' with
    | mk G' m' hm0' hmdeg' F' hFm' hsq' =>
      simp only at hG hm
      subst G'
      subst m'
      have hFF' := AInfinity.IsSuspension.taylor_eq hFm hFm'
      subst F'
      rfl

/-! ### Low-arity identities -/

/-- The arity-one identity is `m₁ m₁ = 0`. -/
theorem stasheff_arity_one (𝒜 : AInfinityAlgebra R A) (x : A) : 𝒜.m 1 ![𝒜.m 1 ![x]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 1).curryRight ![])
  suffices E x = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro p y hy
    have h := 𝒜.stasheff 1 (by omega) (fun _ ↦ p) (fun _ ↦ y) (fun _ _ ↦ hy)
    simpa [E, AInfinity.stasheffSum_one] using h
  rw [hE, LinearMap.zero_apply]

/-- The arity-two identity is the graded Leibniz rule, with sign `(-1)^(d 0)` on the second
differentiated input. -/
theorem stasheff_arity_two (𝒜 : AInfinityAlgebra R A) (x y : A) (p : ℤ)
    (hx : x ∈ 𝒜.grading.piece p) :
    𝒜.m 1 ![𝒜.m 2 ![x, y]] =
      𝒜.m 2 ![𝒜.m 1 ![x], y] +
        negOnePowCast R p • 𝒜.m 2 ![x, 𝒜.m 1 ![y]] := by
  let L : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 2).curryRight ![x])
  let Q : A →ₗ[R] A :=
    (𝒜.m 2).curryRight ![𝒜.m 1 ![x]] +
      negOnePowCast R p • ((𝒜.m 2).curryRight ![x]).comp ((𝒜.m 1).curryRight ![])
  suffices L y = Q y by simpa [L, Q] using this
  have hLQ : L = Q := by
    apply 𝒜.grading.linearMap_ext
    intro q z hz
    let d : ℕ → ℤ := fun i ↦ if i = 0 then p else q
    let a : ℕ → A := fun i ↦ if i = 0 then x else z
    have ha : ∀ i < 2, a i ∈ 𝒜.grading.piece (d i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 := by omega
      rcases hi' with rfl | rfl
      · simpa [a, d] using hx
      · simpa [a, d] using hz
    have h := (AInfinity.stasheffSum_two_eq_zero_iff 𝒜.m d a).mp
      (𝒜.stasheff 2 (by omega) d a ha)
    simpa [L, Q, a, d] using h
  exact LinearMap.congr_fun hLQ y

/-- The arity-three Stasheff identity, with the Koszul signs determined by the degrees of its
first two inputs. -/
theorem stasheff_arity_three (𝒜 : AInfinityAlgebra R A) (a b c : A) (p q : ℤ)
    (ha : a ∈ 𝒜.grading.piece p) (hb : b ∈ 𝒜.grading.piece q) :
    𝒜.m 1 ![𝒜.m 3 ![a, b, c]]
      + 𝒜.m 2 ![𝒜.m 2 ![a, b], c] - 𝒜.m 2 ![a, 𝒜.m 2 ![b, c]]
      + 𝒜.m 3 ![𝒜.m 1 ![a], b, c]
      + negOnePowCast R p • 𝒜.m 3 ![a, 𝒜.m 1 ![b], c]
      + negOnePowCast R (p + q) • 𝒜.m 3 ![a, b, 𝒜.m 1 ![c]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 3).curryRight ![a, b])
      + (𝒜.m 2).curryRight ![𝒜.m 2 ![a, b]]
      - ((𝒜.m 2).curryRight ![a]).comp ((𝒜.m 2).curryRight ![b])
      + (𝒜.m 3).curryRight ![𝒜.m 1 ![a], b]
      + negOnePowCast R p • (𝒜.m 3).curryRight ![a, 𝒜.m 1 ![b]]
      + negOnePowCast R (p + q) •
        ((𝒜.m 3).curryRight ![a, b]).comp ((𝒜.m 1).curryRight ![])
  suffices E c = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro r z hz
    let d : ℕ → ℤ := fun i ↦ if i = 0 then p else if i = 1 then q else r
    let x : ℕ → A := fun i ↦ if i = 0 then a else if i = 1 then b else z
    have hx : ∀ i < 3, x i ∈ 𝒜.grading.piece (d i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 ∨ i = 2 := by omega
      rcases hi' with rfl | rfl | rfl
      · simpa [x, d] using ha
      · simpa [x, d] using hb
      · simpa [x, d] using hz
    have h := 𝒜.stasheff 3 (by omega) d x hx
    rw [AInfinity.stasheffSum_three] at h
    simpa [E, x, d] using h
  rw [hE, LinearMap.zero_apply]

/-- The arity-four Stasheff identity, with the Koszul signs determined by the degrees of its
first three inputs. -/
theorem stasheff_arity_four (𝒜 : AInfinityAlgebra R A) (a b c d : A) (p q r : ℤ)
    (ha : a ∈ 𝒜.grading.piece p) (hb : b ∈ 𝒜.grading.piece q)
    (hc : c ∈ 𝒜.grading.piece r) :
    𝒜.m 1 ![𝒜.m 4 ![a, b, c, d]] - 𝒜.m 2 ![𝒜.m 3 ![a, b, c], d]
      - negOnePowCast R p • 𝒜.m 2 ![a, 𝒜.m 3 ![b, c, d]]
      + 𝒜.m 3 ![𝒜.m 2 ![a, b], c, d] - 𝒜.m 3 ![a, 𝒜.m 2 ![b, c], d]
      + 𝒜.m 3 ![a, b, 𝒜.m 2 ![c, d]] - 𝒜.m 4 ![𝒜.m 1 ![a], b, c, d]
      - negOnePowCast R p • 𝒜.m 4 ![a, 𝒜.m 1 ![b], c, d]
      - negOnePowCast R (p + q) • 𝒜.m 4 ![a, b, 𝒜.m 1 ![c], d]
      - negOnePowCast R (p + q + r) • 𝒜.m 4 ![a, b, c, 𝒜.m 1 ![d]] = 0 := by
  let E : A →ₗ[R] A :=
    ((𝒜.m 1).curryRight ![]).comp ((𝒜.m 4).curryRight ![a, b, c])
      - (𝒜.m 2).curryRight ![𝒜.m 3 ![a, b, c]]
      - negOnePowCast R p •
        ((𝒜.m 2).curryRight ![a]).comp ((𝒜.m 3).curryRight ![b, c])
      + (𝒜.m 3).curryRight ![𝒜.m 2 ![a, b], c]
      - (𝒜.m 3).curryRight ![a, 𝒜.m 2 ![b, c]]
      + ((𝒜.m 3).curryRight ![a, b]).comp ((𝒜.m 2).curryRight ![c])
      - (𝒜.m 4).curryRight ![𝒜.m 1 ![a], b, c]
      - negOnePowCast R p • (𝒜.m 4).curryRight ![a, 𝒜.m 1 ![b], c]
      - negOnePowCast R (p + q) • (𝒜.m 4).curryRight ![a, b, 𝒜.m 1 ![c]]
      - negOnePowCast R (p + q + r) •
        ((𝒜.m 4).curryRight ![a, b, c]).comp ((𝒜.m 1).curryRight ![])
  suffices E d = 0 by simpa [E] using this
  have hE : E = 0 := by
    apply 𝒜.grading.linearMap_ext
    intro s z hz
    let e : ℕ → ℤ := fun i ↦
      if i = 0 then p else if i = 1 then q else if i = 2 then r else s
    let x : ℕ → A := fun i ↦
      if i = 0 then a else if i = 1 then b else if i = 2 then c else z
    have hx : ∀ i < 4, x i ∈ 𝒜.grading.piece (e i) := by
      intro i hi
      have hi' : i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 := by omega
      rcases hi' with rfl | rfl | rfl | rfl
      · simpa [x, e] using ha
      · simpa [x, e] using hb
      · simpa [x, e] using hc
      · simpa [x, e] using hz
    have h := 𝒜.stasheff 4 (by omega) e x hx
    rw [AInfinity.stasheffSum_four] at h
    simpa [E, x, e] using h
  rw [hE, LinearMap.zero_apply]

/-! ### Low-arity identities for arbitrary inputs -/

/-- The unary `A∞` operation, regarded as a linear differential on the total module. -/
def differential (𝒜 : AInfinityAlgebra R A) : A →ₗ[R] A :=
  (𝒜.m 1).curryRight ![]

/-- Evaluating the differential is evaluating the unary operation. -/
@[simp]
theorem differential_apply (𝒜 : AInfinityAlgebra R A) (x : A) :
    𝒜.differential x = 𝒜.m 1 ![x] := by
  simp [differential, MultilinearMap.curryRight_apply]

/-- The unary operation raises the degree by one. -/
theorem differential_mem_piece (𝒜 : AInfinityAlgebra R A) {p : ℤ} {x : A}
    (hx : x ∈ 𝒜.grading.piece p) : 𝒜.differential x ∈ 𝒜.grading.piece (p + 1) := by
  simpa using (𝒜.m_degree 1 one_pos).map_mem (fun _ ↦ p) ![x] (fun _ ↦ by simpa using hx)

/-- On a single letter the Taylor map is the unary operation: the suspension sign of a word of
length one is trivial. -/
@[simp]
theorem taylor_ofLetter (𝒜 : AInfinityAlgebra R A) (x : A) :
    𝒜.taylor (ReducedTensorWords.ofLetter R A x) = 𝒜.m 1 ![x] := by
  have h : 𝒜.taylor ∘ₗ ReducedTensorWords.ofLetter R A = 𝒜.differential := by
    refine 𝒜.grading.linearMap_ext fun p y hy ↦ ?_
    have hs := (AInfinity.isSuspension_def _ _ _).1 𝒜.taylor_isSuspension 1 Nat.one_pos
      (fun _ ↦ p) (fun _ ↦ y) fun _ _ ↦ hy
    rw [ReducedTensorWords.of_tprod_eq_subword R Nat.one_pos,
      ReducedTensorWords.subword_one R A _ Nat.one_pos] at hs
    rw [LinearMap.comp_apply, hs, AInfinity.evalNat_suspend, _root_.MultilinearMap.suspExp_one,
      negOnePowCast_zero, one_smul, MultilinearMap.evalNat_def, differential_apply]
    congr 1
    funext i
    fin_cases i
    rfl
  simpa using LinearMap.congr_fun h x

/-- The bar differential sends a single letter to the single letter given by the unary
operation. -/
@[simp]
theorem barDifferential_ofLetter (𝒜 : AInfinityAlgebra R A) (x : A) :
    𝒜.barDifferential (ReducedTensorWords.ofLetter R A x) =
      ReducedTensorWords.ofLetter R A (𝒜.m 1 ![x]) := by
  -- A coderivation sends primitives to primitives, and the primitives are the single letters.
  have hd : ReducedTensorWords.deconcatenation R A
      (𝒜.barDifferential (ReducedTensorWords.ofLetter R A x)) = 0 := by
    rw [𝒜.isGradedCoderivation_barDifferential.deconcatenation_apply,
      ReducedTensorWords.deconcatenation_ofLetter, map_zero, map_zero, map_zero, add_zero]
  obtain ⟨y, hy⟩ := (ReducedTensorWords.deconcatenation_eq_zero_iff R A).1 hd
  rw [← taylor_ofLetter, ← letter_comp_barDifferential, LinearMap.comp_apply, ← hy,
    ReducedTensorWords.letter_ofLetter]

/-- The binary `A∞` operation, regarded as a linear map in each argument. -/
def mul (𝒜 : AInfinityAlgebra R A) : A →ₗ[R] A →ₗ[R] A :=
  LinearMap.mk₂ R (fun x y ↦ 𝒜.m 2 ![x, y])
    (fun x x' y ↦ by
      convert (𝒜.m 2).map_update_add ![x, y] 0 x x' using 3 <;> ext i <;> fin_cases i <;> rfl)
    (fun c x y ↦ by
      convert (𝒜.m 2).map_update_smul ![x, y] 0 c x using 3 <;> ext i <;> fin_cases i <;> rfl)
    (fun x y y' ↦ by
      convert (𝒜.m 2).map_update_add ![x, y] 1 y y' using 3 <;> ext i <;> fin_cases i <;> rfl)
    (fun c x y ↦ by
      convert (𝒜.m 2).map_update_smul ![x, y] 1 c y using 3 <;> ext i <;> fin_cases i <;> rfl)

/-- Evaluating the bilinear product is evaluating the binary operation. -/
@[simp]
theorem mul_apply (𝒜 : AInfinityAlgebra R A) (x y : A) : 𝒜.mul x y = 𝒜.m 2 ![x, y] := by
  simp [mul]

/-- The binary operation has degree zero. -/
theorem mul_mem_piece (𝒜 : AInfinityAlgebra R A) {p q : ℤ} {x y : A}
    (hx : x ∈ 𝒜.grading.piece p) (hy : y ∈ 𝒜.grading.piece q) :
    𝒜.mul x y ∈ 𝒜.grading.piece (p + q) := by
  have h := (𝒜.m_degree 2 two_pos).map_mem ![p, q] ![x, y] fun i ↦ by fin_cases i <;> simpa
  simpa using h

/-- On a two-letter word the Taylor map is the binary operation, with the suspension sign carried
by the degree-one Koszul twist of the first letter. -/
theorem taylor_of_two (𝒜 : AInfinityAlgebra R A) (a b : A) :
    𝒜.taylor (ReducedTensorWords.of R A (2 : ℕ+)
        (PiTensorProduct.tprod R ![a, b])) =
      𝒜.m 2 ![𝒜.grading.koszulTwist 1 a, b] := by
  let L : A →ₗ[R] A →ₗ[R] A :=
    ((ReducedTensorWords.prepend R A).compr₂ 𝒜.taylor).compl₂
      (ReducedTensorWords.ofLetter R A)
  let Q : A →ₗ[R] A →ₗ[R] A := 𝒜.mul ∘ₗ 𝒜.grading.koszulTwist 1
  suffices h : L = Q by
    rw [← ReducedTensorWords.prepend_ofLetter]
    simpa [L, Q] using LinearMap.congr_fun (LinearMap.congr_fun h a) b
  refine 𝒜.grading.linearMap_ext fun p x hx ↦ ?_
  refine 𝒜.grading.linearMap_ext fun q y hy ↦ ?_
  have hcons : (fun i : Fin 2 ↦ if (i : ℕ) = 0 then x else y) = ![x, y] := by
    funext i
    fin_cases i <;> simp
  have hexp : _root_.MultilinearMap.suspExp 2 (fun j : ℕ ↦ if j = 0 then p else q) = p := by
    simp [_root_.MultilinearMap.suspExp_def, Finset.sum_range_succ]
  have hs := (AInfinity.isSuspension_def _ _ _).1 𝒜.taylor_isSuspension 2 (by omega)
    (fun j : ℕ ↦ if j = 0 then p else q) (fun j : ℕ ↦ if j = 0 then x else y) (by
      intro i hi
      have hi' : i = 0 ∨ i = 1 := by omega
      rcases hi' with rfl | rfl
      · simpa using hx
      · simpa using hy)
  rw [hcons] at hs
  rw [AInfinity.evalNat_suspend, MultilinearMap.evalNat_def, hcons, hexp] at hs
  have hs' : 𝒜.taylor (ReducedTensorWords.of R A (2 : ℕ+)
      (PiTensorProduct.tprod R ![x, y])) = negOnePowCast R p • 𝒜.m 2 ![x, y] := hs
  simp only [L, Q, LinearMap.compl₂_apply, LinearMap.compr₂_apply, LinearMap.comp_apply,
    𝒜.grading.koszulTwist_apply_of_mem hx, ← negOnePowCast_eq_intCast, one_mul, map_smul]
  rw [ReducedTensorWords.prepend_ofLetter]
  exact hs'

/-- The bar differential of a two-letter word: the unary operation applied to either letter, and
the collapse of both letters to the binary operation.  Koszul twists carry the suspension signs. -/
theorem barDifferential_of_two (𝒜 : AInfinityAlgebra R A) (a b : A) :
    𝒜.barDifferential (ReducedTensorWords.of R A (2 : ℕ+)
        (PiTensorProduct.tprod R ![a, b])) =
      ReducedTensorWords.of R A (2 : ℕ+)
          (PiTensorProduct.tprod R ![𝒜.m 1 ![a], b])
        + ReducedTensorWords.ofLetter R A
            (𝒜.m 2 ![𝒜.grading.koszulTwist 1 a, b])
        - ReducedTensorWords.of R A (2 : ℕ+)
            (PiTensorProduct.tprod R ![𝒜.grading.koszulTwist 1 a, 𝒜.m 1 ![b]]) := by
  have hkos : (𝒜.grading.shift 1).koszulTwist 1 = -𝒜.grading.koszulTwist 1 := by
    refine 𝒜.grading.linearMap_ext fun p x hx ↦ ?_
    have hshift : x ∈ (𝒜.grading.shift 1).piece (p - 1) := by
      rwa [InternalGrading.shift_piece, sub_add_cancel]
    have hadd := negOnePowCast_add (R := R) (p - 1) 1
    rw [sub_add_cancel, negOnePowCast_one] at hadd
    rw [LinearMap.neg_apply, InternalGrading.koszulTwist_apply_of_mem _ hshift,
      𝒜.grading.koszulTwist_apply_of_mem hx]
    simp only [one_mul, ← negOnePowCast_eq_intCast]
    rw [hadd, mul_smul, neg_one_smul, smul_neg, neg_neg]
  refine ReducedTensorWords.eq_of_deconcatenation_eq_of_letter_eq R A ?_ ?_
  · rw [𝒜.isGradedCoderivation_barDifferential.deconcatenation_apply,
      ReducedTensorWords.deconcatenation_of_two, map_sub, map_add,
      ReducedTensorWords.deconcatenation_of_two, ReducedTensorWords.deconcatenation_ofLetter,
      ReducedTensorWords.deconcatenation_of_two]
    simp only [LinearMap.rTensor_tmul, LinearMap.lTensor_tmul, ReducedTensorWords.map_ofLetter,
      barDifferential_ofLetter]
    rw [LinearMap.congr_fun hkos a, LinearMap.neg_apply, map_neg, TensorProduct.neg_tmul,
      add_zero]
    abel
  · rw [← LinearMap.comp_apply, letter_comp_barDifferential, taylor_of_two, map_sub,
      map_add, ReducedTensorWords.letter_of_two, ReducedTensorWords.letter_ofLetter,
      ReducedTensorWords.letter_of_two, zero_add, sub_zero]

/-- The unary operation squares to zero. -/
@[simp]
theorem differential_comp_self_eq_zero (𝒜 : AInfinityAlgebra R A) :
    𝒜.differential ∘ₗ 𝒜.differential = 0 := by
  ext x
  simp only [LinearMap.comp_apply, differential_apply, LinearMap.zero_apply,
    𝒜.stasheff_arity_one]

/-- The unary operation anticommutes with the degree-one Koszul twist. -/
theorem m_one_koszulTwist (𝒜 : AInfinityAlgebra R A) (x : A) :
    𝒜.m 1 ![𝒜.grading.koszulTwist 1 x] = -𝒜.grading.koszulTwist 1 (𝒜.m 1 ![x]) := by
  have h : 𝒜.differential ∘ₗ 𝒜.grading.koszulTwist 1 =
      -(𝒜.grading.koszulTwist 1 ∘ₗ 𝒜.differential) := by
    refine 𝒜.grading.linearMap_ext fun p y hy ↦ ?_
    rw [LinearMap.comp_apply, LinearMap.neg_apply, LinearMap.comp_apply,
      𝒜.grading.koszulTwist_apply_of_mem hy, map_smul,
      𝒜.grading.koszulTwist_apply_of_mem (𝒜.differential_mem_piece hy),
      ← neg_smul]
    congr 1
    simp [Int.negOnePow_succ]
  simpa using LinearMap.congr_fun h x

/-- The graded Leibniz rule for arbitrary inputs, with the sign on the second term carried by the
degree-one Koszul twist of the left factor. -/
theorem m_one_m_two (𝒜 : AInfinityAlgebra R A) (x y : A) :
    𝒜.m 1 ![𝒜.m 2 ![x, y]] =
      𝒜.m 2 ![𝒜.m 1 ![x], y] + 𝒜.m 2 ![𝒜.grading.koszulTwist 1 x, 𝒜.m 1 ![y]] := by
  have h : 𝒜.differential ∘ₗ 𝒜.mul.flip y =
      𝒜.mul.flip y ∘ₗ 𝒜.differential +
        𝒜.mul.flip (𝒜.m 1 ![y]) ∘ₗ 𝒜.grading.koszulTwist 1 := by
    refine 𝒜.grading.linearMap_ext fun p z hz ↦ ?_
    simpa [𝒜.grading.koszulTwist_apply_of_mem hz, negOnePowCast_eq_intCast] using
      𝒜.stasheff_arity_two z y p hz
  simpa using LinearMap.congr_fun h x

/-- The arity-three Stasheff identity for arbitrary inputs, with the Koszul signs of the first two
inputs carried by the degree-one twist.  It expresses the associator of the binary operation as a
unary boundary, modulo the three terms in which the ternary operation meets a unary boundary. -/
theorem m_one_m_three (𝒜 : AInfinityAlgebra R A) (x y z : A) :
    𝒜.m 1 ![𝒜.m 3 ![x, y, z]] =
      𝒜.m 2 ![x, 𝒜.m 2 ![y, z]] - 𝒜.m 2 ![𝒜.m 2 ![x, y], z]
        - 𝒜.m 3 ![𝒜.m 1 ![x], y, z]
        - 𝒜.m 3 ![𝒜.grading.koszulTwist 1 x, 𝒜.m 1 ![y], z]
        - 𝒜.m 3 ![𝒜.grading.koszulTwist 1 x, 𝒜.grading.koszulTwist 1 y, 𝒜.m 1 ![z]] := by
  -- Package the six terms as trilinear maps in the three inputs, so that the identity can be
  -- checked on homogeneous inputs, where it is `stasheff_arity_three`.
  let L : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (𝒜.mul.compMultilinearMap (𝒜.m 2)).uncurryRight
  let Qc : A →ₗ[R] MultilinearMap R (fun _ : Fin 2 ↦ A) A :=
    { toFun := fun a ↦ (𝒜.mul a).compMultilinearMap (𝒜.m 2)
      map_add' := fun a b ↦ by ext v; simp
      map_smul' := fun r a ↦ by ext v; simp }
  let Q : MultilinearMap R (fun _ : Fin 3 ↦ A) A := Qc.uncurryLeft
  have L_apply (a b c : A) : L ![a, b, c] = 𝒜.m 2 ![𝒜.m 2 ![a, b], c] := by
    simp only [L, MultilinearMap.uncurryRight_apply, LinearMap.compMultilinearMap_apply,
      mul_apply]
    congr 1
    funext i
    fin_cases i
    · apply congrArg (𝒜.m 2)
      funext j
      fin_cases j <;> rfl
    · rfl
  have Q_apply (a b c : A) : Q ![a, b, c] = 𝒜.m 2 ![a, 𝒜.m 2 ![b, c]] := by
    dsimp [Q, Qc]
    simp only [mul_apply]
  let D : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    𝒜.differential.compMultilinearMap (𝒜.m 3)
  let T₀ : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (𝒜.m 3).compLinearMap ![𝒜.differential, LinearMap.id, LinearMap.id]
  let T₁ : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (𝒜.m 3).compLinearMap
      ![𝒜.grading.koszulTwist 1, 𝒜.differential, LinearMap.id]
  let T₂ : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (𝒜.m 3).compLinearMap
      ![𝒜.grading.koszulTwist 1, 𝒜.grading.koszulTwist 1, 𝒜.differential]
  have D_apply (a b c : A) : D ![a, b, c] = 𝒜.differential (𝒜.m 3 ![a, b, c]) := rfl
  have T₀_apply (a b c : A) : T₀ ![a, b, c] = 𝒜.m 3 ![𝒜.differential a, b, c] := by
    simp only [T₀, MultilinearMap.compLinearMap_apply]
    congr 1
    funext i
    fin_cases i <;> rfl
  have T₁_apply (a b c : A) : T₁ ![a, b, c] =
      𝒜.m 3 ![𝒜.grading.koszulTwist 1 a, 𝒜.differential b, c] := by
    simp only [T₁, MultilinearMap.compLinearMap_apply]
    congr 1
    funext i
    fin_cases i <;> rfl
  have T₂_apply (a b c : A) : T₂ ![a, b, c] =
      𝒜.m 3 ![𝒜.grading.koszulTwist 1 a, 𝒜.grading.koszulTwist 1 b,
        𝒜.differential c] := by
    simp only [T₂, MultilinearMap.compLinearMap_apply]
    congr 1
    funext i
    fin_cases i <;> rfl
  have m_three_smul_first (r : R) (a b c : A) :
      𝒜.m 3 ![r • a, b, c] = r • 𝒜.m 3 ![a, b, c] := by
    convert (𝒜.m 3).map_update_smul ![a, b, c] 0 r a using 2 <;>
      congr 1 <;> funext i <;> fin_cases i <;> rfl
  have m_three_smul_second (r : R) (a b c : A) :
      𝒜.m 3 ![a, r • b, c] = r • 𝒜.m 3 ![a, b, c] := by
    convert (𝒜.m 3).map_update_smul ![a, b, c] 1 r b using 2 <;>
      congr 1 <;> funext i <;> fin_cases i <;> rfl
  -- On homogeneous inputs the two Koszul twists produce exactly the signs of the graded identity.
  let E : MultilinearMap R (fun _ : Fin 3 ↦ A) A := D + L - Q + T₀ + T₁ + T₂
  have hE : E = 0 := by
    apply 𝒜.grading.multilinearMap_ext
    intro d a ha
    have avec : a = ![a 0, a 1, a 2] := by
      funext i
      fin_cases i <;> rfl
    rw [avec]
    simp only [E, add_apply, sub_apply, D_apply, L_apply, Q_apply, T₀_apply, T₁_apply,
      T₂_apply, zero_apply, differential_apply,
      𝒜.grading.koszulTwist_apply_of_mem (ha 0),
      𝒜.grading.koszulTwist_apply_of_mem (ha 1),
      m_three_smul_first, m_three_smul_second, smul_smul, one_mul]
    rw [← negOnePowCast_eq_intCast (R := R) (d 0),
      ← negOnePowCast_eq_intCast (R := R) (d 1), ← negOnePowCast_add]
    exact 𝒜.stasheff_arity_three (a 0) (a 1) (a 2) (d 0) (d 1) (ha 0) (ha 1)
  have h := MultilinearMap.congr_fun hE ![x, y, z]
  simp only [E, add_apply, sub_apply, D_apply, L_apply, Q_apply, T₀_apply, T₁_apply,
    T₂_apply, zero_apply, differential_apply] at h
  rw [← sub_eq_zero, ← h]
  abel

/-- If the ternary operation vanishes, the arity-three identity says that `m₂` is associative. -/
theorem m_two_assoc_of_m_three_eq_zero (𝒜 : AInfinityAlgebra R A) (h₃ : 𝒜.m 3 = 0)
    (x y z : A) :
    𝒜.m 2 ![𝒜.m 2 ![x, y], z] = 𝒜.m 2 ![x, 𝒜.m 2 ![y, z]] := by
  -- Package the left- and right-associated products as trilinear maps. It then suffices to
  -- compare them on homogeneous first and second inputs via `stasheff_arity_three`.
  let L : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (((𝒜.m 2).domDomCongr (Fin.oneSlotEquiv 0 1).symm).oneSlot (𝒜.m 2)).domDomCongr
      (Fin.blockEquiv 0 2 1)
  let Q : MultilinearMap R (fun _ : Fin 3 ↦ A) A :=
    (((𝒜.m 2).domDomCongr (Fin.oneSlotEquiv 1 0).symm).oneSlot (𝒜.m 2)).domDomCongr
      (Fin.blockEquiv 1 2 0)
  have L_apply (a b c : A) : L ![a, b, c] = 𝒜.m 2 ![𝒜.m 2 ![a, b], c] := by
    simp only [L, MultilinearMap.domDomCongr_apply, MultilinearMap.oneSlot_apply]
    congr 1
    funext i
    obtain ⟨j, rfl⟩ := (Fin.oneSlotEquiv 0 1).surjective i
    rcases j with j | (j | j)
    · exact Fin.elim0 j
    · rcases j with ⟨⟩
      simp only [Equiv.symm_apply_apply, Sum.elim_inr, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 0 1 (.inr (.inl ())) = (0 : Fin 2) := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_middle_val 0 1
      rw [hout]
      -- Expose the inner tuple selected by `oneSlot` so that `blockEquiv` can be evaluated
      -- coordinatewise; simplification does not unfold vector notation to this form.
      change (𝒜.m 2) (fun j ↦ ![a, b, c] (Fin.blockEquiv 0 2 1 (.inr (.inl j)))) =
        𝒜.m 2 ![a, b]
      congr 1
      funext k
      have hi : Fin.blockEquiv 0 2 1 (.inr (.inl k)) =
          ⟨k, by omega⟩ := by
        apply Fin.ext
        simpa only [Nat.zero_add] using Fin.blockEquiv_middle_val 0 2 1 k
      rw [hi]
      fin_cases k <;> rfl
    · simp only [Equiv.symm_apply_apply, Sum.elim_inr]
      have hout : Fin.oneSlotEquiv 0 1 (.inr (.inr j)) = ⟨1 + j, by omega⟩ := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_suffix_val 0 1 j
      have hin : Fin.blockEquiv 0 2 1 (.inr (.inr j)) = ⟨2 + j, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_suffix_val 0 2 1 j
      rw [hout, hin]
      fin_cases j
      rfl
  have Q_apply (a b c : A) : Q ![a, b, c] = 𝒜.m 2 ![a, 𝒜.m 2 ![b, c]] := by
    simp only [Q, MultilinearMap.domDomCongr_apply, MultilinearMap.oneSlot_apply]
    congr 1
    funext i
    obtain ⟨j, rfl⟩ := (Fin.oneSlotEquiv 1 0).surjective i
    rcases j with j | (j | j)
    · simp only [Equiv.symm_apply_apply, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 1 0 (.inl j) = ⟨j, by omega⟩ := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_inl_val 1 0 j
      have hin : Fin.blockEquiv 1 2 0 (.inl j) = ⟨j, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_inl_val 1 2 0 j
      rw [hout, hin]
      fin_cases j
      rfl
    · rcases j with ⟨⟩
      simp only [Equiv.symm_apply_apply, Sum.elim_inr, Sum.elim_inl]
      have hout : Fin.oneSlotEquiv 1 0 (.inr (.inl ())) = (1 : Fin 2) := by
        apply Fin.ext
        exact Fin.oneSlotEquiv_middle_val 1 0
      rw [hout]
      -- As above, expose the inner tuple; the coordinate proof below identifies this middle
      -- block with the final two entries of the original tuple.
      change (𝒜.m 2) (fun j ↦ ![a, b, c] (Fin.blockEquiv 1 2 0 (.inr (.inl j)))) =
        𝒜.m 2 ![b, c]
      congr 1
      funext k
      have hi : Fin.blockEquiv 1 2 0 (.inr (.inl k)) = ⟨1 + k, by omega⟩ := by
        apply Fin.ext
        exact Fin.blockEquiv_middle_val 1 2 0 k
      rw [hi]
      fin_cases k <;> rfl
    · exact Fin.elim0 j
  have hcurry : L.curryRight = Q.curryRight := by
    apply 𝒜.grading.multilinearMap_ext
    intro d a ha
    ext c
    have h := 𝒜.stasheff_arity_three (a 0) (a 1) c (d 0) (d 1) (ha 0) (ha 1)
    rw [h₃] at h
    have hz : 𝒜.m 1 ![(0 : A)] = 0 := (𝒜.m 1).map_coord_zero 0 rfl
    simp only [MultilinearMap.curryRight_apply]
    have hac : Fin.snoc a c = ![a 0, a 1, c] := by
      funext i
      fin_cases i <;> rfl
    rw [hac]
    rw [L_apply, Q_apply]
    apply sub_eq_zero.mp
    simpa only [_root_.zero_apply, hz, smul_zero, add_zero, zero_add] using h
  have hLQ : L = Q := by
    rw [← MultilinearMap.uncurry_curryRight L, ← MultilinearMap.uncurry_curryRight Q,
      hcurry]
  rw [← L_apply, ← Q_apply]
  exact MultilinearMap.congr_fun hLQ ![x, y, z]

end AInfinityAlgebra

end TauCeti
