/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Laurent.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Units

/-!
# Units on a Laurent piece

In Wedhorn's reduction of a standard rational cover to Laurent covers, one first chooses a unit
`ϖ` smaller than some member of the covering family at every point. On a Laurent piece generated
by the ratios `ϖ⁻¹ t`, each generator on the `≥ 1` side is invertible in the coordinate ring of
that piece. The pointwise nonvanishing inequality is
`not_vle_zero_of_mem_laurentPiece_inv_mul`; the result here promotes it to invertibility in
any rational presentation of the piece.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Lemma 8.34(ii).
-/

public section

namespace TauCeti.ValuationSpectrum

open TauCeti.Huber TauCeti.Huber.PairOfDefinition UniformSpace

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- A generator with sign `≥ 1` is a unit on a Laurent piece generated by `ϖ⁻¹ t`.
The rational presentation may be any one whose rational subset lies in that piece; in
particular this applies to any presentation of the whole piece. -/
theorem isUnit_toCompletionLoc_of_laurentPiece_inv_mul
    (P : PairOfDefinition A) (Aplus : Subring A) (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    {T : Finset A} (ϖ : Aˣ) {J : Set T} {t : T} (ht : t ∈ J)
    (U : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S]
    [IsLocalization.Away s S] (hden : HasDenominatorPower P U s S)
    (hU : rationalSubset Aplus U s ⊆
      laurentPiece Aplus (fun t : T ↦ (ϖ⁻¹ : Aˣ) * (t : A)) J) :
    letI := locUniformSpace P U s S hden
    letI := isUniformAddGroup_locUniformSpace P U s S hden
    letI := isTopologicalRing_locUniformSpace P U s S hden
    IsUnit (toCompletionLoc P U s S hden t) := by
  let _ := locUniformSpace P U s S hden
  have _ := isUniformAddGroup_locUniformSpace P U s S hden
  have _ := isTopologicalRing_locUniformSpace P U s S hden
  apply (isUnit_toCompletionLoc_iff_forall_notMem_supp P Aplus hP hAplus U s S hden t).2
  intro v hv hsupp
  exact not_vle_zero_of_mem_laurentPiece_inv_mul ϖ ht (hU hv)
    ((mem_supp_iff v t).mp hsupp)

end TauCeti.ValuationSpectrum

end
