/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points

/-!
# When the Kostant weight torus is scheme-theoretically redundant

The Kostant toral closure is defined by adjoining a represented weight torus to a family of
represented root subgroups. This file proves that the torus may be removed from the
scheme-theoretic generating family whenever its universal point is already contained in the
elementary subgroup generated by the root subgroups.

Under this universal-point hypothesis, the root-generated and toral defining ideals and affine
group schemes are equal, and the canonical comparison between the carriers is an isomorphism.
These results are integral and require no reducedness or finite-type hypothesis.

## Main results

* `kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary`:
  generation of the represented universal torus point implies equality of the two defining Hopf
  ideals.
* `kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary`:
  under the same hypothesis, the root-generated and toral carriers are equal.
* `kostantGeneratedToToral_eq_eqToHom_of_universal_torus_mem_elementary`: the canonical comparison
  is the transport along that equality, and hence is an isomorphism.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* W. C. Waterhouse, *Introduction to Affine Group Schemes*, Section 1.4.
-/

public section

open CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Fintype κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- If the represented universal weight-torus point belongs to the elementary subgroup, then the
root-generated defining ideal is killed by the weight-torus coordinate map. -/
theorem kostantGeneratedDefiningIdeal_toIdeal_le_torus_ker_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup κ)) A := toConv (AlgHom.id ℤ T)
      kostantTorusPoints M b wt A (SplitTorus.pointsMulEquiv q) ∈
        kostantElementarySubgroup e h ρ M hM hnil A) :
    (kostantGeneratedDefiningIdeal e h ρ M hM hnil b).toIdeal ≤
      RingHom.ker (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom := by
  let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
  let A := CommAlgCat.of ℤ T
  let q : HopfAlgebra.points
      (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)) A :=
    toConv (AlgHom.id ℤ T)
  let s : κ → Aˣ := SplitTorus.pointsMulEquiv q
  have hs : kostantTorusPoints M b wt A s ∈
      kostantElementarySubgroup e h ρ M hM hnil A := huniv
  have hmatrix : kostantTorusMatrix M b wt s ∈
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b T := by
    apply map_kostantElementarySubgroup_le_generatedPoints e h ρ M hM hnil b T
    rw [← basisMatrix_kostantTorusPoints M b wt s]
    exact ⟨_, hs, rfl⟩
  have hq_matrix : GeneralLinear.pointsMulEquiv n
      ((CommHopfAlgCat.mapPointsFunctor
        (GeneralLinear.weightTorusCoordinateMap wt)).app A q) =
      kostantTorusMatrix M b wt s := by
    rw [GeneralLinear.pointsMulEquiv_mapPointsFunctor_weightTorusCoordinateMap,
      kostantTorusMatrix_apply]
  have hmatrix' : GeneralLinear.pointToGeneralLinear n
      (toConv (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom) ∈
      kostantGeneratedPointsSubgroup e h ρ M hM hnil b T := by
    have hp : (CommHopfAlgCat.mapPointsFunctor
        (GeneralLinear.weightTorusCoordinateMap wt)).app A q =
        toConv (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom := by
      rw [CommHopfAlgCat.mapPointsFunctor_app_apply,
        WithConv.ofConv_toConv, AlgHom.id_comp]
    rw [← GeneralLinear.pointsMulEquiv_apply, ← hp, hq_matrix]
    exact hmatrix
  rw [kostantGeneratedPointsSubgroup_def] at hmatrix'
  exact (GeneralLinear.pointToGeneralLinear_mem_hopfIdealPointsSubgroup_iff_toIdeal_le_ker
    n (kostantGeneratedDefiningIdeal e h ρ M hM hnil b) T
    (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom).mp hmatrix'

/-- **A root-generated universal weight-torus point makes the torus scheme-theoretically
redundant.** If the represented torus over its own coordinate ring belongs to the elementary
subgroup, then adjoining the torus does not change the common-kernel defining Hopf ideal. -/
theorem kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup κ)) A := toConv (AlgHom.id ℤ T)
      kostantTorusPoints M b wt A (SplitTorus.pointsMulEquiv q) ∈
        kostantElementarySubgroup e h ρ M hM hnil A) :
    kostantToralDefiningIdeal e h ρ M hM hnil b wt =
      kostantGeneratedDefiningIdeal e h ρ M hM hnil b := by
  apply le_antisymm
  · exact kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
      e h ρ M hM hnil b wt
  · rw [le_kostantToralDefiningIdeal_iff]
    exact ⟨kostantGeneratedDefiningIdeal_toIdeal_le_ker e h ρ M hM hnil b,
      kostantGeneratedDefiningIdeal_toIdeal_le_torus_ker_of_universal_torus_mem_elementary
        e h ρ M hM hnil b wt huniv⟩

/-- When the universal weight-torus point is generated by the root subgroups, the root-generated
Kostant carrier and the toral closure are the same affine group scheme. -/
theorem kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup κ)) A := toConv (AlgHom.id ℤ T)
      kostantTorusPoints M b wt A (SplitTorus.pointsMulEquiv q) ∈
        kostantElementarySubgroup e h ρ M hM hnil A) :
    kostantToralGroupScheme e h ρ M hM hnil b wt =
      kostantGeneratedGroupScheme e h ρ M hM hnil b := by
  rw [kostantToralGroupScheme,
    kostantGeneratedGroupScheme,
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      e h ρ M hM hnil b wt huniv]

/-- Under generation of the universal torus point, the canonical inclusion of the root-generated
carrier into the toral closure is the transport along their equality. -/
theorem kostantGeneratedToToral_eq_eqToHom_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup κ)) A := toConv (AlgHom.id ℤ T)
      kostantTorusPoints M b wt A (SplitTorus.pointsMulEquiv q) ∈
        kostantElementarySubgroup e h ρ M hM hnil A) :
    kostantGeneratedToToral e h ρ M hM hnil b wt =
      eqToHom
        (kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
          e h ρ M hM hnil b wt huniv).symm := by
  have hideal :=
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      e h ρ M hM hnil b wt huniv
  have hgroup :
      (kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
        e h ρ M hM hnil b wt huniv).symm =
        congrArg (CommHopfAlgCat.quotientSpec
          (GeneralLinear.coordinateHopfAlgebra ℤ n)) hideal.symm :=
    Subsingleton.elim _ _
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [kostantGeneratedToToral_comp_ι]
  rw [kostantGeneratedGroupSchemeι_def, kostantToralGroupSchemeι_def, hgroup]
  rw [← Category.assoc, CommHopfAlgCat.eqToHom_comp_quotientSpecι]
  exact hideal.symm

/-- Generation of the universal weight-torus point makes the canonical comparison from the
root-generated carrier to the toral closure an isomorphism. -/
theorem isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup κ)) A := toConv (AlgHom.id ℤ T)
      kostantTorusPoints M b wt A (SplitTorus.pointsMulEquiv q) ∈
        kostantElementarySubgroup e h ρ M hM hnil A) :
    IsIso (kostantGeneratedToToral e h ρ M hM hnil b wt) := by
  rw [kostantGeneratedToToral_eq_eqToHom_of_universal_torus_mem_elementary
    e h ρ M hM hnil b wt huniv]
  infer_instance

end TauCeti.UniversalEnvelopingAlgebra
