/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.NumberedSymmetry
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Rigidity
import TauCeti.CategoryTheory.Aut.Basic

/-!
# Numbered symmetries of the Kostant toral-closure group scheme

The closed subgroup scheme of `GLₙ` generated by the represented Kostant root subgroups together
with the weight torus of an integral weight family is the carrier of the Chevalley--Demazure
construction. This file makes it inherit the automorphism that a symmetry of the numbered Kostant
data induces on `GLₙ`.

Two hypotheses are needed beyond those of the root-generated case, and they are exactly what the
torus contributes. The rational automorphism `θ` must act monomially on the chosen lattice basis,
by a permutation `π` of `Fin n` and integral scaling coefficients; and the weights must be
equivariant for `π` and a permutation `τ` of the torus index,
`wt (π i) (τ k) = wt i k`. The scaling coefficients cancel from diagonal conjugation, so the
symmetry normalizes the diagonal torus of `GLₙ`, and equivariance identifies the relabelled weight
family with the original one. On the represented generators the resulting automorphism acts by

```text
γ ∘ xᵢ = x_{σ i},        γ ∘ (weight torus) = (weight torus) ∘ relabel(τ⁻¹),
```

and it has order dividing any `m` for which `σ` iterates and `τ` powers to the identity.

The invariance of the defining Hopf ideal that makes all of this work also says that conjugation by
the numbered-symmetry matrix preserves the algebra-valued points of the toral closure. That form of
the statement is proved here too, since it is the one a consumer working with a point group rather
than with the group scheme needs, and it rests on the same ideal computation. The two are compared:
on an algebra-valued point of the carrier, composing with the automorphism of the group scheme and
including into `GLₙ` is that same matrix conjugation.

Both hypotheses hold for the coordinate permutation that a Dynkin-diagram symmetry induces on
Geck's lattice: it permutes the coordinate basis by the induced permutation of the Cartan
coordinates and of the roots, and it permutes the Geck weights contragrediently. Allowing monomial
basis actions also covers pinned lifts, such as the graph symmetry used for `²E₆`, that require
signs.

Nothing here assumes that `σ` or `τ` comes from a diagram symmetry, that the weights are those of
an admissible lattice, or that the carrier is reductive.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralNumberedSymmetryIso`: the automorphism of the
  toral closure.

## Main results

* `kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom` and its inverse and iterated
  counterparts: the pinning equation `γ ∘ xᵢ = x_{σ i}`.
* `kostantWeightTorusToToral_comp_numberedSymmetryIso_hom` and its inverse and iterated
  counterparts: the symmetry normalizes the represented weight torus and acts on it by relabelling.
* `kostantGeneratedToToral_comp_numberedSymmetryIso_hom`: the generated and toral symmetries agree
  along the canonical closed immersion.
* `kostantToralNumberedSymmetryIso_pow_eq_one`: the order relation.
* `conj_kostantNumberedSymmetryMatrix_mem_kostantToralPointsSubgroup_iff` and
  `map_kostantToralPointsSubgroup_conj_numberedSymmetryMatrix`: conjugation by the numbered-symmetry
  matrix preserves the algebra-valued points of the toral closure.
* `schemePointsMulEquiv_kostantToralNumberedSymmetryIso`: on algebra-valued points the automorphism
  of the group scheme is that same conjugation.

All of these live in the `TauCeti.UniversalEnvelopingAlgebra` namespace.

## References

This is the graph-automorphism construction of R. W. Carter, *Finite Groups of Lie Type: Conjugacy
Classes and Complex Characters*, §1.15, and J. E. Humphreys, *Linear Algebraic Groups*, §27, carried
out on the carrier assembled from a torus and root subgroups in R. W. Carter, *Simple Groups of Lie
Type*, §§4.4 and 7.1.

It advances the pinnings and pinned-isomorphism targets of Layer 9 of
`TauCetiRoadmap/ReductiveGroups/README.md`; the resulting automorphisms are required by milestone L1
of `TauCetiRoadmap/CFSGStatement/README.md`.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct WithConv

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)
variable (σ : I → I) (θ : V ≃ₗ[ℚ] V) (hθM : ∀ v, θ v ∈ M ↔ v ∈ M)
variable (hθe : ∀ i, ∀ v : V,
  θ (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) v) =
    ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e (σ i))) (θ v))
variable (hσ : Function.Surjective σ)
variable (basisPerm : Equiv.Perm (Fin n))
variable (basisScale : Fin n → ℤ)
variable (hbasis : ∀ i, θ ((b i : M) : V) =
  (((basisScale i) • b (basisPerm i) : M) : V))
variable (torusPerm : Equiv.Perm κ)
variable (hwt : ∀ i k, wt (basisPerm i) (torusPerm k) = wt i k)

omit [Finite κ] in
include hwt in
/-- The weight family relabelled by the basis permutation is the family with every weight
composed with the torus permutation. -/
private theorem weight_comp_basisPerm_symm :
    (fun i => wt (basisPerm⁻¹ i)) = fun i => wt i ∘ torusPerm := by
  funext i k
  have := hwt (basisPerm⁻¹ i) k
  rwa [Equiv.Perm.inv_def, Equiv.apply_symm_apply, eq_comm] at this

include hbasis hwt in
/-- The ambient coordinate automorphism carries the represented weight torus to itself, acting on
it by the relabelling attached to the torus permutation. -/
private theorem kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus :
    (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom ≫
        GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt =
      GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹ := by
  rw [kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorusCoordinateMap
    M b θ hθM wt basisPerm basisScale hbasis,
    weight_comp_basisPerm_symm wt basisPerm torusPerm hwt,
    GeneralLinear.weightTorusCoordinateMap_reindex]

include hθe hσ hbasis hwt in
/-- The forward ambient symmetry pulls the toral defining ideal into itself. -/
private theorem kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso_hom_le :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).comapOfSurjective
        (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom
        (ConcreteCategory.bijective_of_isIso
          (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom).2 ≤
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  refine kostantToralDefiningIdeal_comapOfSurjective_le_of_comp_eq e h ρ M hM hnil b wt _ _
    (Function.surjInv hσ) (SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹)
    (SplitTorus.relabelCoordinateMap_injective ℤ torusPerm⁻¹) (fun i => ?_) ?_
  · rw [kostantNumberedSymmetryCoordinateIso_hom_comp_rootSubgroupCoordinateMap
      e h ρ M hM hnil b σ θ hθM hθe (Function.surjInv hσ i), Function.surjInv_eq hσ]
  · exact kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus
      M b wt θ hθM basisPerm basisScale hbasis torusPerm hwt

include hθe hbasis hwt in
/-- The inverse ambient symmetry pulls the toral defining ideal into itself. -/
private theorem kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso_inv_le :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).comapOfSurjective
        (kostantNumberedSymmetryCoordinateIso M b θ hθM).inv.hom
        (ConcreteCategory.bijective_of_isIso
          (kostantNumberedSymmetryCoordinateIso M b θ hθM).inv).2 ≤
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  let c := kostantNumberedSymmetryCoordinateIso M b θ hθM
  refine kostantToralDefiningIdeal_comapOfSurjective_le_of_comp_eq e h ρ M hM hnil b wt c.inv _ σ
    (SplitTorus.relabelCoordinateMap ℤ torusPerm)
    (SplitTorus.relabelCoordinateMap_injective ℤ torusPerm) (fun i => ?_) ?_
  · rw [← kostantNumberedSymmetryCoordinateIso_hom_comp_rootSubgroupCoordinateMap
      e h ρ M hM hnil b σ θ hθM hθe i, Iso.inv_hom_id_assoc]
  · rw [← cancel_epi c.hom]
    simp only [← Category.assoc, c.hom_inv_id, Category.id_comp]
    rw [kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus
        M b wt θ hθM basisPerm basisScale hbasis torusPerm hwt,
      Category.assoc, SplitTorus.relabelCoordinateMap_comp, mul_inv_cancel,
      SplitTorus.relabelCoordinateMap_one, Category.comp_id]

include hθe hσ hbasis hwt in
/-- **The numbered-symmetry coordinate automorphism preserves the toral defining ideal.** The root
subgroups are permuted among themselves and the weight torus is carried to itself, so the largest
Hopf ideal killed by all of them is invariant. -/
private theorem kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).comapOfSurjective
        (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom
        (ConcreteCategory.bijective_of_isIso
          (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom).2 =
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  let c := kostantNumberedSymmetryCoordinateIso M b θ hθM
  let J := kostantToralDefiningIdeal e h ρ M hM hnil b wt
  have hhom : J.comapOfSurjective c.hom.hom (ConcreteCategory.bijective_of_isIso c.hom).2 ≤ J :=
    kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso_hom_le
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt
  have hinv : J.comapOfSurjective c.inv.hom (ConcreteCategory.bijective_of_isIso c.inv).2 ≤ J :=
    kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso_inv_le
      e h ρ M hM hnil b wt σ θ hθM hθe basisPerm basisScale hbasis torusPerm hwt
  exact HopfIdeal.comapOfSurjective_eq_of_hom_le_of_inv_le c J hhom hinv

include hθe hσ hbasis hwt in
/-- The coordinate automorphism induced on the toral-closure quotient. -/
private noncomputable def kostantToralCoordinateNumberedSymmetryIso :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≅
      CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) :=
  CommHopfAlgCat.quotientIsoOfComapEq
    (kostantNumberedSymmetryCoordinateIso M b θ hθM)
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt)

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism is induced by the ambient coordinate automorphism. -/
private theorem mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
        (kostantToralCoordinateNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom =
      (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom ≫
        CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) := by
  exact CommHopfAlgCat.mkQuotient_comp_quotientIsoOfComapEq_hom
    (kostantNumberedSymmetryCoordinateIso M b θ hθM)
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt)

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism permutes the factored root-subgroup maps. -/
private theorem kostantToralCoordinateNumberedSymmetryIso_hom_comp_rootMap (i : I) :
    (kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom ≫
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i =
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i) := by
  have hr : (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤ RingHom.ker
      (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b).hom.toAlgHom.toRingHom :=
    kostantToralDefiningIdeal_toIdeal_le_root_ker e h ρ M hM hnil b wt (σ i)
  have hleft := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b) hr
    ((kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom ≫
      kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i) (by
        rw [← Category.assoc,
          mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom,
          Category.assoc, mkQuotient_comp_kostantRootSubgroupToralCoordinateMap,
          kostantNumberedSymmetryCoordinateIso_hom_comp_rootSubgroupCoordinateMap]
        exact hθe)
  have hright := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (kostantRootSubgroupCoordinateMap e h ρ M hM (σ i) (hnil (σ i)) b) hr
    (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i))
    (mkQuotient_comp_kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt (σ i))
  exact hleft.trans hright.symm

include hθe hσ hbasis hwt in
/-- The quotient coordinate automorphism carries the factored weight-torus map to itself,
composed with the relabelling attached to the torus permutation. -/
private theorem kostantToralCoordinateNumberedSymmetryIso_hom_comp_torusMap :
    (kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom ≫
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt =
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹ := by
  have hr : (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤ RingHom.ker
      (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹).hom.toAlgHom.toRingHom := by
    intro x hx
    have h0 : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt).hom x = 0 := by
      simpa using RingHom.mem_ker.mp
        (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt hx)
    have h1 : (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
        SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹).hom x = 0 := by
      rw [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply, h0, map_zero]
    simpa [RingHom.mem_ker] using h1
  have hleft := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) hr
    ((kostantToralCoordinateNumberedSymmetryIso
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom ≫
      kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt) (by
        rw [← Category.assoc,
          mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom,
          Category.assoc, mkQuotient_comp_kostantWeightTorusToralCoordinateMap]
        exact kostantNumberedSymmetryCoordinateIso_hom_comp_weightTorus
          M b wt θ hθM basisPerm basisScale hbasis torusPerm hwt)
  have hright := CommHopfAlgCat.liftQuotient_unique
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap (R := ℤ) wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) hr
    (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt ≫
      SplitTorus.relabelCoordinateMap ℤ torusPerm⁻¹) (by
        rw [← Category.assoc, mkQuotient_comp_kostantWeightTorusToralCoordinateMap])
  exact hleft.trans hright.symm


include hθe hσ hbasis hwt in
/-- **The automorphism of the Kostant toral-closure group scheme induced by a numbered symmetry
which acts monomially on the chosen lattice basis compatibly with the weights.** -/
noncomputable def kostantToralNumberedSymmetryIso :
    Aut (kostantToralGroupScheme e h ρ M hM hnil b wt) :=
  (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).mapIso
    (kostantToralCoordinateNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).op

include hθe hσ hbasis hwt in
/-- The toral symmetry carries the `i`th root subgroup to the one numbered `σ i`, without changing
its additive parameter. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt (σ i) := by
  rw [kostantRootSubgroupToToral_def, kostantToralNumberedSymmetryIso,
    Functor.mapIso_hom, Iso.op_hom, Category.assoc, ← Functor.map_comp, ← op_comp,
    kostantToralCoordinateNumberedSymmetryIso_hom_comp_rootMap]
  exact (kostantRootSubgroupToToral_def e h ρ M hM hnil b wt (σ i)).symm

include hθe hσ hbasis hwt in
/-- The inverse toral symmetry carries the `σ i`th root subgroup back to the `i`th one. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_inv (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt (σ i) ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).inv =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i := by
  rw [← kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt i,
    Category.assoc, (kostantToralNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom_inv_id,
    Category.comp_id]

include hθe hσ hbasis hwt in
/-- **The toral symmetry normalizes the represented weight torus**, acting on it by the relabelling
attached to the torus permutation. -/
@[simp]
theorem kostantWeightTorusToToral_comp_numberedSymmetryIso_hom :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom =
      SplitTorus.relabel ℤ torusPerm⁻¹ ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  rw [kostantWeightTorusToToral_def, kostantToralNumberedSymmetryIso,
    Functor.mapIso_hom, Iso.op_hom, Category.assoc, ← Functor.map_comp, ← op_comp,
    kostantToralCoordinateNumberedSymmetryIso_hom_comp_torusMap, op_comp, Functor.map_comp,
    SplitTorus.relabel_def]
  simp only [Category.assoc, eqToHom_trans_assoc, eqToHom_refl, Category.id_comp]

include hθe hσ hbasis hwt in
/-- The inverse toral symmetry acts on the represented weight torus by the inverse relabelling. -/
@[simp]
theorem kostantWeightTorusToToral_comp_numberedSymmetryIso_inv :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).inv =
      SplitTorus.relabel ℤ torusPerm ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  let γ := kostantToralNumberedSymmetryIso
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt
  have hhom : kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ γ.hom =
      SplitTorus.relabel ℤ torusPerm⁻¹ ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt :=
    kostantWeightTorusToToral_comp_numberedSymmetryIso_hom
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt
  -- The local abbreviation `γ` hides the inverse field of the bundled automorphism; expose it
  -- before applying the categorical inverse identities below.
  change kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ γ.inv = _
  calc
    _ = SplitTorus.relabel ℤ torusPerm ≫
        ((SplitTorus.relabel ℤ torusPerm⁻¹ ≫
          kostantWeightTorusToToral e h ρ M hM hnil b wt) ≫ γ.inv) := by
        simp only [← Category.assoc, SplitTorus.relabel_comp, mul_inv_cancel,
          SplitTorus.relabel_one, Category.id_comp]
    _ = SplitTorus.relabel ℤ torusPerm ≫
        ((kostantWeightTorusToToral e h ρ M hM hnil b wt ≫ γ.hom) ≫ γ.inv) := by
      rw [hhom]
    _ = SplitTorus.relabel ℤ torusPerm ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
      rw [Category.assoc, γ.hom_inv_id, Category.comp_id]

include hθe hσ hbasis hwt in
/-- The root-generated and toral numbered symmetries agree along the canonical closed immersion
from the generated carrier into the toral closure. -/
@[simp]
theorem kostantGeneratedToToral_comp_numberedSymmetryIso_hom :
    kostantGeneratedToToral e h ρ M hM hnil b wt ≫
        (kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt).hom =
      (kostantGeneratedNumberedSymmetryIso
        e h ρ M hM hnil b σ θ hθM hθe hσ).hom ≫
        kostantGeneratedToToral e h ρ M hM hnil b wt := by
  apply kostantGeneratedGroupScheme_hom_ext e h ρ M hM hnil b
  intro i
  simp only [← Category.assoc,
    kostantRootSubgroupToGenerated_comp_kostantGeneratedToToral,
    kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom,
    kostantRootSubgroupToGenerated_comp_numberedSymmetryIso_hom]


include hθe hσ hbasis hwt in
/-- Iterating the toral symmetry carries the `i`th root subgroup to the root subgroup numbered by
the corresponding iterate of `σ`. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_numberedSymmetryIso_pow_hom (m : ℕ) (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt) ^ m).hom =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt ((σ^[m]) i) := by
  exact TauCeti.CategoryTheory.comp_aut_pow_hom_of_comp
    (kostantToralNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt)
    (kostantRootSubgroupToToral e h ρ M hM hnil b wt) σ
    (kostantRootSubgroupToToral_comp_numberedSymmetryIso_hom
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt) m i

include hθe hσ hbasis hwt in
/-- Iterating the toral symmetry acts on the weight torus by the corresponding power of the
relabelling. -/
@[simp]
theorem kostantWeightTorusToToral_comp_numberedSymmetryIso_pow_hom (m : ℕ) :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        ((kostantToralNumberedSymmetryIso
          e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt) ^ m).hom =
      SplitTorus.relabel ℤ (torusPerm⁻¹ ^ m) ≫
        kostantWeightTorusToToral e h ρ M hM hnil b wt := by
  let γ := kostantToralNumberedSymmetryIso
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt
  let F : ℕ → (SplitTorus.groupScheme ℤ κ ⟶
      kostantToralGroupScheme e h ρ M hM hnil b wt) := fun r =>
    SplitTorus.relabel ℤ (torusPerm⁻¹ ^ r) ≫
      kostantWeightTorusToToral e h ρ M hM hnil b wt
  have hstep : ∀ r, F r ≫ γ.hom = F (Nat.succ r) := by
    intro r
    dsimp [F, γ]
    rw [Category.assoc, kostantWeightTorusToToral_comp_numberedSymmetryIso_hom,
      ← Category.assoc, SplitTorus.relabel_comp, pow_succ]
  have hiter := TauCeti.CategoryTheory.comp_aut_pow_hom_of_comp
    γ F Nat.succ hstep m 0
  rw [Nat.succ_iterate, zero_add] at hiter
  simpa [F, γ] using hiter

include hθe hσ hbasis hwt in
/-- **If the numbering permutation and the torus permutation both have order dividing `m`, so does
the induced automorphism of the toral closure.** An involution or a triality of the numbered data
therefore produces a symmetry with `γ ^ 2 = 1` or `γ ^ 3 = 1`. -/
@[simp]
theorem kostantToralNumberedSymmetryIso_pow_eq_one (m : ℕ)
    (hσm : σ^[m] = id) (hτm : torusPerm ^ m = 1) :
    (kostantToralNumberedSymmetryIso
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt) ^ m = 1 := by
  apply Iso.ext
  refine kostantToralGroupScheme_hom_ext e h ρ M hM hnil b wt _ _ (fun i => ?_) ?_
  · rw [kostantRootSubgroupToToral_comp_numberedSymmetryIso_pow_hom, hσm, id_eq]
    -- see above for why the `Aut` identity is exposed by `change`
    change _ = _ ≫ (Iso.refl _).hom
    rw [Iso.refl_hom, Category.comp_id]
  · rw [kostantWeightTorusToToral_comp_numberedSymmetryIso_pow_hom, inv_pow, hτm,
      inv_one, SplitTorus.relabel_one, Category.id_comp]
    -- see above for why the `Aut` identity is exposed by `change`
    change _ = _ ≫ (Iso.refl _).hom
    rw [Iso.refl_hom, Category.comp_id]

/-! ## The symmetry on algebra-valued points -/

include hθe hσ hbasis hwt in
/-- The coordinate automorphism attached to a numbered symmetry preserves the toral defining Hopf
ideal in both directions. -/
private theorem mem_kostantToralDefiningIdeal_numberedSymmetryCoordinateIso_iff
    (x : GeneralLinear.coordinateHopfAlgebra ℤ n) :
    (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom x ∈
        kostantToralDefiningIdeal e h ρ M hM hnil b wt ↔
      x ∈ kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  conv_rhs => rw [← kostantToralDefiningIdeal_comapOfSurjective_numberedSymmetryCoordinateIso
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt]
  rw [HopfIdeal.mem_comapOfSurjective]

include hθe hσ hbasis hwt in
/-- **Conjugating by the matrix of a numbered symmetry preserves the algebra-valued points of the
toral closure**, in both directions. The symmetry permutes the represented root subgroups and
carries the represented weight torus to itself, so it preserves the Hopf ideal cut out by them and
hence the matrices which kill that ideal. -/
theorem conj_kostantNumberedSymmetryMatrix_mem_kostantToralPointsSubgroup_iff
    (A : Type v) [CommRing A] (g : Matrix.GeneralLinearGroup (Fin n) A) :
    kostantNumberedSymmetryMatrix M b θ hθM A * g *
          (kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹ ∈
        kostantToralPointsSubgroup e h ρ M hM hnil b wt A ↔
      g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  have hsurj : Function.Surjective
      (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom :=
    (ConcreteCategory.bijective_of_isIso
      (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom).2
  have hpoint : (GeneralLinear.pointsMulEquiv (R := ℤ) n).symm
      (kostantNumberedSymmetryMatrix M b θ hθM A * g *
        (kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹) =
      toConv (((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv.comp
        ((kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom :
          GeneralLinear.coordinateHopfAlgebra ℤ n →ₐ[ℤ]
            GeneralLinear.coordinateHopfAlgebra ℤ n)) := by
    refine (GeneralLinear.pointsMulEquiv (R := ℤ) n).symm_apply_eq.mpr ?_
    rw [pointsMulEquiv_toConv_comp_kostantNumberedSymmetryCoordinateIso M b θ hθM,
      MulEquiv.apply_symm_apply]
  -- The conjugated point is the original one precomposed with the coordinate automorphism.
  have hval : ∀ x, ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm
        (kostantNumberedSymmetryMatrix M b θ hθM A * g *
          (kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹)).ofConv x =
      ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv
        ((kostantNumberedSymmetryCoordinateIso M b θ hθM).hom.hom x) := fun x => by
    -- The algebra-map coercion of the Hopf-algebra morphism is its own application.
    rw [hpoint, ofConv_toConv, AlgHom.comp_apply]
    rfl
  rw [mem_kostantToralPointsSubgroup_iff, mem_kostantToralPointsSubgroup_iff]
  constructor
  · intro hall x hx
    obtain ⟨y, rfl⟩ := hsurj x
    exact (hval y).symm.trans (hall y
      ((mem_kostantToralDefiningIdeal_numberedSymmetryCoordinateIso_iff
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt y).1 hx))
  · intro hall x hx
    exact (hval x).trans (hall _
      ((mem_kostantToralDefiningIdeal_numberedSymmetryCoordinateIso_iff
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt x).2 hx))

include hθe hσ hbasis hwt in
/-- **The matrix of a numbered symmetry normalizes the algebra-valued points of the toral
closure.** This is the form in which conjugation by that matrix restricts to an automorphism of the
point group. -/
theorem map_kostantToralPointsSubgroup_conj_numberedSymmetryMatrix (A : Type v) [CommRing A] :
    (kostantToralPointsSubgroup e h ρ M hM hnil b wt A).map
        (MulAut.conj (kostantNumberedSymmetryMatrix M b θ hθM A)).toMonoidHom =
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  ext g
  rw [Subgroup.mem_map_equiv, MulAut.conj_symm_apply]
  have hg : kostantNumberedSymmetryMatrix M b θ hθM A *
        ((kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹ * g *
          kostantNumberedSymmetryMatrix M b θ hθM A) *
      (kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹ = g := by
    group
  refine Iff.symm (Iff.trans ?_
    (conj_kostantNumberedSymmetryMatrix_mem_kostantToralPointsSubgroup_iff
      e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt A
      ((kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹ * g *
        kostantNumberedSymmetryMatrix M b θ hθM A)))
  rw [hg]

/-! ## The symmetry on scheme-valued points -/

open scoped CategoryTheory.MonObj

include hθe hσ hbasis hwt in
/-- Composing a scheme-valued point with the toral symmetry precomposes its algebra point with the
quotient coordinate automorphism. -/
private theorem kostantToralSchemePointMulEquiv_comp_numberedSymmetryIso (A : Type) [CommRing A]
    (q : WithConv (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →ₐ[ℤ] A)) :
    kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A q ≫
        (kostantToralNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
          basisScale hbasis torusPerm hwt).hom.hom.hom =
      kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A
        ((CommHopfAlgCat.mapPointsFunctor
          (kostantToralCoordinateNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
            basisScale hbasis torusPerm hwt).hom).app (CommAlgCat.of ℤ A) q) := by
  rw [kostantToralNumberedSymmetryIso, Functor.mapIso_hom, Iso.op_hom]
  exact CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain (R := ℤ) A
    (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)
    (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)
    (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A)
    (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A)
    (kostantToralSchemePointMulEquiv_apply_left e h ρ M hM hnil b wt A)
    (kostantToralSchemePointMulEquiv_apply_left e h ρ M hM hnil b wt A)
    (kostantToralCoordinateNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
      basisScale hbasis torusPerm hwt).hom q

/-- Including a scheme-valued point of the toral closure into `GLₙ` precomposes its algebra point
with the quotient coordinate map. -/
private theorem kostantToralSchemePointMulEquiv_comp_toralGroupSchemeι (A : Type) [CommRing A]
    (q : WithConv (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →ₐ[ℤ] A)) :
    kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A q ≫
        (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom =
      GeneralLinear.groupSchemePointMulEquiv n A
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantToralDefiningIdeal e h ρ M hM hnil b wt))).app (CommAlgCat.of ℤ A) q) := by
  rw [kostantToralGroupSchemeι_def, CommHopfAlgCat.quotientSpecι_def]
  exact CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain (R := ℤ) A
    (GeneralLinear.groupScheme_def ℤ n)
    (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)
    (GeneralLinear.groupSchemePointMulEquiv n A)
    (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A)
    (GeneralLinear.groupSchemePointMulEquiv_apply_left n A)
    (kostantToralSchemePointMulEquiv_apply_left e h ρ M hM hnil b wt A)
    (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt)) q

/-- The matrix of an included scheme-valued point of the toral closure is the matrix of its algebra
point, read in the ambient coordinate Hopf algebra. -/
private theorem schemePointsMulEquiv_kostantToralSchemePointMulEquiv_comp_toralGroupSchemeι
    (A : Type) [CommRing A]
    (q : WithConv (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →ₐ[ℤ] A)) :
    GeneralLinear.schemePointsMulEquiv n A
        (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A q ≫
          (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom) =
      GeneralLinear.pointsMulEquiv n
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantToralDefiningIdeal e h ρ M hM hnil b wt))).app (CommAlgCat.of ℤ A) q) := by
  rw [kostantToralSchemePointMulEquiv_comp_toralGroupSchemeι]
  -- The quotient point carries the coercion of a `GrpCat` element, which `rw` will not identify
  -- with the plain convolution point the general-linear comparison is stated for.
  exact GeneralLinear.schemePointsMulEquiv_groupSchemePointMulEquiv (R := ℤ) n A _

include hθe hσ hbasis hwt in
/-- **On every algebra-valued point of the toral closure, the numbered-symmetry automorphism of the
group scheme is conjugation by the numbered-symmetry matrix.** This identifies the automorphism
`kostantToralNumberedSymmetryIso` of the carrier with the matrix conjugation that
`conj_kostantNumberedSymmetryMatrix_mem_kostantToralPointsSubgroup_iff` shows preserves the point
group: the two constructions, one through the defining Hopf ideal and one through the coordinate
automorphism, agree. -/
theorem schemePointsMulEquiv_kostantToralNumberedSymmetryIso (A : Type) [CommRing A]
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (kostantToralGroupScheme e h ρ M hM hnil b wt).X) :
    GeneralLinear.schemePointsMulEquiv n A
        (p ≫ (kostantToralNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
              basisScale hbasis torusPerm hwt).hom.hom.hom ≫
          (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom) =
      kostantNumberedSymmetryMatrix M b θ hθM A *
          GeneralLinear.schemePointsMulEquiv n A
            (p ≫ (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom) *
        (kostantNumberedSymmetryMatrix M b θ hθM A)⁻¹ := by
  obtain ⟨q, rfl⟩ := (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A).surjective p
  have hsym := kostantToralSchemePointMulEquiv_comp_numberedSymmetryIso
    e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt A q
  have hsymι := congrArg
    (fun f => f ≫ (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom) hsym
  have hincl := schemePointsMulEquiv_kostantToralSchemePointMulEquiv_comp_toralGroupSchemeι
    e h ρ M hM hnil b wt A q
  have hinclSym := schemePointsMulEquiv_kostantToralSchemePointMulEquiv_comp_toralGroupSchemeι
    e h ρ M hM hnil b wt A
    ((CommHopfAlgCat.mapPointsFunctor
      (kostantToralCoordinateNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
        basisScale hbasis torusPerm hwt).hom).app (CommAlgCat.of ℤ A) q)
  rw [← Category.assoc, hsymι, hinclSym, hincl]
  -- The quotient coordinate automorphism is induced by the ambient one, so precomposing a point
  -- with it and then with the quotient map is precomposing with the ambient automorphism.
  have hpoint : (CommHopfAlgCat.mapPointsFunctor
        (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt))).app (CommAlgCat.of ℤ A)
        ((CommHopfAlgCat.mapPointsFunctor
          (kostantToralCoordinateNumberedSymmetryIso e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm
            basisScale hbasis torusPerm hwt).hom).app (CommAlgCat.of ℤ A) q) =
      (CommHopfAlgCat.mapPointsFunctor
        (kostantNumberedSymmetryCoordinateIso M b θ hθM).hom).app (CommAlgCat.of ℤ A)
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
            (kostantToralDefiningIdeal e h ρ M hM hnil b wt))).app (CommAlgCat.of ℤ A) q) := by
    apply WithConv.ofConv_injective
    ext z
    exact congrArg (fun f => q.ofConv (f.hom z))
      (mkQuotient_comp_kostantToralCoordinateNumberedSymmetryIso_hom
        e h ρ M hM hnil b wt σ θ hθM hθe hσ basisPerm basisScale hbasis torusPerm hwt)
  rw [hpoint]
  exact pointsMulEquiv_mapPointsFunctor_kostantNumberedSymmetryCoordinateIso M b θ hθM
    (CommAlgCat.of ℤ A) _

end TauCeti.UniversalEnvelopingAlgebra
