/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Points
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.HopfIdealPoints.Presentation
public import TauCeti.Algebra.AlgebraicGroup.CommHopfAlgCat.SchemePoints

/-!
# Points of the toral Kostant closure

The closed group scheme `kostantToralGroupScheme` is generated inside `GLₙ` by the represented
Kostant root subgroups together with the represented weight torus. This file identifies the
corresponding formal inclusion on algebra-valued points. Its point subgroup contains both the
pointwise elementary group and the represented torus, and hence contains their join.

For an arbitrary set `S` of root indices, write `B_S(A)` for the subgroup generated by the root
subgroups indexed by `S` and the torus. After passing from automorphisms of the base-changed
lattice to matrices in its chosen basis, the main theorem gives

```text
B_S(A) ≤ kostantToralPointsSubgroup(A).
```

Taking `S = Set.univ` places the full torus--elementary subgroup assembled in
`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Borel` inside the points
of the assembled scheme carrier. Equality over an algebraically closed field is a separate
generation theorem and is not asserted here.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup`: the algebra-valued points of
  the toral closure, viewed in `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralSchemePointMulEquiv`: quotient-coordinate
  points of the toral closure identified with its scheme-valued points.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedPointsSubgroup_le_toralPoints`: the
  root-generated point subgroup is contained in the toral point subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix_mem_toralPoints`: every represented
  weight-torus point lies in the toral closure.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralRootSubgroupPoints` and
  `TauCeti.UniversalEnvelopingAlgebra.kostantToralWeightTorusPoints`: the canonical root-subgroup
  and weight-torus homomorphisms into the toral-closure points.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralWeightTorusPoints_conj_rootSubgroupPoints`:
  the pinning equation in those matrix-valued points.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantTorusSubsystemSubgroup_le_toralPoints`: every
  pointwise torus--root-subgroup join lies in the assembled scheme's points.

## References

The construction is the pointwise face of the split torus and root-subgroup carrier in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct WithConv
open scoped CategoryTheory.MonObj

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w v'

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type}
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

section Finite

variable [Finite κ]

/-- The algebra-valued points of the toral Kostant closure, embedded in `GLₙ` through its
Hopf-ideal quotient presentation. -/
noncomputable def kostantToralPointsSubgroup (A : Type v) [CommRing A] :
    Subgroup (Matrix.GeneralLinearGroup (Fin n) A) :=
  GeneralLinear.hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A

/-- The toral-closure points are the general-linear point subgroup cut out by the toral defining
Hopf ideal. -/
theorem kostantToralPointsSubgroup_def (A : Type v) [CommRing A] :
    kostantToralPointsSubgroup e h ρ M hM hnil b wt A =
      GeneralLinear.hopfIdealPointsSubgroup n
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A := by
  rw [kostantToralPointsSubgroup]

/-- Membership in the points of the toral closure is vanishing on its defining Hopf ideal. -/
@[simp]
theorem mem_kostantToralPointsSubgroup_iff (A : Type v) [CommRing A]
    (g : Matrix.GeneralLinearGroup (Fin n) A) :
    g ∈ kostantToralPointsSubgroup e h ρ M hM hnil b wt A ↔
      ∀ x ∈ kostantToralDefiningIdeal e h ρ M hM hnil b wt,
        ((GeneralLinear.pointsMulEquiv (R := ℤ) n).symm g).ofConv x = 0 := by
  rw [kostantToralPointsSubgroup_def]
  exact GeneralLinear.mem_hopfIdealPointsSubgroup_iff n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A g

/-- Adjoining the weight torus can only enlarge the algebra-valued point subgroup cut out by the
root-generated defining ideal. -/
theorem kostantGeneratedPointsSubgroup_le_toralPoints (A : Type v) [CommRing A] :
    kostantGeneratedPointsSubgroup e h ρ M hM hnil b A ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  simpa only [kostantGeneratedPointsSubgroup_def, kostantToralPointsSubgroup_def] using
    GeneralLinear.hopfIdealPointsSubgroup_le_of_le n
      (kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
        e h ρ M hM hnil b wt) A

end Finite

section Fintype

variable [Fintype κ]

/-- Every represented weight-torus matrix is a point of the toral closure. -/
theorem kostantTorusMatrix_mem_toralPoints
    (A : Type v) [CommRing A] (s : κ → Aˣ) :
    kostantTorusMatrix M b wt s ∈
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  let p := (SplitTorus.pointsMulEquiv (R := ℤ) (A := A) (σ := κ)).symm s
  let q : HopfAlgebra.points
      (R := ℤ) (H := GeneralLinear.coordinateHopfAlgebra ℤ n) (CommAlgCat.of ℤ A) :=
    (CommHopfAlgCat.mapPointsFunctor
      (GeneralLinear.weightTorusCoordinateMap wt)).app (CommAlgCat.of ℤ A) p
  have hq_matrix :
      GeneralLinear.pointsMulEquiv n q = kostantTorusMatrix M b wt s := by
    dsimp only [q]
    rw [GeneralLinear.mapPointsFunctor_weightTorusCoordinateMap_app,
      GeneralLinear.pointsMulEquiv_diagonalTorusPoints, kostantTorusMatrix_apply]
    congr 1
    funext i
    rw [GeneralLinear.diagonalTorusCoordinates_pointsMap_weightCharacterMap
      wt (CommAlgCat.of ℤ A) p i]
    simp only [p, MulEquiv.apply_symm_apply]
  rw [kostantToralPointsSubgroup_def, ← hq_matrix]
  exact GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_hopfIdealPointsSubgroup n
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)
    (GeneralLinear.weightTorusCoordinateMap wt)
    (kostantToralDefiningIdeal_toIdeal_le_torus_ker e h ρ M hM hnil b wt) A p

/-! ### The canonical subgroups of the toral-closure points -/

/-- The canonical root-subgroup homomorphism into the matrix-valued points of the toral Kostant
closure. The parameter is read through the multiplicative copy of the additive group. -/
noncomputable def kostantToralRootSubgroupPoints (i : I) (A : Type v) [CommRing A] :
    Multiplicative A →* kostantToralPointsSubgroup e h ρ M hM hnil b wt A :=
  MonoidHom.codRestrict
    ((kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b).comp
      (AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm.toMonoidHom)
    (kostantToralPointsSubgroup e h ρ M hM hnil b wt A) fun _u ↦
      kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A
        (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i _)

/-- The canonical toral-closure root-subgroup point is its represented divided-power exponential
matrix. -/
@[simp]
theorem coe_kostantToralRootSubgroupPoints (i : I) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    (kostantToralRootSubgroupPoints e h ρ M hM hnil b wt i A u :
        Matrix.GeneralLinearGroup (Fin n) A) =
      kostantRootSubgroupMatrix e h ρ M hM i (hnil i) b
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u) := by
  rw [kostantToralRootSubgroupPoints]
  rfl

/-- The canonical weight-torus homomorphism into the matrix-valued points of the toral Kostant
closure. -/
noncomputable def kostantToralWeightTorusPoints (A : Type v) [CommRing A] :
    (κ → Aˣ) →* kostantToralPointsSubgroup e h ρ M hM hnil b wt A :=
  MonoidHom.codRestrict (kostantTorusMatrix M b wt)
    (kostantToralPointsSubgroup e h ρ M hM hnil b wt A)
      (kostantTorusMatrix_mem_toralPoints e h ρ M hM hnil b wt A)

/-- The canonical toral-closure weight-torus point is its diagonal weight matrix. -/
@[simp]
theorem coe_kostantToralWeightTorusPoints (A : Type v) [CommRing A] (s : κ → Aˣ) :
    (kostantToralWeightTorusPoints e h ρ M hM hnil b wt A s :
        Matrix.GeneralLinearGroup (Fin n) A) =
      kostantTorusMatrix M b wt s := by
  rw [kostantToralWeightTorusPoints]
  rfl

/-- The integral-points presentation of the toral Kostant closure. -/
noncomputable abbrev kostantToralPointsPresentation (A : Type v) [CommRing A] :
    GeneralLinear.IntegralPointsPresentation n
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) A :=
  ⟨kostantToralPointsSubgroup e h ρ M hM hnil b wt A,
    kostantToralPointsSubgroup_def e h ρ M hM hnil b wt A⟩

/-- The presented toral-closure root point is natural in the value ring. -/
@[simp]
theorem map_kostantToralRootSubgroupPoints
    {A : Type v} {B : Type v'} [CommRing A] [CommRing B]
    (f : A →+* B) (i : I) (u : Multiplicative A) :
    (kostantToralPointsPresentation e h ρ M hM hnil b wt A).map
        (kostantToralPointsPresentation e h ρ M hM hnil b wt B) f
        (kostantToralRootSubgroupPoints e h ρ M hM hnil b wt i A u) =
      kostantToralRootSubgroupPoints e h ρ M hM hnil b wt i B
        (Multiplicative.ofAdd (f (Multiplicative.toAdd u))) := by
  apply Subtype.ext
  rw [GeneralLinear.IntegralPointsPresentation.coe_map,
    coe_kostantToralRootSubgroupPoints, coe_kostantToralRootSubgroupPoints,
    map_kostantRootSubgroupMatrix,
    AdditiveGroup.mapValue_gaPointsMulEquiv_symm_apply, RingHom.toIntAlgHom_apply]

/-- The presented toral-closure weight-torus point is natural in the value ring. -/
@[simp]
theorem map_kostantToralWeightTorusPoints
    {A : Type v} {B : Type v'} [CommRing A] [CommRing B]
    (f : A →+* B) (s : κ → Aˣ) :
    (kostantToralPointsPresentation e h ρ M hM hnil b wt A).map
        (kostantToralPointsPresentation e h ρ M hM hnil b wt B) f
        (kostantToralWeightTorusPoints e h ρ M hM hnil b wt A s) =
      kostantToralWeightTorusPoints e h ρ M hM hnil b wt B
        (fun i ↦ Units.map (f : A →* B) (s i)) := by
  apply Subtype.ext
  rw [GeneralLinear.IntegralPointsPresentation.coe_map,
    coe_kostantToralWeightTorusPoints, coe_kostantToralWeightTorusPoints]
  exact map_kostantTorusMatrix (M := M) (b := b) (wt := wt) f s

/-- The pinning equation in the matrix-valued points of the toral Kostant closure. If `e i` has
Cartan weight `α`, conjugation by the weight-torus point `s` rescales the root-subgroup
parameter by `α(s)`. This is not a `simp` lemma: the weight `α` is pinned only by the hypothesis
`hα`, so `simp` could never infer it from the left-hand side. -/
theorem kostantToralWeightTorusPoints_conj_rootSubgroupPoints
    (hwt : ∀ x, IsCartanWeightVector h ρ (wt x) ((b x : M) : V))
    {i : I} {α : κ → ℤ} (hα : ∀ j, ⁅h j, e i⁆ = (α j : ℚ) • e i)
    (A : Type v) [CommRing A] (s : κ → Aˣ) (u : Multiplicative A) :
    kostantToralWeightTorusPoints e h ρ M hM hnil b wt A s *
        kostantToralRootSubgroupPoints e h ρ M hM hnil b wt i A u *
        (kostantToralWeightTorusPoints e h ρ M hM hnil b wt A s)⁻¹ =
      kostantToralRootSubgroupPoints e h ρ M hM hnil b wt i A
        (Multiplicative.ofAdd
          ((torusCharacter s α : A) * Multiplicative.toAdd u)) := by
  have hmul := kostantTorusPoints_mul_kostantRootSubgroupPoints e h ρ M hM b wt hwt hα
    (hnil i) s ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u)
    ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
      (Multiplicative.ofAdd ((torusCharacter s α : A) * Multiplicative.toAdd u))) (by simp)
  have hmatrix := congrArg
    (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMonoidHom) hmul
  apply Subtype.ext
  simp only [Subgroup.coe_mul, Subgroup.coe_inv, coe_kostantToralWeightTorusPoints,
    coe_kostantToralRootSubgroupPoints]
  rw [mul_inv_eq_iff_eq_mul, ← basisMatrix_kostantTorusPoints M b wt (A := A) s]
  rw [kostantRootSubgroupMatrix_def, MonoidHom.comp_apply, MonoidHom.comp_apply]
  simpa only [map_mul, MulEquiv.toMonoidHom_eq_coe] using hmatrix

/-- After writing automorphisms in the basis `b`, every subgroup generated by a set of represented
root subgroups together with the weight torus lies in the points of the toral closure. -/
theorem map_kostantTorusSubsystemSubgroup_le_toralPoints
    (S : Set I) (A : Type v) [CommRing A] :
    (kostantTorusSubsystemSubgroup e h ρ M hM hnil b wt S (CommAlgCat.of ℤ A)).map
        (Units.map (LinearMap.toMatrixAlgEquiv (b.baseChange A)).toMulEquiv) ≤
      kostantToralPointsSubgroup e h ρ M hM hnil b wt A := by
  rw [Subgroup.map_le_iff_le_comap]
  apply (kostantTorusSubsystemSubgroup_le_iff e h ρ M hM hnil b wt).2
  constructor
  · intro i _ t
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantRootSubgroupParam]
    exact kostantGeneratedPointsSubgroup_le_toralPoints e h ρ M hM hnil b wt A
      (kostantRootSubgroupMatrix_mem_generatedPoints e h ρ M hM hnil b A i
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm t))
  · intro s
    rw [Subgroup.mem_comap]
    rw [basisMatrix_kostantTorusPoints]
    exact kostantTorusMatrix_mem_toralPoints e h ρ M hM hnil b wt A s

end Fintype

/-! ### Scheme-valued points -/

section SchemePoints

variable [Finite κ]

/-- The toral closure is represented by its quotient coordinate Hopf algebra. -/
theorem kostantToralGroupScheme_eq_hopfSpec :
    kostantToralGroupScheme e h ρ M hM hnil b wt =
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op
        (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt))) :=
  (rfl)

/-- The underlying scheme of the toral closure is the spectrum of its coordinate ring. -/
theorem kostantToralGroupScheme_X_left :
    (kostantToralGroupScheme e h ρ M hM hnil b wt).X.left =
      Spec (CommRingCat.of (CommHopfAlgCat.quotient
        (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt))) :=
  congrArg (fun G : Grp (Over (Spec (CommRingCat.of ℤ))) ↦ G.X.left)
    (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)

/-- Algebra-valued points of the toral closure, transported to scheme-valued points. -/
noncomputable def kostantToralSchemePointMulEquiv (A : Type) [CommRing A] :
    WithConv (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →ₐ[ℤ] A) ≃*
      ((Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
        (letI := (braidedAlgSpec (R := CommRingCat.of ℤ)).toMonoidal
         ((algSpec (CommRingCat.of ℤ)).mapGrp.obj (Opposite.unop
           ((commHopfAlgCatEquivCogrpCommAlgCat ℤ).functor.obj
             (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
               (kostantToralDefiningIdeal e h ρ M hM hnil b wt))))).X)) :=
  CommHopfAlgCat.mapMulEquivOfPresentation _ A
    (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)

/-- The underlying spectrum map of a quotient point of the toral closure. -/
@[simp]
theorem kostantToralSchemePointMulEquiv_apply_left (A : Type) [CommRing A]
    (q : WithConv (CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →ₐ[ℤ] A)) :
    (kostantToralSchemePointMulEquiv e h ρ M hM hnil b wt A q).left =
      Spec.map (CommRingCat.ofHom (q.ofConv :
        CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) →+* A)) ≫
        eqToHom (kostantToralGroupScheme_X_left e h ρ M hM hnil b wt).symm := by
  simpa only [kostantToralSchemePointMulEquiv] using
    CommHopfAlgCat.mapMulEquivOfPresentation_apply_left _ A
      (kostantToralGroupScheme_eq_hopfSpec e h ρ M hM hnil b wt)
      (kostantToralGroupScheme_X_left e h ρ M hM hnil b wt) q

end SchemePoints

end TauCeti.UniversalEnvelopingAlgebra
