/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.DirectSum.Algebra
public import TauCeti.Algebra.Module.GradedModule.GradedObject
public import TauCeti.CategoryTheory.DG.SingleObj

/-!
# The endomorphism differential graded algebra of an object

For an object `X` of a differential graded category `C` over `R`, the homogeneous endomorphisms
of `X` of all degrees form a differential graded algebra `End(X) = ⨁ n, Hom^n(X, X)`: the
product is composition, the unit is the identity, and the differential is the differential of
the Hom complex.  It is the passage from a DG category back to DG algebras: derived Morita theory
describes the derived category generated by a compact generator `G` through modules over the
endomorphism DG algebra of `G`.

The product is Keller-ordered composition, so that for homogeneous `g` of degree `q` and `f` of
degree `p` the product `g * f` is `g ∘ f`, "first `f`, then `g`".  Composition in a
`TauCeti.DGCategory` is in Mathlib's enriched factor order instead, and the two orders differ by
the Koszul sign:

`g * f = (-1) ^ (p * q) • dgComp f g`.

With this sign the Leibniz rule of the Hom complexes becomes the Leibniz rule
`d (g * f) = d g * f + (-1) ^ |g| • g * d f` of a differential graded algebra, and the
construction inverts the one-object DG category `TauCeti.DGSingleObj` of a DG algebra `A`: the
endomorphism DG algebra of its unique object is `A` again, with no sign twist.

The algebra is the external direct sum of the Hom modules, graded by the copies of the summands
(`TauCeti.InternalGrading.gradedObjectPiece`), and its ring structure is the one Mathlib builds on
a direct sum from a graded ring structure on the summands (`DirectSum.GRing`,
`DirectSum.GAlgebra`).

## Main definitions

* `TauCeti.DGEnd`: the endomorphism algebra `⨁ n, Hom^n(X, X)` of an object.
* `TauCeti.DGEnd.grading`: its grading by the degree of a morphism.
* `TauCeti.DGEnd.differential`: its differential, the differential of the Hom complex.

## Main results

* `TauCeti.DGEnd.lof_mul_lof`: multiplication is Keller-ordered composition, with the Koszul sign
  `(-1) ^ (p * q)` relative to `TauCeti.dgComp`.
* `TauCeti.DGEnd.one_def`: the unit is the identity morphism.
* `TauCeti.DGEnd.differential_lof`: the differential is the differential of the Hom complex.
* `TauCeti.DGEnd.isDGAlgebra`: the endomorphism algebra is a differential graded algebra.
* `TauCeti.DGSingleObj.dgEndAlgEquiv`, `TauCeti.DGSingleObj.dgEndAlgEquiv_mem_iff` and
  `TauCeti.DGSingleObj.dgEndAlgEquiv_differential`: the endomorphism DG algebra of the unique
  object of the one-object DG category of a DG algebra `A` is isomorphic to `A`, compatibly with
  the gradings and the differentials.

## References

* B. Keller, *Deriving DG categories*, Section 1.
* B. Keller, *Introduction to A-infinity algebras and modules*, Section 3.1.
-/

public section

open DirectSum

namespace TauCeti

universe v u

variable (R : Type v) [CommRing R] {C : Type u} [DGCategory R C]

/-! ### The graded ring of homogeneous endomorphisms -/

namespace DGEnd

variable {R} (X : C)

/-- A multiple of a composite, regarded as an element of the graded monoid of homogeneous
endomorphisms, does not depend on the name of its degree. -/
private theorem mk_zsmul_dgComp {p q n n' : ℤ} {u u' : ℤ} (hu : u = u')
    (f : DGHom R p X X) (g : DGHom R q X X) (h : p + q = n) (h' : p + q = n') :
    GradedMonoid.mk (A := fun n ↦ DGHom R n X X) n (u • dgComp R f g h) =
      GradedMonoid.mk n' (u' • dgComp R f g h') := by
  subst hu h h'
  rfl

/-- The unit of the graded ring of homogeneous endomorphisms: the identity. -/
noncomputable instance gOne : GradedMonoid.GOne fun n : ℤ ↦ DGHom R n X X where
  one := dgId R X

/-- The product of the graded ring of homogeneous endomorphisms: Keller-ordered composition,
`g * f = (-1) ^ (q * p) • dgComp f g` for `g` of degree `q` and `f` of degree `p`. -/
noncomputable instance gMul : GradedMonoid.GMul fun n : ℤ ↦ DGHom R n X X where
  mul {q p} g f := (q * p).negOnePow • dgComp R f g (add_comm p q)

/-- The unit of the graded ring of homogeneous endomorphisms is the identity. -/
theorem gOne_def :
    (GradedMonoid.GOne.one (A := fun n : ℤ ↦ DGHom R n X X)) = dgId R X :=
  (rfl)

/-- The product of the graded ring of homogeneous endomorphisms is Keller-ordered composition. -/
theorem gMul_def {q p : ℤ} (g : DGHom R q X X) (f : DGHom R p X X) :
    (GradedMonoid.GMul.mul (A := fun n : ℤ ↦ DGHom R n X X) g f) =
      (q * p).negOnePow • dgComp R f g (add_comm p q) :=
  (rfl)

/-- Left multiplication by a multiple of the identity is scalar multiplication. -/
private theorem mk_smul_dgId_mul_mk (c : R) {i : ℤ} (x : DGHom R i X X) :
    GradedMonoid.mk (A := fun n ↦ DGHom R n X X) 0 (c • dgId R X) * GradedMonoid.mk i x =
      GradedMonoid.mk i (c • x) := by
  rw [GradedMonoid.mk_mul_mk, gMul_def, Units.smul_def, dgComp_smul, ← smul_dgComp,
    mk_zsmul_dgComp X (u' := 1) (by simp) _ _ _ (add_zero i), one_smul, dgComp_dgId]

/-- Right multiplication by a multiple of the identity is scalar multiplication. -/
private theorem mk_mul_mk_smul_dgId (c : R) {i : ℤ} (x : DGHom R i X X) :
    GradedMonoid.mk (A := fun n ↦ DGHom R n X X) i x * GradedMonoid.mk 0 (c • dgId R X) =
      GradedMonoid.mk i (c • x) := by
  rw [GradedMonoid.mk_mul_mk, gMul_def, Units.smul_def, smul_dgComp, ← dgComp_smul,
    mk_zsmul_dgComp X (u' := 1) (by simp) _ _ _ (zero_add i), one_smul, dgId_dgComp]

/-- Keller-ordered composition is associative: the Koszul signs of the two bracketings agree. -/
private theorem mk_mul_mk_mul_mk {i j k : ℤ} (a : DGHom R i X X) (b : DGHom R j X X)
    (c : DGHom R k X X) :
    GradedMonoid.mk (A := fun n ↦ DGHom R n X X) i a * GradedMonoid.mk j b * GradedMonoid.mk k c =
      GradedMonoid.mk i a * (GradedMonoid.mk j b * GradedMonoid.mk k c) := by
  simp only [GradedMonoid.mk_mul_mk, gMul_def, Units.smul_def, ← Int.cast_smul_eq_zsmul R,
    smul_dgComp, dgComp_smul, smul_smul, ← Int.cast_mul]
  rw [dgComp_assoc R c b a (add_comm k j) (add_comm j i) (by omega), Int.cast_smul_eq_zsmul,
    Int.cast_smul_eq_zsmul]
  refine mk_zsmul_dgComp X ?_ _ _ _ _
  rw [← Units.val_mul, ← Units.val_mul, ← Int.negOnePow_add, ← Int.negOnePow_add]
  congr 2
  ring

/- In the fields below, the unit of `GradedMonoid` is `⟨0, GOne.one⟩`, the structure map sends
`r` to `r • dgId R X`, and a product `⟨i, a⟩ * ⟨j, b⟩` is `⟨i + j, GMul.mul a b⟩`, all by
definition; the lemmas above are stated in these terms. -/

/-- The homogeneous endomorphisms of an object form a graded monoid under Keller-ordered
composition. -/
noncomputable instance gMonoid : GradedMonoid.GMonoid fun n : ℤ ↦ DGHom R n X X :=
  { gOne X, gMul X with
    one_mul := fun x ↦ by
      have h := mk_smul_dgId_mul_mk X (1 : R) x.2
      rw [one_smul, one_smul] at h
      exact h
    mul_one := fun x ↦ by
      have h := mk_mul_mk_smul_dgId X (1 : R) x.2
      rw [one_smul, one_smul] at h
      exact h
    mul_assoc := fun a b c ↦ by exact mk_mul_mk_mul_mk X a.2 b.2 c.2 }

/-- The homogeneous endomorphisms of an object form a graded ring under Keller-ordered
composition. -/
noncomputable instance gRing : DirectSum.GRing fun n : ℤ ↦ DGHom R n X X :=
  { gMonoid X with
    mul_zero := fun _ ↦ by simp [gMul_def]
    zero_mul := fun _ ↦ by simp [gMul_def]
    mul_add := fun _ _ _ ↦ by simp [gMul_def]
    add_mul := fun _ _ _ ↦ by simp [gMul_def]
    natCast := fun n ↦ n • dgId R X
    natCast_zero := zero_smul _ _
    natCast_succ := fun n ↦ succ_nsmul _ n
    intCast := fun n ↦ n • dgId R X
    intCast_ofNat := fun n ↦ natCast_zsmul _ n
    intCast_negSucc_ofNat := fun n ↦ negSucc_zsmul _ n }

/-- The homogeneous endomorphisms of an object form a graded `R`-algebra: a scalar `r` acts as
the degree-zero endomorphism `r • dgId R X`. -/
noncomputable instance gAlgebra : DirectSum.GAlgebra R fun n : ℤ ↦ DGHom R n X X where
  toFun := (LinearMap.toSpanSingleton R _ (dgId R X)).toAddMonoidHom
  map_one := one_smul R (dgId R X)
  map_mul r s := by
    exact (congrArg (GradedMonoid.mk 0) (mul_smul r s (dgId R X))).trans
      (mk_smul_dgId_mul_mk X r (s • dgId R X)).symm
  commutes r x := by
    exact (mk_smul_dgId_mul_mk X r x.2).trans (mk_mul_mk_smul_dgId X r x.2).symm
  smul_def r x := by
    exact (mk_smul_dgId_mul_mk X r x.2).symm

end DGEnd

/-! ### The endomorphism algebra -/

/-- The **endomorphism algebra** of an object `X` of a differential graded category: the direct
sum `⨁ n, Hom^n(X, X)` of its homogeneous endomorphisms, with Keller-ordered composition as
product and the identity as unit. -/
abbrev DGEnd (X : C) : Type v :=
  ⨁ n : ℤ, DGHom R n X X

namespace DGEnd

variable {R} {X : C}

/-- Multiplication in the endomorphism algebra is Keller-ordered composition: for `g` of degree
`q` and `f` of degree `p`, the product `g * f` is "first `f`, then `g`", which is the enriched
composite `dgComp f g` up to the Koszul sign `(-1) ^ (p * q)`. -/
@[simp]
theorem lof_mul_lof {p q n : ℤ} (g : DGHom R q X X) (f : DGHom R p X X) (h : p + q = n) :
    lof R ℤ (fun n ↦ DGHom R n X X) q g * lof R ℤ (fun n ↦ DGHom R n X X) p f =
      lof R ℤ (fun n ↦ DGHom R n X X) n ((p * q).negOnePow • dgComp R f g h) := by
  subst h
  rw [lof_eq_of, lof_eq_of, lof_eq_of, of_mul_of, gMul_def, mul_comm q p]
  rw [Units.smul_def, Units.smul_def]
  exact DirectSum.of_eq_of_gradedMonoid_eq (mk_zsmul_dgComp X rfl f g (add_comm p q) rfl)

/-- The unit of the endomorphism algebra is the identity morphism. -/
theorem one_def : (1 : DGEnd R X) = lof R ℤ (fun n ↦ DGHom R n X X) 0 (dgId R X) :=
  (rfl)

/-- A scalar acts on the endomorphism algebra as a multiple of the identity morphism. -/
theorem algebraMap_apply (r : R) :
    algebraMap R (DGEnd R X) r = lof R ℤ (fun n ↦ DGHom R n X X) 0 (r • dgId R X) :=
  (rfl)

/-! ### The grading -/

variable (R X)

/-- The grading of the endomorphism algebra by the degree of a morphism: the degree-`n` part is
the copy of `Hom^n(X, X)`. -/
abbrev grading (n : ℤ) : Submodule R (DGEnd R X) :=
  InternalGrading.gradedObjectPiece R (dgHomComplex R X X).X n

variable {R X}

/-- A homogeneous endomorphism of degree `n` lies in the degree-`n` part. -/
theorem lof_mem_grading {n : ℤ} (f : DGHom R n X X) :
    lof R ℤ (fun n ↦ DGHom R n X X) n f ∈ grading R X n :=
  LinearMap.mem_range_self _ f

/-- The degree-`n` part consists of the homogeneous endomorphisms of degree `n`. -/
theorem mem_grading_iff {n : ℤ} {a : DGEnd R X} :
    a ∈ grading R X n ↔ ∃ f : DGHom R n X X, lof R ℤ (fun n ↦ DGHom R n X X) n f = a :=
  LinearMap.mem_range

/-- The grading of the endomorphism algebra respects the unit and the multiplication: the identity
has degree `0`, and a product of homogeneous endomorphisms of degrees `q` and `p` has degree
`q + p`. -/
instance : SetLike.GradedMonoid (grading R X) where
  one_mem := lof_mem_grading (dgId R X)
  mul_mem := by
    rintro q p _ _ ⟨g, rfl⟩ ⟨f, rfl⟩
    rw [lof_mul_lof g f (add_comm p q)]
    exact lof_mem_grading _

variable (R X) in
/-- The endomorphism algebra is graded by the degree of a morphism. -/
noncomputable instance gradedAlgebra : GradedAlgebra (grading R X) :=
  DirectSum.IsInternal.gradedAlgebra (M := grading R X) <| by
    have h := (InternalGrading.ofGradedObject R (dgHomComplex R X X).X).isInternal
    rwa [funext (InternalGrading.ofGradedObject_piece R (dgHomComplex R X X).X)] at h

/-! ### The differential -/

variable (R X) in
/-- The differential of the endomorphism algebra: the differential of the Hom complex, applied
in every degree. -/
noncomputable def differential : DGEnd R X →ₗ[R] DGEnd R X :=
  toModule R ℤ _ fun n ↦ lof R ℤ (fun n ↦ DGHom R n X X) (n + 1) ∘ₗ dgDifferential R n

/-- The differential of the endomorphism algebra is the differential of the Hom complex. -/
@[simp]
theorem differential_lof {n : ℤ} (f : DGHom R n X X) :
    differential R X (lof R ℤ (fun n ↦ DGHom R n X X) n f) =
      lof R ℤ (fun n ↦ DGHom R n X X) (n + 1) (dgDifferential R n f) := by
  rw [differential, toModule_lof, LinearMap.comp_apply]

/-- The Leibniz rule on two homogeneous endomorphisms. -/
private theorem differential_lof_mul_lof {p q : ℤ} (g : DGHom R q X X) (f : DGHom R p X X) :
    differential R X (lof R ℤ (fun n ↦ DGHom R n X X) q g * lof R ℤ (fun n ↦ DGHom R n X X) p f) =
      differential R X (lof R ℤ (fun n ↦ DGHom R n X X) q g) *
          lof R ℤ (fun n ↦ DGHom R n X X) p f +
        q.negOnePow • (lof R ℤ (fun n ↦ DGHom R n X X) q g *
          differential R X (lof R ℤ (fun n ↦ DGHom R n X X) p f)) := by
  rw [lof_mul_lof g f rfl, differential_lof, differential_lof, differential_lof,
    lof_mul_lof (dgDifferential R q g) f (add_assoc p q 1).symm,
    lof_mul_lof g (dgDifferential R p f) (add_right_comm p 1 q), map_zsmul_unit,
    dgDifferential_dgComp, smul_add, ← map_zsmul_unit, ← map_add]
  congr 1
  have e₁ : (p * q).negOnePow * p.negOnePow = (p * (q + 1)).negOnePow := by
    rw [← Int.negOnePow_add, Int.negOnePow_eq_iff]
    exact ⟨0, by ring⟩
  have e₂ : q.negOnePow * ((p + 1) * q).negOnePow = (p * q).negOnePow := by
    rw [← Int.negOnePow_add, Int.negOnePow_eq_iff]
    exact ⟨q, by ring⟩
  rw [smul_smul, smul_smul, e₁, e₂]
  exact add_comm _ _

/-- **The endomorphism algebra of an object is a differential graded algebra.** -/
theorem isDGAlgebra : IsDGAlgebra (grading R X) (differential R X) where
  map_mem := by
    rintro p _ ⟨f, rfl⟩
    rw [differential_lof]
    exact lof_mem_grading _
  sq_zero a := by
    induction a using DirectSum.induction_on with
    | zero => simp
    | of n f => simp [← lof_eq_of R]
    | add a b ha hb => simp [ha, hb]
  leibniz := by
    rintro q _ ⟨g, rfl⟩ b
    induction b using DirectSum.induction_on with
    | zero => simp
    | of p f => simpa [← lof_eq_of R] using differential_lof_mul_lof g f
    | add a b ha hb => simp only [mul_add, map_add, ha, hb, smul_add]; abel

end DGEnd

/-! ### The endomorphism algebra of the one-object category of a DG algebra -/

namespace DGSingleObj

variable {R A : Type v} [CommRing R] [Ring A] [Algebra R A]
  {𝒜 : ℤ → Submodule R A} [GradedAlgebra 𝒜] {d : A →ₗ[R] A} (h : IsDGAlgebra 𝒜 d)

/-- The endomorphism algebra of the unique object of the one-object DG category of a DG algebra
`A` is `A`, as a module: a degree-`n` endomorphism is sent to the element of `𝒜 n` it names. -/
private noncomputable def dgEndLinearEquiv : DGEnd R (star h) ≃ₗ[R] A :=
  (DirectSum.congrLinearEquiv fun n ↦ dgHomEquiv (star h) (star h) n).trans
    (DirectSum.decomposeLinearEquiv 𝒜).symm

private theorem dgEndLinearEquiv_lof {n : ℤ} (f : DGHom R n (star h) (star h)) :
    dgEndLinearEquiv h (lof R ℤ (fun n ↦ DGHom R n (star h) (star h)) n f) =
      dgHomEquiv (star h) (star h) n f := by
  rw [dgEndLinearEquiv, LinearEquiv.trans_apply, DirectSum.coe_congrLinearEquiv,
    DirectSum.lmap_lof, LinearEquiv.coe_toLinearMap, DirectSum.decomposeLinearEquiv_symm_lof]

private theorem dgEndLinearEquiv_mul (x y : DGEnd R (star h)) :
    dgEndLinearEquiv h (x * y) = dgEndLinearEquiv h x * dgEndLinearEquiv h y := by
  induction x using DirectSum.induction_on with
  | zero => simp
  | add x x' hx hx' => simp [add_mul, hx, hx']
  | of q g =>
    induction y using DirectSum.induction_on with
    | zero => simp
    | add y y' hy hy' => simp [mul_add, hy, hy']
    | of p f =>
      rw [← lof_eq_of R, ← lof_eq_of R, DGEnd.lof_mul_lof g f rfl, dgEndLinearEquiv_lof,
        dgEndLinearEquiv_lof, dgEndLinearEquiv_lof, map_zsmul_unit, Submodule.coe_smul_of_tower,
        dgHomEquiv_dgComp, smul_smul, Int.units_mul_self, one_smul]

/-- **The endomorphism algebra of the one-object DG category of a DG algebra `A` is `A`.**  A
degree-`n` endomorphism of the unique object is sent to the element of `𝒜 n` it names; with the
Keller-ordered product of `TauCeti.DGEnd` this is multiplicative, with no sign twist. -/
noncomputable def dgEndAlgEquiv : DGEnd R (star h) ≃ₐ[R] A :=
  AlgEquiv.ofLinearEquiv (dgEndLinearEquiv h)
    (by rw [DGEnd.one_def, dgEndLinearEquiv_lof, dgHomEquiv_dgId]) (dgEndLinearEquiv_mul h)

/-- The comparison sends a homogeneous endomorphism to the element of the algebra it names. -/
@[simp]
theorem dgEndAlgEquiv_lof {n : ℤ} (f : DGHom R n (star h) (star h)) :
    dgEndAlgEquiv h (lof R ℤ (fun n ↦ DGHom R n (star h) (star h)) n f) =
      dgHomEquiv (star h) (star h) n f :=
  dgEndLinearEquiv_lof h f

/-- The comparison identifies the degree-`n` part of the endomorphism algebra with `𝒜 n`. -/
@[simp]
theorem dgEndAlgEquiv_mem_iff {n : ℤ} {x : DGEnd R (star h)} :
    dgEndAlgEquiv h x ∈ 𝒜 n ↔ x ∈ DGEnd.grading R (star h) n := by
  refine ⟨fun hx ↦ ?_, ?_⟩
  · obtain ⟨f, hf⟩ := (dgHomEquiv (star h) (star h) n).surjective ⟨_, hx⟩
    refine DGEnd.mem_grading_iff.mpr ⟨f, (dgEndAlgEquiv h).injective ?_⟩
    rw [dgEndAlgEquiv_lof, hf]
  · rintro ⟨f, rfl⟩
    rw [dgEndAlgEquiv_lof]
    exact SetLike.coe_mem _

/-- The comparison intertwines the differential of the endomorphism algebra with the differential
of the algebra. -/
@[simp]
theorem dgEndAlgEquiv_differential (x : DGEnd R (star h)) :
    dgEndAlgEquiv h (DGEnd.differential R (star h) x) = d (dgEndAlgEquiv h x) := by
  induction x using DirectSum.induction_on with
  | zero => simp
  | add x y hx hy => simp [hx, hy]
  | of n f => rw [← lof_eq_of R, DGEnd.differential_lof, dgEndAlgEquiv_lof, dgEndAlgEquiv_lof,
      dgHomEquiv_dgDifferential]

end DGSingleObj

end TauCeti
