/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.CoordinateRing
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.BaseChange
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Point.Basic
-- Proof-only: evaluation of the coordinate ring, which supplies the equation at the generic point.
import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Eval
-- Proof-only: `polynomialY_ne_zero`, that `W_Y` is a nonzero polynomial once `Δ ≠ 0`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.Derivative

/-!
# The generic point of an affine Weierstrass curve

The coordinate ring `W.CoordinateRing` is `R[X][Y]` modulo the Weierstrass relation, so the
classes of `X` and `Y` in the function field are a pair satisfying that relation over
`W.FunctionField`. They are the *generic point*: a point of `W` base-changed to its own function
field.

What is proved here is that the pair is a point (`equation_genericX_genericY`), that evaluating a
bivariate polynomial at it is reduction modulo the Weierstrass relation
(`evalEval_genericX_genericY`), and that on an elliptic curve over a nontrivial base ring the
resulting solution is nonsingular, cutting out a point `genericPoint` of `W⁄F(W)`. The
coordinate-ring image also lies in the subalgebra generated by the two coordinates
(`algebraMap_mem_adjoin_genericX_genericY`).

Over a field the generic `x`-coordinate is transcendental, and on an elliptic curve the partial
derivative `W_Y = 2Y + a₁X + a₃` is nonzero at the generic point
(`evalEval_polynomialY_genericX_genericY_ne_zero`); in characteristic two the latter holds because
`Δ ≠ 0` rules out `a₁ = a₃ = 0`.

The word "generic" is the usual geometric one, but no specialisation property is established:
nothing below says that a statement about this point transfers to the points of `W`, and no
consumer may rely on that.

## Main definitions

* `WeierstrassCurve.Affine.genericX`, `WeierstrassCurve.Affine.genericY`: the coordinates.
* `WeierstrassCurve.Affine.genericPoint`: the point of `W⁄F(W)` cut out by the generic coordinates.

## Main results

* `WeierstrassCurve.Affine.equation_genericX_genericY`: the generic coordinates satisfy the
  equation.
* `WeierstrassCurve.Affine.nonsingular_genericX_genericY`: they are nonsingular, on an elliptic
  curve.
* `WeierstrassCurve.Affine.evalEval_genericX_genericY`: evaluation there is reduction.
* `WeierstrassCurve.Affine.aeval_genericY_polynomial`: the generic `y`-coordinate is a root of
  the Weierstrass polynomial.
* `WeierstrassCurve.Affine.isIntegral_genericY`: it is integral over any commutative
  `R[X]`-algebra mapping compatibly to the function field.
* `WeierstrassCurve.Affine.algebraMap_eq_aeval_genericX`: the image of `R[X]` in the
  function field is the polynomials in the generic `x`-coordinate.
* `WeierstrassCurve.Affine.algebraMap_mem_adjoin_genericX_genericY`: the coordinate ring, read
  inside the function field, lies in the `R`-subalgebra generated by the generic coordinates.
* `WeierstrassCurve.Affine.transcendental_genericX` and
  `WeierstrassCurve.Affine.genericX_ne_algebraMap`: the coordinate `x` is transcendental
  over the base field, so it takes no constant value.
* `WeierstrassCurve.Affine.evalEval_polynomialY_genericX_genericY_ne_zero`: on an elliptic curve
  over a field the partial derivative `W_Y` is nonzero at the generic point.
* `WeierstrassCurve.Affine.map_genericPoint_injective`: an `F`-algebra homomorphism from the
  function field into a field extension is determined by the point it sends the generic point to.
* `WeierstrassCurve.Affine.eq_of_baseChange_eq_sub_map_genericPoint`: an embedding is likewise
  determined by the rational point it displaces the generic point by.

## Roadmap

`TauCetiRoadmap/EllipticCurves/README.md`, **Layer 0.5**, whose third milestone asks for the
"function-field pullbacks of the translations `τ_P`, with the action and composition laws". Those
pullbacks are evaluation at the translates of the generic point, built in
`TauCeti/AlgebraicGeometry/EllipticCurve/Affine/FunctionField/Translation/Basic.lean`; this file is
the point they translate.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.1, II.2.

## Provenance

The generic coordinates and their equation are adapted from the AINTLIB `HasseWeil` project
(Chris Birkbeck), Apache-2.0, `HasseWeil/MulByIntPullback.lean` at commit
`513e83879e2f8cbc626eb9e04d660e92be16ccba`, declarations `x_gen`, `y_gen`, `W_KE`, and
`generic_equation`. Its transcendence statement is reproved here as `transcendental_genericX`.
The bundled `genericPoint` and its coordinate-accessor API are not ported from that source.

`map_genericPoint_injective` adapts the statement of that project's
`HasseWeil/GapSpines.lean` declaration `emb_le_card_kernel`, same commit and license, which
assigns a point to each embedding and shows the assignment injective. The proof differs: the
source works with points over `AlgebraicClosure K(E)` and with an isogeny carrying its own point
map, while here the point is the image of the generic point and injectivity comes from
`CoordinateRing.algHom_ext` and `IsFractionRing.ringHom_ext`.
-/

public section

open Polynomial WeierstrassCurve WeierstrassCurve.Affine

open scoped Polynomial.Bivariate

namespace WeierstrassCurve.Affine

variable {R : Type*} [CommRing R] (W : _root_.WeierstrassCurve.Affine R)

/-- The generic `x`-coordinate: the class of `X` in the function field. -/
noncomputable def genericX : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X))

/-- The generic `y`-coordinate: the class of `Y` in the function field. -/
noncomputable def genericY : W.FunctionField :=
  algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y)

/-- The generic coordinate `x` is the image of the coordinate-ring class of `X` in the function
field. -/
theorem genericX_def :
    genericX W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W (C X)) := (rfl)

/-- The generic coordinate `y` is the image of the coordinate-ring class of `Y` in the function
field. -/
theorem genericY_def :
    genericY W = algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W Y) := (rfl)

/-- The generic coordinate `x` is the image of polynomial `X` under the induced map from `R[X]`
to the function field. -/
theorem genericX_eq_algebraMap : genericX W = algebraMap R[X] W.FunctionField X := by
  rw [genericX_def, WeierstrassCurve.Affine.CoordinateRing.mk_C_eq_algebraMap,
    IsScalarTower.algebraMap_apply R[X] W.CoordinateRing W.FunctionField]

/-- **Evaluating at the generic point is reduction modulo the Weierstrass relation.** A bivariate
polynomial over `R`, pushed to the function field and evaluated at `(genericX, genericY)`, is the
image of its class in the coordinate ring.

This is the workhorse: it converts any polynomial expression at the generic point into the image
of a coordinate-ring element, where the ring's own API applies. -/
theorem evalEval_genericX_genericY (p : R[X][Y]) :
    (p.map (mapRingHom (algebraMap R W.FunctionField))).evalEval W.genericX W.genericY =
      algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W p) :=
  (CoordinateRing.algHom_mk_eq_evalEval
    (IsScalarTower.toAlgHom R W.CoordinateRing W.FunctionField) p).symm

/-- **The generic coordinate functions satisfy the equation of the curve.** `(X, Y)` satisfies
the equation of `W` base-changed to the function field, because the Weierstrass polynomial is
precisely what the coordinate ring quotients out. -/
theorem equation_genericX_genericY :
    (W⁄W.FunctionField).toAffine.Equation W.genericX W.genericY :=
  CoordinateRing.equation_of_algHom
    (IsScalarTower.toAlgHom R W.CoordinateRing W.FunctionField)

/-- The generic `y`-coordinate is a root of the Weierstrass polynomial.

This is AINTLIB's `root_aeval_polynomial_map` of `projects/HasseWeil/HasseWeil/Ramification.lean`
at revision `513e83879e2f`, Apache-2.0, stated over `R[X]` rather than over a fraction field. -/
@[simp]
theorem aeval_genericY_polynomial : aeval (genericY W) W.polynomial = 0 := by
  rw [genericY_def, AdjoinRoot.mk_X]
  exact AdjoinRoot.aeval_algHom_eq_zero W.polynomial
    (IsScalarTower.toAlgHom R[X] W.CoordinateRing W.FunctionField)

/-- The generic `y`-coordinate is integral over any commutative `R[X]`-algebra `L` mapping
compatibly to the function field. `L` need not embed: no injectivity is assumed. -/
theorem isIntegral_genericY (L : Type*) [CommRing L] [Algebra R[X] L]
    [Algebra L W.FunctionField] [IsScalarTower R[X] L W.FunctionField] :
    IsIntegral L (genericY W) :=
  ⟨_, W.monic_polynomial.map _, by
    rw [← aeval_def, Polynomial.aeval_map_algebraMap]
    exact aeval_genericY_polynomial W⟩

/-- **The image of `R[X]` in the function field consists of the polynomials in the generic
`x`-coordinate.** -/
theorem algebraMap_eq_aeval_genericX (p : R[X]) :
    algebraMap R[X] W.FunctionField p = aeval W.genericX p := by
  have h : IsScalarTower.toAlgHom R R[X] W.FunctionField = aeval W.genericX := by
    apply Polynomial.algHom_ext
    rw [aeval_X, IsScalarTower.coe_toAlgHom', ← genericX_eq_algebraMap]
  exact congr($h p)

/-- **Scalars pass through the inclusion of the coordinate ring into the function field.** An
`R[X]`-scalar acting on `R[W]` becomes multiplication by its image in `R(W)`. -/
theorem algebraMap_smul_eq_mul (r : R[X]) (z : W.CoordinateRing) :
    algebraMap W.CoordinateRing W.FunctionField (r • z) =
      algebraMap R[X] W.FunctionField r * algebraMap W.CoordinateRing W.FunctionField z := by
  -- `LinearMap.map_algebraMap_mul` is the general fact; it is a term rather than a usable
  -- rewrite here, because the goal carries the `RingHom` coercion of `algebraMap` and the
  -- lemma the `LinearMap` one. This lemma is that instantiation, in `rw`-usable form.
  simpa [Algebra.smul_def] using LinearMap.map_algebraMap_mul
    (IsScalarTower.toAlgHom R[X] W.CoordinateRing W.FunctionField).toLinearMap z r

/-- **The coordinate ring, read inside the function field, lies in the subalgebra generated by the
generic point.** Every affine function of `W` is a polynomial in `x` and `y` over `R`, so its
image lies in the `R`-subalgebra `R[x, y]` of `R(W)`. The proof uses that `R[W]` is free of rank
two over `R[X]` with basis `{1, y}`. -/
theorem algebraMap_mem_adjoin_genericX_genericY (z : W.CoordinateRing) :
    algebraMap W.CoordinateRing W.FunctionField z ∈
      Algebra.adjoin R ({W.genericX, W.genericY} : Set W.FunctionField) := by
  have hgen (r : R[X]) : algebraMap R[X] W.FunctionField r ∈
      Algebra.adjoin R ({W.genericX, W.genericY} : Set W.FunctionField) := by
    have hr : aeval W.genericX r ∈ Algebra.adjoin R ({W.genericX} : Set W.FunctionField) := by
      rw [Algebra.adjoin_singleton_eq_range_aeval]
      exact ⟨r, rfl⟩
    rw [algebraMap_eq_aeval_genericX]
    exact Algebra.adjoin_mono (by simp) hr
  obtain ⟨p, q, rfl⟩ := CoordinateRing.exists_smul_basis_eq z
  rw [map_add, algebraMap_smul_eq_mul, algebraMap_smul_eq_mul, map_one, mul_one]
  refine add_mem (hgen p) (mul_mem (hgen q) ?_)
  rw [← genericY_def]
  exact Algebra.subset_adjoin (Set.mem_insert_of_mem _ rfl)

section IsElliptic

variable [Nontrivial R] [W.IsElliptic]

/-- The generic coordinates are nonsingular, so they define an affine point of the base-changed
curve.

Beyond the ambient `[CommRing R]` this needs `[W.IsElliptic]`, which turns the equation into
nonsingularity, and `[Nontrivial R]`, which is what supplies `Nontrivial W.FunctionField` to
`equation_iff_nonsingular`. -/
theorem nonsingular_genericX_genericY :
    (W⁄W.FunctionField).toAffine.Nonsingular W.genericX W.genericY := by
  exact equation_iff_nonsingular.mp (equation_genericX_genericY W)

/-- **The generic point of `W`**: the tautological point of `W` with coordinates in its own
function field. -/
noncomputable def genericPoint : (W⁄W.FunctionField).toAffine.Point :=
  .some _ _ (nonsingular_genericX_genericY W)

/-- The generic point is the affine point whose coordinates are `genericX W` and `genericY W`. -/
theorem genericPoint_eq_some : genericPoint W =
    .some (genericX W) (genericY W) (nonsingular_genericX_genericY W) := (rfl)

@[simp]
theorem xCoord_genericPoint : Point.xCoord (genericPoint W) = genericX W :=
  Point.xCoord_some _

@[simp]
theorem yCoord_genericPoint : Point.yCoord (genericPoint W) = genericY W :=
  Point.yCoord_some _

end IsElliptic

section Field

variable {F : Type*} [Field F] (W : _root_.WeierstrassCurve.Affine F)

/-- **The coordinate function `x` is transcendental over the base field.** -/
theorem transcendental_genericX : Transcendental F (genericX W) := by
  rw [genericX_eq_algebraMap]
  exact (transcendental_algebraMap_iff
    (FaithfulSMul.algebraMap_injective F[X] W.FunctionField)).2 (Polynomial.transcendental_X F)

/-- **The coordinate function `x` takes no constant value**, being transcendental. -/
theorem genericX_ne_algebraMap (x₁ : F) : genericX W ≠ algebraMap F W.FunctionField x₁ :=
  fun hc ↦ transcendental_genericX W (hc ▸ isAlgebraic_algebraMap _)

/-- `W_Y` stays nonzero in the coordinate ring: its degree is below `deg W`, so it is not a
multiple of `W`. -/
private lemma mk_polynomialY_ne_zero [W.IsElliptic] :
    WeierstrassCurve.Affine.CoordinateRing.mk W W.polynomialY ≠ 0 :=
  AdjoinRoot.mk_ne_zero_of_natDegree_lt monic_polynomial
    (polynomialY_ne_zero W.isUnit_Δ.ne_zero) <| by
    rw [natDegree_polynomial, WeierstrassCurve.Affine.polynomialY]
    have : (Polynomial.C (Polynomial.C (2 : F)) * (Y : F[X][Y])).natDegree ≤ 1 :=
      Polynomial.natDegree_mul_le.trans
        (by simp [Polynomial.natDegree_C, Polynomial.natDegree_X])
    exact Nat.lt_of_le_of_lt (Polynomial.natDegree_add_le _ _)
      (by rw [Polynomial.natDegree_C]; omega)

/-- **The partial derivative `W_Y` is nonzero at the generic point** of an elliptic curve. -/
@[simp]
theorem evalEval_polynomialY_genericX_genericY_ne_zero [W.IsElliptic] :
    (W⁄W.FunctionField).toAffine.polynomialY.evalEval (genericX W) (genericY W) ≠ 0 := by
  have h := evalEval_genericX_genericY W W.polynomialY
  rw [← WeierstrassCurve.Affine.map_polynomialY] at h
  have h' :
      (W⁄W.FunctionField).toAffine.polynomialY.evalEval (genericX W) (genericY W) =
        algebraMap W.CoordinateRing W.FunctionField (CoordinateRing.mk W W.polynomialY) := by
    simpa only [WeierstrassCurve.baseChange] using h
  rw [h']
  exact fun hz => mk_polynomialY_ne_zero W
    ((IsFractionRing.injective W.CoordinateRing W.FunctionField).eq_iff.mp
      (hz.trans (map_zero _).symm))

/-- **An `F`-embedding of the function field into a field extension is determined by the image of
the generic point.** The generic point's two coordinates generate the function field over `F`, so
an embedding is recoverable from the point it induces. -/
theorem map_genericPoint_injective [W.IsElliptic] {Ω : Type*} [Field Ω] [Algebra F Ω]
    [DecidableEq Ω] :
    Function.Injective fun σ : W.FunctionField →ₐ[F] Ω ↦ Point.map σ (genericPoint W) := by
  intro σ τ h
  have hx : σ (genericX W) = τ (genericX W) := by
    simpa only [Point.xCoord_map, xCoord_genericPoint] using congrArg Point.xCoord h
  have hy : σ (genericY W) = τ (genericY W) := by
    simpa only [Point.yCoord_map, yCoord_genericPoint] using congrArg Point.yCoord h
  have key : σ.comp (IsScalarTower.toAlgHom F W.CoordinateRing W.FunctionField) =
      τ.comp (IsScalarTower.toAlgHom F W.CoordinateRing W.FunctionField) := by
    refine CoordinateRing.algHom_ext ?_ ?_
    · simpa [genericX_def] using hx
    · simpa [genericY_def] using hy
  refine AlgHom.toRingHom_injective
    (IsFractionRing.ringHom_ext (A := W.CoordinateRing) fun a ↦ ?_)
  exact congrArg (fun f : W.CoordinateRing →ₐ[F] Ω ↦ f a) key

/-- **An embedding is determined by the rational point it displaces the generic point by.** If
each index `i` carries a rational point whose base change is `e i`'s displacement of the generic
point from a fixed embedding `σ₀`, then that point determines `e i`.

This is the injectivity step shared by the embedding counts of the isogenies whose kernels are
counted this way: they differ in *why* the displacement is rational, not in this step. -/
theorem eq_of_baseChange_eq_sub_map_genericPoint [W.IsElliptic] [DecidableEq F] {Ω : Type*}
    [Field Ω] [Algebra F Ω] [DecidableEq Ω] {ι : Type*} (e : ι → (W.FunctionField →ₐ[F] Ω))
    (σ₀ : W.FunctionField →ₐ[F] Ω) {f : ι → (W⁄F).toAffine.Point}
    (hf : ∀ i, Point.baseChange (W' := W) F Ω (f i) =
      Point.map (e i) (genericPoint W) - Point.map σ₀ (genericPoint W))
    {i j : ι} (h : f i = f j) : e i = e j := by
  have h2 : Point.map (e i) (genericPoint W) - Point.map σ₀ (genericPoint W) =
      Point.map (e j) (genericPoint W) - Point.map σ₀ (genericPoint W) := by
    rw [← hf i, ← hf j, h]
  exact map_genericPoint_injective W (sub_left_inj.1 h2)

end Field

end WeierstrassCurve.Affine

end
