/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.RayClass.Modulus

import TauCeti.RingTheory.ClassGroup.Basic

/-!
# The ray class group of a modulus

Let `𝔪` be a modulus of a number field `K`.  The **ray** of `𝔪` is the subgroup of principal
fractional ideals generated by the elements of `Kˣ` congruent to one modulo `𝔪`, and the **ray
class group** `RayClassGroup 𝔪` is the quotient of the group `idealsPrimeTo 𝔪` of invertible
fractional ideals prime to the finite part of `𝔪` by that ray.

The ray really is a subgroup of `idealsPrimeTo 𝔪`, and not merely of all invertible fractional
ideals: an element congruent to one is a unit at every prime dividing the finite part of `𝔪`
(`IsCongrOne.valuation_eq_one`), so its principal ideal has vanishing multiplicity there.  That is
the content of `TauCeti.GlobalNumberFields.rayHom`, from which the ray is obtained as a range.

The class of an ideal is defined on the monoid `integralIdealsPrimeTo 𝔪` of nonzero integral ideals
prime to the finite part, never on all of `Ideal (𝓞 K)`: an ideal sharing a prime with the finite
part has no ray class, and carrying the coprimality proof in the argument makes multiplicativity
literally `map_mul`.

For the trivial modulus the congruence condition is empty, and the ray class group is the ordinary
class group (`oneEquivClassGroup`).

## Main definitions

* `TauCeti.GlobalNumberFields.principalIdealPrimeTo`: the principal fractional ideals whose
  generators are units at the finite part.
* `TauCeti.GlobalNumberFields.rayHom`, `TauCeti.GlobalNumberFields.ray`: the principal ideals of
  the elements congruent to one, and the subgroup they form.
* `TauCeti.GlobalNumberFields.idealsPrimeToClassGroup`: the ordinary ideal class of an invertible
  fractional ideal prime to a modulus.
* `TauCeti.GlobalNumberFields.RayClassGroup`: the quotient of `idealsPrimeTo 𝔪` by the ray, with
  `TauCeti.GlobalNumberFields.rayClassMk` and the universal property
  `TauCeti.GlobalNumberFields.rayClassLift`.
* `TauCeti.GlobalNumberFields.idealClass`: the ray class of an integral ideal prime to `𝔪`, as a
  monoid homomorphism out of `integralIdealsPrimeTo 𝔪`.
* `TauCeti.GlobalNumberFields.classMap`: the transition map, running from the ray class group of a
  larger modulus to that of a divisor of it.

## Main results

* `TauCeti.GlobalNumberFields.toPrincipalIdeal_mem_idealsPrimeTo_iff`: a principal fractional ideal
  is prime to the modulus exactly when its generator is a unit at every prime dividing the finite
  part, with `TauCeti.GlobalNumberFields.IsCongrOne.toPrincipalIdeal_mem_idealsPrimeTo` the
  consequence for an element congruent to one.
* `TauCeti.GlobalNumberFields.idealsPrimeTo_eq_top`: every invertible fractional ideal is prime
  to a modulus whose support is empty, so `TauCeti.GlobalNumberFields.idealsPrimeToEquiv`
  identifies the two carriers there.
* `TauCeti.GlobalNumberFields.idealClass_apply`: the ray class of an integral ideal is the ray
  class of the fractional ideal it generates.
* `TauCeti.GlobalNumberFields.idealClass_mul`: taking the ray class of an integral ideal respects
  multiplication.
* `TauCeti.GlobalNumberFields.idealClass_eq_one_iff`: an ideal has trivial ray class exactly when
  it is generated, as a fractional ideal, by an element of `Kˣ` congruent to one modulo `𝔪`.
* `TauCeti.GlobalNumberFields.classMap_comp_classMap` and
  `TauCeti.GlobalNumberFields.classMap_comp_idealClass`: the transition maps compose along a tower
  of moduli, and carry the class of an integral ideal to the class of the same ideal.  Both are
  equalities of homomorphisms, with the pointwise forms `classMap_classMap` and
  `classMap_idealClass` derived from them.  The transition map from a modulus to itself is the
  identity (`TauCeti.GlobalNumberFields.classMap_refl`).
* `TauCeti.GlobalNumberFields.oneEquivClassGroup`: at the trivial modulus the ray class group is
  the class group of `𝓞 K`, carrying a ray class to the class of the same fractional ideal
  (`TauCeti.GlobalNumberFields.oneEquivClassGroup_rayClassMk`).

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1.
* S. Lang, *Algebraic Number Theory*, Chapter VI, §1.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.GlobalNumberFields

variable {K : Type*} [Field K] [NumberField K]

/-- **A principal fractional ideal is prime to the modulus exactly when its generator is a unit at
every prime dividing the finite part.** -/
theorem toPrincipalIdeal_mem_idealsPrimeTo_iff {𝔪 : Modulus K} {x : Kˣ} :
    toPrincipalIdeal (𝓞 K) K x ∈ idealsPrimeTo 𝔪 ↔ x ∈ primeToSubgroup 𝔪 := by
  rw [NumberFieldArithmetic.mem_idealsAway_iff, mem_primeToSubgroup]
  refine ⟨fun h v hv ↦ ?_, fun h v hv ↦ ?_⟩
  · have hcount := h v ((Modulus.mem_support_iff _ _).mpr hv)
    rw [FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation K v x, neg_eq_zero] at hcount
    have hne : v.valuation K (x : K) ≠ 0 := (Valuation.ne_zero_iff _).mpr x.ne_zero
    rw [← WithZero.exp_log hne, hcount, WithZero.exp_zero]
  · rw [FractionalIdeal.count_toPrincipalIdeal_eq_neg_log_valuation K v x,
      h v ((Modulus.mem_support_iff _ _).mp hv), WithZero.log_one, neg_zero]

/-- **The principal ideal of an element congruent to one is prime to the modulus.**  At a prime
dividing the finite part such an element is a unit, so the multiplicity of its principal ideal
vanishes there. -/
theorem IsCongrOne.toPrincipalIdeal_mem_idealsPrimeTo {𝔪 : Modulus K} {x : Kˣ}
    (hx : IsCongrOne 𝔪 x) : toPrincipalIdeal (𝓞 K) K x ∈ idealsPrimeTo 𝔪 :=
  toPrincipalIdeal_mem_idealsPrimeTo_iff.mpr
    (congruenceSubgroup_le_primeToSubgroup 𝔪 (mem_congruenceSubgroup.mpr hx))

/-- The principal fractional ideal of an element that is a unit at every prime dividing the
finite part of `m`, viewed as an element of `idealsPrimeTo m`. -/
noncomputable def principalIdealPrimeTo (m : Modulus K) :
    primeToSubgroup m →* idealsPrimeTo m :=
  MonoidHom.codRestrict
    ((toPrincipalIdeal (RingOfIntegers K) K).comp (primeToSubgroup m).subtype)
    (idealsPrimeTo m) fun x ↦ toPrincipalIdeal_mem_idealsPrimeTo_iff.mpr x.2

/-- `principalIdealPrimeTo` does not change the underlying principal fractional ideal. -/
@[simp] theorem coe_principalIdealPrimeTo (m : Modulus K) (x : primeToSubgroup m) :
    ((principalIdealPrimeTo m x : idealsPrimeTo m) :
        (FractionalIdeal (RingOfIntegers K)⁰ K)ˣ) =
      toPrincipalIdeal (RingOfIntegers K) K (x : Kˣ) := by
  simp only [principalIdealPrimeTo, MonoidHom.codRestrict_apply, MonoidHom.comp_apply,
    Subgroup.subtype_apply]

/-- The homomorphism sending an element of `Kˣ` congruent to one modulo `𝔪` to its principal
fractional ideal, viewed inside the ideals prime to `𝔪`. -/
noncomputable def rayHom (𝔪 : Modulus K) :
    congruenceSubgroup 𝔪 →* idealsPrimeTo 𝔪 :=
  MonoidHom.codRestrict ((toPrincipalIdeal (𝓞 K) K).comp (congruenceSubgroup 𝔪).subtype) _
    fun x ↦ (mem_congruenceSubgroup.mp x.2).toPrincipalIdeal_mem_idealsPrimeTo

@[simp] theorem coe_rayHom (𝔪 : Modulus K) (x : congruenceSubgroup 𝔪) :
    ((rayHom 𝔪 x : idealsPrimeTo 𝔪) : (FractionalIdeal (𝓞 K)⁰ K)ˣ) =
      toPrincipalIdeal (𝓞 K) K (x : Kˣ) := (rfl)

/-- **The ray of a modulus**: the subgroup of `idealsPrimeTo 𝔪` consisting of the principal
fractional ideals of the elements of `Kˣ` congruent to one modulo `𝔪`. -/
noncomputable def ray (𝔪 : Modulus K) : Subgroup (idealsPrimeTo 𝔪) :=
  (rayHom 𝔪).range

@[simp] theorem mem_ray_iff {𝔪 : Modulus K} {I : idealsPrimeTo 𝔪} :
    I ∈ ray 𝔪 ↔ ∃ x : Kˣ, IsCongrOne 𝔪 x ∧
      toPrincipalIdeal (𝓞 K) K x = (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) := by
  rw [ray, MonoidHom.mem_range]
  refine ⟨fun ⟨x, hx⟩ ↦ ⟨x, mem_congruenceSubgroup.mp x.2, ?_⟩, fun ⟨x, hx, hxI⟩ ↦ ?_⟩
  · rw [← coe_rayHom 𝔪 x, hx]
  · exact ⟨⟨x, mem_congruenceSubgroup.mpr hx⟩, Subtype.ext (Units.ext (by rw [coe_rayHom, hxI]))⟩

/-- **The ordinary ideal class of an invertible fractional ideal prime to a modulus.** This is the
canonical map from `idealsPrimeTo 𝔪` to the ordinary class group; it descends to the right-hand
transition in the ray-class exact sequence. -/
noncomputable def idealsPrimeToClassGroup (𝔪 : Modulus K) :
    idealsPrimeTo 𝔪 →* ClassGroup (𝓞 K) :=
  (ClassGroup.mk K).comp (idealsPrimeTo 𝔪).subtype

@[simp] theorem idealsPrimeToClassGroup_apply (𝔪 : Modulus K) (I : idealsPrimeTo 𝔪) :
    idealsPrimeToClassGroup 𝔪 I =
      ClassGroup.mk K (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :=
  by simp only [idealsPrimeToClassGroup, MonoidHom.comp_apply, Subgroup.subtype_apply]

/-- The principal fractional ideals prime to a modulus are exactly the kernel of the map to the
ordinary ideal class group. -/
theorem range_principalIdealPrimeTo (m : Modulus K) :
    (principalIdealPrimeTo m).range = (idealsPrimeToClassGroup m).ker := by
  ext I
  rw [MonoidHom.mem_range, MonoidHom.mem_ker, idealsPrimeToClassGroup_apply,
    ClassGroup.mk_eq_one_iff_exists]
  constructor
  · rintro ⟨x, rfl⟩
    exact ⟨(x : Kˣ), coe_principalIdealPrimeTo m x⟩
  · rintro ⟨x, hx⟩
    refine ⟨⟨x, toPrincipalIdeal_mem_idealsPrimeTo_iff.mp (hx ▸ I.2)⟩, ?_⟩
    apply Subtype.ext
    apply Units.ext
    rw [coe_principalIdealPrimeTo, hx]

/-- **The ray class group of a modulus**: the invertible fractional ideals prime to the finite part
of `𝔪`, modulo the principal ideals of the elements congruent to one modulo `𝔪`. -/
def RayClassGroup (𝔪 : Modulus K) : Type _ :=
  idealsPrimeTo 𝔪 ⧸ ray 𝔪

noncomputable instance (𝔪 : Modulus K) : CommGroup (RayClassGroup 𝔪) :=
  inferInstanceAs (CommGroup (idealsPrimeTo 𝔪 ⧸ ray 𝔪))

noncomputable instance (𝔪 : Modulus K) : Inhabited (RayClassGroup 𝔪) := ⟨1⟩

/-- The ray class of an invertible fractional ideal prime to the modulus. -/
noncomputable def rayClassMk (𝔪 : Modulus K) :
    idealsPrimeTo 𝔪 →* RayClassGroup 𝔪 :=
  QuotientGroup.mk' (ray 𝔪)

theorem rayClassMk_surjective (𝔪 : Modulus K) : Function.Surjective (rayClassMk 𝔪) :=
  QuotientGroup.mk'_surjective _

@[simp] theorem rayClassMk_eq_one_iff {𝔪 : Modulus K} {I : idealsPrimeTo 𝔪} :
    rayClassMk 𝔪 I = 1 ↔ I ∈ ray 𝔪 :=
  QuotientGroup.eq_one_iff I

/-- **The universal property of the ray class group.**  A homomorphism out of the invertible
fractional ideals prime to `𝔪` which is trivial on the ray factors, uniquely, through the ray
class group. -/
noncomputable def rayClassLift {M : Type*} [Monoid M] {𝔪 : Modulus K} (φ : idealsPrimeTo 𝔪 →* M)
    (h : ray 𝔪 ≤ φ.ker) : RayClassGroup 𝔪 →* M :=
  QuotientGroup.lift (ray 𝔪) φ h

@[simp] theorem rayClassLift_rayClassMk {M : Type*} [Monoid M] {𝔪 : Modulus K}
    (φ : idealsPrimeTo 𝔪 →* M) (h : ray 𝔪 ≤ φ.ker) (I : idealsPrimeTo 𝔪) :
    rayClassLift φ h (rayClassMk 𝔪 I) = φ I := (rfl)

/-- **The factorization through the ray class group is unique**: a homomorphism out of
`RayClassGroup 𝔪` is determined by its composition with `rayClassMk`. -/
theorem rayClassLift_unique {M : Type*} [Monoid M] {𝔪 : Modulus K} (φ : idealsPrimeTo 𝔪 →* M)
    (h : ray 𝔪 ≤ φ.ker) {ψ : RayClassGroup 𝔪 →* M} (hψ : ψ.comp (rayClassMk 𝔪) = φ) :
    ψ = rayClassLift φ h := by
  refine MonoidHom.ext fun c ↦ ?_
  obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔪 c
  rw [rayClassLift_rayClassMk, ← hψ, MonoidHom.comp_apply]

/-- The kernel of `rayClassLift φ h` is the image under `rayClassMk 𝔪` of `φ.ker`.  This exposes
`QuotientGroup.ker_lift` through the module-opaque `RayClassGroup` representation. -/
theorem ker_rayClassLift {M : Type*} [Group M] {𝔪 : Modulus K}
    (φ : idealsPrimeTo 𝔪 →* M) (h : ray 𝔪 ≤ φ.ker) :
    (rayClassLift φ h).ker = Subgroup.map (rayClassMk 𝔪) φ.ker :=
  QuotientGroup.ker_lift (ray 𝔪) φ h

/-- **The ray class of an integral ideal prime to the modulus.**  The domain is the monoid of
nonzero integral ideals prime to the finite part of `𝔪`, never `Ideal (𝓞 K)`: an ideal sharing a
prime with the finite part, or the zero ideal, has no ray class, and a version totalized over
arbitrary ideals would hand back a junk class there.  Carrying the coprimality proof in the
argument also makes multiplicativity `map_mul` rather than a law with side conditions. -/
noncomputable def idealClass (𝔪 : Modulus K) :
    integralIdealsPrimeTo 𝔪 →* RayClassGroup 𝔪 :=
  (rayClassMk 𝔪).comp (NumberFieldArithmetic.integralIdealsAwayHom 𝔪.support)

/-- The ray class of a product is the product of the ray classes. -/
@[simp] theorem idealClass_mul (𝔪 : Modulus K) (I J : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 (I * J) = idealClass 𝔪 I * idealClass 𝔪 J :=
  map_mul _ _ _

/-- The ray class of an integral ideal is the ray class of the fractional ideal it generates. -/
theorem idealClass_apply (𝔪 : Modulus K) (I : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 I = rayClassMk 𝔪 (NumberFieldArithmetic.integralIdealsAwayHom 𝔪.support I) :=
  (rfl)

/-- **The intrinsic triviality criterion for a ray class.**  An integral ideal prime to `𝔪` has
trivial ray class exactly when it is generated as a *fractional* ideal by an element of `Kˣ` that
is congruent to one modulo `𝔪`; the congruence already carries both the finite conditions and the
positivity at the real places of `𝔪`. -/
@[simp] theorem idealClass_eq_one_iff {𝔪 : Modulus K} (I : integralIdealsPrimeTo 𝔪) :
    idealClass 𝔪 I = 1 ↔ ∃ x : Kˣ, IsCongrOne 𝔪 x ∧
      ((I : Ideal (𝓞 K)) : FractionalIdeal (𝓞 K)⁰ K) =
        FractionalIdeal.spanSingleton (𝓞 K)⁰ (x : K) := by
  rw [idealClass, MonoidHom.comp_apply, rayClassMk_eq_one_iff, mem_ray_iff]
  refine exists_congr fun x ↦ and_congr_right fun _ ↦ ?_
  rw [Units.ext_iff, coe_toPrincipalIdeal,
    NumberFieldArithmetic.coe_integralIdealsAwayHom 𝔪.support I]
  exact eq_comm

/-! ### The transition map between ray class groups -/

/-- **The transition map between ray class groups.**  For `𝔪 ∣ 𝔫` it runs from the *larger* modulus
to the smaller one: an invertible fractional ideal prime to `𝔫` is prime to `𝔪`, and an element
congruent to one modulo `𝔫` is congruent to one modulo `𝔪`, so the ray of `𝔫` lands in the ray
of `𝔪`. -/
noncomputable def classMap {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) :
    RayClassGroup 𝔫 →* RayClassGroup 𝔪 :=
  QuotientGroup.map (ray 𝔫) (ray 𝔪)
    (NumberFieldArithmetic.idealsAwayInclusion (Modulus.support_mono h)) <| by
      intro J hJ
      obtain ⟨x, hx, hxJ⟩ := mem_ray_iff.mp hJ
      refine Subgroup.mem_comap.mpr (mem_ray_iff.mpr ⟨x, IsCongrOne.mono h hx, ?_⟩)
      rw [NumberFieldArithmetic.coe_idealsAwayInclusion, hxJ]

@[simp] theorem classMap_rayClassMk {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) (I : idealsPrimeTo 𝔫) :
    classMap h (rayClassMk 𝔫 I) =
      rayClassMk 𝔪 (NumberFieldArithmetic.idealsAwayInclusion (Modulus.support_mono h) I) := (rfl)

/-- **The transition map at a modulus and itself is the identity**, as an equality of
homomorphisms. -/
theorem classMap_refl (𝔪 : Modulus K) :
    classMap (Modulus.dvd_refl 𝔪) = MonoidHom.id (RayClassGroup 𝔪) := by
  refine MonoidHom.ext fun c ↦ ?_
  obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔪 c
  rw [classMap_rayClassMk, MonoidHom.id_apply]
  congr 1
  exact Subtype.ext (Units.ext (by simp [NumberFieldArithmetic.coe_idealsAwayInclusion]))

/-- The transition map at a modulus and itself is the identity. -/
@[simp] theorem classMap_refl_apply (𝔪 : Modulus K) (c : RayClassGroup 𝔪) :
    classMap (Modulus.dvd_refl 𝔪) c = c := by
  rw [classMap_refl, MonoidHom.id_apply]

/-- **The transition maps compose along a tower of moduli**, as an equality of homomorphisms. -/
theorem classMap_comp_classMap {𝔪 𝔫 𝔭 : Modulus K} (h₁ : 𝔪 ∣ 𝔫) (h₂ : 𝔫 ∣ 𝔭) :
    (classMap h₁).comp (classMap h₂) = classMap (Modulus.dvd_trans h₁ h₂) := by
  refine MonoidHom.ext fun c ↦ ?_
  obtain ⟨I, rfl⟩ := rayClassMk_surjective 𝔭 c
  rw [MonoidHom.comp_apply, classMap_rayClassMk, classMap_rayClassMk, classMap_rayClassMk]
  congr 1
  exact Subtype.ext (Units.ext (by simp [NumberFieldArithmetic.coe_idealsAwayInclusion]))

/-- The transition maps compose along a tower of moduli. -/
@[simp] theorem classMap_classMap {𝔪 𝔫 𝔭 : Modulus K} (h₁ : 𝔪 ∣ 𝔫) (h₂ : 𝔫 ∣ 𝔭)
    (c : RayClassGroup 𝔭) :
    classMap h₁ (classMap h₂ c) = classMap (Modulus.dvd_trans h₁ h₂) c := by
  rw [← MonoidHom.comp_apply, classMap_comp_classMap]

/-- **The ray class of an integral ideal is compatible with the transition maps**, as an equality
of homomorphisms out of `integralIdealsPrimeTo 𝔫`. -/
theorem classMap_comp_idealClass {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) :
    (classMap h).comp (idealClass 𝔫) =
      (idealClass 𝔪).comp (integralIdealsPrimeToInclusion h) := by
  refine MonoidHom.ext fun I ↦ ?_
  rw [MonoidHom.comp_apply, MonoidHom.comp_apply, idealClass, MonoidHom.comp_apply,
    classMap_rayClassMk, idealClass, MonoidHom.comp_apply]
  congr 1
  exact Subtype.ext (Units.ext (by simp [NumberFieldArithmetic.coe_integralIdealsAwayHom]))

/-- **The ray class of an integral ideal is compatible with the transition maps.** -/
@[simp] theorem classMap_idealClass {𝔪 𝔫 : Modulus K} (h : 𝔪 ∣ 𝔫) (I : integralIdealsPrimeTo 𝔫) :
    classMap h (idealClass 𝔫 I) = idealClass 𝔪 (integralIdealsPrimeToInclusion h I) := by
  rw [← MonoidHom.comp_apply, classMap_comp_idealClass, MonoidHom.comp_apply]

/-! ### Moduli with unit finite part -/

/-- **Every invertible fractional ideal is prime to a modulus with empty support**: no prime
divides the finite part, so no multiplicity is required to vanish.  The trivial modulus and the
narrow modulus are the two moduli of this kind. -/
theorem idealsPrimeTo_eq_top {𝔪 : Modulus K} (h : 𝔪.support = ∅) : idealsPrimeTo 𝔪 = ⊤ :=
  Subgroup.eq_top_iff' _ |>.mpr fun _ ↦
    NumberFieldArithmetic.mem_idealsAway_iff.mpr fun v hv ↦
      absurd (h ▸ hv) (Finset.notMem_empty v)

/-- The ideals prime to a modulus with empty support are all the invertible fractional ideals. -/
noncomputable def idealsPrimeToEquiv {𝔪 : Modulus K} (h : 𝔪.support = ∅) :
    idealsPrimeTo 𝔪 ≃* (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  (MulEquiv.subgroupCongr (idealsPrimeTo_eq_top h)).trans Subgroup.topEquiv

@[simp] theorem idealsPrimeToEquiv_apply {𝔪 : Modulus K} (h : 𝔪.support = ∅)
    (I : idealsPrimeTo 𝔪) :
    idealsPrimeToEquiv h I = (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) := (rfl)

/-- Under the identification with all invertible fractional ideals, a fractional ideal prime to a
modulus with empty support keeps its underlying ideal. -/
@[simp] theorem idealsPrimeToEquiv_symm_apply {𝔪 : Modulus K} (h : 𝔪.support = ∅)
    (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    (((idealsPrimeToEquiv h).symm I : idealsPrimeTo 𝔪) :
      (FractionalIdeal (𝓞 K)⁰ K)ˣ) = I := (rfl)

/-! ### The trivial modulus -/

/-- The ray of the trivial modulus is the group of all principal fractional ideals. -/
theorem map_ray_one :
    Subgroup.map (idealsPrimeToEquiv (Modulus.support_one (K := K)) :
        idealsPrimeTo (Modulus.one K) →* (FractionalIdeal (𝓞 K)⁰ K)ˣ)
      (ray (Modulus.one K)) = (toPrincipalIdeal (𝓞 K) K).range := by
  ext I
  rw [Subgroup.mem_map, MonoidHom.mem_range]
  refine ⟨fun ⟨J, hJ, hJI⟩ ↦ ?_, fun ⟨x, hx⟩ ↦ ?_⟩
  · obtain ⟨x, _, hxJ⟩ := mem_ray_iff.mp hJ
    exact ⟨x, by rw [hxJ, ← hJI, MonoidHom.coe_ofClass, idealsPrimeToEquiv_apply]⟩
  · exact ⟨⟨I, idealsPrimeTo_eq_top (Modulus.support_one (K := K)) ▸ Subgroup.mem_top I⟩,
      mem_ray_iff.mpr ⟨x, isCongrOne_one x, hx⟩, rfl⟩

/-- **At the trivial modulus the ray class group is the ordinary class group.**  This is a named
equivalence, not a definitional equality: the ray class group is a quotient of the ideals prime to
the empty set of primes, and the class group is a quotient of all invertible fractional ideals. -/
noncomputable def oneEquivClassGroup :
    RayClassGroup (Modulus.one K) ≃* ClassGroup (𝓞 K) :=
  (QuotientGroup.congr (ray (Modulus.one K)) (toPrincipalIdeal (𝓞 K) K).range
    (idealsPrimeToEquiv Modulus.support_one) map_ray_one).trans
    (ClassGroup.equiv (K := K)).symm

/-- **The equivalence at the trivial modulus carries a ray class to the class of the same
fractional ideal.** -/
@[simp] theorem oneEquivClassGroup_rayClassMk (I : idealsPrimeTo (Modulus.one K)) :
    oneEquivClassGroup (rayClassMk (Modulus.one K) I) =
      ClassGroup.mk K (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) := by
  have htrans : oneEquivClassGroup (rayClassMk (Modulus.one K) I) =
      (ClassGroup.equiv (K := K)).symm
        (QuotientGroup.congr (ray (Modulus.one K)) (toPrincipalIdeal (𝓞 K) K).range
          (idealsPrimeToEquiv Modulus.support_one) map_ray_one
          (QuotientGroup.mk' (ray (Modulus.one K)) I)) :=
    MulEquiv.trans_apply _ _ _
  have hmap : Units.mapEquiv (MulEquiv.refl (FractionalIdeal (𝓞 K)⁰ K))
      (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) = (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :=
    Units.ext (by rw [Units.coe_mapEquiv, MulEquiv.refl_apply])
  rw [htrans, QuotientGroup.congr_mk', idealsPrimeToEquiv_apply, MulEquiv.symm_apply_eq,
    ClassGroup.equiv_mk]
  simp only [QuotientGroup.mk'_apply, FractionalIdeal.canonicalEquiv_self,
    RingEquiv.coe_mulEquiv_refl, hmap]

end TauCeti.GlobalNumberFields
