/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import TauCeti.RingTheory.Huber.LocalizationTopology.Completion
public import TauCeti.Topology.Algebra.Nonarchimedean.Completion.RingHom

/-!
# Restriction maps for a refined presentation

The structure presheaf of an adic space sends a rational subset `R(T/s)` to `A⟨T/s⟩` and a
containment `R(T'/s') ⊆ R(T/s)` to a restriction map `A⟨T/s⟩ → A⟨T'/s'⟩` (*Adic Spaces*,
arXiv:1910.05934v1, §8.1–§8.2). This file builds such a map whenever the target presentation
**refines** the source one in the elementary sense that its denominator is a multiple
`s'' = s * r` of the source denominator, and each `t * r`, for `t ∈ T`, is one of its numerators.

Under those hypotheses both conditions of the universal property of `A⟨T/s⟩` hold outright. The
denominator condition exhibits `s` as a factor of an inverted element, so `s` becomes a unit in
`A⟨T''/s''⟩` with the cofactor `r/s''` as an *explicit* inverse; the numerator condition
identifies `t/s` with the distinguished fraction `(t * r)/s''`, which is power-bounded because
every distinguished fraction is. So the map comes from
`existsUnique_continuous_ringHom_completion_locTopology`, and it is the unique continuous ring
homomorphism compatible with the structure maps from `A`.

Refinement is the shape the intersection of two rational subsets produces: `R(T₁/s₁) ∩ R(T₂/s₂)`
is presented with denominator `s₁ * s₂`, a multiple of each. That is why this elementary notion is
enough to compare presentations, and it is what keeps a valuative criterion for integrality out
of the construction — see the Provenance section.

The statements below repeat the uniformity preamble of `locUniformSpace`,
`isUniformAddGroup_locUniformSpace` and `isTopologicalRing_locUniformSpace`, once per presentation,
because `locTopology` is deliberately not an instance; this is the same preamble the sibling module
`LocalizationTopology.Presentation` carries.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.restrictionRingHom` : the restriction map
  `A⟨T/s⟩ →+* A⟨T''/s''⟩` attached to a refinement.

## Main results

* `TauCeti.Huber.PairOfDefinition.isUnit_toCompletionLoc_of_dvd` : a factor of the denominator is
  a unit in `A⟨T/s⟩`.
* `TauCeti.Huber.PairOfDefinition.toCompletionLoc_unit_inv_eq` : its inverse is the cofactor
  fraction, so it can be computed with.
* `TauCeti.Huber.PairOfDefinition.isPowerBounded_toCompletionLoc_mul_unit_inv` : the fractions
  `t/s` are power-bounded in a refining presentation.
* `TauCeti.Huber.PairOfDefinition.existsUnique_continuous_ringHom_of_refines` : exactly one
  continuous ring homomorphism `A⟨T/s⟩ → A⟨T''/s''⟩` is compatible with the structure maps.
* `TauCeti.Huber.PairOfDefinition.continuous_restrictionRingHom` and
  `…restrictionRingHom_comp_toCompletionLoc` : the two properties that determine it.
* `TauCeti.Huber.PairOfDefinition.eq_restrictionRingHom` : anything with those two properties is
  it.
* `TauCeti.Huber.PairOfDefinition.restrictionRingHomOfSubset_heq` : changing the source and target
  presentations without changing their candidate rings of definition leaves the restriction map
  unchanged.
* `TauCeti.Huber.PairOfDefinition.restrictionRingHom_self` and
  `…restrictionRingHom_comp_restrictionRingHom` : the identity and composition laws — a
  presentation refines itself with cofactor `1` and gives the identity map, and refinements compose
  with cofactor `r * r₂`, the restriction map of the composite being the composite of the
  restriction maps. Together these are the functoriality of the assignment.

## What this file does not do

It does not derive the refinement hypotheses from a containment `R(T'/s') ⊆ R(T/s)` of rational
subsets. Doing that means re-presenting the smaller subset as the intersection, which
`rationalSubset_inter` does at the level of sets, and then supplying `HasDenominatorPower` for that
presentation — a separate obligation, left to a consumer, since nothing here mentions `Spa`.

Nor is there a presheaf yet. Both functoriality laws are proved, but the indexing of the values by
rational *subsets* rather than by presentations, and the assignment itself, are later work: that
needs presentation-independence, whose conditional half is `Presentation.presentationRingEquiv`.

## Provenance

AINTLIB constructs restriction maps in `projects/AdicSpaces/Adic spaces/Presheaf.lean` (branch
`dev/adic-spaces`, commit `37bbdaeb`) from a containment of rational subsets rather than from a
refinement, and the comparison is instructive. Its unit condition, `isUnit_algebraMap_s_of_huber`,
is proved: `s` lies in the radical of the ideal generated by `s'`, hence divides a power of it,
the same factor-of-an-inverted-element argument Mathlib packages as
`IsLocalization.Away.isUnit_of_dvd`, which `isUnit_toCompletionLoc_of_dvd` below simply carries
across the completion. Its
power-boundedness condition is *not* proved — it is carried as the field
`HasLocLiftPowerBounded.locLift_divByS_isPowerBounded` of a hypothesis class, because from a bare
containment it needs a valuative criterion for integrality. Wedhorn's is Proposition 7.18, whose
own proof is the bare citation [Hu2] Lemma 3.3; he applies it in Lemma 8.1 through Proposition
7.52(1), a reformulation of 7.18(1). AINTLIB instead reduces to height one, pairing 7.18 with
Proposition 7.41, which bounds a height-one continuous valuation by `1` on `A°`; it calls that
combination an *adic Nullstellensatz*, a name Wedhorn does not use, and records it as an open
ticket. Restricting
attention to a refining presentation is what removes that dependency: the fraction in question is
then a distinguished one, and `isPowerBounded_divBy` already covers it.
So the construction here is unconditional where AINTLIB's rests on an assumed class.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), §8.1–§8.2 for the structure
  presheaf and its restriction maps, and Proposition 8.2 for the containment form. Proposition
  7.18 is the criterion it needs, reached in Lemma 8.1 via Proposition 7.52(1); Proposition 7.41
  belongs to AINTLIB's height-one reduction rather than to Wedhorn's route. Definition 7.14, which
  names rings of integral elements, is a different result and does not supply it.
* [C. Birkbeck, *AINTLIB*](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`,
  commit `37bbdaeb9`, under `projects/AdicSpaces/`:
  * `Adic spaces/Presheaf.lean` — the restriction maps built from a containment.
  * `Adic spaces/PresheafIdentification.lean` — the decomposition into Propositions 7.18 and 7.41.
  * `docs/TICKETS-axiom-clean.md` — records that combination as an open ticket, under the *adic
    Nullstellensatz* name used above.
-/

namespace TauCeti.Huber

open TauCeti.Localization

public section

variable {A : Type*} [CommRing A] [TopologicalSpace A]

namespace PairOfDefinition

variable [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A) (S : Type*)
  [CommRing S] [Algebra A S] [IsLocalization.Away s S] (hden : HasDenominatorPower P T s S)

/-! ### A factor of the denominator, and its inverse -/

/-- **A factor of the denominator is a unit in `A⟨T/s⟩`.** The localisation inverts `s`, hence
every factor of it, and the completion map carries units to units. -/
theorem isUnit_toCompletionLoc_of_dvd {a : A} (h : a ∣ s) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    IsUnit (toCompletionLoc P T s S hden a) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  rw [toCompletionLoc_apply]
  exact (IsLocalization.Away.isUnit_of_dvd s h).map UniformSpace.Completion.coeRingHom

/-- **The inverse of that unit is the cofactor fraction.** If `s = a * r` then the inverse of the
image of `a` in `A⟨T/s⟩` is the image of `r/s`.

The hypothesis is unitness rather than divisibility, so the statement applies to whichever proof of
it a caller already holds. -/
theorem toCompletionLoc_unit_inv_eq {a r : A} (h : s = a * r)
    (hu : letI := locUniformSpace P T s S hden
      letI := isUniformAddGroup_locUniformSpace P T s S hden
      letI := isTopologicalRing_locUniformSpace P T s S hden
      IsUnit (toCompletionLoc P T s S hden a)) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    (↑hu.unit⁻¹ : UniformSpace.Completion S) = ((divBy r s : S) : UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  refine Units.inv_eq_of_mul_eq_one_right ?_
  -- `a * (r/s) = (a * r)/s = s/s = 1`, then transport along the completion map
  rw [hu.unit_spec, toCompletionLoc_apply, ← UniformSpace.Completion.coe_mul, ← divBy_mul, ← h,
    divBy_self, UniformSpace.Completion.coe_one]

/-- Multiplying the image of `t` by the inverse of the image of the denominator gives the
distinguished fraction `t/s` in `A⟨T/s⟩`. -/
theorem toCompletionLoc_mul_unit_inv_eq_divBy (t : A)
    (hu : letI := locUniformSpace P T s S hden
      letI := isUniformAddGroup_locUniformSpace P T s S hden
      letI := isTopologicalRing_locUniformSpace P T s S hden
      IsUnit (toCompletionLoc P T s S hden s)) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    toCompletionLoc P T s S hden t * ↑hu.unit⁻¹ =
      ((divBy t s : S) : UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  rw [toCompletionLoc_unit_inv_eq P T s S hden (mul_one s).symm hu, toCompletionLoc_apply,
    ← UniformSpace.Completion.coe_mul, divBy_one, algebraMap_mul_invSelf]

/-- **`t/a` is power-bounded when `t * r` is a numerator.** If the denominator factors as
`s = a * r` and `t * r` lies in `T`, then `t/a` is the distinguished fraction `(t * r)/s`, which is
power-bounded.

This is the remaining hypothesis of the universal property of `A⟨T'/a⟩`, stated for whichever
proof `hu` of unitness the caller will pass to it. -/
theorem isPowerBounded_toCompletionLoc_mul_unit_inv {a r : A} (h : s = a * r)
    (hu : letI := locUniformSpace P T s S hden
      letI := isUniformAddGroup_locUniformSpace P T s S hden
      letI := isTopologicalRing_locUniformSpace P T s S hden
      IsUnit (toCompletionLoc P T s S hden a)) {t : A} (ht : t * r ∈ T) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    IsPowerBounded (toCompletionLoc P T s S hden t * ↑hu.unit⁻¹) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  have _ := isHuberRing_locUniformSpace P T s S hden
  rw [toCompletionLoc_unit_inv_eq P T s S hden h hu, toCompletionLoc_apply,
    ← UniformSpace.Completion.coe_mul, ← divBy_mul]
  exact isPowerBounded_completion_coe_of_isPowerBounded
    (isPowerBounded_divBy_locUniformSpace P T s S hden ht)

/-! ### The restriction map -/

variable (T'' : Finset A) (s'' : A) (S'' : Type*) [CommRing S''] [Algebra A S'']
  [IsLocalization.Away s'' S''] (hden'' : HasDenominatorPower P T'' s'' S'') (r : A)
  (hs'' : s'' = s * r) (hT : ∀ t ∈ T, t * r ∈ T'')

include r hs'' hT in
/-- **The universal property applied to a refinement.** If `s'' = s * r` and every `t * r`, for
`t ∈ T`, is a numerator of the second presentation, then exactly one continuous ring homomorphism
`A⟨T/s⟩ → A⟨T''/s''⟩` is compatible with the structure maps from `A`.

Nothing is assumed beyond the refinement: the invertibility and power-boundedness the universal
property asks for are consequences of it. -/
theorem existsUnique_continuous_ringHom_of_refines :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    ∃! g : UniformSpace.Completion S →+* UniformSpace.Completion S'',
      Continuous g ∧
        g.comp (toCompletionLoc P T s S hden) = toCompletionLoc P T'' s'' S'' hden'' := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T'' s'' S'' hden''
  have _ := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
  have _ := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
  have _ := isHuberRing_completion_locTopology P T'' s'' S'' hden''
  have hu := isUnit_toCompletionLoc_of_dvd P T'' s'' S'' hden'' ⟨r, hs''⟩
  exact existsUnique_continuous_ringHom_completion_locTopology P T s S hden
    (continuous_toCompletionLoc P T'' s'' S'' hden'').continuousAt hu
    fun t ht ↦ isPowerBounded_toCompletionLoc_mul_unit_inv P T'' s'' S'' hden'' hs'' hu (hT t ht)

include r hs'' hT in
/-- **The restriction map of a refinement**, `A⟨T/s⟩ → A⟨T''/s''⟩`: the unique continuous ring
homomorphism compatible with the structure maps from `A`.

Its two defining properties are `continuous_restrictionRingHom` and
`restrictionRingHom_comp_toCompletionLoc`, and `eq_restrictionRingHom` says they determine it. Those
three are the interface to use. -/
noncomputable def restrictionRingHom :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    UniformSpace.Completion S →+* UniformSpace.Completion S'' :=
  (existsUnique_continuous_ringHom_of_refines P T s S hden T'' s'' S'' hden'' r hs'' hT).choose

/-- The restriction map is continuous. -/
theorem continuous_restrictionRingHom :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    Continuous (restrictionRingHom P T s S hden T'' s'' S'' hden'' r hs'' hT) :=
  (existsUnique_continuous_ringHom_of_refines P T s S hden T'' s'' S'' hden''
    r hs'' hT).choose_spec.1.1

/-- **The restriction map is compatible with the structure maps from `A`.** This is the equation
that characterises it, and the reason it is a map of `A`-algebras. -/
@[simp]
theorem restrictionRingHom_comp_toCompletionLoc :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    (restrictionRingHom P T s S hden T'' s'' S'' hden'' r hs'' hT).comp
        (toCompletionLoc P T s S hden) = toCompletionLoc P T'' s'' S'' hden'' :=
  (existsUnique_continuous_ringHom_of_refines P T s S hden T'' s'' S'' hden''
    r hs'' hT).choose_spec.1.2

/-- **The two properties determine the restriction map.** Any continuous ring homomorphism
compatible with the structure maps from `A` is it. -/
theorem eq_restrictionRingHom :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    ∀ g : UniformSpace.Completion S →+* UniformSpace.Completion S'',
      Continuous g → g.comp (toCompletionLoc P T s S hden) = toCompletionLoc P T'' s'' S'' hden'' →
      g = restrictionRingHom P T s S hden T'' s'' S'' hden'' r hs'' hT := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T'' s'' S'' hden''
  have _ := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
  have _ := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
  exact fun g hgc hge ↦ (existsUnique_continuous_ringHom_of_refines P T s S hden T'' s'' S''
    hden'' r hs'' hT).choose_spec.2 g ⟨hgc, hge⟩

/-- **The identity law.** A presentation refines itself with cofactor `1`, and the restriction map
that gives is the identity — the unit axiom for this family of maps. -/
@[simp]
theorem restrictionRingHom_self :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    restrictionRingHom P T s S hden T s S hden 1 (mul_one s).symm
        (fun t ht ↦ by rwa [mul_one]) = RingHom.id (UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  exact (eq_restrictionRingHom P T s S hden T s S hden 1 (mul_one s).symm
    (fun t ht ↦ by rwa [mul_one]) (RingHom.id _) continuous_id (RingHom.id_comp _)).symm

/-- **The composition law.** Refinements compose — a refinement with cofactor `r` followed by one
with cofactor `r₂` is a refinement with cofactor `r * r₂` — and the restriction map of the
composite is the composite of the restriction maps. This is the cocycle axiom for this family of
maps, and with `restrictionRingHom_self` it is what makes the assignment functorial.

The composite refinement is derived here rather than assumed: its denominator and numerator
conditions follow from the two given refinements by associativity. -/
@[simp]
theorem restrictionRingHom_comp_restrictionRingHom (T''' : Finset A) (s''' : A) (S''' : Type*)
    [CommRing S'''] [Algebra A S'''] [IsLocalization.Away s''' S''']
    (hden''' : HasDenominatorPower P T''' s''' S''') (r₂ : A) (hs''' : s''' = s'' * r₂)
    (hT₂ : ∀ t ∈ T'', t * r₂ ∈ T''') :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T'' s'' S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
    letI := locUniformSpace P T''' s''' S''' hden'''
    letI := isUniformAddGroup_locUniformSpace P T''' s''' S''' hden'''
    letI := isTopologicalRing_locUniformSpace P T''' s''' S''' hden'''
    (restrictionRingHom P T'' s'' S'' hden'' T''' s''' S''' hden''' r₂ hs''' hT₂).comp
          (restrictionRingHom P T s S hden T'' s'' S'' hden'' r hs'' hT)
        = restrictionRingHom P T s S hden T''' s''' S''' hden''' (r * r₂)
          (by rw [hs''', hs'', mul_assoc])
          (fun t ht ↦ by rw [← mul_assoc]; exact hT₂ _ (hT t ht)) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T'' s'' S'' hden''
  have _ := isUniformAddGroup_locUniformSpace P T'' s'' S'' hden''
  have _ := isTopologicalRing_locUniformSpace P T'' s'' S'' hden''
  let _ := locUniformSpace P T''' s''' S''' hden'''
  have _ := isUniformAddGroup_locUniformSpace P T''' s''' S''' hden'''
  have _ := isTopologicalRing_locUniformSpace P T''' s''' S''' hden'''
  -- the composite is continuous and carries the structure map of `A⟨T/s⟩` to that of
  -- `A⟨T'''/s'''⟩`, so `eq_restrictionRingHom` identifies it
  refine eq_restrictionRingHom P T s S hden T''' s''' S''' hden''' (r * r₂) _ _ _
    ((continuous_restrictionRingHom P T'' s'' S'' hden'' T''' s''' S''' hden'''
      r₂ hs''' hT₂).comp
      (continuous_restrictionRingHom P T s S hden T'' s'' S'' hden'' r hs'' hT)) ?_
  rw [RingHom.comp_assoc, restrictionRingHom_comp_toCompletionLoc,
    restrictionRingHom_comp_toCompletionLoc]

/-! ### Refining by enlarging the numerators -/

section Subset

variable (T' : Finset A) (S' : Type*) [CommRing S'] [Algebra A S'] [IsLocalization.Away s S']
  (hden' : HasDenominatorPower P T' s S') (hTT' : ∀ u ∈ T, u ∈ T')

/-- **The restriction map of a numerator enlargement.** A presentation `(T', s)` whose numerators
contain those of `(T, s)` refines it with cofactor `1`, so
`TauCeti.Huber.PairOfDefinition.restrictionRingHom` applies; this names the resulting map and
discharges its side conditions. Adjoining a single numerator, `T' = insert t T`, is the case
Wedhorn's Remark 7.55 chains; keeping `T'` abstract keeps `DecidableEq A` out of the API. -/
noncomputable def restrictionRingHomOfSubset :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    UniformSpace.Completion S →+* UniformSpace.Completion S' :=
  restrictionRingHom P T s S hden T' s S' hden' 1 (mul_one s).symm
    fun u hu ↦ by simpa using hTT' u hu

/-- The enlargement restriction map is continuous. -/
theorem continuous_restrictionRingHomOfSubset :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    Continuous (restrictionRingHomOfSubset P T s S hden T' S' hden' hTT') :=
  continuous_restrictionRingHom P T s S hden T' s S' hden' 1 (mul_one s).symm
    fun u hu ↦ by simpa using hTT' u hu

/-- **The enlargement restriction map commutes with the structure maps from `A`.** -/
@[simp]
theorem restrictionRingHomOfSubset_comp_toCompletionLoc :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    (restrictionRingHomOfSubset P T s S hden T' S' hden' hTT').comp (toCompletionLoc P T s S hden)
      = toCompletionLoc P T' s S' hden' :=
  restrictionRingHom_comp_toCompletionLoc P T s S hden T' s S' hden' 1 (mul_one s).symm
    fun u hu ↦ by simpa using hTT' u hu

/-- **The two properties determine the enlargement restriction map**, the specialisation of
`TauCeti.Huber.PairOfDefinition.eq_restrictionRingHom`. -/
theorem eq_restrictionRingHomOfSubset :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    ∀ g : UniformSpace.Completion S →+* UniformSpace.Completion S', Continuous g →
      g.comp (toCompletionLoc P T s S hden) = toCompletionLoc P T' s S' hden' →
      g = restrictionRingHomOfSubset P T s S hden T' S' hden' hTT' :=
  eq_restrictionRingHom P T s S hden T' s S' hden' 1 (mul_one s).symm
    fun u hu ↦ by simpa using hTT' u hu

/-- **Restriction maps are independent of a simultaneous change of presentation.** Suppose two
source presentations give the same candidate ring of definition inside `S`, and two target
presentations do likewise inside `S'`. Then the corresponding numerator-enlargement restriction
maps are heterogeneously equal.

The conclusion is `HEq` because changing a presentation changes the uniformity used to form each
completion. -/
theorem restrictionRingHomOfSubset_heq
    (P : PairOfDefinition A)
    (T₁ T₁' : Finset A) (s₁ : A) (S : Type*) [CommRing S] [Algebra A S]
    [IsLocalization.Away s₁ S] (hden₁ : HasDenominatorPower P T₁ s₁ S)
    (S' : Type*) [CommRing S'] [Algebra A S'] [IsLocalization.Away s₁ S']
    (hden₁' : HasDenominatorPower P T₁' s₁ S') (hT₁T₁' : ∀ t ∈ T₁, t ∈ T₁')
    (T₂ T₂' : Finset A) (s₂ : A) [IsLocalization.Away s₂ S]
    [IsLocalization.Away s₂ S'] (hden₂ : HasDenominatorPower P T₂ s₂ S)
    (hden₂' : HasDenominatorPower P T₂' s₂ S') (hT₂T₂' : ∀ t ∈ T₂, t ∈ T₂')
    (hS : locSubring P T₂ s₂ S = locSubring P T₁ s₁ S)
    (hS' : locSubring P T₂' s₂ S' = locSubring P T₁' s₁ S') :
    HEq (restrictionRingHomOfSubset P T₂ s₂ S hden₂ T₂' S' hden₂' hT₂T₂')
      (restrictionRingHomOfSubset P T₁ s₁ S hden₁ T₁' S' hden₁' hT₁T₁') := by
  exact completionRingHom_heq_of_uniformSpace_eq
    (locUniformSpace_congr P T₁ T₂ s₁ s₂ S hden₁ hden₂ hS)
    (locUniformSpace_congr P T₁' T₂' s₁ s₂ S' hden₁' hden₂' hS')
    (isUniformAddGroup_locUniformSpace P T₁ s₁ S hden₁)
    (isUniformAddGroup_locUniformSpace P T₂ s₂ S hden₂)
    (isTopologicalRing_locUniformSpace P T₁ s₁ S hden₁)
    (isTopologicalRing_locUniformSpace P T₂ s₂ S hden₂)
    (isUniformAddGroup_locUniformSpace P T₁' s₁ S' hden₁')
    (isUniformAddGroup_locUniformSpace P T₂' s₂ S' hden₂')
    (isTopologicalRing_locUniformSpace P T₁' s₁ S' hden₁')
    (isTopologicalRing_locUniformSpace P T₂' s₂ S' hden₂')
    (restrictionRingHomOfSubset P T₂ s₂ S hden₂ T₂' S' hden₂' hT₂T₂')
    (restrictionRingHomOfSubset P T₁ s₁ S hden₁ T₁' S' hden₁' hT₁T₁')
    (toCompletionLoc P T₂ s₂ S hden₂) (toCompletionLoc P T₁ s₁ S hden₁)
    (toCompletionLoc P T₂' s₂ S' hden₂') (toCompletionLoc P T₁' s₁ S' hden₁')
    (continuous_restrictionRingHomOfSubset P T₂ s₂ S hden₂ T₂' S' hden₂' hT₂T₂')
    (toCompletionLoc_heq P T₁ T₂ s₁ s₂ S hden₁ hden₂ hS)
    (toCompletionLoc_heq P T₁' T₂' s₁ s₂ S' hden₁' hden₂' hS')
    (restrictionRingHomOfSubset_comp_toCompletionLoc P T₂ s₂ S hden₂ T₂' S'
      hden₂' hT₂T₂')
    (eq_restrictionRingHomOfSubset P T₁ s₁ S hden₁ T₁' S' hden₁' hT₁T₁')

/-- **The restriction map carries `t/s` to `t/s`**, for every `t`. This is the fact the Laurent
presentation of a refinement rests on; the numerator condition `t ∈ T'` is not needed here, only
where power-boundedness of `t/s` is.

Both structure maps from `A` commute with restriction, so `t` goes to `t` and `s` goes to `s`. The
image of `s⁻¹` is then forced: `Units.map` carries the unit upstairs to the unit downstairs, and a
unit determines its inverse. -/
@[simp]
theorem restrictionRingHomOfSubset_coe_divBy (t : A) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    restrictionRingHomOfSubset P T s S hden T' S' hden' hTT'
        ((divBy t s : S) : UniformSpace.Completion S)
      = ((divBy t s : S') : UniformSpace.Completion S') := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T' s S' hden'
  have _ := isUniformAddGroup_locUniformSpace P T' s S' hden'
  have _ := isTopologicalRing_locUniformSpace P T' s S' hden'
  have hu : IsUnit (toCompletionLoc P T s S hden s) :=
    isUnit_toCompletionLoc_of_dvd P T s S hden dvd_rfl
  have hu' : IsUnit (toCompletionLoc P T' s S' hden' s) :=
    isUnit_toCompletionLoc_of_dvd P T' s S' hden' dvd_rfl
  set φ := restrictionRingHomOfSubset P T s S hden T' S' hden' hTT' with hφdef
  have hcomp : ∀ a, φ (toCompletionLoc P T s S hden a) = toCompletionLoc P T' s S' hden' a :=
    fun a ↦ by
      rw [hφdef, ← RingHom.comp_apply, restrictionRingHomOfSubset_comp_toCompletionLoc]
  -- `Units.map φ` carries the unit upstairs to the unit downstairs, hence their inverses too
  have hunit : Units.map (φ : _ →* _) hu.unit = hu'.unit :=
    Units.ext (by simp only [Units.coe_map, MonoidHom.coe_ofClass, IsUnit.unit_spec, hcomp s])
  have hinv : φ (↑hu.unit⁻¹) = ↑hu'.unit⁻¹ := by
    rw [← hunit]
    exact (Units.coe_map_inv _ _).symm
  rw [← toCompletionLoc_mul_unit_inv_eq_divBy P T s S hden t hu,
    ← toCompletionLoc_mul_unit_inv_eq_divBy P T' s S' hden' t hu',
    map_mul, hcomp t, hinv]

/-- **The identity law.** A presentation enlarges itself, and the map that gives is the identity. -/
@[simp]
theorem restrictionRingHomOfSubset_self :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    restrictionRingHomOfSubset P T s S hden T S hden (fun _ hu ↦ hu)
      = RingHom.id (UniformSpace.Completion S) :=
  restrictionRingHom_self P T s S hden

/-- **The composition law.** Enlargements compose, and the map of the composite is the composite of
the maps. With `TauCeti.Huber.PairOfDefinition.restrictionRingHomOfSubset_self` this makes the
assignment functorial along a chain of enlargements — the shape Wedhorn's Remark 7.55 produces. -/
@[simp]
theorem restrictionRingHomOfSubset_comp_restrictionRingHomOfSubset (T'' : Finset A) (S'' : Type*)
    [CommRing S''] [Algebra A S''] [IsLocalization.Away s S'']
    (hden'' : HasDenominatorPower P T'' s S'') (hT'T'' : ∀ u ∈ T', u ∈ T'') :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    letI := locUniformSpace P T'' s S'' hden''
    letI := isUniformAddGroup_locUniformSpace P T'' s S'' hden''
    letI := isTopologicalRing_locUniformSpace P T'' s S'' hden''
    (restrictionRingHomOfSubset P T' s S' hden' T'' S'' hden'' hT'T'').comp
        (restrictionRingHomOfSubset P T s S hden T' S' hden' hTT')
      = restrictionRingHomOfSubset P T s S hden T'' S'' hden'' fun u hu ↦ hT'T'' u (hTT' u hu) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T' s S' hden'
  have _ := isUniformAddGroup_locUniformSpace P T' s S' hden'
  have _ := isTopologicalRing_locUniformSpace P T' s S' hden'
  let _ := locUniformSpace P T'' s S'' hden''
  have _ := isUniformAddGroup_locUniformSpace P T'' s S'' hden''
  have _ := isTopologicalRing_locUniformSpace P T'' s S'' hden''
  -- the composite is continuous and agrees with the structure map, so uniqueness identifies it
  refine eq_restrictionRingHomOfSubset P T s S hden T'' S'' hden''
    (fun u hu ↦ hT'T'' u (hTT' u hu)) _ ?_ ?_
  · exact (continuous_restrictionRingHomOfSubset P T' s S' hden' T'' S'' hden'' hT'T'').comp
      (continuous_restrictionRingHomOfSubset P T s S hden T' S' hden' hTT')
  · rw [RingHom.comp_assoc, restrictionRingHomOfSubset_comp_toCompletionLoc,
      restrictionRingHomOfSubset_comp_toCompletionLoc]

/-- **A homomorphism that agrees with another after the structure maps sends `t/s` to `t/s`.**
Given `g` out of `A⟨T'/s⟩` and `φ` out of `A⟨T/s⟩` into a common ring, agreeing after the two
structure maps from `A`, the distinguished fractions correspond. Both `s`-inverses are inverses of
the same element of the target, and inverses in a monoid are unique.

This is the transport that identifies the fraction `t/s` across a numerator enlargement, and it
needs nothing of the target beyond its ring structure. -/
theorem map_divBy_of_comp_toCompletionLoc_eq (t : A) {B : Type*} [Semiring B] :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace P T' s S' hden'
    letI := isUniformAddGroup_locUniformSpace P T' s S' hden'
    letI := isTopologicalRing_locUniformSpace P T' s S' hden'
    ∀ (g : UniformSpace.Completion S' →+* B) (φ : UniformSpace.Completion S →+* B),
      g.comp (toCompletionLoc P T' s S' hden') = φ.comp (toCompletionLoc P T s S hden) →
      g ((divBy t s : S') : UniformSpace.Completion S')
        = φ ((divBy t s : S) : UniformSpace.Completion S) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace P T' s S' hden'
  have _ := isUniformAddGroup_locUniformSpace P T' s S' hden'
  have _ := isTopologicalRing_locUniformSpace P T' s S' hden'
  intro g φ hge
  have hu : IsUnit (toCompletionLoc P T s S hden s) :=
    isUnit_toCompletionLoc_of_dvd P T s S hden dvd_rfl
  have hu' : IsUnit (toCompletionLoc P T' s S' hden' s) :=
    isUnit_toCompletionLoc_of_dvd P T' s S' hden' dvd_rfl
  have hgs : g (toCompletionLoc P T' s S' hden' s) = φ (toCompletionLoc P T s S hden s) :=
    congrArg (fun k : A →+* B ↦ k s) hge
  have hgt : g (toCompletionLoc P T' s S' hden' t) = φ (toCompletionLoc P T s S hden t) :=
    congrArg (fun k : A →+* B ↦ k t) hge
  -- the two inverses of `s` correspond, being inverses of the same element of `B`
  have hginv : g ↑hu'.unit⁻¹ = ↑(hu.map φ).unit⁻¹ := by
    refine (Units.inv_eq_of_mul_eq_one_left ?_).symm
    rw [(hu.map φ).unit_spec, ← hgs, ← map_mul, hu'.val_inv_mul, map_one]
  rw [← toCompletionLoc_mul_unit_inv_eq_divBy P T' s S' hden' t hu', map_mul, hginv, hgt,
    IsUnit.unit_inv_map φ hu, ← map_mul, toCompletionLoc_mul_unit_inv_eq_divBy P T s S hden t hu]

end Subset

end PairOfDefinition

end

end TauCeti.Huber
