/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Order.BigOperators.WeightedGrowth
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.PathsInto
public import TauCeti.RingTheory.TwoSidedIdeal.Homogeneous

/-!
# Path algebras with one quadratic relation per vertex are large

Let `R` be a finite quiver with finitely many arrows, `k` a field, and let every vertex `v` carry
a relator `r_v` which is homogeneous of path length two and lies in the corner `e_v kR e_v`. This
file bounds the growth of `A = kR / (r_v)` from below, in the spirit of the Golod--Shafarevich
inequality, and deduces that `A` is infinite-dimensional as soon as the vertices carry a nonzero
nonnegative weight `δ` with

```text
2 δ_i ≤ ∑_j #(i ⟶ j) δ_j.
```

The preprojective algebra of a quiver is of this form, with the doubled quiver for `R` and the
local preprojective relators for the `r_v`; this is its intended application.

Write `P_n(j)` for the span of the paths of length `n` ending at `j`, which is the degree-`n` part
of the corner `e_j kR`, and `K_n(j)` for its intersection with the relation ideal `I`. Since `kR`
is generated by its vertex idempotents and arrows, `I = ∑_v r_v kR + ∑_b b I`, and cutting this
down to degree `n + 2` at the vertex `j` gives

```text
K_{n+2}(j) = r_j P_n(j) + ∑_{b : i ⟶ j} b K_{n+1}(i).
```

Moreover `r_j = ∑_b b c_b` for some `c_b`, so `r_j K_n(j)` is already contained in the second
summand. Counting dimensions, the dimensions `d_n(j) = dim P_n(j) - dim K_n(j)` of the images of
the `P_n(j)` in `A` satisfy `d_0(j) = 1`, `d_1(j) = ∑_{b : i ⟶ j} d_0(i)` and

```text
d_{n+2}(j) + d_n(j) ≥ ∑_{b : i ⟶ j} d_{n+1}(i),
```

which is the vertexwise form of the coefficientwise inequality `H_A(t) (1 - C t + t²) ≥ 1` for the
matrix Hilbert series of `A`, `C` being the arrow-count matrix of `R`. Weighting by `δ`, the sums
`s_n = ∑_j δ_j d_n(j)` then satisfy `s_{n+2} - s_{n+1} ≥ s_{n+1} - s_n ≥ ⋯ ≥ s_1 - s_0 ≥ s_0`,
so `s_n ≥ (n + 1) s_0 ≥ (n + 1) ∑_j δ_j` (`TauCeti.add_one_mul_sum_mul_le_sum_mul`). If `A` had
finite dimension `N`, then `d_N(j) ≤ N` would give `s_N ≤ N ∑_j δ_j`, contradicting this at
`n = N` since `∑_j δ_j > 0`.

## Main results

* `TauCeti.PathAlgebra.sum_card_mul_finrank_map_pathsInto_le_add`: the Anick-type inequality
  `∑_{b : i ⟶ j} d_{m+1}(i) ≤ d_{m+2}(j) + d_m(j)` for the dimensions of the images of these
  spans in the quotient.
* `TauCeti.PathAlgebra.not_module_finite_quotient_span_range_of_two_mul_le_sum`: **a path algebra
  with one quadratic corner relation per vertex, whose arrow counts admit a nonzero nonnegative
  weight `δ` with `2 δ_i ≤ ∑_j #(i ⟶ j) δ_j`, is infinite-dimensional.**

## Implementation notes

The general path-span API is in `TauCeti.RepresentationTheory.Quiver.PathAlgebra.PathsInto`.
All the dimension counting takes place among subspaces of `kR` itself; the quotient enters only
through the images of the spaces `P_n(j)`, so no grading of the quotient is needed. The
intersections `K_n(j)` with the relation ideal and the decomposition of that ideal are private to
this file.

## References

* E. S. Golod and I. R. Shafarevich, *On the class field tower*, Izv. Akad. Nauk SSSR Ser. Mat.
  28 (1964), for the inequality `dim A_n ≥ d dim A_{n-1} - r dim A_{n-2}` for algebras with `d`
  generators and `r` quadratic relations.
* D. J. Anick, *Non-commutative graded algebras and their Hilbert series*, J. Algebra 78 (1982),
  for the Hilbert-series form of that inequality.
* P. Etingof and C.-H. Eu, *Koszulity and the Hilbert series of preprojective algebras*, Math.
  Res. Lett. 14 (2007), where the matrix Hilbert series of a preprojective algebra is compared
  with `(1 - C t + t²)⁻¹`.
-/

public section

namespace TauCeti

open _root_.Quiver

universe u v w

namespace PathAlgebra

variable {R : Type u} [Quiver.{v} R]

variable (k : Type w)

section Semiring

variable [CommSemiring k]

variable {k}

/-- Left multiplication by a vertex idempotent keeps the relator at that vertex and kills the
other relators. -/
private theorem vertexIdempotent_mul_rel [DecidableEq R] {r : R → pathAlgebra k R}
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (u v : R) :
    vertexIdempotent k u * r v = if u = v then r v else 0 := by
  split_ifs with h
  · rw [h, hl]
  · rw [← hl v, ← mul_assoc, vertexIdempotent_mul_vertexIdempotent_of_ne h, zero_mul]

/-- The relator at a vertex lies in the span of the paths of length two into that vertex. -/
private theorem rel_mem_pathsInto {r : R → pathAlgebra k R} (h2 : ∀ v, r v ∈ grade k R 2)
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (j : R) : r j ∈ pathsInto k 2 j := by
  rw [← hl j]
  exact vertexIdempotent_mul_mem_pathsInto j (h2 j)

end Semiring


section RelationIdeal

variable {k} [Field k] [Finite R] {r : R → pathAlgebra k R}

/-- The degree-`m` part of `r_v y`, cut down to the corner of `j`: only the relator at `j`
survives, and it contributes `r_j` times the degree-`m - 2` part of `y` at `j`. -/
private theorem vertexIdempotent_mul_decompose_rel_mul [DecidableEq R]
    (h2 : ∀ v, r v ∈ grade k R 2) (hl : ∀ v, vertexIdempotent k v * r v = r v)
    (hr : ∀ v, r v * vertexIdempotent k v = r v) (m : ℕ) (j v : R) (y : pathAlgebra k R) :
    vertexIdempotent k j * (DirectSum.decompose (grade k R) (r v * y) m : pathAlgebra k R) =
      if v = j ∧ 2 ≤ m then
        r j * (vertexIdempotent k j * (DirectSum.decompose (grade k R) y (m - 2) :
          pathAlgebra k R))
      else 0 := by
  rw [DirectSum.coe_decompose_mul_of_left_mem _ m (h2 v)]
  split_ifs with hm h h
  · obtain ⟨rfl, -⟩ := h
    rw [← mul_assoc, hl, ← mul_assoc, hr]
  · have hjv : j ≠ v := fun e => h ⟨e.symm, hm⟩
    rw [← mul_assoc, vertexIdempotent_mul_rel hl]
    simp [hjv]
  · exact absurd h.2 hm
  · rw [mul_zero]

/-- The degree-`m` part of `b z`, cut down to the corner of `j`, for an arrow `b : i ⟶ j'`:
it vanishes unless `j' = j`, and is then `b` times the degree-`m - 1` part of `z` at `i`. -/
private theorem vertexIdempotent_mul_decompose_ofArrow_mul [DecidableEq R] (m : ℕ) (j : R)
    {i j' : R} (b : i ⟶ j') (z : pathAlgebra k R) :
    vertexIdempotent k j * (DirectSum.decompose (grade k R) (ofArrow b * z) m : pathAlgebra k R) =
      if j' = j ∧ 1 ≤ m then
        ofArrow b * (vertexIdempotent k i * (DirectSum.decompose (grade k R) z (m - 1) :
          pathAlgebra k R))
      else 0 := by
  rw [DirectSum.coe_decompose_mul_of_left_mem _ m (ofArrow_mem_grade_one b)]
  have hb : (ofArrow b : pathAlgebra k R) * vertexIdempotent k i = ofArrow b := by
    rw [ofArrow_eq_ofPath, ofPath_mul_vertexIdempotent]
  split_ifs with hm h h
  · rw [← mul_assoc, vertexIdempotent_mul_ofArrow, ← mul_assoc, hb]
    simp [h.1]
  · have hj : j' ≠ j := fun e => h ⟨e, hm⟩
    rw [← mul_assoc, vertexIdempotent_mul_ofArrow]
    simp [hj]
  · exact absurd h.2 hm
  · rw [mul_zero]

/-- The part of the relation ideal spanned by paths of length `n` into `j`, as a `k`-subspace. -/
private noncomputable def relPathsInto (r : R → pathAlgebra k R) (n : ℕ) (j : R) :
    Submodule k (pathAlgebra k R) :=
  pathsInto k n j ⊓ (TwoSidedIdeal.span (Set.range r)).asIdeal.restrictScalars k

private theorem relPathsInto_le_pathsInto (n : ℕ) (j : R) :
    relPathsInto r n j ≤ pathsInto k n j :=
  inf_le_left

private theorem mem_relPathsInto {n : ℕ} {j : R} {x : pathAlgebra k R} :
    x ∈ relPathsInto r n j ↔ x ∈ pathsInto k n j ∧ x ∈ TwoSidedIdeal.span (Set.range r) := by
  rw [relPathsInto, Submodule.mem_inf, Submodule.restrictScalars_mem, TwoSidedIdeal.mem_asIdeal]

private instance [∀ a b : R, Finite (a ⟶ b)] (n : ℕ) (j : R) :
    FiniteDimensional k (relPathsInto r n j) :=
  Submodule.finiteDimensional_inf_left _ _

/-- The dimension of the image of the paths of length `n` into `j` in the quotient by the relation
ideal, plus the dimension of its intersection with that ideal, is the number of such paths. -/
private theorem finrank_map_add_finrank_relPathsInto [∀ a b : R, Finite (a ⟶ b)]
    (r : R → pathAlgebra k R) (n : ℕ) (j : R) :
    Module.finrank k ((pathsInto k n j).map
        (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap) +
      Module.finrank k (relPathsInto r n j) = Nat.card (PathInto R n j) := by
  set q := (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap
  have hker : LinearMap.ker q = (TwoSidedIdeal.span (Set.range r)).asIdeal.restrictScalars k := by
    ext x
    simp [q, Ideal.Quotient.eq_zero_iff_mem]
  have h := LinearMap.finrank_range_add_finrank_ker (q.domRestrict (pathsInto k n j))
  rw [LinearMap.range_domRestrict, LinearMap.ker_domRestrict, hker, finrank_pathsInto,
    ← Submodule.finrank_map_subtype_eq, Submodule.map_comap_subtype] at h
  exact h

end RelationIdeal

section Decomposition

variable {k} [Field k] [Fintype R] [∀ a b : R, Fintype (a ⟶ b)] {r : R → pathAlgebra k R}

/-- `F` is a sum `∑ᵥ r_v Y_v + ∑_b b Z_b` whose arrow coefficients `Z_b` lie in the two-sided
ideal generated by the `r_v`. Every element of that ideal has this shape
(`isRelDecomp_of_mem_span`). -/
private def IsRelDecomp (r : R → pathAlgebra k R) (F : pathAlgebra k R) : Prop :=
  ∃ (Y : R → pathAlgebra k R) (Z : (Σ i j : R, (i ⟶ j)) → pathAlgebra k R),
    (∀ a, Z a ∈ TwoSidedIdeal.span (Set.range r)) ∧
      F = ∑ v, r v * Y v + ∑ a, ofArrow a.2.2 * Z a

private theorem isRelDecomp_zero : IsRelDecomp r 0 :=
  ⟨0, 0, fun _ => zero_mem _, by simp⟩

private theorem IsRelDecomp.add {F G : pathAlgebra k R} (hF : IsRelDecomp r F)
    (hG : IsRelDecomp r G) : IsRelDecomp r (F + G) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  obtain ⟨Y', Z', hZ', rfl⟩ := hG
  refine ⟨Y + Y', Z + Z', fun a => add_mem (hZ a) (hZ' a), ?_⟩
  simp only [Pi.add_apply, mul_add, Finset.sum_add_distrib]
  abel

private theorem IsRelDecomp.neg {F : pathAlgebra k R} (hF : IsRelDecomp r F) :
    IsRelDecomp r (-F) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨-Y, -Z, fun a => neg_mem (hZ a), ?_⟩
  simp only [Pi.neg_apply, mul_neg, Finset.sum_neg_distrib, neg_add]

private theorem IsRelDecomp.smul {F : pathAlgebra k R} (c : k) (hF : IsRelDecomp r F) :
    IsRelDecomp r (c • F) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨c • Y, c • Z, fun a => ?_, ?_⟩
  · rw [Pi.smul_apply, ← TwoSidedIdeal.mem_asIdeal]
    exact Submodule.smul_of_tower_mem _ c (TwoSidedIdeal.mem_asIdeal.2 (hZ a))
  · simp only [Pi.smul_apply, mul_smul_comm, smul_add, Finset.smul_sum]

private theorem IsRelDecomp.mul_right {F : pathAlgebra k R} (x : pathAlgebra k R)
    (hF : IsRelDecomp r F) : IsRelDecomp r (F * x) := by
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨fun v => Y v * x, fun a => Z a * x,
    fun a => TwoSidedIdeal.mul_mem_right _ _ _ (hZ a), ?_⟩
  simp only [add_mul, Finset.sum_mul, mul_assoc]

private theorem ofArrow_mul_isRelDecomp {i j : R} (b : i ⟶ j) {G : pathAlgebra k R}
    (hG : G ∈ TwoSidedIdeal.span (Set.range r)) : IsRelDecomp r (ofArrow b * G) := by
  classical
  refine ⟨0, fun a => if a = ⟨i, j, b⟩ then G else 0, fun a => ?_, ?_⟩
  · dsimp only
    split_ifs
    · exact hG
    · exact zero_mem _
  · simp only [Pi.zero_apply, mul_zero, Finset.sum_const_zero, zero_add, mul_ite,
      Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte]

private theorem IsRelDecomp.vertexIdempotent_mul (hl : ∀ v, vertexIdempotent k v * r v = r v)
    (u : R) {F : pathAlgebra k R} (hF : IsRelDecomp r F) :
    IsRelDecomp r (vertexIdempotent k u * F) := by
  classical
  obtain ⟨Y, Z, hZ, rfl⟩ := hF
  refine ⟨fun v => if u = v then Y v else 0, fun a => if a.2.1 = u then Z a else 0,
    fun a => ?_, ?_⟩
  · dsimp only
    split_ifs
    · exact hZ a
    · exact zero_mem _
  · simp only [mul_add, Finset.mul_sum, ← mul_assoc, vertexIdempotent_mul_rel hl,
      vertexIdempotent_mul_ofArrow, ite_mul, zero_mul, mul_ite, mul_zero]

/-- **Every element of the relation ideal is a combination of relators and of arrows times
elements of the ideal.** This is the identity `I = ∑ᵥ r_v · kR + ∑_b b · I`, valid because the
path algebra is generated by the vertex idempotents and the arrows. -/
private theorem isRelDecomp_of_mem_span (hl : ∀ v, vertexIdempotent k v * r v = r v)
    {F : pathAlgebra k R} (hF : F ∈ TwoSidedIdeal.span (Set.range r)) : IsRelDecomp r F := by
  classical
  induction hF using TwoSidedIdeal.span_induction with
  | mem x hx =>
    obtain ⟨v, rfl⟩ := hx
    refine ⟨fun u => if u = v then 1 else 0, 0, fun _ => zero_mem _, ?_⟩
    simp only [mul_ite, mul_one, mul_zero, Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte,
      Pi.zero_apply, Finset.sum_const_zero, add_zero]
  | zero => exact isRelDecomp_zero
  | add x y _ _ hx hy => exact hx.add hy
  | neg x _ hx => exact hx.neg
  | right_absorb b x _ hx => exact hx.mul_right b
  | left_absorb a x hxI hx =>
    induction a using PathAlgebra.induction_linear with
    | zero => rw [zero_mul]; exact isRelDecomp_zero
    | add a a' ha ha' => rw [add_mul]; exact ha.add ha'
    | single x' c =>
      rw [single_eq_smul_ofPath, smul_mul_assoc]
      refine IsRelDecomp.smul c ?_
      obtain ⟨s, t, p⟩ := x'
      cases p with
      | nil =>
        rw [← vertexIdempotent_eq_ofPath]
        exact hx.vertexIdempotent_mul hl s
      | cons q b =>
        rw [← ofArrow_mul_ofPath, mul_assoc]
        exact ofArrow_mul_isRelDecomp b (TwoSidedIdeal.mul_mem_left _ _ _ hxI)

/-- **The graded-corner form of the relation ideal.** An element `F` of the relation ideal lying
in the span of the paths of length `m` into `j` is `r_j Y + ∑_b b Z_b`, where `Y` is spanned by
the paths of length `m - 2` into `j` and each `Z_b`, for `b : i ⟶ j`, is an element of the ideal
spanned by the paths of length `m - 1` into `i`; the relator term is absent when `m < 2` and the
arrow terms when `m = 0`. -/
private theorem exists_eq_of_mem_span_of_mem_pathsInto (h2 : ∀ v, r v ∈ grade k R 2)
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (hr : ∀ v, r v * vertexIdempotent k v = r v)
    {m : ℕ} {j : R} {F : pathAlgebra k R} (hFI : F ∈ TwoSidedIdeal.span (Set.range r))
    (hFP : F ∈ pathsInto k m j) :
    ∃ Y ∈ pathsInto k (m - 2) j, ∃ Z : (i : R) → (i ⟶ j) → pathAlgebra k R,
      (∀ i b, Z i b ∈ TwoSidedIdeal.span (Set.range r) ∧ Z i b ∈ pathsInto k (m - 1) i) ∧
      F = (if 2 ≤ m then r j * Y else 0) +
        ∑ i, ∑ b : i ⟶ j, if 1 ≤ m then ofArrow b * Z i b else 0 := by
  classical
  have hhom := TwoSidedIdeal.homogeneous_span (grade k R) (s := Set.range r)
    (by rintro _ ⟨v, rfl⟩; exact ⟨2, h2 v⟩)
  obtain ⟨Y, Z, hZ, hF⟩ := isRelDecomp_of_mem_span hl hFI
  refine ⟨vertexIdempotent k j * (DirectSum.decompose (grade k R) (Y j) (m - 2) :
      pathAlgebra k R), vertexIdempotent_mul_mem_pathsInto j (Submodule.coe_mem _),
    fun i b => vertexIdempotent k i *
      (DirectSum.decompose (grade k R) (Z ⟨i, j, b⟩) (m - 1) : pathAlgebra k R),
    fun i b => ⟨TwoSidedIdeal.mul_mem_left _ _ _ (TwoSidedIdeal.mem_asIdeal.1
      (hhom (m - 1) (TwoSidedIdeal.mem_asIdeal.2 (hZ _)))),
      vertexIdempotent_mul_mem_pathsInto i (Submodule.coe_mem _)⟩, ?_⟩
  have hFm :
      F = vertexIdempotent k j * (DirectSum.decompose (grade k R) F m : pathAlgebra k R) := by
    rw [DirectSum.decompose_of_mem_same _ (pathsInto_le_grade m j hFP),
      vertexIdempotent_mul_of_mem_pathsInto hFP]
  conv_lhs => rw [hFm, hF]
  simp only [DirectSum.decompose_add, DirectSum.decompose_sum, DirectSum.add_apply,
    DirectSum.sum_apply, Submodule.coe_add, Submodule.coe_sum, mul_add, Finset.mul_sum,
    vertexIdempotent_mul_decompose_rel_mul h2 hl hr, vertexIdempotent_mul_decompose_ofArrow_mul]
  congr 1
  · rw [Finset.sum_eq_single j]
    · simp only [true_and]
    · intro v _ hv
      simp [hv]
    · simp
  · rw [Fintype.sum_sigma]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Fintype.sum_sigma, Finset.sum_eq_single j]
    · simp only [true_and]
    · intro j' _ hj'
      exact Finset.sum_eq_zero fun b _ => by simp [hj']
    · simp

/-- **The Anick-type inequality for one quadratic relation per vertex.** Writing `P` for the
spans of paths of fixed length into a fixed vertex and `K` for their intersections with the
relation ideal, `dim K_{m+2}(j) + dim K_m(j) ≤ dim P_m(j) + ∑_{b : i ⟶ j} dim K_{m+1}(i)`: every
element of `K_{m+2}(j)` is `r_j Y + ∑_b b Z_b`, and the choices of `(Y, Z)` with vanishing sum
contain a copy of `K_m(j)`, because `r_j = ∑_b b c_b` and `r_j Y = ∑_b b (c_b Y)`. -/
private theorem finrank_relPathsInto_add_le (h2 : ∀ v, r v ∈ grade k R 2)
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (hr : ∀ v, r v * vertexIdempotent k v = r v)
    (m : ℕ) (j : R) :
    Module.finrank k (relPathsInto r (m + 2) j) + Module.finrank k (relPathsInto r m j) ≤
      Module.finrank k (pathsInto k m j) +
        ∑ i : R, Fintype.card (i ⟶ j) * Module.finrank k (relPathsInto r (m + 1) i) := by
  classical
  obtain ⟨c, hc, hrj⟩ := exists_eq_sum_ofArrow_mul (rel_mem_pathsInto h2 hl j)
  -- `Ψ (Y, Z) = r_j Y + ∑_b b Z_b`; its range contains `K_{m+2}(j)`.
  let Ψ : (pathsInto k m j × ((i : R) → (i ⟶ j) → relPathsInto r (m + 1) i)) →ₗ[k]
      pathAlgebra k R :=
    ((LinearMap.mulLeft k (r j)).comp (pathsInto k m j).subtype).coprod
      (∑ i : R, ∑ b : i ⟶ j, (LinearMap.mulLeft k (ofArrow b)).comp
        ((relPathsInto r (m + 1) i).subtype.comp
          ((LinearMap.proj (R := k) (φ := fun _ : i ⟶ j => relPathsInto r (m + 1) i) b).comp
            (LinearMap.proj (R := k) (φ := fun i => (i ⟶ j) → relPathsInto r (m + 1) i) i))))
  have hΨ : ∀ Y Z, Ψ (Y, Z) =
      r j * Y + ∑ i : R, ∑ b : i ⟶ j, ofArrow b * (Z i b : pathAlgebra k R) := by
    intro Y Z
    simp [Ψ, LinearMap.sum_apply]
  -- `ι Y = (Y, -(c_b Y)_b)` embeds `K_m(j)` in the kernel of `Ψ`.
  let ι : relPathsInto r m j →ₗ[k]
      (pathsInto k m j × ((i : R) → (i ⟶ j) → relPathsInto r (m + 1) i)) :=
    (Submodule.inclusion (relPathsInto_le_pathsInto m j)).prod
      (LinearMap.pi fun i => LinearMap.pi fun b => -LinearMap.codRestrict _
        ((LinearMap.mulLeft k (c i b)).comp (relPathsInto r m j).subtype) fun y =>
          mem_relPathsInto.2 ⟨mul_mem_pathsInto (hc i b) (mem_relPathsInto.1 y.2).1,
            TwoSidedIdeal.mul_mem_left _ _ _ (mem_relPathsInto.1 y.2).2⟩)
  have hι : Function.Injective ι := by
    intro y y' h
    have h1 := congrArg (fun p => (p.1 : pathAlgebra k R)) h
    simp only [ι, LinearMap.coe_prod, Function.prod_apply, Submodule.coe_inclusion] at h1
    exact Subtype.ext h1
  have hΨι : LinearMap.range ι ≤ LinearMap.ker Ψ := by
    rintro _ ⟨y, rfl⟩
    rw [LinearMap.mem_ker, ← Prod.mk.eta (p := ι y), hΨ]
    simp only [ι, LinearMap.coe_prod, Function.prod_apply, LinearMap.pi_apply,
      LinearMap.neg_apply, LinearMap.codRestrict_apply, LinearMap.coe_comp, Function.comp_apply,
      Submodule.coe_subtype, LinearMap.mulLeft_apply, Submodule.coe_neg, mul_neg,
      Finset.sum_neg_distrib]
    rw [hrj]
    simp only [Submodule.coe_inclusion, Finset.sum_mul, mul_assoc, add_neg_cancel]
  have hK : relPathsInto r (m + 2) j ≤ LinearMap.range Ψ := by
    intro F hF
    obtain ⟨Y, hY, Z, hZ, hF⟩ :=
      exists_eq_of_mem_span_of_mem_pathsInto h2 hl hr (mem_relPathsInto.1 hF).2
        (mem_relPathsInto.1 hF).1
    refine ⟨(⟨Y, hY⟩, fun i b => ⟨Z i b, mem_relPathsInto.2 ⟨(hZ i b).2, (hZ i b).1⟩⟩), ?_⟩
    rw [hΨ, hF]
    simp
  have h1 := Submodule.finrank_mono hK
  have h2' : Module.finrank k (relPathsInto r m j) ≤ Module.finrank k (LinearMap.ker Ψ) :=
    (LinearMap.finrank_range_of_inj hι).symm.le.trans (Submodule.finrank_mono hΨι)
  have h3 := LinearMap.finrank_range_add_finrank_ker Ψ
  rw [Module.finrank_prod, Module.finrank_pi_fintype] at h3
  simp only [Module.finrank_pi_fintype, Finset.sum_const, Finset.card_univ, smul_eq_mul] at h3
  omega

end Decomposition

section Degrees

variable {k} [Field k] [Finite R] {r : R → pathAlgebra k R}

/-- In degrees `0` and `1` the relation ideal, generated in degree `2`, is zero. -/
private theorem relPathsInto_eq_bot_of_lt_two [∀ a b : R, Finite (a ⟶ b)]
    (h2 : ∀ v, r v ∈ grade k R 2)
    (hl : ∀ v, vertexIdempotent k v * r v = r v) (hr : ∀ v, r v * vertexIdempotent k v = r v)
    {n : ℕ} (hn : n < 2) (j : R) : relPathsInto r n j = ⊥ := by
  let : Fintype R := Fintype.ofFinite R
  let : ∀ a b : R, Fintype (a ⟶ b) := fun a b => Fintype.ofFinite (a ⟶ b)
  have h0 : ∀ i : R, relPathsInto r 0 i = ⊥ := fun i => by
    refine (Submodule.eq_bot_iff _).2 fun F hF => ?_
    obtain ⟨Y, -, Z, -, hF⟩ :=
      exists_eq_of_mem_span_of_mem_pathsInto h2 hl hr (mem_relPathsInto.1 hF).2
        (mem_relPathsInto.1 hF).1
    simpa using hF
  obtain _ | _ | n := n
  · exact h0 j
  swap
  · omega
  · refine (Submodule.eq_bot_iff _).2 fun F hF => ?_
    obtain ⟨Y, -, Z, hZ, hF⟩ :=
      exists_eq_of_mem_span_of_mem_pathsInto h2 hl hr (mem_relPathsInto.1 hF).2
        (mem_relPathsInto.1 hF).1
    have hZ0 : ∀ i (b : i ⟶ j), Z i b = 0 := fun i b =>
      (Submodule.mem_bot k).1 (h0 i ▸ mem_relPathsInto.2 ⟨(hZ i b).2, (hZ i b).1⟩)
    simpa [hZ0] using hF

end Degrees

section Main

variable {k} [Field k] [Fintype R] [∀ a b : R, Fintype (a ⟶ b)]

/-- **The Anick-type inequality for one quadratic corner relation per vertex.** Let each vertex `v`
of `R` carry a relator `r_v` of path length two in the corner `e_v kR e_v`, and write `d_n(j)` for
the dimension of the image in `kR / (r_v)` of the span of the paths of length `n` into `j`. Then
`∑_{b : i ⟶ j} d_{m+1}(i) ≤ d_{m+2}(j) + d_m(j)`, the vertexwise form of the coefficientwise
inequality `H_A(t) (1 - C t + t²) ≥ 1` for the matrix Hilbert series of the quotient. -/
theorem sum_card_mul_finrank_map_pathsInto_le_add (r : R → pathAlgebra k R)
    (h2 : ∀ v, r v ∈ grade k R 2) (hl : ∀ v, vertexIdempotent k v * r v = r v)
    (hr : ∀ v, r v * vertexIdempotent k v = r v) (m : ℕ) (j : R) :
    ∑ i, Fintype.card (i ⟶ j) * Module.finrank k ((pathsInto k (m + 1) i).map
        (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap) ≤
      Module.finrank k ((pathsInto k (m + 2) j).map
          (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap) +
        Module.finrank k ((pathsInto k m j).map
          (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap) := by
  have hdK := finrank_map_add_finrank_relPathsInto r
  have hb := finrank_relPathsInto_add_le h2 hl hr m j
  have hc : ∑ i, Fintype.card (i ⟶ j) * Nat.card (PathInto R (m + 1) i) ≤
      Nat.card (PathInto R (m + 2) j) := (card_arrow_mul_card_pathInto_eq (m + 1) j).le
  have hsum : ∑ i, Fintype.card (i ⟶ j) * Module.finrank k ((pathsInto k (m + 1) i).map
      (Ideal.Quotient.mkₐ k (TwoSidedIdeal.span (Set.range r)).asIdeal).toLinearMap) +
      ∑ i, Fintype.card (i ⟶ j) * Module.finrank k (relPathsInto r (m + 1) i) =
        ∑ i, Fintype.card (i ⟶ j) * Nat.card (PathInto R (m + 1) i) := by
    rw [← Finset.sum_add_distrib]
    exact Finset.sum_congr rfl fun i _ => by rw [← mul_add, hdK]
  have e1 : Module.finrank k (pathsInto k m j) = Nat.card (PathInto R m j) :=
    finrank_pathsInto k m j
  have e2 := hdK (m + 2) j
  have e0 := hdK m j
  omega

/-- **A path algebra with one quadratic corner relation per vertex is infinite-dimensional when
its arrow counts admit a suitable weight.** Let `R` be a finite quiver with finitely many arrows
and let each vertex `v` carry a relator `r_v` of path length two in the corner `e_v kR e_v`.
Suppose a nonzero nonnegative weight `δ` on the vertices satisfies `2 δ_i ≤ ∑_j #(i ⟶ j) δ_j` at
every vertex. Then `kR / (r_v)` is not a finite-dimensional `k`-vector space.

For the doubled quiver of a graph, `#(i ⟶ j)` is the adjacency matrix `A` and the hypothesis reads
`(2I - A) δ ≤ 0`. -/
theorem not_module_finite_quotient_span_range_of_two_mul_le_sum {S : Type*} [CommRing S]
    [LinearOrder S] [IsStrictOrderedRing S] (r : R → pathAlgebra k R)
    (h2 : ∀ v, r v ∈ grade k R 2) (hl : ∀ v, vertexIdempotent k v * r v = r v)
    (hr : ∀ v, r v * vertexIdempotent k v = r v) {δ : R → S} (hδ0 : 0 ≤ δ) (hδ : δ ≠ 0)
    (hδle : ∀ i, 2 * δ i ≤ ∑ j, (Fintype.card (i ⟶ j) : S) * δ j) :
    ¬ Module.Finite k (pathAlgebra k R ⧸ (TwoSidedIdeal.span (Set.range r)).asIdeal) := by
  intro hfin
  set N := Module.finrank k (pathAlgebra k R ⧸ (TwoSidedIdeal.span (Set.range r)).asIdeal)
  -- `d n j` is the dimension of the image in the quotient of the paths of length `n` into `j`.
  obtain ⟨d, hdN, hdK, h2'⟩ : ∃ d : ℕ → R → ℕ, (∀ n j, d n j ≤ N) ∧
      (∀ n j, d n j + Module.finrank k (relPathsInto r n j) = Nat.card (PathInto R n j)) ∧
      ∀ m j, ∑ i, Fintype.card (i ⟶ j) * d (m + 1) i ≤ d (m + 2) j + d m j :=
    ⟨_, fun n j => Submodule.finrank_le _, finrank_map_add_finrank_relPathsInto r,
      sum_card_mul_finrank_map_pathsInto_le_add r h2 hl hr⟩
  have hK01 : ∀ n j, n < 2 → Module.finrank k (relPathsInto r n j) = 0 := fun n j hn => by
    rw [relPathsInto_eq_bot_of_lt_two h2 hl hr hn j, finrank_bot]
  -- The Anick-type inequalities for the dimensions `d n j`.
  have h0 : ∀ j, 1 ≤ d 0 j := by
    intro j
    have := hdK 0 j
    rw [hK01 0 j (by norm_num), add_zero] at this
    rw [this]
    exact Nat.one_le_iff_ne_zero.2 (Nat.card_ne_zero.2 ⟨⟨⟨⟨j, Path.nil⟩, rfl⟩⟩, inferInstance⟩)
  have h1 : ∀ j, ∑ i, Fintype.card (i ⟶ j) * d 0 i ≤ d 1 j := by
    intro j
    have hj := hdK 1 j
    rw [hK01 1 j (by norm_num), add_zero] at hj
    have hi : ∀ i, d 0 i = Nat.card (PathInto R 0 i) := fun i => by
      have := hdK 0 i
      rwa [hK01 0 i (by norm_num), add_zero] at this
    simp only [hi]
    exact (card_arrow_mul_card_pathInto_eq 0 j).le.trans hj.ge
  -- The weighted sums grow linearly but are bounded by `N ∑ δ`.
  have hpos : 0 < ∑ j, δ j := by
    obtain ⟨i, hi⟩ := Function.ne_iff.1 hδ
    exact Finset.sum_pos' (fun j _ => hδ0 j) ⟨i, Finset.mem_univ i, lt_of_le_of_ne (hδ0 i)
      (Ne.symm hi)⟩
  have hgrow := add_one_mul_sum_mul_le_sum_mul (fun i j => (Fintype.card (i ⟶ j) : S)) hδ0 hδle
    (d := fun n j => (d n j : S)) (fun _ _ => Nat.cast_nonneg _)
    (fun j => by exact_mod_cast h1 j) (fun m j => by exact_mod_cast h2' m j) N
  have hs0 : ∑ j, δ j ≤ ∑ j, δ j * (d 0 j : S) :=
    Finset.sum_le_sum fun j _ => le_mul_of_one_le_right (hδ0 j) (by exact_mod_cast h0 j)
  have hbound : ∑ j, δ j * (d N j : S) ≤ (N : S) * ∑ j, δ j := by
    rw [Finset.mul_sum]
    exact Finset.sum_le_sum fun j _ => by
      rw [mul_comm (N : S)]
      exact mul_le_mul_of_nonneg_left (Nat.cast_le.2 (hdN N j)) (hδ0 j)
  have := mul_le_mul_of_nonneg_left hs0 (by positivity : (0 : S) ≤ (N : S) + 1)
  linarith

end Main

end PathAlgebra

end TauCeti
