/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.Spin.SpinorNorm.Basic
import Mathlib.GroupTheory.Index
import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-!
# The range of the orthogonal spinor norm

On a nonzero finite-dimensional nondegenerate quadratic space in characteristic different from
two, the special orthogonal group has index two in the orthogonal group. Consequently the
orthogonal spinor-norm image is generated by the special orthogonal image and the class of any
anisotropic reflection.
This reduces the orthogonal column of a local spinor-norm calculation to the special orthogonal
column and one value of the quadratic form.

## References

O. T. O'Meara, *Introduction to Quadratic Forms*, §55.
-/

public section

namespace CliffordAlgebra

open TauCeti QuadraticMap

universe u v

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V]
  [FiniteDimensional K V] [Invertible (2 : K)]

/-- The image of the spinor norm on `O(Q)` is generated by its image on `SO(Q)` and the square
class of the norm of any anisotropic vector. -/
theorem spinorNorm_range_orthogonal_eq_sup (Q : QuadraticForm K V)
    (hQ : Q.Nondegenerate) (v : V) [Invertible (Q v)] :
    (orthogonalSpinorNorm Q hQ).range =
      (spinorNorm Q hQ).range ⊔
        Subgroup.zpowers (squareClassHom (unitOfInvertible (Q v))) := by
  have hv : v ≠ 0 := by
    intro he
    have hzero : Q v = 0 := by rw [he]; simp
    exact Invertible.ne_zero (Q v) hzero
  let _ : Nontrivial V := nontrivial_of_ne v 0 hv
  let r : TauCeti.QuadraticMap.orthogonalGroup Q := reflectionOrthogonal Q v
  have hreflection : orthogonalSpinorNorm Q hQ r =
      squareClassHom (unitOfInvertible (Q v)) :=
    orthogonalSpinorNorm_reflectionOrthogonal Q hQ v
  have hso (g : TauCeti.QuadraticMap.orthogonalGroup Q)
      (hg : g ∈ specialOrthogonalWithin Q) :
      orthogonalSpinorNorm Q hQ g ∈ (spinorNorm Q hQ).range := by
    have hg' : g ∈ (specialOrthogonalToOrthogonal Q).range := by
      simpa only [range_specialOrthogonalToOrthogonal] using hg
    obtain ⟨s, hs⟩ := hg'
    refine ⟨s, ?_⟩
    rw [spinorNorm_apply, hs]
  have hneg : (-1 : Kˣ) ≠ 1 := by
    intro h
    have h' : (-1 : K) = 1 := congrArg Units.val h
    exact NeZero.ne (2 : K) (by linear_combination -h')
  have hrnot : r ∉ specialOrthogonalWithin Q := by
    intro hr
    have hdet : orthogonalDet Q r = 1 := by
      rw [orthogonalDet_apply]
      exact mem_specialOrthogonalWithin_iff.mp hr
    exact hneg (by simpa only [r, orthogonalDet_reflectionOrthogonal] using hdet)
  have hindex : (specialOrthogonalWithin Q).index = 2 :=
    index_specialOrthogonalWithin hQ
  apply le_antisymm
  · rintro x ⟨g, rfl⟩
    by_cases hg : g ∈ specialOrthogonalWithin Q
    · exact Subgroup.mem_sup_left (hso g hg)
    · have hgr : g * r ∈ specialOrthogonalWithin Q := by
        rw [Subgroup.mul_mem_iff_of_index_two hindex]
        exact iff_of_false hg hrnot
      have hrr : r * r = 1 := reflectionOrthogonal_mul_self Q v
      have hdecomp : g = (g * r) * r := by rw [mul_assoc, hrr, mul_one]
      rw [hdecomp, map_mul, hreflection]
      exact Subgroup.mul_mem_sup (hso (g * r) hgr) (Subgroup.mem_zpowers _)
  · refine sup_le ?_ ?_
    · rintro x ⟨s, rfl⟩
      exact ⟨specialOrthogonalToOrthogonal Q s, (spinorNorm_apply Q hQ s).symm⟩
    · apply Subgroup.zpowers_le.mpr
      rw [← hreflection]
      exact ⟨r, rfl⟩

end CliffordAlgebra
