/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.Basis.Defs
public import Mathlib.RingTheory.Localization.Integer
public import Mathlib.RingTheory.Ideal.Maps
import Mathlib.Algebra.Algebra.Tower
import Mathlib.RingTheory.Localization.Finiteness

/-!
# Clearing a finite family of denominators in a localization

Mathlib's `IsLocalization.finsetIntegerMultiple` simultaneously clears the denominators of a
finite family in a localization. This file records how those cleared elements map back into the
localization and the resulting identity between the ideals generated before and after clearing.
Applied to a basis over a localization and pulled back along an injective algebra map, Mathlib's
`multiple_mem_span_of_mem_localization_span` puts a multiple of every element by an element of the
localizing submonoid in the span of lifts of the basis.

## Main results

* `TauCeti.IsLocalization.algebraMap_integerMultiple`: the cleared representative maps to the
  original element multiplied by the common denominator.
* `TauCeti.IsLocalization.finsetIntegerMultiple_image_algebraMap`: the image of the finite family
  of cleared representatives is the original family multiplied by the common denominator.
* `TauCeti.IsLocalization.map_span_finsetIntegerMultiple`: the ideal generated by the cleared
  representatives maps to the ideal generated by the original family.
* `TauCeti.IsLocalization.exists_smul_mem_span_basis`: given a basis of `L` over a localization
  `K` of `A` at `M`, every element of an `A`-algebra `B` embedded in `L` has a multiple by an
  element of `M` in the `A`-span of lifts of the basis to `B`.
-/

public section

namespace TauCeti.IsLocalization

section

variable {A S : Type*} [CommSemiring A] [CommSemiring S] [Algebra A S]

/-- The image of an integer multiple used to clear a finite family of denominators is the
original element multiplied by the image of the common denominator. -/
lemma algebraMap_integerMultiple (M : Submonoid A) [IsLocalization M S] (T : Finset S)
    (x : T) : algebraMap A S (IsLocalization.integerMultiple M T id x) =
      (x : S) * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  rw [IsLocalization.map_integerMultiple, Submonoid.smul_def, Algebra.smul_def]
  exact mul_comm _ _

/-- The image of the finite family obtained by clearing denominators is the original family
multiplied by the image of its common denominator. -/
lemma finsetIntegerMultiple_image_algebraMap (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] [DecidableEq S] (T : Finset S) :
    (IsLocalization.finsetIntegerMultiple M T).image (algebraMap A S) =
      T.image fun x ↦ x * algebraMap A S (IsLocalization.commonDenomOfFinset M T : A) := by
  apply Finset.coe_injective
  rw [Finset.coe_image, Finset.coe_image, IsLocalization.finsetIntegerMultiple_image,
    ← Set.image_smul]
  exact Set.image_congr' fun x ↦ by rw [Submonoid.smul_def, Algebra.smul_def, mul_comm]

open scoped Pointwise in
/-- Clearing the denominators of a finite family does not change the ideal it generates after
mapping to the localization. -/
lemma map_span_finsetIntegerMultiple (M : Submonoid A) [IsLocalization M S]
    [DecidableEq A] (T : Finset S) :
    Ideal.map (algebraMap A S) (Ideal.span (IsLocalization.finsetIntegerMultiple M T : Set A)) =
      Ideal.span (T : Set S) := by
  rw [Ideal.map_span, IsLocalization.finsetIntegerMultiple_image, Submonoid.smul_def,
    ← IsScalarTower.algebraMap_smul S]
  exact Submodule.span_smul_eq_of_isUnit _ _ (IsLocalization.map_units S _)

end

section

variable {A K L B : Type*} [CommSemiring A] [CommSemiring K] [CommSemiring B] [Semiring L]
  [Algebra A K] [Algebra B L] [Algebra A B] [Algebra K L] [Algebra A L]
  [IsScalarTower A K L] [IsScalarTower A B L]

/-- If `B` embeds in `L` and `K` is a localization of `A` at `M`, every element of `B` has a
multiple by an element of `M` in the `A`-span of lifts in `B` of a `K`-basis of `L`. -/
theorem exists_smul_mem_span_basis (M : Submonoid A) [IsLocalization M K] {ι : Type*}
    (b : Module.Basis ι K L) (b' : ι → B)
    (hb' : ∀ i, algebraMap B L (b' i) = b i)
    (hinj : Function.Injective (algebraMap B L)) (x : B) :
    ∃ a ∈ M, a • x ∈ Submodule.span A (Set.range b') := by
  let f := (IsScalarTower.toAlgHom A B L).toLinearMap
  have hb : Set.range b = f '' Set.range b' := by
    rw [← Set.range_comp]
    exact congrArg Set.range (funext fun i ↦ (hb' i).symm)
  obtain ⟨⟨a, ha⟩, hax⟩ := multiple_mem_span_of_mem_localization_span M K (Set.range b)
    (algebraMap B L x) (b.mem_span _)
  rw [hb, ← Submodule.map_span, Submodule.mem_map] at hax
  obtain ⟨y, hy, hyx⟩ := hax
  refine ⟨a, ha, ?_⟩
  rwa [← hinj (hyx.trans (map_smul f a x).symm)]

end

end TauCeti.IsLocalization

end
