/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Index.Discriminant
public import TauCeti.NumberTheory.NumberField.IntrinsicLabel
public import TauCeti.NumberTheory.NumberField.Monogenic
public import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
public import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import Mathlib.Algebra.Squarefree.Basic
import Mathlib.Tactic.NormNum.Prime

/-!
# Arithmetic invariants of the cubic of discriminant −23

Let `K` be generated by an algebraic integer `θ` with minimal polynomial `X³ - X² + 1`.
Its polynomial discriminant is the squarefree integer `−23`, so the index formula forces
`ℤ[θ] = 𝓞 K` and `discr K = −23`. The degree and discriminant sign then give signature
`(1, 1)`, unit rank one, and intrinsic label prefix `3.1.23`. The field is not Galois and
has no proper intermediate fields.

These computations provide the field discriminant and signature used to certify units by
excluding competing minimal polynomials. No integral-basis or field-discriminant assumption
is made.

## References

* D. A. Marcus, *Number Fields*, Chapters 2–4, for the index–discriminant method.
-/

public section

open Polynomial NumberField NumberField.InfinitePlace
open scoped NumberField

namespace TauCeti.NumberField.Cubic23

/-- The discriminant of the defining cubic is `−23`. -/
@[simp]
theorem discr_polynomial : (X ^ 3 - X ^ 2 + 1 : ℤ[X]).discr = -23 := by
  rw [Polynomial.discr_of_degree_eq_three (by compute_degree <;> norm_num)]
  norm_num [coeff_add, coeff_sub, coeff_X_pow, coeff_one]

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}
  (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
  (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)

include hmin hgen

/-- The field generated by the defining cubic has degree three. -/
theorem finrank_eq_three : Module.finrank ℚ K = 3 := by
  let t : IntegralPrimitiveElement K := ⟨θ, hgen⟩
  rw [← _root_.NumberField.RingOfIntegers.rank K, ← t.finrank_adjoin,
    IntegralPrimitiveElement.adjoin_def, (Algebra.adjoin.powerBasis' θ.isIntegral).finrank,
    Algebra.adjoin.powerBasis'_dim, hmin]
  compute_degree <;> norm_num

/-- The defining generator has index one in the full ring of integers. -/
theorem index_eq_one :
    IntegralPrimitiveElement.index (⟨θ, hgen⟩ : IntegralPrimitiveElement K) = 1 := by
  let t : IntegralPrimitiveElement K := ⟨θ, hgen⟩
  have hd := t.discr_minpoly_eq_index_sq_mul_discr
  simp only [t] at hd
  rw [hmin, discr_polynomial] at hd
  have hsf : Squarefree (-23 : ℤ) := by
    apply Int.squarefree_natAbs.mp
    exact (by norm_num : Nat.Prime 23).squarefree
  have hu : IsUnit (t.index : ℤ) := hsf _ (by rw [← sq]; exact ⟨_, hd⟩)
  exact_mod_cast Int.isUnit_iff_natAbs_eq.mp hu

/-- The powers of `θ` span the full ring of integers as a `ℤ`-algebra. -/
theorem adjoin_eq_top : Algebra.adjoin ℤ {θ} = ⊤ := by
  rw [← IntegralPrimitiveElement.adjoin_def ⟨θ, hgen⟩]
  exact (IntegralPrimitiveElement.index_eq_one_iff ⟨θ, hgen⟩).mp (index_eq_one hmin hgen)

/-- The cubic field is monogenic, generated integrally by `θ`. -/
theorem isMonogenic : IsMonogenic K :=
  isMonogenic_def.mpr ⟨θ, adjoin_eq_top hmin hgen⟩

/-- The signed field discriminant is `−23`. -/
theorem discr_eq_neg_twenty_three : discr K = -23 := by
  have hd := IntegralPrimitiveElement.discr_minpoly_eq_index_sq_mul_discr ⟨θ, hgen⟩
  rw [hmin, discr_polynomial, index_eq_one hmin hgen] at hd
  simpa using hd.symm

/-- There is exactly one complex infinite place. -/
theorem nrComplexPlaces_eq_one : nrComplexPlaces K = 1 := by
  have hr := card_add_two_mul_card_eq_rank K
  rw [finrank_eq_three hmin hgen] at hr
  have hs := sign_discr K
  rw [discr_eq_neg_twenty_three hmin hgen, Int.sign_eq_neg_one_of_neg (by decide)] at hs
  have hc : nrComplexPlaces K ≤ 1 := by omega
  rcases Nat.le_one_iff_eq_zero_or_eq_one.mp hc with h | h
  · norm_num [h] at hs
  · exact h

/-- There is exactly one real infinite place. -/
theorem nrRealPlaces_eq_one : nrRealPlaces K = 1 := by
  have h := card_add_two_mul_card_eq_rank K
  rw [finrank_eq_three hmin hgen, nrComplexPlaces_eq_one hmin hgen] at h
  omega

/-- The intrinsic label prefix is `3.1.23`. -/
theorem hasLMFDBIntrinsicLabel : HasLMFDBIntrinsicLabel K 3 1 23 := by
  rw [hasLMFDBIntrinsicLabel_iff]
  refine ⟨finrank_eq_three hmin hgen, nrRealPlaces_eq_one hmin hgen, ?_⟩
  rw [discr_eq_neg_twenty_three hmin hgen]
  norm_num

/-- The unit group has rank one. -/
theorem units_rank_eq_one : NumberField.Units.rank K = 1 := by
  rw [NumberField.Units.rank, card_eq_nrRealPlaces_add_nrComplexPlaces,
    nrRealPlaces_eq_one hmin hgen, nrComplexPlaces_eq_one hmin hgen]

/-- The cubic field has no intermediate fields other than the base and the whole field. -/
theorem intermediateField_eq_bot_or_eq_top (E : IntermediateField ℚ K) : E = ⊥ ∨ E = ⊤ := by
  have := IntermediateField.isSimpleOrder_of_finrank_prime ℚ K
    (show Nat.Prime (Module.finrank ℚ K) by rw [finrank_eq_three hmin hgen]; norm_num)
  exact eq_bot_or_eq_top E

/-- The cubic field is not Galois over `ℚ`: its signature is mixed. -/
theorem not_isGalois : ¬ IsGalois ℚ K := by
  intro h
  have : IsUnramifiedAtInfinitePlaces ℚ K :=
    IsUnramifiedAtInfinitePlaces_of_odd_finrank
      (show Odd (Module.finrank ℚ K) by rw [finrank_eq_three hmin hgen]; decide)
  have : IsTotallyReal K := IsTotallyReal.of_isUnramifiedAtInfinitePlaces (k := ℚ)
  have hz := IsTotallyReal.nrComplexPlaces_eq_zero (K := K)
  rw [nrComplexPlaces_eq_one hmin hgen] at hz
  contradiction

end TauCeti.NumberField.Cubic23
