/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E6.Minuscule.ClosedRootSubgroup
public import
  TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.PositiveSubsystem

/-!
# The positive subsystem of the E6 minuscule carrier

This file constructs the closed subgroup scheme of the type-`E₆` minuscule carrier generated by
the six positive simple-root subgroups and the weight torus. The explicit ordering of the
twenty-seven minuscule weights puts every raising root operator above the diagonal. Consequently the
positive subsystem is a closed subgroup of the standard upper-triangular group scheme, and all of
its algebra-valued point groups are solvable.

This is the scheme-theoretic candidate for the Borel member of a pinning. It is not called a Borel
subgroup here: smoothness, connectedness, and maximality among solvable subgroup schemes remain to
be proved.

## Main definitions

* `TauCeti.E6Minuscule.positiveSubsystemGroupScheme`: the torus-plus-positive-simple-root
  subgroup scheme.
* `TauCeti.E6Minuscule.positiveSubsystemInclusion`: its closed immersion into the full minuscule
  carrier.
* `TauCeti.E6Minuscule.positiveRootSubgroup`: a positive simple-root subgroup factored through
  the positive subsystem.
* `TauCeti.E6Minuscule.positiveWeightTorus`: the weight torus factored through the positive
  subsystem.
* `TauCeti.E6Minuscule.positiveSubsystemToUpperTriangular`: its canonical upper-triangular
  realization.

## Main results

* `TauCeti.E6Minuscule.positiveRootWeight_strict`: positive simple roots strictly raise the
  explicit ordering of minuscule weights.
* `TauCeti.E6Minuscule.isSolvable_points_positiveSubsystem`: every algebra-valued point group of
  the positive subsystem is solvable.

## References

* The type-`E₇` positive subsystem construction in `TauCeti.Algebra.Lie.E7.Minuscule`, introduced
  in [TauCetiProject/TauCeti#9054](https://github.com/TauCetiProject/TauCeti/pull/9054), for the
  interface and proof organization specialized here.
* J. E. Humphreys, *Linear Algebraic Groups*, Sections 26--28.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 4.4 and 8.2.
-/

public section

open scoped Matrix

universe v

namespace TauCeti.E6Minuscule

open AlgebraicGeometry CategoryTheory
open TauCeti.DynkinType
open TauCeti.UniversalEnvelopingAlgebra
open scoped CategoryTheory.MonObj TensorProduct

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => weightTable.cartanMatrix
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => TauCeti.E6.rootGeneratorWeight
local notation "rootWeight6" =>
  (fun k : Fin 6 ⊕ Fin 6 => fun j : Fin 6 => rootWeight k j)
local notation "Λ" => TauCeti.coordinateLattice (Fin 27)
local notation "𝓑" => TauCeti.coordinateLatticeBasis (Fin 27)

/-! ## The positive weight order -/

/-- The numbered positive simple roots among the twelve signed simple-root generators. -/
def positiveSimpleRoots : Set (Fin 6 ⊕ Fin 6) := Set.range Sum.inl

@[simp]
theorem inl_mem_positiveSimpleRoots (i : Fin 6) : Sum.inl i ∈ positiveSimpleRoots :=
  Set.mem_range_self i

@[simp]
theorem inr_not_mem_positiveSimpleRoots (i : Fin 6) : Sum.inr i ∉ positiveSimpleRoots := by
  simp [positiveSimpleRoots]

/-- The character of a positive numbered root generator is the corresponding Cartan row. -/
private theorem rootWeight6_inl (i : Fin 6) : rootWeight6 (.inl i) = CM i := by
  funext j
  simp only [TauCeti.E6.rootGeneratorWeight_inl, weightTable_cartanMatrix,
    Matrix.transpose_apply, (CartanMatrix.E_isSymm 6).apply]

/-- The numbered root generators have the characters used by the positive subsystem. -/
private theorem lie_cartanGen_rootGen (k : Fin 6 ⊕ Fin 6) (j : Fin 6) :
    ⁅cartanGen j, rootGen k⁆ = ((rootWeight6 k j : ℤ) : ℚ) • rootGen k := by
  rw [weightTable_cartanMatrix]
  exact TauCeti.E6.lie_serreH_rootGenerator k j

/-- **Every positive simple root strictly raises the ordered minuscule weight basis.** If two
weights differ by a positive multiple of a positive simple root, the raised weight occurs earlier
in the explicit table. -/
theorem positiveRootWeight_strict (k : Fin 6 ⊕ Fin 6) (hk : k ∈ positiveSimpleRoots)
    {r s : Fin 27} {m : ℕ} (hm : 0 < m)
    (hrs : weightTable.weight r = weightTable.weight s + m • rootWeight6 k) : r < s := by
  rw [weightTable_weight] at hrs
  obtain ⟨i, rfl⟩ := hk
  rw [rootWeight6_inl] at hrs
  have hcoord := congrFun hrs i
  have hr := e6MinusculeWeight_apply_eq_neg_one_or_eq_zero_or_eq_one r i
  have hs := e6MinusculeWeight_apply_eq_neg_one_or_eq_zero_or_eq_one s i
  have hdiag : CM i i = 2 := by
    rw [weightTable_cartanMatrix, Matrix.transpose_apply, CartanMatrix.E_diag]
  simp only [Pi.add_apply, nsmul_eq_mul, Pi.mul_apply, Pi.natCast_apply, hdiag] at hcoord
  have hm_one : m = 1 := by
    rcases hr with hr | hr | hr <;> rcases hs with hs | hs | hs <;> omega
  have hs_neg : e6MinusculeWeight s i = -1 := by
    rcases hr with hr | hr | hr <;> rcases hs with hs | hs | hs <;> omega
  have hreflection :
      e6MinusculeWeight (e6MinusculeReflection i s) = e6MinusculeWeight s + CM i := by
    rw [e6MinusculeWeight_reflection, root_e6SimpleIndex, hs_neg,
      weightTable_cartanMatrix]
    simp
  have hr_reflection : r = e6MinusculeReflection i s := by
    apply e6MinusculeWeight_injective
    rw [hm_one, one_nsmul] at hrs
    exact hrs.trans hreflection.symm
  rw [hr_reflection]
  exact (e6MinusculeReflection_lt_iff i s).2 hs_neg

/-! ## The positive subsystem and its generators -/

/-- The Hopf ideal cutting out the positive subsystem inside `GL₂₇`. -/
noncomputable def positiveSubsystemDefiningIdeal :
    HopfIdeal ℤ (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 27) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemDefiningIdeal rootGen cartanGen
    weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
    positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)

/-- The positive subsystem defining ideal is the generic torus-subsystem common-kernel ideal. -/
theorem positiveSubsystemDefiningIdeal_def :
    positiveSubsystemDefiningIdeal =
      TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemDefiningIdeal rootGen cartanGen
        weightTable.rep
        (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
        positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) := by
  rw [positiveSubsystemDefiningIdeal]

/-- **Coordinate universal property of the positive subsystem.** A Hopf ideal is contained in
the positive defining ideal exactly when every positive simple-root coordinate map and the weight
torus coordinate map kill it. -/
theorem le_positiveSubsystemDefiningIdeal_iff
    (J : HopfIdeal ℤ (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 27)) :
    J ≤ positiveSubsystemDefiningIdeal ↔
      (∀ i : Fin 6, J.toIdeal ≤ RingHom.ker
        (kostantRootSubgroupCoordinateMap rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
          weightTable.rep_kostantForm_mem_lattice (.inl i)
          (weightTable.isNilpotent_rep_serreRootGenerator (.inl i)) 𝓑).hom.toAlgHom.toRingHom) ∧
      J.toIdeal ≤ RingHom.ker
        (TauCeti.GeneralLinear.weightTorusCoordinateMap
          weightTable.weight).hom.toAlgHom.toRingHom := by
  rw [positiveSubsystemDefiningIdeal_def]
  have hiff := le_kostantTorusSubsystemDefiningIdeal_iff rootGen cartanGen weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
    positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) J
  constructor
  · intro hJ
    have h := hiff.mp hJ
    exact ⟨fun i => h.1 (.inl i) (inl_mem_positiveSimpleRoots i), h.2⟩
  · rintro ⟨hroot, htorus⟩
    apply hiff.mpr
    refine ⟨?_, htorus⟩
    intro i hi
    obtain ⟨j, rfl⟩ := hi
    exact hroot j

/-- **The positive subsystem of the type-`E₆` minuscule carrier**, generated by the six
positive simple-root subgroups and the represented weight torus. -/
noncomputable def positiveSubsystemGroupScheme : Grp (Over (Spec (CommRingCat.of ℤ))) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemGroupScheme rootGen cartanGen
    weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
    positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)

/-- The positive carrier is the generic Kostant torus-subsystem for the positive simple roots. -/
theorem positiveSubsystemGroupScheme_def :
    positiveSubsystemGroupScheme =
      TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemGroupScheme rootGen cartanGen
        weightTable.rep
        (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
        positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) := by
  rw [positiveSubsystemGroupScheme]

/-- The positive subsystem is the quotient spectrum cut out by its named defining ideal. -/
theorem positiveSubsystemGroupScheme_eq_quotientSpec :
    positiveSubsystemGroupScheme =
      CommHopfAlgCat.quotientSpec (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 27)
        positiveSubsystemDefiningIdeal := by
  rw [positiveSubsystemGroupScheme_def, positiveSubsystemDefiningIdeal_def]

/-- The canonical inclusion of the positive subsystem into the full minuscule carrier. -/
noncomputable def positiveSubsystemInclusion : positiveSubsystemGroupScheme ⟶ groupScheme :=
  eqToHom positiveSubsystemGroupScheme_def ≫
    TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemToToral rootGen cartanGen
      weightTable.rep
      (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
      weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots

/-- Including the positive subsystem into the carrier and then into `GL₂₇` recovers its
direct Kostant subsystem inclusion. -/
@[simp]
theorem positiveSubsystemInclusion_comp_carrierι :
    positiveSubsystemInclusion ≫ carrierι =
      eqToHom positiveSubsystemGroupScheme_def ≫
        TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemGroupSchemeι rootGen cartanGen
          weightTable.rep
          (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
          positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1) := by
  rw [positiveSubsystemInclusion, carrierι_def]
  simpa only [Category.assoc] using congrArg
    (fun f => eqToHom positiveSubsystemGroupScheme_def ≫ f)
    (TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemToToral_comp_ι
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
      weightTable.weight weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots)

/-- The positive subsystem is a closed subgroup scheme of the full minuscule carrier. -/
instance isClosedImmersion_positiveSubsystemInclusion :
    IsClosedImmersion positiveSubsystemInclusion.hom.hom.left := by
  rw [← closedSubgroupMorphismProperty_iff, positiveSubsystemInclusion,
    (closedSubgroupMorphismProperty _).cancel_left_of_respectsIso,
    closedSubgroupMorphismProperty_iff]
  exact TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantTorusSubsystemToToral
    rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
    weightTable.weight weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots

/-- The positive subsystem bundled as a closed subgroup scheme of the full minuscule carrier. -/
noncomputable def positiveSubsystemClosedSubgroup : ClosedSubgroupScheme groupScheme :=
  ClosedSubgroupScheme.mk positiveSubsystemInclusion

/-- The underlying subobject of the positive subsystem is represented by its canonical
inclusion. -/
@[simp]
theorem coe_positiveSubsystemClosedSubgroup :
    positiveSubsystemClosedSubgroup.1 = Subobject.mk positiveSubsystemInclusion :=
  ClosedSubgroupScheme.coe_mk _

/-- The named positive closed subgroup agrees with the generic Kostant torus subsystem. -/
theorem positiveSubsystemClosedSubgroup_eq_kostantTorusSubsystemClosedSubgroup :
    positiveSubsystemClosedSubgroup =
      kostantTorusSubsystemClosedSubgroup rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
        weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
        weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots := by
  apply Subtype.ext
  rw [coe_positiveSubsystemClosedSubgroup, coe_kostantTorusSubsystemClosedSubgroup]
  exact Subobject.mk_eq_mk_of_comm _ _ (eqToIso positiveSubsystemGroupScheme_def) (by
    rw [eqToIso.hom, positiveSubsystemInclusion])

/-- The `i`-th positive simple-root subgroup factored through the positive subsystem. -/
noncomputable def positiveRootSubgroup (i : Fin 6) :
    AdditiveGroup.groupScheme ℤ ⟶ positiveSubsystemGroupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToTorusSubsystem rootGen cartanGen
    weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
    positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1)
    (inl_mem_positiveSimpleRoots i) ≫ eqToHom positiveSubsystemGroupScheme_def.symm

/-- Factoring a positive root subgroup through the positive subsystem and including it into the
full carrier recovers the named root subgroup. -/
@[simp]
theorem positiveRootSubgroup_comp_positiveSubsystemInclusion (i : Fin 6) :
    positiveRootSubgroup i ≫ positiveSubsystemInclusion = rootSubgroup (.inl i) := by
  rw [positiveRootSubgroup, positiveSubsystemInclusion, rootSubgroup_def]
  exact kostantRootSubgroupToTorusSubsystem_comp_kostantTorusSubsystemToToral
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
      weightTable.weight weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots
      (inl_mem_positiveSimpleRoots i)

/-- Every positive simple-root map into the positive subsystem is a closed immersion. -/
instance isClosedImmersion_positiveRootSubgroup (i : Fin 6) :
    IsClosedImmersion (positiveRootSubgroup i).hom.hom.left := by
  have hcomp : IsClosedImmersion
      ((positiveRootSubgroup i ≫ positiveSubsystemInclusion).hom.hom.left) := by
    rw [positiveRootSubgroup_comp_positiveSubsystemInclusion]
    infer_instance
  simp only [Grp.comp', Mon.comp_hom', Over.comp_left] at hcomp
  have _ := hcomp
  exact IsClosedImmersion.of_comp
    (f := (positiveRootSubgroup i).hom.hom.left)
    (g := positiveSubsystemInclusion.hom.hom.left)

/-- The represented weight torus factored through the positive subsystem. -/
noncomputable def positiveWeightTorus :
    SplitTorus.groupScheme ℤ (Fin 6) ⟶ positiveSubsystemGroupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToTorusSubsystem rootGen cartanGen
    weightTable.rep
    (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
    positiveSimpleRoots (fun k => weightTable.isNilpotent_rep_serreRootGenerator k.1) ≫
      eqToHom positiveSubsystemGroupScheme_def.symm

/-- Factoring the weight torus through the positive subsystem and including it into the full
carrier recovers the named weight torus. -/
@[simp]
theorem positiveWeightTorus_comp_positiveSubsystemInclusion :
    positiveWeightTorus ≫ positiveSubsystemInclusion = weightTorus := by
  rw [positiveWeightTorus, positiveSubsystemInclusion, weightTorus_def]
  exact kostantWeightTorusToTorusSubsystem_comp_kostantTorusSubsystemToToral
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
      weightTable.weight weightTable.isNilpotent_rep_serreRootGenerator positiveSimpleRoots

/-- The weight torus is a closed subgroup of the positive subsystem. -/
instance isClosedImmersion_positiveWeightTorus :
    IsClosedImmersion positiveWeightTorus.hom.hom.left := by
  have hcomp : IsClosedImmersion
      ((positiveWeightTorus ≫ positiveSubsystemInclusion).hom.hom.left) := by
    rw [positiveWeightTorus_comp_positiveSubsystemInclusion]
    infer_instance
  simp only [Grp.comp', Mon.comp_hom', Over.comp_left] at hcomp
  have _ := hcomp
  exact IsClosedImmersion.of_comp
    (f := positiveWeightTorus.hom.hom.left)
    (g := positiveSubsystemInclusion.hom.hom.left)

/-- **Universal property of the positive subsystem.** It is the smallest closed subgroup scheme
of the full minuscule carrier through which every positive simple-root subgroup and the weight
torus factor. -/
theorem positiveSubsystemClosedSubgroup_le_iff (P : ClosedSubgroupScheme groupScheme) :
    positiveSubsystemClosedSubgroup ≤ P ↔
      (∀ i : Fin 6, ∃! f : AdditiveGroup.groupScheme ℤ ⟶
        (P.1 : Grp (Over (Spec (CommRingCat.of ℤ)))),
          f ≫ P.1.arrow = rootSubgroup (.inl i)) ∧
      ∃! f : SplitTorus.groupScheme ℤ (Fin 6) ⟶
        (P.1 : Grp (Over (Spec (CommRingCat.of ℤ)))),
          f ≫ P.1.arrow = weightTorus := by
  rw [positiveSubsystemClosedSubgroup_eq_kostantTorusSubsystemClosedSubgroup,
    kostantTorusSubsystemClosedSubgroup_le_iff]
  constructor
  · rintro ⟨hroot, htorus⟩
    constructor
    · intro i
      simpa only [rootSubgroup_def] using hroot (.inl i) (inl_mem_positiveSimpleRoots i)
    · simpa only [weightTorus_def] using htorus
  · rintro ⟨hroot, htorus⟩
    constructor
    · intro i hi
      obtain ⟨j, rfl⟩ := hi
      simpa only [rootSubgroup_def] using hroot j
    · simpa only [weightTorus_def] using htorus

/-- **Rigidity of the positive subsystem.** Two homomorphisms from it into an affine group scheme
represented by a commutative Hopf algebra are equal if they agree on every positive simple-root
subgroup and on the weight torus. -/
@[ext]
theorem positiveSubsystemGroupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (φ ψ : positiveSubsystemGroupScheme ⟶
      (hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ i, positiveRootSubgroup i ≫ φ = positiveRootSubgroup i ≫ ψ)
    (htorus : positiveWeightTorus ≫ φ = positiveWeightTorus ≫ ψ) :
    φ = ψ := by
  apply (cancel_epi (eqToHom positiveSubsystemGroupScheme_def.symm)).1
  apply kostantTorusSubsystemGroupScheme_hom_ext rootGen cartanGen weightTable.rep (Λ).toAddSubgroup
    weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight positiveSimpleRoots
    (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)
    (eqToHom positiveSubsystemGroupScheme_def.symm ≫ φ)
    (eqToHom positiveSubsystemGroupScheme_def.symm ≫ ψ)
  · intro i hi
    obtain ⟨j, rfl⟩ := hi
    simpa only [positiveRootSubgroup, Category.assoc] using hroot j
  · simpa only [positiveWeightTorus, Category.assoc] using htorus

/-! ## Upper-triangularity and solvability -/

/-- The canonical closed immersion of the positive subsystem into the standard upper-triangular
group scheme. -/
noncomputable def positiveSubsystemToUpperTriangular :
    positiveSubsystemGroupScheme ⟶ TauCeti.GeneralLinear.UpperTriangular.groupScheme ℤ 27 :=
  eqToHom positiveSubsystemGroupScheme_def ≫
    TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemToUpperTriangular
      rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
      weightTable.weight rootWeight6 positiveSimpleRoots
      (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)
      weightTable.isCartanWeightVector_coordinateLatticeBasis
      (fun i _ => lie_cartanGen_rootGen i)
      positiveRootWeight_strict

/-- The positive subsystem's upper-triangular realization recovers its direct inclusion into
`GL₂₇`. -/
@[simp]
theorem positiveSubsystemToUpperTriangular_comp_inclusion :
    positiveSubsystemToUpperTriangular ≫
        TauCeti.GeneralLinear.UpperTriangular.inclusion ℤ 27 =
      positiveSubsystemInclusion ≫ carrierι := by
  rw [positiveSubsystemToUpperTriangular, positiveSubsystemInclusion_comp_carrierι,
    Category.assoc]
  rw [TauCeti.UniversalEnvelopingAlgebra.kostantTorusSubsystemToUpperTriangular_comp_inclusion
      rootGen cartanGen weightTable.rep
      (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
      rootWeight6 positiveSimpleRoots (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)
      weightTable.isCartanWeightVector_coordinateLatticeBasis
      (fun i _ => lie_cartanGen_rootGen i)
      positiveRootWeight_strict]

/-- The positive subsystem is a closed subgroup scheme of the standard upper-triangular group. -/
instance isClosedImmersion_positiveSubsystemToUpperTriangular :
    IsClosedImmersion positiveSubsystemToUpperTriangular.hom.hom.left := by
  rw [← closedSubgroupMorphismProperty_iff, positiveSubsystemToUpperTriangular,
    (closedSubgroupMorphismProperty _).cancel_left_of_respectsIso,
    closedSubgroupMorphismProperty_iff]
  exact
    TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantTorusSubsystemToUpperTriangular
      rootGen cartanGen weightTable.rep
        (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑 weightTable.weight
        rootWeight6 positiveSimpleRoots
        (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)
        weightTable.isCartanWeightVector_coordinateLatticeBasis
        (fun i _ => lie_cartanGen_rootGen i)
        positiveRootWeight_strict

/-- **Every algebra-valued point group of the positive subsystem is solvable.** -/
theorem isSolvable_points_positiveSubsystem (A : Type v) [CommRing A] :
    Group.IsSolvable
      (HopfAlgebra.points (R := ℤ)
        (H := CommHopfAlgCat.quotient (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 27)
          positiveSubsystemDefiningIdeal)
        (CommAlgCat.of ℤ A)) := by
  rw [positiveSubsystemDefiningIdeal_def]
  exact TauCeti.UniversalEnvelopingAlgebra.isSolvable_points_kostantTorusSubsystem
    rootGen cartanGen weightTable.rep (Λ).toAddSubgroup weightTable.rep_kostantForm_mem_lattice 𝓑
    weightTable.weight rootWeight6 positiveSimpleRoots
    (fun i => weightTable.isNilpotent_rep_serreRootGenerator i.1)
    weightTable.isCartanWeightVector_coordinateLatticeBasis
    (fun i _ => lie_cartanGen_rootGen i)
    positiveRootWeight_strict A

end TauCeti.E6Minuscule
