/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.CommHopfAlgCat.SchemePoints
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.RootSubgroupPoints
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.GroupScheme

/-!
# Presented points of the pinned Geck carrier

`TauCeti.DynkinType.geckPointsPresentation` presents the matrix points of the pinned Geck
carrier by its integral defining Hopf ideal. The shared
`GeneralLinear.IntegralPointsPresentation` API supplies maps of value rings, their functoriality,
and the representing equivalence with quotient-algebra points. The scheme-points equivalence
identifies these matrix points with morphisms into the Geck carrier and carries each numbered
root-subgroup morphism to the existing point-level homomorphism. This file also proves that maps
of value rings preserve the pinned root subgroups and weight torus.

The Geck weights span the root lattice rather than, in general, the full character lattice.
This presentation does not identify the carrier with the simply connected group or its points
with the elementary subgroup generated by its root subgroups.

The matrix-points presentation is universe-polymorphic. The Geck carrier is a scheme over
`Spec ℤ` in universe zero, so its scheme-valued points over `Spec A` use value rings `A : Type`.

## References

* M. Geck, *On the construction of semisimple Lie algebras and Chevalley groups*,
  Proc. Amer. Math. Soc. **145** (2017), 3233--3247.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

open AlgebraicGeometry CategoryTheory WithConv
open scoped CategoryTheory.MonObj

namespace TauCeti.DynkinType

universe v v'

noncomputable section

-- Matrices form a Lie ring through their commutator, which is how Geck's construction reads them.
attribute [local instance 100] LieRing.ofAssociativeRing

attribute [local instance] TauCeti.moduleNNRat

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

/-- The matrix points of the pinned Geck carrier, presented by its integral defining Hopf ideal. -/
abbrev geckPointsPresentation (A : Type v) [CommRing A] :
    TauCeti.GeneralLinear.IntegralPointsPresentation (t.geckDim ht) (t.geckDefiningIdeal ht) A :=
  ⟨t.geckPoints ht A, t.geckPoints_def ht A⟩

/-- Quotient-coordinate points of the Geck carrier, identified with its matrix points. -/
noncomputable def geckCoordinatePointMulEquiv (A : Type v) [CommRing A] :
    HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht) (CommAlgCat.of ℤ A) ≃*
      t.geckPoints ht A :=
  (t.geckPointsPresentation ht (CommAlgCat.of ℤ A)).mulEquiv

/-- The coordinate-point equivalence is natural in the value algebra. -/
theorem geckCoordinatePointMulEquiv_mapPoints
    {A B : Type v} [CommRing A] [CommRing B] (f : A →ₐ[ℤ] B)
    (q : HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht)
      (CommAlgCat.of ℤ A)) :
    t.geckCoordinatePointMulEquiv ht B
        (HopfAlgebra.mapPoints (H := t.geckCoordinateHopfAlgebra ht)
          (CommAlgCat.ofHom f) q) =
      (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f.toRingHom
        (t.geckCoordinatePointMulEquiv ht A q) := by
  simpa only [geckCoordinatePointMulEquiv, ConcreteCategory.hom_ofHom,
    AlgHom.toRingHom_eq_coe] using
    (t.geckPointsPresentation ht (CommAlgCat.of ℤ A)).mulEquiv_mapPoints
      (t.geckPointsPresentation ht (CommAlgCat.of ℤ B)) (CommAlgCat.ofHom f) q

/-- An integral point of the Geck carrier, read intrinsically as a point of its coordinate Hopf
algebra. -/
def geckCoordinatePoint (g : t.geckPoints ht ℤ) :
    HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht) (CommAlgCat.of ℤ ℤ) :=
  (t.geckCoordinatePointMulEquiv ht ℤ).symm g

/-- Passing an intrinsic coordinate point back through the presentation recovers the original
integral Geck point. -/
@[simp]
theorem geckCoordinatePointMulEquiv_geckCoordinatePoint (g : t.geckPoints ht ℤ) :
    t.geckCoordinatePointMulEquiv ht ℤ (t.geckCoordinatePoint ht g) = g :=
  MulEquiv.apply_symm_apply _ _

/-- Extending the coordinate point of an integral Geck point to a commutative ring agrees with
the presented-points map on that point. -/
@[simp]
theorem geckCoordinatePointMulEquiv_extendPoint_geckCoordinatePoint
    (g : t.geckPoints ht ℤ) (A : Type v) [CommRing A] :
    t.geckCoordinatePointMulEquiv ht A
        (HopfAlgebra.extendPoint (t.geckCoordinateHopfAlgebra ht) (CommAlgCat.of ℤ A)
          (t.geckCoordinatePoint ht g)) =
      (t.geckPointsPresentation ht ℤ).map (t.geckPointsPresentation ht A)
        (Int.castRingHom A) g := by
  apply Subtype.ext
  simp only [geckCoordinatePointMulEquiv, geckCoordinatePoint]
  rw [GeneralLinear.IntegralPointsPresentation.coe_mulEquiv_apply,
    GeneralLinear.IntegralPointsPresentation.coe_map]
  rw [← HopfAlgebra.mapValue_extendPoint _ (A := CommAlgCat.of ℤ ℤ)
      (Algebra.ofId ℤ (CommAlgCat.of ℤ A)),
    HopfAlgebra.extendPoint_self, ← CommHopfAlgCat.mapValue_quotientPointsHom,
    GeneralLinear.pointsMulEquiv_mapValue]
  have hg := (t.geckPointsPresentation ht (CommAlgCat.of ℤ ℤ)).coe_mulEquiv_apply
    ((t.geckPointsPresentation ht (CommAlgCat.of ℤ ℤ)).mulEquiv.symm g)
  rw [MulEquiv.apply_symm_apply] at hg
  rw [hg, Algebra.toRingHom_ofId, algebraMap_int_eq]

/-! ## Scheme-valued points of the carrier -/

/-- Quotient-Hopf-algebra points of the Geck carrier, transported to scheme-valued points. -/
noncomputable def geckGroupSchemePointMulEquiv (A : Type) [CommRing A] :
    HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht) (CommAlgCat.of ℤ A) ≃*
      ((Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
        (t.geckGroupScheme ht).X) :=
  CommHopfAlgCat.mapMulEquivOfPresentation (t.geckCoordinateHopfAlgebra ht) A
    (t.geckGroupScheme_eq_hopfSpec ht)

/-- The underlying spectrum map of a quotient point of the Geck carrier. -/
@[simp]
theorem geckGroupSchemePointMulEquiv_apply_left (A : Type) [CommRing A]
    (q : HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht)
      (CommAlgCat.of ℤ A)) :
    (t.geckGroupSchemePointMulEquiv ht A q).left =
      Spec.map (CommRingCat.ofHom (q.ofConv : t.geckCoordinateHopfAlgebra ht →+* A)) ≫
        eqToHom (t.geckGroupScheme_X_left ht).symm := by
  simpa only [geckGroupSchemePointMulEquiv] using
    CommHopfAlgCat.mapMulEquivOfPresentation_apply_left
      (t.geckCoordinateHopfAlgebra ht) A (t.geckGroupScheme_eq_hopfSpec ht)
      (t.geckGroupScheme_X_left ht) q

/-- Scheme-valued points of the Geck carrier, identified with its matrix points. -/
noncomputable def geckSchemePointsMulEquiv (A : Type) [CommRing A] :
    ((Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (t.geckGroupScheme ht).X) ≃* t.geckPoints ht A :=
  (t.geckGroupSchemePointMulEquiv ht A).symm.trans
    (t.geckCoordinatePointMulEquiv ht A)

/-- Evaluating the scheme-points equivalence on a presented quotient point recovers its matrix
point. -/
@[simp]
theorem geckSchemePointsMulEquiv_groupSchemePointMulEquiv (A : Type) [CommRing A]
    (q : HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht)
      (CommAlgCat.of ℤ A)) :
    t.geckSchemePointsMulEquiv ht A (t.geckGroupSchemePointMulEquiv ht A q) =
      t.geckCoordinatePointMulEquiv ht A q := by
  simp [geckSchemePointsMulEquiv]

/-- The scheme-valued point identification is covariantly natural in the value ring. A ring
homomorphism `A → B` becomes precomposition by the reversed spectrum map and acts through the
presented-points map on the corresponding Geck point. -/
@[simp]
theorem geckSchemePointsMulEquiv_mapValue {A B : Type} [CommRing A] [CommRing B]
    (f : A →+* B)
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (t.geckGroupScheme ht).X) :
    t.geckSchemePointsMulEquiv ht B
        ((let _ : (Spec.map (CommRingCat.ofHom f)).IsOver
              (Spec (CommRingCat.of ℤ)) := by
            have hf : f.toIntAlgHom.toRingHom = f := RingHom.ext fun _ ↦ rfl
            rw [← hf]
            infer_instance
          (Spec.map (CommRingCat.ofHom f)).asOver
            (Spec (CommRingCat.of ℤ))) ≫ p) =
      (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f
        (t.geckSchemePointsMulEquiv ht A p) := by
  have hf : f.toIntAlgHom.toRingHom = f := RingHom.ext fun _ ↦ rfl
  let _ : (Spec.map (CommRingCat.ofHom f)).IsOver (Spec (CommRingCat.of ℤ)) := by
    rw [← hf]
    infer_instance
  let q := (t.geckGroupSchemePointMulEquiv ht A).symm p
  have hpre :
      (t.geckGroupSchemePointMulEquiv ht B).symm
          ((Spec.map (CommRingCat.ofHom f)).asOver
            (Spec (CommRingCat.of ℤ)) ≫ p) =
        HopfAlgebra.mapPoints (H := t.geckCoordinateHopfAlgebra ht)
          (CommAlgCat.ofHom f.toIntAlgHom) q := by
    simpa only [q, geckGroupSchemePointMulEquiv, hf] using
      CommHopfAlgCat.mapMulEquivOfPresentation_mapValue
        (t.geckCoordinateHopfAlgebra ht) f.toIntAlgHom
          (t.geckGroupScheme_eq_hopfSpec ht) p
  simp only [geckSchemePointsMulEquiv, MulEquiv.trans_apply]
  rw [hpre]
  exact t.geckCoordinatePointMulEquiv_mapPoints ht f.toIntAlgHom q

/-- The quotient-coordinate point obtained by evaluating a numbered Geck root subgroup. -/
private noncomputable def geckRootSubgroupCoordinatePoint (i : Fin t.rank ⊕ Fin t.rank)
    (A : Type v) [CommRing A]
    (q : HopfAlgebra.points (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ)
      (CommAlgCat.of ℤ A)) :
    HopfAlgebra.points (R := ℤ) (H := t.geckCoordinateHopfAlgebra ht)
      (CommAlgCat.of ℤ A) := by
  exact TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToralPoints
    (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
    (t.geckCoordinateLattice ht).toAddSubgroup
    (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
    (t.isNilpotent_geckRepresentation_rootGenerator ht)
    (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht) i (CommAlgCat.of ℤ A) q

/-- Composing an additive-group scheme point with a numbered Geck root-subgroup morphism
evaluates the corresponding quotient-coordinate point. -/
private theorem groupSchemePointMulEquiv_comp_geckRootSubgroup
    (i : Fin t.rank ⊕ Fin t.rank)
    (A : Type) [CommRing A]
    (q : HopfAlgebra.points (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ)
      (CommAlgCat.of ℤ A)) :
    AdditiveGroup.groupSchemePointMulEquiv A q ≫
        (t.geckRootSubgroup ht i).hom.hom =
      t.geckGroupSchemePointMulEquiv ht A (t.geckRootSubgroupCoordinatePoint ht i A q) := by
  rw [geckRootSubgroup_def,
    UniversalEnvelopingAlgebra.kostantRootSubgroupToToral_def]
  simp only [Category.assoc, geckRootSubgroupCoordinatePoint]
  rw [UniversalEnvelopingAlgebra.kostantRootSubgroupToralPoints_apply]
  exact CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain (R := ℤ) A
    (t.geckGroupScheme_eq_hopfSpec ht)
    (AdditiveGroup.groupScheme_def ℤ)
    (t.geckGroupSchemePointMulEquiv ht A) (AdditiveGroup.groupSchemePointMulEquiv A)
    (t.geckGroupSchemePointMulEquiv_apply_left ht A)
    (AdditiveGroup.groupSchemePointMulEquiv_apply_left A)
    (UniversalEnvelopingAlgebra.kostantRootSubgroupToralCoordinateMap
      (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
      (t.geckCoordinateLattice ht).toAddSubgroup
      (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
      (t.isNilpotent_geckRepresentation_rootGenerator ht)
      (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht) i) q

/-- An intrinsic quotient-coordinate root point is the existing matrix-valued Geck root point. -/
@[simp]
private theorem geckCoordinatePointMulEquiv_rootPoint
    (i : Fin t.rank ⊕ Fin t.rank)
    (A : Type v) [CommRing A]
    (q : HopfAlgebra.points (R := ℤ) (H := AdditiveGroup.coordinateHopfAlgebra ℤ)
      (CommAlgCat.of ℤ A)) :
    t.geckCoordinatePointMulEquiv ht A
        (t.geckRootSubgroupCoordinatePoint ht i A q) =
      t.geckRootSubgroupPoints ht i A (AdditiveGroup.gaPointsMulEquiv q) := by
  apply Subtype.ext
  simp only [geckCoordinatePointMulEquiv, geckRootSubgroupCoordinatePoint]
  rw [GeneralLinear.IntegralPointsPresentation.coe_mulEquiv_apply]
  have hpoint :=
    UniversalEnvelopingAlgebra.pointsMulEquiv_quotientPointsHom_kostantRootSubgroupToralPoints
        (e := (t.lieBasis ht).rootGenerator) (h := (t.lieBasis ht).h)
        (ρ := t.geckRepresentation ht) (M := (t.geckCoordinateLattice ht).toAddSubgroup)
        (hM := t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
        (hnil := t.isNilpotent_geckRepresentation_rootGenerator ht)
        (b := t.geckCoordinateBasisFin ht) (wt := t.geckWeightFin ht) i A q
  rw [hpoint, t.coe_geckRootSubgroupPoints ht,
    (AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm_apply_apply]

/-- The map on scheme-valued points induced by a numbered Geck root-subgroup morphism is the
existing matrix-valued root-subgroup homomorphism. -/
@[simp]
theorem geckSchemePointsMulEquiv_comp_geckRootSubgroup (i : Fin t.rank ⊕ Fin t.rank)
    (A : Type) [CommRing A]
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (AdditiveGroup.groupScheme ℤ).X) :
    t.geckSchemePointsMulEquiv ht A (p ≫ (t.geckRootSubgroup ht i).hom.hom) =
      t.geckRootSubgroupPoints ht i A (AdditiveGroup.schemePointsMulEquiv A p) := by
  obtain ⟨q, rfl⟩ := (AdditiveGroup.groupSchemePointMulEquiv A).surjective p
  rw [t.groupSchemePointMulEquiv_comp_geckRootSubgroup ht i A]
  calc
    _ = t.geckCoordinatePointMulEquiv ht A
        (t.geckRootSubgroupCoordinatePoint ht i A q) :=
      t.geckSchemePointsMulEquiv_groupSchemePointMulEquiv ht A _
    _ = t.geckRootSubgroupPoints ht i A (AdditiveGroup.gaPointsMulEquiv q) :=
      t.geckCoordinatePointMulEquiv_rootPoint ht i A q
    _ = _ := congrArg (t.geckRootSubgroupPoints ht i A)
      (AdditiveGroup.schemePointsMulEquiv_groupSchemePointMulEquiv A q).symm

variable {A : Type v} {B : Type v'} [CommRing A] [CommRing B]

/-- **The induced map carries a numbered root-subgroup point along the homomorphism of value
rings.** -/
@[simp]
theorem map_geckRootSubgroupPoints (f : A →+* B)
    (i : Fin t.rank ⊕ Fin t.rank) (u : Multiplicative A) :
    (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f
      (t.geckRootSubgroupPoints ht i A u) =
      t.geckRootSubgroupPoints ht i B
        (Multiplicative.ofAdd (f (Multiplicative.toAdd u))) := by
  refine Subtype.ext ?_
  have h := congrArg Subtype.val
    (TauCeti.UniversalEnvelopingAlgebra.map_kostantToralRootSubgroupPoints
      (e := (t.lieBasis ht).rootGenerator) (h := (t.lieBasis ht).h)
      (ρ := t.geckRepresentation ht) (M := (t.geckCoordinateLattice ht).toAddSubgroup)
      (hM := t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
      (hnil := t.isNilpotent_geckRepresentation_rootGenerator ht)
      (b := t.geckCoordinateBasisFin ht) (wt := t.geckWeightFin ht) f i u)
  rw [TauCeti.GeneralLinear.IntegralPointsPresentation.coe_map] at h
  rw [TauCeti.GeneralLinear.IntegralPointsPresentation.coe_map]
  simpa only [coe_geckRootSubgroupPoints,
    TauCeti.UniversalEnvelopingAlgebra.coe_kostantToralRootSubgroupPoints] using h

/-- **The induced map carries a point of the pinned Geck weight torus along the homomorphism of
value rings**, parameter by parameter. -/
@[simp]
theorem map_geckWeightTorusPoints (f : A →+* B) (s : Fin t.rank → Aˣ) :
    (t.geckPointsPresentation ht A).map (t.geckPointsPresentation ht B) f
      (t.geckWeightTorusPoints ht A s) =
      t.geckWeightTorusPoints ht B (fun j => Units.map (f : A →* B) (s j)) := by
  refine Subtype.ext ?_
  have h := congrArg Subtype.val
    (TauCeti.UniversalEnvelopingAlgebra.map_kostantToralWeightTorusPoints
      (e := (t.lieBasis ht).rootGenerator) (h := (t.lieBasis ht).h)
      (ρ := t.geckRepresentation ht) (M := (t.geckCoordinateLattice ht).toAddSubgroup)
      (hM := t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
      (hnil := t.isNilpotent_geckRepresentation_rootGenerator ht)
      (b := t.geckCoordinateBasisFin ht) (wt := t.geckWeightFin ht) f s)
  rw [TauCeti.GeneralLinear.IntegralPointsPresentation.coe_map] at h
  rw [TauCeti.GeneralLinear.IntegralPointsPresentation.coe_map]
  simpa only [coe_geckWeightTorusPoints,
    TauCeti.UniversalEnvelopingAlgebra.coe_kostantToralWeightTorusPoints] using h

end

end TauCeti.DynkinType
