/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Generation
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.GeckLattice.Generation

/-!
# Scheme-theoretic root generation of full-weight Geck carriers

The Geck carrier is defined as the closed subgroup scheme generated jointly by the numbered
positive and negative simple-root subgroups and the represented weight torus. This file upgrades
universal pointwise generation of the represented torus to equality of the toral and
root-generated defining ideals and carriers.

The general results apply to every valid type whose Cartan rows are primitive. The specializations
record `E₈`, `F₄`, and `G₂`, the three exceptional types whose Geck coordinate weights span the
full character lattice and hence whose Geck tori are the full-weight tori used by the
Chevalley--Demazure construction.

## Main results

* `TauCeti.DynkinType.geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal`: primitive Cartan rows
  make the torus redundant in the Geck defining ideal.
* `TauCeti.DynkinType.geckGroupScheme_eq_kostantGeneratedGroupScheme`: the corresponding carrier
  equality.
* The suffixes `_E8`, `_F4`, and `_G2` record both equalities and the canonical comparison
  isomorphism for the three full-weight Geck carriers.

## References

* R. Steinberg, *Lectures on Chevalley Groups*, Section 3.
* R. W. Carter, *Simple Groups of Lie Type*, Sections 6.4 and 7.1.
-/

public section

open CategoryTheory WithConv
open scoped Matrix TensorProduct

namespace TauCeti.DynkinType

open TauCeti.UniversalEnvelopingAlgebra

universe v

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

variable (t : DynkinType) (ht : t.Valid)

private theorem universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le
    (htorus :
      let T := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin t.rank))).obj
      let A := CommAlgCat.of ℤ T
      (t.geckTorusPoints ht A).range ≤ t.geckElementarySubgroup ht A) :
    let T := (DiagonalizableGroup.coordinateRing ℤ
      (SplitTorus.characterGroup (Fin t.rank))).obj
    let A := CommAlgCat.of ℤ T
    let q : HopfAlgebra.points
        (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
          (SplitTorus.characterGroup (Fin t.rank))) A := toConv (AlgHom.id ℤ T)
    t.geckTorusPoints ht A (SplitTorus.pointsMulEquiv q) ∈
      t.geckElementarySubgroup ht A := by
  apply htorus
  exact ⟨_, rfl⟩

/-- **Generation of the universal Geck torus makes the Geck defining ideal root-generated.** It
is enough to contain its universal point over the coordinate ring of the split torus itself. -/
theorem geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin t.rank))).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup (Fin t.rank))) A := toConv (AlgHom.id ℤ T)
      t.geckTorusPoints ht A (SplitTorus.pointsMulEquiv q) ∈
        t.geckElementarySubgroup ht A) :
    t.geckDefiningIdeal ht =
      kostantGeneratedDefiningIdeal
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht)
        (t.geckCoordinateBasisFin ht) := by
  rw [t.geckDefiningIdeal_def ht]
  exact
    kostantToralDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary
      _ _ _ _ _ _ _ _ huniv

/-- **Primitive Cartan rows make the Geck torus scheme-theoretically redundant.** The defining
Hopf ideal obtained from the numbered root subgroups and the weight torus is already the defining
ideal generated by the numbered root subgroups alone. -/
theorem geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal
    (hrow : ∀ i, ∃ c : Fin t.rank → ℤ, ∑ j, t.cartanMatrix i j * c j = 1) :
    t.geckDefiningIdeal ht =
      kostantGeneratedDefiningIdeal
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht)
        (t.geckCoordinateBasisFin ht) :=
  t.geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary ht
    (t.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le ht
      (t.range_geckTorusPoints_le_geckElementarySubgroup ht hrow _))

/-- **Generation of the universal Geck torus identifies the Geck and root-generated carriers.**
The carrier equality is induced by the equality of their defining Hopf ideals. -/
theorem geckGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin t.rank))).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup (Fin t.rank))) A := toConv (AlgHom.id ℤ T)
      t.geckTorusPoints ht A (SplitTorus.pointsMulEquiv q) ∈
        t.geckElementarySubgroup ht A) :
    t.geckGroupScheme ht =
      kostantGeneratedGroupScheme
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht)
        (t.geckCoordinateBasisFin ht) := by
  rw [t.geckGroupScheme_def ht]
  exact kostantToralGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ _ huniv

/-- **Primitive Cartan rows identify the Geck carrier with the root-generated Kostant carrier.**
Thus the represented weight torus adds no scheme-theoretic generator. -/
theorem geckGroupScheme_eq_kostantGeneratedGroupScheme
    (hrow : ∀ i, ∃ c : Fin t.rank → ℤ, ∑ j, t.cartanMatrix i j * c j = 1) :
    t.geckGroupScheme ht =
      kostantGeneratedGroupScheme
        (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
        (t.geckCoordinateLattice ht).toAddSubgroup
        (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
        (t.isNilpotent_geckRepresentation_rootGenerator ht)
        (t.geckCoordinateBasisFin ht) :=
  t.geckGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary ht
    (t.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le ht
      (t.range_geckTorusPoints_le_geckElementarySubgroup ht hrow _))

/-- Generation of the universal Geck torus makes the canonical comparison from the root-generated
Kostant carrier to the Geck toral carrier an isomorphism. -/
theorem isIso_kostantGeneratedToToral_geck_of_universal_torus_mem_elementary
    (huniv :
      let T := (DiagonalizableGroup.coordinateRing ℤ
        (SplitTorus.characterGroup (Fin t.rank))).obj
      let A := CommAlgCat.of ℤ T
      let q : HopfAlgebra.points
          (R := ℤ) (H := DiagonalizableGroup.coordinateRing ℤ
            (SplitTorus.characterGroup (Fin t.rank))) A := toConv (AlgHom.id ℤ T)
      t.geckTorusPoints ht A (SplitTorus.pointsMulEquiv q) ∈
        t.geckElementarySubgroup ht A) :
    IsIso (kostantGeneratedToToral
      (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
      (t.geckCoordinateLattice ht).toAddSubgroup
      (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
      (t.isNilpotent_geckRepresentation_rootGenerator ht)
      (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)) := by
  exact isIso_kostantGeneratedToToral_of_universal_torus_mem_elementary
    _ _ _ _ _ _ _ _ huniv

/-- Primitive Cartan rows make the canonical comparison from the root-generated Kostant carrier
to the Geck toral carrier an isomorphism. -/
theorem isIso_kostantGeneratedToToral_geck
    (hrow : ∀ i, ∃ c : Fin t.rank → ℤ, ∑ j, t.cartanMatrix i j * c j = 1) :
    IsIso (kostantGeneratedToToral
      (t.lieBasis ht).rootGenerator (t.lieBasis ht).h (t.geckRepresentation ht)
      (t.geckCoordinateLattice ht).toAddSubgroup
      (t.geckRepresentation_kostantForm_mem_geckCoordinateLattice ht)
      (t.isNilpotent_geckRepresentation_rootGenerator ht)
      (t.geckCoordinateBasisFin ht) (t.geckWeightFin ht)) :=
  t.isIso_kostantGeneratedToToral_geck_of_universal_torus_mem_elementary ht
    (t.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le ht
      (t.range_geckTorusPoints_le_geckElementarySubgroup ht hrow _))

/-! ## Full-weight exceptional Geck carriers -/

/-- The type-`E₈` Geck defining ideal is generated scheme-theoretically by its sixteen numbered
positive and negative simple-root subgroups; adjoining the weight torus does not change it. -/
theorem geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_E8 :
    E8.geckDefiningIdeal valid_E8 =
      kostantGeneratedDefiningIdeal
        (E8.lieBasis valid_E8).rootGenerator (E8.lieBasis valid_E8).h
        (E8.geckRepresentation valid_E8)
        (E8.geckCoordinateLattice valid_E8).toAddSubgroup
        (E8.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_E8)
        (E8.isNilpotent_geckRepresentation_rootGenerator valid_E8)
        (E8.geckCoordinateBasisFin valid_E8) :=
  E8.geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary valid_E8
    (E8.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_E8
      (range_geckTorusPoints_le_geckElementarySubgroup_E8 _))

/-- The type-`E₈` full-weight Geck carrier is the closed group scheme generated by its sixteen
numbered positive and negative simple-root subgroups alone. -/
theorem geckGroupScheme_eq_kostantGeneratedGroupScheme_E8 :
    E8.geckGroupScheme valid_E8 =
      kostantGeneratedGroupScheme
        (E8.lieBasis valid_E8).rootGenerator (E8.lieBasis valid_E8).h
        (E8.geckRepresentation valid_E8)
        (E8.geckCoordinateLattice valid_E8).toAddSubgroup
        (E8.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_E8)
        (E8.isNilpotent_geckRepresentation_rootGenerator valid_E8)
        (E8.geckCoordinateBasisFin valid_E8) :=
  E8.geckGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary valid_E8
    (E8.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_E8
      (range_geckTorusPoints_le_geckElementarySubgroup_E8 _))

/-- For type `E₈`, the canonical comparison from the root-generated Kostant carrier to the Geck
toral carrier is an isomorphism. -/
instance isIso_kostantGeneratedToToral_E8 :
    IsIso (kostantGeneratedToToral
      (E8.lieBasis valid_E8).rootGenerator (E8.lieBasis valid_E8).h
      (E8.geckRepresentation valid_E8)
      (E8.geckCoordinateLattice valid_E8).toAddSubgroup
      (E8.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_E8)
      (E8.isNilpotent_geckRepresentation_rootGenerator valid_E8)
      (E8.geckCoordinateBasisFin valid_E8) (E8.geckWeightFin valid_E8)) :=
  E8.isIso_kostantGeneratedToToral_geck_of_universal_torus_mem_elementary valid_E8
    (E8.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_E8
      (range_geckTorusPoints_le_geckElementarySubgroup_E8 _))

/-- The type-`F₄` Geck defining ideal is generated scheme-theoretically by its eight numbered
positive and negative simple-root subgroups; adjoining the weight torus does not change it. -/
theorem geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_F4 :
    F4.geckDefiningIdeal valid_F4 =
      kostantGeneratedDefiningIdeal
        (F4.lieBasis valid_F4).rootGenerator (F4.lieBasis valid_F4).h
        (F4.geckRepresentation valid_F4)
        (F4.geckCoordinateLattice valid_F4).toAddSubgroup
        (F4.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_F4)
        (F4.isNilpotent_geckRepresentation_rootGenerator valid_F4)
        (F4.geckCoordinateBasisFin valid_F4) :=
  F4.geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary valid_F4
    (F4.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_F4
      (range_geckTorusPoints_le_geckElementarySubgroup_F4 _))

/-- The type-`F₄` full-weight Geck carrier is the closed group scheme generated by its eight
numbered positive and negative simple-root subgroups alone. -/
theorem geckGroupScheme_eq_kostantGeneratedGroupScheme_F4 :
    F4.geckGroupScheme valid_F4 =
      kostantGeneratedGroupScheme
        (F4.lieBasis valid_F4).rootGenerator (F4.lieBasis valid_F4).h
        (F4.geckRepresentation valid_F4)
        (F4.geckCoordinateLattice valid_F4).toAddSubgroup
        (F4.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_F4)
        (F4.isNilpotent_geckRepresentation_rootGenerator valid_F4)
        (F4.geckCoordinateBasisFin valid_F4) :=
  F4.geckGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary valid_F4
    (F4.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_F4
      (range_geckTorusPoints_le_geckElementarySubgroup_F4 _))

/-- For type `F₄`, the canonical comparison from the root-generated Kostant carrier to the Geck
toral carrier is an isomorphism. -/
instance isIso_kostantGeneratedToToral_F4 :
    IsIso (kostantGeneratedToToral
      (F4.lieBasis valid_F4).rootGenerator (F4.lieBasis valid_F4).h
      (F4.geckRepresentation valid_F4)
      (F4.geckCoordinateLattice valid_F4).toAddSubgroup
      (F4.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_F4)
      (F4.isNilpotent_geckRepresentation_rootGenerator valid_F4)
      (F4.geckCoordinateBasisFin valid_F4) (F4.geckWeightFin valid_F4)) :=
  F4.isIso_kostantGeneratedToToral_geck_of_universal_torus_mem_elementary valid_F4
    (F4.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_F4
      (range_geckTorusPoints_le_geckElementarySubgroup_F4 _))

/-- The type-`G₂` Geck defining ideal is generated scheme-theoretically by its four numbered
positive and negative simple-root subgroups; adjoining the weight torus does not change it. -/
theorem geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_G2 :
    G2.geckDefiningIdeal valid_G2 =
      kostantGeneratedDefiningIdeal
        (G2.lieBasis valid_G2).rootGenerator (G2.lieBasis valid_G2).h
        (G2.geckRepresentation valid_G2)
        (G2.geckCoordinateLattice valid_G2).toAddSubgroup
        (G2.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_G2)
        (G2.isNilpotent_geckRepresentation_rootGenerator valid_G2)
        (G2.geckCoordinateBasisFin valid_G2) :=
  G2.geckDefiningIdeal_eq_kostantGeneratedDefiningIdeal_of_universal_torus_mem_elementary valid_G2
    (G2.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_G2
      (range_geckTorusPoints_le_geckElementarySubgroup_G2 _))

/-- The type-`G₂` full-weight Geck carrier is the closed group scheme generated by its four
numbered positive and negative simple-root subgroups alone. -/
theorem geckGroupScheme_eq_kostantGeneratedGroupScheme_G2 :
    G2.geckGroupScheme valid_G2 =
      kostantGeneratedGroupScheme
        (G2.lieBasis valid_G2).rootGenerator (G2.lieBasis valid_G2).h
        (G2.geckRepresentation valid_G2)
        (G2.geckCoordinateLattice valid_G2).toAddSubgroup
        (G2.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_G2)
        (G2.isNilpotent_geckRepresentation_rootGenerator valid_G2)
        (G2.geckCoordinateBasisFin valid_G2) :=
  G2.geckGroupScheme_eq_kostantGeneratedGroupScheme_of_universal_torus_mem_elementary valid_G2
    (G2.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_G2
      (range_geckTorusPoints_le_geckElementarySubgroup_G2 _))

/-- For type `G₂`, the canonical comparison from the root-generated Kostant carrier to the Geck
toral carrier is an isomorphism. -/
instance isIso_kostantGeneratedToToral_G2 :
    IsIso (kostantGeneratedToToral
      (G2.lieBasis valid_G2).rootGenerator (G2.lieBasis valid_G2).h
      (G2.geckRepresentation valid_G2)
      (G2.geckCoordinateLattice valid_G2).toAddSubgroup
      (G2.geckRepresentation_kostantForm_mem_geckCoordinateLattice valid_G2)
      (G2.isNilpotent_geckRepresentation_rootGenerator valid_G2)
      (G2.geckCoordinateBasisFin valid_G2) (G2.geckWeightFin valid_G2)) :=
  G2.isIso_kostantGeneratedToToral_geck_of_universal_torus_mem_elementary valid_G2
    (G2.universalGeckTorusPoint_mem_geckElementarySubgroup_of_range_le valid_G2
      (range_geckTorusPoints_le_geckElementarySubgroup_G2 _))

end TauCeti.DynkinType
