/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.InfinitePlace
public import TauCeti.NumberTheory.NumberField.Units.ElementaryTwoQuotient
import Mathlib.GroupTheory.CosetCover
import TauCeti.NumberTheory.NumberField.Units.Dirichlet
import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Norm.Basic
import TauCeti.NumberTheory.NumberField.Quadratic.Norm

/-!
# Units and quadratic conjugation

This file records two sign and square-class consequences for units in a quadratic number field.
A unit whose product with its quadratic conjugate is one is, up to sign, totally positive. It
follows from Dirichlet's unit theorem that a real quadratic field in which every unit has
conjugation norm one has a totally positive unit that is not a square.

These are the archimedean unit inputs to the narrow ambiguous class number formula.

## Main results

* `NumberField.isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_one`: a unit of
  conjugation norm one is, up to sign, totally positive.
* `NumberField.exists_isTotallyPositive_notMem_square`: under the stated real and norm-one
  hypotheses, there is a totally positive unit that is not a square.
-/

public section

open Polynomial NumberField
open scoped NumberField

namespace NumberField

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- **A unit of norm one is `±` a totally positive unit.** The case `N(u) = 1` of
`isTotallyPositive_or_isTotallyPositive_neg_of_norm_pos`, with the norm hypothesis written in the
conjugation form `u σu = 1` in which the descent arguments of this area produce it. -/
theorem isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {u : 𝓞 K}
    (hnorm : u * ringOfIntegersQuadraticConj hmin hgen u = 1) :
    IsTotallyPositive (u : K) ∨ IsTotallyPositive (-(u : K)) := by
  refine isTotallyPositive_or_isTotallyPositive_neg_of_norm_pos hmin hgen ?_
  rw [(norm_eq_intCast_iff_mul_ringOfIntegersQuadraticConj_eq_intCast (n := 1) hmin hgen).mpr
    (by simpa using hnorm)]
  norm_num

/-- **A nonzero element of norm minus one makes `θ` times it `±` totally positive.** The `-1`
companion of `isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_one`: an element of
norm `-1` need not be `±` totally positive, but `θ` has norm `-d`, so the extra factor `θ` restores
the positive norm and with it the sign that the `+1` case has for free. -/
theorem isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_neg_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {u : 𝓞 K}
    (hnorm : u * ringOfIntegersQuadraticConj hmin hgen u = -1) :
    IsTotallyPositive ((θ * u : 𝓞 K) : K) ∨ IsTotallyPositive (-((θ * u : 𝓞 K) : K)) := by
  -- The hypothesis says `N(u) = -1`, which forces `0 < d`; then `N(θu) = (-d) · (-1) = d > 0`.
  have hu : Algebra.norm ℚ (u : K) = -1 := by
    have := (norm_eq_intCast_iff_mul_ringOfIntegersQuadraticConj_eq_intCast (n := -1)
      hmin hgen).mpr (by simpa using hnorm)
    simpa using this
  have hd : (0 : ℚ) < (d : ℚ) := by
    exact_mod_cast radicand_pos_of_norm_eq_neg_one hmin hgen hu
  refine isTotallyPositive_or_isTotallyPositive_neg_of_norm_pos hmin hgen ?_
  have hcoe : ((θ * u : 𝓞 K) : K) = (θ : K) * (u : K) := by push_cast; ring
  rw [hcoe, map_mul, norm_gen_eq_neg_radicand hmin hgen, hu]
  linarith

open scoped Pointwise in
/-- **A real quadratic field with no unit of norm `-1` has a totally positive unit that is not a
square.** With every unit of norm one, every unit is `±` a totally positive unit
(`isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_one`); were every totally positive
unit a square, the unit group would be generated by `-1` together with the squares, so the squares
would have index at most `2`. But a field with a real place has unit rank `1`, where the exact index
is `2 ^ (rank + 1) = 4` (`NumberField.units_sq_index_eq`). -/
theorem exists_isTotallyPositive_notMem_square (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) (hreal : ¬ IsTotallyComplex K)
    (hnorm : ∀ u : (𝓞 K)ˣ,
      (u : 𝓞 K) * ringOfIntegersQuadraticConj hmin hgen (u : 𝓞 K) = 1) :
    ∃ ε : (𝓞 K)ˣ, IsTotallyPositive ((ε : 𝓞 K) : K) ∧ ε ∉ Subgroup.square (𝓞 K)ˣ := by
  by_contra! hsquare
  set H := Subgroup.square (𝓞 K)ˣ
  -- Every unit is a square or `-1` times a square, so those two cosets cover the group.
  have hcovers : ⋃ i ∈ (Finset.univ : Finset (Fin 2)),
      (![1, -1] i : (𝓞 K)ˣ) • (H : Set (𝓞 K)ˣ) = Set.univ := by
    rw [Subgroup.leftCoset_cover_const_iff_surjOn]
    rintro x -
    obtain ⟨u, rfl⟩ := QuotientGroup.mk'_surjective H x
    rcases isTotallyPositive_or_neg_of_mul_ringOfIntegersQuadraticConj_eq_one hmin hgen
      (hnorm u) with h | h
    · exact ⟨0, by simp, by simpa using ((QuotientGroup.eq_one_iff _).mpr (hsquare u h)).symm⟩
    · refine ⟨1, by simp, ?_⟩
      rw [QuotientGroup.mk'_apply, QuotientGroup.eq]
      simpa using hsquare (-u) (by simpa using h)
  have hindex : H.index ≤ 2 := by
    simpa only [Finset.card_fin] using Subgroup.index_le_of_leftCoset_cover_const hcovers
  have hrank : NumberField.Units.rank K = 1 := by
    -- A field with a real place and degree two has unit rank one.
    classical
    have hnr : InfinitePlace.nrRealPlaces K ≠ 0 := fun h =>
      hreal (nrRealPlaces_eq_zero_iff.mp h)
    obtain ⟨⟨w, hw⟩⟩ := Fintype.card_pos_iff.mp (Nat.pos_of_ne_zero hnr)
    exact rank_eq_one_of_finrank_eq_two_of_isReal (NumberField.finrank_rat_eq_two hmin hgen) hw
  rw [NumberField.units_sq_index_eq, hrank] at hindex
  norm_num at hindex

end NumberField
