/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Exponential
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Orbit
public import TauCeti.Algebra.Lie.UniversalEnveloping.Prod

/-!
# Integral exponential actions on Kostant-stable additive subgroups

Let `U_ℤ = kostantForm e h` be a Kostant integral form in `U(L)`, let `ρ` be a representation of
`U(L)` on a rational vector space `V`, and let `M ≤ V` be an additive subgroup preserved by
`ρ(U_ℤ)`. If the endomorphism `ρ(eᵢ)` is nilpotent, the integral exponentials

```text
x_i(t) = exp (t ρ(eᵢ)),   t ∈ ℤ,
```

preserve `M`. This file packages preservation into an action-level statement: the maps `x_i(t)` form
a group homomorphism from the additive group of integers to the additive automorphisms of `M`.

The construction uses `TauCeti.expZSMulAddAut`, which packages the action of integral nilpotent
exponentials on any additive subgroup stable under the corresponding divided powers. Stability
under the whole Kostant form supplies that hypothesis because the divided powers of every
designated root vector are Kostant generators.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.expZSMulKostantAddAut`: integral exponentials
  attached to `e i` act by additive automorphisms on every Kostant-stable additive subgroup.
* `TauCeti.UniversalEnvelopingAlgebra.expZSMulKostantOrbitAddAut`: the canonical
  specialization to the integral orbit generated by a vector under the Kostant form.
* `AlgHom.prodRepresentation_kostantForm_apply_mem`: the product
  lattice of two Kostant-stable lattices is stable for the product representation.

This advances Layer 9, “Root subgroup maps,” of the ReductiveGroups roadmap. When
specialized to distinguished root vectors and admissible lattices, these automorphisms
supply the pointwise algebra assembled into the root subgroup morphisms `x_α : 𝔾ₐ → G`
of the pinned Chevalley--Demazure group scheme.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26--27.
* R. W. Carter, *Simple Groups of Lie Type*, §4.4.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

/-- Integral exponentials attached to `e i` act by additive automorphisms on an additive subgroup
preserved by the Kostant form.

The target is the additive automorphism group of `M`, written multiplicatively so that the
one-parameter group law is exposed as a `MonoidHom`. No freeness or finite-generation assumption on
`M` is needed for this action-level statement. -/
noncomputable def expZSMulKostantAddAut (e : ι → L) (h : κ → L)
    (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
    {S : Type*} [SetLike S V] [AddSubgroupClass S V] (M : S)
    (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M) (i : ι)
    (hnil : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    Multiplicative ℤ →* Multiplicative (AddAut M) :=
  TauCeti.expZSMulAddAut hnil M fun n v hv => by
    rw [← Associative.map_dividedPower ρ n]
    exact hM _ (dividedPower_mem_kostantForm e h i n) v hv

/-- The integral exponential action on a Kostant-stable additive subgroup is the ambient nilpotent
exponential. -/
@[simp]
theorem coe_expZSMulKostantAddAut (e : ι → L) (h : κ → L)
    (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
    {S : Type*} [SetLike S V] [AddSubgroupClass S V] (M : S)
    (hM : ∀ u ∈ kostantForm e h, ∀ v ∈ M, ρ u v ∈ M) (i : ι)
    (hnil : IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (t : Multiplicative ℤ) (v : M) :
    ((Multiplicative.toAdd (expZSMulKostantAddAut e h ρ M hM i hnil t) v : M) : V) =
      IsNilpotent.exp ((Multiplicative.toAdd t : ℤ) •
        ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))) (v : V) := by
  simp only [expZSMulKostantAddAut, TauCeti.coe_expZSMulAddAut, Module.End.smul_def]

end TauCeti.UniversalEnvelopingAlgebra

namespace AlgHom

/-! ## Products of Kostant-stable lattices -/

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]
variable {W : Type w} [AddCommGroup W] [Module ℚ W]

/-- The product of two lattices stable under a Kostant form is stable under the product
representation. This is the stability step for a product admissible lattice. -/
theorem prodRepresentation_kostantForm_apply_mem (e : ι → L) (h : κ → L)
    (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
    (σ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ W)
    (M : Submodule ℤ V) (N : Submodule ℤ W)
    (hM : ∀ u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm e h, ∀ v ∈ M, ρ u v ∈ M)
    (hN : ∀ u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm e h, ∀ w ∈ N, σ u w ∈ N)
    (u : _root_.UniversalEnvelopingAlgebra ℚ L)
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm e h)
    (v : V × W) (hv : v ∈ M.prod N) :
    prodRepresentation ρ σ u v ∈ M.prod N :=
  prodRepresentation_apply_mem_of_mem ρ σ
    (TauCeti.UniversalEnvelopingAlgebra.kostantForm e h) M N hM hN u hu v hv

end AlgHom

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}
variable {V : Type v} [AddCommGroup V] [Module ℚ V]

/-! ## The action on the canonical Kostant orbit -/

variable [Module (_root_.UniversalEnvelopingAlgebra ℚ L) V]
variable [IsScalarTower ℚ (_root_.UniversalEnvelopingAlgebra ℚ L) V]

/-- Integral exponentials attached to `e i` act by additive automorphisms on the Kostant orbit
generated by `v`.

Unlike `expZSMulKostantAddAut`, this specialization has no separate stability hypothesis: the
Kostant orbit is stable under the whole Kostant form by construction. The only remaining
hypothesis is the representation-theoretic condition that `e i` acts nilpotently on `V`. -/
noncomputable def expZSMulKostantOrbitAddAut (e : ι → L) (h : κ → L) (v : V) (i : ι)
    (hnil : IsNilpotent ((Algebra.lsmul ℚ ℚ V)
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)))) :
    Multiplicative ℤ →* Multiplicative (AddAut (kostantOrbit e h v)) :=
  TauCeti.expZSMulAddAut hnil (kostantOrbit e h v) fun n _ hx => by
    rw [← Associative.map_dividedPower (Algebra.lsmul ℚ ℚ V) n]
    exact dividedPower_smul_mem_kostantOrbit i n hx

/-- On the ambient rational representation, the integral exponential action on the Kostant orbit is
the nilpotent exponential of the endomorphism attached to `e i`. -/
@[simp]
theorem coe_expZSMulKostantOrbitAddAut (e : ι → L) (h : κ → L) (v : V) (i : ι)
    (hnil : IsNilpotent ((Algebra.lsmul ℚ ℚ V)
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
    (t : Multiplicative ℤ) (x : kostantOrbit e h v) :
    ((Multiplicative.toAdd (expZSMulKostantOrbitAddAut e h v i hnil t) x :
      kostantOrbit e h v) : V) =
      IsNilpotent.exp ((Multiplicative.toAdd t : ℤ) •
        (Algebra.lsmul ℚ ℚ V) (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))) (x : V) :=
  TauCeti.coe_expZSMulAddAut hnil (kostantOrbit e h v) _ t x

end TauCeti.UniversalEnvelopingAlgebra
