/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.FixedField
public import TauCeti.FieldTheory.IntermediateField.Adjoin.Square
public import TauCeti.NumberTheory.DirichletCharacter.GaussSum
public import TauCeti.NumberTheory.Multiquadratic.FundamentalDiscriminant.Character
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Galois

/-!
# The quadratic character cuts out the quadratic cyclotomic subfield

For a fundamental discriminant `D`, its primitive quadratic character of level `|D|` defines a
subgroup of the Galois group of the `|D|`-th cyclotomic field. This file identifies the fixed field
of that subgroup with `ℚ(√D)`.

The generator is the Dirichlet Gauss sum of the fundamental-discriminant character. Its square is
`D`, and its Galois stabilizer is exactly the kernel of the character. Thus the Galois
correspondence turns the character-theoretic conductor into the quadratic subfield it detects.

For the classical construction see K. Ireland and M. Rosen, *A Classical Introduction to Modern
Number Theory*, Chapter 6, and D. A. Cox, *Primes of the Form x² + ny²*, §3.B.

## Main results

* `gaussSumOfPrimitiveRoot_fundamentalDiscriminantChar_sq`: in any field of characteristic zero,
  the Gauss sum of the character of `D` squares to `D`.
* `fundamentalDiscriminantGaussSum_sq`: the canonical Gauss sum squares to `D`.
* `fixedField_fundamentalDiscriminantCharacterSubgroup`: the kernel-fixed field is generated by
  that Gauss sum.
* `fixedField_fundamentalDiscriminantCharacterSubgroup_eq_adjoin_of_sq_eq`: any chosen square root
  of `D` generates the same fixed field.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

/-- The Gauss sum of the primitive quadratic character attached to a fundamental discriminant,
inside the cyclotomic field of level `|D|`. -/
noncomputable def fundamentalDiscriminantGaussSum (D : ℤ)
    (hD : IsFundamentalDiscriminant D) : CyclotomicField D.natAbs ℚ := by
  let _ : NeZero D.natAbs := ⟨Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : NeZero (D.natAbs : ℚ) :=
    ⟨by exact_mod_cast Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : IsCyclotomicExtension {D.natAbs} ℚ (CyclotomicField D.natAbs ℚ) :=
    CyclotomicField.isCyclotomicExtension D.natAbs ℚ
  exact DirichletCharacter.gaussSumOfPrimitiveRoot (fundamentalDiscriminantChar D hD)
    (IsCyclotomicExtension.zeta_spec D.natAbs ℚ (CyclotomicField D.natAbs ℚ))

/-- The subgroup of the cyclotomic Galois group on which the fundamental-discriminant character
is trivial. -/
noncomputable def fundamentalDiscriminantCharacterSubgroup (D : ℤ)
    (hD : IsFundamentalDiscriminant D) :
    Subgroup Gal(CyclotomicField D.natAbs ℚ/ℚ) := by
  let _ : NeZero D.natAbs := ⟨Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : NeZero (D.natAbs : ℚ) :=
    ⟨by exact_mod_cast Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : IsCyclotomicExtension {D.natAbs} ℚ (CyclotomicField D.natAbs ℚ) :=
    CyclotomicField.isCyclotomicExtension D.natAbs ℚ
  let hζ := IsCyclotomicExtension.zeta_spec D.natAbs ℚ (CyclotomicField D.natAbs ℚ)
  exact ((fundamentalDiscriminantChar D hD).toUnitHom.comp (hζ.autToPow ℚ)).ker

/-- Membership in the fundamental-discriminant character subgroup means that the character is
trivial on the corresponding cyclotomic automorphism. -/
@[simp] theorem mem_fundamentalDiscriminantCharacterSubgroup_iff (D : ℤ)
    (hD : IsFundamentalDiscriminant D) (σ : Gal(CyclotomicField D.natAbs ℚ/ℚ)) :
    let _ : NeZero D.natAbs := ⟨Int.natAbs_ne_zero.mpr hD.ne_zero⟩
    let _ : NeZero (D.natAbs : ℚ) :=
      ⟨by exact_mod_cast Int.natAbs_ne_zero.mpr hD.ne_zero⟩
    let _ : IsCyclotomicExtension {D.natAbs} ℚ (CyclotomicField D.natAbs ℚ) :=
      CyclotomicField.isCyclotomicExtension D.natAbs ℚ
    σ ∈ fundamentalDiscriminantCharacterSubgroup D hD ↔
      fundamentalDiscriminantChar D hD
        ((IsCyclotomicExtension.zeta_spec D.natAbs ℚ
          (CyclotomicField D.natAbs ℚ)).autToPow ℚ σ) = 1 := by
  simp only [fundamentalDiscriminantCharacterSubgroup, MonoidHom.mem_ker,
    MonoidHom.comp_apply, Units.ext_iff, MulChar.coe_toUnitHom, Units.val_one]

/-- **The Gauss sum of a fundamental discriminant squares to it.** In any field of characteristic
zero, the Gauss sum of the character of the fundamental discriminant `D`, formed with a primitive
`|D|`-th root of unity, is a square root of `D`. -/
@[simp]
theorem gaussSumOfPrimitiveRoot_fundamentalDiscriminantChar_sq {L : Type*} [Field L] [CharZero L]
    {D : ℤ} (hD : IsFundamentalDiscriminant D) [NeZero D.natAbs] {ζ : L}
    (hζ : IsPrimitiveRoot ζ D.natAbs) :
    DirichletCharacter.gaussSumOfPrimitiveRoot (fundamentalDiscriminantChar D hD) hζ ^ 2 =
      (D : L) := by
  rw [DirichletCharacter.gaussSumOfPrimitiveRoot_sq _ (isPrimitive_fundamentalDiscriminantChar hD)
    (fundamentalDiscriminantChar_isQuadratic hD)]
  simpa [fundamentalDiscriminantChar_neg_one] using
    congr_arg (Int.cast : ℤ → L) (Int.sign_mul_natAbs D)

/-- The Gauss sum of a fundamental discriminant is a square root of that discriminant. -/
@[simp] theorem fundamentalDiscriminantGaussSum_sq (D : ℤ) (hD : IsFundamentalDiscriminant D) :
    fundamentalDiscriminantGaussSum D hD ^ 2 =
      (D : CyclotomicField D.natAbs ℚ) := by
  let _ : NeZero D.natAbs := ⟨Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  exact gaussSumOfPrimitiveRoot_fundamentalDiscriminantChar_sq hD _

/-- The fixed field of the kernel of the fundamental-discriminant character is generated by its
Gauss sum. -/
theorem fixedField_fundamentalDiscriminantCharacterSubgroup (D : ℤ)
    (hD : IsFundamentalDiscriminant D) :
    fixedField (fundamentalDiscriminantCharacterSubgroup D hD) =
      adjoin ℚ {fundamentalDiscriminantGaussSum D hD} := by
  let _ : NeZero D.natAbs := ⟨Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : NeZero (D.natAbs : ℚ) :=
    ⟨by exact_mod_cast Int.natAbs_ne_zero.mpr hD.ne_zero⟩
  let _ : IsCyclotomicExtension {D.natAbs} ℚ (CyclotomicField D.natAbs ℚ) :=
    CyclotomicField.isCyclotomicExtension D.natAbs ℚ
  let _ : IsGalois ℚ (CyclotomicField D.natAbs ℚ) :=
    IsCyclotomicExtension.isGalois {D.natAbs} ℚ _
  let L := CyclotomicField D.natAbs ℚ
  let hζ := IsCyclotomicExtension.zeta_spec D.natAbs ℚ L
  have hstab := DirichletCharacter.stabilizer_gaussSumOfPrimitiveRoot
    (fundamentalDiscriminantChar D hD) (isPrimitive_fundamentalDiscriminantChar hD) hζ
  rw [fundamentalDiscriminantCharacterSubgroup, ← hstab]
  simp only [fundamentalDiscriminantGaussSum, L]
  exact fixedField_stabilizer_eq_adjoin_simple _

/-- A square root of a fundamental discriminant generates the fixed field cut out by its
quadratic character. -/
theorem fixedField_fundamentalDiscriminantCharacterSubgroup_eq_adjoin_of_sq_eq
    (D : ℤ) (hD : IsFundamentalDiscriminant D) {x : CyclotomicField D.natAbs ℚ}
    (hx : x ^ 2 = (D : CyclotomicField D.natAbs ℚ)) :
    fixedField (fundamentalDiscriminantCharacterSubgroup D hD) = ℚ⟮x⟯ := by
  rw [fixedField_fundamentalDiscriminantCharacterSubgroup]
  apply TauCeti.IntermediateField.adjoin_eq_adjoin_of_forall_sq_eq
  · rintro _ rfl
    exact ⟨x, Set.mem_singleton x, (fundamentalDiscriminantGaussSum_sq D hD).trans hx.symm⟩
  · rintro _ rfl
    exact ⟨fundamentalDiscriminantGaussSum D hD, Set.mem_singleton _,
      hx.trans (fundamentalDiscriminantGaussSum_sq D hD).symm⟩

end TauCeti.Multiquadratic
