/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Topology.Algebra.ContinuousMonoidHom
public import TauCeti.Algebra.Group.Subgroup.Normalizer
public import TauCeti.GroupTheory.Commutator
public import TauCeti.GroupTheory.PLowerCentralSeries
public import TauCeti.Topology.Algebra.Group.Subgroup

/-!
# The lower `p`-series of a topological group

The **lower `p`-series** (descending `p`-central series) of a topological group `G` is the
sequence of closed normal subgroups

```text
λ₀ = G,   λ_{k+1} = closure (λ_kᵖ ⬝ [λ_k, G]),
```

where the right-hand side is the topological closure of the subgroup generated by the `p`-th powers
of elements of `λ_k` and the commutators of elements of `λ_k` with elements of `G`. The indexing is
0-based, as for Mathlib's `lowerCentralSeries`, so that `λ_1` is the topological closure of
`Gᵖ [G, G]`. One step of the recursion is `TauCeti.pLowerCentralStep`, whose characteristic
property `TauCeti.pLowerCentralStep_le_iff` characterizes containment in a closed subgroup.

That step is a special case of the two-argument **verbal step**
`TauCeti.pVerbalStep p H K = closure (Hᵖ ⬝ [H, K])`, the closed subgroup generated by the values
of the words `x ^ p` on `H` and `⁅x, y⁆` on `H × K`: the lower `p`-series step is the case
`K = ⊤`, and the case `K = H` is the step of the Frattini series
(`TauCeti.Topology.Algebra.Group.FrattiniSeries`). Closedness, monotonicity, normality, the
characteristic property and the behaviour under continuous homomorphisms are proved once for the
verbal step and specialized to each.

The series is descending, each term is closed and normal, and its successive quotients are central
and killed by `p`: `⁅λ_k, G⁆ ≤ λ_{k+1}` and `x ^ p ∈ λ_{k+1}` for `x ∈ λ_k`. The main theorem is
the **degree-raising law** `⁅λ_j, λ_k⁆ ≤ λ_{j+k+1}`, which lets the group commutator induce a
bracket `λ_j ⧸ λ_{j+1} × λ_k ⧸ λ_{k+1} → λ_{j+k+1} ⧸ λ_{j+k+2}` on the graded pieces. Continuous
homomorphisms carry `λ_k` into `λ_k`, continuous closed surjections (for instance from a compact
group onto a Hausdorff group) carry it onto `λ_k`, and continuous isomorphisms match the two series
term by term. Each `λ_k` is the topological closure of the corresponding term of the abstract lower
`p`-central series `Subgroup.pLowerCentralSeries p ⊤` of the underlying group, so on a discrete
group the two series agree.

Nothing here assumes `p` prime or `G` profinite. For a profinite `G` and a prime `p`, `λ_1` is the
pro-`p` Frattini subgroup and, when `G` is topologically finitely generated, every `λ_k` is open;
see `TauCeti.Topology.Algebra.Group.Profinite.ProP.LowerCentralSeries`.

## Main definitions

* `TauCeti.pVerbalStep`: the verbal step `H, K ↦ closure (Hᵖ ⬝ [H, K])`, of which both the lower
  `p`-series step and the Frattini series step are special cases.
* `TauCeti.pLowerCentralStep`: one step `H ↦ closure (Hᵖ ⬝ [H, G])` of the recursion.
* `TauCeti.pLowerCentralSeries`: the lower `p`-series `λ_k`.

## Main results

* `TauCeti.pVerbalStep_le_iff`, `TauCeti.pLowerCentralStep_le_iff`: a closed subgroup contains
  `pVerbalStep p H K` exactly when it contains the `p`-th powers of `H` and the commutators
  `⁅H, K⁆`, and `pLowerCentralStep p H` exactly when it contains the `p`-th powers of `H` and the
  commutators `⁅H, G⁆`.
* `TauCeti.normal_of_pLowerCentralStep_le_of_le`: a subgroup between `pLowerCentralStep p R` and
  `R` is normal.
* `TauCeti.mk_conjNormal_eq`: conjugation by `G` acts trivially on `N ⧸ Nᵖ[N, G]`.
* `TauCeti.pLowerCentralStep_subgroupOf_le_ker_iff`: a homomorphism on a closed normal subgroup
  `R` with closed kernel kills `pLowerCentralStep p R` exactly when it kills `p`-th powers and is
  invariant under conjugation by `G`.
* `TauCeti.pLowerCentralSeries_antitone`, `TauCeti.isClosed_pLowerCentralSeries`,
  `TauCeti.pLowerCentralSeries_normal`: the series is descending, closed and normal.
* `TauCeti.pow_mem_pLowerCentralSeries`, `TauCeti.commutator_pLowerCentralSeries_top_le`,
  `TauCeti.map_mk'_pLowerCentralSeries_le_center`: `λ_k ⧸ λ_{k+1}` is central in `G ⧸ λ_{k+1}`
  and killed by `p`.
* `TauCeti.commutator_pLowerCentralSeries_le`, `TauCeti.commutator_mem_pLowerCentralSeries`: the
  degree-raising law `⁅λ_j, λ_k⁆ ≤ λ_{j+k+1}`.
* `MonoidHom.map_pLowerCentralSeries_le`, `MonoidHom.map_pLowerCentralSeries_eq_of_surjective`,
  `ContinuousMulEquiv.map_pLowerCentralSeries_eq`: functoriality of the series.
* `TauCeti.pLowerCentralSeries_eq_topologicalClosure`,
  `TauCeti.pLowerCentralSeries_eq_of_discreteTopology`: comparison with the abstract lower
  `p`-central series of the underlying group.

## References

* J. Labute, *Classification of Demushkin groups*, Canadian J. Math. 19 (1967), §1.
* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 2.8.
* J. D. Dixon, M. P. F. du Sautoy, A. Mann and D. Segal, *Analytic pro-`p` groups*, Section 1.2.
-/

public section

namespace TauCeti

open Subgroup
open scoped commutatorElement

/-! ### The verbal step -/

section VerbalStep

variable (p : ℕ) {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The **`p`-verbal step** `H, K ↦ closure (Hᵖ ⬝ [H, K])`: the topological closure of the subgroup
generated by the values of the words `x ^ p` on `H` and `⁅x, y⁆` on `H × K`. Taking `K = ⊤` gives
one step of the lower `p`-series (`TauCeti.pLowerCentralStep`) and taking `K = H` one step of the
Frattini series (`TauCeti.proPFrattiniStep`). Its characteristic property is
`TauCeti.pVerbalStep_le_iff`. -/
def pVerbalStep (H K : Subgroup G) : Subgroup G :=
  (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, K⁆).topologicalClosure

/-- The defining equation `pVerbalStep p H K = closure (Hᵖ ⬝ [H, K])`, with topological closure,
expresses the verbal step in terms of powers and commutators. -/
theorem pVerbalStep_def (H K : Subgroup G) :
    pVerbalStep p H K =
      (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, K⁆).topologicalClosure := by
  rw [pVerbalStep]

variable {p}

/-- The verbal step is a closed subgroup. -/
theorem isClosed_pVerbalStep (H K : Subgroup G) : IsClosed (pVerbalStep p H K : Set G) := by
  rw [pVerbalStep_def]
  exact isClosed_topologicalClosure _

/-- The `p`-th power of an element of `H` lies in `pVerbalStep p H K`. -/
theorem pow_mem_pVerbalStep {H K : Subgroup G} {x : G} (hx : x ∈ H) :
    x ^ p ∈ pVerbalStep p H K := by
  rw [pVerbalStep_def]
  exact le_topologicalClosure _ (mem_sup_left (Subgroup.subset_closure ⟨x, hx, rfl⟩))

/-- The commutators `⁅H, K⁆` lie in `pVerbalStep p H K`. -/
theorem commutator_le_pVerbalStep (H K : Subgroup G) : ⁅H, K⁆ ≤ pVerbalStep p H K := by
  rw [pVerbalStep_def]
  exact le_sup_right.trans (le_topologicalClosure _)

/-- **The characteristic property of the verbal step.** A closed subgroup contains
`pVerbalStep p H K` exactly when it contains the `p`-th powers of the elements of `H` and the
commutators `⁅H, K⁆`. -/
theorem pVerbalStep_le_iff {H K L : Subgroup G} (hL : IsClosed (L : Set G)) :
    pVerbalStep p H K ≤ L ↔ (∀ x ∈ H, x ^ p ∈ L) ∧ ⁅H, K⁆ ≤ L := by
  refine ⟨fun h ↦ ⟨fun x hx ↦ h (pow_mem_pVerbalStep hx),
    (commutator_le_pVerbalStep H K).trans h⟩, fun ⟨hpow, hcomm⟩ ↦ ?_⟩
  rw [pVerbalStep_def]
  refine topologicalClosure_minimal _ (sup_le ((Subgroup.closure_le _).mpr ?_) hcomm) hL
  rintro _ ⟨x, hx, rfl⟩
  exact hpow x hx

/-- The verbal step is monotone in both arguments. -/
theorem pVerbalStep_mono {H K H' K' : Subgroup G} (hH : H ≤ H') (hK : K ≤ K') :
    pVerbalStep p H K ≤ pVerbalStep p H' K' :=
  (pVerbalStep_le_iff (isClosed_pVerbalStep H' K')).mpr
    ⟨fun _ hx ↦ pow_mem_pVerbalStep (hH hx),
      (commutator_mono hH hK).trans (commutator_le_pVerbalStep H' K')⟩

/-- The verbal step of two normal subgroups is normal. -/
instance pVerbalStep_normal (H K : Subgroup G) [H.Normal] [K.Normal] :
    (pVerbalStep p H K).Normal := by
  rw [pVerbalStep_def]
  have : (Subgroup.closure ((· ^ p) '' (H : Set G))).Normal := by
    refine closure_normal_of_forall_conj_mem ?_
    rintro g _ ⟨x, hx, rfl⟩
    exact ⟨g * x * g⁻¹, Normal.conj_mem ‹H.Normal› x hx g, conj_pow⟩
  exact is_normal_topologicalClosure _

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism carries the verbal step of two subgroups into the verbal step of
their images. -/
theorem _root_.MonoidHom.map_pVerbalStep_le (f : G →* H) (hf : Continuous f) (K L : Subgroup G) :
    (pVerbalStep p K L).map f ≤ pVerbalStep p (K.map f) (L.map f) := by
  rw [map_le_iff_le_comap]
  have hclosed : IsClosed ((pVerbalStep p (K.map f) (L.map f)).comap f : Set G) := by
    rw [coe_comap]
    exact (isClosed_pVerbalStep _ _).preimage hf
  refine (pVerbalStep_le_iff hclosed).mpr ⟨fun x hx ↦ ?_, ?_⟩
  · rw [mem_comap, map_pow]
    exact pow_mem_pVerbalStep (mem_map_of_mem f hx)
  · rw [← map_le_iff_le_comap, map_commutator]
    exact commutator_le_pVerbalStep _ _

/-- A continuous closed map (for instance a continuous homomorphism from a compact group to a
Hausdorff group, by `Continuous.isClosedMap`) carries the verbal step of two subgroups onto the
verbal step of their images. No surjectivity is needed: the verbal step refers to `K` and `L`
alone. -/
theorem _root_.MonoidHom.map_pVerbalStep_eq_of_isClosedMap (f : G →* H) (hf : Continuous f)
    (hfc : IsClosedMap f) (K L : Subgroup G) :
    (pVerbalStep p K L).map f = pVerbalStep p (K.map f) (L.map f) := by
  refine le_antisymm (f.map_pVerbalStep_le hf K L) ?_
  have hclosed : IsClosed ((pVerbalStep p K L).map f : Set H) := by
    rw [coe_map]
    exact hfc _ (isClosed_pVerbalStep K L)
  refine (pVerbalStep_le_iff hclosed).mpr ⟨fun y hy ↦ ?_, ?_⟩
  · obtain ⟨x, hx, rfl⟩ := mem_map.mp hy
    exact ⟨x ^ p, pow_mem_pVerbalStep hx, map_pow f x p⟩
  · rw [← map_commutator]
    exact map_mono (commutator_le_pVerbalStep K L)

end VerbalStep

/-! ### One step of the recursion -/

section Step

variable (p : ℕ) {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- One step of the **lower `p`-series**: `H ↦ closure (Hᵖ ⬝ [H, G])`, the verbal step
`TauCeti.pVerbalStep` of `H` against the whole group. Its characteristic property is
`TauCeti.pLowerCentralStep_le_iff`. -/
def pLowerCentralStep (H : Subgroup G) : Subgroup G := pVerbalStep p H ⊤

/-- One step of the lower `p`-series is the verbal step taken against the whole group. -/
theorem pLowerCentralStep_eq_pVerbalStep (H : Subgroup G) :
    pLowerCentralStep p H = pVerbalStep p H ⊤ := by
  rw [pLowerCentralStep]

/-- The defining equation `pLowerCentralStep p H = closure (Hᵖ ⬝ [H, G])`, with topological
closure, expresses the next lower `p`-series step in terms of powers and commutators. -/
theorem pLowerCentralStep_def (H : Subgroup G) :
    pLowerCentralStep p H =
      (Subgroup.closure ((· ^ p) '' (H : Set G)) ⊔ ⁅H, (⊤ : Subgroup G)⁆).topologicalClosure := by
  rw [pLowerCentralStep_eq_pVerbalStep, pVerbalStep_def]

variable {p}

/-- One step of the lower `p`-series is a closed subgroup. -/
theorem isClosed_pLowerCentralStep (H : Subgroup G) :
    IsClosed (pLowerCentralStep p H : Set G) := by
  rw [pLowerCentralStep_eq_pVerbalStep]
  exact isClosed_pVerbalStep H ⊤

/-- The `p`-th power of an element of `H` lies in `pLowerCentralStep p H`. -/
theorem pow_mem_pLowerCentralStep {H : Subgroup G} {x : G} (hx : x ∈ H) :
    x ^ p ∈ pLowerCentralStep p H := by
  rw [pLowerCentralStep_eq_pVerbalStep]
  exact pow_mem_pVerbalStep hx

/-- The commutators `⁅H, G⁆` lie in `pLowerCentralStep p H`. -/
theorem commutator_le_pLowerCentralStep (H : Subgroup G) :
    ⁅H, (⊤ : Subgroup G)⁆ ≤ pLowerCentralStep p H := by
  rw [pLowerCentralStep_eq_pVerbalStep]
  exact commutator_le_pVerbalStep H ⊤

/-- The commutator of an element of `H` with any element lies in `pLowerCentralStep p H`. -/
theorem commutator_mem_pLowerCentralStep {H : Subgroup G} {x : G} (hx : x ∈ H) (y : G) :
    ⁅x, y⁆ ∈ pLowerCentralStep p H :=
  commutator_le_pLowerCentralStep H (commutator_mem_commutator hx (mem_top y))

/-- **The characteristic property of one step.** A closed subgroup contains
`pLowerCentralStep p H` exactly when it contains the `p`-th powers of the elements of `H` and the
commutators `⁅H, G⁆`. -/
theorem pLowerCentralStep_le_iff {H K : Subgroup G} (hK : IsClosed (K : Set G)) :
    pLowerCentralStep p H ≤ K ↔ (∀ x ∈ H, x ^ p ∈ K) ∧ ⁅H, (⊤ : Subgroup G)⁆ ≤ K := by
  rw [pLowerCentralStep_eq_pVerbalStep, pVerbalStep_le_iff hK]

/-- One step of the lower `p`-series is monotone in the subgroup. -/
theorem pLowerCentralStep_mono {H K : Subgroup G} (h : H ≤ K) :
    pLowerCentralStep p H ≤ pLowerCentralStep p K := by
  rw [pLowerCentralStep_eq_pVerbalStep, pLowerCentralStep_eq_pVerbalStep]
  exact pVerbalStep_mono h le_rfl

/-- One step of the lower `p`-series of a normal subgroup is normal. -/
instance pLowerCentralStep_normal (H : Subgroup G) [H.Normal] :
    (pLowerCentralStep p H).Normal := by
  rw [pLowerCentralStep_eq_pVerbalStep]
  infer_instance

/-- One step of the lower `p`-series of a closed normal subgroup lies in that subgroup. -/
theorem pLowerCentralStep_le {H : Subgroup G} [H.Normal] (hH : IsClosed (H : Set G)) :
    pLowerCentralStep p H ≤ H :=
  (pLowerCentralStep_le_iff hH).mpr ⟨fun _ hx ↦ H.pow_mem hx p, commutator_le_left H ⊤⟩

/-- A subgroup squeezed between `pLowerCentralStep p R` and `R` is normal: it contains the
commutators `⁅R, G⁆`, hence its own commutators with `G`. -/
theorem normal_of_pLowerCentralStep_le_of_le {R K : Subgroup G} (hRK : pLowerCentralStep p R ≤ K)
    (hKR : K ≤ R) : K.Normal :=
  commutator_top_right_le_iff.mp
    ((commutator_mono_left hKR).trans ((commutator_le_pLowerCentralStep R).trans hRK))

/-- One step of the lower `p`-series of a subgroup `N`, read inside `N`, is a closed subgroup of
`N`. -/
theorem isClosed_pLowerCentralStep_subgroupOf (N : Subgroup G) :
    IsClosed ((pLowerCentralStep p N).subgroupOf N : Set N) :=
  (isClosed_pLowerCentralStep N).preimage continuous_subtype_val

/-- `N ⧸ Nᵖ[N, G]` is an abstract `p`-group: the `p`-th power of every element is `1`, since the
`p`-th powers of the elements of `N` lie in `pLowerCentralStep p N`. -/
theorem isPGroup_quotient_pLowerCentralStep_subgroupOf (N : Subgroup G) [N.Normal] :
    IsPGroup p (N ⧸ (pLowerCentralStep p N).subgroupOf N) := fun q ↦ by
  obtain ⟨n, rfl⟩ := QuotientGroup.mk_surjective q
  refine ⟨1, ?_⟩
  rw [pow_one, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff, mem_subgroupOf, coe_pow]
  exact pow_mem_pLowerCentralStep n.2

/-- **Conjugation acts trivially on `N ⧸ Nᵖ[N, G]`.** For a normal subgroup `N`, the class of the
conjugate `g n g⁻¹` in the quotient of `N` by `pLowerCentralStep p N` is the class of `n`. -/
@[simp]
theorem mk_conjNormal_eq {N : Subgroup G} [N.Normal] (g : G) (n : N) :
    ((MulAut.conjNormal g n : N) : N ⧸ (pLowerCentralStep p N).subgroupOf N) = n := by
  rw [QuotientGroup.eq, mem_subgroupOf, coe_mul, coe_inv, MulAut.conjNormal_apply]
  have h : ((g * (n : G) * g⁻¹)⁻¹ * n : G) = ⁅(n : G)⁻¹, g⁆⁻¹ := by
    rw [commutatorElement_inv, commutatorElement_def]
    group
  rw [h]
  exact (pLowerCentralStep p N).inv_mem (commutator_mem_pLowerCentralStep (N.inv_mem n.2) g)

/-- **Homomorphisms out of `R` that factor through `R ⧸ Rᵖ[R, G]`.** For a closed normal subgroup
`R` and a homomorphism `φ` on `R` with closed kernel, `φ` kills `pLowerCentralStep p R` exactly when
it kills the `p`-th powers and is invariant under conjugation by `G`. -/
theorem pLowerCentralStep_subgroupOf_le_ker_iff {R : Subgroup G} [R.Normal]
    (hR : IsClosed (R : Set G)) {A : Type*} [Group A] (φ : R →* A)
    (hφ : IsClosed (φ.ker : Set R)) :
    (pLowerCentralStep p R).subgroupOf R ≤ φ.ker ↔
      (∀ r : R, φ r ^ p = 1) ∧ ∀ (g : G) (r : R), φ (MulAut.conjNormal g r) = φ r := by
  constructor
  · intro h
    refine ⟨fun r ↦ ?_, fun g r ↦ ?_⟩
    · rw [← map_pow]
      exact h (mem_subgroupOf.mpr (by rw [coe_pow]; exact pow_mem_pLowerCentralStep r.2))
    · have hmem : ⁅g, (r : G)⁆ ∈ pLowerCentralStep p R := by
        rw [← commutatorElement_inv]
        exact (pLowerCentralStep p R).inv_mem (commutator_mem_pLowerCentralStep r.2 g)
      have hconj : MulAut.conjNormal g r =
          ⟨⁅g, (r : G)⁆, commutator_le_right ⊤ R (commutator_mem_commutator (mem_top g) r.2)⟩ * r :=
        Subtype.ext (by simp only [MulAut.conjNormal_apply, coe_mul, commutatorElement_def]; group)
      rw [hconj, map_mul, MonoidHom.mem_ker.mp (h (mem_subgroupOf.mpr hmem)), one_mul]
  · rintro ⟨hpow, hconj⟩
    -- The image of the kernel in `G` is a closed subgroup containing `Rᵖ` and `⁅R, G⁆`.
    have hK : IsClosed ((φ.ker.map R.subtype : Subgroup G) : Set G) := by
      rw [coe_map, coe_subtype]
      exact hR.isClosedMap_subtype_val _ hφ
    have hle : pLowerCentralStep p R ≤ φ.ker.map R.subtype := by
      refine (pLowerCentralStep_le_iff hK).mpr ⟨fun x hx ↦ ?_, commutator_le.mpr fun x hx g _ ↦ ?_⟩
      · exact ⟨⟨x, hx⟩ ^ p, MonoidHom.mem_ker.mpr (by rw [map_pow, hpow]), rfl⟩
      · have hxg : ⁅x, g⁆ ∈ R := commutator_le_left R ⊤ (commutator_mem_commutator hx (mem_top g))
        refine ⟨⟨⁅x, g⁆, hxg⟩, MonoidHom.mem_ker.mpr ?_, rfl⟩
        have : (⟨⁅x, g⁆, hxg⟩ : R) = ⟨x, hx⟩ * MulAut.conjNormal g (⟨x, hx⟩ : R)⁻¹ :=
          Subtype.ext (by
            simp only [MulAut.conjNormal_apply, coe_mul, coe_inv, commutatorElement_def]; group)
        rw [this, map_mul, hconj, map_inv, mul_inv_cancel]
    refine (comap_mono hle).trans ?_
    rw [comap_map_eq, ker_subtype, sup_bot_eq]

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism carries one step of the lower `p`-series of a subgroup into the
corresponding step for the image of that subgroup. -/
theorem _root_.MonoidHom.map_pLowerCentralStep_le (f : G →* H) (hf : Continuous f)
    (K : Subgroup G) : (pLowerCentralStep p K).map f ≤ pLowerCentralStep p (K.map f) := by
  rw [pLowerCentralStep_eq_pVerbalStep, pLowerCentralStep_eq_pVerbalStep]
  exact (f.map_pVerbalStep_le hf K ⊤).trans (pVerbalStep_mono le_rfl le_top)

/-- A continuous closed surjection (for instance a continuous surjection from a compact group onto
a Hausdorff group, by `Continuous.isClosedMap`) carries one step of the lower `p`-series of a
subgroup onto the corresponding step for its image. -/
theorem _root_.MonoidHom.map_pLowerCentralStep_eq_of_surjective (f : G →* H) (hf : Continuous f)
    (hfc : IsClosedMap f) (hsurj : Function.Surjective f) (K : Subgroup G) :
    (pLowerCentralStep p K).map f = pLowerCentralStep p (K.map f) := by
  rw [pLowerCentralStep_eq_pVerbalStep, pLowerCentralStep_eq_pVerbalStep,
    f.map_pVerbalStep_eq_of_isClosedMap hf hfc, map_top_of_surjective f hsurj]

end Step

/-! ### The series -/

section Series

variable (p : ℕ) (G : Type*) [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The **lower `p`-series** (descending `p`-central series) of a topological group, 0-based to
match Mathlib's `lowerCentralSeries`: `λ₀ = G` and `λ_{k+1} = closure (λ_kᵖ ⬝ [λ_k, G])`. Its
terms are closed normal subgroups with `⁅λ_j, λ_k⁆ ≤ λ_{j+k+1}`
(`TauCeti.commutator_pLowerCentralSeries_le`). For a profinite group and a prime `p`, `λ_1` is the
pro-`p` Frattini subgroup (`TauCeti.pLowerCentralSeries_one_eq_proPFrattini`). -/
def pLowerCentralSeries : ℕ → Subgroup G
  | 0 => ⊤
  | k + 1 => pLowerCentralStep p (pLowerCentralSeries k)

@[simp]
theorem pLowerCentralSeries_zero : pLowerCentralSeries p G 0 = ⊤ := by
  rw [pLowerCentralSeries]

variable {G} in
/-- Every element lies in `λ_0 = G`. -/
theorem mem_pLowerCentralSeries_zero (g : G) : g ∈ pLowerCentralSeries p G 0 := by
  rw [pLowerCentralSeries_zero]
  exact Subgroup.mem_top g

@[simp]
theorem pLowerCentralSeries_succ (k : ℕ) :
    pLowerCentralSeries p G (k + 1) = pLowerCentralStep p (pLowerCentralSeries p G k) := by
  rw [pLowerCentralSeries]

variable {p G}

/-- Every term of the lower `p`-series is a normal subgroup. -/
instance pLowerCentralSeries_normal (k : ℕ) : (pLowerCentralSeries p G k).Normal := by
  induction k with
  | zero => rw [pLowerCentralSeries_zero]; infer_instance
  | succ k _ => rw [pLowerCentralSeries_succ]; infer_instance

/-- Every term of the lower `p`-series is closed. -/
theorem isClosed_pLowerCentralSeries (k : ℕ) : IsClosed (pLowerCentralSeries p G k : Set G) := by
  cases k with
  | zero => rw [pLowerCentralSeries_zero, coe_top]; exact isClosed_univ
  | succ k => rw [pLowerCentralSeries_succ]; exact isClosed_pLowerCentralStep _

/-- The lower `p`-series is descending. -/
theorem pLowerCentralSeries_succ_le (k : ℕ) :
    pLowerCentralSeries p G (k + 1) ≤ pLowerCentralSeries p G k := by
  rw [pLowerCentralSeries_succ]
  exact pLowerCentralStep_le (isClosed_pLowerCentralSeries k)

/-- The lower `p`-series is antitone. -/
theorem pLowerCentralSeries_antitone : Antitone (pLowerCentralSeries p G) :=
  antitone_nat_of_succ_le pLowerCentralSeries_succ_le

/-- The `p`-th power of an element of `λ_k` lies in `λ_{k+1}`. -/
theorem pow_mem_pLowerCentralSeries {k : ℕ} {x : G} (hx : x ∈ pLowerCentralSeries p G k) :
    x ^ p ∈ pLowerCentralSeries p G (k + 1) := by
  rw [pLowerCentralSeries_succ]
  exact pow_mem_pLowerCentralStep hx

/-- The commutators `⁅λ_k, G⁆` lie in `λ_{k+1}`. -/
theorem commutator_pLowerCentralSeries_top_le (k : ℕ) :
    ⁅pLowerCentralSeries p G k, (⊤ : Subgroup G)⁆ ≤ pLowerCentralSeries p G (k + 1) := by
  rw [pLowerCentralSeries_succ]
  exact commutator_le_pLowerCentralStep _

/-- The commutator of an element of `λ_k` with any element lies in `λ_{k+1}`. -/
theorem commutator_mem_pLowerCentralSeries_succ {k : ℕ} {x : G}
    (hx : x ∈ pLowerCentralSeries p G k) (y : G) : ⁅x, y⁆ ∈ pLowerCentralSeries p G (k + 1) :=
  commutator_pLowerCentralSeries_top_le k (commutator_mem_commutator hx (mem_top y))

/-- **Centrality of the graded pieces.** The image of `λ_k` in `G ⧸ λ_{k+1}` is central. -/
theorem map_mk'_pLowerCentralSeries_le_center (k : ℕ) :
    (pLowerCentralSeries p G k).map (QuotientGroup.mk' (pLowerCentralSeries p G (k + 1))) ≤
      center (G ⧸ pLowerCentralSeries p G (k + 1)) := by
  rw [← commutator_top_right_eq_bot_iff_le_center,
    ← map_top_of_surjective _ (QuotientGroup.mk'_surjective _), ← commutator_le_iff_map_mk'_eq_bot]
  exact commutator_pLowerCentralSeries_top_le k

/-- The first term of the lower `p`-series is the topological closure of `Gᵖ [G, G]`. -/
theorem pLowerCentralSeries_one :
    pLowerCentralSeries p G 1 =
      (Subgroup.closure (Set.range fun g : G ↦ g ^ p) ⊔ commutator G).topologicalClosure := by
  rw [pLowerCentralSeries_succ, pLowerCentralSeries_zero, pLowerCentralStep_def, coe_top,
    Set.image_univ, commutator_def]

/-- **The degree-raising law.** Commutators of `λ_j` with `λ_k` lie in `λ_{j+k+1}`. -/
theorem commutator_pLowerCentralSeries_le (j k : ℕ) :
    ⁅pLowerCentralSeries p G j, pLowerCentralSeries p G k⁆ ≤
      pLowerCentralSeries p G (j + k + 1) := by
  induction k generalizing j with
  | zero => simpa using commutator_pLowerCentralSeries_top_le (p := p) (G := G) j
  | succ k ih =>
    -- Write the target as `N = λ_{m+1}` with `m = j + k + 1`, so that `λ_m ⧸ N` is central in
    -- `G ⧸ N` and killed by `p`.
    rw [← add_assoc]
    set N := pLowerCentralSeries p G (j + k + 1 + 1) with hN
    have hNclosed : IsClosed (N : Set G) := isClosed_pLowerCentralSeries _
    rw [pLowerCentralSeries_succ, pLowerCentralStep_def]
    refine commutator_topologicalClosure_right_le hNclosed ?_
    rw [commutator_sup_left]
    refine sup_le ?_ ?_
    · -- The `p`-th powers: `⁅a, y⁆ ∈ λ_m` commutes with `y` modulo `N`, so `⁅a, y ^ p⁆` is
      -- `⁅a, y⁆ ^ p` modulo `N`, and `⁅a, y⁆ ^ p ∈ N`.
      rw [commutator_closure_le_iff]
      rintro a ha _ ⟨y, hy, rfl⟩
      have hc : ⁅a, y⁆ ∈ pLowerCentralSeries p G (j + k + 1) :=
        commutator_le.mp (ih j) a ha y hy
      exact (commutatorElement_pow_right_mem_iff (commutator_mem_pLowerCentralSeries_succ hc y)
        p).mpr (pow_mem_pLowerCentralSeries hc)
    · -- The commutators: the three subgroups lemma in `G ⧸ N`.
      rw [commutator_comm, commutator_le_iff_map_mk'_eq_bot, map_commutator]
      refine commutator_commutator_eq_bot_of_rotate ?_ ?_
      · rw [← map_commutator, ← commutator_le_iff_map_mk'_eq_bot]
        calc ⁅⁅(⊤ : Subgroup G), pLowerCentralSeries p G j⁆, pLowerCentralSeries p G k⁆
            ≤ ⁅pLowerCentralSeries p G (j + 1), pLowerCentralSeries p G k⁆ :=
              commutator_mono_left
                ((commutator_comm _ _).le.trans (commutator_pLowerCentralSeries_top_le j))
          _ ≤ pLowerCentralSeries p G (j + 1 + k + 1) := ih (j + 1)
          _ = N := by rw [hN, add_right_comm j 1 k]
      · rw [← map_commutator, ← commutator_le_iff_map_mk'_eq_bot]
        exact (commutator_mono_left (ih j)).trans (commutator_pLowerCentralSeries_top_le _)

/-- **The degree-raising law, elementwise.** The commutator of an element of `λ_j` with an element
of `λ_k` lies in `λ_{j+k+1}`. -/
theorem commutator_mem_pLowerCentralSeries {j k : ℕ} {x y : G}
    (hx : x ∈ pLowerCentralSeries p G j) (hy : y ∈ pLowerCentralSeries p G k) :
    ⁅x, y⁆ ∈ pLowerCentralSeries p G (j + k + 1) :=
  commutator_le.mp (commutator_pLowerCentralSeries_le j k) x hx y hy

/-! ### Comparison with the abstract lower `p`-central series -/

/-- Every term of the lower `p`-series is the topological closure of the corresponding term of the
abstract lower `p`-central series `Subgroup.pLowerCentralSeries p ⊤` of the underlying group. -/
theorem pLowerCentralSeries_eq_topologicalClosure (k : ℕ) :
    pLowerCentralSeries p G k = ((⊤ : Subgroup G).pLowerCentralSeries p k).topologicalClosure := by
  induction k with
  | zero =>
    rw [pLowerCentralSeries_zero, Subgroup.pLowerCentralSeries_zero]
    exact (top_le_iff.mp (le_topologicalClosure ⊤)).symm
  | succ k ih =>
    rw [pLowerCentralSeries_succ, ih, Subgroup.pLowerCentralSeries_succ]
    refine le_antisymm ((pLowerCentralStep_le_iff (isClosed_topologicalClosure _)).mpr
      ⟨fun x hx ↦ ?_, ?_⟩) (topologicalClosure_minimal _ (sup_le ((Subgroup.closure_le _).mpr ?_)
        ((commutator_mono (le_topologicalClosure _) le_rfl).trans
          (commutator_le_pLowerCentralStep _))) (isClosed_pLowerCentralStep _))
    · -- `p`-th powers of the closure of `μ_k` lie in the closure of the `p`-th powers of `μ_k`.
      rw [← SetLike.mem_coe, topologicalClosure_coe] at hx ⊢
      exact map_mem_closure (f := fun g : G ↦ g ^ p) (continuous_pow p) hx fun y hy ↦
        mem_sup_left (Subgroup.subset_closure ⟨y, hy, rfl⟩)
    · rw [commutator_comm]
      refine commutator_topologicalClosure_right_le (isClosed_topologicalClosure _) ?_
      rw [commutator_comm]
      exact le_sup_right.trans (le_topologicalClosure _)
    · rintro _ ⟨x, hx, rfl⟩
      exact pow_mem_pLowerCentralStep (le_topologicalClosure _ hx)

/-- On a discrete group the lower `p`-series is the abstract lower `p`-central series of the
group. -/
theorem pLowerCentralSeries_eq_of_discreteTopology [DiscreteTopology G] (k : ℕ) :
    pLowerCentralSeries p G k = (⊤ : Subgroup G).pLowerCentralSeries p k := by
  rw [pLowerCentralSeries_eq_topologicalClosure]
  exact le_antisymm (topologicalClosure_minimal _ le_rfl (isClosed_discrete _))
    (le_topologicalClosure _)

/-! ### Functoriality -/

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism carries `λ_k` into `λ_k`. -/
theorem _root_.MonoidHom.map_pLowerCentralSeries_le (f : G →* H) (hf : Continuous f) (k : ℕ) :
    (pLowerCentralSeries p G k).map f ≤ pLowerCentralSeries p H k := by
  induction k with
  | zero => rw [pLowerCentralSeries_zero]; exact le_top
  | succ k ih =>
    rw [pLowerCentralSeries_succ, pLowerCentralSeries_succ]
    exact (f.map_pLowerCentralStep_le hf _).trans (pLowerCentralStep_mono ih)

/-- A continuous closed surjection (for instance a continuous surjection from a compact group onto
a Hausdorff group, by `Continuous.isClosedMap`) carries `λ_k` onto `λ_k`. -/
theorem _root_.MonoidHom.map_pLowerCentralSeries_eq_of_surjective (f : G →* H) (hf : Continuous f)
    (hfc : IsClosedMap f) (hsurj : Function.Surjective f) (k : ℕ) :
    (pLowerCentralSeries p G k).map f = pLowerCentralSeries p H k := by
  induction k with
  | zero =>
    rw [pLowerCentralSeries_zero, pLowerCentralSeries_zero]
    exact map_top_of_surjective f hsurj
  | succ k ih =>
    rw [pLowerCentralSeries_succ, pLowerCentralSeries_succ,
      f.map_pLowerCentralStep_eq_of_surjective hf hfc hsurj, ih]

/-- A topological group isomorphism matches the lower `p`-series of its source and target term by
term. In particular, every term of the lower `p`-series is stable under continuous
automorphisms. -/
theorem _root_.ContinuousMulEquiv.map_pLowerCentralSeries_eq (e : G ≃ₜ* H) (k : ℕ) :
    (pLowerCentralSeries p G k).map e.toMulEquiv.toMonoidHom = pLowerCentralSeries p H k := by
  refine le_antisymm (MonoidHom.map_pLowerCentralSeries_le _ e.continuous k) fun x hx ↦ ?_
  have hsymm : e.symm x ∈ pLowerCentralSeries p G k :=
    e.symm.toMulEquiv.toMonoidHom.map_pLowerCentralSeries_le e.symm.continuous k
      (mem_map_of_mem _ hx)
  exact ⟨e.symm x, hsymm, e.apply_symm_apply x⟩

/-- A group isomorphism between discrete groups matches their lower `p`-series term by term. -/
theorem _root_.MulEquiv.map_pLowerCentralSeries_eq_of_discreteTopology [DiscreteTopology G]
    [DiscreteTopology H] (e : G ≃* H) (k : ℕ) :
    (pLowerCentralSeries p G k).map e.toMonoidHom = pLowerCentralSeries p H k :=
  ContinuousMulEquiv.map_pLowerCentralSeries_eq
    ⟨e, continuous_of_discreteTopology, continuous_of_discreteTopology⟩ k

end Series

end TauCeti
