/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.Topology.Algebra.Group.Subgroup
public import TauCeti.Topology.Algebra.ContinuousMonoidHom
import Mathlib.Algebra.Ring.Int.Parity

/-!
# Subgroups and topological closure

This file records how subgroup constructions interact with topological closure. It provides
normality of the closure of a normal closure, the kernel criterion for a closed normal closure,
and compatibility of multiplicative and additive subgroup closures. It also records that a
dense subgroup meets every open subgroup densely.

Mathlib's theorem that the topological closure of a subgroup is closed is registered as an
instance, so that the quotient of a topological group by the topological closure of a normal
subgroup is found to be a Hausdorff topological group by instance search alone.

The **closed normal closure** of a set `s`, the topological closure of `Subgroup.normalClosure s`,
is the least closed normal subgroup containing `s`
(`Subgroup.topologicalClosure_normalClosure_le_iff`), and it is `N` itself when `s` is the carrier
of a closed normal subgroup `N` (`Subgroup.topologicalClosure_normalClosure_eq_self`), for
instance the kernel of a continuous homomorphism to a `T1` group
(`ContinuousMonoidHom.topologicalClosure_normalClosure_ker`). This is the fact behind the
universal property of a group presented by generators and relators inside a category of
topological groups.

A continuous homomorphism carries the topological closure of a subgroup into the topological
closure of its image, and a closed subgroup containing the commutators `⁅A, B⁆` also contains the
commutators `⁅A, closure B⁆`. These are the two closure facts needed to run commutator calculus on
closed subgroups that are given as topological closures, such as the terms of a lower central
series of a profinite group.

## Main results

* `Subgroup.continuous_inclusion`: the inclusion of a subgroup into a larger one is continuous.
* `Subgroup.continuous_subgroupOf_codRestrict`: the inclusion of `U ⊓ D` into `U`, presented
  using `U.subgroupOf D`, is continuous.
* `Dense.denseRange_subgroupOf_codRestrict`: a dense subgroup meets an open subgroup densely.
* `Subgroup.instIsClosedTopologicalClosure`: the topological closure of a subgroup is closed.
* `Subgroup.dense_iff_topologicalClosure_eq_top`: a subgroup is dense exactly when its topological
  closure is everything; `IsClosed.subgroup_topologicalClosure_eq`: a closed subgroup is its own
  topological closure.
* `Subgroup.dense_preimage_val_iff_le_topologicalClosure`: a subgroup `H ≤ K` is dense in `K`
  exactly when `K` lies in the topological closure of `H`.
* `TauCeti.instNormal_topologicalClosure_normalClosure`: the closure of a normal closure is
  normal.
* `TauCeti.topologicalClosure_normalClosure_le_ker`: relators killed by a continuous map have
  closed normal closure in its kernel.
* `Subgroup.topologicalClosure_normalClosure_le_iff`: the closed normal closure is the least closed
  normal subgroup containing the set.
* `Subgroup.topologicalClosure_normalClosure_eq_self`: the closed normal closure of a closed normal
  subgroup is that subgroup.
* `ContinuousMonoidHom.topologicalClosure_normalClosure_ker`: the kernel of a continuous
  homomorphism to a `T1` group is its own closed normal closure.
* `Subgroup.toAddSubgroup_topologicalClosure`: converting to an additive subgroup commutes with
  topological closure; `Subgroup.dense_toAddSubgroup_iff`: and preserves density.
* `MonoidHom.map_topologicalClosure_le`: a continuous homomorphism maps the topological closure of
  a subgroup into the topological closure of its image; `MonoidHom.map_topologicalClosure`: with
  equality when the subgroup's closure is compact and the target Hausdorff.
  `Subgroup.isClosed_map` says that images of compact subgroups in Hausdorff groups are closed.
* `Subgroup.commutator_topologicalClosure_right_le`: a closed subgroup containing `⁅A, B⁆`
  contains `⁅A, B.topologicalClosure⁆`.
* `Subgroup.topologicalClosure_commutator_le_of_forall_commutatorElement_mem`: a closed normal
  subgroup containing the commutators of a topological generating set contains the closure of
  the commutator subgroup.
* `Subgroup.instCompactSpace_of_isClosed`: a closed subgroup of a compact group is compact.
* `TauCeti.mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers`: if a closed subgroup `H`
  contains `u ^ 2`, the closed subgroup generated by `u` lies in `H ∪ u • H`.
-/

public section

namespace TauCeti

/-- The closure of the normal closure of a set is a normal subgroup. -/
instance instNormal_topologicalClosure_normalClosure {G : Type*} [Group G]
    [TopologicalSpace G] [IsTopologicalGroup G] (s : Set G) :
    ((Subgroup.normalClosure s).topologicalClosure).Normal := by
  exact Subgroup.is_normal_topologicalClosure _

end TauCeti

namespace TauCeti

/-- The closed normal closure of relators lies in the kernel of a continuous homomorphism that
kills them. -/
theorem topologicalClosure_normalClosure_le_ker {G H : Type*} [Group G] [Group H]
    [TopologicalSpace G] [IsTopologicalGroup G] [TopologicalSpace H] [T1Space H] {s : Set G}
    {f : G →ₜ* H} (hf : ∀ r ∈ s, f r = 1) :
    (Subgroup.normalClosure s).topologicalClosure ≤ f.toMonoidHom.ker := by
  exact Subgroup.topologicalClosure_minimal (Subgroup.normalClosure s)
    (Subgroup.normalClosure_le_normal fun r hr ↦ MonoidHom.mem_ker.mpr (hf r hr))
    (isClosed_singleton.preimage f.continuous)

end TauCeti

namespace Subgroup

variable {G : Type*} [Group G] [TopologicalSpace G]

/-- The inclusion of `U ⊓ D` into `U`, where `U ⊓ D` is presented as the subgroup `U.subgroupOf D`
of `D`, is continuous. -/
theorem continuous_subgroupOf_codRestrict (D U : Subgroup G) :
    Continuous ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2) :=
  (continuous_subtype_val.comp continuous_subtype_val).codRestrict _

/-- **A dense subgroup meets an open subgroup densely.** If `D` is dense and `U` is open, the
inclusion of `U ⊓ D`, presented as the subgroup `U.subgroupOf D` of `D`, into `U` has dense
range. -/
theorem _root_.Dense.denseRange_subgroupOf_codRestrict {D U : Subgroup G}
    (hD : Dense (D : Set G)) (hU : IsOpen (U : Set G)) :
    DenseRange ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2) := by
  -- The range is `D ∩ U`, viewed inside `U`, and `Subtype.val : U → G` is an open map.
  have hrange : Set.range ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2)
      = (Subtype.val : U → G) ⁻¹' (D : Set G) := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact y.1.2
    · intro hxD
      exact ⟨⟨⟨x, hxD⟩, x.2⟩, rfl⟩
  rw [DenseRange, hrange]
  exact hD.preimage hU.isOpenMap_subtype_val

variable [IsTopologicalGroup G]

omit [IsTopologicalGroup G] in
/-- The inclusion of a subgroup into a larger subgroup is continuous. -/
@[fun_prop]
theorem continuous_inclusion {H K : Subgroup G} (h : H ≤ K) : Continuous (inclusion h) :=
  continuous_induced_rng.2 continuous_subtype_val

/-- The topological closure of a subgroup is closed. -/
instance instIsClosedTopologicalClosure (s : Subgroup G) :
    IsClosed (s.topologicalClosure : Set G) :=
  s.isClosed_topologicalClosure

/-- A subgroup is dense exactly when its topological closure is the whole group. -/
@[to_additive /-- An additive subgroup is dense exactly when its topological closure is the whole
group. -/]
theorem dense_iff_topologicalClosure_eq_top {s : Subgroup G} :
    Dense (s : Set G) ↔ s.topologicalClosure = ⊤ := by
  rw [SetLike.ext'_iff, topologicalClosure_coe, coe_top, dense_iff_closure_eq]

/-- A closed subgroup is its own topological closure. -/
@[to_additive /-- A closed additive subgroup is its own topological closure. -/]
theorem _root_.IsClosed.subgroup_topologicalClosure_eq {s : Subgroup G}
    (hs : IsClosed (s : Set G)) : s.topologicalClosure = s :=
  SetLike.coe_injective (topologicalClosure_coe.trans hs.closure_eq)

/-- A subgroup `H ≤ K` is dense in `K` exactly when `K` lies in the topological closure of `H`. -/
theorem dense_preimage_val_iff_le_topologicalClosure {H K : Subgroup G} (h : H ≤ K) :
    Dense ((Subtype.val : K → G) ⁻¹' (H : Set G)) ↔ K ≤ H.topologicalClosure := by
  have himage : (Subtype.val : K → G) '' (Subtype.val ⁻¹' (H : Set G)) = H :=
    Set.image_preimage_eq_of_subset (by rw [Subtype.range_coe_subtype]; exact h)
  constructor
  · intro hd x hx
    have := closure_subtype.1 (hd ⟨x, hx⟩)
    rwa [himage, ← topologicalClosure_coe] at this
  · intro hle x
    rw [closure_subtype, himage, ← topologicalClosure_coe]
    exact hle x.2

omit [IsTopologicalGroup G] in
/-- A closed subgroup of a compact group is compact. -/
instance instCompactSpace_of_isClosed [CompactSpace G] (N : Subgroup G) [IsClosed (N : Set G)] :
    CompactSpace N :=
  (IsClosed.isClosedEmbedding_subtypeVal ‹_›).compactSpace

/-- A closed normal subgroup contains the closed normal closure of `s` exactly when it contains
`s`: the closed normal closure is the least closed normal subgroup containing `s`. -/
@[simp]
theorem topologicalClosure_normalClosure_le_iff {s : Set G} {N : Subgroup G} [N.Normal]
    (hN : IsClosed (N : Set G)) : (normalClosure s).topologicalClosure ≤ N ↔ s ⊆ N :=
  ⟨fun h ↦ subset_normalClosure.trans ((normalClosure s).le_topologicalClosure.trans h),
    fun h ↦ (normalClosure s).topologicalClosure_minimal (normalClosure_le_normal h) hN⟩

/-- The closed normal closure of the carrier of a closed normal subgroup is that subgroup. -/
theorem topologicalClosure_normalClosure_eq_self (N : Subgroup G) [N.Normal]
    (hN : IsClosed (N : Set G)) : (normalClosure (N : Set G)).topologicalClosure = N :=
  le_antisymm ((topologicalClosure_normalClosure_le_iff hN).2 subset_rfl)
    (le_normalClosure.trans (normalClosure (N : Set G)).le_topologicalClosure)

/-- The kernel of a continuous homomorphism to a `T1` group is a closed normal subgroup, so it is
its own closed normal closure. -/
theorem _root_.ContinuousMonoidHom.topologicalClosure_normalClosure_ker {H : Type*} [Group H]
    [TopologicalSpace H] [T1Space H] (φ : G →ₜ* H) :
    (normalClosure ((φ : G →* H).ker : Set G)).topologicalClosure = (φ : G →* H).ker :=
  topologicalClosure_normalClosure_eq_self _ (isClosed_singleton.preimage (map_continuous φ))

/-- Converting a subgroup to an additive subgroup commutes with topological closure. -/
@[simp]
theorem toAddSubgroup_topologicalClosure (S : Subgroup G) :
    S.topologicalClosure.toAddSubgroup = S.toAddSubgroup.topologicalClosure :=
  -- `Additive G` inherits the topology of `G`, and both subgroup closures use the
  -- set-theoretic closure of the same carrier. The definitional reduction is confined
  -- to this bridge so consumers can rewrite without unfolding these representations.
  (rfl)

/-- Converting a subgroup to an additive subgroup preserves density. -/
theorem dense_toAddSubgroup_iff (S : Subgroup G) :
    Dense (S.toAddSubgroup : Set (Additive G)) ↔ Dense (S : Set G) := by
  rw [AddSubgroup.dense_iff_topologicalClosure_eq_top, dense_iff_topologicalClosure_eq_top,
    ← toAddSubgroup_topologicalClosure, ← toAddSubgroup.map_top, toAddSubgroup.injective.eq_iff]

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism maps the topological closure of a subgroup into the topological
closure of its image. -/
theorem _root_.MonoidHom.map_topologicalClosure_le (f : G →* H) (hf : Continuous f)
    (S : Subgroup G) : S.topologicalClosure.map f ≤ (S.map f).topologicalClosure := by
  rw [← SetLike.coe_subset_coe, coe_map, topologicalClosure_coe, topologicalClosure_coe, coe_map]
  exact image_closure_subset_closure_image hf

omit [IsTopologicalGroup G] [IsTopologicalGroup H] in
/-- A continuous homomorphism to a Hausdorff group maps compact subgroups to closed subgroups. -/
theorem isClosed_map [T2Space H] {S : Subgroup G} (hS : IsCompact (S : Set G))
    (f : G →* H) (hf : Continuous f) : IsClosed (S.map f : Set H) := by
  rw [coe_map]
  exact (hS.image hf).isClosed

/-- A continuous homomorphism to a Hausdorff group maps a subgroup's compact topological
closure onto the topological closure of its image. -/
theorem _root_.MonoidHom.map_topologicalClosure [T2Space H] (f : G →* H)
    (hf : Continuous f) (S : Subgroup G) (hS : IsCompact (S.topologicalClosure : Set G)) :
    S.topologicalClosure.map f = (S.map f).topologicalClosure := by
  rw [topologicalClosure_coe] at hS
  rw [← SetLike.coe_set_eq, coe_map, topologicalClosure_coe, topologicalClosure_coe, coe_map]
  exact image_closure_of_isCompact hS hf.continuousOn

open scoped commutatorElement in
/-- A closed subgroup containing the commutators `⁅A, B⁆` contains the commutators
`⁅A, B.topologicalClosure⁆`. -/
theorem commutator_topologicalClosure_right_le {A B N : Subgroup G} (hN : IsClosed (N : Set G))
    (h : ⁅A, B⁆ ≤ N) : ⁅A, B.topologicalClosure⁆ ≤ N := by
  rw [commutator_le] at h ⊢
  intro a ha b hb
  have hcont : Continuous fun y : G ↦ ⁅a, y⁆ := by
    simp only [commutatorElement_def]
    fun_prop
  rw [← SetLike.mem_coe, topologicalClosure_coe] at hb
  exact closure_minimal (fun y hy ↦ h a ha y hy) (hN.preimage hcont) hb

open scoped commutatorElement in
/-- **Commutators of topological generators generate the commutators.** If `s` topologically
generates `G` and `N` is a closed normal subgroup containing the commutators of the elements of
`s`, then `N` contains the closure of the commutator subgroup: the quotient `G ⧸ N` is topologically
generated by pairwise commuting elements, hence commutative. -/
theorem topologicalClosure_commutator_le_of_forall_commutatorElement_mem {s : Set G}
    (hs : (closure s).topologicalClosure = ⊤) {N : Subgroup G} [N.Normal]
    (hN : IsClosed (N : Set G)) (h : ∀ x ∈ s, ∀ y ∈ s, ⁅x, y⁆ ∈ N) :
    (_root_.commutator G).topologicalClosure ≤ N := by
  have : IsClosed (N : Set G) := hN
  -- The images of the generators commute pairwise in `G ⧸ N`, so the closed subgroup they
  -- generate, which is all of `G ⧸ N`, is commutative.
  have hcomm : IsMulCommutative ((closure s).map (QuotientGroup.mk' N)) := by
    rw [MonoidHom.map_closure]
    refine isMulCommutative_closure ?_
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩ -
    rw [← commutatorElement_eq_one_iff_commute, ← map_commutatorElement, QuotientGroup.mk'_apply,
      QuotientGroup.eq_one_iff]
    exact h x hx y hy
  have htop : IsMulCommutative (⊤ : Subgroup (G ⧸ N)) := by
    rw [← (QuotientGroup.mk'_surjective N).denseRange.topologicalClosure_map_subgroup
      QuotientGroup.continuous_mk hs]
    infer_instance
  refine (_root_.commutator G).topologicalClosure_minimal ?_ hN
  rw [_root_.commutator_def, commutator_le]
  intro a _ b _
  rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, map_commutatorElement,
    commutatorElement_eq_one_iff_commute]
  exact setLike_mul_comm (mem_top _) (mem_top _)

end Subgroup

namespace TauCeti

/-- If a closed subgroup `H` contains `u ^ 2`, then the closed subgroup topologically generated
by `u` is contained in `H ∪ u • H`: the even powers of `u` lie in `H`, the odd ones in `u • H`,
and this closed union contains their closure. -/
theorem mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers
    {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (u : G) (H : Subgroup G) (hH : IsClosed (H : Set G)) (hu : u ^ 2 ∈ H)
    {x : G} (hx : x ∈ (Subgroup.zpowers u).topologicalClosure) :
    x ∈ H ∨ u⁻¹ * x ∈ H := by
  have hpow (k : ℤ) : u ^ (2 * k) ∈ H := by
    rw [zpow_mul, show u ^ (2 : ℤ) = u ^ (2 : ℕ) from zpow_natCast u 2]
    exact H.zpow_mem hu k
  have hsubset : (Subgroup.zpowers u : Set G) ⊆
      (H : Set G) ∪ (fun y : G ↦ u⁻¹ * y) ⁻¹' (H : Set G) := by
    rintro _ ⟨k, rfl⟩
    rcases Int.even_or_odd k with hk | hk
    · obtain ⟨k, rfl⟩ := even_iff_exists_two_mul.mp hk
      exact Or.inl (hpow k)
    · obtain ⟨k, rfl⟩ := hk
      right
      simp only [Set.mem_preimage, SetLike.mem_coe]
      rw [add_comm (2 * k) 1, zpow_add, zpow_one, inv_mul_cancel_left]
      exact hpow k
  exact closure_minimal hsubset
    (hH.union (hH.preimage (continuous_const.mul continuous_id))) hx

end TauCeti
