/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Manifold.ContMDiffMap.Chart.Jet

/-!
# The weak Whitney topology for manifold-valued maps

A compact derivative test fixes source and target charts, a compact subset of the source
chart target, a derivative order, and an open set of multilinear maps. A map passes the
test when it carries the compact set into the target chart and its coordinate derivative
lies in the prescribed open set. The topology generated by these tests is the weak Whitney
topology. Derivatives are taken within the extended source chart target, including at boundary
and corner points; values outside the target chart never enter a test.

For maps between normed spaces, this agrees with the global weak Whitney topology.
Evaluation is continuous, so the map space is Hausdorff when the target is Hausdorff.
The topology is not a global function-space instance; use `open scoped
TauCeti.ManifoldWeakWhitney` to select it, which also supplies the Hausdorff instance.

The construction follows M. Hirsch, *Differential Topology*, GTM 33, Chapter 2, §1,
pp. 34–36: the compact-open tests on each derivative generate the weak topology.
On compact source manifolds this is also the strong Whitney topology.
-/

public section

open Set Filter Topology
open scoped Manifold

namespace ContMDiffMap

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜]
  {E : Type*} [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners 𝕜 E H}
  {n : WithTop ℕ∞}
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
  {F : Type*} [NormedAddCommGroup F] [NormedSpace 𝕜 F]
  {G : Type*} [TopologicalSpace G] {J : ModelWithCorners 𝕜 F G}
  {N : Type*} [TopologicalSpace N] [ChartedSpace G N]

/-- A chart derivative test. Each tested point must map into the chosen target chart;
only there is its coordinate derivative used. Compactness and openness are imposed when
these sets generate the weak Whitney topology. -/
def chartJetSet [hI : IsManifold I n M] [hJ : IsManifold J n N] (x : M) (y : N) (m : ℕ)
    (K : Set (extChartAt I x).target) (V : Set (E [×m]→L[𝕜] F)) :
    Set C^n⟮I, M; J, N⟯ :=
  let _ := hI
  let _ := hJ
  {f | ∀ z ∈ K, f ((extChartAt I x).symm z) ∈ (extChartAt J y).source ∧
    iteratedFDerivWithin 𝕜 m (extChartAt J y ∘ f ∘ (extChartAt I x).symm)
      (extChartAt I x).target z ∈ V}

/-- Membership in a chart derivative test records both chart validity and derivative control. -/
@[simp]
theorem mem_chartJetSet [IsManifold I n M] [IsManifold J n N]
    {x : M} {y : N} {m : ℕ}
    {K : Set (extChartAt I x).target} {V : Set (E [×m]→L[𝕜] F)}
    {f : C^n⟮I, M; J, N⟯} :
    f ∈ chartJetSet x y m K V ↔
      ∀ z ∈ K, f ((extChartAt I x).symm z) ∈ (extChartAt J y).source ∧
        iteratedFDerivWithin 𝕜 m (extChartAt J y ∘ f ∘ (extChartAt I x).symm)
          (extChartAt I x).target z ∈ V := Iff.rfl

/-- The weak Whitney topology on manifold-valued `C^n` maps, generated by compact-open
coordinate-derivative tests of every finite order at most `n`. -/
@[instance_reducible]
noncomputable def manifoldWeakWhitneyTopology [IsManifold I n M] [IsManifold J n N] :
    TopologicalSpace C^n⟮I, M; J, N⟯ :=
  .generateFrom {s | ∃ (x : M) (y : N) (m : ℕ), m ≤ n ∧
    ∃ (K : Set (extChartAt I x).target), IsCompact K ∧
      ∃ (V : Set (E [×m]→L[𝕜] F)), IsOpen V ∧ s = chartJetSet x y m K V}

section Topology

variable [IsManifold I n M] [IsManifold J n N]

attribute [local instance] manifoldWeakWhitneyTopology

/-- Compact chart derivative tests with open targets are open in the weak Whitney topology. -/
theorem isOpen_chartJetSet (x : M) (y : N) (m : ℕ) (hm : m ≤ n)
    {K : Set (extChartAt I x).target} (hK : IsCompact K)
    {V : Set (E [×m]→L[𝕜] F)} (hV : IsOpen V) :
    IsOpen (chartJetSet (J := J) (n := n) x y m K V) :=
  TopologicalSpace.isOpen_generateFrom_of_mem ⟨x, y, m, hm, K, hK, V, hV, rfl⟩

/-- A family is Whitney-continuous exactly when the inverse image of every compact chart
derivative test is open. -/
theorem continuous_manifoldWeakWhitney_iff {P : Type*} [TopologicalSpace P]
    {g : P → C^n⟮I, M; J, N⟯} :
    Continuous g ↔ ∀ (x : M) (y : N) (m : ℕ), m ≤ n →
      ∀ (K : Set (extChartAt I x).target), IsCompact K →
        ∀ (V : Set (E [×m]→L[𝕜] F)), IsOpen V →
          IsOpen (g ⁻¹' chartJetSet x y m K V) := by
  rw [continuous_generateFrom_iff]
  constructor
  · intro h x y m hm K hK V hV
    exact h _ ⟨x, y, m, hm, K, hK, V, hV, rfl⟩
  · rintro h _ ⟨x, y, m, hm, K, hK, V, hV, rfl⟩
    exact h x y m hm K hK V hV

/-- Convergence is eventual membership in every compact chart derivative test passed by
the limiting map. -/
theorem tendsto_manifoldWeakWhitney_iff {P : Type*} {l : Filter P}
    {g : P → C^n⟮I, M; J, N⟯} {f : C^n⟮I, M; J, N⟯} :
    Tendsto g l (𝓝 f) ↔ ∀ (x : M) (y : N) (m : ℕ), m ≤ n →
      ∀ (K : Set (extChartAt I x).target), IsCompact K →
        ∀ (V : Set (E [×m]→L[𝕜] F)), IsOpen V →
          f ∈ chartJetSet x y m K V → ∀ᶠ p in l, g p ∈ chartJetSet x y m K V := by
  rw [TopologicalSpace.tendsto_nhds_generateFrom_iff]
  constructor
  · intro h x y m hm K hK V hV hf
    exact h _ ⟨x, y, m, hm, K, hK, V, hV, rfl⟩ hf
  · rintro h _ ⟨x, y, m, hm, K, hK, V, hV, rfl⟩ hf
    exact h x y m hm K hK V hV hf

/-- Evaluation at a fixed source point is continuous for the manifold weak Whitney topology. -/
theorem continuous_eval_manifoldWeakWhitney (x : M) :
    Continuous (fun f : C^n⟮I, M; J, N⟯ ↦ f x) := by
  apply continuous_def.mpr
  intro U hU
  apply isOpen_iff_forall_mem_open.mpr
  intro f hf
  obtain ⟨W, hW, hmem, hsub⟩ := continuousOn_iff.mp
    (continuousOn_extChartAt_symm (I := J) (f x)) _ (mem_extChartAt_target (f x))
      U hU (by simpa only [mem_preimage, extChartAt_to_inv] using hf)
  let z : (extChartAt I x).target := ⟨extChartAt I x x, mem_extChartAt_target x⟩
  let V : Set (E [×0]→L[𝕜] F) := (fun A ↦ A 0) ⁻¹' W
  have hV : IsOpen V := hW.preimage (by fun_prop)
  refine ⟨chartJetSet x (f x) 0 {z} V, ?_,
    isOpen_chartJetSet x (f x) 0 (by simp) isCompact_singleton hV, ?_⟩
  · intro g hg
    have hz := (mem_chartJetSet.mp hg) z (mem_singleton z)
    have hcoord : extChartAt J (f x) (g x) ∈ W := by
      simpa only [V, mem_preimage, iteratedFDerivWithin_zero_apply,
        Function.comp_apply, z, extChartAt_to_inv] using hz.2
    have hsource : g x ∈ (extChartAt J (f x)).source := by
      simpa only [z, extChartAt_to_inv] using hz.1
    have hu := hsub ⟨hcoord, (extChartAt J (f x)).mapsTo hsource⟩
    simpa only [mem_preimage, (extChartAt J (f x)).left_inv hsource] using hu
  · rw [mem_chartJetSet]
    intro w hw
    obtain rfl := mem_singleton_iff.mp hw
    constructor
    · simpa only [z, extChartAt_to_inv] using mem_extChartAt_source (I := J) (f x)
    · simpa only [V, mem_preimage, iteratedFDerivWithin_zero_apply,
        Function.comp_apply, z, extChartAt_to_inv] using hmem

/-- A Hausdorff target gives a Hausdorff weak Whitney map space. -/
theorem t2Space_manifoldWeakWhitney [T2Space N] : T2Space C^n⟮I, M; J, N⟯ :=
  T2Space.of_injective_continuous DFunLike.coe_injective
    (continuous_pi (fun x ↦ continuous_eval_manifoldWeakWhitney x))

end Topology

section VectorTarget

variable [IsManifold I n M]

/-- For a vector-space target, chart tests are exactly compact-open tests on the existing
source-chart derivative maps. -/
theorem chartJetSet_self_target (x : M) (y : F) (m : ℕ) (hm : m ≤ n)
    (K : Set (extChartAt I x).target) (V : Set (E [×m]→L[𝕜] F)) :
    chartJetSet (J := 𝓘(𝕜, F)) (n := n) x y m K V =
      {f | MapsTo (chartIteratedFDeriv f x m hm) K V} := by
  ext f
  simp only [mem_chartJetSet, extChartAt_model_space_eq_id, PartialEquiv.refl_source,
    mem_univ, true_and, mem_ofPred_eq, MapsTo, chartIteratedFDeriv_self_target_apply,
    PartialEquiv.refl_coe, Function.id_comp]

end VectorTarget

section NormedSpaces

/-- On maps between normed spaces, the manifold weak Whitney topology agrees with the existing
topology defined using global iterated derivatives. -/
@[simp]
theorem manifoldWeakWhitneyTopology_self :
    manifoldWeakWhitneyTopology (I := 𝓘(𝕜, E)) (M := E) (J := 𝓘(𝕜, F)) (N := F) (n := n) =
      ContMDiffMap.weakWhitneyTopology := by
  apply le_antisymm
  · apply continuous_id_iff_le.mp
    let : TopologicalSpace C^n⟮𝓘(𝕜, E), E; 𝓘(𝕜, F), F⟯ :=
      manifoldWeakWhitneyTopology
    apply _root_.ContMDiffMap.continuous_weakWhitney_iff.mpr
    intro m hm
    let toTarget : C(E, (extChartAt 𝓘(𝕜, E) (0 : E)).target) :=
      ⟨fun y ↦ ⟨y, by simp only [extChartAt_model_space_eq_id, PartialEquiv.refl_target,
        mem_univ]⟩, continuous_id.subtype_mk (fun _ ↦ by
          simp only [extChartAt_model_space_eq_id, PartialEquiv.refl_target, mem_univ])⟩
    have hchart : Continuous (fun f : C^n⟮𝓘(𝕜, E), E; 𝓘(𝕜, F), F⟯ ↦
        chartIteratedFDeriv f 0 m hm) := by
      apply ContinuousMap.continuous_compactOpen.mpr
      intro K hK V hV
      convert isOpen_chartJetSet (n := n) (0 : E) (0 : F) m hm hK hV using 1
      exact (chartJetSet_self_target 0 0 m hm K V).symm
    have h := (ContinuousMap.continuous_precomp toTarget).comp hchart
    convert h using 1
    funext f
    apply ContinuousMap.ext
    intro y
    simp only [Function.comp_apply, ContinuousMap.comp_apply]
    convert (chartIteratedFDeriv_self_apply f 0 m hm (toTarget y)).symm using 1
    rfl
  · apply continuous_id_iff_le.mp
    let : TopologicalSpace C^n⟮𝓘(𝕜, E), E; 𝓘(𝕜, F), F⟯ :=
      ContMDiffMap.weakWhitneyTopology
    apply continuous_manifoldWeakWhitney_iff.mpr
    intro x y m hm K hK V hV
    rw [chartJetSet_self_target x y m hm]
    have h := (ContinuousMap.continuous_restrict (extChartAt 𝓘(𝕜, E) x).target).comp
      (ContMDiffMap.continuous_iteratedFDerivContinuousMap (k := 𝕜)
        (E := E) (F := F) (n := n) m hm)
    have hchart : Continuous (fun f : C^n⟮𝓘(𝕜, E), E; 𝓘(𝕜, F), F⟯ ↦
        chartIteratedFDeriv f x m hm) := by
      convert h using 1
      funext f
      apply ContinuousMap.ext
      intro z
      simp only [ContinuousMap.restrict_apply, Function.comp_apply]
      exact chartIteratedFDeriv_self_apply f x m hm z
    exact (ContinuousMap.isOpen_setOfPred_mapsTo hK hV).preimage
      hchart

end NormedSpaces

end ContMDiffMap

namespace TauCeti

-- Select the manifold weak Whitney topology.
scoped[TauCeti.ManifoldWeakWhitney] attribute [instance 1100]
  ContMDiffMap.manifoldWeakWhitneyTopology

-- Separation travels with the topology the scope selects.
scoped[TauCeti.ManifoldWeakWhitney] attribute [instance]
  ContMDiffMap.t2Space_manifoldWeakWhitney

end TauCeti
