/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.SeparationQuotient
import TauCeti.RingTheory.Huber.Continuous.ValuativeCriterion
import TauCeti.RingTheory.Ideal.OneAddLocalisation
import Mathlib.RingTheory.Valuation.LocalSubring
import Mathlib.RingTheory.LocalRing.ResidueField.Ideal

/-!
# Emptiness of the analytic locus

This file completes Wedhorn's criterion for the analytic locus of a Huber pair to be empty.
For a pair of definition `(A₀, I)`, the difficult implication starts with two prime ideals
`p ⊆ q` of `A₀`, where `q` contains `I`. If `p` did not contain `I`, a valuation ring of
the residue field at `p` dominating the image of `q` would give a valuation with support `p` and
value `< 1` on `q`. Restricting its value group to the convex subgroup generated by one maximal
nonzero value on a finite generating set of `I`, then extending from `A₀` to `A`, produces a
continuous analytic point. Thus emptiness forces `I ⊆ p`.

After localising `A₀` at `1 + I`, every prime contracts to such a `p` and admits a
specialisation containing `I`. Hence the image of `I` lies in every prime of the localisation.
The ideal-theoretic result `Ideal.exists_forall_pow_eq_pow` makes the powers of `I` eventually
constant. Their images are a neighbourhood basis of zero in `A`, so the closure of zero is open
and the separated quotient is discrete.

## Main result

* `TauCeti.ValuationSpectrum.spaAnalytic_eq_empty_iff_discrete_separationQuotient`:
  **Wedhorn Proposition 7.49(2)**, the analytic locus is empty exactly when the separated
  quotient is discrete.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition 7.49(2).

-/

public section

namespace TauCeti.ValuationSpectrum

open Filter MonoidWithZeroHom TauCeti TauCeti.Huber Topology Valuation

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- A valuation of a ring of definition which is bounded by one everywhere, strictly sub-unit on
the ideal of definition, and nonzero somewhere on that ideal yields a continuous analytic point
of the Huber ring. -/
private theorem exists_isAnalyticPoint_isContinuous_of_valuation
    (P : PairOfDefinition A) {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    (u : Valuation P.ringOfDefinition Γ₀)
    (hu_le : ∀ a : P.ringOfDefinition, u a ≤ 1)
    (hu_lt : ∀ a ∈ P.idealOfDefinition, u a < 1)
    (hu_ne : ∃ a ∈ P.idealOfDefinition, u a ≠ 0) :
    ∃ v : Spv A, IsAnalyticPoint v ∧ v.IsContinuous := by
  classical
  obtain ⟨S, hS⟩ := P.fg_idealOfDefinition
  have hSne : S.Nonempty := by
    by_contra h
    rw [Finset.not_nonempty_iff_eq_empty.mp h, Finset.coe_empty, Ideal.span_empty] at hS
    obtain ⟨a, ha, ha0⟩ := hu_ne
    have ha' : a ∈ (⊥ : Ideal P.ringOfDefinition) := hS.symm ▸ ha
    have haeq : a = 0 := by simpa only [Ideal.mem_bot] using ha'
    exact ha0 (haeq ▸ map_zero u)
  obtain ⟨t₀, ht₀S, ht₀max⟩ := S.exists_max_image u hSne
  have ht₀I : t₀ ∈ P.idealOfDefinition := hS ▸ Ideal.subset_span (Finset.mem_coe.mpr ht₀S)
  have hut₀ne : u t₀ ≠ 0 := by
    intro ht₀zero
    have hSsupp : (S : Set P.ringOfDefinition) ⊆ u.supp := by
      intro x hx
      exact (u.mem_supp_iff x).mpr
        (nonpos_iff_eq_zero.mp (ht₀zero ▸ ht₀max x (Finset.mem_coe.mp hx)))
    obtain ⟨a, haI, ha0⟩ := hu_ne
    apply ha0
    rw [← u.mem_supp_iff]
    exact (hS ▸ Ideal.span_le.mpr hSsupp) haI
  obtain ⟨v, hvcont, ht₀not, -⟩ :=
    P.exists_continuous_coarsened_extension_of_valuation u hu_le hS ht₀I
      (fun t ht ↦ ht₀max t (Finset.mem_coe.mp ht)) (hu_lt t₀ ht₀I) hut₀ne
  refine ⟨v, ?_, hvcont⟩
  rw [isAnalyticPoint_def]
  intro hopen
  have hopen' : IsOpen ((v.supp.comap P.ringOfDefinition.subtype :
      Ideal P.ringOfDefinition) : Set P.ringOfDefinition) := by
    rw [Ideal.coe_comap]
    exact hopen.preimage continuous_subtype_val
  obtain ⟨n, -, hn⟩ := P.isAdic_idealOfDefinition.hasBasis_nhds_zero.mem_iff.mp
    (hopen'.mem_nhds (v.supp.comap P.ringOfDefinition.subtype).zero_mem)
  have ht₀pow : t₀ ^ n ∈ v.supp.comap P.ringOfDefinition.subtype := hn
    (Ideal.pow_mem_pow ht₀I n)
  have ht₀supp : t₀ ∈ v.supp.comap P.ringOfDefinition.subtype :=
    Ideal.IsPrime.mem_of_pow_mem (inferInstance : v.supp.IsPrime) n ht₀pow
  rw [Ideal.mem_comap] at ht₀supp
  exact ht₀not ht₀supp

/-- The valuative heart of Wedhorn Proposition 7.49(2). If `p ⊆ q` are primes of a ring of
definition and `q` contains its ideal of definition, then failure of `p` to contain that ideal
produces a continuous analytic point of the ambient Huber ring. -/
private theorem exists_isAnalyticPoint_isContinuous_of_prime_specialization
    (P : PairOfDefinition A)
    {p q : Ideal P.ringOfDefinition} [p.IsPrime] [q.IsPrime]
    (hpq : p ≤ q) (hIq : P.idealOfDefinition ≤ q) (hIp : ¬P.idealOfDefinition ≤ p) :
    ∃ v : Spv A, IsAnalyticPoint v ∧ v.IsContinuous := by
  classical
  let f : P.ringOfDefinition →+* p.ResidueField := algebraMap _ _
  let R : Subring p.ResidueField := f.range
  let fR : P.ringOfDefinition →+* R := f.rangeRestrict
  let J : Ideal R := q.map fR
  have hfRsurj : Function.Surjective fR := f.rangeRestrict_surjective
  have hfRker : RingHom.ker fR = p := by
    ext a
    rw [RingHom.mem_ker]
    constructor
    · intro h
      exact Ideal.algebraMap_residueField_eq_zero.mp (congrArg Subtype.val h)
    · intro h
      apply Subtype.ext
      exact Ideal.algebraMap_residueField_eq_zero.mpr h
  have hJcomap : J.comap fR = q := by
    dsimp [J]
    rw [Ideal.comap_map_of_surjective fR hfRsurj, ← RingHom.ker_eq_comap_bot,
      hfRker, sup_eq_left.mpr hpq]
  have hJne : J ≠ ⊤ := by
    intro hJ
    have : q = ⊤ := by rw [← hJcomap, hJ, Ideal.comap_top]
    exact Ideal.IsPrime.ne_top (I := q) (by infer_instance) this
  obtain ⟨V, hRV, hJV⟩ := Ideal.image_subset_nonunits_valuationSubring J hJne
  let u : Valuation P.ringOfDefinition V.ValueGroup := V.valuation.comap f
  have hu_le : ∀ a : P.ringOfDefinition, u a ≤ 1 := by
    intro a
    dsimp [u]
    exact (ValuationSubring.valuation_le_one_iff V _).mpr (hRV ⟨a, rfl⟩)
  have hu_lt : ∀ a ∈ P.idealOfDefinition, u a < 1 := by
    intro a ha
    have haJ : fR a ∈ J := Ideal.mem_map_of_mem fR (hIq ha)
    have haV : f a ∈ V.nonunits := hJV ⟨fR a, haJ, rfl⟩
    dsimp [u]
    exact haV
  have hu_ne : ∃ a ∈ P.idealOfDefinition, u a ≠ 0 := by
    obtain ⟨a, haI, hap⟩ := IsConcreteLE.not_le_iff_exists.mp hIp
    refine ⟨a, haI, ?_⟩
    dsimp [u]
    exact (Valuation.ne_zero_iff V.valuation).mpr
      (Ideal.algebraMap_residueField_eq_zero.not.mpr hap)
  exact exists_isAnalyticPoint_isContinuous_of_valuation P u hu_le hu_lt hu_ne

/-- If the analytic locus is empty, an ideal-of-definition prime specialisation cannot cross
the ideal of definition: whenever `p ⊆ q` and `I ⊆ q`, already `I ⊆ p`. -/
private theorem idealOfDefinition_le_of_prime_specialization_of_spaAnalytic_eq_empty
    [IsHuberRing A] (P : PairOfDefinition A) (Aplus : Subring A)
    (hAplus : Aplus ≤ powerBoundedSubring A) (hempty : spaAnalytic Aplus = ∅)
    {p q : Ideal P.ringOfDefinition} [p.IsPrime] [q.IsPrime]
    (hpq : p ≤ q) (hIq : P.idealOfDefinition ≤ q) : P.idealOfDefinition ≤ p := by
  by_contra hIp
  obtain ⟨v, hvana, hvcont⟩ :=
    exists_isAnalyticPoint_isContinuous_of_prime_specialization P hpq hIq hIp
  obtain ⟨H, -, -, hw, -⟩ := hvana.exists_coarsenByUnits_mem_spaAnalytic Aplus
    hAplus hvcont
  rw [hempty] at hw
  exact hw

/-- Under emptiness of the analytic locus, the ideal of definition maps into every prime after
localising the ring of definition at `1 + I`. -/
private theorem map_idealOfDefinition_le_prime_oneAddLocalization
    [IsHuberRing A] (P : PairOfDefinition A) (Aplus : Subring A)
    (hAplus : Aplus ≤ powerBoundedSubring A) (hempty : spaAnalytic Aplus = ∅)
    (C : Type*) [CommRing C] [Algebra P.ringOfDefinition C]
    [IsLocalization (Ideal.oneAdd P.idealOfDefinition) C]
    (Q : Ideal C) (hQ : Q.IsPrime) :
    P.idealOfDefinition.map (algebraMap P.ringOfDefinition C) ≤ Q := by
  let p : Ideal P.ringOfDefinition := Q.comap (algebraMap P.ringOfDefinition C)
  have hp : p.IsPrime := hQ.comap _
  have hpdisj : Disjoint (Ideal.oneAdd P.idealOfDefinition : Set P.ringOfDefinition)
      (p : Set P.ringOfDefinition) :=
    ((IsLocalization.isPrime_iff_isPrime_disjoint
      (Ideal.oneAdd P.idealOfDefinition) C Q).mp hQ).2
  have hsup : p ⊔ P.idealOfDefinition ≠ ⊤ := by
    intro htop
    have hmem : (1 : P.ringOfDefinition) ∈ p ⊔ P.idealOfDefinition := htop.symm ▸ Set.mem_univ 1
    obtain ⟨x, hx, y, hy, hxy⟩ := Submodule.mem_sup.mp hmem
    have hxone : x = 1 + (-y) := by rw [← hxy]; ring
    have hxS : x ∈ Ideal.oneAdd P.idealOfDefinition :=
      (Ideal.mem_oneAdd P.idealOfDefinition).mpr ⟨-y, P.idealOfDefinition.neg_mem hy, hxone⟩
    exact Set.disjoint_left.mp hpdisj hxS hx
  obtain ⟨q, hqmax, hpIq⟩ := Ideal.exists_le_maximal _ hsup
  have : q.IsPrime := hqmax.isPrime
  have hIq : P.idealOfDefinition ≤ q := le_sup_right.trans hpIq
  have hpq : p ≤ q := le_sup_left.trans hpIq
  exact Ideal.map_le_iff_le_comap.mpr
    (idealOfDefinition_le_of_prime_specialization_of_spaAnalytic_eq_empty
      P Aplus hAplus hempty hpq hIq)

/-- **Wedhorn Proposition 7.49(2).** If `Aplus` consists of power-bounded elements (in particular,
if it is a ring of integral elements), its analytic locus is empty if and only if the separated
quotient of the Huber ring `A` is discrete. -/
theorem spaAnalytic_eq_empty_iff_discrete_separationQuotient [IsHuberRing A]
    (Aplus : Subring A) (hAplus : Aplus ≤ powerBoundedSubring A) :
    spaAnalytic Aplus = ∅ ↔ DiscreteTopology (SeparationQuotient A) := by
  constructor
  · intro hempty
    let P : PairOfDefinition A := Classical.choice IsHuberRing.nonempty_pairOfDefinition
    let C := Localization (Ideal.oneAdd P.idealOfDefinition)
    have hprime : ∀ Q : Ideal C, Q.IsPrime →
        P.idealOfDefinition.map (algebraMap P.ringOfDefinition C) ≤ Q :=
      fun Q hQ ↦ map_idealOfDefinition_le_prime_oneAddLocalization
        P Aplus hAplus hempty C Q hQ
    obtain ⟨n, hn⟩ := Ideal.exists_forall_pow_eq_pow
      (C := C) P.fg_idealOfDefinition hprime
    have hopen : IsOpen (Ideal.closure (⊥ : Ideal A) : Set A) :=
      P.isOpen_closure_zero_of_eventually_constant_powers
        ⟨n, hn (n + 1) (Nat.le_succ n)⟩
    let _ : DiscreteTopology (separationQuotientRing (A := A)) :=
      QuotientAddGroup.discreteTopology hopen
    exact (UniformSpace.sepQuotHomeomorphRingQuot A).symm.discreteTopology
  · exact spaAnalytic_eq_empty_of_discrete_separationQuotient Aplus

end TauCeti.ValuationSpectrum
