/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.DirectSum.Basic
public import Mathlib.LinearAlgebra.TensorProduct.Tower
public import TauCeti.Algebra.Group.Coprime
public import TauCeti.RepresentationTheory.Induction.VirtualCharacter

/-!
# The virtual characters induced from a family of subgroups form an ideal

Fix a finite group `G` and a property `P` of its subgroups.  The virtual characters of `G` induced
from subgroups satisfying `P` span an additive subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G P` of the functions on `G`; in Serre's notation,
for `P` the elementary subgroups, this is the image `V_G` of `⨁_{E} R(E) → R(G)`.

The theorem of this file is that `V_G` is an **ideal** of the virtual-character ring `R(G)`
(`TauCeti.ClassFunction.mul_mem_indVirtualCharacters`): multiplying an induced virtual character by
a virtual character of `G` gives another induced virtual character.  This is the projection formula
`TauCeti.indClassFun_comp_subtype_mul` -- Frobenius reciprocity in its module form -- together with
the closure of the virtual characters of a subgroup under restriction and under products.

The family-general induction map is also bundled here as
`TauCeti.ClassFunction.indVirtualCharacterDirectSumAddHom`, the homomorphism
`⨁_{S} R(S) → R(G)`.  Its range is exactly `V_G`.  After tensoring source and target with `ℚ`, a
nonzero multiple of `1` in `V_G` makes the resulting map surjective.  These constructions belong
with the ideal property because they work for an arbitrary family and use no cyclic or elementary
input; `TauCeti.RepresentationTheory.Induction.Artin.Basic` supplies those arithmetic
specializations.

Its consequence `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` is the
standard reduction of an induction theorem to a single membership: `V_G` is all of `R(G)` **iff**
the constant function `1` lies in `V_G`.  Brauer's induction theorem is exactly the statement that
`1 ∈ V_G` for the elementary subgroups, and that arithmetic input is not proved here.

What is proved here is the form in which that membership is established:
`TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff_forall_prime` weakens it to
asking, one prime `p` at a time, for a multiple `m • 1` with `p ∤ m` that is a combination of
induced virtual characters with coefficients in a ring such as `ℤ[ζ]`. The coefficients descend to
`ℤ` by `TauCeti.mem_of_mem_span_of_mem_virtualCharacters`, and the primes are assembled by
`AddSubgroup.mem_of_forall_prime_exists_nsmul_mem`.

## Main definitions

* `TauCeti.ClassFunction.indVirtualCharacters`: the additive subgroup generated by virtual
  characters induced from a family of subgroups.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumAddHom`: the bundled direct-sum induction
  map from the virtual-character lattices of that family.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat`: its scalar extension to
  `ℚ`.

## Main statements

* `TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`: an induced virtual character
  is a virtual character.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_closure_indFDRepCharacter`: induced genuine
  characters already generate the subgroup of induced virtual characters.
* `TauCeti.ClassFunction.range_subtype_comp_indVirtualCharacterDirectSumAddHom`: the range of the
  bundled map is exactly `indVirtualCharacters`.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem`: a
  general criterion for rational surjectivity of the scalar-extended induction map.
* `TauCeti.ClassFunction.mul_mem_indVirtualCharacters`: the ideal property.
* `TauCeti.ClassFunction.nsmul_mem_indVirtualCharacters_of_nsmul_one_mem`: propagation of a
  multiple of `1` to the same multiple of every virtual character.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`: the induction theorem for
  a family of subgroups holds exactly when `1` is induced from that family.
* `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff_forall_prime`: equivalently,
  for every prime `p` some multiple `m • 1` with `p ∤ m` is induced with coefficients in a subring
  of `k` that retracts additively onto `ℤ`.

## References

This is the "`Ind_H^G : R(H) → R(G)` is a homomorphism of `R(G)`-modules -- Frobenius reciprocity
as a module identity" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`, and the reduction step of the
Brauer-induction item of the same layer.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 10.1,
  where `V_G` is introduced and shown to be an ideal, and Theorem 18; Chapter 10, in the proof of
  Theorem 18, for the reduction to one prime at a time over `ℤ[ζ]`.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

open scoped TensorProduct

variable {k : Type u} {G : Type v} [Field k] [Group G] [Finite G]

variable (k G) in
/-- The set of class functions on `G` induced from a virtual character of a subgroup satisfying
`P`.  Its members are genuine virtual characters of `G`
(`TauCeti.ClassFunction.indVirtualCharacters_le_virtualCharacters`); the additive subgroup they
generate is `TauCeti.ClassFunction.indVirtualCharacters`. -/
private def indVirtualCharacterSet (P : Subgroup G → Prop) : Set (G → k) :=
  {u | ∃ S : Subgroup G, P S ∧ ∃ ψ ∈ virtualCharacters k S, indClassFun S ψ = u}

variable (k G) in
/-- **The virtual characters of `G` induced from a family of subgroups**: the additive subgroup of
`G → k` generated by `Ind_S^G ψ` for `S` satisfying `P` and `ψ` a virtual character of `S`.

For `P` the cyclic or elementary subgroups this is the subgroup generated by induction from their
virtual-character lattices; it is the image of the induction map `⨁_S R(S) → R(G)`. -/
def indVirtualCharacters (P : Subgroup G → Prop) : AddSubgroup (G → k) :=
  AddSubgroup.closure (indVirtualCharacterSet k G P)

variable {P Q : Subgroup G → Prop}

/-- A virtual character induced from a subgroup of the family is a member. -/
theorem indClassFun_mem_indVirtualCharacters {S : Subgroup G} (hS : P S) {ψ : S → k}
    (hψ : ψ ∈ virtualCharacters k S) : indClassFun S ψ ∈ indVirtualCharacters k G P :=
  AddSubgroup.subset_closure ⟨S, hS, ψ, hψ, rfl⟩

/-- **Induction preserves `A`-combinations of virtual characters**, for any subring `A` of `k`:
an `A`-combination of virtual characters of a subgroup of the family induces to an
`A`-combination of induced virtual characters, induction being additive and `k`-homogeneous. -/
theorem indClassFun_mem_span_indVirtualCharacters (A : Subring k) {S : Subgroup G} (hS : P S)
    {ψ : S → k} (hψ : ψ ∈ Submodule.span A (virtualCharacters k S : Set (S → k))) :
    indClassFun S ψ ∈ Submodule.span A (indVirtualCharacters k G P : Set (G → k)) := by
  induction hψ using Submodule.span_induction with
  | mem x hx => exact Submodule.subset_span (indClassFun_mem_indVirtualCharacters hS hx)
  | zero => rw [indClassFun_zero]; exact Submodule.zero_mem _
  | add x y _ _ hx hy => rw [indClassFun_add]; exact Submodule.add_mem _ hx hy
  | smul a x _ hx =>
    rw [Subring.smul_def, indClassFun_smul, ← Subring.smul_def]
    exact Submodule.smul_mem _ a hx

/-- The universal property of `TauCeti.ClassFunction.indVirtualCharacters`: it is contained in an
additive subgroup exactly when every induced virtual character of the family is. -/
theorem indVirtualCharacters_le_iff {H : AddSubgroup (G → k)} :
    indVirtualCharacters k G P ≤ H ↔
      ∀ S : Subgroup G, P S → ∀ ψ ∈ virtualCharacters k S, indClassFun S ψ ∈ H := by
  rw [indVirtualCharacters, AddSubgroup.closure_le]
  constructor
  · exact fun h S hS ψ hψ => h ⟨S, hS, ψ, hψ, rfl⟩
  · rintro h - ⟨S, hS, ψ, hψ, rfl⟩
    exact h S hS ψ hψ

/-- **Induced genuine characters generate the induced virtual characters.** Although
`TauCeti.ClassFunction.indVirtualCharacters` is defined by inducing all virtual characters, it is
already generated by the inductions of characters of genuine finite-dimensional representations.
-/
theorem indVirtualCharacters_eq_closure_indFDRepCharacter :
    indVirtualCharacters k G P =
      AddSubgroup.closure
        {f | ∃ S : Subgroup G, P S ∧ ∃ V : FDRep k S, indClassFun S V.character = f} := by
  apply le_antisymm
  · refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ ↦ ?_
    have hle : virtualCharacters k S ≤
        (AddSubgroup.closure
          {f | ∃ T : Subgroup G, P T ∧ ∃ V : FDRep k T, indClassFun T V.character = f}).comap
            (indClassFunAddHom S) := by
      refine virtualCharacters_le fun V ↦ ?_
      rw [AddSubgroup.mem_comap, indClassFunAddHom_apply]
      exact AddSubgroup.subset_closure ⟨S, hS, V, rfl⟩
    have hmem := hle hψ
    rwa [AddSubgroup.mem_comap, indClassFunAddHom_apply] at hmem
  · rw [AddSubgroup.closure_le]
    rintro f ⟨S, hS, V, rfl⟩
    exact indClassFun_mem_indVirtualCharacters hS (character_mem_virtualCharacters V)

/-- Enlarging the family of subgroups enlarges the subgroup of induced virtual characters. -/
theorem indVirtualCharacters_mono (h : ∀ S : Subgroup G, P S → Q S) :
    indVirtualCharacters k G P ≤ indVirtualCharacters k G Q :=
  indVirtualCharacters_le_iff.mpr fun S hS _ hψ =>
    indClassFun_mem_indVirtualCharacters (h S hS) hψ

/-- **An induced virtual character is a virtual character.**  Equivalently, the induction map lands
in `R(G)`, so `TauCeti.ClassFunction.indVirtualCharacters` really is a subgroup of the
virtual-character lattice. -/
theorem indVirtualCharacters_le_virtualCharacters :
    indVirtualCharacters k G P ≤ virtualCharacters k G :=
  indVirtualCharacters_le_iff.mpr fun S _ _ hψ => indClassFun_mem_virtualCharacters S hψ

/-! ### The direct-sum induction map -/

variable (k G) in
/-- **The direct-sum induction homomorphism for a family of subgroups.** Its `S`-component is
`Ind_S^G : R(S) → R(G)`. -/
noncomputable def indVirtualCharacterDirectSumAddHom (P : Subgroup G → Prop) :
    DirectSum {S : Subgroup G // P S} (fun S ↦ ↑(virtualCharacters k (S : Subgroup G))) →+
      virtualCharacters k G := by
  classical
  exact DirectSum.toAddMonoid fun S ↦ indVirtualCharacterAddHom k G S

/-- The direct-sum induction map sends a vector supported at `S` to induction from `S`. -/
@[simp]
theorem indVirtualCharacterDirectSumAddHom_of [DecidableEq {S : Subgroup G // P S}]
    (S : {S : Subgroup G // P S})
    (ψ : virtualCharacters k (S : Subgroup G)) :
    indVirtualCharacterDirectSumAddHom k G P
        (DirectSum.of (fun S : {S : Subgroup G // P S} ↦
          ↑(virtualCharacters k (S : Subgroup G))) S ψ) =
      indVirtualCharacterAddHom k G S ψ := by
  rw [indVirtualCharacterDirectSumAddHom]
  exact DirectSum.toAddMonoid_of _ _ _

/-- The range of the bundled induction map, after forgetting the target subtype, is exactly the
canonical subgroup `indVirtualCharacters k G P`. -/
theorem range_subtype_comp_indVirtualCharacterDirectSumAddHom :
    ((virtualCharacters k G).subtype.comp
      (indVirtualCharacterDirectSumAddHom k G P)).range =
        indVirtualCharacters k G P := by
  classical
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    induction x using DirectSum.induction_on with
    | zero => simp
    | of S ψ =>
        simpa using indClassFun_mem_indVirtualCharacters (P := P) S.2 ψ.2
    | add x y hx hy => simpa using AddSubgroup.add_mem _ hx hy
  · refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ ↦ ?_
    let S' : {S : Subgroup G // P S} := ⟨S, hS⟩
    let ψ' : virtualCharacters k S := ⟨ψ, hψ⟩
    refine AddMonoidHom.mem_range.mpr ⟨DirectSum.of
      (fun S : {S : Subgroup G // P S} ↦ ↑(virtualCharacters k (S : Subgroup G))) S' ψ', ?_⟩
    simpa only [AddMonoidHom.comp_apply, indVirtualCharacterDirectSumAddHom_of,
      AddSubgroup.subtype_apply] using
      indVirtualCharacterAddHom_apply_coe (k := k) (G := G) S' ψ'

/-- **The induced virtual characters form an ideal of the virtual-character ring.**  For a virtual
character `f` of `G` and a virtual character `ψ` of a subgroup `S` of the family, the projection
formula rewrites `f · Ind_S^G ψ` as `Ind_S^G ((Res_S f) · ψ)`, and `(Res_S f) · ψ` is again a
virtual character of `S`, restriction and multiplication both preserving them.

This is the structural half of every induction theorem: once `1` is known to be induced from the
family, `TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff` turns the ideal into
all of `R(G)`. -/
theorem mul_mem_indVirtualCharacters {f u : G → k} (hf : f ∈ virtualCharacters k G)
    (hu : u ∈ indVirtualCharacters k G P) : f * u ∈ indVirtualCharacters k G P := by
  have hle : indVirtualCharacters k G P ≤
      (indVirtualCharacters k G P).comap (AddMonoidHom.mulLeft f) := by
    refine indVirtualCharacters_le_iff.mpr fun S hS ψ hψ => ?_
    have hres : (fun s : S => f s) * ψ ∈ virtualCharacters k S :=
      mul_mem_virtualCharacters (comp_subtype_mem_virtualCharacters S hf) hψ
    have hproj : f * indClassFun S ψ = indClassFun S ((fun s : S => f s) * ψ) :=
      (indClassFun_comp_subtype_mul (virtualCharacters_le_classFunction hf) ψ).symm
    rw [AddSubgroup.mem_comap, AddMonoidHom.coe_mulLeft, hproj]
    exact indClassFun_mem_indVirtualCharacters hS hres
  exact hle hu

/-- If a natural-number multiple of the trivial character is induced from a family, then the same
multiple of every virtual character is induced from that family. -/
theorem nsmul_mem_indVirtualCharacters_of_nsmul_one_mem {n : ℕ}
    (h : n • (1 : G → k) ∈ indVirtualCharacters k G P) {f : G → k}
    (hf : f ∈ virtualCharacters k G) : n • f ∈ indVirtualCharacters k G P := by
  simpa [nsmul_eq_mul, mul_comm] using mul_mem_indVirtualCharacters hf h

/-! ### Rational scalar extension -/

variable (k G) in
/-- The direct-sum induction map after extension of scalars from `ℤ` to `ℚ`. -/
noncomputable def indVirtualCharacterDirectSumBaseChangeRat (P : Subgroup G → Prop) :
    (ℚ ⊗[ℤ] DirectSum {S : Subgroup G // P S}
      (fun S ↦ ↑(virtualCharacters k (S : Subgroup G)))) →ₗ[ℚ]
      (ℚ ⊗[ℤ] ↑(virtualCharacters k G)) :=
  (indVirtualCharacterDirectSumAddHom k G P).toIntLinearMap.baseChange ℚ

/-- Rationalized induction sends a pure tensor to the tensor of its induced component. -/
@[simp]
theorem indVirtualCharacterDirectSumBaseChangeRat_tmul (P : Subgroup G → Prop) (q : ℚ)
    (x : DirectSum {S : Subgroup G // P S}
      (fun S ↦ ↑(virtualCharacters k (S : Subgroup G)))) :
    indVirtualCharacterDirectSumBaseChangeRat k G P (q ⊗ₜ[ℤ] x) =
      q ⊗ₜ[ℤ] indVirtualCharacterDirectSumAddHom k G P x := by
  rw [indVirtualCharacterDirectSumBaseChangeRat, LinearMap.baseChange_tmul,
    AddMonoidHom.coe_toIntLinearMap]

/-- A nonzero multiple of the trivial character in the induced subgroup makes rationalized
induction surjective. -/
theorem indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem
    (P : Subgroup G → Prop) (n : ℕ)
    (hn : n ≠ 0) (h : n • (1 : G → k) ∈ indVirtualCharacters k G P) :
    Function.Surjective (indVirtualCharacterDirectSumBaseChangeRat k G P) := by
  classical
  intro z
  induction z using TensorProduct.inductionOn with
  | add x y hx hy =>
      obtain ⟨x', rfl⟩ := hx
      obtain ⟨y', rfl⟩ := hy
      exact ⟨x' + y', map_add _ _ _⟩
  | tmul q f =>
      have hf : n • (f : G → k) ∈ indVirtualCharacters k G P :=
        nsmul_mem_indVirtualCharacters_of_nsmul_one_mem h f.2
      rw [← range_subtype_comp_indVirtualCharacterDirectSumAddHom] at hf
      obtain ⟨x, hx⟩ := AddMonoidHom.mem_range.mp hf
      have hx' : indVirtualCharacterDirectSumAddHom k G P x = n • f := Subtype.ext hx
      refine ⟨((q / (n : ℚ)) ⊗ₜ[ℤ] x), ?_⟩
      rw [indVirtualCharacterDirectSumBaseChangeRat_tmul, hx']
      rw [← Nat.cast_smul_eq_nsmul ℤ, TensorProduct.tmul_smul]
      rw [← Int.cast_smul_eq_zsmul ℚ]
      have hnq : (n : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr hn
      have hscalar : (((n : ℤ) : ℚ)) • (q / (n : ℚ)) = q := by
        rw [smul_eq_mul]
        field_simp
        ac_rfl
      exact congrArg (fun a : ℚ ↦ a ⊗ₜ[ℤ] f) hscalar

/-- **An induction theorem is a single membership.**  The virtual characters induced from a family
of subgroups exhaust `R(G)` exactly when the constant function `1`, the character of the trivial
representation, is one of them.

Brauer's induction theorem is this statement for the elementary subgroups, and its whole content is
therefore the membership `1 ∈ V_G`. -/
theorem indVirtualCharacters_eq_virtualCharacters_iff :
    indVirtualCharacters k G P = virtualCharacters k G ↔
      (1 : G → k) ∈ indVirtualCharacters k G P := by
  refine ⟨fun h => h ▸ one_mem_virtualCharacters, fun h => le_antisymm
    indVirtualCharacters_le_virtualCharacters fun f hf => ?_⟩
  simpa using mul_mem_indVirtualCharacters hf h

/-- **An induction theorem, one prime at a time and with coefficients in a subring.** Let `A` be a
subring of `k` admitting an additive map `t : A → ℤ` with `t 1 = 1`; for example `ℤ[ζ]` for a root
of unity `ζ` in characteristic zero (`PowerBasis.exists_linearMap_apply_one`). The virtual
characters induced from a family of subgroups exhaust `R(G)` exactly when, for every prime `p`,
some multiple `m • 1` with `p ∤ m` is an `A`-linear combination of them.

This reduces an induction theorem to a separate statement for each prime `p`. In Serre's proof of
Brauer's induction theorem, that statement is supplied, for the elementary subgroups, by the
`p`-elementary subgroups with coefficients in `ℤ[ζ]`, `ζ` a primitive `|G|`-th root of unity; this
declaration does not prove it. -/
theorem indVirtualCharacters_eq_virtualCharacters_iff_forall_prime [IsAlgClosed k]
    [Invertible (Nat.card G : k)] (A : Subring k) (t : A →+ ℤ) (ht : t 1 = 1) :
    indVirtualCharacters k G P = virtualCharacters k G ↔
      ∀ p : ℕ, p.Prime → ∃ m : ℕ, ¬ p ∣ m ∧
        m • (1 : G → k) ∈ Submodule.span A (indVirtualCharacters k G P : Set (G → k)) := by
  rw [indVirtualCharacters_eq_virtualCharacters_iff]
  refine ⟨fun h1 p hp => ⟨1, hp.not_dvd_one, by simpa using Submodule.subset_span h1⟩,
    fun h => AddSubgroup.mem_of_forall_prime_exists_nsmul_mem fun p hp => ?_⟩
  obtain ⟨m, hm, hmA⟩ := h p hp
  exact ⟨m, hm, mem_of_mem_span_of_mem_virtualCharacters A t ht
    indVirtualCharacters_le_virtualCharacters
    (AddSubgroup.nsmul_mem _ one_mem_virtualCharacters _) hmA⟩

end ClassFunction

end TauCeti
