/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.IntermediateField.Adjoin.Algebra
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import TauCeti.Algebra.Field.Subfield.Quadratic
public import TauCeti.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.Algebra.QuadraticDiscriminant
import TauCeti.FieldTheory.Minpoly

/-!
# Quadratic normal forms in intermediate fields

This file contains normal-form lemmas for adjoining one element whose square already lies in an
intermediate field, together with the corresponding quadratic finrank and degree-doubling API.
Conversely, it shows by completing the square that, when `2 ≠ 0`, every quadratic intermediate
field is generated by an element whose square lies in the base field.
The finrank lemmas live here because they combine the normal form with intermediate-field
scalar restriction for one quadratic tower step.
The receiver-style finrank lemmas extend Mathlib's `IntermediateField` API and therefore live in
that namespace; the remaining normal-form API stays in `TauCeti.IntermediateField`.

## Provenance

`exists_add_mul_of_mem_sup_adjoin_sq` is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the formalization
of L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture, where it was a
step in the square-class descent for multiquadratic fields; here it is stated for an arbitrary
field extension.
-/

public section

open IntermediateField

namespace TauCeti.IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- If `x² ∈ F`, then `x` is integral over `F` (it is a root of `X² - x²`). -/
private theorem isIntegral_of_sq_mem {F : IntermediateField K L} {x : L} (hx2 : x ^ 2 ∈ F) :
    IsIntegral F x := by
  have hx2_int : IsIntegral F (x ^ 2) := by
    simpa using isIntegral_algebraMap (R := F) (A := L) (x := (⟨x ^ 2, hx2⟩ : F))
  exact IsIntegral.of_pow (by norm_num : 0 < 2) hx2_int

/-- If `x² ∈ F`, then the minimal polynomial of `x` over `F` has degree at most `2`, since it
divides the nonzero polynomial `X² - x²`. -/
private theorem minpoly_natDegree_le_two_of_sq_mem {F : IntermediateField K L} {x : L}
    (hx2 : x ^ 2 ∈ F) : (minpoly F x).natDegree ≤ 2 := by
  have hpoly_ne : ((Polynomial.X : Polynomial F) ^ 2 - Polynomial.C ⟨x ^ 2, hx2⟩) ≠ 0 :=
    (Polynomial.monic_X_pow_sub_C _ (by decide : (2 : ℕ) ≠ 0)).ne_zero
  have hdeg := minpoly.degree_le_of_ne_zero F x hpoly_ne (by simp)
  rw [Polynomial.degree_X_pow_sub_C (n := 2) (by norm_num)] at hdeg
  exact Polynomial.natDegree_le_iff_degree_le.mpr hdeg

/-- If `x² ∈ F`, every element of `F ⊔ K⟮x⟯` has the form `a + b * x` with
`a, b ∈ F`. -/
theorem exists_add_mul_of_mem_sup_adjoin_sq {F : IntermediateField K L} {x : L}
    (hx2 : x ^ 2 ∈ F) {y : L}
    (hy : y ∈ F ⊔ IntermediateField.adjoin K {x}) :
    ∃ a b : L, a ∈ F ∧ b ∈ F ∧ y = a + b * x := by
  -- Since `x² ∈ F`, the element `x` is integral over `F` and the minimal polynomial of `x`
  -- over `F` divides `X² - x²`, so `F⟮x⟯` carries a power basis `1, x` of dimension `≤ 2`.
  have hx_int : IsIntegral F x := isIntegral_of_sq_mem hx2
  -- View `y` as an element of `F⟮x⟯` and write it on the power basis: `y = c₁ * x + c₀`
  -- with `c₀ c₁ ∈ F`, the coefficients of a polynomial of degree `< dim ≤ 2`.
  rw [← IntermediateField.restrictScalars_adjoin_eq_sup K F ({x} : Set L),
    mem_restrictScalars] at hy
  set pb := IntermediateField.adjoin.powerBasis hx_int with hpb
  obtain ⟨f, hfdeg, hf⟩ := pb.exists_eq_aeval ⟨y, hy⟩
  have hdim : pb.dim ≤ 2 := by
    rw [hpb, IntermediateField.adjoin.powerBasis_dim]
    exact minpoly_natDegree_le_two_of_sq_mem hx2
  have hfle : f.natDegree ≤ 1 := by
    have := hfdeg.trans_le hdim
    omega
  rw [hpb, Polynomial.eq_X_add_C_of_natDegree_le_one hfle,
    IntermediateField.adjoin.powerBasis_gen] at hf
  refine ⟨algebraMap F L (f.coeff 0), algebraMap F L (f.coeff 1),
    (f.coeff 0).2, (f.coeff 1).2, ?_⟩
  have hfeq := congrArg (Subtype.val (p := (· ∈ adjoin F {x}))) hf
  rw [AdjoinSimple.coe_aeval_gen_apply] at hfeq
  simp only [Polynomial.aeval_add, Polynomial.aeval_mul, Polynomial.aeval_C,
    Polynomial.aeval_X] at hfeq
  linear_combination hfeq

/-- Membership in `F ⊔ K⟮x⟯`, for `x² ∈ F`, is equivalent to having the form `a + b * x`
with `a, b ∈ F`. -/
@[simp]
theorem mem_sup_adjoin_sq {F : IntermediateField K L} {x : L}
    (hx2 : x ^ 2 ∈ F) {y : L} :
    y ∈ F ⊔ IntermediateField.adjoin K {x} ↔
      ∃ a b : L, a ∈ F ∧ b ∈ F ∧ y = a + b * x :=
  ⟨exists_add_mul_of_mem_sup_adjoin_sq hx2, mem_sup_adjoin_of_exists_add_mul⟩

/-- If `x² ∈ F` but `x ∉ F`, then the simple extension `F⟮x⟯` has finrank two over `F`. -/
theorem _root_.IntermediateField.finrank_adjoin_simple_eq_two_of_sq_mem_notMem
    (F : IntermediateField K L) {x : L}
    (hx2 : x ^ 2 ∈ F) (hxF : x ∉ F) :
    Module.finrank F (IntermediateField.adjoin F {x}) = 2 := by
  have hx_int : IsIntegral F x := isIntegral_of_sq_mem hx2
  rw [IntermediateField.adjoin.finrank hx_int]
  refine (minpoly_natDegree_le_two_of_sq_mem hx2).antisymm ?_
  apply (minpoly.two_le_natDegree_iff hx_int).mpr
  rintro ⟨y, hy⟩
  exact hxF (hy ▸ y.2)

/-- If `x² ∈ F` but `x ∉ F`, then adjoining `x` doubles the degree:
`[F ⊔ K⟮x⟯ : K] = 2 · [F : K]`. -/
theorem _root_.IntermediateField.finrank_sup_adjoin_simple_eq_mul_two
    (F : IntermediateField K L) {x : L}
    (hx2 : x ^ 2 ∈ F) (hxF : x ∉ F) :
    Module.finrank K ((F ⊔ IntermediateField.adjoin K {x}) : IntermediateField K L)
      = Module.finrank K F * 2 := by
  have hL : (IntermediateField.adjoin F {x}).restrictScalars K
      = F ⊔ IntermediateField.adjoin K {x} :=
    IntermediateField.restrictScalars_adjoin_eq_sup K F ({x} : Set L)
  have hfinL : Module.finrank F (IntermediateField.adjoin F {x}) = 2 :=
    F.finrank_adjoin_simple_eq_two_of_sq_mem_notMem hx2 hxF
  -- `restrictScalars` keeps the same carrier and inherited `K`-module structure, so its
  -- `K`-finrank is definitionally unchanged. Mathlib's `Submodule.restrictScalarsEquiv` proves
  -- the analogue for submodules, but only as an `F`-linear equivalence; restricting that
  -- equivalence to `K` needs tower instances unavailable for `Submodule.restrictScalars K`.
  calc Module.finrank K ((F ⊔ IntermediateField.adjoin K {x}) : IntermediateField K L)
      = Module.finrank K ((IntermediateField.adjoin F {x}).restrictScalars K) := by rw [hL]
    _ = Module.finrank K (IntermediateField.adjoin F {x}) := rfl
    _ = Module.finrank K F * Module.finrank F (IntermediateField.adjoin F {x}) := by
        rw [Module.finrank_mul_finrank]
    _ = Module.finrank K F * 2 := by rw [hfinL]

/-- **Same square class from a shared simple quadratic field.** Let `x` and `y` be square roots of
`a` and `c` in a field extension `L / K` with `2 ≠ 0`. If `x ∉ K` and the simple extensions `K(x)`
and `K(y)` coincide, then `a · c` is a square in `K`: two square roots generate the same quadratic
subfield only when their radicands lie in the same square class. -/
theorem isSquare_mul_of_adjoin_simple_eq [NeZero (2 : K)] {a c : K} {x y : L}
    (hx : x ^ 2 = algebraMap K L a) (hy : y ^ 2 = algebraMap K L c)
    (hxb : x ∉ (⊥ : IntermediateField K L))
    (hxy : IntermediateField.adjoin K {x} = IntermediateField.adjoin K {y}) :
    IsSquare (a * c) := by
  have : NeZero (2 : L) :=
    NeZero.nat_of_injective (n := 2) (f := algebraMap K L) (algebraMap K L).injective
  -- Write `y` in the base-field normal form `algebraMap p₀ + algebraMap q₀ * x`.
  have hx2 : x ^ 2 ∈ (⊥ : IntermediateField K L) := by
    rw [hx]; exact IntermediateField.algebraMap_mem _ _
  have hy_mem : y ∈ (⊥ : IntermediateField K L) ⊔ IntermediateField.adjoin K {x} := by
    rw [bot_sup_eq, hxy]; exact IntermediateField.mem_adjoin_simple_self K y
  obtain ⟨p, q, hp, hq, hy_eq⟩ := (mem_sup_adjoin_sq hx2).mp hy_mem
  rw [IntermediateField.mem_bot] at hp hq
  obtain ⟨p₀, rfl⟩ := hp
  obtain ⟨q₀, rfl⟩ := hq
  -- The square `y² = c` lands in `⊥`, so the shared cross-term lemma forces `p₀ * q₀ = 0`.
  have hab_mem :
      (algebraMap K L p₀ + algebraMap K L q₀ * x) ^ 2 ∈ (⊥ : IntermediateField K L) := by
    rw [← hy_eq, hy]; exact IntermediateField.algebraMap_mem _ _
  have hpq : algebraMap K L p₀ * algebraMap K L q₀ = 0 :=
    mul_eq_zero_of_add_mul_sq_mem hx2 hxb (IntermediateField.algebraMap_mem _ _)
      (IntermediateField.algebraMap_mem _ _) hab_mem
  have hpq0 : p₀ * q₀ = 0 := by
    apply FaithfulSMul.algebraMap_injective K L
    rw [map_mul, map_zero]
    exact hpq
  -- The vanishing cross term forces `c = p₀² + q₀² * a`.
  have hc : c = p₀ ^ 2 + q₀ ^ 2 * a := by
    have hy2 : (algebraMap K L p₀ + algebraMap K L q₀ * x) ^ 2 = algebraMap K L c := by
      rw [← hy_eq]; exact hy
    apply FaithfulSMul.algebraMap_injective K L
    rw [map_add, map_pow, map_mul, map_pow]
    linear_combination -hy2 + (algebraMap K L q₀) ^ 2 * hx + 2 * x * hpq
  -- Either `p₀ = 0`, giving `a * c = (q₀ * a)²`, or `q₀ = 0`, forcing `x ∈ K`, a contradiction.
  rcases mul_eq_zero.mp hpq0 with hp0 | hq0
  · -- `p₀ = 0`, so `c = q₀² * a` and `a * c = (q₀ * a)²`.
    exact ⟨q₀ * a, by rw [hc, hp0]; ring⟩
  · -- `q₀ = 0` puts `y` in the base field, forcing `x ∈ K`, a contradiction.
    refine absurd ?_ hxb
    have hyb : y ∈ (⊥ : IntermediateField K L) := by
      rw [hy_eq, hq0, map_zero, zero_mul, add_zero]
      exact IntermediateField.algebraMap_mem _ _
    exact IntermediateField.adjoin_simple_eq_bot_iff.mp
      (hxy.trans (IntermediateField.adjoin_simple_eq_bot_iff.mpr hyb))

/-- An element outside the base field generates a quadratic intermediate field and has degree
two. -/
private theorem adjoin_simple_eq_of_finrank_eq_two {E : IntermediateField K L} {y : L}
    (hE : Module.finrank K E = 2) (hyE : y ∈ E) (hyb : y ∉ (⊥ : IntermediateField K L)) :
    IntermediateField.adjoin K {y} = E ∧ (minpoly K y).natDegree = 2 := by
  have hEfin : FiniteDimensional K E := .of_finrank_pos (by omega)
  have hyint : IsIntegral K y := (IsIntegral.of_finite K (⟨y, hyE⟩ : E)).map E.val
  have hle : IntermediateField.adjoin K {y} ≤ E := IntermediateField.adjoin_simple_le_iff.mpr hyE
  have hadj : Module.finrank K (IntermediateField.adjoin K {y}) = (minpoly K y).natDegree :=
    IntermediateField.adjoin.finrank hyint
  have hdeg : (minpoly K y).natDegree = 2 := by
    have hge2 : 2 ≤ (minpoly K y).natDegree :=
      (minpoly.two_le_natDegree_iff hyint).mpr fun ⟨z, hz⟩ =>
        hyb (IntermediateField.mem_bot.mpr ⟨z, hz⟩)
    have hle2 : Module.finrank K (IntermediateField.adjoin K {y}) ≤ 2 :=
      hE ▸ IntermediateField.finrank_le_of_le_right hle
    omega
  exact ⟨IntermediateField.eq_of_le_of_finrank_eq hle (by rw [hadj, hdeg, hE]), hdeg⟩

/-- **A quadratic intermediate field is generated by a square root.** If `2 ≠ 0` in `K` and the
intermediate field `E` of `L / K` has degree `2` over `K`, then `E = K⟮x⟯` for an `x` whose square
lies in `K` and which does not itself lie in `K`.

Completing the square is what needs `2` invertible: a generator `y` of `E` satisfies a monic
quadratic `y² + b y + c = 0` over `K`, and `x = 2y + b` then has `x² = b² - 4c ∈ K`. -/
theorem exists_sq_mem_range_adjoin_simple_eq_of_finrank_eq_two [NeZero (2 : K)]
    {E : IntermediateField K L} (hE : Module.finrank K E = 2) :
    ∃ x : L, x ∈ E ∧ x ∉ (⊥ : IntermediateField K L) ∧
      (∃ a : K, x ^ 2 = algebraMap K L a) ∧ IntermediateField.adjoin K {x} = E := by
  have : NeZero (2 : L) :=
    NeZero.nat_of_injective (n := 2) (f := algebraMap K L) (algebraMap K L).injective
  -- `E ≠ ⊥`, so it has an element `y` outside the base field.
  have hEbot : (⊥ : IntermediateField K L) < E := by
    refine bot_le.lt_of_ne fun h => ?_
    rw [← h, IntermediateField.finrank_bot] at hE
    omega
  obtain ⟨y, hyE, hyb⟩ := IsConcreteLE.exists_of_lt hEbot
  obtain ⟨hEeq, hdeg⟩ := adjoin_simple_eq_of_finrank_eq_two hE hyE hyb
  have hEfin : FiniteDimensional K E := .of_finrank_pos (by omega)
  have hyint : IsIntegral K y := (IsIntegral.of_finite K (⟨y, hyE⟩ : E)).map E.val
  obtain ⟨b, c, hrel⟩ := hyint.exists_quadratic_relation hdeg
  -- The discriminant identity gives `(2y + b)² = b² - 4c` in the base field.
  set x : L := 2 * y + algebraMap K L b with hx
  have hyx : y = (x - algebraMap K L b) / 2 := by
    rw [eq_div_iff (NeZero.ne (2 : L)), hx]
    ring
  refine ⟨x, add_mem (mul_mem (E.natCast_mem 2) hyE) (E.algebraMap_mem _), ?_,
    ⟨b ^ 2 - 4 * c, ?_⟩, ?_⟩
  · refine fun hmem => hyb ?_
    rw [hyx]
    exact div_mem (sub_mem hmem (IntermediateField.algebraMap_mem _ _))
      (IntermediateField.natCast_mem _ 2)
  · have hdisc := discrim_eq_sq_of_quadratic_eq_zero
      (a := (1 : L)) (b := algebraMap K L b) (c := algebraMap K L c) (x := y) (by
        simpa [sq] using hrel)
    rw [hx]
    symm
    simpa only [discrim, one_mul, mul_one, map_sub, map_pow, map_mul, map_ofNat] using hdisc
  · -- Shifting by a constant does not change the generated field.
    rw [← hEeq]
    refine le_antisymm (IntermediateField.adjoin_simple_le_iff.mpr ?_)
      (IntermediateField.adjoin_simple_le_iff.mpr ?_)
    · rw [hx]
      exact add_mem
        (mul_mem (IntermediateField.natCast_mem _ 2) (IntermediateField.mem_adjoin_simple_self K y))
        (IntermediateField.algebraMap_mem _ _)
    · rw [hyx]
      exact div_mem
        (sub_mem (IntermediateField.mem_adjoin_simple_self K x)
          (IntermediateField.algebraMap_mem _ _))
        (IntermediateField.natCast_mem _ 2)

end TauCeti.IntermediateField
