/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Quiver.Acyclic.Basic
public import TauCeti.RepresentationTheory.Quiver.Representation.DimensionVector
public import TauCeti.RepresentationTheory.Quiver.Representation.Subrepresentation
public import Mathlib.Algebra.Category.ModuleCat.Simple

/-!
# The vertex simple representations of a quiver

For a vertex `i` of a quiver `Q`, the *vertex simple* representation `Sᵢ` is the base field `k` at
`i` and the zero module at every other vertex, every arrow acting by zero. This file constructs
`Sᵢ`, proves that it is a simple object of the category of representations, and proves that over an
acyclic quiver these are *all* the simple objects.

The construction is a `CategoryTheory.Paths.lift` of the prefunctor sending `i` to `k`, every other
vertex to the zero module, and every arrow to the zero map; functoriality along path concatenation
is then supplied by Mathlib. Simplicity is checked pointwise: a monomorphism into `Sᵢ` is zero away
from `i` because the target vanishes there, so it is determined by its component at `i`, where `k`
is a simple `k`-module.

The converse classification runs through the subrepresentations of
`TauCeti.RepresentationTheory.Quiver.Representation.Subrepresentation`. A nonzero vector `x` of `Mᵢ`
spans two of them: the subrepresentation it generates, and the one generated by the images of `x`
along the paths of positive length. Over an acyclic quiver the second vanishes at `i` while the
first contains `x`, so simplicity makes the second zero and the first everything; `M` is then the
line through `x` at `i` and zero elsewhere, which is `Sᵢ`.

## Main definitions

* `TauCeti.simpleRep k Q i`: the vertex simple representation `Sᵢ`.
* `TauCeti.simpleRepSelfEquiv`: the identification `(Sᵢ)ᵢ ≃ₗ[k] k`, and
  `TauCeti.simpleRepGenerator`: the element of `(Sᵢ)ᵢ` it sends to `1`.
* `TauCeti.simpleRepHom`: the morphism `Sᵢ ⟶ M` sending the generator to a chosen vector `x` of
  `Mᵢ`, available whenever every path out of `i` of positive length kills `x`.

## Main results

* `TauCeti.simpleRep_simple`: `Sᵢ` is a simple object of `TauCeti.QuiverRep k Q`.
* `TauCeti.isIso_simpleRepHom`: a representation spanned at `i` by a single nonzero vector and
  vanishing at every other vertex is `Sᵢ`.
* `TauCeti.exists_iso_simpleRep_of_simple`: over an acyclic quiver every simple representation is
  isomorphic to some `Sᵢ`.
* `TauCeti.exists_eq_smul_simpleRepGenerator`: `(Sᵢ)ᵢ` is the line spanned by the generator.
* `TauCeti.hom_simpleRep_eq_zero_iff` and `TauCeti.simpleRep_hom_eq_zero_iff`: a morphism into or
  out of `Sᵢ` is detected by its component at `i`.
* `TauCeti.dimVector_simpleRep`: the dimension vector of `Sᵢ` is `Pi.single i 1`.
* `TauCeti.not_nonempty_simpleRep_iso`: vertex simples at distinct vertices are not isomorphic.

## Implementation notes

`simpleRep` branches on equality of vertices. It is noncomputable in any case, so that branch is
decided classically and no `DecidableEq Q` instance appears in the interface; `simpleRep_obj_self`
and `simpleRep_obj_of_ne` describe the two cases without mentioning the branch. Only
`dimVector_simpleRep` assumes `DecidableEq Q`, because `Pi.single` needs one to be stated.

The objects of `CategoryTheory.Paths Q` are the vertices of `Q`, so the statements below use a
vertex directly as an object of the path category. The classification is the exception: `rw` and
`simp` build their motives at a transparency at which `M.obj i` for a vertex `i : Q` is not
type-correct, so `simpleRepHom` and everything downstream of it spell the base vertex as
`(CategoryTheory.Paths.of Q).obj i`, and pin the implicit vertex of the spanning
subrepresentations to match.

The roadmap pins the simplicity result as `simpleRep_simple`, so the instance carries that name
rather than the `simple_simpleRep` a Mathlib predicate prefix would give it.

## References

This implements the vertex simples of Layer 1 of
`TauCetiRoadmap/RepresentationTheory/QuiverRepresentations/README.md`.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits
open scoped ZeroObject

universe u v

variable (k : Type u) (Q : Type v) [Field k] [Quiver Q]

open scoped Classical in
/-- The **vertex simple** representation `Sᵢ` of a quiver: the base field `k` at the vertex `i`,
the zero module at every other vertex, and the zero map along every arrow. -/
noncomputable def simpleRep (i : Q) : QuiverRep k Q :=
  Paths.lift { obj := fun a ↦ if a = i then ModuleCat.of k k else 0, map := fun _ ↦ 0 }

variable {k Q}

/-- At `i`, the vertex simple `Sᵢ` is the base field `k`. -/
@[simp]
theorem simpleRep_obj_self (i : Q) : (simpleRep k Q i).obj i = ModuleCat.of k k :=
  ite_eq_left rfl

/-- Away from `i`, the vertex simple `Sᵢ` is the zero module. -/
@[simp]
theorem simpleRep_obj_of_ne {i a : Q} (h : a ≠ i) : (simpleRep k Q i).obj a = 0 :=
  ite_eq_right h

/-- Away from `i`, the vertex simple `Sᵢ` vanishes. -/
theorem isZero_simpleRep_obj {i a : Q} (h : a ≠ i) : IsZero ((simpleRep k Q i).obj a) := by
  rw [simpleRep_obj_of_ne h]
  exact isZero_zero _

/-- At `i`, the vertex simple `Sᵢ` is the simple `k`-module `k`. -/
instance simple_simpleRep_obj_self (i : Q) : Simple ((simpleRep k Q i).obj i) := by
  rw [simpleRep_obj_self]
  infer_instance

instance finiteDimensional_simpleRep_obj (i a : Q) :
    FiniteDimensional k ((simpleRep k Q i).obj a) := by
  rcases eq_or_ne a i with rfl | ha
  · rw [simpleRep_obj_self]
    exact inferInstanceAs (FiniteDimensional k k)
  · rw [simpleRep_obj_of_ne ha]
    have : Subsingleton ((0 : ModuleCat k) : Type u) :=
      ModuleCat.subsingleton_of_isZero (isZero_zero _)
    infer_instance

/-! ### The vertex simple is a line at its vertex -/

variable (k)

/-- The vector space that the vertex simple `Sᵢ` puts at `i` is the base field. -/
noncomputable def simpleRepSelfEquiv (i : Q) : (simpleRep k Q i).obj ((Paths.of Q).obj i) ≃ₗ[k] k :=
  (eqToIso (simpleRep_obj_self i)).toLinearEquiv

/-- The canonical generator of the line `(Sᵢ)ᵢ`: the element corresponding to `1 : k`. -/
noncomputable def simpleRepGenerator (i : Q) : (simpleRep k Q i).obj ((Paths.of Q).obj i) :=
  (simpleRepSelfEquiv k i).symm 1

/-- The generator of `(Sᵢ)ᵢ` corresponds to `1 : k`. -/
@[simp]
theorem simpleRepSelfEquiv_apply_generator (i : Q) :
    simpleRepSelfEquiv k i (simpleRepGenerator k i) = 1 :=
  (simpleRepSelfEquiv k i).apply_symm_apply 1

/-- **The vertex simple is a line at its vertex**: every element of `(Sᵢ)ᵢ` is a multiple of the
generator. -/
theorem exists_eq_smul_simpleRepGenerator {i : Q} (x : (simpleRep k Q i).obj ((Paths.of Q).obj i)) :
    ∃ c : k, x = c • simpleRepGenerator k i := by
  refine ⟨simpleRepSelfEquiv k i x, ?_⟩
  rw [simpleRepGenerator, ← LinearEquiv.map_smul, smul_eq_mul, mul_one,
    LinearEquiv.symm_apply_apply]

/-- The generator of `(Sᵢ)ᵢ` is nonzero. -/
theorem simpleRepGenerator_ne_zero (i : Q) : simpleRepGenerator k i ≠ 0 := by
  intro h
  have h1 := congrArg (simpleRepSelfEquiv k i) h
  rw [simpleRepSelfEquiv_apply_generator, map_zero] at h1
  exact one_ne_zero h1

variable {k}

/-- Every arrow of the quiver acts by zero on the vertex simple `Sᵢ`. -/
@[simp]
theorem simpleRep_map_toPath (i : Q) {a b : Q} (e : a ⟶ b) : (simpleRep k Q i).map e.toPath = 0 :=
  Paths.lift_toPath _ e

/-- More generally, every path of positive length acts by zero on the vertex simple `Sᵢ`. -/
@[simp]
theorem simpleRep_map_cons (i : Q) {a b c : Q} (p : Quiver.Path a b) (e : b ⟶ c) :
    (simpleRep k Q i).map (p.cons e) = 0 := by
  rw [simpleRep, Paths.lift_cons]
  exact Limits.comp_zero

/-- A path of positive length acts by zero on the vertex simple `Sᵢ`; only the trivial paths, which
act by the identity, survive. -/
theorem simpleRep_map_eq_zero_of_length_ne_zero (i : Q) {a b : Q} (p : Quiver.Path a b)
    (hp : p.length ≠ 0) : (simpleRep k Q i).map p = 0 := by
  cases p with
  | nil => exact absurd rfl hp
  | cons q e => exact simpleRep_map_cons i q e

/-- A morphism into the vertex simple `Sᵢ` vanishes as soon as its component at `i` does: all its
other components land in a zero module. -/
@[simp]
theorem hom_simpleRep_eq_zero_iff {i : Q} {M : QuiverRep k Q} (f : M ⟶ simpleRep k Q i) :
    f = 0 ↔ f.app i = 0 := by
  refine ⟨fun h ↦ by
    rw [h]
    exact CategoryTheory.Limits.zero_app M (simpleRep k Q i)
      ((Paths.of Q).obj i), fun h ↦ ?_⟩
  refine NatTrans.ext (funext fun a ↦ ?_)
  rcases eq_or_ne a i with rfl | ha
  · exact h
  · exact (isZero_simpleRep_obj (Q := Q) ha).eq_of_tgt _ _

/-- Dually, a morphism out of the vertex simple `Sᵢ` vanishes as soon as its component at `i` does:
all its other components start from a zero module. -/
@[simp]
theorem simpleRep_hom_eq_zero_iff {i : Q} {M : QuiverRep k Q} (f : simpleRep k Q i ⟶ M) :
    f = 0 ↔ f.app i = 0 := by
  refine ⟨fun h ↦ by
    rw [h]
    exact CategoryTheory.Limits.zero_app (simpleRep k Q i) M
      ((Paths.of Q).obj i), fun h ↦ ?_⟩
  refine NatTrans.ext (funext fun a ↦ ?_)
  rcases eq_or_ne a i with rfl | ha
  · exact h
  · exact (isZero_simpleRep_obj (Q := Q) ha).eq_of_src _ _

/-- **The vertex simples are simple.** The vertex representation `Sᵢ = simpleRep k Q i` is a simple
object of `TauCeti.QuiverRep k Q`. -/
instance simpleRep_simple (i : Q) : Simple (simpleRep k Q i) where
  mono_isIso_iff_nonzero {M} f _ := by
    constructor
    · intro _ h
      have hzi : IsZero ((simpleRep k Q i).obj i) := (IsZero.of_epi_eq_zero f h).obj i
      rw [simpleRep_obj_self] at hzi
      exact not_subsingleton k (ModuleCat.subsingleton_of_isZero hzi)
    · intro h
      rw [NatTrans.isIso_iff_isIso_app]
      intro a
      change Q at a
      change IsIso (f.app ((Paths.of Q).obj a))
      rcases eq_or_ne a i with rfl | ha
      · let : Simple ((simpleRep k Q a).obj ((Paths.of Q).obj a)) := by
          change Simple ((simpleRep k Q a).obj a)
          exact simple_simpleRep_obj_self a
        exact isIso_of_mono_of_nonzero ((hom_simpleRep_eq_zero_iff f).ne.mp h)
      · have ht : IsZero ((simpleRep k Q i).obj ((Paths.of Q).obj a)) := by
          change IsZero ((simpleRep k Q i).obj a)
          exact isZero_simpleRep_obj (Q := Q) ha
        have hs : IsZero (M.obj ((Paths.of Q).obj a)) :=
          IsZero.of_mono (f.app ((Paths.of Q).obj a)) ht
        rw [hs.eq_of_src (f.app ((Paths.of Q).obj a)) (hs.iso ht).hom]
        infer_instance

/-- The dimension vector of the vertex simple `Sᵢ` is the standard basis vector at `i`. -/
@[simp]
theorem dimVector_simpleRep [DecidableEq Q] (i : Q) :
    dimVector (simpleRep k Q i) = Pi.single i 1 := by
  funext a
  rw [dimVector_apply, Paths.of_obj, Pi.single_apply]
  rcases eq_or_ne a i with rfl | ha
  · rw [ite_eq_left rfl, simpleRep_obj_self]
    exact Module.finrank_self k
  · rw [ite_eq_right ha]
    have : Subsingleton ((simpleRep k Q i).obj a) :=
      ModuleCat.subsingleton_of_isZero (isZero_simpleRep_obj ha)
    exact Module.finrank_zero_of_subsingleton

/-! ### The vertex simples are the only simples over an acyclic quiver -/

open scoped Classical in
/-- **The morphism `Sᵢ ⟶ M` determined by a vector at `i`**, for a vector `x` that every path out
of `i` of positive length annihilates. It carries the generator of the line `(Sᵢ)ᵢ` to `x`, and is
the zero map at every other vertex. The hypothesis `hx` is exactly what naturality asks for: a path
of positive length acts by zero on `Sᵢ`, so it must kill `x` as well. -/
noncomputable def simpleRepHom {i : Q} {M : QuiverRep k Q} (x : M.obj ((Paths.of Q).obj i))
    (hx : ∀ {a : Q} (p : Quiver.Path i a), p.length ≠ 0 → M.map p x = 0) :
    simpleRep k Q i ⟶ M where
  app a :=
    if h : a = i then
      eqToHom (by subst h; exact simpleRep_obj_self _) ≫
        ModuleCat.ofHom (LinearMap.toSpanSingleton k (M.obj a) (M.map (eqToHom h.symm) x))
    else 0
  naturality {a b} p := by
    rcases eq_or_ne a i with rfl | ha
    · rcases eq_or_ne p.length 0 with hp | hp
      · -- a path of length zero is closed, hence the identity, and both sides are the component
        -- at the base vertex
        obtain rfl := Quiver.Path.eq_of_length_zero p hp
        have hp' : p = 𝟙 _ := Quiver.Path.eq_nil_of_length_zero p hp
        rw [hp']
        simp
      · -- the base vertex is now a `Paths Q` object, so `(Q := Q)` is needed to keep instance
        -- search from picking up the quiver of the path category
        have hz : (simpleRep k Q a).map p = 0 :=
          simpleRep_map_eq_zero_of_length_ne_zero (Q := Q) a p hp
        rw [hz, Limits.zero_comp]
        ext c
        -- the component at the base vertex lands in the line through `x`, which `p` annihilates
        simp only [ModuleCat.hom_zero, LinearMap.zero_apply, ↓reduceDIte, eqToHom_refl,
          CategoryTheory.Functor.map_id, ModuleCat.hom_id, LinearMap.id_coe, Category.assoc,
          ModuleCat.hom_comp, ConcreteCategory.hom_ofHom, LinearMap.coe_comp, Function.comp_apply,
          LinearMap.toSpanSingleton_apply, map_smul]
        exact (smul_eq_zero_of_right _ (hx p hp)).symm
    · exact (isZero_simpleRep_obj ha).eq_of_src _ _

/-- Away from `i`, the morphism `Sᵢ ⟶ M` attached to `x : Mᵢ` vanishes. -/
@[simp]
theorem simpleRepHom_app_of_ne {i : Q} {M : QuiverRep k Q} (x : M.obj ((Paths.of Q).obj i))
    (hx : ∀ {a : Q} (p : Quiver.Path i a), p.length ≠ 0 → M.map p x = 0) {a : Q} (ha : a ≠ i) :
    (simpleRepHom x hx).app a = 0 :=
  dite_eq_right ha

/-- The morphism `Sᵢ ⟶ M` attached to `x : Mᵢ` carries the generator of `(Sᵢ)ᵢ` to `x`. -/
@[simp]
theorem simpleRepHom_app_generator {i : Q} {M : QuiverRep k Q} (x : M.obj ((Paths.of Q).obj i))
    (hx : ∀ {a : Q} (p : Quiver.Path i a), p.length ≠ 0 → M.map p x = 0) :
    (simpleRepHom x hx).app ((Paths.of Q).obj i) (simpleRepGenerator k i) = x := by
  have happ : (simpleRepHom x hx).app ((Paths.of Q).obj i)
      = eqToHom (simpleRep_obj_self i) ≫
        ModuleCat.ofHom (LinearMap.toSpanSingleton k (M.obj ((Paths.of Q).obj i))
          (M.map (𝟙 ((Paths.of Q).obj i)) x)) := dite_eq_left rfl
  rw [happ, M.map_id]
  -- `eqToHom` composed with `ModuleCat.ofHom` is not a rewrite target: `eqToHom` transports along
  -- `simpleRep_obj_self i`, which is what `simpleRepSelfEquiv` is defined from, so the two sides
  -- differ only by the definitional unfolding of that equivalence and of `ModuleCat` composition.
  change LinearMap.toSpanSingleton k (M.obj ((Paths.of Q).obj i)) x
      (simpleRepSelfEquiv k i (simpleRepGenerator k i)) = x
  rw [simpleRepSelfEquiv_apply_generator]
  exact LinearMap.toSpanSingleton_apply_one k _ x

/-- **A representation carried by a single vector at `i` is `Sᵢ`**: the morphism `Sᵢ ⟶ M` attached
to a nonzero vector `x` spanning `Mᵢ` is an isomorphism, as soon as `M` vanishes at every other
vertex. -/
theorem isIso_simpleRepHom {i : Q} {M : QuiverRep k Q} (x : M.obj ((Paths.of Q).obj i))
    (hx : ∀ {a : Q} (p : Quiver.Path i a), p.length ≠ 0 → M.map p x = 0) (hx0 : x ≠ 0)
    (hspan : Submodule.span k ({x} : Set (M.obj ((Paths.of Q).obj i))) = ⊤)
    (hM : ∀ a : Q, a ≠ i → IsZero (M.obj a)) : IsIso (simpleRepHom x hx) := by
  -- at `i` the morphism attached to `x` is `(Sᵢ)ᵢ ≃ k` followed by `c ↦ c • x`
  have hcoe : ∀ y, (simpleRepHom x hx).app ((Paths.of Q).obj i) y
      = LinearMap.toSpanSingleton k (M.obj ((Paths.of Q).obj i)) x (simpleRepSelfEquiv k i y) := by
    intro y
    obtain ⟨c, rfl⟩ := exists_eq_smul_simpleRepGenerator k y
    simp [LinearMap.toSpanSingleton_apply]
  have hisoi : IsIso ((simpleRepHom x hx).app ((Paths.of Q).obj i)) := by
    rw [ConcreteCategory.isIso_iff_bijective]
    constructor
    · intro y z hyz
      refine (simpleRepSelfEquiv k i).injective
        (LinearMap.ker_eq_bot.1 (LinearMap.ker_toSpanSingleton k hx0) ?_)
      rw [← hcoe, ← hcoe]
      exact hyz
    · intro y
      obtain ⟨c, hc⟩ :=
        LinearMap.range_eq_top.1 ((LinearMap.range_toSpanSingleton x).trans hspan) y
      exact ⟨(simpleRepSelfEquiv k i).symm c, by rw [hcoe, LinearEquiv.apply_symm_apply]; exact hc⟩
  rw [NatTrans.isIso_iff_isIso_app]
  intro a
  change Q at a
  change IsIso ((simpleRepHom x hx).app ((Paths.of Q).obj a))
  rcases eq_or_ne a i with rfl | ha
  · exact hisoi
  · -- away from `i` both vertex spaces vanish, so every map between them is invertible
    have hs : IsZero ((simpleRep k Q i).obj ((Paths.of Q).obj a)) := isZero_simpleRep_obj ha
    have ht : IsZero (M.obj ((Paths.of Q).obj a)) := hM a ha
    rw [hs.eq_of_src ((simpleRepHom x hx).app ((Paths.of Q).obj a)) (hs.iso ht).hom]
    infer_instance

/-- **The vertex simples exhaust the simples.** Over an acyclic quiver every simple representation
is isomorphic to a vertex simple `Sᵢ`.

The proof compares two subrepresentations attached to a nonzero vector `x` of `Mᵢ`: the one it
generates, and the one generated by its images under the paths of positive length. Simplicity forces
each to be everything or nothing; over an acyclic quiver the second vanishes at `i` while the first
contains `x`, so the second is nothing and the first everything. Away from `i` the two agree, so `M`
vanishes there, and at `i` it is the line through `x`. -/
theorem exists_iso_simpleRep_of_simple (hQ : Quiver.IsAcyclic Q) (M : QuiverRep k Q) [Simple M] :
    ∃ i : Q, Nonempty (M ≅ simpleRep k Q i) := by
  obtain ⟨i, hi⟩ : ∃ i : Q, ¬IsZero (M.obj i) := by
    by_contra h
    exact Simple.not_isZero M (Functor.isZero _ fun a ↦ not_not.1 fun ha ↦ h ⟨a, ha⟩)
  obtain ⟨x, hx⟩ : ∃ x : M.obj ((Paths.of Q).obj i), x ≠ 0 := by
    have : Nontrivial (M.obj ((Paths.of Q).obj i)) := by
      rw [← not_subsingleton_iff_nontrivial]
      exact fun hs ↦ hi (ModuleCat.isZero_iff_subsingleton.2 hs)
    exact exists_ne 0
  -- acyclicity is used only through the closed paths at `i`
  have hnil : ∀ p : Quiver.Path i i, p = Quiver.Path.nil := fun p ↦ hQ.eq_nil p
  -- in particular no closed path of positive length survives to act on `x`
  have hxi : ∀ p : Quiver.Path i i, p.length ≠ 0 → M.map p x = 0 := fun p hp ↦
    absurd (hnil p) fun h ↦ hp (by rw [h, Quiver.Path.length_nil])
  -- and the trivial closed path leaves `x` on the line it spans
  have hxs : ∀ p : Quiver.Path i i,
      M.map p x ∈ Submodule.span k ({x} : Set (M.obj ((Paths.of Q).obj i))) := fun p ↦ by
    -- `QuiverRep.map_nil_apply` is used as a term: `rw` cannot see through `(Paths.of Q).obj i`
    have hval : M.map p x = x := by
      rw [hnil p]
      exact QuiverRep.map_nil_apply M i x
    rw [hval]
    exact Submodule.mem_span_singleton_self x
  -- the paths of positive length out of `i` span nothing at all
  have h1 : ∀ a : Q, (QuiverSubrep.pathSpan (i := i) x 1).toSubmodule a = ⊥ := by
    rcases (QuiverSubrep.pathSpan (i := i) x 1).eq_bot_or_eq_top with h | h
    · intro a
      rw [h, QuiverSubrep.toSubmodule_bot]
    · refine absurd ?_ hx
      have hmem : x ∈ (QuiverSubrep.pathSpan (i := i) x 1).toSubmodule i := by
        rw [h, QuiverSubrep.toSubmodule_top]
        trivial
      rw [QuiverSubrep.pathSpan_one_self_of_forall_map_eq_zero (i := i) x hxi] at hmem
      exact (Submodule.mem_bot k).1 hmem
  -- so the vector `x` generates all of `M`
  have h0 : ∀ a : Q, (QuiverSubrep.pathSpan (i := i) x 0).toSubmodule a = ⊤ := by
    rcases (QuiverSubrep.pathSpan (i := i) x 0).eq_bot_or_eq_top with h | h
    · refine absurd ?_ hx
      have hmem := QuiverSubrep.mem_pathSpan_zero (i := i) x
      rw [h, QuiverSubrep.toSubmodule_bot] at hmem
      exact (Submodule.mem_bot k).1 hmem
    · intro a
      rw [h, QuiverSubrep.toSubmodule_top]
  -- away from `i` the two spans agree, so `M` vanishes there
  have hM : ∀ a : Q, a ≠ i → IsZero (M.obj a) := by
    intro a ha
    refine ModuleCat.isZero_iff_subsingleton.2 (subsingleton_of_forall_eq 0 fun y ↦ ?_)
    have hy : y ∈ (QuiverSubrep.pathSpan (i := i) x 0).toSubmodule a := by
      rw [h0 a]
      trivial
    rw [QuiverSubrep.pathSpan_zero_eq_pathSpan_one_of_ne (i := i) x ha, h1 a] at hy
    exact (Submodule.mem_bot k).1 hy
  -- and at `i` it is the line through `x`
  have hspan0 := h0 i
  rw [QuiverSubrep.pathSpan_zero_self_of_forall_map_mem_span (i := i) x hxs] at hspan0
  have hspan : Submodule.span k ({x} : Set (M.obj ((Paths.of Q).obj i))) = ⊤ := hspan0
  -- so every path of positive length out of `i` kills `x`: a closed one is trivial, and any other
  -- lands where `M` vanishes
  have hxp : ∀ {a : Q} (p : Quiver.Path i a), p.length ≠ 0 → M.map p x = 0 := by
    intro a p hp
    rcases eq_or_ne a i with rfl | ha
    · exact hxi p hp
    · have : Subsingleton (M.obj a) := ModuleCat.subsingleton_of_isZero (hM a ha)
      exact Subsingleton.elim _ _
  refine ⟨i, ⟨?_⟩⟩
  have := isIso_simpleRepHom x hxp hx hspan hM
  exact (asIso (simpleRepHom x hxp)).symm

/-- Vertex simples at distinct vertices are not isomorphic: their dimension vectors differ. -/
theorem not_nonempty_simpleRep_iso {i j : Q} (h : i ≠ j) :
    ¬ Nonempty (simpleRep k Q i ≅ simpleRep k Q j) := by
  classical
  rintro ⟨e⟩
  have hd := dimVector_eq_of_iso e
  rw [dimVector_simpleRep, dimVector_simpleRep] at hd
  simpa [Pi.single_apply, h] using congrFun hd i

end TauCeti
