/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Group.Invertible.Defs
public import Mathlib.Algebra.Module.Defs
public import Mathlib.Algebra.Ring.Idempotent

import Mathlib.Algebra.Group.Action.Basic
import Mathlib.Algebra.Module.NatInt
import Mathlib.Tactic.Abel

/-!
# The averaging idempotent of a cube root of one

Let `A` be a semiring that is a module over a semiring `R` in which `3` is invertible, and
let `υ : A` satisfy `υ ^ 3 = 1`. Then `(1 + υ + υ²) / 3` is idempotent: it is the averaging
idempotent of the cyclic group generated by `υ`. This is the order-three counterpart of
`TauCeti.isIdempotentElem_halfOneAdd`, which shows that `(1 + ω) / 2` is idempotent when
`ω * ω = 1`.

## Main results

* `TauCeti.isIdempotentElem_invOf_three_smul_one_add_add_sq`: `(1 + υ + υ²) / 3` is idempotent
  when `υ ^ 3 = 1`.
-/

public section

namespace TauCeti

variable (R : Type*) {A : Type*} [Semiring R] [Semiring A] [Module R A] {υ : A}

/-- **`(1 + υ + υ²) / 3` is idempotent** when `υ ^ 3 = 1` and `3` is invertible: it is the
averaging idempotent of the cyclic group generated by `υ`, the order-three counterpart of
`TauCeti.isIdempotentElem_halfOneAdd`. -/
theorem isIdempotentElem_invOf_three_smul_one_add_add_sq [Invertible (3 : R)] (hυ : υ ^ 3 = 1) :
    IsIdempotentElem ((⅟3 : R) • (1 + υ + υ ^ 2)) := by
  -- `N = 1 + υ + υ²` is fixed by right multiplication by `υ`, so `N * N = N + N υ + N υ² = 3 N`
  have hυN : (1 + υ + υ ^ 2) * υ = 1 + υ + υ ^ 2 := by
    rw [add_mul, add_mul, one_mul, ← sq, ← pow_succ, hυ]
    abel
  set N := 1 + υ + υ ^ 2
  have hN : N * N = 3 • N := by
    rw [mul_add, mul_add, mul_one, sq υ, ← mul_assoc, hυN, hυN]
    abel
  -- `e = ⅟3 • N` satisfies `3 • e = N`, so `9 • (e * e) = N * N = 3 • N = 9 • e`; cancel `9`
  have h3 (x : A) : (⅟3 : R) • 3 • x = x := by rw [← ofNat_smul_eq_nsmul R, invOf_smul_smul]
  have h3_inj {x y : A} (h : 3 • x = 3 • y) : x = y := by rw [← h3 x, h, h3]
  set e := (⅟3 : R) • N
  have he : 3 • e = N := by rw [← ofNat_smul_eq_nsmul R, smul_invOf_smul]
  have h9 : 3 • 3 • (e * e) = 3 • 3 • e := by
    rw [← smul_mul_assoc, ← mul_smul_comm, he, hN]
  exact h3_inj (h3_inj h9)

end TauCeti
