/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.Algebra.Order.Archimedean.Class
public import Mathlib.Algebra.Order.Group.Defs
public import Mathlib.Algebra.Order.Hom.Monoid
public import Mathlib.Algebra.Order.Hom.MonoidWithZero
public import Mathlib.GroupTheory.QuotientGroup.Basic
public import Mathlib.Order.Quotient
public import TauCeti.Algebra.Order.Group.Subgroup
import Mathlib.Algebra.Group.Subgroup.Order

/-!
# Convex subgroups of linearly ordered groups

A subgroup of a group with a linear order is *convex* if it contains every element
lying between two of its members. That definition, the closure and preimage constructions
and the elementary exclusion lemmas need no more than a group with a linear order. The
results that make convex subgroups useful for valuation theory need the value-group
setting, a linearly ordered commutative group: there any two convex subgroups are
comparable, each has a largest convex subgroup avoiding a given element, and the quotient
by one carries a linear order making it an ordered group again — so convex subgroups are
exactly the kernels of the order-compatible quotients of a value group.
This file develops the basic theory following Wedhorn, *Adic Spaces* (arXiv:1910.05934v1),
§1.4 and §7.1; the convex subgroup `cΓ_v(I)` of Wedhorn Definition 7.3 is intended to be
built from `closure` in the forthcoming valuation-spectrum development of `Spv (A, I)`.

## Main definitions

* `TauCeti.ConvexSubgroup Γ` : The type of order-convex subgroups of `Γ`.
* `TauCeti.ConvexSubgroup.quotientLinearOrder` : The linear order on `Γ ⧸ H.toSubgroup`
  induced by a convex subgroup `H`.
* `TauCeti.ConvexSubgroup.quotientIsOrderedMonoid` : That order is compatible with the
  quotient group structure.
* `TauCeti.ConvexSubgroup.closure S` : The smallest convex subgroup containing a set.
* `TauCeti.ConvexSubgroup.maxAvoid hγ` : The largest convex subgroup avoiding `γ ≠ 1`.
* `TauCeti.ConvexSubgroup.comap` : The preimage of a convex subgroup under a monotone
  monoid homomorphism.

## Main results

* `TauCeti.ConvexSubgroup.le_total` : Convex subgroups are totally ordered by
  inclusion.
* `TauCeti.ConvexSubgroup.mem_closure_singleton` : The convex subgroup generated by one
  element consists of the elements whose absolute value is bounded by a power of it.
* `TauCeti.ConvexSubgroup.closure_singleton_pow` : An element and its nonzero powers generate
  the same convex subgroup.
* `TauCeti.ConvexSubgroup.mem_closure_of_nonempty_of_mul_mem_of_one_le` : For a nonempty set of
  elements `≥ 1` closed under multiplication, membership in the convex closure is boundedness
  by a single member.
* `TauCeti.ConvexSubgroup.lt_closure_singleton` : An element outside a convex subgroup
  generates a strictly larger one.
* `TauCeti.ConvexSubgroup.mulArchimedean_iff_forall_eq_bot_or_eq_top` : A linearly ordered
  commutative group is `MulArchimedean` exactly when its only convex subgroups are `⊥`
  and `⊤`.
* `TauCeti.ConvexSubgroup.nontrivial_quotient_maxAvoid` and
  `TauCeti.ConvexSubgroup.mulArchimedean_quotient_maxAvoid` : quotienting by the largest convex
  subgroup avoiding a convex-generating element gives a nontrivial archimedean group.
* `TauCeti.ConvexSubgroup.quotientBotOrderIso` : The quotient by `⊥` is the group itself, as an
  order isomorphism, so order-theoretic properties transfer across it.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, §1.4, §7.1

Ported from the AINTLIB development `projects/AdicSpaces/Adic spaces/OrderedGroupConvex.lean`,
adapted to the pinned Mathlib: the quotient order is obtained from Mathlib's condensation
API (`Quotient.instLinearOrder` over order-connected fibers) rather than constructed by hand.

`quotientMk_monotone` and `quotientMk_lt_one_of_notMem` come from a different AINTLIB file:
`projects/AdicSpaces/Adic spaces/ValuationCoarsening.lean` at commit `37bbdaeb`, where they are
the order facts the coarsening construction consumes.
-/

public section

namespace TauCeti

variable (Γ : Type*) [Group Γ] [LinearOrder Γ]

/-- A **convex subgroup** of a group `Γ` with a linear order is a subgroup
that is order-convex: if `a ≤ x ≤ b` and `a, b ∈ H`, then `x ∈ H`. -/
structure ConvexSubgroup extends Subgroup Γ where
  ordConnected' : carrier.OrdConnected

namespace ConvexSubgroup

variable {Γ}

instance : SetLike (ConvexSubgroup Γ) Γ where
  coe H := H.carrier
  coe_injective := by
    intro ⟨H₁, _⟩ ⟨H₂, _⟩ h
    congr 1
    exact Subgroup.ext (Set.ext_iff.mp h)

instance : SubgroupClass (ConvexSubgroup Γ) Γ where
  mul_mem {H} := H.toSubgroup.mul_mem'
  one_mem {H} := H.toSubgroup.one_mem'
  inv_mem {H} := H.toSubgroup.inv_mem'

@[ext]
theorem ext {H₁ H₂ : ConvexSubgroup Γ} (h : ∀ x, x ∈ H₁ ↔ x ∈ H₂) : H₁ = H₂ :=
  SetLike.ext h

/-- A convex subgroup is an order-connected subset. -/
theorem ordConnected (H : ConvexSubgroup Γ) : (H : Set Γ).OrdConnected :=
  H.ordConnected'

/-- Convexity: if `a, b ∈ H` and `a ≤ x ≤ b`, then `x ∈ H`. -/
theorem convex (H : ConvexSubgroup Γ) {a b x : Γ} (ha : a ∈ H) (hb : b ∈ H)
    (h₁ : a ≤ x) (h₂ : x ≤ b) : x ∈ H :=
  H.ordConnected'.out ha hb ⟨h₁, h₂⟩

/-- A convex subgroup contains every element between `1` and one of its members. -/
theorem mem_of_one_le_le {H : ConvexSubgroup Γ} {x h : Γ}
    (hh : h ∈ H) (h1 : 1 ≤ x) (hx : x ≤ h) : x ∈ H :=
  H.convex (one_mem H) hh h1 hx

/-- A convex subgroup contains every element between one of its members and `1`. -/
theorem mem_of_le_le_one {H : ConvexSubgroup Γ} {x h : Γ}
    (hh : h ∈ H) (hx : h ≤ x) (h1 : x ≤ 1) : x ∈ H :=
  H.convex hh (one_mem H) hx h1

/-- The trivial subgroup `{1}` is convex. -/
instance : Bot (ConvexSubgroup Γ) where
  bot :=
    { toSubgroup := ⊥
      ordConnected' := by
        have h : (⊥ : Subgroup Γ).carrier = ({1} : Set Γ) := by
          ext x
          simp
        rw [h]
        exact Set.ordConnected_singleton }

/-- The full group is a convex subgroup. -/
instance : Top (ConvexSubgroup Γ) where
  top :=
    { toSubgroup := ⊤
      ordConnected' := by
        have h : (⊤ : Subgroup Γ).carrier = (Set.univ : Set Γ) := by
          ext x
          simp
        rw [h]
        exact Set.ordConnected_univ }

@[simp]
theorem mem_bot {x : Γ} : x ∈ (⊥ : ConvexSubgroup Γ) ↔ x = 1 :=
  Subgroup.mem_bot

@[simp]
theorem mem_top {x : Γ} : x ∈ (⊤ : ConvexSubgroup Γ) :=
  trivial

/-- Convex subgroups are ordered by inclusion. -/
instance : PartialOrder (ConvexSubgroup Γ) :=
  PartialOrder.ofSetLike (ConvexSubgroup Γ)

instance : OrderBot (ConvexSubgroup Γ) where
  bot_le H _ hx := mem_bot.mp hx ▸ one_mem H

instance : OrderTop (ConvexSubgroup Γ) where
  le_top _ _ _ := mem_top

/-! ### The underlying subgroup

Membership, the underlying set, the order and the two lattice ends all agree with their
`Subgroup` counterparts definitionally. Naming them lets proofs move between a convex
subgroup and `H.toSubgroup` by rewriting. -/

/-- Membership in the underlying subgroup is membership in the convex subgroup. -/
@[simp]
theorem mem_toSubgroup {H : ConvexSubgroup Γ} {x : Γ} : x ∈ H.toSubgroup ↔ x ∈ H :=
  Iff.rfl

/-- The underlying subgroup has the same underlying set. -/
@[simp]
theorem coe_toSubgroup (H : ConvexSubgroup Γ) : ((H.toSubgroup : Subgroup Γ) : Set Γ) = H :=
  rfl

/-- Inclusion of convex subgroups is inclusion of the underlying subgroups. -/
@[simp]
theorem toSubgroup_le {H K : ConvexSubgroup Γ} : H.toSubgroup ≤ K.toSubgroup ↔ H ≤ K :=
  Iff.rfl

/-- Strict inclusion of convex subgroups is strict inclusion of the underlying subgroups. -/
@[simp]
theorem toSubgroup_lt {H K : ConvexSubgroup Γ} : H.toSubgroup < K.toSubgroup ↔ H < K := by
  simp [lt_iff_le_not_ge, toSubgroup_le]

/-- A convex subgroup is determined by the subgroup underlying it: convexity is a property,
not extra data. -/
theorem toSubgroup_injective : Function.Injective (toSubgroup (Γ := Γ)) := by
  intro H K h
  ext x
  rw [← mem_toSubgroup, ← mem_toSubgroup, h]

/-- Two convex subgroups are equal exactly when their underlying subgroups are. -/
@[simp]
theorem toSubgroup_inj {H K : ConvexSubgroup Γ} : H.toSubgroup = K.toSubgroup ↔ H = K :=
  toSubgroup_injective.eq_iff

/-- The underlying subgroup of the trivial convex subgroup is the trivial subgroup. -/
@[simp]
theorem bot_toSubgroup : (⊥ : ConvexSubgroup Γ).toSubgroup = ⊥ :=
  rfl

/-- The underlying subgroup of the full convex subgroup is the full subgroup. -/
@[simp]
theorem top_toSubgroup : (⊤ : ConvexSubgroup Γ).toSubgroup = ⊤ :=
  rfl

/-! ### Elements outside a convex subgroup -/

/-- If `γ ∉ H` and `γ ≤ 1`, then `γ` lies strictly below every member of `H`. -/
theorem lt_of_notMem_of_le_one (H : ConvexSubgroup Γ) {γ : Γ} (hγ : γ ∉ H) (hγ1 : γ ≤ 1)
    {h : Γ} (hh : h ∈ H) : γ < h := by
  by_contra hle
  push Not at hle
  exact hγ (H.convex hh (one_mem H) hle hγ1)

/-- If `γ ∉ H` and `1 ≤ γ`, then `γ` lies strictly above every member of `H`. -/
theorem lt_of_notMem_of_one_le (H : ConvexSubgroup Γ) {γ : Γ} (hγ : γ ∉ H) (hγ1 : 1 ≤ γ)
    {h : Γ} (hh : h ∈ H) : h < γ := by
  by_contra hle
  push Not at hle
  exact hγ (H.convex (one_mem H) hh hγ1 hle)

/-- If `γ ∉ H` and `1 ≤ γ`, then no element above `γ` lies in `H`. -/
theorem notMem_of_notMem_of_one_le_le (H : ConvexSubgroup Γ)
    {γ : Γ} (hγ : γ ∉ H) (hγ1 : 1 ≤ γ) {x : Γ} (hγx : γ ≤ x) : x ∉ H :=
  fun hx ↦ hγ (H.convex (one_mem H) hx hγ1 hγx)

/-- If `γ ∉ H` and `γ ≤ 1`, then no element below `γ` lies in `H`. -/
theorem notMem_of_notMem_of_le_le_one (H : ConvexSubgroup Γ)
    {γ : Γ} (hγ : γ ∉ H) (hγ1 : γ ≤ 1) {x : Γ} (hxγ : x ≤ γ) : x ∉ H :=
  fun hx ↦ hγ (H.convex hx (one_mem H) hxγ hγ1)

/-! ### The smallest convex subgroup containing a set -/

/-- The smallest convex subgroup containing a set `S`, as the intersection of all convex
subgroups containing `S`. The convex subgroup `cΓ_v(I)` of Wedhorn Definition 7.3 will be
an instance of this construction. -/
def closure (S : Set Γ) : ConvexSubgroup Γ where
  toSubgroup :=
    { carrier := {x | ∀ H : ConvexSubgroup Γ, S ⊆ H → x ∈ H}
      one_mem' := fun H _ ↦ one_mem H
      mul_mem' := fun ha hb H hS ↦ mul_mem (ha H hS) (hb H hS)
      inv_mem' := fun ha H hS ↦ inv_mem (ha H hS) }
  ordConnected' := ⟨fun _ ha _ hb _ hz H hS ↦ H.ordConnected'.out (ha H hS) (hb H hS) hz⟩

/-- Membership in the convex closure: membership in every convex subgroup containing the
generating set. Deliberately not a `simp` lemma — as a normal form it would rewrite every
`x ∈ closure S` into the defining intersection, exposing the construction. `closure_le` is
the universal property `simp` should use instead. -/
theorem mem_closure {S : Set Γ} {x : Γ} :
    x ∈ closure S ↔ ∀ H : ConvexSubgroup Γ, S ⊆ H → x ∈ H :=
  Iff.rfl

/-- The generating set is contained in its convex closure. -/
theorem subset_closure (S : Set Γ) : S ⊆ closure S :=
  fun _ hx _ hS ↦ hS hx

/-- Universal property: `closure S` lies inside a convex subgroup iff the generating set
does. -/
@[simp]
theorem closure_le {S : Set Γ} {H : ConvexSubgroup Γ} : closure S ≤ H ↔ S ⊆ H :=
  ⟨fun h ↦ (subset_closure S).trans h, fun hS _ hx ↦ hx H hS⟩

/-- The convex subgroup generated by a set is generated by its inverse image. -/
@[simp]
theorem closure_inv (S : Set Γ) : closure S⁻¹ = closure S := by
  refine le_antisymm (closure_le.mpr fun z hz ↦ ?_) (closure_le.mpr fun z hz ↦ ?_)
  · exact inv_inv z ▸ inv_mem (subset_closure S (Set.mem_inv.mp hz))
  · exact inv_mem_iff.mp (subset_closure S⁻¹ (Set.mem_inv.mpr (by simpa using hz)))

/-- The convex subgroup generated by an element equals the one generated by its
inverse. -/
@[simp]
theorem closure_singleton_inv (y : Γ) : closure {y⁻¹} = closure ({y} : Set Γ) := by
  rw [← closure_inv {y}]
  congr 1
  simp

/-! ### Preimages of convex subgroups -/

/-- The preimage of a convex subgroup under an ordered group homomorphism is a convex
subgroup. This lifts convex subgroups from quotient value groups back to the original
value group. -/
def comap {Δ F : Type*} [Group Δ] [LinearOrder Δ] [FunLike F Γ Δ]
    [MonoidHomClass F Γ Δ] [OrderHomClass F Γ Δ] (f : F)
    (K : ConvexSubgroup Δ) : ConvexSubgroup Γ where
  toSubgroup := K.toSubgroup.comap (MonoidHom.ofClass f)
  ordConnected' := K.ordConnected'.preimage_mono (OrderHomClass.monotone f)

@[simp]
theorem mem_comap {Δ F : Type*} [Group Δ] [LinearOrder Δ] [FunLike F Γ Δ]
    [MonoidHomClass F Γ Δ] [OrderHomClass F Γ Δ] {f : F}
    {K : ConvexSubgroup Δ} {x : Γ} :
    x ∈ comap f K ↔ f x ∈ K :=
  Iff.rfl

/-- The comap of a convex subgroup along the identification `(WithZero Γ)ˣ ≃*o Γ`.

This is what carries a convex subgroup of a *value group* over to the units of the value monoid
containing it, which is the form a restriction of a valuation consumes. -/
def comapUnitsWithZero (K : ConvexSubgroup Γ) : ConvexSubgroup ((WithZero Γ)ˣ) :=
  comap (OrderMonoidIso.unitsWithZero (α := Γ)) K

/-- Membership in the transported subgroup is membership of the corresponding value group
element: the unit `u` is carried across by `OrderMonoidIso.unitsWithZero`. -/
@[simp]
theorem mem_comapUnitsWithZero {K : ConvexSubgroup Γ} {u : (WithZero Γ)ˣ} :
    u ∈ comapUnitsWithZero K ↔ OrderMonoidIso.unitsWithZero u ∈ K :=
  mem_comap

/-! ### Total ordering of convex subgroups -/

section TotalOrder

variable {Γ : Type*} [CommGroup Γ] [LinearOrder Γ] [IsOrderedMonoid Γ]

/-- Any two convex subgroups are comparable. -/
protected theorem le_total (H₁ H₂ : ConvexSubgroup Γ) : H₁ ≤ H₂ ∨ H₂ ≤ H₁ := by
  by_contra h
  push Not at h
  obtain ⟨hne₁, hne₂⟩ := h
  obtain ⟨a, haH₁, haH₂⟩ := Set.not_subset.mp fun hsub ↦ hne₁ fun x hx ↦ hsub hx
  refine hne₂ fun b hb ↦ ?_
  have hainv : a⁻¹ ∉ H₂ := inv_mem_iff.not.mpr haH₂
  rcases le_total a 1 with ha | ha
  · have hab : a < b := H₂.lt_of_notMem_of_le_one haH₂ ha hb
    have hba : b < a⁻¹ := H₂.lt_of_notMem_of_one_le hainv (one_le_inv'.mpr ha) hb
    exact H₁.convex haH₁ (inv_mem haH₁) hab.le hba.le
  · have hba : b < a := H₂.lt_of_notMem_of_one_le haH₂ ha hb
    have hab : a⁻¹ < b := H₂.lt_of_notMem_of_le_one hainv (inv_le_one'.mpr ha) hb
    exact H₁.convex (inv_mem haH₁) haH₁ hab.le hba.le

noncomputable instance : LinearOrder (ConvexSubgroup Γ) :=
  { (inferInstance : PartialOrder (ConvexSubgroup Γ)) with
    le_total := ConvexSubgroup.le_total
    toDecidableLE := Classical.decRel _
    toDecidableEq := Classical.decEq _
    toDecidableLT := Classical.decRel _ }

/-! ### The largest convex subgroup avoiding an element -/

/-- An element bounded in absolute value by a member of a convex subgroup is a member. -/
theorem mem_of_mabs_le_mabs {H : ConvexSubgroup Γ} {x h : Γ} (hh : h ∈ H)
    (hx : |x|ₘ ≤ |h|ₘ) : x ∈ H := by
  have habs : |h|ₘ ∈ H := mabs_mem_iff.mpr hh
  exact H.convex (inv_mem habs) habs (by simpa using (mabs_le.mp hx).1) (mabs_le.mp hx).2

/-- The largest convex subgroup avoiding an element `γ ≠ 1`: Mathlib's Archimedean open ball
at the class of `γ`, that is, the elements of strictly larger Archimedean class. Reusing
`MulArchimedeanClass.ballSubgroup` rather than building the directed union of all convex
subgroups avoiding `γ` gives the same subgroup with the group structure already in place. -/
noncomputable def maxAvoid {γ : Γ} (hγ : γ ≠ 1) : ConvexSubgroup Γ where
  toSubgroup := MulArchimedeanClass.ballSubgroup (MulArchimedeanClass.mk γ)
  ordConnected' := by
    have htop : MulArchimedeanClass.mk γ ≠ ⊤ := fun h ↦ hγ (MulArchimedeanClass.mk_eq_top_iff.mp h)
    constructor
    intro a ha b hb x hx
    simp only [Subgroup.mem_carrier, MulArchimedeanClass.mem_ballSubgroup_iff htop] at ha hb ⊢
    exact lt_of_lt_of_le (lt_min ha hb)
      (MulArchimedeanClass.min_le_mk_of_le_of_le hx.1 hx.2)

/-- Membership in `maxAvoid hγ`: a strictly larger Archimedean class than `γ`. -/
@[simp]
theorem mem_maxAvoid_iff {γ : Γ} {hγ : γ ≠ 1} {x : Γ} :
    x ∈ maxAvoid hγ ↔ MulArchimedeanClass.mk γ < MulArchimedeanClass.mk x :=
  MulArchimedeanClass.mem_ballSubgroup_iff
    (fun h ↦ hγ (MulArchimedeanClass.mk_eq_top_iff.mp h))

/-- The avoided element is not a member. -/
theorem notMem_maxAvoid {γ : Γ} (hγ : γ ≠ 1) : γ ∉ maxAvoid hγ := by
  rw [mem_maxAvoid_iff (hγ := hγ)]
  exact lt_irrefl _

/-- Universal property: a convex subgroup lies inside `maxAvoid hγ` iff it excludes
`γ`. -/
@[simp]
theorem le_maxAvoid {γ : Γ} {hγ : γ ≠ 1} {H : ConvexSubgroup Γ} :
    H ≤ maxAvoid hγ ↔ γ ∉ H := by
  refine ⟨fun h hγH ↦ notMem_maxAvoid hγ (h hγH), fun h x hx ↦ ?_⟩
  rw [mem_maxAvoid_iff (hγ := hγ)]
  by_contra hle
  rw [not_lt, MulArchimedeanClass.mk_le_mk] at hle
  obtain ⟨n, hn⟩ := hle
  exact h (mem_of_mabs_le_mabs (pow_mem hx n) (hn.trans_eq (mabs_pow n x).symm))

/-! ### The convex subgroup generated by a multiplicatively closed set -/

/-- **For a nonempty, multiplicatively closed set of elements `≥ 1`, membership in the convex
closure is boundedness by a single member.**

This is what one needs whenever a convex subgroup is generated by the values a multiplicative
map attains — for instance the characteristic subgroup `cΓ_v` of a valuation, generated by the
attained values `≥ 1`, where it says that a single attained value already bounds. -/
@[simp]
theorem mem_closure_of_nonempty_of_mul_mem_of_one_le {S : Set Γ} (hne : S.Nonempty)
    (hmul : ∀ x ∈ S, ∀ y ∈ S, x * y ∈ S) (hge : ∀ x ∈ S, 1 ≤ x) {x : Γ} :
    x ∈ closure S ↔ ∃ g ∈ S, g⁻¹ ≤ x ∧ x ≤ g := by
  refine ⟨fun hx ↦ ?_, fun ⟨g, hg, hgx, hxg⟩ ↦ ?_⟩
  · -- The right-hand side is itself a convex subgroup containing `S`: multiplicative closure
    -- of `S` makes it a subgroup, and `1 ≤ g` for `g ∈ S` makes it order-convex.
    let B : ConvexSubgroup Γ :=
      { toSubgroup :=
          { carrier := {y | ∃ g ∈ S, g⁻¹ ≤ y ∧ y ≤ g}
            one_mem' := by
              obtain ⟨g, hg⟩ := hne
              exact ⟨g, hg, inv_le_one'.mpr (hge g hg), hge g hg⟩
            mul_mem' := fun {a b} ⟨g, hg, hga, hag⟩ ⟨h, hh, hhb, hbh⟩ ↦
              ⟨g * h, hmul g hg h hh, by rw [mul_inv]; exact mul_le_mul' hga hhb,
                mul_le_mul' hag hbh⟩
            inv_mem' := fun {a} ⟨g, hg, hga, hag⟩ ↦
              ⟨g, hg, by simpa using inv_le_inv' hag, by simpa using inv_le_inv' hga⟩ }
        ordConnected' := by
          constructor
          rintro p ⟨g, hg, hgp, hpg⟩ q ⟨h, hh, hhq, hqh⟩ z hz
          refine ⟨g * h, hmul g hg h hh, ?_, ?_⟩
          · refine le_trans ?_ (hgp.trans hz.1)
            rw [mul_inv]
            exact mul_le_of_le_one_right' (inv_le_one'.mpr (hge h hh))
          · exact (hz.2.trans hqh).trans (le_mul_of_one_le_left' (hge g hg)) }
    exact (closure_le (H := B)).mpr (fun g hg ↦ ⟨g, hg, (inv_le_one'.mpr (hge g hg)).trans
      (hge g hg), le_rfl⟩) hx
  · exact (closure S).convex (inv_mem (subset_closure S hg)) (subset_closure S hg) hgx hxg

/-! ### The convex subgroup generated by one element -/

/-- The closed archimedean ball of `y` as a convex subgroup: Mathlib's
`MulArchimedeanClass.closedBallSubgroup` — the elements whose absolute value is bounded
by a power of `|y|ₘ` — which is order-connected. -/
private noncomputable def archimedeanBall (y : Γ) : ConvexSubgroup Γ where
  toSubgroup := MulArchimedeanClass.closedBallSubgroup (MulArchimedeanClass.mk y)
  ordConnected' := by
    constructor
    intro a ha b hb x hx
    simp only [Subgroup.mem_carrier, MulArchimedeanClass.mem_closedBallSubgroup_iff,
      MulArchimedeanClass.mk_le_mk] at ha hb ⊢
    obtain ⟨m, hm⟩ := ha
    obtain ⟨n, hn⟩ := hb
    refine ⟨max m n, mabs_le.mpr ⟨?_, ?_⟩⟩
    · exact ((mabs_le.mp hm).1.trans hx.1).trans'
        (inv_le_inv' (pow_le_pow_right' (one_le_mabs y) (le_max_left m n)))
    · exact (hx.2.trans (mabs_le.mp hn).2).trans
        (pow_le_pow_right' (one_le_mabs y) (le_max_right m n))

/-- The underlying subgroup of `archimedeanBall y` is Mathlib's closed ball subgroup at the
archimedean class of `y`. -/
@[simp]
private theorem archimedeanBall_toSubgroup (y : Γ) :
    (archimedeanBall y).toSubgroup
      = MulArchimedeanClass.closedBallSubgroup (MulArchimedeanClass.mk y) :=
  rfl

/-- The convex subgroup generated by a single element consists of the elements whose
absolute value is bounded by a power of `|y|ₘ` — the closed archimedean ball of `y`. -/
@[simp]
theorem mem_closure_singleton {y x : Γ} :
    x ∈ closure {y} ↔ ∃ n : ℕ, |x|ₘ ≤ |y|ₘ ^ n := by
  constructor
  · intro hx
    have hb := mem_closure.mp hx (archimedeanBall y) fun z hz ↦ by
      rw [Set.mem_singleton_iff] at hz
      subst hz
      rw [SetLike.mem_coe, ← mem_toSubgroup, archimedeanBall_toSubgroup]
      exact MulArchimedeanClass.mem_closedBallSubgroup_iff.mpr le_rfl
    rw [← mem_toSubgroup, archimedeanBall_toSubgroup] at hb
    exact MulArchimedeanClass.mk_le_mk.mp
      (MulArchimedeanClass.mem_closedBallSubgroup_iff.mp hb)
  · rintro ⟨n, hn⟩
    have hy : y ∈ closure ({y} : Set Γ) := subset_closure _ rfl
    have habs : |y|ₘ ∈ closure ({y} : Set Γ) := mabs_mem_iff.mpr hy
    obtain ⟨hlo, hhi⟩ := mabs_le.mp hn
    exact (closure {y}).convex (inv_mem (pow_mem habs n)) (pow_mem habs n) hlo hhi

/-- **An element and its nonzero natural powers generate the same convex subgroup.** No
nontriviality is required — at `γ = 1` both sides are `⊥`.

Wedhorn needs this in Lemma 7.2: the largest value is attained on a finitely generated ideal
`J` with `√I = √J`, so it is only some *power* of it that is attained on `I` itself. -/
@[simp]
theorem closure_singleton_pow {γ : Γ} {n : ℕ} (hn : n ≠ 0) :
    closure {γ ^ n} = closure ({γ} : Set Γ) := by
  refine le_antisymm (closure_le.mpr ?_) (closure_le.mpr ?_)
  · intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst hx
    rw [SetLike.mem_coe, mem_closure_singleton]
    exact ⟨n, by rw [mabs_pow]⟩
  · intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst hx
    rw [SetLike.mem_coe, mem_closure_singleton]
    refine ⟨1, ?_⟩
    rw [pow_one, mabs_pow]
    exact le_self_pow (one_le_mabs x) hn

/-- An element outside a convex subgroup generates a strictly larger convex subgroup.
Wedhorn needs this in the proof of Lemma 7.2 to know `cΓ_v ⊊ H` before Lemma 7.1 may be
applied to the subgroup `H` generated by the largest value of a generating set. No side
condition on `h` is needed. -/
theorem lt_closure_singleton {C : ConvexSubgroup Γ} {h : Γ} (hC : h ∉ C) :
    C < closure {h} := by
  refine lt_of_le_of_ne (fun x hx ↦ ?_) fun hEq ↦
    hC (hEq ▸ subset_closure ({h} : Set Γ) rfl)
  rw [mem_closure_singleton]
  refine ⟨1, ?_⟩
  rw [pow_one]
  rcases le_total h 1 with h1 | h1
  · rw [mabs_eq_inv_self.mpr h1]
    refine mabs_le.mpr ⟨?_, ?_⟩
    · rw [inv_inv]
      exact (C.lt_of_notMem_of_le_one hC h1 hx).le
    · have hx' := inv_lt_inv' (C.lt_of_notMem_of_le_one hC h1 (inv_mem hx))
      rw [inv_inv] at hx'
      exact hx'.le
  · rw [mabs_eq_self.mpr h1]
    refine mabs_le.mpr ⟨?_, ?_⟩
    · have hx' := inv_lt_inv' (C.lt_of_notMem_of_one_le hC h1 (inv_mem hx))
      rw [inv_inv] at hx'
      exact hx'.le
    · exact (C.lt_of_notMem_of_one_le hC h1 hx).le

/-! ### The Archimedean characterization -/

/-- In a `MulArchimedean` group every convex subgroup is `⊥` or `⊤`. -/
theorem eq_bot_or_eq_top_of_mulArchimedean [MulArchimedean Γ] (H : ConvexSubgroup Γ) :
    H = ⊥ ∨ H = ⊤ := by
  by_contra hH
  push Not at hH
  obtain ⟨hbot, htop⟩ := hH
  obtain ⟨y, hy, -, hy1⟩ := Subgroup.exists_one_lt_of_lt
    (by simpa using toSubgroup_lt.mpr (bot_lt_iff_ne_bot.mpr hbot))
  obtain ⟨x, -, hx, hx1⟩ := Subgroup.exists_one_lt_of_lt
    (by simpa using toSubgroup_lt.mpr (lt_top_iff_ne_top.mpr htop))
  rw [mem_toSubgroup] at hy hx
  obtain ⟨n, hn⟩ := MulArchimedean.arch x hy1
  exact hx (H.convex (one_mem H) (pow_mem hy n) hx1.le hn)

/-- If every convex subgroup is `⊥` or `⊤`, the group is `MulArchimedean`. -/
theorem mulArchimedean_of_forall_eq_bot_or_eq_top
    (h : ∀ H : ConvexSubgroup Γ, H = ⊥ ∨ H = ⊤) : MulArchimedean Γ where
  arch x {y} hy := by
    by_contra hna
    push Not at hna
    have hy_mem : y ∈ closure ({y} : Set Γ) := subset_closure _ rfl
    have hx_nmem : x ∉ closure ({y} : Set Γ) := fun hx ↦ by
      obtain ⟨n, hle⟩ := mem_closure_singleton.mp hx
      rw [mabs_eq_self.mpr hy.le] at hle
      exact absurd ((le_mabs_self x).trans hle) (not_le.mpr (hna n))
    rcases h (closure {y}) with heq | heq
    · exact ne_of_gt hy (mem_bot.mp (heq ▸ hy_mem))
    · exact hx_nmem (heq ▸ mem_top)

/-- **The Archimedean characterization.** A linearly ordered commutative group is
`MulArchimedean` iff its only convex subgroups are `⊥` and `⊤`. -/
theorem mulArchimedean_iff_forall_eq_bot_or_eq_top :
    MulArchimedean Γ ↔ ∀ H : ConvexSubgroup Γ, H = ⊥ ∨ H = ⊤ :=
  ⟨fun _ ↦ eq_bot_or_eq_top_of_mulArchimedean, mulArchimedean_of_forall_eq_bot_or_eq_top⟩

/-! ### The quotient linear order -/

section Quotient

/-- The fibers of the projection to the quotient by a convex subgroup are the cosets, which
are order-connected by convexity. This is the hypothesis Mathlib's condensation API takes as
an instance (`Quotient.mk_le_mk`, `Quotient.instLinearOrder`); it is supplied explicitly at
both call sites rather than registered globally, since as an instance its head would match
every quotient of a linear order and send synthesis down a blind alley. -/
private theorem ordConnected_leftRel_fiber (H : ConvexSubgroup Γ) :
    ∀ q : Γ ⧸ H.toSubgroup,
      Set.OrdConnected (Quotient.mk (QuotientGroup.leftRel H.toSubgroup) ⁻¹' {q}) := by
  intro q
  constructor
  induction q using Quotient.inductionOn with | _ b =>
  intro x hx y hy z hz
  have hx' : x⁻¹ * b ∈ H.toSubgroup := QuotientGroup.eq.mp hx
  have hy' : y⁻¹ * b ∈ H.toSubgroup := QuotientGroup.eq.mp hy
  have hz' : z⁻¹ * b ∈ H.toSubgroup :=
    mem_toSubgroup.mpr (H.convex (mem_toSubgroup.mp hy') (mem_toSubgroup.mp hx')
      (mul_le_mul_left (inv_le_inv' hz.2) b) (mul_le_mul_left (inv_le_inv' hz.1) b))
  exact QuotientGroup.eq.mpr hz'

variable (H : ConvexSubgroup Γ)

/-- The quotient of `Γ` by a convex subgroup `H` is linearly ordered, as the condensation
of `Γ` along the order-connected cosets. The body is not exposed: consumers work through
`quotient_le_iff` rather than by unfolding the condensation. -/
@[no_expose]
noncomputable instance quotientLinearOrder : LinearOrder (Γ ⧸ H.toSubgroup) :=
  @Quotient.instLinearOrder Γ (QuotientGroup.leftRel H.toSubgroup) _
    (ordConnected_leftRel_fiber H) (fun _ _ ↦ Classical.dec _)

omit [IsOrderedMonoid Γ] in
/-- The coercion `Γ → Γ ⧸ H.toSubgroup` is `Quotient.mk` of the left-coset setoid; this
names the definitional equality so that the condensation API applies by rewriting. -/
private theorem coe_eq_mk (a : Γ) :
    (a : Γ ⧸ H.toSubgroup) = Quotient.mk (QuotientGroup.leftRel H.toSubgroup) a :=
  rfl

/-- The defining unfolding of `≤` on the quotient by a convex subgroup:
`[a] ≤ [b]` iff `b⁻¹ * a ≤ 1` or `b⁻¹ * a ∈ H`. -/
@[simp]
theorem quotient_le_iff (a b : Γ) :
    ((a : Γ ⧸ H.toSubgroup) ≤ (b : Γ ⧸ H.toSubgroup)) ↔
      (b⁻¹ * a ≤ 1 ∨ b⁻¹ * a ∈ H.toSubgroup) := by
  rw [coe_eq_mk, coe_eq_mk, Quotient.mk_le_mk (H := ordConnected_leftRel_fiber H)]
  refine or_congr ⟨fun h ↦ ?_, fun h ↦ ?_⟩ ?_
  · simpa using mul_le_mul_right h b⁻¹
  · simpa using mul_le_mul_right h b
  · constructor
    · intro h
      simpa [mul_inv_rev] using H.toSubgroup.inv_mem (QuotientGroup.leftRel_apply.mp h)
    · intro h
      exact QuotientGroup.leftRel_apply.mpr
        (by simpa [mul_inv_rev] using H.toSubgroup.inv_mem h)

/-- The quotient linear order is compatible with the group operation. -/
instance quotientIsOrderedMonoid : IsOrderedMonoid (Γ ⧸ H.toSubgroup) where
  mul_le_mul_left a b hab c := by
    induction a using Quotient.inductionOn with | _ a =>
    induction b using Quotient.inductionOn with | _ b =>
    induction c using Quotient.inductionOn with | _ c =>
    rw [← QuotientGroup.mk_mul, ← QuotientGroup.mk_mul, quotient_le_iff] at *
    have h : (b * c)⁻¹ * (a * c) = b⁻¹ * a := by
      simp [mul_inv_rev, mul_comm, mul_assoc]
    rw [h]
    exact hab

/-- The quotient map `Γ →* Γ ⧸ H.toSubgroup` is monotone. -/
-- re-exports the condensation's `Quotient.mk_monotone`: importing modules cannot unfold the
-- sealed `quotientLinearOrder`, so they must take monotonicity from here
theorem quotientMk_monotone : Monotone (QuotientGroup.mk' H.toSubgroup) := Quotient.mk_monotone

/-- An element at most `1` and outside `H` has class strictly below `1` in the quotient. -/
theorem quotientMk_lt_one_of_notMem {a : Γ} (ha : a ≤ 1) (haH : a ∉ H) :
    (QuotientGroup.mk' H.toSubgroup a : Γ ⧸ H.toSubgroup) < 1 := by
  have hle : (QuotientGroup.mk' H.toSubgroup a : Γ ⧸ H.toSubgroup) ≤ 1 := by
    simpa using H.quotientMk_monotone ha
  refine hle.lt_of_ne fun heq ↦ haH ?_
  exact (QuotientGroup.eq_one_iff a).mp (by simpa using heq)

/-! ### A height-one quotient -/

/-- The quotient by the largest convex subgroup avoiding `γ ≠ 1` is nontrivial: the class
of `γ` is different from `1`.

Together with `mulArchimedean_quotient_maxAvoid`, this is the elementary ordered-group input to
the fact that a valuation with a nonzero cofinal value is microbial. -/
theorem nontrivial_quotient_maxAvoid {γ : Γ} (hγ : γ ≠ 1) :
    Nontrivial (Γ ⧸ (maxAvoid hγ).toSubgroup) := by
  apply QuotientGroup.nontrivial_iff.mpr
  intro htop
  apply notMem_maxAvoid hγ
  rw [← mem_toSubgroup, htop]
  exact Subgroup.mem_top γ

/-- If `γ` generates the whole group as a convex subgroup, the quotient by the largest convex
subgroup avoiding `γ` is archimedean. Equivalently, it has height at most one. -/
theorem mulArchimedean_quotient_maxAvoid {γ : Γ} (hγ : γ ≠ 1)
    (hclosure : closure ({γ} : Set Γ) = ⊤) :
    MulArchimedean (Γ ⧸ (maxAvoid hγ).toSubgroup) := by
  let q : Γ →*o Γ ⧸ (maxAvoid hγ).toSubgroup :=
    OrderMonoidHom.mk (QuotientGroup.mk' (maxAvoid hγ).toSubgroup)
      (maxAvoid hγ).quotientMk_monotone
  rw [mulArchimedean_iff_forall_eq_bot_or_eq_top]
  intro K
  by_cases hK : K = ⊥
  · exact Or.inl hK
  · right
    let L : ConvexSubgroup Γ := comap q K
    have hHL : maxAvoid hγ ≤ L := by
      intro x hx
      simp only [L, mem_comap]
      have hxq : q x = 1 := (QuotientGroup.eq_one_iff x).mpr hx
      rw [hxq]
      exact one_mem K
    have hlt : maxAvoid hγ < L := by
      refine hHL.lt_of_ne fun hEq ↦ hK ?_
      apply bot_unique
      intro z hz
      obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective (maxAvoid hγ).toSubgroup z
      rw [mem_bot]
      apply (QuotientGroup.eq_one_iff x).mpr
      have hxL : x ∈ L := by
        simp only [L, mem_comap]
        exact hz
      rw [ConvexSubgroup.mem_toSubgroup, hEq]
      exact hxL
    have hγL : γ ∈ L := by
      by_contra hγL
      exact (not_le_of_gt hlt) (le_maxAvoid.mpr hγL)
    have hL : L = ⊤ := by
      apply top_unique
      rw [← hclosure, closure_le]
      simpa using hγL
    apply top_unique
    intro z _
    obtain ⟨x, rfl⟩ := QuotientGroup.mk'_surjective (maxAvoid hγ).toSubgroup z
    have hxL : x ∈ L := hL ▸ mem_top
    simp only [L, mem_comap] at hxL
    exact hxL

/-- **The quotient by `⊥` is the group itself.** `QuotientGroup.quotientBot` identifies the two
groups once `bot_toSubgroup` has rewritten which subgroup is being quotiented by.

Private implementation detail: this is only the underlying multiplicative equivalence of
`quotientBotOrderIso`, which is the reusable object. It is named at all so that the order
comparison below can be stated before that isomorphism exists. -/
private noncomputable def quotientBotMulEquiv : (Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup) ≃* Γ :=
  (QuotientGroup.quotientMulEquivOfEq (bot_toSubgroup (Γ := Γ))).trans QuotientGroup.quotientBot

omit [IsOrderedMonoid Γ] in
/-- **`quotientBotMulEquiv` sends the class of `a` to `a`.** Not `@[simp]`; see
`quotientBotOrderIso_mk` for why none of these application lemmas can be. -/
private theorem quotientBotMulEquiv_mk (a : Γ) :
    quotientBotMulEquiv ((a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup)) = a := rfl

omit [IsOrderedMonoid Γ] in
/-- **`quotientBotMulEquiv.symm` sends `a` to its class.** Not `@[simp]`; see
`quotientBotOrderIso_mk`. -/
private theorem quotientBotMulEquiv_symm_apply (a : Γ) :
    quotientBotMulEquiv.symm a = (a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup) := rfl

/-- **`quotientBotMulEquiv` is an order equivalence.** Quotienting by `⊥` leaves the order alone:
`a ≤ b` in the quotient unfolds to `b⁻¹ * a ≤ 1` or `b⁻¹ * a = 1`, and both give `a ≤ b`.

This exists to supply the `map_le_map_iff'` field of `quotientBotOrderIso`, so it is stated before
that isomorphism is available. Downstream, prefer `map_le_map_iff` on `quotientBotOrderIso`. -/
private theorem quotientBotMulEquiv_le_quotientBotMulEquiv_iff
    {a b : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup} :
    quotientBotMulEquiv a ≤ quotientBotMulEquiv b ↔ a ≤ b := by
  induction a using QuotientGroup.induction_on with | _ a =>
  induction b using QuotientGroup.induction_on with | _ b =>
  have key : b⁻¹ * a ≤ 1 ↔ a ≤ b := by
    rw [mul_comm, ← div_eq_mul_inv]; exact div_le_one'
  simp only [quotientBotMulEquiv_mk]
  rw [quotient_le_iff]
  simp only [bot_toSubgroup, Subgroup.mem_bot]
  constructor
  · intro h; exact Or.inl (key.mpr h)
  · rintro (h | h)
    · exact key.mp h
    · exact le_of_eq (inv_mul_eq_one.mp h).symm

/-- **The quotient by `⊥` is the group itself, as an ordered group.** This is the reusable object
of this section: it carries order-theoretic properties such as `Nontrivial` and `MulArchimedean`
across the identification.

Its body is sealed. Consumers work through `quotientBotOrderIso_mk` and
`quotientBotOrderIso_symm_apply` rather than by unfolding the construction, exactly as they do for
`quotientLinearOrder`. -/
noncomputable def quotientBotOrderIso : (Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup) ≃*o Γ :=
  { quotientBotMulEquiv with
    map_le_map_iff' := quotientBotMulEquiv_le_quotientBotMulEquiv_iff }

/-- The `rfl` proof of `quotientBotOrderIso_mk`, kept private because it unfolds the sealed
`quotientBotOrderIso`, which an exported theorem may not do. -/
private theorem quotientBotOrderIso_mk_aux (a : Γ) :
    quotientBotOrderIso ((a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup)) = a := rfl

/-- **`quotientBotOrderIso` sends the class of `a` to `a`.**

Deliberately not `@[simp]`, and the same holds for every application lemma in this group. Each
mentions `Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup`, and `bot_toSubgroup` is itself a `simp` lemma
rewriting `(⊥ : ConvexSubgroup Γ).toSubgroup` to `(⊥ : Subgroup Γ)`. So `simp` normalises that
subterm — in the coercion's type arguments, which come from the isomorphism's own domain, not just
in the argument — and a left-hand side spelled this way could never match afterwards. Marking these
`@[simp]` would add rules that can never fire.

The normal form is not reachable either: `quotientLinearOrder` has head
`LinearOrder (Γ ⧸ ?H.toSubgroup)`, so synthesis cannot invert the projection and
`LinearOrder (Γ ⧸ (⊥ : Subgroup Γ))` does not exist — there is no ordered quotient to state the
simp-normal form over. These therefore stay explicit rewrites, which is what lets consumers avoid
unfolding the sealed construction. -/
theorem quotientBotOrderIso_mk (a : Γ) :
    quotientBotOrderIso ((a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup)) = a :=
  quotientBotOrderIso_mk_aux a

/-- The `rfl` proof of `quotientBotOrderIso_symm_apply`, private for the same reason as
`quotientBotOrderIso_mk_aux`. -/
private theorem quotientBotOrderIso_symm_apply_aux (a : Γ) :
    quotientBotOrderIso.symm a = (a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup) := rfl

/-- **`quotientBotOrderIso.symm` sends `a` to its class.** Not `@[simp]`; see
`quotientBotOrderIso_mk`. -/
theorem quotientBotOrderIso_symm_apply (a : Γ) :
    quotientBotOrderIso.symm a = (a : Γ ⧸ (⊥ : ConvexSubgroup Γ).toSubgroup) :=
  quotientBotOrderIso_symm_apply_aux a

end Quotient

end TotalOrder

end ConvexSubgroup

end TauCeti
