/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
public import TauCeti.Algebra.AlgebraicGroup.BaseChange.CentralPoint
public import TauCeti.Algebra.AlgebraicGroup.CommHopfAlgCat.BaseChange
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.CommonKernel.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Central
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Basic
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Augmentation
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Map
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Kernel

/-!
# Base change of Hopf ideals

A closed subgroup scheme of `Spec H` is cut out by a Hopf ideal `J` of the coordinate Hopf
algebra `H`. This file base-changes that description along a ring map `k → K`: the ideal of
`K ⊗[k] H` generated by `1 ⊗ J` is again a Hopf ideal, and quotienting by it produces the base
change `K ⊗[k] (H ⧸ J)` of the original quotient. Geometrically, the closed subgroup scheme
base-changes to a closed subgroup scheme of the base-changed ambient group, and its points over a
`K`-algebra are the original points over the same algebra viewed over `k`.

The Hopf-ideal structure is obtained without checking the comultiplication condition again: the
base-changed ideal is realized as the kernel of the base change of the quotient morphism, which
is surjective, and the kernel of a surjective morphism of commutative Hopf algebras is a Hopf
ideal (`TauCeti.HopfIdeal.kerOfSurjective`). Right exactness of the tensor product
(`Algebra.TensorProduct.lTensor_ker`) then identifies that kernel with the extension of `J`
along `h ↦ 1 ⊗ h`.

## Main declarations

* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal`: the base change `J_K` of a Hopf ideal `J`.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_toIdeal`: `J_K` is generated by `1 ⊗ J`.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_le_iff`: along an injective scalar map, base
  change reflects containment of Hopf ideals when the larger quotient is flat over the base.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_toIdeal_le_ker_baseChangeMap`: base-changing a
  morphism that kills `J` gives a morphism that kills `J_K`.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_augmentation`: base change preserves the
  augmentation ideal, so the identity section base-changes to the identity section.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_le_iff_of_faithfullyFlat`: faithfully flat base
  change reflects containment of Hopf ideals.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_injective`: faithfully flat base change reflects
  equality of Hopf ideals.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_comapOfIso`: base change commutes with pulling a
  Hopf ideal back along an ambient isomorphism.
* `TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_commonKernelHopfIdeal_le`: the subgroup generated
  by a base-changed family sits inside the base change of the subgroup it generates.
* `TauCeti.CommHopfAlgCat.quotientBaseChangeIso`: the identification
  `(K ⊗[k] H) ⧸ J_K ≅ K ⊗[k] (H ⧸ J)`.
* `TauCeti.CommHopfAlgCat.map_baseChangeHopfIdeal_of_quotientIso`: an ambient base-change
  isomorphism carries a base-changed Hopf ideal onto a target ideal presented as the kernel of
  the base change of the quotient morphism.
* `TauCeti.CommHopfAlgCat.map_baseChangeHopfIdeal_kerOfSurjective`: the specialization to kernels
  of surjective morphisms matched by base change.
* `TauCeti.CommHopfAlgCat.quotientBaseChangeIsoOfMapEq`: transport of this identification
  across an ambient base-change isomorphism carrying the base-changed ideal to a target ideal.
* `TauCeti.CommHopfAlgCat.mkQuotient_comp_quotientBaseChangeIso_hom`: the identification is
  compatible with the two quotient morphisms.
* `TauCeti.CommHopfAlgCat.mem_quotientPointsSubgroup_baseChangeHopfIdeal_iff`: a point of the
  base change lies in the base-changed closed subgroup exactly when its restriction lies in the
  original one.
* `TauCeti.CommHopfAlgCat.isCentral_baseChangeHopfIdeal`: base change preserves central Hopf
  ideals.

## References

This supplies the Hopf-ideal infrastructure for the Layer 9 milestone "base change along `ℤ → k`
for any commutative ring `k`" of `TauCetiRoadmap/ReductiveGroups/README.md`, transporting a
Chevalley--Demazure carrier presented as a Hopf-ideal quotient. See J. S. Milne, *Algebraic Groups*
(2017), §§1.d, 2.a, and W. C. Waterhouse, *Introduction to Affine Group Schemes*, §16.
-/

public section

open CategoryTheory TensorProduct

namespace TauCeti.CommHopfAlgCat

universe u v w x y

variable {k : Type u} {K : Type w} [CommRing k] [CommRing K] [Algebra k K]
variable {H L : _root_.CommHopfAlgCat.{v} k}

/-- The base change of a Hopf ideal `J` of `H` along `k → K`, as a Hopf ideal of `K ⊗[k] H`.

It is defined as the kernel of the base change of the quotient morphism `H ⟶ H ⧸ J`, which is
surjective, so no Hopf-ideal condition has to be rechecked;
`TauCeti.CommHopfAlgCat.baseChangeHopfIdeal_toIdeal` identifies the underlying ideal with the
one generated by `1 ⊗ J`. -/
noncomputable def baseChangeHopfIdeal (J : HopfIdeal k H) :
    HopfIdeal K (baseChange (K := K) H) :=
  HopfIdeal.kerOfSurjective (baseChangeMap (K := K) (mkQuotient H J)).hom
    (baseChangeMap_surjective (mkQuotient H J) (by
      rw [hom_mkQuotient]
      exact Ideal.Quotient.mkₐ_surjective k J.toIdeal))

/-- Membership in the base-changed Hopf ideal is vanishing under the base-changed quotient
morphism. -/
@[simp]
theorem mem_baseChangeHopfIdeal_iff (J : HopfIdeal k H) (y : baseChange (K := K) H) :
    y ∈ baseChangeHopfIdeal (K := K) J ↔ (baseChangeMap (K := K) (mkQuotient H J)).hom y = 0 :=
  HopfIdeal.mem_kerOfSurjective _ _

/-- The base-changed quotient morphism is the algebra-level map `id ⊗ (Ideal.Quotient.mk)`. -/
private theorem hom_baseChangeMap_mkQuotient_apply (J : HopfIdeal k H)
    (y : K ⊗[k] H) :
    (baseChangeMap (K := K) (mkQuotient H J)).hom y =
      Algebra.TensorProduct.map (AlgHom.id k K) (Ideal.Quotient.mkₐ k J.toIdeal) y := by
  induction y using TensorProduct.inductionOn with
  | tmul s h =>
    rw [baseChangeMap_apply_tmul, Algebra.TensorProduct.map_tmul, mkQuotient_apply,
      AlgHom.id_apply]
  | add a b ha hb => rw [map_add, map_add, ha, hb]

/-- The base change of a Hopf ideal is the ideal generated by `1 ⊗ J`, that is, the extension
of `J` along `h ↦ 1 ⊗ h`. -/
@[simp]
theorem baseChangeHopfIdeal_toIdeal (J : HopfIdeal k H) :
    (baseChangeHopfIdeal (K := K) J).toIdeal =
      J.toIdeal.map (Algebra.TensorProduct.includeRight : H →ₐ[k] K ⊗[k] H) := by
  rw [baseChangeHopfIdeal, HopfIdeal.kerOfSurjective_toIdeal]
  have hker :
      RingHom.ker ((baseChangeMap (K := K) (mkQuotient H J)).hom.toAlgHom) =
        RingHom.ker
          (Algebra.TensorProduct.map (AlgHom.id k K) (Ideal.Quotient.mkₐ k J.toIdeal)) := by
    ext y
    rw [RingHom.mem_ker, RingHom.mem_ker]
    exact Iff.of_eq (congrArg (· = 0) (hom_baseChangeMap_mkQuotient_apply J y))
  rw [hker, Algebra.TensorProduct.lTensor_ker _ (Ideal.Quotient.mkₐ_surjective k J.toIdeal)]
  congr 1
  rw [← RingHom.ker_coe_toRingHom (Ideal.Quotient.mkₐ k J.toIdeal),
    Ideal.Quotient.mkₐ_ker k J.toIdeal]

/-- A scalar multiple of a base-changed element of a Hopf ideal lies in its base change. -/
theorem tmul_mem_baseChangeHopfIdeal {J : HopfIdeal k H} (s : K) {h : H} (hh : h ∈ J) :
    s ⊗ₜ[k] h ∈ baseChangeHopfIdeal (K := K) J := by
  rw [mem_baseChangeHopfIdeal_iff, baseChangeMap_apply_tmul,
    (mkQuotient_eq_zero_iff H J h).mpr hh, tmul_zero]

/-- An element of a Hopf ideal lies in its base change, viewed through `h ↦ 1 ⊗ h`. -/
theorem one_tmul_mem_baseChangeHopfIdeal {J : HopfIdeal k H} {h : H} (hh : h ∈ J) :
    (1 : K) ⊗ₜ[k] h ∈ baseChangeHopfIdeal (K := K) J :=
  tmul_mem_baseChangeHopfIdeal 1 hh

/-- Base change of Hopf ideals is monotone. -/
theorem baseChangeHopfIdeal_mono {J J' : HopfIdeal k H} (hJ : J ≤ J') :
    baseChangeHopfIdeal (K := K) J ≤ baseChangeHopfIdeal (K := K) J' := by
  rw [← HopfIdeal.toIdeal_le_toIdeal, baseChangeHopfIdeal_toIdeal, baseChangeHopfIdeal_toIdeal]
  exact Ideal.map_mono (HopfIdeal.toIdeal_le_toIdeal.mpr hJ)

/-- Base change commutes with pulling a Hopf ideal back along an ambient Hopf-algebra
isomorphism. -/
@[simp]
theorem baseChangeHopfIdeal_comapOfIso (J : HopfIdeal k L) (e : H ≅ L) :
    baseChangeHopfIdeal (K := K)
        (J.comapOfSurjective e.hom.hom (ConcreteCategory.bijective_of_isIso e.hom).2) =
      (baseChangeHopfIdeal (K := K) J).comapOfSurjective
        (baseChangeMap (K := K) e.hom).hom
        (ConcreteCategory.bijective_of_isIso
          ((baseChangeFunctor (K := K)).mapIso e).hom).2 := by
  let qIso := quotientIsoOfIso e J
  let qIsoK := (baseChangeFunctor (K := K)).mapIso qIso
  have hcomm :
      baseChangeMap (K := K) (mkQuotient H
          (J.comapOfSurjective e.hom.hom (ConcreteCategory.bijective_of_isIso e.hom).2)) ≫
          qIsoK.hom =
        baseChangeMap (K := K) e.hom ≫
          baseChangeMap (K := K) (mkQuotient L J) := by
    -- `baseChangeMap` is the map field of the `baseChangeFunctor` abbreviation. Unfolding
    -- that wrapper here exposes both composites in the form required by `Functor.map_comp`.
    change (baseChangeFunctor (K := K)).map (mkQuotient H
          (J.comapOfSurjective e.hom.hom (ConcreteCategory.bijective_of_isIso e.hom).2)) ≫
        (baseChangeFunctor (K := K)).map qIso.hom =
      (baseChangeFunctor (K := K)).map e.hom ≫
        (baseChangeFunctor (K := K)).map (mkQuotient L J)
    rw [← Functor.map_comp, ← Functor.map_comp]
    exact congrArg (fun f ↦ (baseChangeFunctor (K := K)).map f)
      (mkQuotient_comp_quotientIsoOfIso_hom e J)
  ext x
  rw [mem_baseChangeHopfIdeal_iff, HopfIdeal.mem_comapOfSurjective,
    mem_baseChangeHopfIdeal_iff]
  have hpoint : qIsoK.hom.hom
        ((baseChangeMap (K := K) (mkQuotient H
          (J.comapOfSurjective e.hom.hom
            (ConcreteCategory.bijective_of_isIso e.hom).2))).hom x) =
      (baseChangeMap (K := K) (mkQuotient L J)).hom
        ((baseChangeMap (K := K) e.hom).hom x) :=
    congrArg
      (fun f : baseChange (K := K) H ⟶ baseChange (K := K) (quotient L J) ↦ f.hom x) hcomm
  constructor
  · intro hx
    rw [hx, map_zero] at hpoint
    exact hpoint.symm
  · intro hx
    apply (ConcreteCategory.bijective_of_isIso qIsoK.hom).1
    rw [map_zero, hpoint, hx]

/-- Along an injective scalar map, base change reflects containment of Hopf ideals when the
quotient by the larger ideal is flat over the base. In particular, this applies to every field
extension. -/
theorem baseChangeHopfIdeal_le_iff (halg : Function.Injective (algebraMap k K))
    {J J' : HopfIdeal k H} [Module.Flat k (CommHopfAlgCat.quotient H J')] :
    baseChangeHopfIdeal (K := K) J ≤ baseChangeHopfIdeal (K := K) J' ↔ J ≤ J' := by
  constructor
  · intro hJJ' x hx
    have hx' := hJJ' (one_tmul_mem_baseChangeHopfIdeal (K := K) hx)
    rw [mem_baseChangeHopfIdeal_iff, baseChangeMap_apply_tmul] at hx'
    have hzero : (mkQuotient H J').hom x = 0 := by
      exact Algebra.TensorProduct.includeRight_injective
        (B := CommHopfAlgCat.quotient H J') halg <| by
          simpa only [Algebra.TensorProduct.includeRight_apply, TensorProduct.tmul_zero] using hx'
    exact HopfIdeal.mem_toIdeal.mp ((mkQuotient_eq_zero_iff H J' x).mp hzero)
  · exact baseChangeHopfIdeal_mono

section FaithfullyFlat

variable [Module.FaithfullyFlat k K]

/-- Faithfully flat base change preserves and reflects containment of Hopf ideals.

Contravariantly, one closed subgroup scheme is contained in another exactly when the same is true
after base change. -/
@[simp]
theorem baseChangeHopfIdeal_le_iff_of_faithfullyFlat (J J' : HopfIdeal k H) :
    baseChangeHopfIdeal (K := K) J ≤ baseChangeHopfIdeal (K := K) J' ↔ J ≤ J' := by
  rw [← HopfIdeal.toIdeal_le_toIdeal, baseChangeHopfIdeal_toIdeal,
    baseChangeHopfIdeal_toIdeal]
  constructor
  · intro hJJ'
    have hcomp : (Algebra.TensorProduct.comm k K H).toRingHom.comp
        Algebra.TensorProduct.includeRight.toRingHom = algebraMap H (H ⊗[k] K) := by
      ext x
      exact DFunLike.congr_fun
        (Algebra.TensorProduct.comm_comp_includeRight k K H) x
    have hmap : J.toIdeal.map (algebraMap H (H ⊗[k] K)) ≤
        J'.toIdeal.map (algebraMap H (H ⊗[k] K)) := by
      rw [← hcomp, ← Ideal.map_map, ← Ideal.map_map]
      exact Ideal.map_mono hJJ'
    exact Ideal.le_comap_map.trans <|
      (Ideal.comap_mono hmap).trans_eq
        (Ideal.comap_map_eq_self_of_faithfullyFlat J'.toIdeal)
  · exact Ideal.map_mono

/-- Faithfully flat base change reflects equality of Hopf ideals. -/
theorem baseChangeHopfIdeal_injective :
    Function.Injective
      (baseChangeHopfIdeal (K := K) : HopfIdeal k H → HopfIdeal K (baseChange (K := K) H)) :=
  fun J J' hJJ' ↦ le_antisymm
    ((baseChangeHopfIdeal_le_iff_of_faithfullyFlat J J').mp hJJ'.le)
    ((baseChangeHopfIdeal_le_iff_of_faithfullyFlat J' J).mp hJJ'.ge)

end FaithfullyFlat

/-- If a Hopf ideal is killed by a morphism, its base change is killed by the base change of that
morphism. This is the ideal-theoretic form of compatibility between closed subgroup
factorizations and base change. -/
theorem baseChangeHopfIdeal_toIdeal_le_ker_baseChangeMap {N : _root_.CommHopfAlgCat.{v} k}
    (J : HopfIdeal k H) (f : H ⟶ N) (hJ : J.toIdeal ≤ RingHom.ker f.hom.toAlgHom.toRingHom) :
    (baseChangeHopfIdeal (K := K) J).toIdeal ≤
      RingHom.ker (baseChangeMap (K := K) f).hom.toAlgHom.toRingHom := by
  rw [baseChangeHopfIdeal_toIdeal, Ideal.map_le_iff_le_comap]
  intro h hh
  rw [Ideal.mem_comap, RingHom.mem_ker, Algebra.TensorProduct.includeRight_apply]
  -- The ideal goal applies the underlying `RingHom`; expose the Hopf morphism application so the
  -- pure-tensor equation for `baseChangeMap` can rewrite it.
  change (baseChangeMap (K := K) f).hom (1 ⊗ₜ[k] h) = 0
  rw [baseChangeMap_apply_tmul]
  have hf : f.hom h = 0 := RingHom.mem_ker.mp (hJ hh)
  rw [hf, tmul_zero]

/-- The base change of the trivial Hopf ideal is trivial. -/
@[simp]
theorem baseChangeHopfIdeal_bot :
    baseChangeHopfIdeal (K := K) (⊥ : HopfIdeal k H) = ⊥ := by
  refine HopfIdeal.ext fun y ↦ ?_
  rw [← HopfIdeal.mem_toIdeal, ← HopfIdeal.mem_toIdeal, HopfIdeal.bot_toIdeal,
    baseChangeHopfIdeal_toIdeal, HopfIdeal.bot_toIdeal, Ideal.map_bot]

/-- Every element of a base change agrees, modulo the base change of the augmentation ideal, with
the image of its counit: the unit splits the base-changed counit, factorwise on pure tensors. -/
private theorem sub_algebraMap_counit_mem_baseChangeHopfIdeal_augmentation (y : K ⊗[k] H) :
    y - algebraMap K (K ⊗[k] H) (Coalgebra.counit (R := K) y) ∈
      baseChangeHopfIdeal (K := K) (HopfIdeal.augmentation k H) := by
  induction y using TensorProduct.inductionOn with
  | tmul s x =>
    have hx : x - Coalgebra.counit (R := k) x • (1 : H) ∈ HopfIdeal.augmentation k H := by
      rw [HopfIdeal.mem_augmentation, map_sub, map_smul, Bialgebra.counit_one, smul_eq_mul,
        mul_one, sub_self]
    have hy : s ⊗ₜ[k] x - algebraMap K (K ⊗[k] H) (Coalgebra.counit (R := K) (s ⊗ₜ[k] x)) =
        s ⊗ₜ[k] (x - Coalgebra.counit (R := k) x • (1 : H)) := by
      rw [_root_.TensorProduct.counit_tmul, CommSemiring.counit_apply,
        Algebra.TensorProduct.algebraMap_apply, Algebra.algebraMap_self_apply,
        TensorProduct.smul_tmul, TensorProduct.tmul_sub]
    rw [hy]
    exact tmul_mem_baseChangeHopfIdeal s hx
  | add a c ha hc =>
    have hac : a + c - algebraMap K (K ⊗[k] H) (Coalgebra.counit (R := K) (a + c)) =
        (a - algebraMap K (K ⊗[k] H) (Coalgebra.counit (R := K) a)) +
          (c - algebraMap K (K ⊗[k] H) (Coalgebra.counit (R := K) c)) := by
      rw [map_add, map_add]
      ring
    rw [hac]
    exact add_mem ha hc

/-- Base change preserves the augmentation ideal: the identity section of a base-changed affine
group scheme is the base change of the identity section. -/
@[simp]
theorem baseChangeHopfIdeal_augmentation :
    baseChangeHopfIdeal (K := K) (HopfIdeal.augmentation k H) =
      HopfIdeal.augmentation K (baseChange (K := K) H) := by
  refine le_antisymm ?_ ?_
  · rw [← HopfIdeal.toIdeal_le_toIdeal, baseChangeHopfIdeal_toIdeal]
    refine Ideal.map_le_iff_le_comap.mpr fun x hx ↦ ?_
    have hx0 : Coalgebra.counit (R := k) x = 0 :=
      (HopfIdeal.mem_augmentation k H).mp (HopfIdeal.mem_toIdeal.mp hx)
    rw [Ideal.mem_comap, HopfIdeal.mem_toIdeal, HopfIdeal.mem_augmentation,
      Algebra.TensorProduct.includeRight_apply, _root_.TensorProduct.counit_tmul, hx0,
      zero_smul]
  · intro y hy
    have hy0 : Coalgebra.counit (R := K) y = 0 :=
      (HopfIdeal.mem_augmentation K (baseChange (K := K) H)).mp hy
    have hsplit := sub_algebraMap_counit_mem_baseChangeHopfIdeal_augmentation (K := K) y
    rwa [hy0, map_zero, sub_zero] at hsplit

section CommonKernel

variable {ι : Type y} {N : ι → _root_.CommHopfAlgCat.{v} k}

/-- The base change of the largest Hopf ideal killed by a family of morphisms is killed by the
base change of that family.

Contravariantly: the closed subgroup scheme generated by a base-changed family of morphisms is a
closed subgroup scheme of the base change of the one generated by the original family. The
reverse containment does not follow from generation alone. -/
theorem baseChangeHopfIdeal_commonKernelHopfIdeal_le (f : ∀ i, H ⟶ N i) :
    baseChangeHopfIdeal (K := K) (commonKernelHopfIdeal f) ≤
      commonKernelHopfIdeal fun i ↦ baseChangeMap (K := K) (f i) := by
  refine (le_commonKernelHopfIdeal_iff _ _).mpr fun i ↦ ?_
  rw [baseChangeHopfIdeal_toIdeal]
  refine Ideal.map_le_iff_le_comap.mpr fun h hh ↦ ?_
  have hker : (f i).hom h = 0 :=
    RingHom.mem_ker.mp (commonKernelHopfIdeal_toIdeal_le_ker f i hh)
  have hz : (baseChangeMap (K := K) (f i)).hom ((1 : K) ⊗ₜ[k] h) = 0 := by
    rw [baseChangeMap_apply_tmul, hker, tmul_zero]
  rw [Ideal.mem_comap, RingHom.mem_ker, Algebra.TensorProduct.includeRight_apply]
  exact hz

end CommonKernel

/-- The quotient of a base change by a base-changed Hopf ideal is the base change of the
quotient: `(K ⊗[k] H) ⧸ J_K ≅ K ⊗[k] (H ⧸ J)`.

Geometrically, the closed subgroup scheme cut out by `J` base-changes to the closed subgroup
scheme cut out by `J_K`. -/
noncomputable def quotientBaseChangeIso (J : HopfIdeal k H) :
    quotient (baseChange (K := K) H) (baseChangeHopfIdeal (K := K) J) ≅
      baseChange (K := K) (quotient H J) :=
  _root_.CommHopfAlgCat.isoMk
    (HopfIdeal.kerLiftBialgEquiv (baseChangeMap (K := K) (mkQuotient H J)).hom
      (baseChangeMap_surjective (mkQuotient H J) (by
        rw [hom_mkQuotient]
        exact Ideal.Quotient.mkₐ_surjective k J.toIdeal)))

/-- The identification of the base-changed quotient reads a quotient class through the
base-changed quotient morphism. -/
@[simp]
theorem quotientBaseChangeIso_hom_apply (J : HopfIdeal k H) (y : baseChange (K := K) H) :
    (quotientBaseChangeIso (K := K) J).hom
        (Ideal.Quotient.mk (baseChangeHopfIdeal (K := K) J).toIdeal y) =
      (baseChangeMap (K := K) (mkQuotient H J)).hom y := by
  have hy : (quotientBaseChangeIso (K := K) J).hom
      (Ideal.Quotient.mkₐ K (baseChangeHopfIdeal (K := K) J).toIdeal y) =
        (baseChangeMap (K := K) (mkQuotient H J)).hom y :=
    HopfIdeal.kerLiftBialgHom_mk _ _ y
  rwa [Ideal.Quotient.mkₐ_eq_mk] at hy

/-- The identification of the base-changed quotient is compatible with the quotient morphisms:
quotienting `K ⊗[k] H` by `J_K` and then identifying is base-changing `H ⟶ H ⧸ J`. -/
@[simp]
theorem mkQuotient_comp_quotientBaseChangeIso_hom (J : HopfIdeal k H) :
    mkQuotient (baseChange (K := K) H) (baseChangeHopfIdeal (K := K) J) ≫
        (quotientBaseChangeIso (K := K) J).hom =
      baseChangeMap (K := K) (mkQuotient H J) := by
  ext y
  rw [_root_.CommHopfAlgCat.comp_apply, mkQuotient_apply, Ideal.Quotient.mkₐ_eq_mk,
    quotientBaseChangeIso_hom_apply]

/-- An ambient base-change isomorphism carries a base-changed Hopf ideal generated by a set to
the target Hopf ideal when it carries the generating set onto the target generating set. -/
theorem map_baseChangeHopfIdeal_of_toIdeal_eq_span
    {H' : _root_.CommHopfAlgCat.{max w v} K} {S : Set H} {S' : Set H'}
    (J : HopfIdeal k H) (J' : HopfIdeal K H') (e : baseChange (K := K) H ≅ H')
    (hJ : J.toIdeal = Ideal.span S) (hJ' : J'.toIdeal = Ideal.span S')
    (h : (fun x : H => e.hom.hom ((1 : K) ⊗ₜ[k] x)) '' S = S') :
    (baseChangeHopfIdeal (K := K) J).map e.hom.hom = J' := by
  apply HopfIdeal.ext
  intro x
  rw [← HopfIdeal.mem_toIdeal, ← HopfIdeal.mem_toIdeal, HopfIdeal.map_toIdeal,
    baseChangeHopfIdeal_toIdeal, hJ, hJ', Ideal.map_span, Ideal.map_span,
    Set.image_image]
  simpa only [Algebra.TensorProduct.includeRight_apply, BialgHom.coe_toAlgHom,
    AlgHom.toRingHom_eq_coe, RingHom.coe_coe] using
    Iff.of_eq (congrArg (fun T => x ∈ Ideal.span T) h)

/-- An ambient base-change isomorphism carries a base-changed Hopf ideal onto a target Hopf
ideal, when both are presented as vanishing ideals of morphisms matched by base change: `J` is
the kernel of `f`, which factors through the quotient by `J` via the isomorphism `q`, and `f'`
is the base change of `f` read through `e` and `t`.

This is the kernel-presented companion of
`TauCeti.CommHopfAlgCat.map_baseChangeHopfIdeal_of_toIdeal_eq_span`, for ideals that come with a
quotient presentation rather than with generating sets. -/
theorem map_baseChangeHopfIdeal_of_quotientIso
    {T : _root_.CommHopfAlgCat.{v} k} {H' T' : _root_.CommHopfAlgCat.{max w v} K}
    (J : HopfIdeal k H) (J' : HopfIdeal K H')
    (e : baseChange (K := K) H ≅ H') (t : baseChange (K := K) T ≅ T')
    (q : quotient H J ≅ T) {f : H ⟶ T} {f' : H' ⟶ T'}
    (hq : mkQuotient H J ≫ q.hom = f)
    (hf' : e.inv ≫ baseChangeMap (K := K) f ≫ t.hom = f')
    (hJ' : ∀ x, x ∈ J' ↔ f'.hom x = 0) :
    (baseChangeHopfIdeal (K := K) J).map e.hom.hom = J' := by
  have he : Function.Bijective e.hom.hom := ConcreteCategory.bijective_of_isIso e.hom
  have hcomm : baseChangeMap (K := K) (mkQuotient H J) ≫
      (baseChangeMap (K := K) q.hom ≫ t.hom) = e.hom ≫ f' := by
    rw [← Category.assoc, ← (baseChangeFunctor (K := K)).map_comp, hq, ← hf']
    simp
  have hr : Function.Injective (baseChangeMap (K := K) q.hom ≫ t.hom).hom :=
    (ConcreteCategory.bijective_of_isIso
      ((baseChangeFunctor (K := K)).mapIso q ≪≫ t).hom).1
  have hzero (y : baseChange (K := K) H) :
      (baseChangeMap (K := K) (mkQuotient H J)).hom y = 0 ↔ f'.hom (e.hom.hom y) = 0 := by
    have hy := congrArg (fun g ↦ g.hom y) hcomm
    simp only [_root_.CommHopfAlgCat.hom_comp, BialgHom.comp_apply] at hy
    rw [← hy]
    exact ⟨fun hy0 ↦ by rw [hy0]; simp, fun hy0 ↦ hr (by simpa using hy0)⟩
  ext x
  rw [HopfIdeal.mem_map_iff_of_surjective he.2, hJ' x]
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact (hzero y).mp ((mem_baseChangeHopfIdeal_iff J y).mp hy)
  · intro hx
    refine ⟨e.inv.hom x, ?_, _root_.CommHopfAlgCat.hom_inv_apply e x⟩
    rw [mem_baseChangeHopfIdeal_iff]
    apply (hzero _).mpr
    rwa [_root_.CommHopfAlgCat.hom_inv_apply]

/-- An ambient base-change isomorphism carries the base change of the kernel of a surjective
morphism `f` onto the kernel of a surjective morphism `f'`, when `f'` is the base change of `f`
read through `e` and `t`. -/
theorem map_baseChangeHopfIdeal_kerOfSurjective
    {T : _root_.CommHopfAlgCat.{v} k} {H' T' : _root_.CommHopfAlgCat.{max w v} K}
    (e : baseChange (K := K) H ≅ H') (t : baseChange (K := K) T ≅ T')
    {f : H ⟶ T} (hf : Function.Surjective f.hom) {f' : H' ⟶ T'}
    (hf' : Function.Surjective f'.hom)
    (hbase : e.inv ≫ baseChangeMap (K := K) f ≫ t.hom = f') :
    (baseChangeHopfIdeal (K := K) (HopfIdeal.kerOfSurjective f.hom hf)).map e.hom.hom =
      HopfIdeal.kerOfSurjective f'.hom hf' :=
  map_baseChangeHopfIdeal_of_quotientIso _ _ e t (quotientKerOfSurjectiveIso f hf)
    (mkQuotient_comp_quotientKerOfSurjectiveIso_hom f hf) hbase
    (fun _ ↦ HopfIdeal.mem_kerOfSurjective _ _)

/-- Pulling a target Hopf ideal back along an ambient isomorphism which is its image recovers
the original ideal. -/
private theorem comapOfSurjective_eq_baseChangeHopfIdeal_of_map_eq
    {H' : _root_.CommHopfAlgCat.{max w v} K} (J : HopfIdeal k H) (J' : HopfIdeal K H')
    (e : baseChange (K := K) H ≅ H')
    (hJ : (baseChangeHopfIdeal (K := K) J).map e.hom.hom = J') :
    J'.comapOfSurjective e.hom.hom (ConcreteCategory.bijective_of_isIso e.hom).2 =
      baseChangeHopfIdeal (K := K) J := by
  let he : Function.Bijective e.hom.hom :=
    ⟨(ConcreteCategory.bijective_of_isIso e.hom).1,
      (ConcreteCategory.bijective_of_isIso e.hom).2⟩
  calc
    J'.comapOfSurjective e.hom.hom (ConcreteCategory.bijective_of_isIso e.hom).2 =
        ((baseChangeHopfIdeal (K := K) J).map e.hom.hom).comapOfSurjective
          e.hom.hom he.2 := by
      rw [hJ]
    _ = baseChangeHopfIdeal (K := K) J :=
      HopfIdeal.comapOfSurjective_map_of_bijective _ _ he

/-- Transport the base change of a Hopf-ideal quotient across an isomorphism of the ambient
base-changed Hopf algebra which carries the base-changed ideal to a target Hopf ideal. -/
noncomputable def quotientBaseChangeIsoOfMapEq
    {H' : _root_.CommHopfAlgCat.{max w v} K} (J : HopfIdeal k H) (J' : HopfIdeal K H')
    (e : baseChange (K := K) H ≅ H')
    (hJ : (baseChangeHopfIdeal (K := K) J).map e.hom.hom = J') :
    baseChange (K := K) (quotient H J) ≅ quotient H' J' :=
  (quotientBaseChangeIso (K := K) J).symm ≪≫
    eqToIso (congrArg (quotient (baseChange (K := K) H))
      (comapOfSurjective_eq_baseChangeHopfIdeal_of_map_eq J J' e hJ).symm) ≪≫
    quotientIsoOfIso e J'

/-- The transported quotient base-change isomorphism commutes with the quotient morphisms. -/
@[simp]
theorem baseChangeMap_mkQuotient_comp_quotientBaseChangeIsoOfMapEq_hom
    {H' : _root_.CommHopfAlgCat.{max w v} K} (J : HopfIdeal k H) (J' : HopfIdeal K H')
    (e : baseChange (K := K) H ≅ H')
    (hJ : (baseChangeHopfIdeal (K := K) J).map e.hom.hom = J') :
    baseChangeMap (K := K) (mkQuotient H J) ≫
        (quotientBaseChangeIsoOfMapEq J J' e hJ).hom =
      e.hom ≫ mkQuotient H' J' := by
  let hcomap := comapOfSurjective_eq_baseChangeHopfIdeal_of_map_eq J J' e hJ
  have hbase :
      baseChangeMap (K := K) (mkQuotient H J) ≫
          (quotientBaseChangeIso (K := K) J).symm.hom =
        mkQuotient (baseChange (K := K) H) (baseChangeHopfIdeal (K := K) J) := by
    rw [← cancel_mono (quotientBaseChangeIso (K := K) J).hom]
    simp
  rw [quotientBaseChangeIsoOfMapEq, Iso.trans_hom, Iso.trans_hom,
    ← Category.assoc, hbase, eqToIso.hom, ← Category.assoc,
    mkQuotient_comp_eqToHom, mkQuotient_comp_quotientIsoOfIso_hom]
  exact hcomap

variable (A : CommAlgCat.{x} K)

/-- A point of the base change lies in the closed subgroup cut out by the base-changed Hopf
ideal exactly when its restriction along `h ↦ 1 ⊗ h` lies in the closed subgroup cut out by the
original one. On points, base change changes nothing but the base ring the algebra is viewed
over. -/
theorem mem_quotientPointsSubgroup_baseChangeHopfIdeal_iff (J : HopfIdeal k H)
    (g : HopfAlgebra.points (R := K) (H := baseChange (K := K) H) A) :
    g ∈ quotientPointsSubgroup (baseChange (K := K) H) (baseChangeHopfIdeal (K := K) J) A ↔
      baseChangePointsMulEquiv (K := K) A H g ∈
        quotientPointsSubgroup H J
          (_root_.TauCeti.CommAlgCat.restrictScalarsObj (algebraMap k K) A) := by
  rw [mem_quotientPointsSubgroup_iff, mem_quotientPointsSubgroup_iff]
  constructor
  · intro hg h hh
    rw [baseChangePointsMulEquiv_apply_apply]
    exact hg _ (one_tmul_mem_baseChangeHopfIdeal hh)
  · intro hg y hy
    have hle : (baseChangeHopfIdeal (K := K) J).toIdeal ≤
        RingHom.ker (g.ofConv : baseChange (K := K) H →ₐ[K] A) := by
      rw [baseChangeHopfIdeal_toIdeal]
      refine Ideal.map_le_iff_le_comap.mpr fun h hh ↦ ?_
      rw [Ideal.mem_comap, RingHom.mem_ker]
      have := hg h ((HopfIdeal.mem_toIdeal (I := J)).mp hh)
      rwa [baseChangePointsMulEquiv_apply_apply] at this
    exact RingHom.mem_ker.mp (hle ((HopfIdeal.mem_toIdeal (I := baseChangeHopfIdeal J)).mpr hy))

end TauCeti.CommHopfAlgCat

namespace TauCeti.CommHopfAlgCat

universe u v

variable {k : Type u} {K : Type v} [CommRing k] [CommRing K] [Algebra k K]
variable {H : _root_.CommHopfAlgCat.{v} k}

/-- Base change preserves central Hopf ideals, or equivalently central closed subgroup schemes. -/
theorem isCentral_baseChangeHopfIdeal {J : HopfIdeal k H} (hJ : J.IsCentral) :
    (baseChangeHopfIdeal (K := K) J).IsCentral := by
  rw [isCentral_iff_forall_isCentralPoint]
  intro A g hg
  have hrestrictMem :=
    (mem_quotientPointsSubgroup_baseChangeHopfIdeal_iff (K := K) A J g).mp hg
  have hrestrictCentral :=
    isCentralPoint_of_mem_quotientPointsSubgroup H J hJ _ hrestrictMem
  exact (isCentralPoint_baseChangePointsMulEquiv_iff H A g).mp hrestrictCentral

end TauCeti.CommHopfAlgCat
