/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Group.Subgroup.Map
public import TauCeti.Topology.Algebra.Group.Generation
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicPow
public import TauCeti.Topology.Algebra.Module.Compact
public import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.NumberTheory.Padics.ProperSpace

/-!
# Compact modules underlying abelian pro-p groups

The canonical `ℤ_[p]`-module structure on an abelian pro-`p` group is a compact module in the
sense of `TauCeti.IsCompactModule`. It has the same finite generation theory as the underlying
topological group. A finite topological generating set spans the module because its `ℤ_[p]`-span
is closed. Conversely, an algebraic module generating set
generates a dense subgroup: multiplication by an arbitrary `p`-adic scalar is approximated by
natural-number multiples, using the density of `ℕ` in `ℤ_[p]`.

Thus a topologically finitely generated abelian pro-`p` group is a finitely generated
`ℤ_[p]`-module, the input needed for the structure theorem for compact abelian pro-`p` groups.

## Main results

* `TauCeti.IsProP.isCompactModule`: an abelian pro-`p` group is a compact `ℤ_[p]`-module.
* `TauCeti.IsProP.isTopologicallyFinitelyGenerated_iff_module_finite`: topological finite
  generation of an abelian pro-`p` group is equivalent to finite generation of its canonical
  `ℤ_[p]`-module.
* `TauCeti.IsProP.exists_finite_subset_le_topologicalClosure_closure`,
  `TauCeti.IsProP.isTopologicallyFinitelyGenerated_of_isClosed`: a closed subgroup of a
  topologically finitely generated abelian pro-`p` group is topologically finitely generated, by
  finitely many of its own elements.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 4.3.
-/

public section

namespace TauCeti.IsProP

variable {p : ℕ} [Fact p.Prime] {A : Type*} [CommGroup A] [TopologicalSpace A]
  [IsTopologicalGroup A] [CompactSpace A] [TotallyDisconnectedSpace A]

/-- **An abelian pro-`p` group is a compact `ℤ_p`-module**, for the module structure
`TauCeti.IsProP.module`. -/
theorem isCompactModule (hA : IsProP p A) :
    letI := hA.module
    IsCompactModule ℤ_[p] (Additive A) :=
  letI := hA.module
  ⟨inferInstance, hA.continuousSMul_module, inferInstance, inferInstance⟩

/-- An element of the `ℤ_[p]`-span of `s` lies in the topological closure of the additive
subgroup generated by `s`. -/
theorem span_le_topologicalClosure_closure (hA : IsProP p A) (s : Set (Additive A)) :
    letI := hA.module
    (Submodule.span ℤ_[p] s : Set (Additive A)) ⊆
      ((AddSubgroup.closure s).topologicalClosure : Set (Additive A)) := by
  let _ : Module ℤ_[p] (Additive A) := hA.module
  let _ : ContinuousSMul ℤ_[p] (Additive A) := hA.continuousSMul_module
  intro y hy
  let H := (AddSubgroup.closure s).topologicalClosure
  refine Submodule.span_induction (p := fun x _ ↦ x ∈ H)
    (fun x hx ↦ (AddSubgroup.le_topologicalClosure _) (AddSubgroup.subset_closure hx)) H.zero_mem
    (fun _ _ _ _ hx hy ↦ H.add_mem hx hy) ?_ hy
  intro l x _ hx
  refine PadicInt.denseRange_natCast.induction_on l ?_ fun n ↦ ?_
  · exact (AddSubgroup.isClosed_topologicalClosure _).preimage
      (continuous_id.smul continuous_const)
  · simpa [hA.module_smul] using H.nsmul_mem hx n

/-- **Compact abelian pro-`p` groups have the same algebraic and topological notion of finite
generation.** The module structure in the right-hand side is `TauCeti.IsProP.module`. -/
theorem isTopologicallyFinitelyGenerated_iff_module_finite (hA : IsProP p A) :
    IsTopologicallyFinitelyGenerated A ↔
      letI := hA.module
      Module.Finite ℤ_[p] (Additive A) := by
  let _ : Module ℤ_[p] (Additive A) := hA.module
  let _ : ContinuousSMul ℤ_[p] (Additive A) := hA.continuousSMul_module
  constructor
  · intro hfg
    obtain ⟨s, hs⟩ := isTopologicallyFinitelyGenerated_iff.mp hfg
    have ht : (Additive.ofMul '' (s : Set A)).Finite := s.finite_toSet.image _
    -- The additive classes of `s` span: their `ℤ_p`-span is closed and contains the dense
    -- subgroup they generate.
    have hspan : Submodule.span ℤ_[p] (Additive.ofMul '' (s : Set A)) = ⊤ := by
      refine Submodule.span_eq_top_of_dense_closure ht Submodule.subset_span ?_
      rw [Equiv.image_eq_preimage_symm, Additive.ofMul_symm_eq, ← Subgroup.toAddSubgroup_closure,
        Subgroup.dense_toAddSubgroup_iff, Subgroup.dense_iff_topologicalClosure_eq_top]
      exact hs
    exact Module.finite_def.2 (hspan ▸ Submodule.fg_span ht)
  · intro hfinite
    obtain ⟨s, hs⟩ := hfinite.fg_top
    classical
    apply isTopologicallyFinitelyGenerated_iff.mpr
    refine ⟨(s.image Additive.toMul), ?_⟩
    have hspan_le := hA.span_le_topologicalClosure_closure (s : Set (Additive A))
    have haddtop : (AddSubgroup.closure (s : Set (Additive A))).topologicalClosure = ⊤ := by
      apply top_unique
      intro x _
      apply hspan_le
      rw [hs]
      trivial
    have hclosure :
        (Subgroup.closure (Additive.toMul '' (s : Set (Additive A)))).toAddSubgroup =
          AddSubgroup.closure (s : Set (Additive A)) := by
      rw [Subgroup.toAddSubgroup_closure]
      congr 1
      ext x
      simp
    apply SetLike.ext
    intro x
    constructor
    · intro _
      trivial
    · intro _
      have hx : Additive.ofMul x ∈
          (AddSubgroup.closure (s : Set (Additive A))).topologicalClosure := by
        rw [haddtop]
        trivial
      rw [← hclosure] at hx
      -- `Additive A` has definitionally the topology of `A`; expose the carrier closures to
      -- pass back through the type tag without relying on the subgroup operations.
      change x ∈ _root_.closure
        (Subgroup.closure (Additive.toMul '' (s : Set (Additive A))) : Set A) at hx
      change x ∈ _root_.closure
        (Subgroup.closure ((s.image Additive.toMul : Finset A) : Set A) : Set A)
      simpa only [Finset.coe_image] using hx

/-- **Closed subgroups of topologically finitely generated abelian pro-`p` groups are topologically
finitely generated**, by finitely many of their own elements: a closed subgroup is a
`ℤ_p`-submodule of the canonical module `TauCeti.IsProP.module`, which is a finitely generated
module over the Noetherian ring `ℤ_p`. -/
theorem exists_finite_subset_le_topologicalClosure_closure (hA : IsProP p A)
    (hfg : IsTopologicallyFinitelyGenerated A) {K : Subgroup A} (hK : IsClosed (K : Set A)) :
    ∃ t : Set A, t.Finite ∧ t ⊆ K ∧ K ≤ (Subgroup.closure t).topologicalClosure := by
  let _ : Module ℤ_[p] (Additive A) := hA.module
  have : Module.Finite ℤ_[p] (Additive A) :=
    hA.isTopologicallyFinitelyGenerated_iff_module_finite.1 hfg
  -- The closed subgroup `K` is a `ℤ_p`-submodule: its span lies in its closure, which is itself.
  have hspan : (Submodule.span ℤ_[p] (K.toAddSubgroup : Set (Additive A)) : Set (Additive A)) ⊆
      K.toAddSubgroup := by
    refine (hA.span_le_topologicalClosure_closure _).trans ?_
    rw [AddSubgroup.closure_eq, ← Subgroup.toAddSubgroup_topologicalClosure,
      hK.subgroup_topologicalClosure_eq]
  -- The span is finitely generated, because `ℤ_p` is Noetherian.
  obtain ⟨t', ht'⟩ :=
    IsNoetherian.noetherian (Submodule.span ℤ_[p] (K.toAddSubgroup : Set (Additive A)))
  refine ⟨Additive.toMul '' (t' : Set (Additive A)), t'.finite_toSet.image _, ?_, fun x hx ↦ ?_⟩
  · rintro _ ⟨y, hy, rfl⟩
    exact hspan (ht' ▸ Submodule.subset_span hy)
  · have h1 : Additive.ofMul x ∈
        (AddSubgroup.closure (t' : Set (Additive A))).topologicalClosure :=
      hA.span_le_topologicalClosure_closure _ (ht' ▸ Submodule.subset_span (by simpa using hx))
    rwa [← Additive.toMul.injective.preimage_image (t' : Set (Additive A)),
      ← Subgroup.toAddSubgroup_closure, ← Subgroup.toAddSubgroup_topologicalClosure,
      Additive.mem_toAddSubgroup, toMul_ofMul] at h1

/-- **A closed subgroup of a topologically finitely generated abelian pro-`p` group is
topologically finitely generated.** -/
theorem isTopologicallyFinitelyGenerated_of_isClosed (hA : IsProP p A)
    (hfg : IsTopologicallyFinitelyGenerated A) {K : Subgroup A} (hK : IsClosed (K : Set A)) :
    IsTopologicallyFinitelyGenerated K := by
  obtain ⟨t, ht, htK, hle⟩ := hA.exists_finite_subset_le_topologicalClosure_closure hfg hK
  refine (ht.preimage Subtype.val_injective.injOn).isTopologicallyFinitelyGenerated ?_
  rw [← Subgroup.dense_iff_topologicalClosure_eq_top, Subgroup.closure_coe_preimage_of_subset htK,
    Subgroup.coe_comap, Subgroup.coe_subtype,
    Subgroup.dense_preimage_val_iff_le_topologicalClosure ((Subgroup.closure_le K).2 htK)]
  exact hle

end TauCeti.IsProP
