/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ProP.CompactModule
public import TauCeti.Topology.Algebra.Group.TopologicalAbelianization

/-!
# Finite normal generation of closed normal subgroups with commutative quotient

Let `G` be a topologically finitely generated pro-`p` group. A closed normal subgroup `N` of `G`
with commutative quotient is the closed normal closure of a finite set. Indeed `N` contains the
closure of the commutator subgroup, which is normally generated by the commutators of a finite
topological generating set of `G`, and the image of `N` in the topological abelianization `G^{ab}`
is a closed subgroup of a topologically finitely generated abelian pro-`p` group, hence
topologically generated by finitely many elements
(`IsProP.exists_finite_subset_le_topologicalClosure_closure`), which lift to `N`.

The case of interest is the kernel `X` of a continuous character `χ : G → A` to a commutative
group: finite normal generation of `X` is what makes its topological abelianization `X ⧸ (X, X)`
a finitely generated module over the completed group algebra of `G ⧸ X`.

## Main results

* `IsProP.exists_finite_topologicalClosure_normalClosure_eq`: a closed normal subgroup with
  commutative quotient of a topologically finitely generated pro-`p` group is the closed normal
  closure of a finite set.
* `IsProP.exists_finite_topologicalClosure_normalClosure_eq_ker`: the kernel of a continuous
  homomorphism from a topologically finitely generated pro-`p` group to a commutative `T1` group is
  the closed normal closure of a finite set.
-/

public section

open scoped commutatorElement

namespace TauCeti.IsProP

variable {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G] (hG : IsProP p G)
  (hfg : IsTopologicallyFinitelyGenerated G)
include hG hfg

/-- **A closed normal subgroup with commutative quotient of a topologically finitely generated
pro-`p` group is the closed normal closure of a finite set.** The subgroup contains the closure of
the commutator subgroup, which is normally generated by the commutators of a finite topological
generating set, and its image in the abelianization is a closed subgroup of a topologically
finitely generated abelian pro-`p` group, hence topologically generated by finitely many elements,
which lift to the subgroup. -/
theorem exists_finite_topologicalClosure_normalClosure_eq {N : Subgroup G} [N.Normal]
    (hN : IsClosed (N : Set G)) (hc : commutator G ≤ N) :
    ∃ S : Set G, S.Finite ∧ (Subgroup.normalClosure S).topologicalClosure = N := by
  obtain ⟨s, hs⟩ := isTopologicallyFinitelyGenerated_iff.1 hfg
  -- The image of `N` in the abelianization is topologically finitely generated.
  set q : G →* TopologicalAbelianization G := QuotientGroup.mk' _
  have hq : Continuous q := QuotientGroup.continuous_mk
  obtain ⟨t, ht, htK, hle⟩ := (hG.quotient _).exists_finite_subset_le_topologicalClosure_closure
    (hfg.quotient _) (Subgroup.isClosed_map hN.isCompact q hq)
  have hlift : ∀ y ∈ t, ∃ x, x ∈ N ∧ q x = y := fun y hy ↦ Subgroup.mem_map.1 (htK hy)
  choose! f hf using hlift
  refine ⟨Set.image2 (fun x y ↦ ⁅x, y⁆) (s : Set G) s ∪ f '' t,
    (s.finite_toSet.image2 _ s.finite_toSet).union (ht.image f), le_antisymm ?_ ?_⟩
  · -- Commutators and the lifted generators lie in `N`.
    rw [Subgroup.topologicalClosure_normalClosure_le_iff hN]
    rintro x (⟨a, -, b, -, rfl⟩ | ⟨y, hy, rfl⟩)
    · exact hc (Subgroup.commutator_mem_commutator (Subgroup.mem_top a) (Subgroup.mem_top b))
    · exact (hf y hy).1
  · set M := (Subgroup.normalClosure
      (Set.image2 (fun x y ↦ ⁅x, y⁆) (s : Set G) s ∪ f '' t)).topologicalClosure
    have hcomm : (commutator G).topologicalClosure ≤ M :=
      Subgroup.topologicalClosure_commutator_le_of_forall_commutatorElement_mem hs
        (Subgroup.isClosed_topologicalClosure _) fun x hx y hy ↦
          Subgroup.le_topologicalClosure _
            (Subgroup.subset_normalClosure (Or.inl ⟨x, hx, y, hy, rfl⟩))
    -- `M` contains the kernel of `q`, so it is the preimage of its image, a closed subgroup of the
    -- abelianization containing `t` and therefore the image of `N`.
    intro x hx
    rw [← Subgroup.comap_map_eq_self ((QuotientGroup.ker_mk' _).trans_le hcomm),
      Subgroup.mem_comap]
    refine (Subgroup.closure t).topologicalClosure_minimal ((Subgroup.closure_le _).2 fun y hy ↦ ?_)
      (Subgroup.isClosed_map (Subgroup.isClosed_topologicalClosure _).isCompact q hq)
      (hle (Subgroup.mem_map_of_mem q hx))
    exact ⟨f y, Subgroup.le_topologicalClosure _
      (Subgroup.subset_normalClosure (Or.inr ⟨y, hy, rfl⟩)), (hf y hy).2⟩

variable {A : Type*} [CommGroup A] [TopologicalSpace A] [T1Space A] (χ : G →* A)
  (hχ : Continuous χ)
include hχ

/-- **The kernel of a character of a topologically finitely generated pro-`p` group is the closed
normal closure of a finite set**: it is a closed normal subgroup with commutative quotient
(`IsProP.exists_finite_topologicalClosure_normalClosure_eq`). -/
theorem exists_finite_topologicalClosure_normalClosure_eq_ker :
    ∃ S : Set G, S.Finite ∧ (Subgroup.normalClosure S).topologicalClosure = χ.ker :=
  hG.exists_finite_topologicalClosure_normalClosure_eq hfg
    (χ.coe_ker ▸ isClosed_singleton.preimage hχ) (Abelianization.commutator_subset_ker χ)

end TauCeti.IsProP
