/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.ProP.LowerCentralSeries
public import TauCeti.Topology.Algebra.Group.Profinite.Rank

/-!
# Normal generation in pro-`p` groups

Let `R` be a closed normal subgroup of a pro-`p` group `F`, and let `Rᵖ[R, F]` be the closed
subgroup `TauCeti.pLowerCentralStep p R` generated by the `p`-th powers of `R` and the commutators
`⁅R, F⁆`. The quotient `R ⧸ Rᵖ[R, F]` is the largest quotient of `R` that is elementary abelian
with trivial conjugation action of `F`, and it controls generation of `R` as a **closed normal
subgroup** of `F` exactly as the Frattini quotient `F ⧸ Φ(F)` controls generation of `F`
(`TauCeti.topologicallyGenerates_iff_frattiniQuotient`): a subset of `R` generates `R` as a closed
normal subgroup of `F` if and only if its image topologically generates `R ⧸ Rᵖ[R, F]`. In
particular `R` is generated as a closed normal subgroup of `F` by `n` elements exactly when
`R ⧸ Rᵖ[R, F]` is topologically generated by `n` elements, so when this quotient is topologically
finitely generated, the least number of generators of `R` as a closed normal subgroup of `F` is
its topological generator rank.

The input is Nakayama's lemma for pro-`p` groups in its relative form,
`TauCeti.IsProP.le_of_le_topologicalClosure_sup_pLowerCentralStep`: if `R ≤ closure (N ⬝ Rᵖ[R, F])`
for a closed normal subgroup `N`, then `R ≤ N`.

For a minimal presentation `1 → R → F → G → 1` of a pro-`p` group, with `F` free pro-`p`, the
transgression identifies `H¹(R, 𝔽_p)^F` with `H²(G, 𝔽_p)`, and the `F`-invariant continuous
homomorphisms `R → 𝔽_p` are exactly those factoring through `R ⧸ Rᵖ[R, F]`
(`TauCeti.pLowerCentralStep_subgroupOf_le_ker_iff`). The results here are therefore what make
`dim H²(G, 𝔽_p)` count relations: it is the least number of generators of the relation subgroup
`R` as a closed normal subgroup of `F`.

## Main results

* `TauCeti.IsProP.topologicalClosure_normalClosure_eq_iff_topologicalClosure_sup_eq`: a subset `s`
  of `R` generates `R` as a closed normal subgroup exactly when `s` and `Rᵖ[R, F]` together
  topologically generate `R`.
* `TauCeti.IsProP.topologicalClosure_normalClosure_eq_iff_quotient_pLowerCentralStep`:
  **Burnside's basis theorem for normal generation.** A subset of `R` generates `R` as a closed
  normal subgroup of `F` exactly when its image topologically generates `R ⧸ Rᵖ[R, F]`.
* `TauCeti.IsProP.exists_finset_card_le_topologicalClosure_normalClosure_eq_iff`,
  `TauCeti.IsProP.isTopologicallyFinitelyGenerated_quotient_pLowerCentralStep_iff`,
  `TauCeti.IsProP.topologicalGeneratorRankNat_quotient_pLowerCentralStep_le_iff`: `R` is generated
  as a closed normal subgroup by `n` elements exactly when `R ⧸ Rᵖ[R, F]` is topologically
  generated by `n` elements; so when `R ⧸ Rᵖ[R, F]` is topologically finitely generated, the
  least number of generators of `R` as a closed normal subgroup is its topological generator
  rank.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, Proposition 3.9.5.
* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), Section 1.4.
* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 2.8.
-/

public section

namespace TauCeti

open Subgroup

universe u

variable {p : ℕ} {F : Type u} [Group F] [TopologicalSpace F] [IsTopologicalGroup F]
  [CompactSpace F] [TotallyDisconnectedSpace F]

namespace IsProP

variable (hF : IsProP p F) (hp : p.Prime) {R : Subgroup F} [R.Normal] (hR : IsClosed (R : Set F))
include hF hp hR

/-- **Normal generation modulo `Rᵖ[R, F]`, subgroup form.** A subset `s` of a closed normal
subgroup `R` of a pro-`p` group generates `R` as a closed normal subgroup exactly when `s`
together with `Rᵖ[R, F]` topologically generates `R`. -/
theorem topologicalClosure_normalClosure_eq_iff_topologicalClosure_sup_eq {s : Set F}
    (hs : s ⊆ R) :
    (normalClosure s).topologicalClosure = R ↔
      (Subgroup.closure s ⊔ pLowerCentralStep p R).topologicalClosure = R := by
  set K := (Subgroup.closure s ⊔ pLowerCentralStep p R).topologicalClosure with hK
  have hKR : K ≤ R :=
    topologicalClosure_minimal _ (sup_le ((Subgroup.closure_le _).mpr hs) (pLowerCentralStep_le hR))
      hR
  constructor
  · intro h
    -- `K` is a closed subgroup between `Rᵖ[R, F]` and `R`, hence normal, and it contains `s`,
    -- hence the closed normal closure of `s`.
    have : K.Normal :=
      normal_of_pLowerCentralStep_le_of_le (le_sup_right.trans (le_topologicalClosure _)) hKR
    refine le_antisymm hKR (h.symm.le.trans ?_)
    exact (topologicalClosure_normalClosure_le_iff (isClosed_topologicalClosure _)).mpr
      (Subgroup.subset_closure.trans
        (SetLike.coe_subset_coe.mpr (le_sup_left.trans (le_topologicalClosure _))))
  · intro h
    refine le_antisymm ((topologicalClosure_normalClosure_le_iff hR).mpr hs) ?_
    refine hF.le_of_le_topologicalClosure_sup_pLowerCentralStep hp (isClosed_topologicalClosure _)
      (h.symm.le.trans (topologicalClosure_mono (sup_le_sup_right ?_ _)))
    exact closure_le_normalClosure.trans (le_topologicalClosure _)

/-- **Burnside's basis theorem for normal generation.** A subset `s` of a closed normal subgroup
`R` of a pro-`p` group `F` generates `R` as a closed normal subgroup of `F` exactly when its image
topologically generates the quotient `R ⧸ Rᵖ[R, F]`. -/
theorem topologicalClosure_normalClosure_eq_iff_quotient_pLowerCentralStep (s : Set R) :
    (normalClosure (Subtype.val '' s)).topologicalClosure = R ↔
      (Subgroup.closure
        (QuotientGroup.mk' ((pLowerCentralStep p R).subgroupOf R) '' s)).topologicalClosure =
          ⊤ := by
  have : CompactSpace R := isCompact_iff_compactSpace.mp hR.isCompact
  have hs : Subtype.val '' s ⊆ R := by
    rintro _ ⟨x, -, rfl⟩
    exact x.2
  rw [hF.topologicalClosure_normalClosure_eq_iff_topologicalClosure_sup_eq hp hR hs,
    ← topologicalClosure_closure_sup_eq_top_iff]
  -- Both sides describe the same subgroup of `R`, read in `F` and in `R`.
  have hmap : ((Subgroup.closure s ⊔ (pLowerCentralStep p R).subgroupOf R).topologicalClosure).map
      R.subtype =
        (Subgroup.closure (Subtype.val '' s) ⊔ pLowerCentralStep p R).topologicalClosure := by
    rw [R.subtype.map_topologicalClosure continuous_subtype_val _
      (isClosed_topologicalClosure _).isCompact, Subgroup.map_sup, MonoidHom.map_closure,
      map_subgroupOf_eq_of_le (pLowerCentralStep_le hR), coe_subtype]
  have htop : (⊤ : Subgroup R).map R.subtype = R := by
    rw [← MonoidHom.range_eq_map, range_subtype]
  constructor
  · intro h
    exact map_injective Subtype.val_injective (hmap.trans (h.trans htop.symm))
  · intro h
    rw [← hmap, h, htop]

/-- A closed normal subgroup `R` of a pro-`p` group is generated as a closed normal subgroup by at
most `n` elements exactly when `R ⧸ Rᵖ[R, F]` is topologically generated by at most `n`
elements. -/
theorem exists_finset_card_le_topologicalClosure_normalClosure_eq_iff (n : ℕ) :
    (∃ s : Finset R, s.card ≤ n ∧
        (normalClosure (Subtype.val '' (s : Set R))).topologicalClosure = R) ↔
      ∃ t : Finset (R ⧸ (pLowerCentralStep p R).subgroupOf R), t.card ≤ n ∧
        (Subgroup.closure (t : Set (R ⧸ (pLowerCentralStep p R).subgroupOf R))).topologicalClosure =
          ⊤ := by
  classical
  have hq : Function.Surjective (QuotientGroup.mk' ((pLowerCentralStep p R).subgroupOf R)) :=
    QuotientGroup.mk'_surjective _
  constructor
  · rintro ⟨s, hsn, hs⟩
    refine ⟨s.image (QuotientGroup.mk' _), Finset.card_image_le.trans hsn, ?_⟩
    rw [Finset.coe_image]
    exact (hF.topologicalClosure_normalClosure_eq_iff_quotient_pLowerCentralStep hp hR _).mp hs
  · rintro ⟨t, htn, ht⟩
    refine ⟨t.image (Function.surjInv hq), Finset.card_image_le.trans htn, ?_⟩
    rw [hF.topologicalClosure_normalClosure_eq_iff_quotient_pLowerCentralStep hp hR,
      Finset.coe_image, (Function.rightInverse_surjInv hq).image_image]
    exact ht

/-- The quotient `R ⧸ Rᵖ[R, F]` of a closed normal subgroup `R` of a pro-`p` group is topologically
finitely generated exactly when `R` is generated as a closed normal subgroup by finitely many
elements. -/
theorem isTopologicallyFinitelyGenerated_quotient_pLowerCentralStep_iff :
    IsTopologicallyFinitelyGenerated (R ⧸ (pLowerCentralStep p R).subgroupOf R) ↔
      ∃ s : Finset R, (normalClosure (Subtype.val '' (s : Set R))).topologicalClosure = R := by
  constructor
  · intro h
    obtain ⟨t, ht⟩ := isTopologicallyFinitelyGenerated_iff.mp h
    obtain ⟨s, -, hs⟩ :=
      (hF.exists_finset_card_le_topologicalClosure_normalClosure_eq_iff hp hR t.card).mpr
        ⟨t, le_rfl, ht⟩
    exact ⟨s, hs⟩
  · rintro ⟨s, hs⟩
    obtain ⟨t, -, ht⟩ :=
      (hF.exists_finset_card_le_topologicalClosure_normalClosure_eq_iff hp hR s.card).mp
        ⟨s, le_rfl, hs⟩
    exact isTopologicallyFinitelyGenerated_iff.mpr ⟨t, ht⟩

/-- **The least number of generators of `R` as a closed normal subgroup.** The topological
generator rank of `R ⧸ Rᵖ[R, F]` is at most `n` exactly when the closed normal subgroup `R` of the
pro-`p` group `F` is generated as a closed normal subgroup by at most `n` elements. -/
theorem topologicalGeneratorRankNat_quotient_pLowerCentralStep_le_iff
    (h : IsTopologicallyFinitelyGenerated (R ⧸ (pLowerCentralStep p R).subgroupOf R)) (n : ℕ) :
    topologicalGeneratorRankNat (R ⧸ (pLowerCentralStep p R).subgroupOf R) h ≤ n ↔
      ∃ s : Finset R, s.card ≤ n ∧
        (normalClosure (Subtype.val '' (s : Set R))).topologicalClosure = R := by
  rw [hF.exists_finset_card_le_topologicalClosure_normalClosure_eq_iff hp hR n]
  constructor
  · intro hn
    obtain ⟨t, ht, htgen⟩ := exists_finset_card_eq_topologicalGeneratorRankNat h
    exact ⟨t, ht.le.trans hn, htgen⟩
  · rintro ⟨t, htn, ht⟩
    exact (topologicalGeneratorRankNat_le h ht).trans htn

end IsProP

end TauCeti
