/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Padics.TwistedUnits
import Mathlib.Topology.Algebra.OpenSubgroup
import TauCeti.Algebra.Group.Subgroup.ZPowers
import TauCeti.NumberTheory.Padics.PadicIntegers
import TauCeti.Topology.Algebra.Group.Subgroup

/-!
# The closed subgroups of `ℤ_2ˣ`

The dyadic unit group decomposes as `ℤ_2ˣ = {±1} × U^(2)` with `U^(2) = 1 + 4ℤ_2`, and the
nontrivial closed subgroups of `U^(2)` are the principal unit groups `U^(f) = 1 + 2^f ℤ_2`,
`f ≥ 2`. Sorting a closed subgroup `A ≤ ℤ_2ˣ` by how it sits over `{±1}` gives Labute's
description of all of them. Writing `A₀ = A ⊓ U^(2)` for the even part:

* if `A₀ = 1` then `A = {±1}` (or `A` is trivial);
* if `A₀ = U^(f)` and `-1 ∈ A` then `A = V^(f) := {±1} × U^(f)`, the subgroup generated by `-1`
  together with `U^(f)`;
* if `A₀ = U^(f)` and `-1 ∉ A` then either `A = U^(f)`, or `f ≥ 3` and `A` is the **twisted
  subgroup** `U^[f-1]`, the closed subgroup generated by `-1 + 2^(f-1)`.

No two members of the resulting list `U^(f)`, `V^(f)` (`f ≥ 2`), `{±1}`, `U^[f]` (`f ≥ 2`)
coincide, and each family is indexed faithfully by its level. The principal and twisted
subgroups are procyclic, while `V^(f)` is not: `[V^(f) : U^(f+1)] = 4` but every element of
`V^(f)` squares into `U^(f+1)`. Together with the indices `[ℤ_2ˣ : U^(f)] = 2^(f-1)`,
`[ℤ_2ˣ : V^(f)] = 2^(f-2)` and `[ℤ_2ˣ : U^[f]] = 2^(f-1)`, this is the table from which the
image of a continuous character `G → ℤ_2ˣ` on a pro-`2` group is read off.

The last column of that table is the index `(A : A²)` of the subgroup of squares, which is the
numerical invariant of the image of an orientation character that the existence half of the
classification of Demushkin groups compares with `2 ^ n`. The squares of `U^(f)`, of `V^(f)` and
of `U^[f]` are all `U^(f+1)`, and the squares of `{±1}` are trivial, so `(A : A²)` is `2` for the
three procyclic families and `4` for `V^(f)`; for a closed subgroup `A` of `ℤ_2ˣ` it is `1`, `2`
or `4`, with `1` exactly for `A = 1` and `4` exactly for `A = V^(f)`.

## Main declarations

* `TauCeti.unitsPlusMinus f`: `V^(f) = {±1} × U^(f)`, with `TauCeti.mem_unitsPlusMinus_iff`
  (`u ∈ V^(f) ↔ u ∈ U^(f) ∨ -u ∈ U^(f)`), `TauCeti.unitsPlusMinus_le_iff`
  (`V^(f) ≤ A ↔ U^(f) ≤ A ∧ -1 ∈ A`), `TauCeti.index_unitsPlusMinus`
  (`[ℤ_2ˣ : V^(f)] = 2 ^ (f - 2)`), `TauCeti.unitsPlusMinus_inf_unitsPrincipal_two`
  (`V^(f) ⊓ U^(2) = U^(f)`) and `TauCeti.unitsPlusMinus_inj`.
* `TauCeti.unitsPlusMinus_two`, `TauCeti.disjoint_unitsPrincipal_zpowers_neg_one`: the
  decomposition `ℤ_2ˣ = {±1} × U^(2)`.
* `TauCeti.closedSubgroup_units_two_classification`: every nontrivial closed subgroup of `ℤ_2ˣ`
  is a `U^(f)`, a `V^(f)`, `{±1}`, or a twisted subgroup `U^[f]` with its model generator
  `-1 + 2 ^ f`; the lemmas `TauCeti.unitsPrincipal_ne_unitsPlusMinus` and their companions
  show that the four families are pairwise distinct.
* `TauCeti.exists_topologicalClosure_zpowers_eq_of_isClosed_of_neg_one_notMem`: a closed
  subgroup of `ℤ_2ˣ` not containing `-1` is procyclic;
  `TauCeti.not_exists_topologicalClosure_zpowers_eq_unitsPlusMinus`: `V^(f)` is not.
* `TauCeti.map_powMonoidHom_two_unitsPlusMinus`: `(V^(f))² = U^(f+1)`;
  `TauCeti.relIndex_map_powMonoidHom_two_unitsPlusMinus`: `(V^(f) : (V^(f))²) = 4`.
* `TauCeti.relIndex_map_powMonoidHom_two_eq_one_or_two_or_four`: `(A : A²) ∈ {1, 2, 4}` for
  closed `A`;
  `TauCeti.relIndex_map_powMonoidHom_two_eq_four_iff` and
  `TauCeti.relIndex_map_powMonoidHom_two_eq_one_iff`: the value `4` characterizes the `V^(f)` and
  the value `1` the trivial subgroup.

## References

* J. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), the remark
  following the corollary to Theorem 4.
* J. Neukirch, *Algebraic Number Theory*, Chapter II, Proposition 5.7.
-/

public section

namespace TauCeti

/-! ### The subgroups `V^(f) = {±1} × U^(f)` -/

/-- `V^(f) = {±1} × U^(f)`, the subgroup of `ℤ_2ˣ` generated by `-1` together with the principal
unit group `U^(f)`. For `f ≥ 2` it is the closed subgroup with even part `U^(f)` containing `-1`;
at `f ≤ 2` it is all of `ℤ_2ˣ`. -/
noncomputable def unitsPlusMinus (f : ℕ) : Subgroup ℤ_[2]ˣ :=
  unitsPrincipal 2 f ⊔ Subgroup.zpowers (-1)

/-- `V^(f) = U^(f) ⊔ ⟨-1⟩`. -/
theorem unitsPlusMinus_def (f : ℕ) :
    unitsPlusMinus f = unitsPrincipal 2 f ⊔ Subgroup.zpowers (-1) :=
  (rfl)

/-- `V^(f)` is the least subgroup containing `U^(f)` and `-1`: `V^(f) ≤ A` iff `U^(f) ≤ A` and
`-1 ∈ A`. -/
@[simp]
theorem unitsPlusMinus_le_iff {f : ℕ} {A : Subgroup ℤ_[2]ˣ} :
    unitsPlusMinus f ≤ A ↔ unitsPrincipal 2 f ≤ A ∧ (-1 : ℤ_[2]ˣ) ∈ A := by
  rw [unitsPlusMinus_def, sup_le_iff, Subgroup.zpowers_le]

/-- `u ∈ V^(f)` iff `u ∈ U^(f)` or `-u ∈ U^(f)`. -/
@[simp]
theorem mem_unitsPlusMinus_iff {f : ℕ} {u : ℤ_[2]ˣ} :
    u ∈ unitsPlusMinus f ↔ u ∈ unitsPrincipal 2 f ∨ -u ∈ unitsPrincipal 2 f := by
  constructor
  · intro h
    obtain ⟨y, hy, z, hz, rfl⟩ := Subgroup.mem_sup.mp h
    rcases (Subgroup.mem_zpowers_neg_one_iff PadicInt.units_neg_one_ne_one).mp hz with rfl | rfl
    · exact Or.inl (by rwa [mul_one])
    · exact Or.inr (by rwa [mul_neg_one, neg_neg])
  · rintro (h | h)
    · exact Subgroup.mem_sup_left h
    · have := (unitsPlusMinus f).mul_mem (Subgroup.mem_sup_right (Subgroup.mem_zpowers _))
        (Subgroup.mem_sup_left h)
      rwa [neg_one_mul, neg_neg] at this

/-- `U^(f) ≤ V^(f)`. -/
theorem unitsPrincipal_le_unitsPlusMinus (f : ℕ) : unitsPrincipal 2 f ≤ unitsPlusMinus f :=
  le_sup_left

/-- `-1 ∈ V^(f)`. -/
theorem neg_one_mem_unitsPlusMinus (f : ℕ) : (-1 : ℤ_[2]ˣ) ∈ unitsPlusMinus f :=
  Subgroup.mem_sup_right (Subgroup.mem_zpowers _)

/-- The subgroups `V^(f)` decrease with the level. -/
theorem unitsPlusMinus_antitone : Antitone unitsPlusMinus := fun _ _ hfg ↦
  sup_le_sup_right (unitsPrincipal_antitone 2 hfg) _

/-- `V^(f)` is open: it contains the open subgroup `U^(f)`. -/
theorem isOpen_unitsPlusMinus (f : ℕ) : IsOpen (unitsPlusMinus f : Set ℤ_[2]ˣ) :=
  Subgroup.isOpen_mono (unitsPrincipal_le_unitsPlusMinus f) (isOpen_unitsPrincipal 2 f)

/-- `V^(f)` is closed, being an open subgroup. -/
theorem isClosed_unitsPlusMinus (f : ℕ) : IsClosed (unitsPlusMinus f : Set ℤ_[2]ˣ) :=
  (unitsPlusMinus f).isClosed_of_isOpen (isOpen_unitsPlusMinus f)

/-- Every element of `V^(f)` squares into `U^(f+1)`, for `f ≥ 1`. -/
theorem sq_mem_unitsPrincipal_succ_of_mem_unitsPlusMinus {f : ℕ} (hf : 0 < f) {x : ℤ_[2]ˣ}
    (hx : x ∈ unitsPlusMinus f) : x ^ 2 ∈ unitsPrincipal 2 (f + 1) := by
  rcases mem_unitsPlusMinus_iff.mp hx with hx | hx
  · simpa only [pow_one] using pow_pow_mem_unitsPrincipal hf hx 1
  · simpa only [pow_one, neg_sq] using pow_pow_mem_unitsPrincipal hf hx 1

/-! ### The decomposition `ℤ_2ˣ = {±1} × U^(2)` -/

/-- `ℤ_2ˣ = {±1} · U^(2)`: every dyadic unit is `≡ ±1 mod 4`. -/
@[simp]
theorem unitsPlusMinus_two : unitsPlusMinus 2 = ⊤ :=
  top_unique fun u _ ↦ mem_unitsPlusMinus_iff.mpr <| by
    rw [neg_mem_unitsPrincipal_two_two_iff]
    exact em _

/-- `{±1} ⊓ U^(f) = 1` for `f ≥ 2`: the two factors of `ℤ_2ˣ = {±1} × U^(2)` meet trivially. -/
theorem disjoint_unitsPrincipal_zpowers_neg_one {f : ℕ} (hf : 2 ≤ f) :
    Disjoint (unitsPrincipal 2 f) (Subgroup.zpowers (-1 : ℤ_[2]ˣ)) := by
  refine Subgroup.disjoint_def.mpr fun hx hx' ↦ ?_
  rcases (Subgroup.mem_zpowers_neg_one_iff PadicInt.units_neg_one_ne_one).mp hx' with rfl | rfl
  · rfl
  · exact absurd (neg_one_mem_unitsPrincipal_two_iff.mp hx) (by omega)

/-! ### Indices and levels of `V^(f)` -/

/-- `V^(f) ⊓ U^(2) = U^(f)` for `f ≥ 2`: the even part of `V^(f)` is `U^(f)`. -/
theorem unitsPlusMinus_inf_unitsPrincipal_two {f : ℕ} (hf : 2 ≤ f) :
    unitsPlusMinus f ⊓ unitsPrincipal 2 2 = unitsPrincipal 2 f := by
  refine le_antisymm (fun x hx ↦ ?_)
    (le_inf (unitsPrincipal_le_unitsPlusMinus f) (unitsPrincipal_antitone 2 hf))
  obtain ⟨hxV, hx2⟩ := Subgroup.mem_inf.mp hx
  rcases mem_unitsPlusMinus_iff.mp hxV with h | h
  · exact h
  · exact absurd hx2 (neg_mem_unitsPrincipal_two_two_iff.mp (unitsPrincipal_antitone 2 hf h))

/-- `[V^(f) : U^(f)] = 2` for `f ≥ 2`: `V^(f) = U^(f) ∪ -U^(f)`. -/
theorem relIndex_unitsPrincipal_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) :
    (unitsPrincipal 2 f).relIndex (unitsPlusMinus f) = 2 := by
  refine Subgroup.relIndex_eq_two_iff_exists_notMem_and.mpr ⟨-1, neg_one_mem_unitsPlusMinus f,
    fun h ↦ absurd (neg_one_mem_unitsPrincipal_two_iff.mp h) (by omega), fun b hb ↦ ?_⟩
  rw [mul_neg_one]
  exact (mem_unitsPlusMinus_iff.mp hb).symm

/-- `[V^(f) : U^(f+1)] = 4` for `f ≥ 2`. -/
theorem relIndex_unitsPrincipal_succ_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) :
    (unitsPrincipal 2 (f + 1)).relIndex (unitsPlusMinus f) = 4 := by
  rw [← Subgroup.relIndex_mul_relIndex _ _ _ (unitsPrincipal_antitone 2 (Nat.le_succ f))
    (unitsPrincipal_le_unitsPlusMinus f), relIndex_unitsPrincipal_unitsPlusMinus hf,
    relIndex_unitsPrincipal 2 (by omega) 1]
  norm_num

/-- `[ℤ_2ˣ : V^(f)] = 2 ^ (f - 2)` for `f ≥ 2`. -/
theorem index_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) : (unitsPlusMinus f).index = 2 ^ (f - 2) := by
  have := Subgroup.relIndex_mul_index (unitsPrincipal_le_unitsPlusMinus f)
  rw [relIndex_unitsPrincipal_unitsPlusMinus hf, index_unitsPrincipal_two] at this
  -- `2 * [ℤ_2ˣ : V^(f)] = 2 ^ (f - 1) = 2 * 2 ^ (f - 2)`
  refine Nat.eq_of_mul_eq_mul_left two_pos (this.trans ?_)
  rw [← pow_succ']
  congr 1
  omega

instance (f : ℕ) : (unitsPlusMinus f).FiniteIndex :=
  Subgroup.finiteIndex_of_le (unitsPrincipal_le_unitsPlusMinus f)

/-- The level of `V^(f)` is determined by the subgroup, for `f ≥ 2`. -/
theorem unitsPlusMinus_inj {f g : ℕ} (hf : 2 ≤ f) (hg : 2 ≤ g) :
    unitsPlusMinus f = unitsPlusMinus g ↔ f = g := by
  refine ⟨fun h ↦ ?_, fun h ↦ h ▸ rfl⟩
  rw [← unitsPrincipal_inj (p := 2) (by omega) (by omega),
    ← unitsPlusMinus_inf_unitsPrincipal_two hf, ← unitsPlusMinus_inf_unitsPrincipal_two hg, h]

/-! ### The four families are distinct -/

/-- `U^(f) ≠ V^(g)` for `f ≥ 2`: `-1 ∈ V^(g)` but `-1 ∉ U^(f)`. -/
theorem unitsPrincipal_ne_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) (g : ℕ) :
    unitsPrincipal 2 f ≠ unitsPlusMinus g := fun h ↦
  absurd (neg_one_mem_unitsPrincipal_two_iff.mp (h ▸ neg_one_mem_unitsPlusMinus g)) (by omega)

/-- `U^(f) ≠ {±1}` for `f ≥ 2`. -/
theorem unitsPrincipal_ne_zpowers_neg_one {f : ℕ} (hf : 2 ≤ f) :
    unitsPrincipal 2 f ≠ Subgroup.zpowers (-1 : ℤ_[2]ˣ) := fun h ↦
  absurd (neg_one_mem_unitsPrincipal_two_iff.mp (h ▸ Subgroup.mem_zpowers _)) (by omega)

/-- `V^(f) ≠ {±1}`: `V^(f)` contains a nontrivial principal unit group. -/
theorem unitsPlusMinus_ne_zpowers_neg_one (f : ℕ) :
    unitsPlusMinus f ≠ Subgroup.zpowers (-1 : ℤ_[2]ˣ) := fun h ↦
  unitsPrincipal_ne_bot 2 (max f 2) <|
    (disjoint_unitsPrincipal_zpowers_neg_one (le_max_right f 2)).eq_bot_of_le <|
      h ▸ (unitsPrincipal_antitone 2 (le_max_left f 2)).trans (unitsPrincipal_le_unitsPlusMinus f)

/-- `U^(f) ≠ U^[g]` for `f ≥ 2`: the generator `u ≡ -1 mod 4` of `U^[g]` lies outside
`1 + 4ℤ_2`. -/
theorem unitsPrincipal_ne_topologicalClosure_zpowers {f : ℕ} (hf : 2 ≤ f) {u : ℤ_[2]ˣ}
    (hu : -u ∈ unitsPrincipal 2 2) :
    unitsPrincipal 2 f ≠ (Subgroup.zpowers u).topologicalClosure := fun h ↦
  notMem_unitsPrincipal_two_of_neg_mem (le_refl 2) hu <|
    unitsPrincipal_antitone 2 hf <| h ▸ Subgroup.le_topologicalClosure _ (Subgroup.mem_zpowers u)

/-- `V^(f) ≠ U^[g]`: `-1 ∈ V^(f)` but `-1 ∉ U^[g]`. -/
theorem unitsPlusMinus_ne_topologicalClosure_zpowers (f : ℕ) {g : ℕ} (hg : 2 ≤ g) {u : ℤ_[2]ˣ}
    (hu : -u ∈ unitsPrincipal 2 g) (hu' : -u ∉ unitsPrincipal 2 (g + 1)) :
    unitsPlusMinus f ≠ (Subgroup.zpowers u).topologicalClosure := fun h ↦
  neg_one_notMem_topologicalClosure_zpowers_two hg hu hu' (h ▸ neg_one_mem_unitsPlusMinus f)

/-- `{±1} ≠ U^[g]`: `-1 ∉ U^[g]`. -/
theorem zpowers_neg_one_ne_topologicalClosure_zpowers {g : ℕ} (hg : 2 ≤ g) {u : ℤ_[2]ˣ}
    (hu : -u ∈ unitsPrincipal 2 g) (hu' : -u ∉ unitsPrincipal 2 (g + 1)) :
    Subgroup.zpowers (-1 : ℤ_[2]ˣ) ≠ (Subgroup.zpowers u).topologicalClosure := fun h ↦
  neg_one_notMem_topologicalClosure_zpowers_two hg hu hu' (h ▸ Subgroup.mem_zpowers _)

/-! ### The classification -/

/-- A nontrivial subgroup of `ℤ_2ˣ` meeting `1 + 4ℤ_2` trivially is `{±1}`: every element squares
into the even part. -/
theorem eq_zpowers_neg_one_of_inf_unitsPrincipal_two_eq_bot {A : Subgroup ℤ_[2]ˣ} (hA : A ≠ ⊥)
    (h : A ⊓ unitsPrincipal 2 2 = ⊥) : A = Subgroup.zpowers (-1) := by
  have hpm : ∀ a ∈ A, a = 1 ∨ a = -1 := by
    intro a ha
    have hsq : a ^ 2 ∈ A ⊓ unitsPrincipal 2 2 :=
      Subgroup.mem_inf.mpr ⟨A.pow_mem ha 2, unitsPrincipal_antitone 2 (by norm_num)
        (sq_mem_unitsPrincipal_succ_of_mem_unitsPlusMinus two_pos
          (unitsPlusMinus_two ▸ Subgroup.mem_top a))⟩
    rw [h, Subgroup.mem_bot, Units.ext_iff, Units.val_pow_eq_pow_val, Units.val_one,
      sq_eq_one_iff] at hsq
    rcases hsq with h1 | h1
    · exact Or.inl (Units.ext h1)
    · exact Or.inr (Units.ext (by rw [Units.val_neg, Units.val_one]; exact h1))
  obtain ⟨a, haA, ha1⟩ := A.bot_or_exists_ne_one.resolve_left hA
  have hneg : (-1 : ℤ_[2]ˣ) ∈ A := by
    rcases hpm a haA with rfl | rfl
    · exact (ha1 rfl).elim
    · exact haA
  refine le_antisymm (fun a ha ↦ ?_) (Subgroup.zpowers_le.mpr hneg)
  rcases hpm a ha with rfl | rfl
  · exact one_mem _
  · exact Subgroup.mem_zpowers _

/-- A subgroup of `ℤ_2ˣ` containing `-1` with even part `U^(f)` is `V^(f)`. -/
theorem eq_unitsPlusMinus_of_inf_unitsPrincipal_two_eq {A : Subgroup ℤ_[2]ˣ} {f : ℕ}
    (h : A ⊓ unitsPrincipal 2 2 = unitsPrincipal 2 f) (h1 : (-1 : ℤ_[2]ˣ) ∈ A) :
    A = unitsPlusMinus f := by
  refine le_antisymm (fun a ha ↦ ?_) (unitsPlusMinus_le_iff.mpr ⟨h ▸ inf_le_left, h1⟩)
  rw [mem_unitsPlusMinus_iff, ← h]
  by_cases h2 : a ∈ unitsPrincipal 2 2
  · exact Or.inl (Subgroup.mem_inf.mpr ⟨ha, h2⟩)
  · refine Or.inr (Subgroup.mem_inf.mpr ⟨?_, neg_mem_unitsPrincipal_two_two_iff.mpr h2⟩)
    simpa using A.mul_mem h1 ha

/-- A closed subgroup of `ℤ_2ˣ` with even part `U^(f)`, not containing `-1` and not contained in
`1 + 4ℤ_2`, is the twisted subgroup `U^[g]` with `f = g + 1`: it is generated by `-1 + 2 ^ g`. -/
theorem exists_eq_topologicalClosure_zpowers_of_inf_unitsPrincipal_two_eq {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) {f : ℕ} (h : A ⊓ unitsPrincipal 2 2 = unitsPrincipal 2 f)
    (h1 : (-1 : ℤ_[2]ˣ) ∉ A) {a : ℤ_[2]ˣ} (ha : a ∈ A) (ha2 : a ∉ unitsPrincipal 2 2) :
    ∃ (g : ℕ) (u : ℤ_[2]ˣ), f = g + 1 ∧ 2 ≤ g ∧ (u : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ g ∧
      A = (Subgroup.zpowers u).topologicalClosure := by
  have hneg : -a ∈ unitsPrincipal 2 2 := neg_mem_unitsPrincipal_two_two_iff.mpr ha2
  -- `-a ≠ 1` has an exact level `g`, and `g ≥ 2` since `-a ∈ U^(2)`
  obtain ⟨g, hg, hg'⟩ := exists_mem_unitsPrincipal_and_notMem_succ (p := 2) (u := -a)
    fun h ↦ h1 (neg_eq_iff_eq_neg.mp h ▸ ha)
  have hg2 : 2 ≤ g := by
    by_contra hlt
    exact hg' (unitsPrincipal_antitone 2 (by omega) hneg)
  -- `a² = (-a)²` lies in the even part `U^(f)` and has exact level `g + 1`, so `f ≤ g + 1`
  have hsq : a ^ 2 ∈ unitsPrincipal 2 f := by
    rw [← h]
    refine Subgroup.mem_inf.mpr ⟨A.pow_mem ha 2, ?_⟩
    rw [← neg_sq]
    exact (unitsPrincipal 2 2).pow_mem hneg 2
  have hfg : f ≤ g + 1 := by
    by_contra hlt
    have := pow_pow_notMem_unitsPrincipal (p := 2) (by omega) (fun _ ↦ hg2) hg hg' 1
    rw [pow_one, neg_sq] at this
    exact this (unitsPrincipal_antitone 2 (by omega) hsq)
  -- `-a ∉ U^(f)`, since otherwise `-1 = (-a) * a⁻¹ ∈ A`; so `g < f`
  have hnf : -a ∉ unitsPrincipal 2 f := fun hmem ↦ h1 (by
    have hmem' : -a ∈ A ⊓ unitsPrincipal 2 2 := by rw [h]; exact hmem
    have := A.mul_mem (Subgroup.mem_inf.mp hmem').1 (A.inv_mem ha)
    rwa [neg_mul, mul_inv_cancel] at this)
  have hgf : g < f := lt_of_not_ge fun hle ↦ hnf (unitsPrincipal_antitone 2 hle hg)
  obtain rfl : f = g + 1 := by omega
  obtain ⟨u, hu⟩ := exists_val_eq_neg_one_add_two_pow (by omega : 1 ≤ g)
  refine ⟨g, u, rfl, hg2, hu, ?_⟩
  rw [← (topologicalClosure_zpowers_two_eq_iff hg2 hg2 hg hg'
    (neg_mem_unitsPrincipal_two_of_val_eq hu) (neg_notMem_unitsPrincipal_two_succ_of_val_eq hu)).mpr
    rfl]
  -- `A = closure ⟨a⟩`: both are `U^(g+1) ∪ a U^(g+1)`
  refine le_antisymm (fun x hx ↦ ?_)
    (Subgroup.topologicalClosure_minimal _ (Subgroup.zpowers_le.mpr ha) hA)
  rw [mem_topologicalClosure_zpowers_two_iff hg2 hg hg', ← h]
  by_cases hx2 : x ∈ unitsPrincipal 2 2
  · exact Or.inl (Subgroup.mem_inf.mpr ⟨hx, hx2⟩)
  · refine Or.inr (Subgroup.mem_inf.mpr ⟨A.mul_mem (A.inv_mem ha) hx, ?_⟩)
    have := (unitsPrincipal 2 2).mul_mem ((unitsPrincipal 2 2).inv_mem hneg)
      (neg_mem_unitsPrincipal_two_two_iff.mpr hx2)
    rwa [inv_neg, neg_mul_neg] at this

/-- **Labute's classification of the closed subgroups of `ℤ_2ˣ`.** Every nontrivial closed
subgroup of `ℤ_2ˣ` is a principal unit group `U^(f)` with `f ≥ 2`, a subgroup
`V^(f) = {±1} × U^(f)` with `f ≥ 2`, the subgroup `{±1}`, or a twisted subgroup `U^[f]` with
`f ≥ 2`, generated by `-1 + 2 ^ f`. The four families are pairwise distinct and faithfully indexed
by `f`: `unitsPrincipal_inj`, `unitsPlusMinus_inj`, `topologicalClosure_zpowers_two_eq_iff` and
the `ne` lemmas above. -/
theorem closedSubgroup_units_two_classification {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) (hA' : A ≠ ⊥) :
    (∃ f : ℕ, 2 ≤ f ∧ A = unitsPrincipal 2 f) ∨
      (∃ f : ℕ, 2 ≤ f ∧ A = unitsPlusMinus f) ∨
      A = Subgroup.zpowers (-1 : ℤ_[2]ˣ) ∨
      ∃ (f : ℕ) (u : ℤ_[2]ˣ), 2 ≤ f ∧ (u : ℤ_[2]) = -1 + (2 : ℤ_[2]) ^ f ∧
        A = (Subgroup.zpowers u).topologicalClosure := by
  -- the even part `A ⊓ U^(2)` is a closed subgroup of `1 + 4ℤ_2`, so trivial or some `U^(f)`
  rcases eq_or_ne (A ⊓ unitsPrincipal 2 2) ⊥ with h0 | h0
  · exact Or.inr (Or.inr (Or.inl (eq_zpowers_neg_one_of_inf_unitsPrincipal_two_eq_bot hA' h0)))
  obtain ⟨f, hf, h⟩ := exists_eq_unitsPrincipal_of_isClosed two_pos (fun _ ↦ le_rfl)
    (hA.inter (isClosed_unitsPrincipal 2 2)) inf_le_right h0
  by_cases h1 : (-1 : ℤ_[2]ˣ) ∈ A
  · exact Or.inr (Or.inl ⟨f, hf, eq_unitsPlusMinus_of_inf_unitsPrincipal_two_eq h h1⟩)
  by_cases hle : A ≤ unitsPrincipal 2 2
  · exact Or.inl ⟨f, hf, by rw [← h, inf_eq_left.mpr hle]⟩
  obtain ⟨a, ha, ha2⟩ := IsConcreteLE.not_le_iff_exists.mp hle
  obtain ⟨g, u, -, hg, hu, hAu⟩ :=
    exists_eq_topologicalClosure_zpowers_of_inf_unitsPrincipal_two_eq hA h h1 ha ha2
  exact Or.inr (Or.inr (Or.inr ⟨g, u, hg, hu, hAu⟩))

/-! ### Procyclicity -/

/-- A closed subgroup of `ℤ_2ˣ` not containing `-1` is **procyclic**: it is `1`, a principal unit
group `U^(f)`, or a twisted subgroup `U^[f]`, each topologically generated by one element. -/
theorem exists_topologicalClosure_zpowers_eq_of_isClosed_of_neg_one_notMem {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) (h1 : (-1 : ℤ_[2]ˣ) ∉ A) :
    ∃ u : ℤ_[2]ˣ, (Subgroup.zpowers u).topologicalClosure = A := by
  rcases eq_or_ne A ⊥ with rfl | hA'
  · refine ⟨1, le_antisymm ?_ bot_le⟩
    rw [Subgroup.zpowers_one_eq_bot]
    exact Subgroup.topologicalClosure_minimal _ le_rfl
      (by rw [Subgroup.coe_bot]; exact isClosed_singleton)
  rcases closedSubgroup_units_two_classification hA hA' with ⟨f, hf, rfl⟩ | ⟨f, hf, rfl⟩ | rfl |
    ⟨f, u, hf, hu, rfl⟩
  · exact exists_topologicalClosure_zpowers_eq_unitsPrincipal (by omega) fun _ ↦ hf
  · exact (h1 (neg_one_mem_unitsPlusMinus f)).elim
  · exact (h1 (Subgroup.mem_zpowers _)).elim
  · exact ⟨u, rfl⟩

/-- `V^(f)` is **not procyclic** for `f ≥ 2`: `[V^(f) : U^(f+1)] = 4`, while a closed subgroup
`closure ⟨u⟩` with `u² ∈ U^(f+1)` is contained in `U^(f+1) ∪ u U^(f+1)`. -/
theorem not_exists_topologicalClosure_zpowers_eq_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) :
    ¬ ∃ u : ℤ_[2]ˣ, (Subgroup.zpowers u).topologicalClosure = unitsPlusMinus f := by
  rintro ⟨u, hu⟩
  have hu' : u ∈ unitsPlusMinus f :=
    hu ▸ Subgroup.le_topologicalClosure _ (Subgroup.mem_zpowers u)
  have h2 : (unitsPrincipal 2 (f + 1)).relIndex (unitsPlusMinus f) ∣ 2 := by
    refine Subgroup.relIndex_dvd_two_iff'.mpr
      ⟨u⁻¹, (unitsPlusMinus f).inv_mem hu', fun b hb ↦ ?_⟩
    rw [← hu] at hb
    exact (mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers u _
      (isClosed_unitsPrincipal 2 (f + 1))
      (sq_mem_unitsPrincipal_succ_of_mem_unitsPlusMinus (by omega) hu') hb).symm
  rw [relIndex_unitsPrincipal_succ_unitsPlusMinus hf] at h2
  norm_num at h2

/-! ### The subgroup of squares and the index `(A : A²)` -/

/-- `(V^(f))² = U^(f+1)` for `f ≥ 2`: the squares of `{±1} × U^(f)` are the squares of `U^(f)`. -/
@[simp]
theorem map_powMonoidHom_two_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) :
    (unitsPlusMinus f).map (powMonoidHom 2) = unitsPrincipal 2 (f + 1) := by
  rw [unitsPlusMinus_def, Subgroup.map_sup, map_powMonoidHom_unitsPrincipal (by omega) fun _ ↦ hf,
    Subgroup.map_powMonoidHom_two_zpowers_neg_one, sup_bot_eq]

/-- `(V^(f) : (V^(f))²) = 4` for `f ≥ 2`. -/
theorem relIndex_map_powMonoidHom_two_unitsPlusMinus {f : ℕ} (hf : 2 ≤ f) :
    ((unitsPlusMinus f).map (powMonoidHom 2)).relIndex (unitsPlusMinus f) = 4 := by
  rw [map_powMonoidHom_two_unitsPlusMinus hf]
  exact relIndex_unitsPrincipal_succ_unitsPlusMinus hf

/-- **The table of `(A : A²)`.** A nontrivial closed subgroup `A ≤ ℤ_2ˣ` has `(A : A²) = 2`
unless it is some `V^(f)` with `f ≥ 2`: the three procyclic families `U^(f)`, `{±1}` and `U^[f]`
have `(A : A²) = 2`, while `V^(f)` has `(A : A²) = 4`. -/
theorem relIndex_map_powMonoidHom_two_eq_two_or_exists_eq_unitsPlusMinus {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) (hA' : A ≠ ⊥) :
    (A.map (powMonoidHom 2)).relIndex A = 2 ∨ ∃ f : ℕ, 2 ≤ f ∧ A = unitsPlusMinus f := by
  rcases closedSubgroup_units_two_classification hA hA' with ⟨f, hf, rfl⟩ | ⟨f, hf, rfl⟩ | rfl |
    ⟨f, u, hf, hu, rfl⟩
  · exact Or.inl (relIndex_map_powMonoidHom_unitsPrincipal (by omega) fun _ ↦ hf)
  · exact Or.inr ⟨f, hf, rfl⟩
  · exact Or.inl (Subgroup.relIndex_map_powMonoidHom_two_zpowers_neg_one
      PadicInt.units_neg_one_ne_one)
  · exact Or.inl (relIndex_map_powMonoidHom_two_topologicalClosure_zpowers_two hf
      (neg_mem_unitsPrincipal_two_of_val_eq hu) (neg_notMem_unitsPrincipal_two_succ_of_val_eq hu))

/-- `(A : A²) = 4` exactly for the subgroups `A = V^(f)`, `f ≥ 2`, among the closed subgroups of
`ℤ_2ˣ`. -/
theorem relIndex_map_powMonoidHom_two_eq_four_iff {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) :
    (A.map (powMonoidHom 2)).relIndex A = 4 ↔ ∃ f : ℕ, 2 ≤ f ∧ A = unitsPlusMinus f := by
  refine ⟨fun h ↦ ?_, ?_⟩
  · rcases eq_or_ne A ⊥ with rfl | hA'
    · rw [Subgroup.relIndex_eq_one.mpr bot_le] at h
      omega
    exact (relIndex_map_powMonoidHom_two_eq_two_or_exists_eq_unitsPlusMinus hA hA').resolve_left
      (by omega)
  · rintro ⟨f, hf, rfl⟩
    exact relIndex_map_powMonoidHom_two_unitsPlusMinus hf

/-- `(A : A²) = 1` exactly for the trivial subgroup, among the closed subgroups of `ℤ_2ˣ`: every
nontrivial closed subgroup has a non-square. -/
theorem relIndex_map_powMonoidHom_two_eq_one_iff {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) :
    (A.map (powMonoidHom 2)).relIndex A = 1 ↔ A = ⊥ := by
  refine ⟨fun h ↦ by_contra fun hA' ↦ ?_, fun h ↦ h ▸ Subgroup.relIndex_eq_one.mpr bot_le⟩
  rcases relIndex_map_powMonoidHom_two_eq_two_or_exists_eq_unitsPlusMinus hA hA' with
    h2 | ⟨f, hf, rfl⟩
  · omega
  · rw [relIndex_map_powMonoidHom_two_unitsPlusMinus hf] at h
    omega

/-- **`(A : A²) ∈ {1, 2, 4}` for every closed subgroup `A ≤ ℤ_2ˣ`.** -/
theorem relIndex_map_powMonoidHom_two_eq_one_or_two_or_four {A : Subgroup ℤ_[2]ˣ}
    (hA : IsClosed (A : Set ℤ_[2]ˣ)) :
    (A.map (powMonoidHom 2)).relIndex A = 1 ∨ (A.map (powMonoidHom 2)).relIndex A = 2 ∨
      (A.map (powMonoidHom 2)).relIndex A = 4 := by
  rcases eq_or_ne A ⊥ with rfl | hA'
  · exact Or.inl (Subgroup.relIndex_eq_one.mpr bot_le)
  rcases relIndex_map_powMonoidHom_two_eq_two_or_exists_eq_unitsPlusMinus hA hA' with
    h2 | ⟨f, hf, rfl⟩
  · exact Or.inr (Or.inl h2)
  · exact Or.inr (Or.inr (relIndex_map_powMonoidHom_two_unitsPlusMinus hf))

end TauCeti
