/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.DirichletDensity
public import TauCeti.NumberTheory.Chebotarev.FrobeniusPrimeSet
import TauCeti.NumberTheory.Chebotarev.Density.Abelian
import TauCeti.Algebra.Group.ConjFinite
import TauCeti.NumberTheory.Chebotarev.Density.FixedField

/-!
# The Chebotarev density theorem

Let `L / K` be a finite Galois extension of number fields with group `G`, and let `C` be a
conjugacy class of `G`. The primes of `𝓞 K` whose Frobenius in `L` lies in `C` have Dirichlet
density `#C / #G`.

## Main results

* `NumberField.Chebotarev.hasDirichletDensity_frobeniusPrimeSet`: the Chebotarev density theorem,
  for Dirichlet density.
* `NumberField.Chebotarev.hasDirichletDensity_splitCompletely`: the primes that split completely in
  `L` have Dirichlet density `1 / #Gal(L/K)`.
* `NumberField.Chebotarev.infinite_frobeniusPrimeSet`: every conjugacy class of `Gal(L/K)` is the
  Frobenius class of infinitely many primes of `𝓞 K`.
* `NumberField.Chebotarev.hasDirichletDensity_iff_of_finite_symmDiff_frobeniusPrimeSet`: a set of
  primes differing from a Frobenius fibre in finitely many primes has Dirichlet density `δ` exactly
  when `δ = #C / #G`.

## References

* R. Sharifi, *Algebraic Number Theory*, Theorem 7.2.2.
* J. Neukirch, *Algebraic Number Theory*, Chapter VII, §13.
-/

public section

open scoped NumberField symmDiff

namespace NumberField.Chebotarev

variable (K L : Type*) [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]
  [IsGalois K L]

/-- **The Chebotarev density theorem.** For a finite Galois extension `L / K` of number fields
and a conjugacy class `C` of `Gal(L/K)`, the primes of `𝓞 K` whose Frobenius in `L` lies in `C`
have Dirichlet density `#C / #Gal(L/K)`. -/
theorem hasDirichletDensity_frobeniusPrimeSet (C : ConjClasses (L ≃ₐ[K] L)) :
    NumberField.Set.HasDirichletDensity (frobeniusPrimeSet K L C)
      ((Nat.card C.carrier : ℝ) / (Nat.card (L ≃ₐ[K] L) : ℝ)) := by
  obtain ⟨σ, rfl⟩ := ConjClasses.mk_surjective C
  refine hasDirichletDensity_frobeniusPrimeSet_of_fixedField _ σ ConjClasses.mem_carrier_mk ?_
  -- `Gal(L / L ^ ⟨σ⟩)` is generated by `σ`, so it is cyclic and hence abelian.
  have : IsCyclic (L ≃ₐ[IntermediateField.fixedField (Subgroup.zpowers σ)] L) :=
    isCyclic_iff_exists_zpowers_eq_top.mpr ⟨_, AlgEquiv.zpowers_toFixedFieldAlgEquiv_eq_top σ⟩
  exact AlgEquiv.card_algEquiv_fixedField_zpowers σ ▸ hasDirichletDensity_abelianFrobenius _ L
    IsCyclic.commGroup.mul_comm σ.toFixedFieldAlgEquiv

/-- **The completely split primes have density `1 / #Gal(L/K)`.** The primes of `𝓞 K` that split
completely in `L`, whose Frobenius class is trivial, have Dirichlet density `1 / #Gal(L/K)`. This
is `hasDirichletDensity_frobeniusPrimeSet` for the class of the identity. The same density, in the
form `1 / [L : K]`, is `hasDirichletDensity_frobeniusPrimeSet_one`, which is proved directly by
counting primes and is used before this theorem is available. -/
theorem hasDirichletDensity_splitCompletely :
    NumberField.Set.HasDirichletDensity (frobeniusPrimeSet K L 1)
      (1 / (Nat.card (L ≃ₐ[K] L) : ℝ)) := by
  simpa [ConjClasses.one_eq_mk_one] using hasDirichletDensity_frobeniusPrimeSet K L 1

/-- **Every Frobenius class occurs infinitely often.** For every conjugacy class `C` of
`Gal(L/K)`, infinitely many primes of `𝓞 K` are unramified in `L` with Frobenius class `C`. -/
theorem infinite_frobeniusPrimeSet (C : ConjClasses (L ≃ₐ[K] L)) :
    (frobeniusPrimeSet K L C).Infinite :=
  (hasDirichletDensity_frobeniusPrimeSet K L C).infinite
    (C.card_carrier_div_card_ne_zero (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))

variable {K L} in
/-- **Chebotarev density up to finitely many primes.** A set `S` of primes of `𝓞 K` that differs
from the Frobenius fibre of a conjugacy class `C` of `Gal(L/K)` in only finitely many primes has
Dirichlet density `δ` if and only if `δ = #C / #Gal(L/K)`. -/
theorem hasDirichletDensity_iff_of_finite_symmDiff_frobeniusPrimeSet
    {S : Set (IsDedekindDomain.HeightOneSpectrum (𝓞 K))} {C : ConjClasses (L ≃ₐ[K] L)} {δ : ℝ}
    (hS : (S ∆ frobeniusPrimeSet K L C).Finite) :
    NumberField.Set.HasDirichletDensity S δ ↔
      δ = (Nat.card C.carrier : ℝ) / (Nat.card (L ≃ₐ[K] L) : ℝ) := by
  have hC := hasDirichletDensity_frobeniusPrimeSet K L C
  rw [NumberField.Set.hasDirichletDensity_iff_of_finite_symmDiff hS]
  exact ⟨fun h ↦ h.unique hC, fun h ↦ h ▸ hC⟩

end NumberField.Chebotarev
