/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Module.Projective
public import Mathlib.LinearAlgebra.Dimension.Constructions
public import Mathlib.LinearAlgebra.FreeModule.StrongRankCondition
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
public import Mathlib.RingTheory.Finiteness.Cardinality
public import TauCeti.LinearAlgebra.Multilinear.Span

/-!
# Fitting ideals

Let `M` be a finite module over a commutative ring `R`, and choose a surjection `φ : F → M` from a
free module of finite rank `n`. The `k`-th Fitting ideal of `M` is the ideal generated by the
`(n - k) × (n - k)` minors of the relations `ker φ`. It does not depend on the choice of `φ`.
For a finite module, `Fitt_k(M)` cuts out the locus of primes at which `M` needs more than `k`
generators; for a syntomic relative curve of dimension one, the first Fitting ideal of its
module of differentials cuts out its singular locus.

To make the independence of the presentation transparent, the minors are formed with arbitrary
linear functionals rather than with coordinates. For a submodule `N` of a module `F`, the ideal
`N.minorsIdeal p` is generated by the determinants `det (f j (v i))` of `p` linear functionals
`f j` on `F` evaluated at `p` elements `v i` of `N`. For `F = Fin n → R`, taking coordinate
functionals shows that every `p × p` minor of a matrix whose columns lie in `N` is such a
determinant. Conversely, by the Cauchy–Binet formula, every such determinant is a combination of
these minors. This formulation is manifestly invariant under linear equivalences of `F`.

The independence of the presentation reduces to two computations. Adjoining a free summand `R` to
both `F` and `N` shifts the minors ideals by one. Two
surjections `φ : F → M` and `ψ : F' → M` both factor through `φ + ψ : F × F' → M`, whose kernel
is carried by a shear automorphism of `F × F'` onto `ker φ × F'`.

## Main definitions

* `Submodule.minorsIdeal N p`: the ideal generated by the `p × p` determinants of linear
  functionals on `F` evaluated at elements of `N`.
* `TauCeti.fittingIdeal R M k`: the `k`-th Fitting ideal of the `R`-module `M`.

## Main results

* `Submodule.minorsIdeal_prod_top`: adjoining a free summand of rank `r` shifts the minors ideals
  by `r`.
* `Submodule.minorsIdeal_ker_eq_of_surjective`: the minors ideals of the kernels of two surjections
  from free modules of finite rank onto the same module agree after the shift by the ranks.
* `TauCeti.fittingIdeal_eq_minorsIdeal_ker`: the Fitting ideals may be computed from any
  surjection from a free module of finite rank.
* `TauCeti.fittingIdeal_monotone`: `Fitt₀(M) ≤ Fitt₁(M) ≤ ⋯`.
* `TauCeti.fittingIdeal_le_of_surjective`: Fitting ideals grow along surjections.
* `TauCeti.fittingIdeal_eq_top_of_surjective`: `Fitt_k(M) = ⊤` once `M` is generated by `k`
  elements.
* `TauCeti.fittingIdeal_eq_bot_of_lt_finrank`: a free module of rank `n` has `Fitt_k = ⊥` for
  `k < n`.
* `TauCeti.fittingIdeal_quotient_zero`: `Fitt₀(R ⧸ I) = I`.

## References

* [Stacks Project, Tag 07Z6](https://stacks.math.columbia.edu/tag/07Z6)
* [Stacks Project, Tag 07ZA](https://stacks.math.columbia.edu/tag/07ZA)
-/

public section

noncomputable section

open Function LinearMap Module

namespace Submodule

variable {R F F' G M : Type*} [CommRing R] [AddCommGroup F] [Module R F]
  [AddCommGroup F'] [Module R F'] [AddCommGroup G] [Module R G] [AddCommGroup M] [Module R M]

/-- The ideal of `p × p` minors of a submodule `N` of `F`: the ideal generated by the
determinants `det (f j (v i))` of `p` linear functionals `f j` on `F` evaluated at `p` elements
`v i` of `N`. -/
def minorsIdeal (N : Submodule R F) (p : ℕ) : Ideal R :=
  Ideal.span {r | ∃ (f : Fin p → Dual R F) (v : Fin p → F), (∀ i, v i ∈ N) ∧
    (Matrix.of fun i j ↦ f j (v i)).det = r}

variable {N N' : Submodule R F} {p : ℕ}

/-- Each determinant `det (f j (v i))` with all `v i ∈ N` lies in the ideal of minors. -/
theorem det_mem_minorsIdeal (f : Fin p → Dual R F) {v : Fin p → F} (hv : ∀ i, v i ∈ N) :
    (Matrix.of fun i j ↦ f j (v i)).det ∈ N.minorsIdeal p :=
  Ideal.subset_span ⟨f, v, hv, rfl⟩

/-- The ideal of minors is contained in `I` exactly when all its generating determinants are. -/
theorem minorsIdeal_le_iff {I : Ideal R} :
    N.minorsIdeal p ≤ I ↔ ∀ (f : Fin p → Dual R F) (v : Fin p → F), (∀ i, v i ∈ N) →
      (Matrix.of fun i j ↦ f j (v i)).det ∈ I := by
  refine ⟨fun h f v hv ↦ h (det_mem_minorsIdeal f hv), fun h ↦ Ideal.span_le.2 ?_⟩
  rintro _ ⟨f, v, hv, rfl⟩
  exact h f v hv

/-- The ideal of `0 × 0` minors is the unit ideal. -/
@[simp]
theorem minorsIdeal_zero (N : Submodule R F) : N.minorsIdeal 0 = ⊤ :=
  (Ideal.eq_top_iff_one _).2 <| by
    simpa using det_mem_minorsIdeal (N := N) finZeroElim (v := finZeroElim) finZeroElim

/-- Laplace expansion along the first row: every `(p + 1) × (p + 1)` minor is a combination of
`p × p` minors. -/
theorem minorsIdeal_succ_le (N : Submodule R F) (p : ℕ) :
    N.minorsIdeal (p + 1) ≤ N.minorsIdeal p := by
  refine minorsIdeal_le_iff.2 fun f v hv ↦ ?_
  rw [Matrix.det_succ_row_zero]
  exact sum_mem fun j _ ↦ Ideal.mul_mem_left _ _ <|
    det_mem_minorsIdeal (fun k ↦ f (j.succAbove k)) fun i ↦ hv i.succ

/-- The minors ideals decrease with the size of the minors. -/
theorem minorsIdeal_antitone (N : Submodule R F) : Antitone N.minorsIdeal :=
  antitone_nat_of_succ_le N.minorsIdeal_succ_le

/-- The minors ideals grow with the submodule. -/
theorem minorsIdeal_mono (h : N ≤ N') (p : ℕ) : N.minorsIdeal p ≤ N'.minorsIdeal p :=
  minorsIdeal_le_iff.2 fun f _ hv ↦ det_mem_minorsIdeal f fun i ↦ h (hv i)

/-- The minors ideals can only shrink under a linear map, since functionals pull back. -/
theorem minorsIdeal_map_le (φ : F →ₗ[R] F') (N : Submodule R F) (p : ℕ) :
    (N.map φ).minorsIdeal p ≤ N.minorsIdeal p := by
  refine minorsIdeal_le_iff.2 fun f v hv ↦ ?_
  choose w hw hwv using fun i ↦ mem_map.1 (hv i)
  obtain rfl : v = fun i ↦ φ (w i) := funext fun i ↦ (hwv i).symm
  exact det_mem_minorsIdeal (fun j ↦ f j ∘ₗ φ) hw

/-- The minors ideals are invariant under linear equivalences of the ambient module. -/
@[simp]
theorem minorsIdeal_map_equiv (e : F ≃ₗ[R] F') (N : Submodule R F) (p : ℕ) :
    (N.map (e : F →ₗ[R] F')).minorsIdeal p = N.minorsIdeal p := by
  refine le_antisymm (minorsIdeal_map_le _ _ _) ?_
  calc N.minorsIdeal p = ((N.map (e : F →ₗ[R] F')).map (e.symm : F' →ₗ[R] F)).minorsIdeal p := by
        rw [(map_symm_eq_iff e).2 rfl]
    _ ≤ (N.map (e : F →ₗ[R] F')).minorsIdeal p := minorsIdeal_map_le _ _ _

/-- The minors ideals are invariant under linear equivalences of the ambient module. -/
@[simp]
theorem minorsIdeal_comap_equiv (e : F ≃ₗ[R] F') (N : Submodule R F') (p : ℕ) :
    (N.comap (e : F →ₗ[R] F')).minorsIdeal p = N.minorsIdeal p := by
  rw [comap_equiv_eq_map_symm, minorsIdeal_map_equiv]

/-- The zero submodule has no nonzero minors of positive size. -/
@[simp]
theorem minorsIdeal_bot (p : ℕ) : (⊥ : Submodule R F).minorsIdeal (p + 1) = ⊥ := by
  refine le_bot_iff.1 (minorsIdeal_le_iff.2 fun f v hv ↦ ?_)
  rw [Ideal.mem_bot]
  exact Matrix.det_eq_zero_of_row_eq_zero 0 fun j ↦ by simp [(mem_bot R).1 (hv 0)]

/-- A determinant `det (f j (w i))` whose rows `w i` lie in `N × 0` except for at most one row
equal to `(0, 1)` lies in the minors ideal of `N` of one size less. -/
private theorem det_mem_minorsIdeal_of_mem_insert (N : Submodule R F)
    (f : Fin (p + 1) → Dual R (F × R)) {w : Fin (p + 1) → F × R}
    (hw : ∀ i, w i ∈ insert ((0 : F), (1 : R)) (LinearMap.inl R F R '' N)) :
    (Matrix.of fun i j ↦ f j (w i)).det ∈ N.minorsIdeal p := by
  by_cases h : ∃ i₀, w i₀ = (0, 1)
  · obtain ⟨i₀, hi₀⟩ := h
    by_cases h' : ∃ i, i ≠ i₀ ∧ w i = (0, 1)
    · -- Two rows equal to `(0, 1)` make the determinant vanish.
      obtain ⟨i, hi, hwi⟩ := h'
      rw [Matrix.det_zero_of_row_eq hi (by ext j; simp [hwi, hi₀])]
      exact zero_mem _
    · -- Expand along the row `(0, 1)`; the remaining rows lie in `N × 0`.
      push Not at h'
      choose! x hx hxw using fun i (hi : i ≠ i₀) ↦ (hw i).resolve_left (h' i hi)
      rw [Matrix.det_succ_row _ i₀]
      refine sum_mem fun j _ ↦ Ideal.mul_mem_left _ _ ?_
      convert det_mem_minorsIdeal (fun k ↦ f (j.succAbove k) ∘ₗ LinearMap.inl R F R)
        (v := fun k ↦ x (i₀.succAbove k)) fun k ↦ hx _ (Fin.succAbove_ne _ _) using 2
      ext a b
      simp only [Matrix.submatrix_apply, Matrix.of_apply, LinearMap.comp_apply,
        ← hxw _ (Fin.succAbove_ne i₀ a)]
  · -- All rows lie in `N × 0`.
    push Not at h
    choose x hx hxw using fun i ↦ (hw i).resolve_left (h i)
    obtain rfl : w = fun i ↦ LinearMap.inl R F R (x i) := funext fun i ↦ (hxw i).symm
    exact minorsIdeal_succ_le N p (det_mem_minorsIdeal (fun j ↦ f j ∘ₗ LinearMap.inl R F R) hx)

/-- Adjoining a free summand `R` to a submodule and to its ambient module shifts the minors
ideals by one. -/
private theorem minorsIdeal_prod_top_succ (N : Submodule R F) (p : ℕ) :
    (N.prod (⊤ : Submodule R R)).minorsIdeal (p + 1) = N.minorsIdeal p := by
  refine le_antisymm (minorsIdeal_le_iff.2 fun f v hv ↦ ?_) (minorsIdeal_le_iff.2 fun f v hv ↦ ?_)
  · -- The determinant is multilinear in the rows, and `N × R` is spanned by `N × 0` and `(0, 1)`.
    set T : Set (F × R) := insert (0, 1) (LinearMap.inl R F R '' N)
    have hT (i : Fin (p + 1)) : v i ∈ span R T := by
      have hvi : (v i).1 ∈ N := (mem_prod.1 (hv i)).1
      have hsplit : v i = LinearMap.inl R F R (v i).1 + (v i).2 • ((0 : F), (1 : R)) := by
        ext <;> simp
      rw [hsplit]
      exact add_mem (subset_span (Set.mem_insert_of_mem _ ⟨_, hvi, rfl⟩))
        (smul_mem _ _ (subset_span (Set.mem_insert _ _)))
    let μ : MultilinearMap R (fun _ : Fin (p + 1) ↦ F × R) R :=
      Matrix.detRowAlternating.toMultilinearMap.compLinearMap fun _ ↦ LinearMap.pi f
    have hμ (w : Fin (p + 1) → F × R) : μ w = (Matrix.of fun i j ↦ f j (w i)).det := by
      simp only [μ, MultilinearMap.compLinearMap_apply, Matrix.det]
      congr 1
    rw [← hμ]
    refine span_le.2 ?_ (μ.map_mem_span_image_pi (fun _ ↦ T) hT)
    rintro _ ⟨w, hw, rfl⟩
    exact det_mem_minorsIdeal_of_mem_insert N f fun i ↦ hw i trivial
  · -- Border the matrix by the row `(0, 1)` and the functional `snd`.
    convert det_mem_minorsIdeal (N := N.prod ⊤)
      (Fin.cons (LinearMap.snd R F R) fun j ↦ f j ∘ₗ LinearMap.fst R F R)
      (v := Fin.cons ((0 : F), (1 : R)) fun i ↦ ((v i, 0) : F × R))
      (Fin.cases (by simp) fun i ↦ by simpa using hv i) using 1
    rw [Matrix.det_succ_row_zero, Fin.sum_univ_succ]
    simp [Matrix.submatrix]

/-- Adjoining the free summand `Fin r → R` shifts the minors ideals by `r`. -/
private theorem minorsIdeal_prod_top_pi (N : Submodule R F) (r p : ℕ) :
    (N.prod (⊤ : Submodule R (Fin r → R))).minorsIdeal (p + r) = N.minorsIdeal p := by
  induction r generalizing p with
  | zero =>
    let e : (F × (Fin 0 → R)) ≃ₗ[R] F := LinearEquiv.prodUnique
    have he : (N.prod (⊤ : Submodule R (Fin 0 → R))).map (e : (F × (Fin 0 → R)) →ₗ[R] F) = N := by
      ext x
      simp [mem_map_equiv, e]
    rw [Nat.add_zero, ← minorsIdeal_map_equiv e, he]
  | succ r ih =>
    let e : (F × (Fin (r + 1) → R)) ≃ₗ[R] (F × (Fin r → R)) × R :=
      ((LinearEquiv.refl R F).prodCongr (((Fin.consLinearEquiv R fun _ : Fin (r + 1) ↦ R).symm :
        (Fin (r + 1) → R) ≃ₗ[R] R × (Fin r → R)).trans
          (LinearEquiv.prodComm R R (Fin r → R)))).trans (LinearEquiv.prodAssoc R F _ R).symm
    have he : ((N.prod (⊤ : Submodule R (Fin r → R))).prod (⊤ : Submodule R R)).comap
        (e : (F × (Fin (r + 1) → R)) →ₗ[R] (F × (Fin r → R)) × R) =
        N.prod ⊤ := by
      ext ⟨x, y⟩
      simp only [mem_comap, mem_prod, mem_top, and_true]
      simp [e, LinearEquiv.prodCongr_apply, LinearEquiv.prodComm_apply,
        LinearEquiv.prodAssoc]
    rw [← he, minorsIdeal_comap_equiv, ← add_assoc, minorsIdeal_prod_top_succ, ih]

/-- Adjoining a free summand `G` of finite rank shifts the minors ideals by the rank of `G`. -/
theorem minorsIdeal_prod_top [Free R G] [Module.Finite R G] (N : Submodule R F) (p : ℕ) :
    (N.prod (⊤ : Submodule R G)).minorsIdeal (p + finrank R G) = N.minorsIdeal p := by
  nontriviality R
  let e : (F × G) ≃ₗ[R] F × (Fin (finrank R G) → R) :=
    (LinearEquiv.refl R F).prodCongr (finBasis R G).equivFun
  have he : (N.prod (⊤ : Submodule R (Fin (finrank R G) → R))).comap
      (e : (F × G) →ₗ[R] F × (Fin (finrank R G) → R)) = N.prod ⊤ := by
    ext ⟨x, y⟩
    simp [e]
  rw [← he, minorsIdeal_comap_equiv, minorsIdeal_prod_top_pi]

/-- If `ρ : F × G → M` is surjective on `F × 0` and `G` is projective, then a shear
automorphism of `F × G` carries `ker ρ` onto `ker (ρ ∘ inl) × G`. -/
private theorem minorsIdeal_ker_eq_prod_top [Projective R G] (ρ : F × G →ₗ[R] M)
    (hρ : Surjective (ρ ∘ₗ LinearMap.inl R F G)) (p : ℕ) :
    (ker ρ).minorsIdeal p =
      ((ker (ρ ∘ₗ LinearMap.inl R F G)).prod (⊤ : Submodule R G)).minorsIdeal p := by
  obtain ⟨h, hh⟩ :=
    projective_lifting_property (ρ ∘ₗ LinearMap.inl R F G) (ρ ∘ₗ LinearMap.inr R F G) hρ
  let σ : (F × G) ≃ₗ[R] F × G :=
    ((LinearEquiv.prodComm R F G).trans ((LinearEquiv.refl R G).skewProd (.refl R F) h)).trans
      (LinearEquiv.prodComm R G F)
  have hσ (x : F) (y : G) : σ (x, y) = (x + h y, y) := by simp [σ]
  have hρσ (x : F) (y : G) : ρ (x + h y, 0) = ρ (x, y) := by
    have hy : ρ (h y, 0) = ρ (0, y) := by simpa using LinearMap.congr_fun hh y
    rw [← add_zero (0 : G), ← Prod.mk_add_mk, map_add, hy, ← map_add, Prod.mk_add_mk,
      add_zero, zero_add]
  have hker : ker ρ = ((ker (ρ ∘ₗ LinearMap.inl R F G)).prod (⊤ : Submodule R G)).comap
      (σ : (F × G) →ₗ[R] F × G) := by
    ext ⟨x, y⟩
    simp [hσ, hρσ]
  rw [hker, minorsIdeal_comap_equiv]

/-- The minors ideal of the kernel of `φ + ψ : F × F' → M`, for `φ` surjective, is the shifted
minors ideal of the kernel of `φ`. -/
private theorem minorsIdeal_ker_coprod [Free R F'] [Module.Finite R F']
    {φ : F →ₗ[R] M} (hφ : Surjective φ) (ψ : F' →ₗ[R] M) (k : ℕ) :
    (ker (φ.coprod ψ)).minorsIdeal (finrank R F + finrank R F' - k) =
      (ker φ).minorsIdeal (finrank R F - k) := by
  rw [minorsIdeal_ker_eq_prod_top _ (by rwa [coprod_inl]), coprod_inl]
  rcases le_total k (finrank R F) with hk | hk
  · have hsize : finrank R F + finrank R F' - k =
        finrank R F - k + finrank R F' := by omega
    rw [hsize, minorsIdeal_prod_top]
  · rw [Nat.sub_eq_zero_of_le hk, minorsIdeal_zero, eq_top_iff]
    calc ⊤ = ((ker φ).prod (⊤ : Submodule R F')).minorsIdeal (0 + finrank R F') := by
          rw [minorsIdeal_prod_top, minorsIdeal_zero]
      _ ≤ _ := minorsIdeal_antitone _ (by omega)

/-- **Independence of the presentation.** For two surjections `φ : F → M` and `ψ : F' → M` from
free modules of finite rank, the minors ideals of their kernels of sizes `rank F - k` and
`rank F' - k` agree. -/
theorem minorsIdeal_ker_eq_of_surjective [Free R F] [Module.Finite R F] [Free R F']
    [Module.Finite R F'] {φ : F →ₗ[R] M} {ψ : F' →ₗ[R] M} (hφ : Surjective φ)
    (hψ : Surjective ψ) (k : ℕ) :
    (ker φ).minorsIdeal (finrank R F - k) = (ker ψ).minorsIdeal (finrank R F' - k) := by
  have hswap : (ker (φ.coprod ψ)).comap (LinearEquiv.prodComm R F' F : (F' × F) →ₗ[R] F × F') =
      ker (ψ.coprod φ) := by
    ext ⟨x, y⟩
    simp [add_comm]
  rw [← minorsIdeal_ker_coprod hφ ψ, ← minorsIdeal_ker_coprod hψ φ, ← hswap,
    minorsIdeal_comap_equiv, add_comm (finrank R F')]

end Submodule

namespace Ideal

variable {R : Type*} [CommRing R]

/-- The ideal of `1 × 1` minors of an ideal, viewed as a submodule of `R`, is the ideal itself. -/
@[simp]
theorem minorsIdeal_one (I : Ideal R) : Submodule.minorsIdeal I 1 = I := by
  refine le_antisymm (Submodule.minorsIdeal_le_iff.2 fun f v hv ↦ ?_) fun x hx ↦ ?_
  · rw [Matrix.det_fin_one, Matrix.of_apply, ← mul_one (v 0), ← smul_eq_mul, map_smul,
      smul_eq_mul]
    exact I.mul_mem_right _ (hv 0)
  · simpa [Matrix.det_fin_one] using Submodule.det_mem_minorsIdeal (N := I) (p := 1)
      (fun _ ↦ LinearMap.id) (v := fun _ ↦ x) fun _ ↦ hx

end Ideal

namespace TauCeti

variable {R F M M' : Type*} [CommRing R] [AddCommGroup F] [Module R F]
  [AddCommGroup M] [Module R M] [Module.Finite R M] [AddCommGroup M'] [Module R M']

variable (R M) in
open scoped Classical in
/-- The `k`-th Fitting ideal of a finite `R`-module `M`. For a presentation as a quotient of
`Fin n → R`, it is the ideal of `(n - k) × (n - k)` minors of the relations; this does not depend
on the presentation (`TauCeti.fittingIdeal_eq_minorsIdeal_ker`). -/
def fittingIdeal (k : ℕ) : Ideal R :=
  (ker (Module.Finite.exists_fin' R M).choose_spec.choose).minorsIdeal
    ((Module.Finite.exists_fin' R M).choose - k)

/-- The Fitting ideals of a module may be computed from any surjection from a free module of
finite rank. -/
theorem fittingIdeal_eq_minorsIdeal_ker [Free R F] [Module.Finite R F] {φ : F →ₗ[R] M}
    (hφ : Surjective φ) (k : ℕ) :
    fittingIdeal R M k = (ker φ).minorsIdeal (finrank R F - k) := by
  nontriviality R
  have key := Submodule.minorsIdeal_ker_eq_of_surjective
    (Module.Finite.exists_fin' R M).choose_spec.choose_spec hφ k
  rw [finrank_fin_fun] at key
  simpa only [fittingIdeal] using key

variable (R M) in
/-- The Fitting ideals increase: `Fitt₀(M) ≤ Fitt₁(M) ≤ ⋯`. -/
theorem fittingIdeal_monotone : Monotone (fittingIdeal R M) := by
  intro k l hkl
  obtain ⟨n, φ, hφ⟩ := Module.Finite.exists_fin' R M
  rw [fittingIdeal_eq_minorsIdeal_ker hφ, fittingIdeal_eq_minorsIdeal_ker hφ]
  exact Submodule.minorsIdeal_antitone _ (by omega)

/-- A module generated by `n` elements has `Fitt_k = ⊤` for `k ≥ n`. -/
theorem fittingIdeal_eq_top_of_surjective [Free R F] [Module.Finite R F] {φ : F →ₗ[R] M}
    (hφ : Surjective φ) {k : ℕ} (hk : finrank R F ≤ k) : fittingIdeal R M k = ⊤ := by
  rw [fittingIdeal_eq_minorsIdeal_ker hφ, Nat.sub_eq_zero_of_le hk, Submodule.minorsIdeal_zero]

/-- The Fitting ideals grow along surjections. -/
theorem fittingIdeal_le_of_surjective [Module.Finite R M'] {q : M →ₗ[R] M'}
    (hq : Surjective q) (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R M' k := by
  obtain ⟨n, φ, hφ⟩ := Module.Finite.exists_fin' R M
  rw [fittingIdeal_eq_minorsIdeal_ker hφ, fittingIdeal_eq_minorsIdeal_ker (φ := q ∘ₗ φ)
    (by rw [coe_comp]; exact hq.comp hφ)]
  exact Submodule.minorsIdeal_mono (ker_le_ker_comp φ q) _

/-- Isomorphic modules have the same Fitting ideals. -/
theorem fittingIdeal_congr [Module.Finite R M'] (e : M ≃ₗ[R] M') (k : ℕ) :
    fittingIdeal R M k = fittingIdeal R M' k :=
  le_antisymm (fittingIdeal_le_of_surjective e.surjective k)
    (fittingIdeal_le_of_surjective e.symm.surjective k)

/-- A free module of rank `n` has `Fitt_k = ⊥` for `k < n`. -/
theorem fittingIdeal_eq_bot_of_lt_finrank [Free R F] [Module.Finite R F] {k : ℕ}
    (hk : k < finrank R F) : fittingIdeal R F k = ⊥ := by
  have hsize : finrank R F - k = finrank R F - k - 1 + 1 := by omega
  rw [fittingIdeal_eq_minorsIdeal_ker (φ := LinearMap.id) surjective_id, ker_id,
    hsize, Submodule.minorsIdeal_bot]

/-- The zeroth Fitting ideal of `R ⧸ I` is `I`. -/
@[simp]
theorem fittingIdeal_quotient_zero (I : Ideal R) : fittingIdeal R (R ⧸ I) 0 = I := by
  nontriviality R
  rw [fittingIdeal_eq_minorsIdeal_ker (Submodule.mkQ_surjective I), Submodule.ker_mkQ,
    finrank_self, Nat.sub_zero, Ideal.minorsIdeal_one]

end TauCeti
