/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Presentation.GroupPresentation

/-!
# A transcribed presentation of the Lyons group

This file carries the `Ly` row of the sporadic presentation data required by milestone S1 of
`TauCetiRoadmap/CFSGStatement/README.md`. It records Sims' presentation of the Lyons sporadic
group, in the amended form published by Havas and Sims, as a `TauCeti.GroupPresentation`, together
with its source, conventions, expected counts, and decidable checks.

The source presents `Ly` on the five generators `a`, `b`, `c`, `d`, `z` together with thirty-four
auxiliary generators, all of them words in `a`, `b`, `c`, `d`, by eighty-six relators and
relations (14.1) to (14.86). Following the source's own recipe for coset enumeration, this row
keeps the six generators `a`, `b`, `c`, `d`, `e`, `z`, substitutes the auxiliary generators
`c₁`, ..., `c₅`, `a₁`, ..., `a₄`, `u` and `x₂₃`, ..., `x₃₇₁` by their defining words (14.6) to
(14.10) and (14.45) to (14.72), and keeps the remaining fifty-three relators in the source's
order: (14.1) to (14.5), (14.11) to (14.28), (14.29) to (14.44), and (14.73) to (14.86). The
generator `e` is retained because the source retains it, defined by (14.29). This is the
fifty-three-relator presentation on `a`, `b`, `c`, `d`, `e`, `z` that Section 14.4 of the source
describes and enumerates.

The source writes `x^y` for `y⁻¹xy`, which is `TauCeti.Relator.conj`, and `(x, y)` for
`x⁻¹y⁻¹xy`, transcribed as `TauCeti.Relator.comm (.inv x) (.inv y)`; a displayed equation `r = s`
is compiled as the relator `r s⁻¹`, which is `TauCeti.Relator.div`. Each auxiliary word is a
named abbreviation, so that every relator is displayed in the source's own shape.

## Source-to-Lean read-through

The relators were read from a 300 dpi rendering of the journal PDF of the chapter, whose SHA-256
digest is recorded in `presentation`. Every relator and every auxiliary definition was compared
with the print letter for letter.

## Verification outside Lean

The source proves that this presentation defines `Ly` by a coset enumeration of the `8835156`
cosets of the subgroup generated by `a`, `b`, `c`, `d`, together with the identification of that
subgroup with `G₂(5)`. That enumeration was reproduced with the coset enumerator ACE on the
relators exactly as compiled from this file: the enumeration closes at index `8835156` with the
maximum number of cosets defined equal to the index, and the subgroup generated by `a`, `b`, `c`
has index `3906` in the group presented by the z-free relators. This is provenance rather than a
Lean theorem: the file asserts no order, finiteness, simplicity, or identification result. The
independent FiniteSimpleGroups development named by the roadmap does not cover `Ly`.

Three of the fifty-three relators are not cyclically reduced after free reduction: the commutator
relations (14.14), (14.18), and (14.19) freely reduce to words that begin and end with a cancelling
pair of letters, because their two sides share a conjugating prefix. The cyclic-reducedness check
stated by other rows is therefore not stated here; it exists to compare a reduced letter count with
a published presentation length, and this source prints none.

An earlier version of this row transcribed Gebhardt's twenty-five-relator presentation (Experimental
Mathematics 9 (2000), 333--338). That row presented the trivial group, because of transcription
errors and a misprint in the paper's fourth `R_G` relator; the present source is used instead
because its correctness proof is a reproducible coset enumeration.

## Main definitions and results

* `TauCeti.Sporadic.Lyons.presentation`: the Havas--Sims finite presentation of `Ly`.
* `TauCeti.Sporadic.Lyons.presentation_transcribed` and the equations for the remaining fields:
  the characterization of the sealed row, with the source's auxiliary words as `let`-bound
  abbreviations.
* `TauCeti.Sporadic.Lyons.matchesMetadata_presentation`,
  `TauCeti.Sporadic.Lyons.map_length_relators_presentation` and
  `TauCeti.Sporadic.Lyons.reducedTotalLength_presentation`: the transcription checks.

## References

* G. Havas and C. C. Sims, *A presentation for the Lyons simple group*, in: Computational
  Methods for Representations of Groups and Algebras (Essen, 1997), Progress in Mathematics 173,
  Birkhäuser, Basel, 1999, 241--249, <https://doi.org/10.1007/978-3-0348-8716-8_14>.
* C. C. Sims, *The existence and uniqueness of Lyons' group*, in: Finite Groups '72, North-Holland
  Mathematics Studies 7, 1973, 138--141.
* V. Gebhardt, *Two Short Presentations for Lyons' Sporadic Simple Group*, Experimental
  Mathematics 9 (2000), 333--338, <https://doi.org/10.1080/10586458.2000.10504410>, the source
  of the previous row.
-/

public section

namespace TauCeti.Sporadic.Lyons

/-- The source's generator `a`, of order eight. -/
abbrev genA : Relator (Fin 6) := .gen 0

/-- The source's generator `b`, of order five. -/
abbrev genB : Relator (Fin 6) := .gen 1

/-- The source's generator `c`, of order five. -/
abbrev genC : Relator (Fin 6) := .gen 2

/-- The source's generator `d`. -/
abbrev genD : Relator (Fin 6) := .gen 3

/-- The source's generator `e`, an involution defined by relation (14.29). -/
abbrev genE : Relator (Fin 6) := .gen 4

/-- The source's generator `z`, the element outside the subgroup `G₂(5)`. -/
abbrev genZ : Relator (Fin 6) := .gen 5

/-- The source's commutator `(r, s) = r⁻¹ s⁻¹ r s`. -/
abbrev sourceCommutator {α : Type*} (r s : Relator α) : Relator α := .comm (.inv r) (.inv s)

@[inherit_doc Relator.mul]
local infixl:70 " ⬝ " => Relator.mul

/-- The source's `c₁ = c` (14.6). -/
private def cOne : Relator (Fin 6) :=
  genC

/-- The source's `c₂ = c^a` (14.7). -/
private def cTwo : Relator (Fin 6) :=
  Relator.conj genC genA

/-- The source's `c₃ = c^b` (14.8). -/
private def cThree : Relator (Fin 6) :=
  Relator.conj genC genB

/-- The source's `c₄ = c^(b⁻¹)` (14.9). -/
private def cFour : Relator (Fin 6) :=
  Relator.conj genC (.inv genB)

/-- The source's `c₅ = (c₁, c₂)` (14.10). -/
private def cFive : Relator (Fin 6) :=
  sourceCommutator cOne cTwo

/-- The source's `a₁ = a` (14.45). -/
private def aOne : Relator (Fin 6) :=
  genA

/-- The source's `a₂ = a^(b⁻¹)` (14.46). -/
private def aTwo : Relator (Fin 6) :=
  Relator.conj genA (.inv genB)

/-- The source's `a₃ = a^(b⁻²)` (14.47). -/
private def aThree : Relator (Fin 6) :=
  Relator.conj genA (.pow (.inv genB) 2)

/-- The source's `a₄ = a^(b²)` (14.48). -/
private def aFour : Relator (Fin 6) :=
  Relator.conj genA (.pow genB 2)

/-- The source's `u = a²` (14.49). -/
private def u : Relator (Fin 6) :=
  .pow genA 2

/-- The source's `x₂₃ = d` (14.50). -/
private def x23 : Relator (Fin 6) :=
  genD

/-- The source's `x₂₄ = d⁻¹` (14.51). -/
private def x24 : Relator (Fin 6) :=
  .inv genD

/-- The source's `x₂₅` (14.52). -/
private def x25 : Relator (Fin 6) :=
  .pow genB 2 ⬝ .inv genA ⬝ .inv genB ⬝ .inv genA ⬝ .pow genB 2 ⬝ .inv genC ⬝ genA ⬝ genC ⬝
  .inv genA ⬝ .inv genC ⬝ genD ⬝ .inv genC ⬝ .pow genB 2 ⬝ .inv genA ⬝ genC ⬝ genB

/-- The source's `x₂₉` (14.53). -/
private def x29 : Relator (Fin 6) :=
  genA ⬝ genB ⬝ .inv genA ⬝ .pow genB 2 ⬝ .inv genA ⬝ .pow genB 2 ⬝ .inv genC ⬝ genA ⬝ genC ⬝
  genB ⬝ genC ⬝ .inv genB ⬝ genD ⬝ genC ⬝ .pow (.inv genB) 2 ⬝ genD ⬝ genC ⬝ genB ⬝ genC

/-- The source's `x₄₇` (14.54). -/
private def x47 : Relator (Fin 6) :=
  .inv genC ⬝ .inv genD ⬝ .inv genA ⬝ .inv genC ⬝ .inv genA ⬝ genB ⬝ .inv genC ⬝ .inv genD

/-- The source's `x₉₆ = bd` (14.55). -/
private def x96 : Relator (Fin 6) :=
  genB ⬝ genD

/-- The source's `x₁₂₉ = d⁻¹b⁻¹` (14.56). -/
private def x129 : Relator (Fin 6) :=
  .inv genD ⬝ .inv genB

/-- The source's `x₁₆₂` (14.57). -/
private def x162 : Relator (Fin 6) :=
  .inv genA ⬝ .inv genB ⬝ .inv genA ⬝ genB ⬝ .inv genC ⬝ .inv genB ⬝ genA ⬝ .inv genC ⬝ genB ⬝
  genA

/-- The source's `x₁₆₃` (14.58). -/
private def x163 : Relator (Fin 6) :=
  .pow (.inv genB) 2 ⬝ genA ⬝ genC ⬝ .inv genA ⬝ genB ⬝ genC ⬝ genB

/-- The source's `x₁₆₄` (14.59). -/
private def x164 : Relator (Fin 6) :=
  .inv genA ⬝ .inv genB ⬝ .inv genA ⬝ genC ⬝ genA ⬝ genB ⬝ genA

/-- The source's `x₁₆₅` (14.60). -/
private def x165 : Relator (Fin 6) :=
  .inv genB ⬝ .inv genA ⬝ genB ⬝ genC ⬝ .inv genB ⬝ genA ⬝ genB

/-- The source's `x₁₆₆` (14.61). -/
private def x166 : Relator (Fin 6) :=
  .pow genB 2 ⬝ .inv genA ⬝ .inv genB ⬝ genC ⬝ genB ⬝ genA ⬝ genC ⬝ .pow (.inv genB) 2 ⬝
  .inv genC

/-- The source's `x₁₆₇ = a⁻³` (14.62). -/
private def x167 : Relator (Fin 6) :=
  .pow (.inv genA) 3

/-- The source's `x₁₆₈` (14.63). -/
private def x168 : Relator (Fin 6) :=
  genB ⬝ .inv genA ⬝ .inv genB ⬝ .pow (.inv genA) 2

/-- The source's `x₁₆₉` (14.64). -/
private def x169 : Relator (Fin 6) :=
  genA ⬝ .pow genB 2 ⬝ genA ⬝ .pow (.inv genB) 2 ⬝ .inv genA

/-- The source's `x₃₆₄` (14.65). -/
private def x364 : Relator (Fin 6) :=
  .inv genA ⬝ genD ⬝ .inv genB ⬝ .inv genC ⬝ .inv genA ⬝ genB ⬝ .inv genC ⬝ .inv genD ⬝ genB ⬝
  .inv genC ⬝ .inv genB ⬝ .inv genA ⬝ .inv genC ⬝ genA ⬝ .inv genB ⬝ genA ⬝ genB ⬝ genA ⬝
  .inv genB

/-- The source's `x₃₆₅` (14.66). -/
private def x365 : Relator (Fin 6) :=
  genA ⬝ .pow (.inv genB) 2 ⬝ .inv genA ⬝ genC ⬝ genB ⬝ .inv genC ⬝ genB ⬝ .inv genA ⬝
  .pow (.inv genC) 2 ⬝ genD ⬝ genC ⬝ genA ⬝ genC ⬝ .inv genA ⬝ genC ⬝ .inv genB ⬝ .inv genD

/-- The source's `x₃₆₆` (14.67). -/
private def x366 : Relator (Fin 6) :=
  genB ⬝ genA ⬝ .inv genB ⬝ .inv genA ⬝ .pow (.inv genB) 2 ⬝ .inv genA ⬝ .inv genB ⬝ genC ⬝
  .pow genB 2 ⬝ genC ⬝ genB ⬝ genD ⬝ genC ⬝ .pow (.inv genB) 2 ⬝ genD ⬝ genC ⬝ genB ⬝ genC

/-- The source's `x₃₆₇` (14.68). -/
private def x367 : Relator (Fin 6) :=
  .inv genC ⬝ .inv genB ⬝ .inv genC ⬝ .inv genD ⬝ .pow genB 2 ⬝ .inv genC ⬝ .inv genD ⬝
  .inv genB ⬝ .inv genC ⬝ .pow (.inv genB) 2 ⬝ .inv genC ⬝ genB ⬝ genA ⬝ .pow genB 2 ⬝ genA ⬝
  genB ⬝ .inv genA ⬝ .inv genB

/-- The source's `x₃₆₈` (14.69). -/
private def x368 : Relator (Fin 6) :=
  .inv genA ⬝ .inv genC ⬝ .inv genD ⬝ genA ⬝ .inv genC ⬝ .inv genB ⬝ genA ⬝ .inv genC ⬝
  .inv genD ⬝ .inv genA ⬝ .inv genC ⬝ genA ⬝ genC ⬝ .pow (.inv genB) 2 ⬝ .inv genC ⬝ .inv genB ⬝
  .inv genA ⬝ .pow (.inv genB) 2

/-- The source's `x₃₆₉` (14.70). -/
private def x369 : Relator (Fin 6) :=
  .inv genA ⬝ .inv genC ⬝ .inv genD ⬝ genB ⬝ .inv genA ⬝ .inv genB ⬝ .inv genC ⬝ .inv genD ⬝
  genB ⬝ .inv genA ⬝ .inv genB ⬝ .inv genC ⬝ .inv genB ⬝ genA ⬝ .pow (.inv genB) 2 ⬝ genA ⬝
  .inv genB

/-- The source's `x₃₇₀` (14.71). -/
private def x370 : Relator (Fin 6) :=
  .inv genD ⬝ genA ⬝ genC ⬝ genB ⬝ genC ⬝ .inv genA ⬝ .inv genC ⬝ .inv genD ⬝ genA ⬝ .inv genB ⬝
  .inv genA ⬝ genC ⬝ .inv genA ⬝ .pow (.inv genB) 2 ⬝ .inv genA ⬝ genB ⬝ .inv genA

/-- The source's `x₃₇₁` (14.72). -/
private def x371 : Relator (Fin 6) :=
  .inv genC ⬝ .inv genA ⬝ genC ⬝ genB ⬝ .inv genC ⬝ .inv genD ⬝ genC ⬝ .inv genA ⬝ genC ⬝ genA ⬝
  genC ⬝ .inv genB ⬝ .inv genA ⬝ .inv genB ⬝ .inv genA ⬝ genB

/-- The source's relators (14.1) to (14.5), presenting `GL₂(5)` on `a` and `b`. -/
private def relatorsOne : List (Relator (Fin 6)) :=
  [ .pow genA 8,
    .pow genB 5,
    .pow (genA ⬝ genB) 4,
    sourceCommutator (.pow genA 2) genB,
    .pow (sourceCommutator genA genB) 3 ]

/-- The source's relators (14.11) to (14.28), the relations among `c₁`, ..., `c₅` and their
conjugates by `a` and `b`, presenting `5^(1+4) : GL₂(5)` on `a`, `b`, `c`. -/
private def relatorsTwo : List (Relator (Fin 6)) :=
  [ .pow cOne 5,
    .pow cFive 5,
    sourceCommutator cOne cFive,
    sourceCommutator cTwo cFive,
    sourceCommutator cThree cFive,
    sourceCommutator cFour cFive,
    Relator.div (sourceCommutator cOne cThree) (.pow (.inv cFive) 2),
    Relator.div (sourceCommutator cOne cFour) (.pow cFive 2),
    Relator.div (sourceCommutator cTwo cThree) (.inv cFive),
    sourceCommutator cTwo cFour,
    Relator.div (sourceCommutator cThree cFour) (.inv cFive),
    Relator.div (Relator.conj cTwo genA) (.pow (.inv cOne) 2),
    Relator.div (Relator.conj cThree genA) (.pow (.inv cThree) 2 ⬝ cOne ⬝ cFour),
    Relator.div (Relator.conj cFour genA) (cOne ⬝ .inv cTwo ⬝ .inv cThree ⬝ cFour ⬝ cOne ⬝
    cFour),
    Relator.div (Relator.conj cFive genA) (.pow cFive 2),
    Relator.div (Relator.conj cTwo genB) (cTwo ⬝ cThree ⬝ .inv cFour ⬝ .inv cOne ⬝ .inv cFour),
    Relator.div (Relator.conj cThree genB) (.pow cOne 2 ⬝ cFour ⬝ .pow (.inv cThree) 2),
    Relator.div (Relator.conj cFive genB) cFive ]

/-- The source's relators (14.29) to (14.44), defining `e` and `d` and presenting `G₂(5)` on `a`,
`b`, `c`, `d`, `e`. -/
private def relatorsThree : List (Relator (Fin 6)) :=
  [ Relator.div genE (.pow (.inv genB) 2 ⬝ sourceCommutator genA cOne ⬝ .inv genA ⬝ cOne ⬝ genA ⬝
    genD ⬝ cOne ⬝ genB ⬝ genA ⬝ .inv genB ⬝ genD ⬝ cOne ⬝ genD),
    .pow genE 2,
    Relator.div (Relator.conj cOne genE) (genB ⬝ cThree ⬝ genB ⬝ .inv cOne),
    Relator.div (Relator.conj cThree genE) (.pow genB 2 ⬝ genA ⬝ cTwo ⬝ .inv cOne ⬝ .inv cFour ⬝
    .inv genA),
    Relator.div (Relator.conj cFour genE) (.pow genB 2 ⬝ .inv cThree ⬝ cFour),
    Relator.div (Relator.conj cFive genE) (cOne ⬝ .inv cThree ⬝ cOne ⬝ .inv cFour),
    Relator.div (genE ⬝ .pow genA 2 ⬝ genE) (genA ⬝ .pow genB 2 ⬝ genA ⬝ .inv genB ⬝ genA ⬝ cOne ⬝
    cFive ⬝ .inv cFour),
    Relator.div (Relator.conj genB genE) (cOne ⬝ .inv cThree ⬝ .pow (.inv cFour) 2),
    Relator.div (genE ⬝ genA ⬝ .pow genB 2 ⬝ genA ⬝ .inv genB ⬝ genA ⬝ genE) (.pow genA 2 ⬝ cOne ⬝
    cFive ⬝ .inv cFour),
    genE ⬝ cTwo ⬝ genE ⬝ .inv cTwo ⬝ genE ⬝ cTwo ⬝ .inv cFour ⬝ genA ⬝ cThree ⬝ .pow genA 3,
    Relator.div genD (genA ⬝ .pow genB 2 ⬝ .inv genA ⬝ .inv genB ⬝ .inv cOne ⬝ .inv cFour ⬝
    .inv cFive ⬝ genA ⬝ genE ⬝ genA ⬝ genE ⬝ genA ⬝ .inv cTwo ⬝ genB ⬝ genE),
    Relator.div (.pow genD 2) (.pow genA 4),
    sourceCommutator genB genD,
    Relator.div (Relator.conj genA genD) (.pow genA 3),
    .pow (genD ⬝ cFive) 5,
    genD ⬝ cFive ⬝ genD ⬝ .inv cFive ⬝ genD ⬝ cFive ⬝ .pow (.inv genA) 2 ]

/-- The source's relators (14.73) to (14.86), the relations involving `z`, completing the
presentation of `Ly`. -/
private def relatorsFour : List (Relator (Fin 6)) :=
  [ Relator.div (Relator.conj cOne genZ) x162,
    Relator.div (Relator.conj cTwo genZ) x163,
    Relator.div (Relator.conj cThree genZ) x164,
    Relator.div (Relator.conj cFour genZ) x165,
    Relator.div (Relator.conj cFive genZ) x166,
    Relator.div (Relator.conj aOne genZ) x167,
    Relator.div (Relator.conj aTwo genZ) x168,
    Relator.div (Relator.conj aThree genZ) x169,
    Relator.div (.pow genZ 2) u,
    .pow (aFour ⬝ genZ) 3 ⬝ u,
    x47 ⬝ genZ ⬝ x364 ⬝ genZ ⬝ x368 ⬝ genZ,
    .inv genZ ⬝ x24 ⬝ .inv genZ ⬝ x369 ⬝ genZ ⬝ x23 ⬝ genZ ⬝ x29,
    genZ ⬝ x366 ⬝ genZ ⬝ x365 ⬝ .inv genZ ⬝ x367 ⬝ .inv genZ ⬝ x370,
    genZ ⬝ x96 ⬝ genZ ⬝ x25 ⬝ .inv genZ ⬝ x129 ⬝ .inv genZ ⬝ x371 ]

/-- All fifty-three relators, in the source's order. -/
private def relatorList : List (Relator (Fin 6)) :=
  relatorsOne ++ relatorsTwo ++ relatorsThree ++ relatorsFour

/-- Sims' presentation of the Lyons sporadic group `Ly`, as amended by Havas and Sims, on the six
generators `a`, `b`, `c`, `d`, `e`, `z`.

The source proves that these relators present `Ly` (Theorem 14.2), the final step being a coset
enumeration of the `8835156` cosets of the subgroup generated by `a`, `b`, `c`, `d`. No structural
property of the resulting `PresentedGroup` is asserted here; the definition records only the
generators and relators. -/
def presentation : GroupPresentation where
  generatorNames := ["a", "b", "c", "d", "e", "z"]
  source := "G. Havas and C. C. Sims, A presentation for the Lyons simple group, in Computational \
    Methods for Representations of Groups and Algebras (Essen, 1997), Progress in Mathematics \
    173, Birkhauser, Basel, 1999, 241-249"
  sourceLocator := "Section 14.2, relators and relations (14.1) to (14.86), pp. 242-244; \
    doi:10.1007/978-3-0348-8716-8_14; SHA-256 of the chapter PDF \
    db0f8a96b79392b590982505ab32224890e548cc957239d03fc3f8f68949e1df"
  generatorConvention := "The source's generators a, b, c, d, e, z, in that order, so indices 0 \
    to 5 denote a, b, c, d, e, z. The source writes x^y for y^-1*x*y and (x, y) for \
    x^-1*y^-1*x*y, and products are read left to right."
  transcriptionNotes := "The source presents Ly on a, b, c, d, z and thirty-four auxiliary \
    generators, all words in a, b, c, d, by relators (14.1) to (14.86). This row follows the \
    source's Section 14.4: it keeps the six generators a, b, c, d, e, z, substitutes the \
    auxiliary generators c1 to c5, a1 to a4, u and x23 to x371 by their defining relations \
    (14.6) to (14.10) and (14.45) to (14.72), and keeps the remaining fifty-three relators in \
    source order, namely (14.1) to (14.5), (14.11) to (14.28), (14.29) to (14.44) and (14.73) \
    to (14.86). An equation r = s is compiled as r*s^-1. Free reduction gives total length 975; \
    the source prints no length. Coset enumeration with ACE on these compiled relators closes \
    at index 8835156 over the subgroup generated by a, b, c, d, with maximum cosets equal to \
    the index. The independent FiniteSimpleGroups development does not cover Ly."
  expectedGeneratorCount := 6
  expectedRelatorCount := 53
  transcribed := relatorList

/-- The generator names recorded for `Ly`. -/
@[simp]
theorem presentation_generatorNames :
    presentation.generatorNames = ["a", "b", "c", "d", "e", "z"] := by
  rfl

/-- The bibliographic source recorded for `Ly`. -/
@[simp]
theorem presentation_source :
    presentation.source =
      "G. Havas and C. C. Sims, A presentation for the Lyons simple group, in Computational \
      Methods for Representations of Groups and Algebras (Essen, 1997), Progress in \
      Mathematics 173, Birkhauser, Basel, 1999, 241-249" := by
  rfl

/-- The locator recorded for `Ly`. -/
@[simp]
theorem presentation_sourceLocator :
    presentation.sourceLocator =
      "Section 14.2, relators and relations (14.1) to (14.86), pp. 242-244; \
      doi:10.1007/978-3-0348-8716-8_14; SHA-256 of the chapter PDF \
      db0f8a96b79392b590982505ab32224890e548cc957239d03fc3f8f68949e1df" := by
  rfl

/-- The generator convention recorded for `Ly`. -/
@[simp]
theorem presentation_generatorConvention :
    presentation.generatorConvention =
      "The source's generators a, b, c, d, e, z, in that order, so indices 0 to 5 denote a, \
      b, c, d, e, z. The source writes x^y for y^-1*x*y and (x, y) for x^-1*y^-1*x*y, and \
      products are read left to right." := by
  rfl

/-- The transcription notes recorded for `Ly`. -/
@[simp]
theorem presentation_transcriptionNotes :
    presentation.transcriptionNotes =
      "The source presents Ly on a, b, c, d, z and thirty-four auxiliary generators, all \
      words in a, b, c, d, by relators (14.1) to (14.86). This row follows the source's \
      Section 14.4: it keeps the six generators a, b, c, d, e, z, substitutes the \
      auxiliary generators c1 to c5, a1 to a4, u and x23 to x371 by their defining \
      relations (14.6) to (14.10) and (14.45) to (14.72), and keeps the remaining \
      fifty-three relators in source order, namely (14.1) to (14.5), (14.11) to (14.28), \
      (14.29) to (14.44) and (14.73) to (14.86). An equation r = s is compiled as r*s^-1. \
      Free reduction gives total length 975; the source prints no length. Coset \
      enumeration with ACE on these compiled relators closes at index 8835156 over the \
      subgroup generated by a, b, c, d, with maximum cosets equal to the index. The \
      independent FiniteSimpleGroups development does not cover Ly." := by
  rfl

/-- The generator count recorded for `Ly`. -/
@[simp]
theorem presentation_expectedGeneratorCount : presentation.expectedGeneratorCount = 6 := by
  rfl

/-- The relator count recorded for `Ly`. -/
@[simp]
theorem presentation_expectedRelatorCount : presentation.expectedRelatorCount = 53 := by
  rfl

/-- The transcribed relators of the row, spelled out in the source's own shape: the six
generators, the source's auxiliary words as `let`-bound abbreviations, and the fifty-three relators
in the source's order (14.1) to (14.5), (14.11) to (14.28), (14.29) to (14.44), (14.73) to (14.86).
Together with `TauCeti.GroupPresentation.relators_def` and
`TauCeti.GroupPresentation.mem_relatorSet_iff` this determines the relations defining
`TauCeti.GroupPresentation.Group`, so a consumer never has to unfold the row. -/
@[simp]
theorem presentation_transcribed :
    presentation.transcribed =
      let a : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨0, by simp [presentation]⟩
      let b : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨1, by simp [presentation]⟩
      let c : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨2, by simp [presentation]⟩
      let d : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨3, by simp [presentation]⟩
      let e : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨4, by simp [presentation]⟩
      let z : Relator (Fin presentation.generatorNames.length) :=
        .gen ⟨5, by simp [presentation]⟩
      let cOne := c
      let cTwo := Relator.conj c a
      let cThree := Relator.conj c b
      let cFour := Relator.conj c (.inv b)
      let cFive := sourceCommutator cOne cTwo
      let aOne := a
      let aTwo := Relator.conj a (.inv b)
      let aThree := Relator.conj a (.pow (.inv b) 2)
      let aFour := Relator.conj a (.pow b 2)
      let u := .pow a 2
      let x23 := d
      let x24 := .inv d
      let x25 :=
        .pow b 2 ⬝ .inv a ⬝ .inv b ⬝ .inv a ⬝ .pow b 2 ⬝ .inv c ⬝ a ⬝ c ⬝ .inv a ⬝ .inv c ⬝ d ⬝
        .inv c ⬝ .pow b 2 ⬝ .inv a ⬝ c ⬝ b
      let x29 :=
        a ⬝ b ⬝ .inv a ⬝ .pow b 2 ⬝ .inv a ⬝ .pow b 2 ⬝ .inv c ⬝ a ⬝ c ⬝ b ⬝ c ⬝ .inv b ⬝ d ⬝ c ⬝
        .pow (.inv b) 2 ⬝ d ⬝ c ⬝ b ⬝ c
      let x47 := .inv c ⬝ .inv d ⬝ .inv a ⬝ .inv c ⬝ .inv a ⬝ b ⬝ .inv c ⬝ .inv d
      let x96 := b ⬝ d
      let x129 := .inv d ⬝ .inv b
      let x162 := .inv a ⬝ .inv b ⬝ .inv a ⬝ b ⬝ .inv c ⬝ .inv b ⬝ a ⬝ .inv c ⬝ b ⬝ a
      let x163 := .pow (.inv b) 2 ⬝ a ⬝ c ⬝ .inv a ⬝ b ⬝ c ⬝ b
      let x164 := .inv a ⬝ .inv b ⬝ .inv a ⬝ c ⬝ a ⬝ b ⬝ a
      let x165 := .inv b ⬝ .inv a ⬝ b ⬝ c ⬝ .inv b ⬝ a ⬝ b
      let x166 := .pow b 2 ⬝ .inv a ⬝ .inv b ⬝ c ⬝ b ⬝ a ⬝ c ⬝ .pow (.inv b) 2 ⬝ .inv c
      let x167 := .pow (.inv a) 3
      let x168 := b ⬝ .inv a ⬝ .inv b ⬝ .pow (.inv a) 2
      let x169 := a ⬝ .pow b 2 ⬝ a ⬝ .pow (.inv b) 2 ⬝ .inv a
      let x364 :=
        .inv a ⬝ d ⬝ .inv b ⬝ .inv c ⬝ .inv a ⬝ b ⬝ .inv c ⬝ .inv d ⬝ b ⬝ .inv c ⬝ .inv b ⬝
        .inv a ⬝ .inv c ⬝ a ⬝ .inv b ⬝ a ⬝ b ⬝ a ⬝ .inv b
      let x365 :=
        a ⬝ .pow (.inv b) 2 ⬝ .inv a ⬝ c ⬝ b ⬝ .inv c ⬝ b ⬝ .inv a ⬝ .pow (.inv c) 2 ⬝ d ⬝ c ⬝ a ⬝
        c ⬝ .inv a ⬝ c ⬝ .inv b ⬝ .inv d
      let x366 :=
        b ⬝ a ⬝ .inv b ⬝ .inv a ⬝ .pow (.inv b) 2 ⬝ .inv a ⬝ .inv b ⬝ c ⬝ .pow b 2 ⬝ c ⬝ b ⬝ d ⬝
        c ⬝ .pow (.inv b) 2 ⬝ d ⬝ c ⬝ b ⬝ c
      let x367 :=
        .inv c ⬝ .inv b ⬝ .inv c ⬝ .inv d ⬝ .pow b 2 ⬝ .inv c ⬝ .inv d ⬝ .inv b ⬝ .inv c ⬝
        .pow (.inv b) 2 ⬝ .inv c ⬝ b ⬝ a ⬝ .pow b 2 ⬝ a ⬝ b ⬝ .inv a ⬝ .inv b
      let x368 :=
        .inv a ⬝ .inv c ⬝ .inv d ⬝ a ⬝ .inv c ⬝ .inv b ⬝ a ⬝ .inv c ⬝ .inv d ⬝ .inv a ⬝ .inv c ⬝
        a ⬝ c ⬝ .pow (.inv b) 2 ⬝ .inv c ⬝ .inv b ⬝ .inv a ⬝ .pow (.inv b) 2
      let x369 :=
        .inv a ⬝ .inv c ⬝ .inv d ⬝ b ⬝ .inv a ⬝ .inv b ⬝ .inv c ⬝ .inv d ⬝ b ⬝ .inv a ⬝ .inv b ⬝
        .inv c ⬝ .inv b ⬝ a ⬝ .pow (.inv b) 2 ⬝ a ⬝ .inv b
      let x370 :=
        .inv d ⬝ a ⬝ c ⬝ b ⬝ c ⬝ .inv a ⬝ .inv c ⬝ .inv d ⬝ a ⬝ .inv b ⬝ .inv a ⬝ c ⬝ .inv a ⬝
        .pow (.inv b) 2 ⬝ .inv a ⬝ b ⬝ .inv a
      let x371 :=
        .inv c ⬝ .inv a ⬝ c ⬝ b ⬝ .inv c ⬝ .inv d ⬝ c ⬝ .inv a ⬝ c ⬝ a ⬝ c ⬝ .inv b ⬝ .inv a ⬝
        .inv b ⬝ .inv a ⬝ b
      [ .pow a 8,
        .pow b 5,
        .pow (a ⬝ b) 4,
        sourceCommutator (.pow a 2) b,
        .pow (sourceCommutator a b) 3,
        .pow cOne 5,
        .pow cFive 5,
        sourceCommutator cOne cFive,
        sourceCommutator cTwo cFive,
        sourceCommutator cThree cFive,
        sourceCommutator cFour cFive,
        Relator.div (sourceCommutator cOne cThree) (.pow (.inv cFive) 2),
        Relator.div (sourceCommutator cOne cFour) (.pow cFive 2),
        Relator.div (sourceCommutator cTwo cThree) (.inv cFive),
        sourceCommutator cTwo cFour,
        Relator.div (sourceCommutator cThree cFour) (.inv cFive),
        Relator.div (Relator.conj cTwo a) (.pow (.inv cOne) 2),
        Relator.div (Relator.conj cThree a) (.pow (.inv cThree) 2 ⬝ cOne ⬝ cFour),
        Relator.div (Relator.conj cFour a) (cOne ⬝ .inv cTwo ⬝ .inv cThree ⬝ cFour ⬝ cOne ⬝
        cFour),
        Relator.div (Relator.conj cFive a) (.pow cFive 2),
        Relator.div (Relator.conj cTwo b) (cTwo ⬝ cThree ⬝ .inv cFour ⬝ .inv cOne ⬝ .inv cFour),
        Relator.div (Relator.conj cThree b) (.pow cOne 2 ⬝ cFour ⬝ .pow (.inv cThree) 2),
        Relator.div (Relator.conj cFive b) cFive,
        Relator.div e (.pow (.inv b) 2 ⬝ sourceCommutator a cOne ⬝ .inv a ⬝ cOne ⬝ a ⬝ d ⬝ cOne ⬝
        b ⬝ a ⬝ .inv b ⬝ d ⬝ cOne ⬝ d),
        .pow e 2,
        Relator.div (Relator.conj cOne e) (b ⬝ cThree ⬝ b ⬝ .inv cOne),
        Relator.div (Relator.conj cThree e) (.pow b 2 ⬝ a ⬝ cTwo ⬝ .inv cOne ⬝ .inv cFour ⬝
        .inv a),
        Relator.div (Relator.conj cFour e) (.pow b 2 ⬝ .inv cThree ⬝ cFour),
        Relator.div (Relator.conj cFive e) (cOne ⬝ .inv cThree ⬝ cOne ⬝ .inv cFour),
        Relator.div (e ⬝ .pow a 2 ⬝ e) (a ⬝ .pow b 2 ⬝ a ⬝ .inv b ⬝ a ⬝ cOne ⬝ cFive ⬝
        .inv cFour),
        Relator.div (Relator.conj b e) (cOne ⬝ .inv cThree ⬝ .pow (.inv cFour) 2),
        Relator.div (e ⬝ a ⬝ .pow b 2 ⬝ a ⬝ .inv b ⬝ a ⬝ e) (.pow a 2 ⬝ cOne ⬝ cFive ⬝
        .inv cFour),
        e ⬝ cTwo ⬝ e ⬝ .inv cTwo ⬝ e ⬝ cTwo ⬝ .inv cFour ⬝ a ⬝ cThree ⬝ .pow a 3,
        Relator.div d (a ⬝ .pow b 2 ⬝ .inv a ⬝ .inv b ⬝ .inv cOne ⬝ .inv cFour ⬝ .inv cFive ⬝ a ⬝
        e ⬝ a ⬝ e ⬝ a ⬝ .inv cTwo ⬝ b ⬝ e),
        Relator.div (.pow d 2) (.pow a 4),
        sourceCommutator b d,
        Relator.div (Relator.conj a d) (.pow a 3),
        .pow (d ⬝ cFive) 5,
        d ⬝ cFive ⬝ d ⬝ .inv cFive ⬝ d ⬝ cFive ⬝ .pow (.inv a) 2,
        Relator.div (Relator.conj cOne z) x162,
        Relator.div (Relator.conj cTwo z) x163,
        Relator.div (Relator.conj cThree z) x164,
        Relator.div (Relator.conj cFour z) x165,
        Relator.div (Relator.conj cFive z) x166,
        Relator.div (Relator.conj aOne z) x167,
        Relator.div (Relator.conj aTwo z) x168,
        Relator.div (Relator.conj aThree z) x169,
        Relator.div (.pow z 2) u,
        .pow (aFour ⬝ z) 3 ⬝ u,
        x47 ⬝ z ⬝ x364 ⬝ z ⬝ x368 ⬝ z,
        .inv z ⬝ x24 ⬝ .inv z ⬝ x369 ⬝ z ⬝ x23 ⬝ z ⬝ x29,
        z ⬝ x366 ⬝ z ⬝ x365 ⬝ .inv z ⬝ x367 ⬝ .inv z ⬝ x370,
        z ⬝ x96 ⬝ z ⬝ x25 ⬝ .inv z ⬝ x129 ⬝ .inv z ⬝ x371 ] := by
  rfl

/-- The recorded generator and relator counts agree with the transcribed data. -/
theorem matchesMetadata_presentation : presentation.matchesMetadata := by
  decide

/-- The lengths of the fifty-three compiled relator words, block by block in source order. -/
theorem map_length_relators_presentation :
    presentation.relators.map List.length =
      [8, 5, 8, 6, 12,
        5, 40, 18, 22, 22, 22, 24, 24, 20, 12, 20, 7, 15, 19, 26, 18, 16, 18,
        18, 2, 9, 16, 13, 18, 22, 13, 22, 22, 28, 6, 4, 6, 45, 29,
        13, 13, 12, 12, 21, 6, 10, 14, 4, 20, 50, 46, 83, 43] := by
  simp only [GroupPresentation.relators_def, presentation, relatorList, relatorsOne, relatorsTwo,
    relatorsThree, relatorsFour, cOne, cTwo, cThree, cFour, cFive, aOne, aTwo, aThree, aFour, u,
    x23, x24, x25, x29, x47, x96, x129, x162, x163, x164, x165, x166, x167, x168, x169, x364,
    x365, x366, x367, x368, x369, x370, x371, sourceCommutator, Relator.conj, Relator.div,
    List.map_cons, List.map_nil, List.append_assoc, List.cons_append, List.nil_append,
    Relator.toWord_gen, Relator.toWord_inv, Relator.toWord_mul, Relator.toWord_pow,
    Relator.toWord_comm]
  decide

/-- The compiled relator words have `1007` letters in total. -/
theorem totalLength_presentation : presentation.totalLength = 1007 := by
  rw [GroupPresentation.totalLength_def, map_length_relators_presentation]
  decide

/-- The lengths of the fifty-three compiled relator words after free reduction, block by block in
source order. -/
theorem map_length_reduce_relators_presentation :
    (presentation.relators.map fun w => (FreeGroup.reduce w).length) =
      [8, 5, 8, 6, 12,
        5, 40, 16, 20, 22, 22, 24, 24, 20, 12, 20, 7, 13, 19, 24, 18, 12, 18,
        18, 2, 7, 14, 11, 18, 18, 11, 18, 22, 26, 6, 4, 6, 45, 27,
        13, 13, 12, 12, 21, 6, 10, 14, 4, 20, 50, 46, 83, 43] := by
  simp only [GroupPresentation.relators_def, presentation, relatorList, relatorsOne, relatorsTwo,
    relatorsThree, relatorsFour, cOne, cTwo, cThree, cFour, cFive, aOne, aTwo, aThree, aFour, u,
    x23, x24, x25, x29, x47, x96, x129, x162, x163, x164, x165, x166, x167, x168, x169, x364,
    x365, x366, x367, x368, x369, x370, x371, sourceCommutator, Relator.conj, Relator.div,
    List.map_cons, List.map_nil, List.append_assoc, List.cons_append, List.nil_append,
    Relator.toWord_gen, Relator.toWord_inv, Relator.toWord_mul, Relator.toWord_pow,
    Relator.toWord_comm]
  decide

/-- The freely reduced relator words have `975` letters in total. The source prints no length
for this presentation, so this figure states the transcribed data for a reviewer. -/
theorem reducedTotalLength_presentation :
    (presentation.relators.map fun w => (FreeGroup.reduce w).length).sum = 975 := by
  rw [map_length_reduce_relators_presentation]
  decide

end TauCeti.Sporadic.Lyons
