/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.Exact.Frobenius
public import TauCeti.CategoryTheory.Preadditive.MorphismIdeal.Additive
public import TauCeti.CategoryTheory.Preadditive.MorphismIdeal.FactorThrough

/-!
# Projective stable quotients of exact categories

For an exact structure `E`, this file packages the objects that are both relatively projective
and relatively injective. It also defines `E.ProjectiveStableCategory`, the additive quotient by
morphisms factoring through relative projectives. When `E` is Frobenius, the projectives are
exactly the injectives, so this is the stable category obtained by killing the
projective-injective objects.

The quotient is formed with the general morphism-ideal API. In particular, it has the same
objects as the original category, while a morphism becomes zero precisely when it factors
through a relative projective. An object becomes zero precisely when it is relatively
projective; under the Frobenius hypothesis this is equivalently relative injectivity or membership
in the projective-injective class.

This additive category is the input to Happel's construction of the suspension and distinguished
triangles. No triangulated structure is asserted here: that construction requires the full
Frobenius hypothesis and choices of projective-injective conflations.

## Main definitions

* `TauCeti.ExactStructure.projectiveInjective`: the objects that are both projective and
  injective relative to an exact structure.
* `TauCeti.ExactStructure.ProjectiveInjective`: their full subcategory.
* `TauCeti.ExactStructure.projectiveStableIdeal`: the ideal of maps generated by factorizations
  through relative projectives.
* `TauCeti.ExactStructure.ProjectiveStableCategory`: the quotient by `projectiveStableIdeal`.
* `TauCeti.ExactStructure.projectiveStableFunctor`: the quotient functor to the projective stable
  category.
* `TauCeti.ExactStructure.projectiveStableIsoBiprod`: the isomorphism `Y ≅ P ⊞ Y` in the stable
  category attached to a relatively projective `P`.

## References

* Dieter Happel, *Triangulated Categories in the Representation Theory of Finite Dimensional
  Algebras*, Chapter I, Section 2.
* Theo Bühler, *Exact Categories*, Expositiones Mathematicae **28** (2010), 1–69,
  <https://arxiv.org/abs/0811.1480>, Sections 11–13.
-/

public section

namespace TauCeti

open CategoryTheory CategoryTheory.Limits ZeroObject

universe v u

variable {C : Type u} [Category.{v} C] [Preadditive C] [HasZeroObject C]
  [HasBinaryBiproducts C]

namespace ExactStructure

variable (E : ExactStructure C)

/-- The objects that are both projective and injective relative to `E`. For a Frobenius exact
structure this agrees with either one of those two object properties. -/
def projectiveInjective : ObjectProperty C :=
  E.isProjective ⊓ E.isInjective

/-- Membership in the projective-injective class means simultaneous relative projectivity and
relative injectivity. -/
@[simp]
theorem projectiveInjective_iff (X : C) :
    E.projectiveInjective X ↔ E.isProjective X ∧ E.isInjective X :=
  Iff.rfl

/-- The projective-injective objects form a replete class stable under retracts. -/
instance : E.projectiveInjective.IsStableUnderRetracts where
  of_retract r h :=
    ⟨E.isProjective.prop_of_retract r h.1, E.isInjective.prop_of_retract r h.2⟩

/-- The projective-injective class contains a zero object. -/
instance : E.projectiveInjective.ContainsZero where
  exists_zero := ⟨0, isZero_zero C,
    ⟨E.isProjective.prop_of_isZero (isZero_zero C),
      E.isInjective.prop_of_isZero (isZero_zero C)⟩⟩

/-- Binary biproducts of projective-injective objects are projective-injective. -/
instance : E.projectiveInjective.IsClosedUnderBinaryProducts :=
  ObjectProperty.isClosedUnderBinaryProducts_of_prop_biprod E.projectiveInjective
    fun _ _ h₁ h₂ ↦ ⟨E.isProjective_biprod h₁.1 h₂.1,
      E.isInjective_biprod h₁.2 h₂.2⟩

/-- The projective-injective class is closed under all finite products, hence under finite
biproducts in the ambient preadditive category. -/
noncomputable instance : E.projectiveInjective.IsClosedUnderFiniteProducts := by
  let _ : HasFiniteProducts C := hasFiniteProducts_of_has_binary_and_terminal
  exact ObjectProperty.IsClosedUnderFiniteProducts.mk'

/-- In a Frobenius exact structure, the projective-injective class is the class of relative
projectives. -/
theorem IsFrobenius.projectiveInjective_eq_isProjective {E : ExactStructure C}
    (hE : E.IsFrobenius) : E.projectiveInjective = E.isProjective := by
  apply le_antisymm inf_le_left
  intro X hX
  exact ⟨hX, (hE.projective_iff_injective X).mp hX⟩

/-- In a Frobenius exact structure, the projective-injective class is the class of relative
injectives. -/
theorem IsFrobenius.projectiveInjective_eq_isInjective {E : ExactStructure C}
    (hE : E.IsFrobenius) : E.projectiveInjective = E.isInjective := by
  apply le_antisymm inf_le_right
  intro X hX
  exact ⟨(hE.projective_iff_injective X).mpr hX, hX⟩

/-- The full subcategory of objects that are both projective and injective relative to `E`. -/
abbrev ProjectiveInjective := E.projectiveInjective.FullSubcategory

/-- The ideal generated by morphisms factoring through relative projective objects. For a
Frobenius exact structure these are exactly the projective-injective objects. -/
def projectiveStableIdeal : MorphismIdeal C :=
  E.isProjective.factorIdeal

/-- The projective stable category of `E`, formed by quotienting morphisms by those factoring
through relative projectives. This is the projective-injective stable category when `E` is
Frobenius. -/
abbrev ProjectiveStableCategory := E.projectiveStableIdeal.Quotient

/-- The quotient functor from an exact category to its projective stable category. -/
abbrev projectiveStableFunctor : CategoryTheory.Functor C E.ProjectiveStableCategory :=
  E.projectiveStableIdeal.quotientFunctor

/-- Membership in the projective stable ideal is equivalent to factoring through a relative
projective. -/
@[simp]
theorem mem_projectiveStableIdeal_iff {X Y : C} {f : X ⟶ Y} :
    f ∈ E.projectiveStableIdeal.hom X Y ↔ E.isProjective.FactorsThrough f := by
  rw [projectiveStableIdeal, ObjectProperty.mem_factorIdeal_iff]

/-- In a Frobenius exact structure, the projective stable ideal is generated by factorizations
through the projective-injective objects. -/
theorem IsFrobenius.projectiveStableIdeal_eq_factorIdeal {E : ExactStructure C}
    (hE : E.IsFrobenius) :
    E.projectiveStableIdeal = E.projectiveInjective.factorIdeal := by
  rw [projectiveStableIdeal, hE.projectiveInjective_eq_isProjective]

/-- A morphism becomes zero in the projective stable category exactly when it factors through a
relative projective. -/
@[simp high]
theorem projectiveStableFunctor_map_eq_zero_iff {X Y : C} {f : X ⟶ Y} :
    E.projectiveStableFunctor.map f = 0 ↔ E.isProjective.FactorsThrough f := by
  rw [MorphismIdeal.quotientFunctor_map_eq_zero_iff, mem_projectiveStableIdeal_iff]

/-- For a Frobenius exact structure, a morphism becomes zero in the projective stable category
exactly when it factors through a projective-injective object. -/
theorem IsFrobenius.projectiveStableFunctor_map_eq_zero_iff {E : ExactStructure C}
    (hE : E.IsFrobenius) {X Y : C} {f : X ⟶ Y} :
    E.projectiveStableFunctor.map f = 0 ↔ E.projectiveInjective.FactorsThrough f := by
  rw [ExactStructure.projectiveStableFunctor_map_eq_zero_iff E,
    hE.projectiveInjective_eq_isProjective]

/-- An object becomes zero in the projective stable category exactly when it is relatively
projective. -/
@[simp high]
theorem isZero_projectiveStableFunctor_obj_iff (X : C) :
    IsZero (E.projectiveStableFunctor.obj X) ↔ E.isProjective X := by
  rw [MorphismIdeal.isZero_quotientFunctor_obj_iff, mem_projectiveStableIdeal_iff,
    ObjectProperty.factorsThrough_id_iff]

/-- For a Frobenius exact structure, an object becomes zero in the projective stable category
exactly when it is projective-injective. -/
theorem IsFrobenius.isZero_projectiveStableFunctor_obj_iff {E : ExactStructure C}
    (hE : E.IsFrobenius) (X : C) :
    IsZero (E.projectiveStableFunctor.obj X) ↔ E.projectiveInjective X :=
  (ExactStructure.isZero_projectiveStableFunctor_obj_iff E X).trans (by
    rw [hE.projectiveInjective_eq_isProjective])

/-- For a Frobenius exact structure, an object becomes zero in the projective stable category
exactly when it is relatively injective. -/
theorem IsFrobenius.isZero_projectiveStableFunctor_obj_iff_isInjective {E : ExactStructure C}
    (hE : E.IsFrobenius) (X : C) :
    IsZero (E.projectiveStableFunctor.obj X) ↔ E.isInjective X :=
  (ExactStructure.isZero_projectiveStableFunctor_obj_iff E X).trans
    (hE.projective_iff_injective X)

/-- A relatively projective summand is invisible in the projective stable category: the
biproduct inclusion `Y ⟶ P ⊞ Y` becomes an isomorphism there, with inverse the projection. -/
noncomputable def projectiveStableIsoBiprod {P : C} (hP : E.isProjective P) (Y : C) :
    E.projectiveStableFunctor.obj Y ≅ E.projectiveStableFunctor.obj (P ⊞ Y) where
  hom := E.projectiveStableFunctor.map biprod.inr
  inv := E.projectiveStableFunctor.map biprod.snd
  hom_inv_id := by
    rw [← Functor.map_comp, biprod.inr_snd, E.projectiveStableFunctor.map_id]
  inv_hom_id := by
    have hfst : E.projectiveStableFunctor.map
        ((biprod.fst : P ⊞ Y ⟶ P) ≫ (biprod.inl : P ⟶ P ⊞ Y)) = 0 := by
      rw [projectiveStableFunctor_map_eq_zero_iff]
      exact ObjectProperty.factorsThrough_comp E.isProjective hP _ _
    have hsplit : (biprod.snd : P ⊞ Y ⟶ Y) ≫ biprod.inr =
        𝟙 (P ⊞ Y) - biprod.fst ≫ (biprod.inl : P ⟶ P ⊞ Y) := by
      rw [← biprod.total]
      abel
    rw [← Functor.map_comp, hsplit, Functor.map_sub, hfst, sub_zero,
      E.projectiveStableFunctor.map_id]

/-- The comparison with a relatively projective summand is the biproduct inclusion. -/
@[simp]
theorem projectiveStableIsoBiprod_hom {P : C} (hP : E.isProjective P) (Y : C) :
    (E.projectiveStableIsoBiprod hP Y).hom = E.projectiveStableFunctor.map biprod.inr :=
  (rfl)

/-- The inverse comparison with a relatively projective summand is the biproduct projection. -/
@[simp]
theorem projectiveStableIsoBiprod_inv {P : C} (hP : E.isProjective P) (Y : C) :
    (E.projectiveStableIsoBiprod hP Y).inv = E.projectiveStableFunctor.map biprod.snd :=
  (rfl)

/-- Two morphisms `φ ψ : S ⟶ T` of short complexes out of a conflation `S`, agreeing on first
terms, induce the same map on third terms in the projective stable category once the middle term
of `T` is relatively projective: `φ.τ₃ - ψ.τ₃` factors through `T.X₂`. -/
theorem projectiveStableFunctor_map_τ₃_eq_of_τ₁_eq {S T : ShortComplex C} (hS : E.Conflation S)
    (hT : E.isProjective T.X₂) {φ ψ : S ⟶ T} (h : φ.τ₁ = ψ.τ₁) :
    E.projectiveStableFunctor.map φ.τ₃ = E.projectiveStableFunctor.map ψ.τ₃ := by
  have hkc := E.isKernelCokernelPair S hS
  have := hkc.epi_g
  have hb : S.f ≫ (φ.τ₂ - ψ.τ₂) = 0 := by
    rw [Preadditive.comp_sub, ← φ.comm₁₂, ← ψ.comm₁₂, h, sub_self]
  have hdiff : φ.τ₃ - ψ.τ₃ = hkc.desc _ hb ≫ T.g := by
    rw [← cancel_epi S.g, Preadditive.comp_sub, ← φ.comm₂₃, ← ψ.comm₂₃, ← Preadditive.sub_comp,
      ← Category.assoc, hkc.g_desc]
  rw [← sub_eq_zero, ← Functor.map_sub, projectiveStableFunctor_map_eq_zero_iff, hdiff]
  exact ObjectProperty.factorsThrough_comp E.isProjective hT _ _

/-- Two morphisms `φ ψ : S ⟶ T` of short complexes into a conflation `T`, agreeing on third
terms, induce the same map on first terms in the projective stable category once the middle term
of `S` is relatively projective: `φ.τ₁ - ψ.τ₁` factors through `S.X₂`. -/
theorem projectiveStableFunctor_map_τ₁_eq_of_τ₃_eq {S T : ShortComplex C} (hT : E.Conflation T)
    (hS : E.isProjective S.X₂) {φ ψ : S ⟶ T} (h : φ.τ₃ = ψ.τ₃) :
    E.projectiveStableFunctor.map φ.τ₁ = E.projectiveStableFunctor.map ψ.τ₁ := by
  have hkc := E.isKernelCokernelPair T hT
  have := hkc.mono_f
  have hb : (φ.τ₂ - ψ.τ₂) ≫ T.g = 0 := by
    rw [Preadditive.sub_comp, φ.comm₂₃, ψ.comm₂₃, h, sub_self]
  have hdiff : φ.τ₁ - ψ.τ₁ = S.f ≫ hkc.lift _ hb := by
    rw [← cancel_mono T.f, Preadditive.sub_comp, φ.comm₁₂, ψ.comm₁₂, ← Preadditive.comp_sub,
      Category.assoc, hkc.lift_f]
  rw [← sub_eq_zero, ← Functor.map_sub, projectiveStableFunctor_map_eq_zero_iff, hdiff]
  exact ObjectProperty.factorsThrough_comp E.isProjective hS _ _

/-- A square on the first two terms which commutes in the stable quotient extends to a
morphism of short complexes after changing only the middle map by a projectively trivial map.
The source must be a conflation; the target need only be a short complex. It suffices that
every relatively projective object is relatively injective. -/
theorem exists_shortComplex_hom_of_stable_square
    (hPI : ∀ P, E.isProjective P → E.isInjective P)
    {S T : ShortComplex C} (hS : E.Conflation S) (a : S.X₁ ⟶ T.X₁) (b : S.X₂ ⟶ T.X₂)
    (hab : E.projectiveStableFunctor.map (S.f ≫ b) =
      E.projectiveStableFunctor.map (a ≫ T.f)) :
    ∃ φ : S ⟶ T, φ.τ₁ = a ∧ E.projectiveStableFunctor.map φ.τ₂ =
      E.projectiveStableFunctor.map b := by
  have hz : E.projectiveStableFunctor.map (S.f ≫ b - a ≫ T.f) = 0 := by
    simp [Functor.map_sub, hab]
  obtain ⟨P, hP, i, p, hp⟩ := (ObjectProperty.factorsThrough_iff _ _).1
    ((E.projectiveStableFunctor_map_eq_zero_iff).1 hz)
  let hI := hPI P hP
  let t := hI.factorThru (E.isInflation_f hS) i
  have ht : S.f ≫ t = i := hI.comp_factorThru (E.isInflation_f hS) i
  have hb : S.f ≫ (b - t ≫ p) = a ≫ T.f := by
    rw [Preadditive.comp_sub, ← Category.assoc, ht, ← hp]
    abel
  let c := (E.isKernelCokernelPair S hS).desc ((b - t ≫ p) ≫ T.g) (by
    rw [← Category.assoc, hb, Category.assoc, T.zero, comp_zero])
  let φ : S ⟶ T :=
    { τ₁ := a
      τ₂ := b - t ≫ p
      τ₃ := c
      comm₁₂ := hb.symm
      comm₂₃ := ((E.isKernelCokernelPair S hS).g_desc _ _).symm }
  refine ⟨φ, rfl, ?_⟩
  have htp : E.projectiveStableFunctor.map (t ≫ p) = 0 :=
    (E.projectiveStableFunctor_map_eq_zero_iff).2
      (ObjectProperty.factorsThrough_comp E.isProjective hP t p)
  simp only [φ, Functor.map_sub, htp, sub_zero]

end ExactStructure

end TauCeti
