/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.Algebra.Order.Group.Units
public import Mathlib.Algebra.Order.Monoid.Submonoid
public import Mathlib.RingTheory.Valuation.Basic
public import TauCeti.RingTheory.Valuation.ValueGroupTransport
public import TauCeti.Algebra.Order.Group.ConvexSubgroup

/-!
# The characteristic subgroup of a valuation, cofinal values, and fullness

The characteristic subgroup `cΓ_v` of Wedhorn, *Adic Spaces* (arXiv:1910.05934v1), 4.13 —
the convex subgroup of the value group generated by the attained values `≥ 1` — together
with the two value conditions of the `Spv (A, I)` theory of §4.3 and §7.1 that are stated
against it. They share a file because the fullness condition `Γ_v = cΓ_v` is precisely a
statement about this subgroup, and the `Spv (A, I)` membership criterion of Lemma 7.4
combines it with cofinality. Both are formulated
on the **value group** of `v` — Mathlib's `v.ValueGroup₀`, via the restricted
valuation `v.restrict` — not on the ambient codomain, so they are invariant under valuation
equivalence (`IsEquiv.cofinalValue_iff`, `IsEquiv.hasFullCharacteristicGroup_iff`) and can
be consumed on points of the valuation spectrum:

* a value `v a` is *cofinal* if its powers fall below every positive element of the value
  group — the condition on ideals of definition in Wedhorn Lemma 7.1;
* `v` *has full characteristic group* if every positive element of the value group is
  bounded between `(v a)⁻¹` and `v a` for some `a` — the elementwise
  reading of "`Γ_v = cΓ_v`", for the characteristic subgroup `cΓ_v` of Wedhorn 4.13.

These are the two disjuncts of the membership criterion for `Spv (A, I)`: Wedhorn
Lemma 7.4 proves `cΓ_v(I) = Γ_v` equivalent to "`v a` is cofinal for every `a ∈ I`, or
`Γ_v = cΓ_v`". The *microbial* condition of Wedhorn Definition 5.46 (existence of a
dependent height-one valuation) is a genuinely different notion and is deliberately not
formalised here.

## Main definitions

* `Valuation.CofinalValue v a` : Powers of `v a` fall below every positive element
  of the value group of `v`.
* `Valuation.characteristicGenerators v` and
  `Valuation.characteristicSubgroup v` : The attained values `≥ 1` and the convex
  subgroup `cΓ_v` they generate.
* `Valuation.HasFullCharacteristicGroup v` : Every positive element of the value
  group of `v` is bounded by attained values.

## Main results

* `Valuation.exists_pow_lt_of_forall_cofinalValue` : one exponent serves finitely many
  cofinal values.
* `Valuation.mem_characteristicSubgroup_iff` : Membership in `cΓ_v` is bounding by a
  single attained value `≥ 1`.
* `Valuation.hasFullCharacteristicGroup_iff_characteristicSubgroup_eq_top` : The
  elementwise fullness condition is exactly `cΓ_v = Γ_v`.
* `Valuation.characteristicSubgroup_eq_comap_of_isEquiv` and
  `Valuation.valueGroupOrderIso_mem_characteristicSubgroup_iff` : `cΓ_v` is invariant
  under valuation equivalence, so it descends to points of the valuation spectrum.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, 4.13, Lemma 7.1, Lemma 7.4

The statements are adapted from the AINTLIB development (Apache 2.0), files
`projects/AdicSpaces/Adic spaces/SpvAI.lean` (the cofinal-value cluster) and
`projects/AdicSpaces/Adic spaces/CharacteristicSubgroup.lean` (the characteristic-group
cluster), reformulated on the value group.
-/

public section

namespace Valuation

open MonoidWithZeroHom

variable {A : Type*} [Ring A] {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
  {Γ₀' : Type*} [LinearOrderedCommGroupWithZero Γ₀']

/-! ### Cofinal values -/

/-- A value `v a` is **cofinal** if for every positive `γ` in the value group of `v` some
power `(v a) ^ n` lies strictly below `γ` (Wedhorn Lemma 7.1: the condition satisfied by
the elements of an ideal of definition). -/
def CofinalValue (v : Valuation A Γ₀) (a : A) : Prop :=
  ∀ γ : v.ValueGroup₀, 0 < γ → ∃ n : ℕ, v.restrict a ^ n < γ

/-- The defining property of a cofinal value, on the value group of `v`. -/
@[simp]
theorem cofinalValue_iff {v : Valuation A Γ₀} {a : A} :
    CofinalValue v a ↔ ∀ γ : v.ValueGroup₀, 0 < γ → ∃ n : ℕ, v.restrict a ^ n < γ :=
  Iff.rfl

/-- **A uniform exponent for finitely many cofinal values.** If every member of a finite set has
cofinal value, then a single exponent works for all of them at once.

No bound on the values need be assumed: cofinality already forces `v.restrict a ≤ 1`, by taking
`γ = 1`. That is what makes the exponent uniform, since raising a value `≤ 1` to a higher power
only decreases it, so the largest of the individual exponents serves. -/
theorem exists_pow_lt_of_forall_cofinalValue {v : Valuation A Γ₀} (S : Finset A)
    (hcof : ∀ a ∈ S, CofinalValue v a) {γ : v.ValueGroup₀} (hγ : 0 < γ) :
    ∃ n : ℕ, ∀ a ∈ S, v.restrict a ^ n < γ := by
  have hle : ∀ a ∈ S, v.restrict a ≤ 1 := fun a ha ↦ by
    obtain ⟨n, hn⟩ := hcof a ha 1 one_pos
    exact not_lt.mp fun h ↦ absurd hn (not_lt.mpr (one_le_pow₀ h.le))
  choose! f hf using fun a (ha : a ∈ S) ↦ hcof a ha γ hγ
  exact ⟨S.sup f, fun a ha ↦
    (pow_le_pow_right_of_le_one' (hle a ha) (Finset.le_sup ha)).trans_lt (hf a ha)⟩

/-- Cofinality transports along an equivalence of valuations, through the ordered
isomorphism of their value groups. -/
theorem CofinalValue.of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {a : A} (hv : CofinalValue v a) : CofinalValue w a := by
  intro γ hγ
  obtain ⟨n, hn⟩ := hv (h.orderMonoidIso.symm γ)
    (zero_lt_iff.mpr fun heq ↦ hγ.ne' (by simpa using congrArg h.orderMonoidIso heq))
  refine ⟨n, ?_⟩
  have := (map_lt_map_iff h.orderMonoidIso).mpr hn
  rw [map_pow, Valuation.IsEquiv.orderMonoidIso_spec] at this
  simpa using this

/-- Cofinality is invariant under valuation equivalence. -/
theorem IsEquiv.cofinalValue_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) {a : A} :
    CofinalValue v a ↔ CofinalValue w a :=
  ⟨fun hv ↦ hv.of_isEquiv h, fun hw ↦ hw.of_isEquiv h.symm⟩

/-! ### The full-characteristic-group condition -/

/-- A valuation **has full characteristic group** if every positive element of its value
group is bounded between `(v a)⁻¹` and `v a` for some `a` — the elementwise form of
"`Γ_v = cΓ_v`", for the characteristic subgroup `cΓ_v` of Wedhorn 4.13. Such a witness
automatically satisfies `1 ≤ v.restrict a`, since the two bounds force `x⁻¹ ≤ x`. This is
the second disjunct of Wedhorn Lemma 7.4(ii); it is weaker than the *microbial* condition
of Wedhorn Definition 5.46 (on a field it holds for every valuation). -/
def HasFullCharacteristicGroup (v : Valuation A Γ₀) : Prop :=
  ∀ γ : v.ValueGroup₀, 0 < γ →
    ∃ a : A, (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a

/-- The defining property of the full-characteristic-group condition. -/
@[simp]
theorem hasFullCharacteristicGroup_iff {v : Valuation A Γ₀} :
    HasFullCharacteristicGroup v ↔
      ∀ γ : v.ValueGroup₀, 0 < γ →
        ∃ a : A, (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a :=
  Iff.rfl

/-- A bounding witness is automatically at least `1`: the two bounds force
`x⁻¹ ≤ x` at a positive element. -/
private theorem one_le_of_inv_le_of_le {v : Valuation A Γ₀}
    {x γ : v.ValueGroup₀} (hγ : 0 < γ)
    (h1 : x⁻¹ ≤ γ) (h2 : γ ≤ x) : 1 ≤ x := by
  by_contra hx
  push Not at hx
  have hx0 : 0 < x := hγ.trans_le h2
  have h3 : (1 : v.ValueGroup₀) < x⁻¹ := (one_lt_inv₀ hx0).mpr hx
  exact absurd ((h1.trans h2).trans hx.le) (not_le.mpr h3)

/-- Strengthened elimination: a bounding witness for a positive `γ` can be taken with
`1 ≤ v.restrict a` alongside the two bounds. -/
theorem HasFullCharacteristicGroup.exists_one_le {v : Valuation A Γ₀}
    (h : HasFullCharacteristicGroup v) {γ : v.ValueGroup₀} (hγ : 0 < γ) :
    ∃ a : A, 1 ≤ v.restrict a ∧ (v.restrict a)⁻¹ ≤ γ ∧ γ ≤ v.restrict a := by
  obtain ⟨a, h1, h2⟩ := h γ hγ
  exact ⟨a, one_le_of_inv_le_of_le hγ h1 h2, h1, h2⟩

/-- The full-characteristic-group condition transports along an equivalence of
valuations, through the ordered isomorphism of their value groups. -/
theorem HasFullCharacteristicGroup.of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) (hv : HasFullCharacteristicGroup v) : HasFullCharacteristicGroup w := by
  intro γ hγ
  obtain ⟨a, ha_lo, ha_hi⟩ := hv (h.orderMonoidIso.symm γ)
    (zero_lt_iff.mpr fun heq ↦ hγ.ne' (by simpa using congrArg h.orderMonoidIso heq))
  refine ⟨a, ?_, ?_⟩
  · have := (map_le_map_iff h.orderMonoidIso).mpr ha_lo
    rw [map_inv₀, Valuation.IsEquiv.orderMonoidIso_spec] at this
    simpa using this
  · have := (map_le_map_iff h.orderMonoidIso).mpr ha_hi
    rw [Valuation.IsEquiv.orderMonoidIso_spec] at this
    simpa using this

/-- The full-characteristic-group condition is invariant under valuation equivalence. -/
theorem IsEquiv.hasFullCharacteristicGroup_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) :
    HasFullCharacteristicGroup v ↔ HasFullCharacteristicGroup w :=
  ⟨fun hv ↦ hv.of_isEquiv h, fun hw ↦ hw.of_isEquiv h.symm⟩

/-- Under the full-characteristic-group condition, every positive element of the value
group dominates the inverse of some nonzero value: the existence statement used in the
`Γ_v = cΓ_v` case of Wedhorn Lemma 7.10. -/
theorem HasFullCharacteristicGroup.exists_inv_le {v : Valuation A Γ₀}
    (h : HasFullCharacteristicGroup v)
    {γ : v.ValueGroup₀} (hγ : 0 < γ) :
    ∃ t : A, v.restrict t ≠ 0 ∧ (v.restrict t)⁻¹ ≤ γ := by
  obtain ⟨a, ha_inv_le, ha_le⟩ := h γ hγ
  exact ⟨a, (hγ.trans_le ha_le).ne', ha_inv_le⟩

/-! ### The characteristic subgroup -/

/-- The generators of the characteristic subgroup `cΓ_v` of Wedhorn 4.13: the values `≥ 1`
attained by `v`, as elements of the value group (Mathlib's `valueGroup.mk f r s`
represents `(f r)⁻¹ * f s`, so `valueGroup.mk (v : A →*₀ Γ₀) 1 a` is the value `v a`). -/
def characteristicGenerators (v : Valuation A Γ₀) : Set v.valueGroup :=
  {γ | 1 ≤ γ ∧ ∃ a : A, v.restrict a = (γ : v.ValueGroup₀)}

/-- Membership in the generating set: the attained values `≥ 1`, in the `v.restrict` form
consumers hold. -/
@[simp]
theorem mem_characteristicGenerators {v : Valuation A Γ₀} {γ : v.valueGroup} :
    γ ∈ characteristicGenerators v ↔
      1 ≤ γ ∧ ∃ a : A, v.restrict a = (γ : v.ValueGroup₀) :=
  Iff.rfl

/-- The **characteristic subgroup** `cΓ_v` of Wedhorn 4.13: the smallest convex subgroup of
the value group containing the values `≥ 1` attained by `v`. -/
noncomputable def characteristicSubgroup (v : Valuation A Γ₀) :
    TauCeti.ConvexSubgroup v.valueGroup :=
  TauCeti.ConvexSubgroup.closure (characteristicGenerators v)

/-- Universal property: `cΓ_v` lies inside a convex subgroup exactly when the attained
values `≥ 1` do. -/
@[simp]
theorem characteristicSubgroup_le_iff {v : Valuation A Γ₀}
    {H : TauCeti.ConvexSubgroup v.valueGroup} :
    characteristicSubgroup v ≤ H ↔ characteristicGenerators v ⊆ H :=
  TauCeti.ConvexSubgroup.closure_le

/-- The generators lie in the characteristic subgroup they generate. -/
theorem characteristicGenerators_subset_characteristicSubgroup (v : Valuation A Γ₀) :
    characteristicGenerators v ⊆ characteristicSubgroup v :=
  TauCeti.ConvexSubgroup.subset_closure _

/-- **Introduction rule.** An attained value `≥ 1` lies in the characteristic subgroup,
stated for the ordinary restricted value. -/
theorem mem_characteristicSubgroup_of_restrict {v : Valuation A Γ₀} {a : A}
    {γ : v.valueGroup} (h1 : 1 ≤ γ)
    (ha : v.restrict a = (γ : v.ValueGroup₀)) :
    γ ∈ characteristicSubgroup v :=
  characteristicGenerators_subset_characteristicSubgroup v ⟨h1, a, ha⟩

/-- The `valueGroup.mk` restatement of the introduction rule, for consumers already holding
a representation of the value. -/
theorem valueGroup_mk_mem_characteristicSubgroup_of_one_le
    {v : Valuation A Γ₀} {a : A}
    (h : v a ≠ 0)
    (h1 : 1 ≤ valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h) :
    valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h ∈ characteristicSubgroup v :=
  mem_characteristicSubgroup_of_restrict h1 (v.restrict_eq_mk h)

/-- An attained value at least `1` puts its class in `cΓ_v`. This is the form consumers hold,
since they meet `1 ≤ v a` rather than a bound in the value group. The nonvanishing hypothesis
is part of the statement, since the class `valueGroup.mk … h` is indexed by it. -/
theorem valueGroup_mk_mem_characteristicSubgroup_of_one_le_value {v : Valuation A Γ₀} {a : A}
    (h : v a ≠ 0) (h1 : 1 ≤ v a) :
    valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h ∈ characteristicSubgroup v := by
  refine valueGroup_mk_mem_characteristicSubgroup_of_one_le h ?_
  rw [← WithZero.coe_le_coe, ← v.restrict_eq_mk h]
  have : v.restrict 1 ≤ v.restrict a := v.restrict_le_iff.mpr (by simpa using h1)
  simpa using this

/-- Equivalent valuations have corresponding characteristic generators. -/
theorem characteristicGenerators_map_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {γ : v.valueGroup} (hγ : γ ∈ characteristicGenerators v) :
    h.valueGroupOrderIso γ ∈ characteristicGenerators w := by
  obtain ⟨h1, a, ha⟩ := hγ
  refine ⟨?_, a, ?_⟩
  · simpa using h.valueGroupOrderIso.map_le_map_iff'.mpr h1
  · rw [h.valueGroupOrderIso_coe, ← ha, h.orderMonoidIso_spec]

/-- **Invariance under valuation equivalence.** The characteristic subgroup is carried into
the characteristic subgroup by the induced value-group isomorphism. Applying this to `h.symm`
gives the converse inclusion, so `cΓ_v` is a genuine invariant of the equivalence class and
may be used on points of the valuation spectrum. -/
theorem characteristicSubgroup_le_comap_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) :
    characteristicSubgroup v ≤
      TauCeti.ConvexSubgroup.comap h.valueGroupOrderIso (characteristicSubgroup w) := by
  rw [characteristicSubgroup_le_iff]
  intro γ hγ
  exact TauCeti.ConvexSubgroup.mem_comap.mpr
    (characteristicGenerators_subset_characteristicSubgroup w
      (characteristicGenerators_map_of_isEquiv h hγ))

/-- Membership form of the invariance. -/
theorem mem_characteristicSubgroup_of_isEquiv {v : Valuation A Γ₀} {w : Valuation A Γ₀'}
    (h : v.IsEquiv w) {γ : v.valueGroup} (hγ : γ ∈ characteristicSubgroup v) :
    h.valueGroupOrderIso γ ∈ characteristicSubgroup w :=
  TauCeti.ConvexSubgroup.mem_comap.mp (characteristicSubgroup_le_comap_of_isEquiv h hγ)

/-! ### Fullness as a statement about the characteristic subgroup -/

/-- `1` is an attained value `≥ 1`. -/
private theorem one_mem_characteristicGenerators (v : Valuation A Γ₀) :
    (1 : v.valueGroup) ∈ characteristicGenerators v :=
  ⟨le_rfl, 1, by simp⟩

/-- The attained values `≥ 1` are closed under multiplication, because `v` is. -/
private theorem mul_mem_characteristicGenerators {v : Valuation A Γ₀}
    {γ δ : v.valueGroup} (hγ : γ ∈ characteristicGenerators v)
    (hδ : δ ∈ characteristicGenerators v) : γ * δ ∈ characteristicGenerators v := by
  obtain ⟨h1, a, ha⟩ := hγ
  obtain ⟨h2, b, hb⟩ := hδ
  refine ⟨one_le_mul h1 h2, a * b, ?_⟩
  rw [map_mul, ha, hb]
  simp

/-- **Elimination rule.** Membership in `cΓ_v` is bounding by a *single* attained value `≥ 1`.
The non-obvious direction is that one generator suffices: the attained values `≥ 1` are closed
under multiplication, so the elements they bound already form a convex subgroup. -/
theorem mem_characteristicSubgroup_iff {v : Valuation A Γ₀}
    {γ : v.valueGroup} :
    γ ∈ characteristicSubgroup v ↔
      ∃ g ∈ characteristicGenerators v, g⁻¹ ≤ γ ∧ γ ≤ g := by
  exact TauCeti.ConvexSubgroup.mem_closure_of_nonempty_of_mul_mem_of_one_le
    ⟨1, one_mem_characteristicGenerators v⟩
    (fun _ hx _ hy ↦ mul_mem_characteristicGenerators hx hy) (fun _ hg ↦ hg.1)

/-- **Fullness is exactly `Γ_v = cΓ_v`.** The elementwise condition of
`HasFullCharacteristicGroup` says every positive value is bounded by a *single* attained
value; that is equivalent to the characteristic subgroup exhausting the value group, because
the attained values `≥ 1` are multiplicatively closed and so a single bound already suffices
for the whole convex subgroup they generate. -/
theorem hasFullCharacteristicGroup_iff_characteristicSubgroup_eq_top {v : Valuation A Γ₀} :
    HasFullCharacteristicGroup v ↔ characteristicSubgroup v = ⊤ := by
  constructor
  · intro hv
    refine eq_top_iff.mpr fun γ _ ↦ ?_
    obtain ⟨a, hinv, hle⟩ := hv (γ : v.ValueGroup₀) (by simp)
    have hne : v.restrict a ≠ 0 := by
      intro hz
      rw [hz] at hle
      simp at hle
    have h0 : v a ≠ 0 := fun hz ↦
      hne (v.restrict_eq_zero_iff.mpr hz)
    have hga : v.restrict a = ((valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h0 :
      v.valueGroup) : v.ValueGroup₀) := v.restrict_eq_mk h0
    rw [hga, ← WithZero.coe_inv, WithZero.coe_le_coe] at hinv
    rw [hga, WithZero.coe_le_coe] at hle
    have h1g : (1 : v.valueGroup) ≤ valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h0 := by
      rcases le_total 1 (valueGroup.mk (v : A →*₀ Γ₀) 1 a (by simp) h0) with h | h
      · exact h
      · exact (one_le_inv'.mpr h).trans (hinv.trans hle)
    have hmem := mem_characteristicSubgroup_of_restrict h1g hga
    exact (characteristicSubgroup v).convex (inv_mem hmem) hmem hinv hle
  · intro hv γ hγ
    obtain ⟨δ, rfl⟩ := WithZero.ne_zero_iff_exists.mp hγ.ne'
    obtain ⟨g, hg, hgd, hdg⟩ :=
      mem_characteristicSubgroup_iff.mp (hv ▸ TauCeti.ConvexSubgroup.mem_top)
    obtain ⟨_, a, ha⟩ := hg
    refine ⟨a, ?_, ?_⟩
    · rw [ha, ← WithZero.coe_inv, WithZero.coe_le_coe]; exact hgd
    · rw [ha, WithZero.coe_le_coe]; exact hdg

/-- The generators correspond **exactly** under the induced value-group isomorphism: both
sides are indexed by the same ring, and `orderMonoidIso_spec` matches `v.restrict a` with
`w.restrict a`.

Not a `simp` lemma, though its subgroup counterpart is: `mem_characteristicGenerators` is
already the `simp` normal form for the left-hand side, so tagging this one fails `simpNF`
(the left-hand side rewrites to `1 ≤ …  ∧ ∃ a, w.restrict a = …` before it can fire). -/
theorem valueGroupOrderIso_mem_characteristicGenerators_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) {γ : v.valueGroup} :
    h.valueGroupOrderIso γ ∈ characteristicGenerators w ↔ γ ∈ characteristicGenerators v := by
  refine ⟨fun ⟨h1, a, ha⟩ ↦ ⟨?_, a, ?_⟩, characteristicGenerators_map_of_isEquiv h⟩
  · simpa using h.valueGroupOrderIso.map_le_map_iff'.mp (by simpa using h1)
  · have hspec : h.orderMonoidIso (v.restrict a) = w.restrict a := h.orderMonoidIso_spec a
    rw [ha, h.valueGroupOrderIso_coe] at hspec
    exact h.orderMonoidIso.toMulEquiv.injective hspec

/-- **`cΓ_v` is an invariant of the equivalence class**, in membership form. -/
@[simp]
theorem valueGroupOrderIso_mem_characteristicSubgroup_iff {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) {γ : v.valueGroup} :
    h.valueGroupOrderIso γ ∈ characteristicSubgroup w ↔ γ ∈ characteristicSubgroup v := by
  rw [mem_characteristicSubgroup_iff, mem_characteristicSubgroup_iff]
  constructor
  · rintro ⟨g, hg, hgγ, hγg⟩
    refine ⟨h.valueGroupOrderIso.symm g, ?_, ?_, ?_⟩
    · rw [← valueGroupOrderIso_mem_characteristicGenerators_iff h]
      simpa using hg
    · simpa using h.valueGroupOrderIso.symm.map_le_map_iff'.mpr hgγ
    · simpa using h.valueGroupOrderIso.symm.map_le_map_iff'.mpr hγg
  · rintro ⟨g, hg, hgγ, hγg⟩
    exact ⟨h.valueGroupOrderIso g,
      (valueGroupOrderIso_mem_characteristicGenerators_iff h).mpr hg,
      by simpa using h.valueGroupOrderIso.map_le_map_iff'.mpr hgγ,
      h.valueGroupOrderIso.map_le_map_iff'.mpr hγg⟩

/-- Equality form of the invariance: `cΓ_v` is the pullback of `cΓ_w`. -/
theorem characteristicSubgroup_eq_comap_of_isEquiv {v : Valuation A Γ₀}
    {w : Valuation A Γ₀'} (h : v.IsEquiv w) :
    characteristicSubgroup v =
      TauCeti.ConvexSubgroup.comap h.valueGroupOrderIso (characteristicSubgroup w) :=
  TauCeti.ConvexSubgroup.ext fun _ ↦
    ((valueGroupOrderIso_mem_characteristicSubgroup_iff h).symm.trans
      TauCeti.ConvexSubgroup.mem_comap.symm)

end Valuation
