/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Smooth.Jacobian
public import Mathlib.RingTheory.Smooth.StandardSmoothCotangent
public import Mathlib.RingTheory.Smooth.Locus

/-!
# Smooth coordinate charts of the nodal equation

The algebra `NodeAlgebra R a = R[x,y]/(xy-a)` is the local model for smoothing a node.
Inverting either coordinate gives a standard smooth algebra of relative dimension one.
Consequently a prime at which at least one coordinate is nonzero belongs to the smooth
locus. These assertions hold over any commutative base ring.

For a discrete valuation ring and `a = πⁿ`, this supplies the smooth charts away from
the origin in the local model used to resolve nodal curves.

## References

* Stacks Project, Example 55.14.1, Tag 0CDC.
-/

public section

noncomputable section

namespace TauCeti

open MvPolynomial Algebra

/-- The coordinate algebra of the equation `xy = a` over `R`. -/
def NodeAlgebra (R : Type*) [CommRing R] (a : R) :=
  MvPolynomial (Fin 2) R ⧸ Ideal.span {X 0 * X 1 - C a}

namespace NodeAlgebra

variable {R : Type*} [CommRing R] (a : R)

instance : CommRing (NodeAlgebra R a) :=
  inferInstanceAs (CommRing (MvPolynomial (Fin 2) R ⧸ Ideal.span {X 0 * X 1 - C a}))

instance : Algebra R (NodeAlgebra R a) :=
  inferInstanceAs (Algebra R (MvPolynomial (Fin 2) R ⧸ Ideal.span {X 0 * X 1 - C a}))

/-- The quotient algebra map from polynomials to the nodal algebra. -/
def mk : MvPolynomial (Fin 2) R →ₐ[R] NodeAlgebra R a :=
  Ideal.Quotient.mkₐ R _

/-- Every element of the nodal algebra is represented by a polynomial. -/
lemma mk_surjective : Function.Surjective (mk a) :=
  Ideal.Quotient.mk_surjective

/-- The kernel of the quotient map is generated by the nodal equation. -/
@[simp]
lemma ker_mk : RingHom.ker (mk a : MvPolynomial (Fin 2) R →+* NodeAlgebra R a) =
    Ideal.span {X 0 * X 1 - C a} :=
  Ideal.mk_ker

/-- The two coordinate functions on `xy = a`. -/
def coord (i : Fin 2) : NodeAlgebra R a :=
  mk a (X i)

/-- The quotient map sends each polynomial variable to its coordinate function. -/
@[simp]
lemma mk_X (i : Fin 2) :
    mk a (X i) = coord a i := (rfl)

/-- The defining equation of the nodal algebra. -/
@[simp]
lemma coord_zero_mul_coord_one :
    coord a 0 * coord a 1 = algebraMap R (NodeAlgebra R a) a := by
  have h : mk a (X 0 * X 1 - C a) = 0 := by
    apply (RingHom.mem_ker (f := (mk a).toRingHom)).mp
    rw [AlgHom.toRingHom_eq_coe, ker_mk]
    exact Ideal.subset_span (Set.mem_singleton _)
  simpa only [map_sub, map_mul, mk_X, sub_eq_zero, ← algebraMap_eq,
    AlgHom.commutes] using h

private lemma aeval_eq_zero_of_mem {A : Type*} [CommSemiring A] [Algebra R A] (x y : A)
    (h : x * y = algebraMap R A a) (p : MvPolynomial (Fin 2) R)
    (hp : p ∈ Ideal.span {X 0 * X 1 - C a}) : aeval ![x, y] p = 0 := by
  have hker : Ideal.span {X (0 : Fin 2) * X 1 - C a} ≤
      RingHom.ker (aeval ![x, y]).toRingHom := by
    rw [Ideal.span_singleton_le_iff_mem, RingHom.mem_ker]
    simp only [sub_eq_add_neg, ← map_neg C, AlgHom.toRingHom_eq_coe, AlgHom.coe_toRingHom,
      map_add, map_mul, aeval_X, aeval_C, Matrix.cons_val_zero,
      Matrix.cons_val_one, h]
    rw [← map_add, add_neg_cancel, map_zero]
  exact RingHom.mem_ker.mp (hker hp)

/-- Evaluate the nodal algebra at two elements satisfying its defining equation. -/
def lift {A : Type*} [CommSemiring A] [Algebra R A] (x y : A)
    (h : x * y = algebraMap R A a) : NodeAlgebra R a →ₐ[R] A :=
  Ideal.Quotient.liftₐ _ (aeval ![x, y]) (aeval_eq_zero_of_mem a x y h)

/-- Evaluation on a polynomial representative is polynomial evaluation at the two elements. -/
@[simp]
lemma lift_mk {A : Type*} [CommSemiring A] [Algebra R A] (x y : A)
    (h : x * y = algebraMap R A a) (p : MvPolynomial (Fin 2) R) :
    lift a x y h (mk a p) = aeval ![x, y] p :=
  AlgHom.congr_fun (Ideal.Quotient.liftₐ_comp _ _ (aeval_eq_zero_of_mem a x y h)) p

/-- Evaluation sends the first coordinate to the chosen first element. -/
@[simp]
lemma lift_coord_zero {A : Type*} [CommSemiring A] [Algebra R A] (x y : A)
    (h : x * y = algebraMap R A a) : lift a x y h (coord a 0) = x := by
  simp only [coord, lift_mk, aeval_X, Matrix.cons_val_zero]

/-- Evaluation sends the second coordinate to the chosen second element. -/
@[simp]
lemma lift_coord_one {A : Type*} [CommSemiring A] [Algebra R A] (x y : A)
    (h : x * y = algebraMap R A a) : lift a x y h (coord a 1) = y := by
  simp only [coord, lift_mk, aeval_X, Matrix.cons_val_one, Matrix.cons_val_zero]

/-- Algebra maps out of the nodal algebra are determined by the two coordinates. -/
@[ext]
lemma hom_ext {A : Type*} [Semiring A] [Algebra R A]
    {f g : NodeAlgebra R a →ₐ[R] A}
    (h₀ : f (coord a 0) = g (coord a 0))
    (h₁ : f (coord a 1) = g (coord a 1)) : f = g := by
  apply Ideal.Quotient.algHom_ext
  apply MvPolynomial.algHom_ext
  intro i
  fin_cases i
  · exact h₀
  · exact h₁

private def presentation : Presentation R (NodeAlgebra R a) (Fin 2) Unit :=
  (Presentation.naive (v := fun _ : Unit ↦ X 0 * X 1 - C a)).ofAlgEquiv
    (Ideal.quotientEquivAlgOfEq R (by simp))

/-- The nodal equation is an algebra of finite presentation over its coefficient ring. -/
instance : FinitePresentation R (NodeAlgebra R a) :=
  (presentation a).finitePresentation_of_isFinite

private def prePresentation (i : Fin 2) :
    PreSubmersivePresentation R (NodeAlgebra R a) (Fin 2) Unit where
  __ := presentation a
  map _ := 1 - i
  map_inj := Function.injective_of_subsingleton _

private lemma prePresentation_jacobian (i : Fin 2) :
    (prePresentation a i).jacobian = coord a i := by
  rw [PreSubmersivePresentation.jacobian_eq_jacobiMatrix_det, Matrix.det_unique]
  rw [PreSubmersivePresentation.jacobiMatrix_apply, Generators.algebraMap_apply]
  -- Identify the fields of the local `prePresentation` wrapper, which has no projection API.
  change aeval (presentation a).val
    (pderiv (1 - i) ((presentation a).relation ())) = coord a i
  have hrelation : (presentation a).relation () = X 0 * X 1 - C a :=
    (Presentation.ofAlgEquiv_relation _ _ ()).trans (Presentation.naive_relation_apply _ _ ())
  have hderiv : pderiv (1 - i) (X 0 * X 1 - C a) = X i := by
    fin_cases i
    -- Normalize the two closed `Fin 2` subtractions before applying the derivative lemmas.
    · change pderiv 1 (X 0 * X 1 - C a) = X 0
      simp only [map_sub, pderiv_mul, pderiv_X_of_ne (by decide : (0 : Fin 2) ≠ 1),
        pderiv_X_self, pderiv_C, zero_mul, mul_one, zero_add, sub_zero]
    · change pderiv 0 (X 0 * X 1 - C a) = X 1
      simp only [map_sub, pderiv_mul, pderiv_X_of_ne (by decide : (1 : Fin 2) ≠ 0),
        pderiv_X_self, pderiv_C, one_mul, mul_zero, add_zero, sub_zero]
  rw [hrelation, hderiv, aeval_X]
  -- Identify the generator of the local presentation with its transported quotient class.
  change (Ideal.quotientEquivAlgOfEq R _)
    (Ideal.Quotient.mk _ (X i)) = coord a i
  rw [Ideal.quotientEquivAlgOfEq_mk]
  rfl

/-- Each coordinate chart of `xy = a` is standard smooth of relative dimension one. -/
theorem isStandardSmoothOfRelativeDimension_localizationAway_coord (i : Fin 2) :
    IsStandardSmoothOfRelativeDimension 1 R (Localization.Away (coord a i)) := by
  have : IsLocalization.Away (prePresentation a i).jacobian
      (Localization.Away (coord a i)) := by
    rw [prePresentation_jacobian]
    infer_instance
  simpa [Presentation.dimension] using
    (prePresentation a i).isStandardSmoothOfRelativeDimension_localizationAway
      (Localization.Away (coord a i))

/-- The complement of either coordinate's zero locus lies in the smooth locus of `xy = a`. -/
theorem basicOpen_coord_subset_smoothLocus (i : Fin 2) :
    (PrimeSpectrum.basicOpen (coord a i) : Set (PrimeSpectrum (NodeAlgebra R a))) ⊆
      Algebra.smoothLocus R (NodeAlgebra R a) := by
  have := (isStandardSmoothOfRelativeDimension_localizationAway_coord a i).isStandardSmooth
  exact Algebra.basicOpen_subset_smoothLocus_iff_smooth.mpr inferInstance

/-- A point of `xy = a` is smooth whenever at least one coordinate is outside its prime ideal. -/
theorem isSmoothAt_of_coord_notMem (p : Ideal (NodeAlgebra R a)) [p.IsPrime]
    (h : ∃ i, coord a i ∉ p) : Algebra.IsSmoothAt R p := by
  obtain ⟨i, hi⟩ := h
  exact basicOpen_coord_subset_smoothLocus a i
    ((PrimeSpectrum.mem_basicOpen _ ⟨p, inferInstance⟩).mpr hi)

/-- If the smoothing parameter is invertible, the whole nodal algebra is standard smooth
of relative dimension one. This includes `xy = 1` and `xy = a` over a field with `a ≠ 0`. -/
theorem isStandardSmoothOfRelativeDimension_of_isUnit (ha : IsUnit a) :
    IsStandardSmoothOfRelativeDimension 1 R (NodeAlgebra R a) := by
  have hx : IsUnit (coord a 0) := by
    have h := ha.map (algebraMap R (NodeAlgebra R a))
    rw [← coord_zero_mul_coord_one] at h
    exact isUnit_of_mul_isUnit_left h
  let P : SubmersivePresentation R (NodeAlgebra R a) (Fin 2) Unit :=
    { prePresentation a 0 with
      jacobian_isUnit := by rwa [prePresentation_jacobian] }
  exact P.isStandardSmoothOfRelativeDimension (by simp [Presentation.dimension])

end NodeAlgebra

end TauCeti
