/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.Degeneracy
public import TauCeti.NumberTheory.ModularForms.Petersson.Orthogonal

/-!
# The old and new subspaces of `S_k(Γ₁(N))`

A cusp form of level `M` produces cusp forms of level `N` for every multiple `N` of `M`: if
`d * M ∣ N` then the level-raising operator `V_d`, `(V_d f)(τ) = f(dτ)` of
`TauCeti.CuspForm.levelRaise`, carries `S_k(Γ₁(M))` into `S_k(Γ₁(N))`. The **old subspace**
`S_k(Γ₁(N))ᵒˡᵈ` is the span of all of these images with `M` a *proper* divisor of `N`, and the
**new subspace** `S_k(Γ₁(N))ⁿᵉʷ` is its Petersson-orthogonal complement.

The properness condition is imposed as `M ≠ N`, which discards exactly one pair: `d * M ∣ N`
already forces `d = 1` when `M = N`, so the only excluded operator is the identity `V₁` at the
level itself. Every other pair contributes, including `M ∣ N` proper with `d = 1`, the plain
restriction of a lower-level form (`ofLe_mem_cuspFormsOld`).

The old subspace is stable under the diamond operators, because `V_d` intertwines them:
`⟨u⟩` at level `N` acts on `V_d f` as `⟨u mod M⟩` acts on `f`
(`TauCeti.CuspForm.diamondOpCusp_levelRaise`). This is the lemma behind the fixed-nebentypus
refinement `S_k(N, χ)ⁿᵉʷ = S_k(Γ₁(N))ⁿᵉʷ ⊓ S_k(N, χ)` of Layer 3 of the ModularForms roadmap,
which additionally needs the diamond operators to be Petersson-unitary and is carried out in
`TauCeti/NumberTheory/ModularForms/Newforms/Nebentypus.lean`.

The old subspace is likewise stable under the Hecke operators at primes `p` coprime to the level
(`TauCeti.heckeTCuspNat_mem_cuspFormsOld`, in
`TauCeti/NumberTheory/ModularForms/Newforms/HeckeStability.lean`), for the Hecke action
`TauCeti.HeckeRing.GL2.heckeTCuspNat` on cusp forms. The corresponding stability of the *new*
subspace is still missing.

## Main definitions

* `TauCeti.cuspFormsOld`: the old subspace `S_k(Γ₁(N))ᵒˡᵈ`.
* `TauCeti.cuspFormsNew`: the new subspace `S_k(Γ₁(N))ⁿᵉʷ`, the Petersson-orthogonal complement
  of the old one.
* `TauCeti.cuspFormsOldMultiples`: the part of the old subspace generated by the *new* forms at
  proper divisor levels that are multiples of a given `m`. No nebentypus condition is imposed on
  the generators, so this is an uncharactered auxiliary space.

## Main results

* `TauCeti.levelRaise_mem_cuspFormsOld` and `TauCeti.cuspFormsOld_le`: the introduction and
  elimination rules for the old subspace.
* `TauCeti.levelRaise_mem_cuspFormsOldMultiples` and `TauCeti.cuspFormsOldMultiples_le`: the
  introduction and elimination rules for the refined old subspace.
* `TauCeti.cuspFormsOldMultiples_le_cuspFormsOld` and
  `TauCeti.cuspFormsOldMultiples_le_of_dvd`: the refined old subspace sits inside the old
  subspace, and shrinks as the level condition tightens.
* `TauCeti.cuspFormsOldMultiples_one_eq_cuspFormsOld`: the old subspace is generated by the
  level-raised new subspaces of the proper divisor levels.
* `TauCeti.cuspFormsOld_le_of_prime`: the sharper elimination rule of Diamond–Shurman, in which
  only the two degeneracy maps `S_k(Γ₁(N/p)) → S_k(Γ₁(N))` at each prime `p ∣ N` are tested.
* `TauCeti.mem_cuspFormsNew_iff`: a form is new exactly when it is Petersson-orthogonal to
  every level-raised form from a proper divisor level.
* `TauCeti.disjoint_cuspFormsOld_cuspFormsNew`: the two subspaces meet only in `0`.
* `TauCeti.sup_cuspFormsOld_cuspFormsNew_eq_top`: the old and new subspaces span the full
  cusp-form space.
* `TauCeti.isCompl_cuspFormsOld_cuspFormsNew`: the two subspaces are complements, so every cusp
  form splits uniquely as an oldform plus a newform. The splitting map is Mathlib's
  `Submodule.projection` at this witness, which carries the reconstruction equation and the
  characterisations of its fixed points and kernel.
* `TauCeti.CuspForm.diamondOpCusp_levelRaise`: `V_d` intertwines the diamond operators, whence
  `TauCeti.diamondOpCusp_mem_cuspFormsOld`, the diamond stability of the old subspace.
* `TauCeti.cuspFormsOld_one`, `TauCeti.cuspFormsNew_one`: at level one there are no oldforms,
  so every cusp form is new.

## References

* [F. Diamond and J. Shurman, *A first course in modular forms*][diamondshurman2005],
  Section 5.6.
* Miyake, *Modular forms*, Section 4.6.
* AINTLIB's [`LeanModularForms/HeckeRIngs/GL2/Newforms/Basic.lean`](https://github.com/CBirkbeck/AINTLIB/blob/dev/leanmodularforms/projects/LeanModularForms/LeanModularForms/HeckeRIngs/GL2/Newforms/Basic.lean),
  by the LeanModularForms contributors (Apache-2.0), pinned at commit
  `2baa76f742bdb4fb8ee323fabba41203bd390e08`, for the `cuspFormsOld` and `cuspFormsNew` API and
  for the `IsCompl` statement of the old/new decomposition at lines 293-400. The `IsCompl` proof
  is not adapted from there — that source derives it through a real bilinear form, whereas here
  it is assembled from `CuspForm.isCompl_peterssonOrthogonal`.
-/

public noncomputable section

open Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup

open scoped MatrixGroups ModularForm Pointwise

namespace TauCeti

open _root_.CuspForm

variable {k : ℤ}

/-! ### The old subspace -/

/-- The **old subspace** `S_k(Γ₁(N))ᵒˡᵈ`: the subspace of `S_k(Γ₁(N))` spanned by the images of
the level-raising operators `V_d : S_k(Γ₁(M)) → S_k(Γ₁(N))` over all pairs `(M, d)` with
`d * M ∣ N` and `M` a proper divisor of `N`. Since `d * M ∣ N` forces `d = 1` when `M = N`, the
condition `M ≠ N` removes exactly the identity operator at level `N`. -/
def cuspFormsOld (N : ℕ) [NeZero N] (k : ℤ) :
    Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k) :=
  ⨆ (M : ℕ) (d : ℕ) (h : d * M ∣ N ∧ M ≠ N),
    have : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h.1)
    LinearMap.range (CuspForm.levelRaiseₗ (k := k) d (Gamma1_map_le_conjAct_scaleGL_of_dvd h.1))

variable {M d N : ℕ}

/-- **Introduction rule for the old subspace**: every level-raise from a proper divisor level
is old. -/
theorem levelRaise_mem_cuspFormsOld [NeZero N] (h : d * M ∣ N) (hM : M ≠ N)
    (k : ℤ) (f : CuspForm ((Gamma1 M).map (mapGL ℝ)) k) :
    haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h)
    CuspForm.levelRaise d (Gamma1_map_le_conjAct_scaleGL_of_dvd h) f ∈ cuspFormsOld N k :=
  let _ := NeZero.of_dvd (dvd_of_mul_right_dvd h)
  Submodule.mem_iSup_of_mem M (Submodule.mem_iSup_of_mem d
    (Submodule.mem_iSup_of_mem ⟨h, hM⟩ ⟨f, CuspForm.levelRaiseₗ_apply d _ f⟩))

/-- **Elimination rule for the old subspace**: a subspace containing every level-raise from a
proper divisor level contains the whole old subspace. -/
theorem cuspFormsOld_le [NeZero N] {V : Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)}
    (hV : ∀ (M d : ℕ) (h : d * M ∣ N), M ≠ N →
      ∀ f : CuspForm ((Gamma1 M).map (mapGL ℝ)) k,
        haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h)
        CuspForm.levelRaise d (Gamma1_map_le_conjAct_scaleGL_of_dvd h) f ∈ V) :
    cuspFormsOld N k ≤ V := by
  refine iSup_le fun M ↦ iSup_le fun d ↦ iSup_le fun h ↦ ?_
  have := NeZero.of_dvd (dvd_of_mul_right_dvd h.1)
  rintro _ ⟨f, rfl⟩
  rw [CuspForm.levelRaiseₗ_apply]
  exact hV M d h.1 h.2 f

/-- The restriction to level `N` of a cusp form of proper divisor level `M` is old: it is the
level-raise `V₁`. -/
theorem ofLe_mem_cuspFormsOld [NeZero N] (h : M ∣ N) (hM : M ≠ N) (k : ℤ)
    (f : CuspForm ((Gamma1 M).map (mapGL ℝ)) k) :
    _root_.CuspForm.ofLe (Gamma1_map_le_Gamma1_map_of_dvd h) f ∈
      cuspFormsOld N k := by
  have h1 : 1 * M ∣ N := by rwa [one_mul]
  have := levelRaise_mem_cuspFormsOld h1 hM k f
  -- At `d = 1`, level-raising is exactly restriction along the subgroup inclusion.
  rwa [_root_.CuspForm.levelRaise_one] at this

/-- **Level one has no oldforms**: `1` has no proper divisors. -/
@[simp]
theorem cuspFormsOld_one (k : ℤ) : cuspFormsOld 1 k = ⊥ :=
  le_bot_iff.mp <| cuspFormsOld_le fun _ d h hM _ ↦
    absurd (Nat.dvd_one.mp ((Dvd.intro_left d rfl).trans h)) hM

/-- **The old subspace is generated by the prime-level degeneracy maps.** Every level-raise
`V_d f` from a proper divisor level factors through an intermediate level `L` with `p * L = N`
for a prime `p`, the last step being `V₁` or `V_p`. So the definition above, a supremum over
all proper divisor levels, agrees with Diamond–Shurman's presentation of the old subspace by
the two degeneracy maps `S_k(Γ₁(N/p)) → S_k(Γ₁(N))` attached to each prime `p ∣ N`: a subspace
closed under those already contains every oldform.

The factorization is `V_d = V_p ∘ V_{d/p}` when a prime `p` divides `d`, and
`V₁ = V₁ ∘ V₁` through the level `N/p` for a prime `p` dividing `N/M` otherwise. -/
theorem cuspFormsOld_le_of_prime [NeZero N]
    {V : Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)}
    (hV : ∀ (p L : ℕ), p.Prime → ∀ (hpL : p * L = N) (d : ℕ) (hd : d = 1 ∨ d = p),
      ∀ g : CuspForm ((Gamma1 L).map (mapGL ℝ)) k,
        have hdvd : d * L ∣ N := by
          rcases hd with rfl | rfl
          · exact ⟨p, by rw [← hpL]; ring⟩
          · exact ⟨1, by rw [← hpL, mul_one]⟩
        haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd hdvd)
        CuspForm.levelRaise d (Gamma1_map_le_conjAct_scaleGL_of_dvd hdvd) g ∈ V) :
    cuspFormsOld N k ≤ V := by
  refine cuspFormsOld_le fun M d hdvd hM f ↦ ?_
  rcases eq_or_ne d 1 with rfl | hd1
  · -- `V₁` from a proper divisor level `M`: split off a prime factor `p` of `N / M`
    obtain ⟨m, hm⟩ : M ∣ N := by rwa [one_mul] at hdvd
    have hm1 : m ≠ 1 := fun h ↦ hM (by rw [hm, h, mul_one])
    obtain ⟨p, hp, t, rfl⟩ := Nat.exists_prime_and_dvd hm1
    have hpL : p * (M * t) = N := by rw [hm]; ring
    have : NeZero (M * t) := NeZero.of_dvd (Dvd.intro_left p hpL)
    have h1M : 1 * M ∣ M * t := ⟨t, by rw [one_mul]⟩
    have hmem := hV p (M * t) hp hpL 1 (Or.inl rfl)
      (CuspForm.levelRaise 1 (Gamma1_map_le_conjAct_scaleGL_of_dvd h1M) f)
    simpa only [CuspForm.levelRaise_levelRaise, one_mul] using hmem
  · -- `V_d` with `d ≠ 1`: split off a prime factor `q` of `d`
    obtain ⟨q, hq, e, rfl⟩ := Nat.exists_prime_and_dvd hd1
    obtain ⟨s, hs⟩ := id hdvd
    have hqL : q * (e * M * s) = N := by rw [hs]; ring
    have heN : e ∣ N := ⟨q * M * s, by rw [← hqL]; ring⟩
    have : NeZero e := NeZero.of_dvd heN
    have : NeZero (e * M * s) := NeZero.of_dvd (Dvd.intro_left q hqL)
    have heM : e * M ∣ e * M * s := ⟨s, rfl⟩
    have hmem := hV q (e * M * s) hq hqL q (Or.inr rfl)
      (CuspForm.levelRaise e (Gamma1_map_le_conjAct_scaleGL_of_dvd heM) f)
    simpa only [CuspForm.levelRaise_levelRaise, Nat.mul_comm e q] using hmem

/-! ### The new subspace -/

/-- The **new subspace** `S_k(Γ₁(N))ⁿᵉʷ`: the Petersson-orthogonal complement of the old
subspace inside `S_k(Γ₁(N))`. -/
def cuspFormsNew (N : ℕ) [NeZero N] (k : ℤ) :
    Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k) :=
  CuspForm.peterssonOrthogonal (cuspFormsOld N k)

/-- Defining equation for the sealed `cuspFormsNew`: it is the Petersson-orthogonal complement
of the old subspace. -/
lemma cuspFormsNew_def (N : ℕ) [NeZero N] (k : ℤ) :
    cuspFormsNew N k = CuspForm.peterssonOrthogonal (cuspFormsOld N k) := (rfl)

/-- **Newness is tested on the level-raises.** A cusp form of level `N` is new exactly when it
is Petersson-orthogonal to `V_d g` for every cusp form `g` of proper divisor level. -/
@[simp]
theorem mem_cuspFormsNew_iff [NeZero N] {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k} :
    f ∈ cuspFormsNew N k ↔ ∀ (M d : ℕ) (h : d * M ∣ N), M ≠ N →
      ∀ g : CuspForm ((Gamma1 M).map (mapGL ℝ)) k,
        haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h)
        peterssonInnerCosets
          (CuspForm.levelRaise d (Gamma1_map_le_conjAct_scaleGL_of_dvd h) g) f = 0 := by
  rw [cuspFormsNew]
  refine ⟨fun hf M d h hM g ↦ CuspForm.mem_peterssonOrthogonal_iff.mp hf _
    (levelRaise_mem_cuspFormsOld h hM k g), fun h ↦ ?_⟩
  rw [CuspForm.mem_peterssonOrthogonal_iff_le_ker]
  refine cuspFormsOld_le fun M d hdvd hM g ↦ ?_
  rw [LinearMap.mem_ker, CuspForm.peterssonInnerCosetsₛₗ_apply_apply,
    ← peterssonInnerCosets_conj_symm, h M d hdvd hM g, map_zero]

/-- **The old and new subspaces meet only in `0`**, by positive definiteness of the Petersson
product. -/
theorem disjoint_cuspFormsOld_cuspFormsNew (N : ℕ) [NeZero N] (k : ℤ) :
    Disjoint (cuspFormsOld N k) (cuspFormsNew N k) :=
  CuspForm.peterssonOrthogonal_disjoint _

/-- **The old and new subspaces span the full cusp-form space.** -/
theorem sup_cuspFormsOld_cuspFormsNew_eq_top (N : ℕ) [NeZero N] (k : ℤ) :
    cuspFormsOld N k ⊔ cuspFormsNew N k = ⊤ := by
  rw [cuspFormsNew]
  exact CuspForm.sup_peterssonOrthogonal_eq_top _

/-- **At level one every cusp form is new**, there being no oldforms to be orthogonal to. -/
@[simp]
theorem cuspFormsNew_one (k : ℤ) : cuspFormsNew 1 k = ⊤ := by
  rw [cuspFormsNew, cuspFormsOld_one, CuspForm.peterssonOrthogonal_bot]

/-! ### The old/new decomposition -/

/-- **The old and new subspaces are complements.** Diamond–Shurman (5.20):
`S_k(Γ₁(N)) = S_k(Γ₁(N))ᵒˡᵈ ⊕ S_k(Γ₁(N))ⁿᵉʷ`. -/
theorem isCompl_cuspFormsOld_cuspFormsNew (N : ℕ) [NeZero N] (k : ℤ) :
    IsCompl (cuspFormsOld N k) (cuspFormsNew N k) :=
  cuspFormsNew_def N k ▸ CuspForm.isCompl_peterssonOrthogonal (cuspFormsOld N k)

/-! ### The old subspace generated by newforms at prescribed levels -/

/-- The part of the old subspace generated by the **new** forms at proper divisor levels that are
multiples of `m`: the supremum of the `V_d`-images of `S_k(Γ₁(M))ⁿᵉʷ` over the pairs `(M, d)` with
`d * M ∣ N`, `M ≠ N` and `m ∣ M`.

The intended `m` is the conductor of a nebentypus character, which is why the level condition is
divisibility by `m`; but this is **not** Miyake's `S_k^♭(N, χ)` (p. 162). The generators here range
over the whole newspace `cuspFormsNew M k` at each eligible level, including forms of nebentypus
unrelated to `χ`, whereas Miyake's space is generated by the `χ`-isotypic newspaces together with
the character transition along each `M ∣ N`. Recovering `S_k^♭(N, χ)` needs those. This is an
uncharactered auxiliary subspace of the old subspace — neither containing nor contained in
Miyake's space in general — and it is what the inclusion into `cuspFormsOld` below is stated
for. -/
def cuspFormsOldMultiples (N : ℕ) [NeZero N] (k : ℤ) (m : ℕ) :
    Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k) :=
  ⨆ (M : ℕ) (d : ℕ) (h : d * M ∣ N ∧ M ≠ N ∧ m ∣ M),
    have : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h.1)
    have : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd h.1)
    (cuspFormsNew M k).map
      (CuspForm.levelRaiseₗ (k := k) d (Gamma1_map_le_conjAct_scaleGL_of_dvd h.1))

/-- **Introduction rule**: a newform at a proper divisor level divisible by `m`, level-raised,
lies in `cuspFormsOldMultiples`. -/
theorem levelRaise_mem_cuspFormsOldMultiples [NeZero N] {m : ℕ} (h : d * M ∣ N) (hM : M ≠ N)
    (hm : m ∣ M) (k : ℤ) (g : CuspForm ((Gamma1 M).map (mapGL ℝ)) k)
    (hg : haveI : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd h)
      g ∈ cuspFormsNew M k) :
    haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h)
    CuspForm.levelRaiseₗ (k := k) d (Gamma1_map_le_conjAct_scaleGL_of_dvd h) g ∈
      cuspFormsOldMultiples N k m :=
  let _ := NeZero.of_dvd (dvd_of_mul_right_dvd h)
  let _ := NeZero.of_dvd (dvd_of_mul_left_dvd h)
  Submodule.mem_iSup_of_mem M (Submodule.mem_iSup_of_mem d
    (Submodule.mem_iSup_of_mem ⟨h, hM, hm⟩ (Submodule.mem_map_of_mem hg)))

/-- **Newforms level-raised from proper divisor levels are old**, whatever the level condition
`m ∣ M` selects. Only `d * M ∣ N` and `M ≠ N` are used — the newness of the raised form and the
divisibility by `m` are both discarded, which is why one inclusion is elementary while the
reverse is not. -/
theorem cuspFormsOldMultiples_le_cuspFormsOld (N : ℕ) [NeZero N] (k : ℤ) (m : ℕ) :
    cuspFormsOldMultiples N k m ≤ cuspFormsOld N k := by
  refine iSup_le fun M ↦ iSup_le fun d ↦ iSup_le fun h ↦ ?_
  rintro x ⟨f, -, rfl⟩
  have : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h.1)
  -- the generator is a `levelRaiseₗ` application; `levelRaiseₗ_apply` is the bridge to the
  -- bare `levelRaise` that the old subspace's introduction rule is stated with
  simpa only [CuspForm.levelRaiseₗ_apply] using levelRaise_mem_cuspFormsOld h.1 h.2.1 k f

/-- **Elimination rule for the refined old subspace**: a subspace containing every level-raise of
a newform from a proper divisor level divisible by `m` contains the whole refined old subspace.

This is the companion to `levelRaise_mem_cuspFormsOldMultiples`, and it is what downstream
proofs use rather than the lattice lemmas directly. -/
theorem cuspFormsOldMultiples_le [NeZero N] {m : ℕ}
    {V : Submodule ℂ (CuspForm ((Gamma1 N).map (mapGL ℝ)) k)}
    (hV : ∀ (M d : ℕ) (h : d * M ∣ N), M ≠ N → m ∣ M →
      ∀ g : CuspForm ((Gamma1 M).map (mapGL ℝ)) k,
        haveI : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd h)
        g ∈ cuspFormsNew M k →
        haveI : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd h)
        CuspForm.levelRaise d (Gamma1_map_le_conjAct_scaleGL_of_dvd h) g ∈ V) :
    cuspFormsOldMultiples N k m ≤ V := by
  refine iSup_le fun M ↦ iSup_le fun d ↦ iSup_le fun h ↦ ?_
  have := NeZero.of_dvd (dvd_of_mul_right_dvd h.1)
  have := NeZero.of_dvd (dvd_of_mul_left_dvd h.1)
  rintro _ ⟨g, hg, rfl⟩
  -- Why consumers want this rule rather than the lattice lemmas: a bare `iSup_le` against a
  -- `Submodule.comap` leaves the `CompleteLattice` instance stuck on a metavariable, whereas an
  -- explicit `V` determines the ambient module. `levelRaiseₗ_apply` bridges the generator's
  -- `levelRaiseₗ` application to the bare `levelRaise` that `hV` is stated with.
  simpa only [CuspForm.levelRaiseₗ_apply] using hV M d h.1 h.2.1 h.2.2 g hg

/-- `cuspFormsOldMultiples` is monotone in the level condition: a coarser divisibility
requirement admits more generators. -/
theorem cuspFormsOldMultiples_le_of_dvd (N : ℕ) [NeZero N] (k : ℤ) {m m' : ℕ} (h : m' ∣ m) :
    cuspFormsOldMultiples N k m ≤ cuspFormsOldMultiples N k m' := by
  refine iSup_le fun M ↦ iSup_le fun d ↦ iSup_le fun hM ↦ ?_
  exact le_iSup_of_le M (le_iSup_of_le d
    (le_iSup_of_le ⟨hM.1, hM.2.1, h.trans hM.2.2⟩ le_rfl))

/-- **The old subspace is generated by the level-raised new subspaces**: every oldform of level
`Γ₁(N)` is a combination of forms `V_d g` with `g` new of a proper divisor level `M` and
`d * M ∣ N`. With `sup_cuspFormsOld_cuspFormsNew_eq_top` this is the spanning half of
Diamond–Shurman, Theorem 5.8.3. -/
theorem cuspFormsOldMultiples_one_eq_cuspFormsOld (N : ℕ) [NeZero N] (k : ℤ) :
    cuspFormsOldMultiples N k 1 = cuspFormsOld N k := by
  refine le_antisymm (cuspFormsOldMultiples_le_cuspFormsOld N k 1) ?_
  revert ‹NeZero N›
  induction N using Nat.strong_induction_on with
  | _ N ih =>
  intro _
  refine cuspFormsOld_le fun M d hdvd hM f ↦ ?_
  have : NeZero d := NeZero.of_dvd (dvd_of_mul_right_dvd hdvd)
  have : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd hdvd)
  have hMN : M < N :=
    (Nat.le_of_dvd (Nat.pos_of_neZero N) (dvd_of_mul_left_dvd hdvd)).lt_of_ne hM
  -- split `f` into its old and new parts at level `M`
  obtain ⟨o, ho, n, hn, rfl⟩ := Submodule.mem_sup.mp
    ((sup_cuspFormsOld_cuspFormsNew_eq_top M k).ge (Submodule.mem_top (x := f)))
  rw [← CuspForm.levelRaiseₗ_apply, map_add]
  refine add_mem ?_ (levelRaise_mem_cuspFormsOldMultiples hdvd hM (one_dvd M) k n hn)
  -- the old part is, by induction, generated by level-raised newforms of lower level
  refine cuspFormsOldMultiples_le (V := (cuspFormsOldMultiples N k 1).comap
    (CuspForm.levelRaiseₗ d (Gamma1_map_le_conjAct_scaleGL_of_dvd hdvd)))
    (fun M' d' h' hM' _ g hg ↦ ?_) (ih M hMN ho)
  have : NeZero d' := NeZero.of_dvd (dvd_of_mul_right_dvd h')
  have : NeZero M' := NeZero.of_dvd (dvd_of_mul_left_dvd h')
  have hdvd' : d' * d * M' ∣ N :=
    (dvd_of_eq (by ring) : d' * d * M' ∣ d * (d' * M')).trans
      ((mul_dvd_mul_left d h').trans hdvd)
  have hM'N : M' ≠ N :=
    ((Nat.le_of_dvd (Nat.pos_of_neZero M) (dvd_of_mul_left_dvd h')).trans_lt hMN).ne
  rw [Submodule.mem_comap, CuspForm.levelRaiseₗ_apply, CuspForm.levelRaise_levelRaise]
  simpa using levelRaise_mem_cuspFormsOldMultiples hdvd' hM'N (one_dvd M') k g hg

/-! ### Diamond stability of the old subspace -/

/-- **The old subspace is diamond-stable.** -/
theorem diamondOpCusp_mem_cuspFormsOld [NeZero N] (u : (ZMod N)ˣ)
    {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k} (hf : f ∈ cuspFormsOld N k) :
    diamondOpCusp k u f ∈ cuspFormsOld N k := by
  refine cuspFormsOld_le (V := (cuspFormsOld N k).comap (diamondOpCusp k u)) ?_ hf
  intro M d hdvd hM g
  have := NeZero.of_dvd (dvd_of_mul_left_dvd hdvd)
  rw [Submodule.mem_comap, CuspForm.diamondOpCusp_levelRaise hdvd]
  exact levelRaise_mem_cuspFormsOld hdvd hM k _

/-- The old subspace is diamond-stable, in the `Submodule.map` form. -/
theorem cuspFormsOld_map_diamondOpCusp_le [NeZero N] (u : (ZMod N)ˣ) (k : ℤ) :
    (cuspFormsOld N k).map (diamondOpCusp k u) ≤ cuspFormsOld N k := by
  rw [Submodule.map_le_iff_le_comap]
  exact fun _ hf ↦ diamondOpCusp_mem_cuspFormsOld u hf

end TauCeti
