/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.Fricke.OldSpace
public import TauCeti.NumberTheory.ModularForms.Newforms.MultiplicityOne
public import TauCeti.NumberTheory.ModularForms.Newforms.Newform
import TauCeti.NumberTheory.ModularForms.AtkinLehner.Hecke
import TauCeti.NumberTheory.ModularForms.Parity
import TauCeti.NumberTheory.ModularForms.Petersson.AtkinLehner
import TauCeti.NumberTheory.ModularForms.TrivialNebentypus

/-!
# The Fricke sign of a newform of trivial nebentypus

For a newform `f` of level `N`, weight `k` and trivial nebentypus, the normalized Fricke
operator `𝒲_N f = (√N) ^ (2 - k) • (f ∣[k] !![0, -1; N, 0])` is `ε_N · f` for a sign
`ε_N ∈ {1, -1}`, the **Fricke sign** (or Fricke eigenvalue) of `f`. The sign of the functional
equation of `L(s, f)` is `i ^ k · ε_N`.

The argument has three inputs.

* `𝒲_N` preserves the new subspace. It preserves the old subspace
  (`TauCeti.normalizedFrickeOperatorCusp_mem_cuspFormsOld`) and its Petersson adjoint is
  `(-1) ^ k • 𝒲_N`, so it preserves the orthogonal complement.
* On `S_k(N, 1)` the operator `𝒲_N` commutes with the Hecke operators `Tₙ` for `n` prime to `N`.
  At the trivial character the nebentypus-twisted Hecke sum is the plain `Γ₀(N)` slash sum
  (`HeckeRing.GL2.twistedHeckeSlashSum_eq_heckeSlashSum`). That sum commutes with the Fricke
  slash coset by coset
  (`TauCeti.commute_atkinLehnerOperatorCusp_heckeSlashGamma0CuspFormEnd`), and the ring elements
  `Tₙ` with `(n, N) = 1` are generated by double cosets of determinant prime to `N`
  (`HeckeRing.GL2.heckeTCompositeGamma0_mem_closure_coprimeDetCoset`).
* Multiplicity one, in the form
  `HeckeRing.GL2.exists_eq_smul_of_commute_heckeRingHomCusp_of_mem_cuspFormsNew` for a
  commuting involution. `𝒲_N f` is then a good Hecke eigenvector in the new part with the same
  eigenvalues as `f`, hence a multiple `ε • f`, and `𝒲_N ∘ 𝒲_N = (-1) ^ k` forces `ε ^ 2 = 1`,
  since `(-1) ^ k = 1` by the parity lemma when `f ≠ 0` has trivial nebentypus.

For a nontrivial nebentypus `χ` the operator `𝒲_N` carries `S_k(N, χ)` to `S_k(N, χ⁻¹)`, and a
newform goes to a multiple of its conjugate form, not of itself. So the sign statement is
specific to trivial nebentypus.

## Main results

* `TauCeti.normalizedFrickeOperatorCusp_mem_cuspFormsNew`,
  `TauCeti.cuspFormsNew_map_normalizedFrickeOperatorCusp`: `𝒲_N` maps the new subspace onto
  itself.
* `TauCeti.commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace`: on `S_k(N, 1)`,
  `𝒲_N` commutes with `Tₙ` for every `n` prime to `N`.
* `TauCeti.exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew`: a nonzero
  form in the new part of `S_k(N, 1)` that is an eigenvector of every good `Tₚ` satisfies
  `𝒲_N f = ε • f` with `ε = 1` or `ε = -1`.
* `HeckeRing.GL2.Newform.frickeSign`: the canonical Fricke sign of a newform of trivial
  nebentypus, together with its eigenvalue equation and sign law.

## References

* A. O. L. Atkin and J. Lehner, *Hecke operators on `Γ₀(m)`*, Math. Ann. 185 (1970), 134–160.
* [T. Miyake, *Modular forms*][miyake1989], Theorem 4.6.15.
* [F. Diamond and J. Shurman, *A first course in modular forms*][diamondshurman2005], §5.10.
-/

public section

open Matrix Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup HeckeRing.GLn

open scoped MatrixGroups ModularForm

/-! ### `𝒲_N` preserves the new subspace -/

namespace TauCeti

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- **The normalized Fricke operator preserves the new subspace**: `𝒲_N` maps
`S_k(Γ₁(N))ⁿᵉʷ` into itself. -/
theorem normalizedFrickeOperatorCusp_mem_cuspFormsNew
    {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k} (hf : f ∈ cuspFormsNew N k) :
    normalizedFrickeOperatorCusp k f ∈ cuspFormsNew N k := by
  rw [cuspFormsNew_def] at hf ⊢
  exact normalizedFrickeOperatorCusp_mem_peterssonOrthogonal
    (fun _ hg ↦ normalizedFrickeOperatorCusp_mem_cuspFormsOld hg) hf

/-- **The normalized Fricke operator carries the new subspace onto itself.** -/
theorem cuspFormsNew_map_normalizedFrickeOperatorCusp (N : ℕ) [NeZero N] (k : ℤ) :
    (cuspFormsNew N k).map (normalizedFrickeOperatorCusp k) = cuspFormsNew N k := by
  refine le_antisymm (Submodule.map_le_iff_le_comap.mpr fun f hf ↦
    normalizedFrickeOperatorCusp_mem_cuspFormsNew hf) fun f hf ↦ ?_
  refine ⟨(-1 : ℂ) ^ k • normalizedFrickeOperatorCusp k f,
    Submodule.smul_mem _ _ (normalizedFrickeOperatorCusp_mem_cuspFormsNew hf), ?_⟩
  rw [map_smul, normalizedFrickeOperatorCusp_normalizedFrickeOperatorCusp_apply, smul_smul,
    ← mul_zpow, neg_one_mul, neg_neg, _root_.one_zpow, one_smul]

/-! ### `𝒲_N` commutes with the good Hecke operators on `S_k(N, 1)` -/

open HeckeRing.GL2

/-- **The normalized Fricke operator on the trivial-nebentypus space** `S_k(N, 1)`, as the
endomorphism obtained by specializing `normalizedFrickeCharCuspRestrict` to the trivial
character. -/
noncomputable def normalizedFrickeCharCuspOneEnd (k : ℤ) :
    Module.End ℂ (cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :=
  (normalizedFrickeOperatorCusp k).restrict fun _ hf ↦ by
    simpa using normalizedFrickeOperatorCusp_mem_cuspFormCharSpace k 1 hf

/-- On underlying cusp forms, `normalizedFrickeCharCuspOneEnd` is
`normalizedFrickeOperatorCusp`. -/
@[simp]
theorem coe_normalizedFrickeCharCuspOneEnd_apply
    (f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :
    ((normalizedFrickeCharCuspOneEnd k f : cuspFormCharSpace k 1) :
        CuspForm ((Gamma1 N).map (mapGL ℝ)) k) =
      normalizedFrickeOperatorCusp k (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) := by
  exact LinearMap.coe_restrict_apply _ _

/-- The slash sum of a double coset of determinant prime to `N` commutes with the Fricke slash
on a form of trivial nebentypus. This is the `Γ₀(N)` commutation read through the identification
`S_k(N, 1) ≃ S_k(Γ₀(N))`. -/
private lemma heckeSlashSum_slash_frickeGL
    {D : HeckeCoset (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ))}
    (hD : CoprimeDetCoset N N D) (f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)) :
    heckeSlashSum k D ⇑(f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∣[k] frickeGL ℝ N =
      heckeSlashSum k D (⇑(f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∣[k] frickeGL ℝ N) := by
  have h := congrArg DFunLike.coe (LinearMap.congr_fun
    (commute_atkinLehnerOperatorCusp_heckeSlashGamma0CuspFormEnd (NeZero.pos N) dvd_rfl
      isAtkinLehnerMatrix_fricke hD).eq (cuspFormCharSpaceOneEquiv N k f))
  simpa [coe_atkinLehnerOperatorCusp, atkinLehnerGL_fricke] using h

/-- `𝒲_N` commutes with the Hecke action of a single double coset of determinant prime to
`N`. -/
private lemma commute_normalizedFrickeCharCuspOneEnd_single
    {D : HeckeCoset (Delta0 N) ((Gamma0 N).map (mapGL ℚ)) ((Gamma0 N).map (mapGL ℚ))}
    (hD : CoprimeDetCoset N N D) (c : ℤ) :
    Commute (normalizedFrickeCharCuspOneEnd k)
      (heckeRingHomCuspCharSpace k 1 (HeckeCosetModule.single ℤ D c)) := by
  refine LinearMap.ext fun f ↦ ?_
  have key : normalizedFrickeCharCuspOneEnd k (twistedHeckeSlashCuspFormCharEnd k 1 D f) =
      twistedHeckeSlashCuspFormCharEnd k 1 D (normalizedFrickeCharCuspOneEnd k f) := by
    refine Subtype.ext (DFunLike.coe_injective ?_)
    simp only [coe_normalizedFrickeCharCuspOneEnd_apply, coe_normalizedFrickeOperatorCusp,
      coe_twistedHeckeSlashCuspFormCharEnd, twistedHeckeSlashSum_eq_heckeSlashSum]
    rw [heckeSlashSum_smul k D (det_rightCosetRep_pos_of_delta0 D),
      heckeSlashSum_slash_frickeGL hD f]
  simp [key]

/-- **The normalized Fricke operator commutes with the good Hecke operators on `S_k(N, 1)`**:
for `n` prime to `N`, `𝒲_N Tₙ = Tₙ 𝒲_N`. -/
theorem commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace {n : ℕ}
    (hn : Nat.Coprime n N) :
    Commute (normalizedFrickeCharCuspOneEnd k)
      (heckeRingHomCuspCharSpace k 1 (heckeTCompositeGamma0 N n)) :=
  commute_map_heckeTCompositeGamma0_of_forall_coprimeDetCoset N _ hn fun _ hD ↦
    commute_normalizedFrickeCharCuspOneEnd_single hD 1

/-! ### The Fricke sign -/

/-- **The Fricke sign**: a nonzero cusp form in the new part of
`S_k(N, 1)` that is an eigenvector of `Tₚ` at every prime `p ∤ N` is an eigenvector of the
normalized Fricke operator, with eigenvalue `1` or `-1`. -/
theorem exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew
    {f : cuspFormCharSpace k (1 : (ZMod N)ˣ →* ℂˣ)}
    (ha : ∀ p : ℕ, p.Prime → Nat.Coprime p N → ∃ c : ℂ,
      heckeRingHomCuspCharSpace k 1 (heckeTCompositeGamma0 N p) f = c • f)
    (hf : (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsNew N k)
    (hf0 : (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ≠ 0) :
    ∃ ε : ℂ, (ε = 1 ∨ ε = -1) ∧
      normalizedFrickeOperatorCusp k (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) =
        ε • (f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) := by
  -- `𝒲_N ∘ 𝒲_N = (-1) ^ k`, and `(-1) ^ k = 1` since `f ≠ 0` has trivial nebentypus
  have hk : (-1 : ℂ) ^ k = 1 := by
    simpa using (char_neg_one_of_mem_cuspFormCharSpace f.2 hf0).symm
  have hWW : normalizedFrickeCharCuspOneEnd k (normalizedFrickeCharCuspOneEnd k f) = f := by
    rw [Subtype.ext_iff, coe_normalizedFrickeCharCuspOneEnd_apply,
      coe_normalizedFrickeCharCuspOneEnd_apply,
      normalizedFrickeOperatorCusp_normalizedFrickeOperatorCusp_apply, hk, one_smul]
  -- so the multiplicity-one step for a commuting involution applies to `𝒲_N` on `S_k(N, 1)`
  obtain ⟨ε, hε, hWf⟩ := exists_eq_smul_of_commute_heckeRingHomCusp_of_mem_cuspFormsNew
    (fun _ _ hpN ↦ commute_normalizedFrickeCharCuspOneEnd_heckeRingHomCuspCharSpace hpN)
    (fun _ hg ↦ by
      rw [coe_normalizedFrickeCharCuspOneEnd_apply]
      exact normalizedFrickeOperatorCusp_mem_cuspFormsNew hg)
    ha hf hf0 hWW
  exact ⟨ε, hε, by rw [← coe_normalizedFrickeCharCuspOneEnd_apply, hWf, Submodule.coe_smul]⟩

end TauCeti

namespace HeckeRing.GL2

open TauCeti

variable {N : ℕ} [NeZero N] {k : ℤ}

/-- **The Fricke sign of a newform of trivial nebentypus**: `𝒲_N f = ε • f` with `ε = 1` or
`ε = -1`. -/
theorem Newform.exists_normalizedFrickeOperatorCusp_eq_smul (f : Newform N k) (hχ : f.χ = 1) :
    ∃ ε : ℂ, (ε = 1 ∨ ε = -1) ∧
      normalizedFrickeOperatorCusp k f.toCuspForm = ε • f.toCuspForm := by
  revert hχ
  obtain ⟨⟨F, χ, hmem, a, heig, hne⟩, hnew, -⟩ := f
  rintro rfl
  exact exists_normalizedFrickeOperatorCusp_eq_smul_of_mem_cuspFormsNew (f := ⟨F, hmem⟩)
    (fun p hp hpN ↦ ⟨a ⟨p, hp.pos⟩ hpN, heig ⟨p, hp.pos⟩ hpN⟩) hnew hne

/-- **The Fricke sign** `ε_N(f)` of a newform with trivial nebentypus. -/
noncomputable def Newform.frickeSign (f : Newform N k) (hχ : f.χ = 1) : ℂ :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose

/-- The normalized Fricke operator acts on a trivial-nebentypus newform by its Fricke sign. -/
theorem Newform.normalizedFrickeOperatorCusp_eq_frickeSign_smul
    (f : Newform N k) (hχ : f.χ = 1) :
    normalizedFrickeOperatorCusp k f.toCuspForm = f.frickeSign hχ • f.toCuspForm :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose_spec.2

/-- The Fricke sign of a trivial-nebentypus newform is `1` or `-1`. -/
theorem Newform.frickeSign_eq_one_or_neg_one (f : Newform N k) (hχ : f.χ = 1) :
    f.frickeSign hχ = 1 ∨ f.frickeSign hχ = -1 :=
  (f.exists_normalizedFrickeOperatorCusp_eq_smul hχ).choose_spec.1

/-- A scalar satisfying the normalized Fricke eigenvalue equation is the Fricke sign. -/
theorem Newform.frickeSign_eq_of_normalizedFrickeOperatorCusp_eq_smul
    (f : Newform N k) (hχ : f.χ = 1) {ε : ℂ}
    (hε : normalizedFrickeOperatorCusp k f.toCuspForm = ε • f.toCuspForm) :
    f.frickeSign hχ = ε :=
  smul_left_injective ℂ f.ne_zero
    ((f.normalizedFrickeOperatorCusp_eq_frickeSign_smul hχ).symm.trans hε)

end HeckeRing.GL2
