/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ModularForms.HeckeSlash.Degeneracy
public import TauCeti.NumberTheory.ModularForms.HeckeSlash.Nebentypus.Prime.Basic
public import TauCeti.NumberTheory.ModularForms.Newforms.Basic
import TauCeti.NumberTheory.ModularForms.Petersson.Hecke

/-!
# Hecke stability of the old and new subspaces

The old subspace of `S_k(Γ₁(N))` is stable under the Hecke operator `Tₚ` at every prime `p`,
and the new subspace is stable under `Tₚ` for `p` coprime to the level.

The old subspace is generated by the level-raises `V_d g` of cusp forms `g` of proper divisor
level `M`, so stability is exactly the statement that `Tₚ` carries each such generator back into
the subspace; the elimination rule `cuspFormsOld_le` turns that generator-wise statement into the
stability of the whole subspace. For `p` coprime to `N` the generator statement is
`heckeTCuspNat_levelRaise`: `Tₚ` commutes with `V_d`. For `p ∣ N` the operator `Tₚ` at level `N`
is `Uₚ`, reading off the coefficients `a_{p m}`, and it no longer commutes with `V_d`; instead
`Tₚ (V_d g)` is computed on `q`-expansions (`HeckeSlash/Degeneracy.lean`) as `V_{d/p} g` when
`p ∣ d`, as `V_d (Tₚ g)` when `p ∤ d` and `p ∣ M`, and as
`V_d (Tₚ g) - p ^ (k - 1) • V_{d p} (⟨p⟩ g)` when `p ∤ d M`, each an old form.

This mirrors the diamond half, `diamondOpCusp_mem_cuspFormsOld`, which is proved from
`CuspForm.diamondOpCusp_levelRaise`. Together they say the old subspace is stable under every
`Tₚ` and every diamond operator.

The new subspace is the Petersson-orthogonal complement of the old subspace. For `p` coprime to
`N` its stability follows from the old-space stability, because the Petersson adjoint of `Tₚ` is
`⟨p⟩⁻¹ Tₚ` there. It is the invariant-subspace input for restricting the simultaneous good-Hecke
diagonalization to the newspace. The stability of both old and new subspaces under every Hecke
operator is Diamond–Shurman, *A First Course in Modular Forms*, Proposition 5.6.2; at `p ∣ N`
the old-space half is proved here and the new-space half is not, since the adjoint of `Uₚ` is not
a multiple of `Uₚ`.

Both stability statements also hold for the Hecke-ring *generator*
`heckeTGeneratorGamma0 N p`, acting on a character space — the form eigenform
arguments need, since eigen-ness of an `EigenformAwayFromLevel` is stated for
`heckeRingHomCuspCharSpace` rather than for `heckeTCuspNat`. No separate argument is required:
at a prime the two operators agree on `S_k(N, χ)`
(`HeckeRing.GL2.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0`). Nothing here is claimed
for a general element of the ring; the generators at primes are what the eigenform arguments
use, and stability for the subring they generate would need the products handled too.

## Main results

* `TauCeti.heckeTCuspNat_mem_cuspFormsOld`: `Tₚ` maps the old subspace into itself, for every
  prime `p`.
* `TauCeti.cuspFormsOld_map_heckeTCuspNat_le`: the same in `Submodule.map` form.
* `TauCeti.heckeTCuspNat_mem_cuspFormsNew`: `Tₚ` maps the new subspace into itself, for `p`
  prime and coprime to `N`, with `TauCeti.cuspFormsNew_map_heckeTCuspNat_le` as its
  `Submodule.map` form.
* `TauCeti.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsOld`: the same
  old-space stability, for the Hecke-ring generator at a prime acting on `S_k(N, χ)`, and
  `TauCeti.cuspFormsOld_comap_map_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_le` in
  `Submodule.map` form.
* `TauCeti.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsNew`: the
  corresponding newspace stability on `S_k(N, χ)` at a good prime, and
  `TauCeti.cuspFormsNew_comap_map_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_le` in
  `Submodule.map` form.
-/

public section

open Matrix.SpecialLinearGroup UpperHalfPlane CongruenceSubgroup

open scoped MatrixGroups ModularForm

namespace TauCeti

variable {k : ℤ} {N p : ℕ}

/-! ### The old subspace -/

/-- **The old subspace is Hecke-stable** at every prime `p`: `Tₚ` maps `S_k(Γ₁(N))ᵒˡᵈ` into
itself, whether or not `p` divides the level. At `p ∣ N` this is the old-space half of
Diamond–Shurman's Proposition 5.6.2 for the operator `Uₚ = Tₚ`. -/
theorem heckeTCuspNat_mem_cuspFormsOld [NeZero N] (hp : p.Prime)
    {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k} (hf : f ∈ cuspFormsOld N k) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    HeckeRing.GL2.heckeTCuspNat k p f ∈ cuspFormsOld N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  refine cuspFormsOld_le (V := (cuspFormsOld N k).comap (HeckeRing.GL2.heckeTCuspNat k p)) ?_ hf
  intro M d hdvd hM g
  have : NeZero M := NeZero.of_dvd (dvd_of_mul_left_dvd hdvd)
  rw [Submodule.mem_comap]
  -- In each case `Tₚ (V_d g)` is a combination of level-raises from the level `M`.
  by_cases hpN : Nat.Coprime p N
  · -- a good prime: `Tₚ (V_d g) = V_d (Tₚ g)`
    rw [HeckeRing.GL2.heckeTCuspNat_levelRaise k hdvd hp hpN]
    exact levelRaise_mem_cuspFormsOld hdvd hM k _
  by_cases hpd : p ∣ d
  · -- `d = p e`: `Tₚ (V_{p e} g) = V_e g`
    obtain ⟨e, rfl⟩ := hpd
    rw [HeckeRing.GL2.heckeTCuspNat_levelRaise_mul k hdvd]
    exact levelRaise_mem_cuspFormsOld ((mul_dvd_mul_right (dvd_mul_left e p) M).trans hdvd) hM k g
  have hpd' : Nat.Coprime p d := (Nat.Prime.coprime_iff_not_dvd hp).2 hpd
  by_cases hpM : p ∣ M
  · -- `p ∤ d`, `p ∣ M`: `Tₚ (V_d g) = V_d (Tₚ g)`, with `Tₚ = Uₚ` at both levels
    have hpM' : p.primeFactors ⊆ M.primeFactors := by
      rw [hp.primeFactors]
      exact Finset.singleton_subset_iff.2
        (Nat.mem_primeFactors.2 ⟨hp, hpM, NeZero.ne M⟩)
    rw [HeckeRing.GL2.heckeTCuspNat_levelRaise_of_primeFactors_subset k hdvd hpM' hpd']
    exact levelRaise_mem_cuspFormsOld hdvd hM k _
  -- `p ∤ d M`, `p ∣ N`: `Tₚ (V_d g) = V_d (Tₚ g) - p ^ (k - 1) • V_{d p} (⟨p⟩ g)`
  have hpdM : Nat.Coprime p (d * M) :=
    Nat.Coprime.mul_right hpd' ((Nat.Prime.coprime_iff_not_dvd hp).2 hpM)
  have hdpM : d * p * M ∣ N := by
    rw [mul_right_comm, mul_comm]
    exact hpdM.mul_dvd_of_dvd_of_dvd ((Nat.Prime.dvd_iff_not_coprime hp).2 hpN) hdvd
  rw [HeckeRing.GL2.heckeTCuspNat_levelRaise_eq_sub k hp hpd' hdpM]
  exact sub_mem (levelRaise_mem_cuspFormsOld hdvd hM k _)
    (Submodule.smul_mem _ _ (levelRaise_mem_cuspFormsOld hdpM hM k _))

/-- **The old part of `S_k(N, χ)` is stable under the Hecke-ring generator at a prime**, in
the form eigenform arguments need it: `heckeTGeneratorGamma0 N p` acting on the character space
carries an old form to an old form. At a prime that action *is* the classical `Tₚ`
(`HeckeRing.GL2.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0`), so this is
`heckeTCuspNat_mem_cuspFormsOld` read through that identification. -/
theorem coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsOld [NeZero N]
    {χ : (ZMod N)ˣ →* ℂˣ} (hp : p.Prime)
    {F : cuspFormCharSpace k χ}
    (hF : (F : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsOld N k) :
    (HeckeRing.GL2.heckeRingHomCuspCharSpace k χ (HeckeRing.GL2.heckeTGeneratorGamma0 N p) F :
        CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsOld N k := by
  rw [HeckeRing.GL2.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0 k χ hp]
  exact heckeTCuspNat_mem_cuspFormsOld hp hF

/-- **The same stability in `Submodule.map` form**: the Hecke-ring generator at a prime
carries the preimage of `cuspFormsOld` in the character space into itself. The counterpart of
`cuspFormsOld_map_heckeTCuspNat_le` for that generator; the old subspace is pulled back along the
inclusion because the action is on `cuspFormCharSpace`, not on all of `S_k(Γ₁(N))`. -/
theorem cuspFormsOld_comap_map_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_le [NeZero N]
    (χ : (ZMod N)ˣ →* ℂˣ) (hp : p.Prime) (k : ℤ) :
    ((cuspFormsOld N k).comap (cuspFormCharSpace k χ).subtype).map
        (HeckeRing.GL2.heckeRingHomCuspCharSpace k χ
          (HeckeRing.GL2.heckeTGeneratorGamma0 N p)) ≤
      (cuspFormsOld N k).comap (cuspFormCharSpace k χ).subtype := by
  rw [Submodule.map_le_iff_le_comap]
  exact fun F hF ↦
    coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsOld hp hF

/-- The old subspace is Hecke-stable at every prime, in the `Submodule.map` form. -/
theorem cuspFormsOld_map_heckeTCuspNat_le [NeZero N] (hp : p.Prime) (k : ℤ) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    (cuspFormsOld N k).map (HeckeRing.GL2.heckeTCuspNat k p) ≤ cuspFormsOld N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  rw [Submodule.map_le_iff_le_comap]
  exact fun _ hf ↦ heckeTCuspNat_mem_cuspFormsOld hp hf

/-! ### The new subspace -/

/-- **The new subspace is Hecke-stable** at a prime `p` coprime to the level: `Tₚ` maps
`S_k(Γ₁(N))ⁿᵉᵂ` into itself. -/
theorem heckeTCuspNat_mem_cuspFormsNew [NeZero N] (hp : p.Prime)
    (hpN : Nat.Coprime p N) {f : CuspForm ((Gamma1 N).map (mapGL ℝ)) k}
    (hf : f ∈ cuspFormsNew N k) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    HeckeRing.GL2.heckeTCuspNat k p f ∈ cuspFormsNew N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  rw [cuspFormsNew_def] at hf ⊢
  exact CuspForm.map_mem_peterssonOrthogonal
    (HeckeRing.GL2.peterssonInnerCosets_heckeTCuspNat_left k hpN)
    (fun g hg ↦ diamondOpCusp_mem_cuspFormsOld _
      (heckeTCuspNat_mem_cuspFormsOld hp hg)) hf

/-- **The new part of `S_k(N, χ)` is stable under the Hecke-ring generator at a good
prime.** This is the fixed-nebentypus form used to restrict the simultaneous good-Hecke
diagonalization to the newspace. -/
theorem coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsNew [NeZero N]
    {χ : (ZMod N)ˣ →* ℂˣ} (hp : p.Prime) (hpN : Nat.Coprime p N)
    {F : cuspFormCharSpace k χ}
    (hF : (F : CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsNew N k) :
    (HeckeRing.GL2.heckeRingHomCuspCharSpace k χ (HeckeRing.GL2.heckeTGeneratorGamma0 N p) F :
        CuspForm ((Gamma1 N).map (mapGL ℝ)) k) ∈ cuspFormsNew N k := by
  rw [HeckeRing.GL2.coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0 k χ hp]
  exact heckeTCuspNat_mem_cuspFormsNew hp hpN hF

/-- **The fixed-nebentypus newspace is stable under a good prime Hecke generator**, in
`Submodule.map` form. The newspace is pulled back along the inclusion because the Hecke-ring
action is on `cuspFormCharSpace`, not on all of `S_k(Γ₁(N))`. -/
theorem cuspFormsNew_comap_map_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_le [NeZero N]
    (χ : (ZMod N)ˣ →* ℂˣ) (hp : p.Prime) (hpN : Nat.Coprime p N) (k : ℤ) :
    ((cuspFormsNew N k).comap (cuspFormCharSpace k χ).subtype).map
        (HeckeRing.GL2.heckeRingHomCuspCharSpace k χ
          (HeckeRing.GL2.heckeTGeneratorGamma0 N p)) ≤
      (cuspFormsNew N k).comap (cuspFormCharSpace k χ).subtype := by
  rw [Submodule.map_le_iff_le_comap]
  exact fun F hF ↦
    coe_heckeRingHomCuspCharSpace_heckeTGeneratorGamma0_mem_cuspFormsNew hp hpN hF

/-- The new subspace is Hecke-stable, in the `Submodule.map` form. -/
theorem cuspFormsNew_map_heckeTCuspNat_le [NeZero N] (hp : p.Prime)
    (hpN : Nat.Coprime p N) (k : ℤ) :
    haveI : NeZero p := ⟨hp.ne_zero⟩
    (cuspFormsNew N k).map (HeckeRing.GL2.heckeTCuspNat k p) ≤ cuspFormsNew N k := by
  have : NeZero p := ⟨hp.ne_zero⟩
  rw [Submodule.map_le_iff_le_comap]
  exact fun _ hf ↦ heckeTCuspNat_mem_cuspFormsNew hp hpN hf

end TauCeti
