/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.FiniteDimensional.Defs
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Homogeneous
public import TauCeti.Algebra.WordFiltration.Noetherian
public import TauCeti.LinearAlgebra.SymmetricAlgebra.Noetherian

/-!
# The enveloping algebra of a finite Lie algebra over a Noetherian ring is Noetherian

A universal enveloping algebra need not be commutative -- it is when `L` is abelian, but not in
general -- so the Hilbert basis theorem does not apply to it directly; what is always commutative is
the associated graded of its PBW filtration. This file runs that comparison. The PBW filtration is
the word filtration generated by the canonical Lie map `UniversalEnvelopingAlgebra.ι R`, and it is
exhaustive (`TauCeti.UniversalEnvelopingAlgebra.iSup_pbwFiltration_eq_top`), so the
filtered-to-graded transfer of `TauCeti/Algebra/WordFiltration/Noetherian.lean` applies to it
verbatim: `U(L)` is left Noetherian as soon as `gr U(L)` is.

The graded side needs no Poincaré--Birkhoff--Witt theorem, only its easy half. The canonical map
`TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap` from the symmetric algebra `Sym(L)` to
`gr U(L)` is surjective for every Lie algebra over every commutative ring
(`TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap_surjective`) -- injectivity, the hard
half, is what needs `L` free -- and `Sym(L)` is Noetherian whenever `R` is Noetherian and `L` is
module-finite (`TauCeti.SymmetricAlgebra.instIsNoetherianRing`). So `gr U(L)` is a quotient of a
Noetherian ring, hence Noetherian, and the transfer carries that down to `U(L)`.

The hypotheses are therefore `R` Noetherian and `L` finite as an `R`-module, with no field, no
freeness and no abelianness. Over a field this specializes to the Poincaré--Birkhoff--Witt
corollary that the enveloping algebra of a finite-dimensional Lie algebra is Noetherian
(`TauCeti.UniversalEnvelopingAlgebra.isNoetherianRing_universalEnvelopingAlgebra`). Only left ideals
are treated, matching Mathlib's `IsNoetherianRing`; the right-handed statement is the same theorem
read in the opposite algebra and is not proved here.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.instIsNoetherianRingPBWAssociatedGraded`: the PBW associated
  graded is Noetherian, being a quotient of the symmetric algebra.
* `TauCeti.UniversalEnvelopingAlgebra.isNoetherianRing_of_isNoetherianRing_pbwAssociatedGraded`:
  `U(L)` is Noetherian as soon as `gr U(L)` is.
* `TauCeti.UniversalEnvelopingAlgebra.instIsNoetherianRing`: **the enveloping algebra of a Lie
  algebra finite over a Noetherian commutative ring is left Noetherian.**
* `TauCeti.UniversalEnvelopingAlgebra.isNoetherianRing_universalEnvelopingAlgebra`: the same
  statement for a finite-dimensional Lie algebra over a field.

## References

* J. Dixmier, *Enveloping Algebras*, AMS GSM 11 (1996), §2.3.
* J. C. McConnell and J. C. Robson, *Noncommutative Noetherian Rings*, Wiley (1987), §1.6.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

attribute [local instance 100] LieRing.ofAssociativeRing

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

/-- **The PBW associated graded of a module-finite Lie algebra over a Noetherian ring is
Noetherian**: it is a quotient of the symmetric algebra `Sym(L)` by
`TauCeti.UniversalEnvelopingAlgebra.pbwAssociatedGradedMap_surjective`, and that symmetric algebra
is Noetherian. -/
instance instIsNoetherianRingPBWAssociatedGraded [IsNoetherianRing R] [Module.Finite R L] :
    IsNoetherianRing (PBWAssociatedGraded R L) :=
  isNoetherianRing_of_surjective (SymmetricAlgebra R L) (PBWAssociatedGraded R L)
    (pbwAssociatedGradedMap R L).toRingHom (pbwAssociatedGradedMap_surjective R L)

/-- **The enveloping algebra is left Noetherian as soon as its PBW associated graded is.** -/
theorem isNoetherianRing_of_isNoetherianRing_pbwAssociatedGraded
    [IsNoetherianRing (PBWAssociatedGraded R L)] : IsNoetherianRing U :=
  TauCeti.Algebra.wordFiltration.isNoetherianRing_of_isNoetherianRing_associatedGraded
    (_root_.UniversalEnvelopingAlgebra.ι R (L := L)).toLinearMap
    fun a => by simpa only [pbwFiltration_def] using exists_mem_pbwFiltration R L a

/-- **The enveloping algebra of a Lie algebra finite over a Noetherian commutative ring is left
Noetherian.** -/
instance instIsNoetherianRing [IsNoetherianRing R] [Module.Finite R L] : IsNoetherianRing U :=
  isNoetherianRing_of_isNoetherianRing_pbwAssociatedGraded R L

/-- **The enveloping algebra of a finite-dimensional Lie algebra over a field is left Noetherian**,
the Poincaré--Birkhoff--Witt corollary. This is the classical form of
`TauCeti.UniversalEnvelopingAlgebra.instIsNoetherianRing`; no freeness hypothesis appears, a
finite-dimensional vector space being automatically free. -/
theorem isNoetherianRing_universalEnvelopingAlgebra (K : Type u) (L : Type v) [Field K] [LieRing L]
    [LieAlgebra K L] [FiniteDimensional K L] :
    IsNoetherianRing (_root_.UniversalEnvelopingAlgebra K L) :=
  inferInstance

end TauCeti.UniversalEnvelopingAlgebra
